### ISSUE TITLE
n-Viterbi

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#2013]
http://www.openwall.com/lists/john-dev/2015/10/16/3

_n-Viterbi is an extension of the Viterbi algorithm:_

https://en.wikipedia.org/wiki/Viterbi_algorithm

_As far as I'm aware, this extension was first introduced in "Timing Analysis of Keystrokes and Timing Attacks on SSH" by Dawn Song et al:_

http://users.ece.cmu.edu/~dawnsong/papers/ssh-timing.pdf

_As I tweeted a couple of years ago:_

_@dawnsongtweets How about finally releasing the n-Viterbi code for your "Timing Analysis of Keystrokes and Timing Attacks on SSH"?_
_@dawnsongtweets As discussed in 2001, I am not convinced n-Viterbi gives all answers and exactly in decreasing order of probabilities_
_@dawnsongtweets However, if n-Viterbi actually does that and isn't more complex than what the paper says, it has many other applications_
_I did try (re)implementing n-Viterbi from the English description at the time. It'd skip some answers and the order would be suboptimal._

_(I guess I should have pinged Dawn Song via e-mail again, as she didn't proceed to tweet much.  I think she just got on Twitter at the time.)_

_Good news: @mitar_m has just found what looks like an implementation of n-Viterbi, here:_

https://github.com/edechter/PRISM/blob/master/src/c/up/viterbi.c

_it's the compute_n_max() function, as called from:_

https://github.com/edechter/PRISM/blob/master/src/c/up/mcmc_predict.c

``` c
    /* Compute the candidates Es for reranking by n-Viterbi */
    compute_n_max(n);
```

_Other source files/functions in that directory also look relevant (at first glance; to be confirmed)._

_Is anyone willing to give this a try, for a potential new cracking mode for JtR?  Potentially, this would replace incremental or Markov modes' suboptimal ordering with the most optimal ordering that can be inferred from the available statistics (overfitting is a risk, though). My experiments in 2001 didn't result in an algorithm that would behave as well as the paper claimed it should (Viterbi finds one most probable candidate easily, but then it's tricky for the 2nd most probable and on), but maybe it was just me, and maybe the implementation above is actually it.  I think this is worth a try.  Unfortunately, I don't have time for it right now._

**Comment by solardiz** [comment]
Maybe more and simpler implementations:

https://github.com/carthach/kBestViterbi (Python)
https://github.com/meerkat-cv/top_n_viterbi (C++)

**Comment by solardiz** [comment]
I read up on this for https://www.openwall.com/presentations/OffensiveCon2024-Password-Cracking/ slides 68-71. Apparently, the algorithm in our Markov mode is actually very similar, and according to the OMEN paper its "indexing [is not] in order of decreasing probability." OMEN works around that: "our algorithm discretizes all probabilities into a number of bins, and iterates over all those bins in order of decreasing likelihood."

Maybe n-Viterbi isn't a silver bullet (although I'm not sure if different implementation authors refer to the same thing by that name), and maybe what OMEN did is the best we can do - or/and maybe try a variation of incremental mode with Markov chain settings similar to OMEN's (so 4-grams, but no per-position nor per-length).

**Comment by solardiz** [comment]
This was labeled "new cracking mode", but I think this issue isn't actually actionable now. We know there's room for further research and experimentation, and we have a collection of relevant links here, but there's no need to track this as an issue.
