### ISSUE TITLE
Use dlopen for OpenCL

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#2133]
This would take a bit of initial work but in the end you could run an OpenCL build on a machine lacking OpenCL libs. Hashkill does this. This would be great for dists. See #2118.

We already use dlopen for GPU fan/temp support.

**Comment by magnumripper** [comment]
Here a cool idea from @claudioandre in #2118 
> ```
if dlopen("opencl_lib")
   exec("/regular/opencl_build/JtR")
else
   'Go-on and use this non-opencl build
```
I'm pretty sure that would work just fine.

**Comment by crioux** [comment]
On Windows on the jtrdll branch I use this on the linker line:
```
/DELAYLOAD:"OpenCL.DLL"
```
to do lazy binding, it just works. There may be a similar linking option for Unix OS's.

**Comment by crioux** [comment]
per this, it's 
```-z lazy
```
http://linux.die.net/man/1/ld

**Comment by crioux** [comment]
Actually, i'm dumb that doesn't work if the library doesn't exist.

**Comment by crioux** [comment]
Yea, it would appear dlopen is the only portable way to do this.

**Comment by jfoug** [comment]
dlopen likely does not work (Or does it?) in cygwin (i.e. windows).

**Comment by crioux** [comment]
dlopen works fine in cygwin (it calls through to loadlibrary)
In windows, LoadLibrary/GetProcAddress is the way.

**Comment by solardiz** [comment]
This has been implemented.
