### ISSUE TITLE
rar-opencl and md5crypt-opencl failing on AMD R9 390 w/ Crimson 15.12

### ISSUE THREAD

**Issue by virdiignis** [openwall/john#2283]
Hi.
I was trying to crack rar archive password ($RAR3$_1_ type) with John today, but I've encountered errors.
The exact error was "Self test failed (cmp_all(1))" while running with hash. This is what john --test=0 showed:
[test.txt](https://github.com/magnumripper/JohnTheRipper/files/482846/test.txt)
My graphics card is Gigabyte R9 390, OS: Arch Linux (kernel 4.7.4), Crimson 15.12

**Comment by virdiignis** [comment]
Also, when I commented out 
`/*if (where) {
				fprintf(stderr, "Self test failed (%s)\n",
				    where);
				error();
			}*/`

in john.c
and
`if (db->loaded && db->format->methods.reset == fmt_default_reset)
	if ((where = fmt_self_test(db->format, db))) {
		log_event("! Self test failed (%s)", where);
		fprintf(stderr, "Self test failed (%s)\n", where);
		error();
	}`
in cracker.c
it seems to be working.

**Comment by claudioandre** [comment]
You are cheating :smile:

**Comment by claudioandre** [comment]
Well, just a note: once upon a time, I tried 15.12 and gave up. It wasn't good enough. 
* I was able to trigger new driver bugs; 
  * bugs/errors not seen in 15.7 or 15.9 (the recommend/supported versions).

**Comment by virdiignis** [comment]
Sorry for cheating :P Anyway, maybe I'll try out 15.9. I always use 15.12 as this is in AUR as catalyst-test, and didn't think of "-test" being the problem.

**Comment by magnumripper** [comment]
When you say "seems to be working", do you mean that it actually cracks test hashes correctly?

A much easier way of skipping self-tests is the option `--skip-self-tests` but it's obviously better to try finding a driver that's less buggy. If it fails self-tests it may just as well give you false negatives.

**Comment by magnumripper** [comment]
BTW Hashcat recommends "AMD drivers 14.9 or later (recommended 15.12 exact)" so we should probably try to work around any bugs in 15.12.

**Comment by virdiignis** [comment]
No, it doesn't crack correctly, I haven't checked that ealier. But GPU's getting loaded and hot, so it does something.

**Comment by mirh** [comment]
Vi0L0 did some CL cleaning last winter. 
Is this working now?

**Comment by solardiz** [comment]
I revised md5crypt-opencl significantly in 2019 (including addition of a workaround for an amdgpu-pro bug, which did help there), so at least that part of this 2016 issue is stale and would need re-testing. We also don't know the current status of rar-opencl with that driver, and in general we accept that various ones of our OpenCL formats fail self-test with various AMD drivers (things are much more stable on NVIDIA). So I'll close this issue now.

@virdiignis If you can/care to retest, please feel free to add comments to this issue. If the problem is still present and relevant, we can reopen. Thanks.

**Comment by solardiz** [comment]
BTW, these two are currently _not_ among failing formats with recent amdgpu-pro on R9 390, see https://github.com/openwall/john/issues/3610#issuecomment-982652301. So you definitely can use these two formats on this hardware now. We just don't know about the old Crimson driver.

**Comment by solardiz** [comment]
See also #4670 where we reduced the number of failing formats with the old AMD Catalyst from 22 to 13 or 11 (on different devices). Crimson is probably similar.
