### ISSUE TITLE
Transfer this repo to "Openwall" org

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#2667]
Taken here from https://github.com/magnumripper/JohnTheRipper/issues/2600#issuecomment-322064644:
> Maybe is it time to create the Openwall organization and have a more granular control?

I'm not really familiar with orgs at GitHub but I like the idea (I'd leave ultimate control to @solardiz yet I could stay at my current role for now). What would be the pros and cons? What more functionality would we get? Is there a cost involved?

**Comment by claudioandre** [comment]
* Free plan, unlimited public repositories
What OSS projects need.

* Flexible repository access
You can add repositories to your teams with more flexible levels of access (Admin, Write, Read).

* Request to join teams
Members can quickly request to join any team. An owner or team maintainer can approve the request.

* Seamless communication with teams
Teams are a great way for groups of people to communicate and work on code together. 

* Team mentions
 You can mention the entire team.

**Comment by solardiz** [comment]
While at it, we may also transfer to @Openwall GitHub account. IIRC, Shinnok created that one and offered to give it to me, but I postponed that discussion. Maybe now is the time. Would we be able to preserve all the issue discussions, wiki, etc. if we do that?

**Comment by magnumripper** [comment]
> Would we be able to preserve all the issue discussions, wiki, etc. if we do that?

Good question.

Also, all old links (from john-users ML etc.) starting with "github.com/magnumripper" would become outdated (unless they have some means to redirect). On the other hand, my repo would almost always be updated and in par with the new origin.

**Comment by claudioandre** [comment]
> Would we be able to preserve all the issue discussions, wiki, etc. if we do that?

> my repo would almost always be updated and on par with the new origin.

I expect to use the "Transfer ownership" to do "solve" the issue: it means transfer (all) the repository (wiki, issues, ...) to another user or to an organization where magnum has the ability to create repositories.
* After that, magnum will have to create a fork and rebase frequently to keep github/magnumripper somehow updated; and to keep old stuff (from john-users ML etc.) still valid.

**Comment by magnumripper** [comment]
OK so just FTR I'm totally willing to do this - but I don't care enough that I will dig much further into it on my own. Things are pretty fine as is, except that if I get hit by a truck it will be too late to transfer.

**Comment by shinnok** [comment]
@solardiz @magnumripper Hi! Just checked and yes, I still own the https://github.com/openwall account. I think I can easily transfer to you by assigning your e-mail to it. Let me know via e-mail which one I should use.

**Comment by rofl0r** [comment]
just FYI: when a repo gets moved, the old links will automatically be redirected to the new destination. (for example i moved https://github.com/rofl0r/sabotage to https://github.com/sabotage-linux/sabotage and the links still work). i'm not sure though what happens with issues.

**Comment by solardiz** [comment]
This has been taken care of.
