### ISSUE TITLE
Items needing added to configure checks

### ISSUE THREAD

**Issue by jfoug** [openwall/john#2850]
- [ ] lib lzma
- [ ] lib lzma2
- [x] header inttypes.h

Getting VC back up.  These checks needed added

libs:     lzma    lzma2
Both of those are used in 7z.  I put a for msc_ver and have the code commented out, and return true. The ST pass, but I am not sure this is correct. It may be that if either of those libs are not found, that the full 7z format is simply complied out.

headers:    inttypes.h
This appears to be used a lot in zip formats.  ONLY thing used is PRIx64 and PRIu64 defines.  The include is in a couple of headers.  We could use our own "inttypes.h" or add code wrapping the calls to this in the few headers which it is found to handle things properly if the inittypes.h header is not part of the system.

NOTE, there already is HAVE_INTTYPES_H in the configure script, so all we need to do is add proper code into the few header files to be able to deal with systems without <inttypes.h>.

**Comment by jfoug** [comment]
This I think is all that is needed to be added for the inttypes.h   NOTE, there is an ancillary file using this header also, but I have not made any changes there.

```diff
diff --git a/src/jumbo.h b/src/jumbo.h
index 7f968625f..59883db66 100644
--- a/src/jumbo.h
+++ b/src/jumbo.h
@@ -40,7 +40,12 @@

 #include <stdint.h>
 #define __STDC_FORMAT_MACROS
+#if (AC_BUILT && HAVE_INTTYPES_H) && ! defined(_MSC_VER)
 #include <inttypes.h>
+#else
+#define PRIx64    "llx"
+#define PRIu64    "llu"
+#endif
```

**Comment by jfoug** [comment]
This change was added at  136a3e8c1  since this was a pretty big change needed for VC (i.e. the VC port).

**Comment by jfoug** [comment]
Ok, I feel good now.  The new method finds the exact same salt-pw list.  It did have a few duplicates. I think there were dupes when I shut things down before the first run block completed, and then started it again with a different OMP level.  BUT i the end, all salt-pw pairs were processed

```
$ wc full-x-run
 290004  870012 9570132 full-x-run

$ wc part-x*
  22272   66816  734976 part-x0-run
   6792   20376  224136 part-x1-run
  17292   51876  570636 part-x2-run
  31008   93024 1023264 part-x3-run
 213900  641700 7058700 part-x4-run
 291264  873792 9611712 total                     (Note, count a bit high here)

$ cat part-x* | sort > p

$ cat p | uniq | wc
 290004  870012 9570132   (after uniq, the count matches exactly)
```

**Comment by solardiz** [comment]
The `inttypes.h` issue has been taken care of, and I don't understand the lzma issue - we already had a copy of the lzma code in this tree before this issue was opened, so why would we be checking for lzma via `configure`?

I'm closing this now.
