### ISSUE TITLE
Code cleanup ideas

### ISSUE THREAD

**Issue by kholia** [openwall/john#3001]
Here are a couple of ideas regarding code cleanup,

* Lot of formats include `assert.h`, `errno`, and `ctype.h` headers. I don't think that these headers are required in a large majority of the formats.

* Use @solardiz's approach to using OpenMP properly. Use `tacacs_plus_fmt_plug.c` as a template for other formats.

Thoughts?

**Comment by jfoug** [comment]
What about this format?  The ```#pragma omp parallel for``` not capturing the for loop?    Note all (many) for loops OMP blocks looked like that previously, but magnum changed them to capture the for within the #if clause (for optimization reason??)   Same logic was used in the cmp_all() of these formats.

**Comment by magnumripper** [comment]
The latest recommendations for OMP IIRC are:
- We don't multiply with OMP_SCALE unless number of threads is actually > 1
- We tune MAX_KEYS_PER_CRYPT first, then OMP_SCALE. Many formats have MAX_KEYS_PER_CRYPT==1 and a too large OMP_SCALE.

@kholia what about errno is it that needs a change? Did you mean sourcing errno.h for no reason? And same with assert.h and ctype.h I guess?

**Comment by kholia** [comment]
> Did you mean sourcing errno.h for no reason? And same with assert.h and ctype.h I guess?

Yes, exactly that. Sourcing these files for no reason.

**Comment by kholia** [comment]
@jfoug I will take that into account too when fixing the formats. Thanks!

**Comment by kholia** [comment]
Regarding the incorrect OpenMP usage,

```
$ grep -Rin "pragma omp parallel" -A 1 | tee ~/log.txt | grep -v "endif"
...
<lot here>
eigrp_fmt_plug.c:276:#pragma omp parallel for
eigrp_fmt_plug.c-277-	for (index = 0; index < count; index++)
...
skein_fmt_plug.c:208:#pragma omp parallel for
skein_fmt_plug.c-209-	for (index = 0; index < count; index++)
```

I could use a better grep hack ;)

Note: We want to find code patterns which deviate from the following standard construction,

```
#ifdef _OPENMP
#pragma omp parallel for
#endif
```

Hopefully, my understanding regarding the correct OpenMP constructions is OK. It has been a while.

**Comment by kholia** [comment]
NOTE: There are many actionable items mentioned by @solardiz in https://github.com/magnumripper/JohnTheRipper/pull/3029.

**Comment by solardiz** [comment]
I don't find the tiny subset of possible yet still unimplemented code cleanups described in comments here worth tracking separately.
