### ISSUE TITLE
Add support for Karbowanec wallets

### ISSUE THREAD

**Issue by kholia** [openwall/john#3158]
References,

* https://github.com/seredat/karbowanecwallet

* https://github.com/seredat/karbowanec/tree/master/src/WalletLegacy

* Issue https://github.com/magnumripper/JohnTheRipper/issues/3144 (for Monero wallets)

Karbowanec wallets use the older `WalletLegacy` code.

Look at `WalletLegacy::initAndLoad` funtion from `cryptonote/src/WalletLegacy/WalletLegacy.cpp`. Next, look at `WalletLegacySerializer::deserialize` from `WalletLegacy/WalletLegacySerializer.cpp` file.

The amount of decrypted data can be huge. I haven't found a `password verifier mechanism` yet.

**Comment by kholia** [comment]
Wallet format for `WalletLegacy`,

* Version -> bytes[0]

* IV -> bytes[1:9]

* Data -> bytes[12:]

**Comment by solardiz** [comment]
This one wallet looks too obscure to me, although supporting the whole ecosystem of forks from the same codebase could make sense if requested by anyone. Dhiru's notes in here may be useful, but without his intent to proceed with implementation himself I don't expect anyone would. Closing as not planned for now.
