### ISSUE TITLE
bash completion needs adjustments

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#3514]
* `--test-full=LEVEL` is missing
* `--rules-stack=` is missing
* `--rules=` expansion is now broken
* `--single-seed=` and `--single-wordlist=` similarly broke `--single=` expansion

Ideally some general logic fix can solve most of this. Jumbo's getopt now doesn't count `-si` as ambiguous even though there are `--single-seed=` and `--single-wordlist=`, but as soon as you write `--single-` it will demand either an `s` or a `w` for unambiguousity.

I'm hoping for Frank here but in a pinch I could probably sort it out.

**Comment by magnumripper** [comment]
@frank-dittrich this is quite important for the release. Will you have time to look into it?

**Comment by frank-dittrich** [comment]
@magnumripper I know it is important. Unfortunately, I'll not have much time.
And, last time I looked into this problem, I didn't see an easy solution.
May be, there is one.

**Comment by frank-dittrich** [comment]
`--test` and `--test-full` have the same problem.

This patch at least "helps" for `--test-full`, but solving the problem for the shorter option names is far more important.

```
diff --git a/run/john.bash_completion b/run/john.bash_completion
index 369e1667d..683d62441 100644
--- a/run/john.bash_completion
+++ b/run/john.bash_completion
@@ -215,6 +215,7 @@ _john()
 #	Just those options that can be used together with a value,
 #	even if that value is optional:
 	valopts=`echo "$options"|grep '='|sed 's#^ *\([a-z=-]*\).*$#\1#'`
+
 #	This is used to decide whether or not the completion should add
 #	a trailing space.
 #	(That means, for a jumbo build, --rules doesn't get a trailing space,
@@ -611,6 +612,10 @@ _john()
 			COMPREPLY=( $(compgen -W "--test --test=SECONDS" -- ${cur}) )
 			return 0
 			;;
+		--test-full)
+			COMPREPLY=( $(compgen -W "--test-full --test-full=SECONDS" -- ${cur}) )
+			return 0
+			;;
 		--show)
 			COMPREPLY=( $(compgen -W "--show --show=" -- ${cur}) )
 			return 0
```

**Comment by frank-dittrich** [comment]
The problem is that for the shorter option name (rules, test, etc.) I never arrive at this statement in line 323:
```
	case "${option}" in
```
because $(option) only gets filled if for the string on the command line there remains only one valid option name.

**Comment by frank-dittrich** [comment]
${option} needs to be filled if the string on the command line matches the shorter option name, even if there are other options which start with the same string.

**Comment by frank-dittrich** [comment]
> ${option} needs to be filled if the string on the command line matches the shorter option name, even if there are other options which start with the same string.

No, that wouldn't work.

Then, bash completion would show possible completions for `--rules` only, ignoring `--rules-stack=` as a possible completion, unless the command line contains at least the string `--rules-`.

I'm afraid a major rewrite is necessary. Not sure when I'll have the time.

**Comment by frank-dittrich** [comment]
May be I can skip the major rewrite for now, if I somehow hard code the currently known option names which have corresponding longer option names starting with the name of the shorter option.
(Each new collision will then need an adjustment of john.bash-completion.)

**Comment by solardiz** [comment]
Personally, I never use any non-default bash completions, and I am annoyed when I'm on a distro that has some - they tend to get in the way of my expectations of bash's default behavior, and are also an added security risk. But when we already have these optional bash completions in our tree, they better match the current john options. So I treat (work on) this issue as a candidate for the upcoming release, but not a blocker.

**Comment by magnumripper** [comment]
Sounds like I'm definitely not likely to be able to fix it at all, and definitely not in the existing time frame. If Frank don't get some clever idea and fixes it, we'll just document it as a quirk and hope for a fix before J2.

**Comment by magnumripper** [comment]
> `--test` and `--test-full` have the same problem.
> 
> This patch at least "helps" for `--test-full`, but solving the problem for the shorter option names is far more important.
> 
> (...)

I presume this works because there is no *other* `--test-*` option while `--single` is harder because we have `--single-seed`, `--single-wordlist` and `--single-retest-guess`, right?

**Comment by frank-dittrich** [comment]
@magnumripper 
No, the --test-full addition just helps completing `--test-` or `--test-f` etc.

The problem really is ambiguity of option names.
I think I may have found a solution, but when I am not able to complete this within the next 30 minutes, you'll have to wait several hours...

**Comment by solardiz** [comment]
Unimportant for the release. Changed milestone.

**Comment by frank-dittrich** [comment]
I now have a patch which fixes most of the issues I know of.
bash completion works for --single, --rules, --prince, and other options for which overlapping longer option names exist
fixed --fuzz-dump completion
added completion for --rules-stack, --prince-loopback, --tune

I will submit a pull request once I know how to handle --test-full=LEVEL

It used to be `--test-full[=SECONDS]`
Now it is LEVEL instead of SECONDS, but I'm not sure about what values are allowed.
But it looks like the LEVEL parameter is optional, but this isn't reflected in john's --help output.

**Comment by magnumripper** [comment]
Awesome @frank-dittrich! The `--test-full=N` has a weird history. I thought the only currently allowed parameter was `0` and that it's mandatory, but that doesn't seem to be the case now that I try. Perhaps only the code will tell.

Anyway for bash completion I think you should simply expect a number. As long as it's not optional (as in `[=N]` instead of `=N` in --help output, don't expect it to be.

**Comment by frank-dittrich** [comment]
I think the --help output should be changed to `--test-full=[LEVEL]` if that parameter is optional.

For now, `--test-f` will be completed to `--test-full=`, but it looks like `--test-full=` without any parameter works like `--test-full` or `--test-full=-1`

**Comment by magnumripper** [comment]
> I think the --help output should be changed to `--test-full=[LEVEL]` if that parameter is optional.

Right, we'll fix either the usage blob or other code if needed, so you should trust it.

**Comment by frank-dittrich** [comment]
Another question:
```
$ ./john --help |grep "show.*="
--show[=left]              show cracked passwords [if =left, then uncracked]
--show=formats             show information about hashes in a file (JSON)
--show=invalid             show lines that are not valid for selected format(s)
```
```
$ ./john --show=dummy testfile
Invalid option in --show switch. Valid options:
--show, --show=left, --show=formats, --show=types, --show=invalid
```

The (according to doc/SHOW_FORMATS.md deprecated) option `--show=types` seems to work, doc/OPTIONS still mentions --show=types, but it is not mentioned in the `--help` output.

Should I remove `--show=types` from bash completion?
Should I sync bash completion output with this stderr output?
```
options.c-992-                  fprintf(stderr, "Invalid option in --show switch. Valid options:\n"
options.c:993:                          "--show, --show=left, --show=formats, --show=types, --show=invalid\n");
```

**Comment by magnumripper** [comment]
> Should I sync bash completion output with this stderr output?

I think we deprecated `--show=types` in favor of `--show=formats` (which is the same but with json output). I'm OK with either option: Either go by the usage blob or use `--show=help` to get that list.

**Comment by magnumripper** [comment]
Perhaps we should add `--list=format-classes` to get a list of format classes/groups/aliases such as dynamic, cpu, omp, opencl, ztex, all, disabled, enabled that should be included as well.

**Comment by magnumripper** [comment]
Thanks a lot Frank!

**Comment by frank-dittrich** [comment]
> Perhaps we should add `--list=format-classes` to get a list of format classes/groups/aliases such as dynamic, cpu, omp, opencl, ztex, all, disabled, enabled that should be included as well.

I guess this is still open.

the only "class" added so far is `dynamic`.
We'd need the other classes as well.
I could add a hard coded list to bash completion, but I wouldn't want  to add ztex unless really available.

@magnumripper I guess you are the only one who really knows all possible ways to specify or exclude certain formats or format classes, e.g.
```
$ ./john --test --format='-a*,-s*,-descrypt,-b*,-dynamic,-m*,-l*,-c*'
```
Let me know if we should add support for format classes (possible values mixed with regular format names) and/or I should add bash completion support for `--format=-[tab]`, `./john --test --format=opencl,dynamic,[tab]` etc.

**Comment by magnumripper** [comment]
Adding format classes isn't very important for the relase, it would just be nice to have sooner or later. Let's say I'll add `--list=format-classes` soon-ish and let you know, and then you'll add support for using it if/when you've got time. If all that happens pre release, all the better. If not, well, the things you did just now was hell of a lot more important 👍

Solar said back then:
> Personally, I never use any non-default bash completions

I hate not having it. It's not about spelling out `--incremental` faster than I could type `-inc`, it's about not remembering all available options for prince and just get them served. Or that rule that started with "dev" but what the heck was it? I love tab completion.
