### ISSUE TITLE
Can't build on Gentoo

### ISSUE THREAD

**Issue by lovesegfault** [openwall/john#3595]
This has been confirmed as no longer building on Gentoo, it fails in the configuration step with an error relating to OpenSSL. Opening this to notify the upstream maintainers.

Downstream bug: https://bugs.gentoo.org/674656

**Comment by bemeurer** [comment]
Oh, interesting. I can bump the ebuild and add a `-9999` (read: live/HEAD) variant. Will there be another release cut soon?

**Comment by magnumripper** [comment]
That's great. We're hoping to release within a month or two, but to be honest we've had that hope for years now  :doh:

**Comment by frank-dittrich** [comment]
Could we somehow tag each git commit which passes all circleci and travis tests as an alpha release?

Just to avoid gentoo users don't run into a commit which is broken.

**Comment by bemeurer** [comment]
@frank-dittrich That would be really nice!

**Comment by magnumripper** [comment]
I have no idea how we'd maccomplish that but we're not supposed to merge *anything* that doesn't pass the build bots. The only one who can do so at all (I think) is yours truly. I'll try to refrain from committing *any* code changes from now on without creating a PRn and have it scrutinised by the mighty bots.

**Comment by frank-dittrich** [comment]
@magnumripper 
google found some hints.
for travis:
https://stackoverflow.com/questions/28217556/travis-ci-auto-tag-build-for-github-release

for circleci
https://circleci.com/blog/publishing-to-github-releases-via-circleci/

But I didn't spend enough time checking these links in detail, and I have no idea whether this can be combined.

May be it is better to spend our energy on finishing the next release.

**Comment by bemeurer** [comment]
Just as an update, I emerged the live ebuild on gentoo, and it compiles perfectly.

I think if there could be some timely alpha tag (as opposed to it being every commit) it would be better. Just tag an alpha every 2 weeks or a month, even if automated. This lowers the burden on downstream packagers and rolling release users.

**Comment by magnumripper** [comment]
@frank-dittrich I just assumed this was about OpenSSL 1.1.0 messing good with backwards compatibility.

**Comment by magnumripper** [comment]
@bemeurer please elaborate. How/why would that be better?

**Comment by bemeurer** [comment]
@magnumripper Maybe that could be fixed by bumping the major version number of these live tags to something else? E.g. in Gentoo the way they've worked around the problem of "How do we version live builds" is to call the package, say, `app-crypt/johntheripper-jump-9999`, as opposed to`app-crypt/johntheripper-jump-1.80`, kind of betting that the version will never get that high.

Unless distros are automatically packaging latest releases, even if they have a major version difference, in which case I am scared.

**Comment by magnumripper** [comment]
Unfortunately IIRC we can tag something "not working" and it will be picked because it's the latest tag 🙄 . At least that was true from some distro we had an issue with some time ago - that was what made us stop tagging stuff at all.

**Comment by bemeurer** [comment]
@magnumripper That's gross. Honestly, if their distribution model is to compile the latest tag with no checks and put it into distribution, I question how worthy is the time effort to accommodate them. But then here I am asking you to accommodate Gentoo :P

**Comment by magnumripper** [comment]
I actually never looked at it in that way, I was angry with GitHub 😆 but you are right.

**Comment by defau1t** [comment]
For a quick fix, I found that editing the configure file in the src directory to be "-l:libssl.so.1.0.0" configures properly

**Comment by solardiz** [comment]
This issue was fixed back in 2019 by us releasing 1.9.0-jumbo-1 and Gentoo updating to that. Closing.
