### ISSUE TITLE
keystore2john.py and python3

### ISSUE THREAD

**Issue by AlbertVeli** [openwall/john#3658]
When running ./keystore2john.py it works if python2 is the default interpreter but not with python3:

### With python3
app.keystore:$keystore$0$2182$b'feedfeed...

### With python2
app.keystore:$keystore$0$2182$feedfeed...

### Solution
Python3 inserts a b'. It probably has something to do something with how python3 treats things as bytes differently from python2. Either change the code to work with both, or specify #!/usr/bin/env python2 on the first line.

**Comment by kholia** [comment]
@AlbertVeli Thanks for reporting this. It would be awesome if you could submit a pull request to fix this! ;)

This is related to https://github.com/magnumripper/JohnTheRipper/issues/3591 (Test our python scripts with Python 3.x).

We need help in finding and fixing these portability issues.

**Comment by kholia** [comment]
> Either change the code to work with both, or specify #!/usr/bin/env python2 on the first line.

The choice is "always" the former option for us.

**Comment by marksilinio** [comment]
I think this bugreport should be closed/resolved because https://github.com/openwall/john/pull/3664 is merged

**Comment by solardiz** [comment]
Thank you, @AlbertVeli and @marksilinio. Closing.
