### ISSUE TITLE
John proper should allow to use '$JOHN' in JOHN_SYSTEMWIDE_EXEC and JOHN_SYSTEMWIDE_HOME

### ISSUE THREAD

**Issue by claudioandre-br** [openwall/john#3686]
**JtR will work as it does now if I use a** `#define JOHN_SYSTEMWIDE_EXEC "/usr/libexec/john"`
****
**[edited]**

As seen in the patch [1] below:
* I guess only path_init() have to be changed to support this. 
* It will allow packagers to install JtR wherever they want.

[1] Allow JtR system wide build to be executed from any location. Why hard code a path?
```diff
diff --git a/src/params.h b/src/params.h
index 0156044b6..a5e576fe7 100644
--- a/src/params.h
+++ b/src/params.h
@@ -100,10 +100,10 @@
 
 #if JOHN_SYSTEMWIDE
 #ifndef JOHN_SYSTEMWIDE_EXEC /* please refer to the notes above */
-#define JOHN_SYSTEMWIDE_EXEC           "/usr/libexec/john"
+#define JOHN_SYSTEMWIDE_EXEC           "$JOHN"
 #endif
 #ifndef JOHN_SYSTEMWIDE_HOME
-#define JOHN_SYSTEMWIDE_HOME           "/usr/share/john"
+#define JOHN_SYSTEMWIDE_HOME           "$JOHN"
 #endif
 #define JOHN_PRIVATE_HOME              "~/.john"
 #endif
```
This hard-coded path "mode" is NOT the best choice for system wide packages like flatpak and snap.

**Comment by solardiz** [comment]
What does [1] refer to? Perhaps you forgot to include the reference?

I'm undecided on making this change, and currently don't intend to look into it before our upcoming release.

**Comment by claudioandre-br** [comment]
Previous comment edited.

**Comment by magnumripper** [comment]
Do you mean the install would be something like `export JOHN=/usr/local/john (...)` instead of editing params.h or build with `(...) -DJOHN_SYSTEMWIDE_HOME=/usr/local/john (...)`?

I think this is confusing.

**Comment by claudioandre-br** [comment]
? Do you mean the install would be something like export JOHN=/usr/local/john (...) instead of editing params.h or build with (...) -DJOHN_SYSTEMWIDE_HOME=/usr/local/john (...)?

No. I mean a JtR system wide build can "calculate" `$JOHN` during runtime and use it (as a non system wide build does nowadays).

**Comment by magnumripper** [comment]
So how would it "calculate" `$JOHN`? From the actual path of the john binary? Or from the environment variable `$JOHN`? To me it sounds like using a system-wide build for cases where a non-systemwide would be better.

**Comment by claudioandre-br** [comment]
> So how would it "calculate" $JOHN? From the actual path of the john binary? 

From the actual path of the john binary

> To me it sounds like using a system-wide build for cases where a non-systemwide would be better.

Ok, So, lets call it a non-systemwide build (installed in a read-only folder). 
* Since $JOHN is read-only, I need to set JOHN_PRIVATE_HOME.

Nowadays a package is more than `.deb` or `.rpm`. A package is whatever I put in a `read-only folder`.
- The `POT_NAME` have to be `JOHN_PRIVATE_HOME "/john.pot"`
- Ops, as a non-systemwide build, `"$JOHN/john.pot"` is not a valid file name.

**Comment by claudioandre-br** [comment]
As JtR works now, `JOHN_PRIVATE_HOME` only applies to `JOHN_SYSTEMWIDE` builds.

**Comment by solardiz** [comment]
Right now, a JtR system-wide package may contain e.g.:

```
/usr/bin/john
/usr/libexec/john
/usr/libexec/john/john-avx
/usr/libexec/john/john-i686
/usr/libexec/john/john-mmx
/usr/libexec/john/john-omp-avx
/usr/libexec/john/john-omp-i686
/usr/libexec/john/john-omp-mmx
/usr/libexec/john/john-omp-sse2
/usr/libexec/john/john-sse2
/usr/libexec/john/john-xop
```

With the change proposed here, those fallback binaries would all have to be right in `/usr/bin`, and thus in `$PATH`. I think that's wrong - we don't want them in `$PATH`.

OTOH, if the change is only to _defaults_ for those paths, then a package can override them at build time either way. So do we prefer the defaults to be for traditional system-wide packages like a `.deb` or `.rpm`, or for "whatever I put in a read-only folder", in Claudio's words? I don't know. I have no strong preference.

**Comment by claudioandre-br** [comment]
> With the change proposed here, those fallback binaries would all have to be right in /usr/bin, and thus in $PATH. I think that's wrong - we don't want them in $PATH.

Kind of. At least, fallback binaries will be:

```
/usr/bin/john => So, "$JOHN = /usr/bin"

$JOHN/libexec/john/john-avx
$JOHN/libexec/john/john-i686
$JOHN/libexec/john/john-mmx
$JOHN/libexec/john/john-omp-avx
$JOHN/libexec/john/john-omp-i686
$JOHN/libexec/john/john-omp-mmx
$JOHN/libexec/john/john-omp-sse2
$JOHN/libexec/john/john-sse2
$JOHN/libexec/john/john-xop```

**Comment by claudioandre-br** [comment]
Imagine that an OS have a package system where you download a "special" zip file containing all information needed, put it in a special location, and all is set. (people told me Mac works this way).

* The "special" zip file is mounted read-only in, e.g., /app/xpto.
* How should I create such a package? System wide? Non systemwide?

Now, think about distribute JtR in a squashfs (how Canonical snap works) system. And so on.

**Comment by magnumripper** [comment]
Yes, I think OSX works that way, more or less. I understand your rationale. I have no objection against supporting this, since it will only happen if someone actually edits params.h that way.

**Comment by claudioandre-br** [comment]
Another strategy is to make `JOHN_PRIVATE_HOME` independent of `JOHN_SYSTEMWIDE`. In any case, JtR should update its package concept.

```diff
From 04b7c6e37a6906ae49a5cb856990c893a6a7fcff Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Claudio=20Andr=C3=A9?= <claudioandre.br@gmail.com>
Date: Tue, 26 Mar 2019 21:09:18 -0300
Subject: [PATCH] private

---
 src/listconf.c |  2 ++
 src/params.h   |  5 +++-
 src/path.c     | 69 +++++++++++++++++++++++++-------------------------
 3 files changed, 40 insertions(+), 36 deletions(-)

diff --git a/src/listconf.c b/src/listconf.c
index 73f43be82..5bf477c84 100644
--- a/src/listconf.c
+++ b/src/listconf.c
@@ -145,6 +145,8 @@ static void listconf_list_build_info(void)
 #if JOHN_SYSTEMWIDE
 	puts("System-wide exec: " JOHN_SYSTEMWIDE_EXEC);
 	puts("System-wide home: " JOHN_SYSTEMWIDE_HOME);
+#endif
+#ifdef JOHN_PRIVATE_HOME
 	puts("Private home: " JOHN_PRIVATE_HOME);
 #endif
 #if CPU_REQ
diff --git a/src/params.h b/src/params.h
index 44876fca5..fe5cf39ca 100644
--- a/src/params.h
+++ b/src/params.h
@@ -105,6 +105,9 @@
 #ifndef JOHN_SYSTEMWIDE_HOME
 #define JOHN_SYSTEMWIDE_HOME		"/usr/share/john"
 #endif
+#endif
+
+#if JOHN_SYSTEMWIDE || JOHN_PACKAGE
 #define JOHN_PRIVATE_HOME		"~/.john"
 #endif
 
@@ -160,7 +163,7 @@
 #else
 #define CFG_FULL_NAME			"$JOHN/john.conf"
 #endif
-#if JOHN_SYSTEMWIDE
+#ifdef JOHN_PRIVATE_HOME
 #ifdef __DJGPP__
 #define CFG_PRIVATE_FULL_NAME		JOHN_PRIVATE_HOME "/john.ini"
 #else
diff --git a/src/path.c b/src/path.c
index d5b563e38..2cbeff45e 100644
--- a/src/path.c
+++ b/src/path.c
@@ -24,7 +24,7 @@ static int john_home_length;
 static char *john_home_pathex = NULL;
 static int john_home_lengthex;
 
-#if JOHN_SYSTEMWIDE
+#ifdef JOHN_PRIVATE_HOME
 #if (!AC_BUILT || HAVE_UNISTD_H) && !_MSC_VER
 #include <unistd.h>
 #endif
@@ -40,12 +40,11 @@ static int user_home_length;
 
 void path_init(char **argv)
 {
-#if JOHN_SYSTEMWIDE
-	char *home_dir;
 #ifdef JOHN_PRIVATE_HOME
+	char *home_dir;
 	const char *private;
 #endif
-#else
+#if !JOHN_SYSTEMWIDE
 	char *pos;
 #endif
 
@@ -53,34 +52,6 @@ void path_init(char **argv)
 	john_home_path = mem_alloc(PATH_BUFFER_SIZE);
 	strnzcpy(john_home_path, JOHN_SYSTEMWIDE_HOME "/", PATH_BUFFER_SIZE);
 	john_home_length = strlen(john_home_path);
-
-	if (user_home_path) return;
-
-	/* $HOME may override user's home directory */
-	if (!(home_dir = getenv("HOME"))) {
-		struct passwd *pw;
-
-		pw = getpwuid(getuid());
-		endpwent();
-		if (!pw)
-			return;
-		home_dir = pw->pw_dir;
-	}
-
-	user_home_length = strlen(home_dir) + 1;
-	if (user_home_length >= PATH_BUFFER_SIZE) return;
-
-	user_home_path = mem_alloc(PATH_BUFFER_SIZE);
-	memcpy(user_home_path, home_dir, user_home_length - 1);
-	user_home_path[user_home_length - 1] = '/';
-
-#ifdef JOHN_PRIVATE_HOME
-	private = path_expand(JOHN_PRIVATE_HOME);
-	if (mkdir(private, S_IRUSR | S_IWUSR | S_IXUSR)) {
-		if (errno != EEXIST) pexit("mkdir: %s", private);
-	} else
-		fprintf(stderr, "Created directory: %s\n", private);
-#endif
 #else
 	if (argv[0]) {
 		int dos=0;
@@ -109,6 +80,34 @@ void path_init(char **argv)
 		}
 	}
 #endif
+
+#ifdef JOHN_PRIVATE_HOME
+	if (user_home_path) return;
+
+	/* $HOME may override user's home directory */
+	if (!(home_dir = getenv("HOME"))) {
+		struct passwd *pw;
+
+		pw = getpwuid(getuid());
+		endpwent();
+		if (!pw)
+			return;
+		home_dir = pw->pw_dir;
+	}
+
+	user_home_length = strlen(home_dir) + 1;
+	if (user_home_length >= PATH_BUFFER_SIZE) return;
+
+	user_home_path = mem_alloc(PATH_BUFFER_SIZE);
+	memcpy(user_home_path, home_dir, user_home_length - 1);
+	user_home_path[user_home_length - 1] = '/';
+
+	private = path_expand(JOHN_PRIVATE_HOME);
+	if (mkdir(private, S_IRUSR | S_IWUSR | S_IXUSR)) {
+		if (errno != EEXIST) pexit("mkdir: %s", private);
+	} else
+		fprintf(stderr, "Created directory: %s\n", private);
+#endif
 }
 
 void path_init_ex(const char *path)
@@ -166,7 +165,7 @@ const char *path_expand(const char *name)
 		return name + 6;
 	}
 
-#if JOHN_SYSTEMWIDE
+#ifdef JOHN_PRIVATE_HOME
 	if (!strncmp(name, "~/", 2)) {
 		if (user_home_path &&
 		    user_home_length + strlen(name) - 2 < PATH_BUFFER_SIZE) {
@@ -199,7 +198,7 @@ const char *path_expand_safe(const char *name)
 		return full_path;
 	}
 
-#if JOHN_SYSTEMWIDE
+#ifdef JOHN_PRIVATE_HOME
 	if (!strncmp(name, "~/", 2)) {
 		if (user_home_path &&
 		    user_home_length + strlen(name) - 2 < PATH_BUFFER_SIZE) {
@@ -243,7 +242,7 @@ char *path_session(const char *session, const char *suffix)
 void path_done(void)
 {
 	MEM_FREE(john_home_path);
-#if JOHN_SYSTEMWIDE
+#ifdef JOHN_PRIVATE_HOME
 	MEM_FREE(user_home_path);
 #endif
 	if (john_home_pathex)
-- 
2.19.1
```

**Comment by magnumripper** [comment]
I think I'm fine with such a patch. Now I really need to sleep. Pulling the plug!

**Comment by ulidtko** [comment]
So uh... will something be merged here, ever?

I'm bumping the issue — since it's currently huge PITA to try to use `john` built-from-source from outside the `run` directory.

I don't find it usable, at all, to mix my hash-files, dictionary-files, session-files and whatnot with **182** (!) scripts, binaries, symlinks and datafiles living under `run`. May I use CWD of my choice, please?

I've tried:
 * `strace`-ing the `fopen: john.conf: No such file or directory` error
 * editing `params.h`
 * uncommenting disfunctional `make install` target
 * symlinking crap around

... no dice. It only frustrates more, by not-working in a wonderful novel way; makes me think:

> Ewww. What's *wrong* with this piece of software, why can't it *just work*?

Perhaps complaining on github helps?.. :face_with_head_bandage:

**Comment by solardiz** [comment]
I've just added a milestone so that we take another look at this issue before making the next release. However, I am not sure what needs to be done here, if anything.

@ulidtko You say there's a usability problem, but somehow I don't feel there's one, and I've been using JtR a lot. I can run e.g.:

```
cd hashdir
~/john/run/john -w=../wordsdir/wordlist hashfile
```

and it works just fine. Yes, it uses `john.pot`, `john.rec`, and `john.log` files (or differently named ones of the latter two for a different session name) in the `run` directory - but to me that's most convenient.

What is the problem in this for you? Just trying to understand you better. Thanks.

**Comment by ulidtko** [comment]
@solardiz your attention appreciated. I'll try elaborating.

There's a solid number of various datafiles shipped-with and used-by JtR (mostly depending on running mode), especially the jumbo build:

 * OpenCL kernels
 * `rules` lists
 * Markov Chain models
 * `.dic` files
 * `.chr` files
 * `john.conf`

and probably more. I'd be trivially convinced that JtR author can remember all those, and the respective --options to pass so JtR can find stuff when needed.

My point is: users generally can't remember that. Nor should they. It's a basic usability expectation that programs are able to locate their resources/datafiles — without imposing assumptions onto CWD.

In particular, I was trying to run jumbo JtR "hybrid mode" on a 10-year-old gpg key using OpenCL GPUs — from outside the `run` directory. I couldn't do that, despite trying hard. The command line just grows clumsy big pretty quick.

I ended up putting my input materials (hash file, dictionary file, rules file) into a subdirectory, `jtr/run/gpg`, and running `./john ...` strictly from `run`. Even then, needing to repeat `gpg/` three times, for 12 extra characters total, certainly adds clumsiness when most of the cmdline is filled with opencl- and attack-related options; it all starts to line-wrap heavily, and I start needing a dedicated shell-script.

That's what I meant by implying poor usability.

-----

Nice, I've stopped talking and just tried your example:

    cd hashdir
    ~/john/run/john -w=../wordsdir/wordlist hashfile

And it does indeed work. But did you ever try this?

    cd hashdir
    export PATH=$PATH:~/john/run
    john -w=../wordsdir/wordlist hashfile

JtR falls face flat in this case.

I figure, that's the primary reason why I struggled so much: wanting to shave `~/src/JohnTheRipper/run/` off my command lines by using PATH, and being misled by error messages.

Hope that helps. And, thanks for what you do!

**Comment by solardiz** [comment]
@ulidtko Thanks. So basically things work when you specify the full pathname to `john` explicitly, and don't work with PATH (as expected, knowing how `john` finds other files by parsing its pathname). In your example with `run/gpg`, I expect you'd have mostly avoided the problem by being in `run/gpg` and typing `../john`. I understand this is not ideal, but it's also not as clumsy as the approach you ended up using.

As to what we could do, I see these options:

1. Add support for user local installs, where a path like `/home/username/john` would be getting hard-coded into the `john` binary at build time.

2. Search `PATH` trying to mimic what the shell does... and sometimes running into issues when there's any discrepancy. Worse, potentially even security issues.

3. On Linux specifically, we could read the `/proc/PID/exe` symlink. Should be reliable, but Linux-specific.

**Comment by solardiz** [comment]
@ulidtko Here's a trick that I think should work (but I haven't tested):

```
alias john=~/john/run/john
```

instead of using PATH.

**Comment by ulidtko** [comment]
@solardiz both the alias and `../john` are excellent workarounds.

Let me suggest an easy warning to hint at those when someone follows the same PATH mistake I did.

**Comment by solardiz** [comment]
This issue was initially about enhancing the core branch, but I currently have no plans to develop the core branch further outside of jumbo.

Then discussion diverted to issues with usage of jumbo, ending in a suggestion to use aliases and have jumbo itself print such a suggestion when relevant, which was implemented.

I see no further actions to take here, so closing (as "not planned" with regard to the issue's title and core branch).
