### ISSUE TITLE
Support cracking WPA from .ivs files

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#371]
aircrack-ng can store .ivs files with just the information needed to crack WPA (or WEP, but that is not interesting for us). There are pcap2ivs tools but I can't find any ivs2pcap tool so we currently can't crack WPA with an .ivs file as input.

We should either add a ivs2john tool, or perhaps add that support to wpapcap2john.

**Comment by khanmehandi10** [comment]
is there any online cracker for .hccap file

**Comment by kholia** [comment]
@khanmehandi10 this is a bug tracker, not a forum for end-user support.
