### ISSUE TITLE
Improve auto-tune

### ISSUE THREAD

**Issue by solardiz** [openwall/john#3779]
I often see significantly better speeds reported during verbose auto-tune than the final speed reported by `--test`. Why could this be? 100% reproducible example:

```
[solar@super run]$ ./john -test -form=md5crypt-opencl -dev=4 -v=5 
[...]
gws:     81920	  8119Kc/s  8119122000 rounds/s  10.089ms per crypt_all()+
pass xfer: 823.968us, crypt: 17.550ms, result xfer: 780.512us
gws:    163840	  8553Kc/s  8553462000 rounds/s  19.154ms per crypt_all()+
pass xfer: 1.660ms, crypt: 34.102ms, result xfer: 1.583ms
gws:    327680	  8774Kc/s  8774064000 rounds/s  37.346ms per crypt_all()+
pass xfer: 3.296ms, crypt: 69.752ms, result xfer: 3.126ms
gws:    655360	  8603Kc/s  8603274000 rounds/s  76.175ms per crypt_all()
pass xfer: 6.604ms, crypt: 138.479ms, result xfer: 6.274ms
gws:   1310720	  8659Kc/s  8659740000 rounds/s 151.357ms per crypt_all()
pass xfer: 13.267ms, crypt: 262.318ms (exceeds 200ms)
pass xfer: 823.968us, crypt: 15.910ms, result xfer: 783.136us
gws:    163840	  9352Kc/s  9352657000 rounds/s  17.518ms per crypt_all()!!
pass xfer: 412.928us, crypt: 8.008ms, result xfer: 392.640us
gws:     81920	  9294Kc/s  9294118000 rounds/s   8.814ms per crypt_all()-

Local worksize (LWS) 1024, global worksize (GWS) 163840 (160 blocks)
DONE
Raw:	8192K c/s real, 8273K c/s virtual, GPU util: 87%
```

This persists even despite of these changes to match benchmark more closely:

```diff
[solar@super run]$ git diff
diff --git a/src/opencl_common.c b/src/opencl_common.c
index 5d6fab9..062fbe8 100644
--- a/src/opencl_common.c
+++ b/src/opencl_common.c
@@ -1552,15 +1552,15 @@ static cl_ulong gws_test(size_t gws, unsigned int rounds, int sequential_id)
                len = MAX(len, self->params.plaintext_min_length);
                len = MIN(len, self->params.plaintext_length);
 
-               memset(key, 0x61, sizeof(key));
+               memset(key, 0x41, sizeof(key));
+               key[len] = 0;
 
                for (i = 0; i < kpc; i++) {
-                       int l = 0;
+                       int l = len - 1;
 
-                       key[len] = 0;
                        self->methods.set_key(key, i);
-                       while (++key[l] > 0x7a)
-                               key[l++] = 0x21;
+                       while (l >= 0 && ++key[l] > 0x60)
+                               key[l--] = 0x21;
                }
        }
 
diff --git a/src/opencl_md5crypt_fmt_plug.c b/src/opencl_md5crypt_fmt_plug.c
index cad946f..f9cf463 100644
--- a/src/opencl_md5crypt_fmt_plug.c
+++ b/src/opencl_md5crypt_fmt_plug.c
@@ -91,6 +91,7 @@ static struct fmt_main *self;
 
 static struct fmt_tests tests[] = {
        {"$1$Btiy90iG$bGn4vzF3g1rIVGZ5odGIp/", "qwerty"},
+       {"$1$7Uu2iTBB$Y4hQl2WvrOA3LBbLDxbAf0", "12345"},
        {"$1$salt$c813W/s478KCzR0NnHx7j0", "qwerty"},
        {"$1$salt$8LO.EVfsTf.HATV1Bd0ZP/", "john"},
        {"$1$salt$TelRRxWBCxlpXmgAeB82R/", "openwall"},
```

(BTW, I think we should merge these. Edit: I just noticed there's similar code in `opencl_find_best_lws`, which would need to be kept consistent with the above.)

**Comment by magnumripper** [comment]
Does that change at all if you `-test -mask`?

**Comment by solardiz** [comment]
It's similar with `-test -mask`:

```
[solar@super run]$ ./john -test -form=md5crypt-opencl -dev=4 -v=5 -mask
Note: Self-tests currently not performed when using -mask with -test
initUnicode(UNICODE, ASCII/ASCII)
ASCII -> ASCII -> ASCII
Device 4: GeForce GTX 1080

Test mask: ?a?a?l?u?d?d?s
[...]
gws:     81920	  8132Kc/s  8132638000 rounds/s  10.072ms per crypt_all()+
pass xfer: 824.704us, crypt: 17.382ms, result xfer: 796.384us
gws:    163840	  8621Kc/s  8621575000 rounds/s  19.003ms per crypt_all()+
pass xfer: 1.645ms, crypt: 34.334ms, result xfer: 1.583ms
gws:    327680	  8723Kc/s  8723149000 rounds/s  37.564ms per crypt_all()+
pass xfer: 3.310ms, crypt: 70.095ms, result xfer: 3.142ms
gws:    655360	  8561Kc/s  8561303000 rounds/s  76.549ms per crypt_all()
pass xfer: 6.603ms, crypt: 139.679ms, result xfer: 6.246ms
gws:   1310720	  8593Kc/s  8593238000 rounds/s 152.529ms per crypt_all()
pass xfer: 13.192ms, crypt: 264.508ms (exceeds 200ms)
pass xfer: 823.968us, crypt: 16.289ms, result xfer: 783.328us
gws:    163840	  9154Kc/s  9154561000 rounds/s  17.897ms per crypt_all()!!
pass xfer: 412.928us, crypt: 8.217ms, result xfer: 389.984us
gws:     81920	  9081Kc/s  9081588000 rounds/s   9.020ms per crypt_all()-

Local worksize (LWS) 1024, global worksize (GWS) 163840 (160 blocks)
DONE
Raw:	8192K c/s real, 8151K c/s virtual, GPU util: 88%
```

**Comment by magnumripper** [comment]
I have no idea. The first tune figures for same GWS are lower - but still higher than final.

Are we calculating c/s -> Kc/s the same way? I use to just shift right by 10...

**Comment by solardiz** [comment]
Also, speeds seen during actual cracking with that mask are close to `-test` final speeds, not to auto-tune speeds:

```
[solar@super run]$ ./john -form=md5crypt-opencl -dev=4 -v=5 pw -mask='?a?a?l?u?d?d?s'
[...]
gws:     81920	  8662Kc/s  8662813000 rounds/s   9.456ms per crypt_all()
pass xfer: 823.936us, crypt: 17.200ms, result xfer: 780.448us
gws:    163840	  8712Kc/s  8712802000 rounds/s  18.804ms per crypt_all()+
pass xfer: 1.660ms, crypt: 34.341ms, result xfer: 1.561ms
gws:    327680	  8723Kc/s  8723342000 rounds/s  37.563ms per crypt_all()
pass xfer: 3.295ms, crypt: 69.082ms, result xfer: 3.127ms
gws:    655360	  8679Kc/s  8679591000 rounds/s  75.505ms per crypt_all()
pass xfer: 6.606ms, crypt: 136.875ms, result xfer: 6.247ms
gws:   1310720	  8753Kc/s  8753909000 rounds/s 149.729ms per crypt_all()
pass xfer: 13.233ms, crypt: 259.275ms (exceeds 200ms)
pass xfer: 413.216us, crypt: 8.224ms, result xfer: 390.592us
gws:     81920	  9073Kc/s  9073413000 rounds/s   9.028ms per crypt_all()!!
pass xfer: 208.032us, crypt: 4.144ms, result xfer: 195.328us
gws:     40960	  9007Kc/s  9007233000 rounds/s   4.547ms per crypt_all()-
Local worksize (LWS) 1024, global worksize (GWS) 81920 (80 blocks)
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:03 0.12% (ETA: 01:27:17) 0g/s 7771Kp/s 7771Kc/s 7771KC/s GPU:60C util:86% fan:42% q=tQ31...+<gQ31.
0g 0:00:00:10 0.40% (ETA: 01:27:27) 0g/s 7965Kp/s 7965Kc/s 7965KC/s GPU:62C util:86% fan:48% RZnR30...X&hR30.
0g 0:00:00:47 1.87% (ETA: 01:27:40) 0g/s 7992Kp/s 7992Kc/s 7992KC/s GPU:73C util:87% fan:53% x[hG05...FazG05.
```

**Comment by solardiz** [comment]
Here's a guess: maybe auto-tune somehow assumes "many salts", but our "Raw" benchmark and my actual cracking run here is single-salt. Thus, auto-tune is 100% GPU util, but actual for single-salt is then ~87%.

But this doesn't explain why the same discrepancy is also seen e.g. for sha512crypt-opencl, which is slow enough that it gets to nearly 100% GPU util even at single-salt.

**Comment by claudioandre-br** [comment]
> I often see significantly better speeds reported during verbose auto-tune than the final speed reported by --test. Why could this be? 100% reproducible example:

This is expected for intermediate-fast hashes. Tune is measuring kernel execution times. 

It can't compute how long:
- `set_key()`, `cmp_*()` etc takes.

Lets say it is computing how JtR asynchronous version wil behave.

**Comment by magnumripper** [comment]
BTW the auto-tune only times the actual OpenCL calls within crypt_all(). The benchmark figure includes other things like `set_key()` (including random pw generation, which we've seen before may take enough time to affect the resuilts). I see Claudio says the same :)

**Comment by solardiz** [comment]
Oh, right. This is close to my "many salts" guess. It's even more than that, actually.

But is e.g. sha512crypt-opencl's `set_key` and `cmp_*` slow enough (relatively to hashing) for a similar discrepancy to be seen? And it is seen there as well, of similar magnitude.

**Comment by magnumripper** [comment]
I just looked, we're only setting one salt, once.

**Comment by solardiz** [comment]
But we're reusing already-set keys like we would have with many salts.

**Comment by magnumripper** [comment]
True. So that shouldn't affect things much.

**Comment by solardiz** [comment]
Or maybe not: we do set keys every time `gws_test` is called, and it then does just one call to `crypt_all`. So this is similar to single-salt cracking run.

But it's missing `cmp_all`. Maybe that's why the discrepancy - maybe we avoid transferring the computed hashes back to host during auto-tune?

**Comment by solardiz** [comment]
BTW, ideally we'd auto-tune for the salt count that we've actually loaded. Not for single-salt, nor for arbitrary "many salts". And maybe we should keep `cmp_all` in there, too.

**Comment by magnumripper** [comment]
md5crypt does a cl_Finish, which blocks until everything is transferred. You can even see result transfer time, 390.592us in your latest paste.

Neither bench.c or auto-tune calls `cmp_*`. The biggest difference is that bench measures time for `bench_set_key` and `set_key`.

**Comment by solardiz** [comment]
bench.c _does_ call `cmp_all`:

```c
#ifndef BENCH_BUILD
                format->methods.cmp_all(binary,
                    format->methods.crypt_all(&count, test_db->salts));
#else
                format->methods.cmp_all(binary,
                    format->methods.crypt_all(&count, NULL));
#endif
```

> The biggest difference is that bench measures time for `bench_set_key` and `set_key`.

Oh, I see this now: although `gws_test` does set all keys every time, it only starts the timer after it's done that. This explains it.

What is still unexplained to me is why the discrepancy is roughly the same in relative terms for sha512crypt-opencl, which is so much slower than its key setup time should have been relatively negligible.

**Comment by claudioandre-br** [comment]
> BTW, ideally we'd auto-tune for the salt count that we've actually loaded. Not for single-salt, nor for arbitrary "many salts". 

We use the worst case:
https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/opencl_common.c#L1569

**Comment by magnumripper** [comment]
Yes we use the worst loaded cost, but not the count (I think)

**Comment by solardiz** [comment]
@claudioandre-br Good to know. I meant salt count, not tunable costs, though. Currently, we don't take salt count into consideration at all, but if we would then it'd better be the real one.

BTW, you can press `y` on GitHub to obtain a permalink to a particular revision, so that line-number links such as the one in your comment wouldn't become outdated.

**Comment by magnumripper** [comment]
> bench.c _does_ call `cmp_all`:

Right. Perhaps auto-tune should too? We have/had formats that does transfers or other things in cmp_all.

**Comment by solardiz** [comment]
> although `gws_test` does set all keys every time, it only starts the timer after it's done that.

I've just tried moving these lines:

```c
       // Activate events. Then clear them later.
       for (i = 0; i < MAX_EVENTS; i++)
               multi_profilingEvent[i] = &benchEvent[i];
```

to before the `clear_keys` call. Surprisingly, this doesn't appear to have made a difference.

> Perhaps auto-tune should too?

Yes, perhaps auto-tune should call `cmp_all` too.

**Comment by magnumripper** [comment]
Even if you moved those lines, we're only profiling the calls in crypt_all(). Anything that has `multi_profilingEvent[n]` in the format, nothing else.

**Comment by solardiz** [comment]
Oh. I just don't know how this works. OK.

**Comment by magnumripper** [comment]
This also means if we add `cmp_all()` to auto-tune, it wont affect the figures at all unless there's OpenCL calls in that function that uses `multi_profilingEvent[n]`.

**Comment by solardiz** [comment]
Then I guess we need to revisit this issue after the upcoming release. And it's a rather generic issue of making auto-tune closely resemble actual usage of the formats interfaces and for the run's actual salt count, and to include everything relevant in the timing measurements. Maybe we should change the issue's description accordingly, or open a new one in lieu of this one.

**Comment by solardiz** [comment]
BTW, it's also useful to see how fast `crypt_all` alone would be. So maybe we should retain that ability somehow, for our own code debugging/tuning.

**Comment by claudioandre-br** [comment]
We still need to measure `multi_profilingEvent[n]`

**Comment by magnumripper** [comment]
> We will need to measure `multi_profilingEvent[n]` after the change

Yes, but that's nothing new - just add events to the array. Eg:
```diff
diff --git a/src/opencl_rawsha512_fmt_plug.c b/src/opencl_rawsha512_fmt_plug.c
index 95ef9ee9d..3576495ae 100644
--- a/src/opencl_rawsha512_fmt_plug.c
+++ b/src/opencl_rawsha512_fmt_plug.c
@@ -92,7 +92,7 @@ static struct fmt_main *self;
 #include "opencl_autotune.h"
 
 static const char * warn[] = {
-       "xfer: ",  ", crypt: "
+       "xfer: ",  ", crypt: ", "vin: ", ", verify: ", ", vout: "
 };
 
 /* ------- Helper functions ------- */
@@ -325,16 +325,16 @@ static int cmp_all(void *binary, int count)
        uint32_t result;
        ///Copy binary to GPU memory
        HANDLE_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], mem_binary, CL_FALSE,
-               0, sizeof(uint64_t), ((uint64_t*)binary)+3, 0, NULL, NULL), "Copy mem_binary");
+               0, sizeof(uint64_t), ((uint64_t*)binary)+3, 0, NULL, multi_profilingEvent[2]), "Copy mem_binary");
 
        ///Run kernel
        HANDLE_CLERROR(clEnqueueNDRangeKernel
            (queue[gpu_id], cmp_kernel, 1, NULL, &global_work_size, &local_work_size,
-               0, NULL, NULL), "Set ND range");
+               0, NULL, multi_profilingEvent[3]), "Set ND range");
 
        /// Copy result out
        HANDLE_CLERROR(clEnqueueReadBuffer(queue[gpu_id], mem_cmp, CL_TRUE, 0,
-               sizeof(uint32_t), &result, 0, NULL, NULL), "Copy data back");
+               sizeof(uint32_t), &result, 0, NULL, multi_profilingEvent[4]), "Copy data back");
 
        return result;
 }
```

**Comment by magnumripper** [comment]
Oh, and `s/HANDLE_CLERROR/BENCH_CLERROR/g` in that function as well

**Comment by magnumripper** [comment]
This is actually a trivial change - we should do that right now.

**Comment by claudioandre-br** [comment]
> But is e.g. sha512crypt-opencl's set_key and cmp_* slow enough (relatively to hashing) for a similar discrepancy to be seen? And it is seen there as well, of similar magnitude.

That was not the case of Titan X (or it is up to 1%). It seems to me sha512crypt-opencl is no longer a "slow hash". It deserves GPU mask mode or async or ...

**Comment by solardiz** [comment]
> It seems to me sha512crypt-opencl is no longer a "slow hash".

I think it is enough of a slow hash that the idle time between batches of candidates is probably under 1%. We do see 100% GPU util reported for it.

**Comment by claudioandre-br** [comment]
This is sha512crypt-opencl now. Sometimes good figures. But:
```
|   2  GeForce GTX TIT...  Off  | 00000000:84:00.0 Off |                  N/A |
| 30%   72C    P2   145W / 250W |    179MiB / 12212MiB |     77%      Default |
```

It can:
```
|   2  GeForce GTX TIT...  Off  | 00000000:84:00.0 Off |                  N/A |
| 38%   83C    P2   246W / 250W |    762MiB / 12212MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

```

**Comment by claudioandre-br** [comment]
> Yes, but that's nothing new - just add events to the array. Eg:

In fact, almost all formats are doing this already. The only missing bits are measure "core tasks".

```
prep: 11.040us, xfer pass: 27.296us, idx: 14.432us, crypt: 19.456us, result: 14.144us*
```

**Comment by magnumripper** [comment]
> In fact, almost all formats are doing this already

We're talking about cmp_all now, so no. That function wasn't even called from auto-tune. See #3781

**Comment by magnumripper** [comment]
Only a few of myrice's formats were affected, but in the future I'm pretty sure there'll be more.

**Comment by solardiz** [comment]
I've just created a new issue for the remaining ideas, and I'll close this general discussion issue.
