### ISSUE TITLE
yescrypt problem on AVX, clang, ASan/UbSan? And Windows.

### ISSUE THREAD

**Issue by claudioandre-br** [openwall/john#3798]
This happened twice (yesterday on yescript, today on scrypt). Some investigation is advised.

```
Testing: md5crypt, crypt(3) $1$ [MD5 128/128 AVX 4x5]... (2xOMP) PASS
Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]... (2xOMP) 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

```

clang version 8.0.0-3 (tags/RELEASE_800/final)

May be caused by:
```
Development options (these may hurt performance when enabled):
AddressSanitizer ("ASan") .................. enabled
UndefinedBehaviorSanitizer ("UbSan") ....... enabled
Fuzzing test ............................... no
Experimental code .......................... no
```

**Comment by claudioandre-br** [comment]
Not sure now (but what called my attention yesterday was):
```
yescrypt/yescrypt-opt.c:513:2: warning: "Note: using x86-64 inline assembly for YESCRYPT_RW.  That's great." [-W#warnings]
#warning "Note: using x86-64 inline assembly for YESCRYPT_RW.  That's great."
```

**Comment by claudioandre-br** [comment]
scrypt is also misbehaving on Windows 32bits
```
Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]... (2xOMP) /-Command exited with code -1073741819
```

**Comment by magnumripper** [comment]
> Not sure now (but what called my attention yesterday was):
> 
> ```
> yescrypt/yescrypt-opt.c:513:2: warning: "Note: using x86-64 inline assembly for YESCRYPT_RW.  That's great." [-W#warnings]
> #warning "Note: using x86-64 inline assembly for YESCRYPT_RW.  That's great."
> ```

I dropped that diagnostic in cba22ea9

**Comment by claudioandre-br** [comment]
I noticed. Well, the stall is 100% reproducible on Travis.

I will rebase and re-run the tests to see if I found anything new.

**Comment by solardiz** [comment]
I've just tried building on super using devtoolset-3 with `./configure --enable-asan`. No issues for the scrypt format - passes `-test`, `-test=0`, `-test-full=1`.

@claudioandre-br Are all of the failures only with clang so far?

**Comment by claudioandre-br** [comment]
No. On Windows it is:

```
Version: 1.9.0-jumbo-1-bleeding-3736e3e3e 2019-04-12 06:59:47 -0300
Build: cygwin 32-bit i686 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:2 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is 
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseeko
ftell(): ftello
fopen(): _fopen64
memmem(): System's
```

But, on Linux it only happens in clang 8 + ASAN + UBSAN

**Comment by solardiz** [comment]
Also no issue on "well" with its old clang and `./configure --enable-asan --enable-ubsan CC=clang`.

@claudioandre-br Is the issue reproducible when testing the scrypt format alone, or only when scrypt is being tested along with other formats - that is, pure `-test` without `-format`?

**Comment by claudioandre-br** [comment]
The same "build" using gcc 8 passes.
```
$ JtR -test=0 --format=cpu
Testing: descrypt, traditional crypt(3) [DES 128/128 AVX]... (2xOMP) Will run 2 OpenMP threads
DES_bs.c:538:2: runtime error: load of misaligned address 0x7f0aa6690d21 for type 'long int', which requires 8 byte alignment
0x7f0aa6690d21: note: pointer points here
 00 00 00  1f 02 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
DES_bs.c:539:2: runtime error: load of misaligned address 0x7f0aa6690d31 for type 'long int', which requires 8 byte alignment
0x7f0aa6690d31: note: pointer points here
 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ff ff ff ff ff ff ff ff  ff ff ff ff ff
              ^ 
DES_bs.c:541:2: runtime error: load of misaligned address 0x7f0aa6690cf1 for type 'long int', which requires 8 byte alignment
0x7f0aa6690cf1: note: pointer points here
 00 00 00  e0 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  bf ff ff ff ff ff ff ff  ff ff ff ff ff
              ^ 
DES_bs.c:542:2: runtime error: load of misaligned address 0x7f0aa6690d01 for type 'long int', which requires 8 byte alignment
0x7f0aa6690d01: note: pointer points here
 ff ff ff  bf ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  1f 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
DES_bs.c:543:2: runtime error: load of misaligned address 0x7f0aa6690d11 for type 'long int', which requires 8 byte alignment
0x7f0aa6690d11: note: pointer points here
 ff ff ff  1f 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  1f 02 00 00 00 00 00 00  00 00 00 00 00
              ^ 
DES_bs.c:548:4: runtime error: load of misaligned address 0x7f0aa6690ce1 for type 'long int', which requires 8 byte alignment
0x7f0aa6690ce1: note: pointer points here
 ff ff ff  5f 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  e0 ff ff ff ff ff ff ff  ff ff ff ff ff
              ^ 
DES_bs.c:553:9: runtime error: load of misaligned address 0x7f0aa6690d41 for type 'long int', which requires 8 byte alignment
0x7f0aa6690d41: note: pointer points here
 00 00 00  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  a0 fd ff ff ff ff ff ff  ff ff ff ff ff
              ^ 
PASS
Testing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 128/128 AVX]... (2xOMP) PASS
Testing: md5crypt, crypt(3) $1$ [MD5 128/128 AVX 4x3]... (2xOMP) PASS
Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]... (2xOMP) PASS
```

**Comment by solardiz** [comment]
BTW, I didn't expect any unaligned accesses for descrypt. That's weird. Also, those line numbers look a bit off (I'm looking at the latest bleeding-jumbo).

**Comment by claudioandre-br** [comment]
1. it will failt when running `"$JtR" -test-full=0 --format=scrypt` [1]
2. it fails when running `"$JtR" -test-full=0`

[1] Running slowly
https://travis-ci.org/claudioandre-br/JohnTheRipper/jobs/519251013

BTW: gcc test is not the same.

**Comment by claudioandre-br** [comment]
That's weird. Also, those line numbers look a bit off (I'm looking at the latest bleeding-jumbo).You can look at the source used by the compilation. E.g., for https://travis-ci.org/claudioandre-br/JohnTheRipper/jobs/519255612

* files are at https://github.com/claudioandre-br/JohnTheRipper/tree/316f2c993ddafd685e436024561ff00a86e6418e

Both complain: gcc and clang
https://travis-ci.org/claudioandre-br/JohnTheRipper/jobs/519255613

**Comment by claudioandre-br** [comment]
Sorry, editing previous message

**Comment by solardiz** [comment]
Are the scrypt failures in 32-bit builds only?

**Comment by claudioandre-br** [comment]
No. Failure on Travis is 64bits. BTW: you can open the logs [1], search for scrypt and press a PgUp to find all configure + `list=build-info` plus UbSan.

[1]
* clang: https://travis-ci.org/claudioandre-br/JohnTheRipper/jobs/519255612
* gcc: https://travis-ci.org/claudioandre-br/JohnTheRipper/jobs/519255613

**Comment by claudioandre-br** [comment]
I can't make it fail on gcc, linux 64 bits.

**Comment by solardiz** [comment]
So the problem is it stalls for 10 minutes, but doesn't crash, right? Is it possible clang's ASan is somehow just that slow when running scrypt?

Also, does this show up only for the "scrypt" format or also for other formats that use scrypt (such as "django-scrypt")?

**Comment by solardiz** [comment]
Here's another guess: ASan allocates truly a lot of address space (overcommits memory). If the VM has little memory, then actual writes into that memory (which happen when scrypt writes into its scratchpad memory, especially if we're testing multiple instances of scrypt with OpenMP) may make it swap aggressively and appear to stall.

**Comment by solardiz** [comment]
None of this would explain why the problem appears just now. We were probably using just as much memory with "escrypt", before the switch to the newer "yescrypt" codebase. Well, maybe we're using huge pages now and we didn't before.

**Comment by claudioandre-br** [comment]
It fails for `"$JtR" -test-full=0 --format=scrypt`

> Is it possible clang's ASan is somehow just that slow when running scrypt?

I can increase it to 30 min to check.

**Comment by solardiz** [comment]
Can you also try `"$JtR" -test-full=0 --format=django-scrypt`?

**Comment by claudioandre-br** [comment]
This needs to be tested locally. The build finished an hour ago and I can't see what happened.

That said, Jumbo 2.

**Comment by claudioandre-br** [comment]
There is no UBSAN in well or super. I can't check if they complain about DES.

**Comment by claudioandre-br** [comment]
I was able to reproduce this:
* directly inside a Virtual machine on GCE using Ubuntu Xenial
```
Testing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]... (2xOMP) 
```
* using the CI infra plus Docker in another format.
```
Testing: multibit, MultiBit Wallet [MD5/scrypt AES 32/64]... (2xOMP) 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

```

**Comment by solardiz** [comment]
@claudioandre-br Do you know how much RAM+swap those systems have? When you reproduce "directly inside a Virtual machine on GCE using Ubuntu Xenial", do you have interactive access to that VM? Can you attach with gdb and see what the process is doing when it's non-responsive? Thanks!

**Comment by solardiz** [comment]
BTW, the "32/64" reporting for "multibit" is partially wrong - it refers to the fast MD5 variation of multibit hashes, not to the slow scrypt variation of them. But I can't come up with a clean fix for that, short of splitting this into two format structs, which might very well be the right thing to do.

**Comment by solardiz** [comment]
Claudio, also in your latest "I was able to reproduce this" comment, were both builds with ASan?

**Comment by claudioandre-br** [comment]
> Claudio, also in your latest "I was able to reproduce this" comment, were both builds with ASan?

Not sure now. Anyway, I'm always running a "poor" VM. So, 4GB in the best scenario.

**Comment by solardiz** [comment]
While looking into this, I found that commit 7216d2cce66e5dc4ab7b0e90a0b6b9c7e81cb04b by @jfoug broke my original code's de-association of per-thread `local` buffers with `crypt_all` indices, so running this with a higher `max_keys_per_crypt` than the thread count would unnecessarily require correspondingly more `local` buffers. However, that commit broke this in a way that setting `max_keys_per_crypt` to higher than thread count, which the code currently doesn't do, would cause out of bounds access rather than a larger allocation. So this is definitely not the issue we're seeing here. But I'll probably revert those aspects of that commit anyway.

**Comment by solardiz** [comment]
Commit 7aeb906c40eb4094bae2ba5aee657eab916b2401 "JtR hack: don't use OpenMP inside (ye)scrypt" should reduce address space demands when running our tests, which _might_ help mitigate the issue of ASan-enabled builds _possibly_ needing too much memory.

**Comment by magnumripper** [comment]
Perhaps the salt-sorting problems we fixed recently affected this?

**Comment by solardiz** [comment]
> Perhaps the salt-sorting problems we fixed recently affected this?

Unlikely. The test vector re-ordering only affects which test vectors are used for benchmark, whereas all of them are used for self-test anyway. The benchmark duration is limited by the timer. Also, IIRC none of the test vectors looked like they have parameters so high that they'd cause trouble on a reasonable system.

**Comment by solardiz** [comment]
I think we haven't run into this issue for more than a year, so it's probably gone. Closing.
