### ISSUE TITLE
SIP does not handle "sip:*" uri

### ISSUE THREAD

**Issue by nanosonde** [openwall/john#3829]
Using the SIP trace log of SNOM phone, I have the problem that the URI looks like this "sip:*" in the authorization header field. 
However, this is not handled in JTP SIP format. 
It leads to a wrong number of fields in the SIP format.

**Comment by solardiz** [comment]
Have you tried replacing the colon with an asterisk? It looks like this logic we have in place would reintroduce the colon(s) (one or two) after initial parsing:

```c
        /* special handling for uri */
        if (!strcmp(lines[7], ""))
                sprintf(login.uri, "%s:%s", lines[5], lines[6]);
        else
                sprintf(login.uri, "%s:%s:%s", lines[5], lines[6], lines[7]);
```

Either way, please post the input to JtR that you're testing with. Thanks!

**Comment by nanosonde** [comment]
Consider this sipdump file content:
```
1.2.3.4"5.6.7.8"155350609596347633"sip.provider.com"REGISTER"sip:*"7dfb229f37d9834084f1aa5cdd1e2460"547401db"00000147"auth"MD5"e1facc132ebe3973521a83950ff54994
```

Running the sipdump2john.py on this file generated this output for use with JtR:
```
1.2.3.4-5.6.7.8:$sip$*1.2.3.4*5.6.7.8*155350609596347633*sip.provider.com*REGISTER*sip****7dfb229f37d9834084f1aa5cdd1e2460*547401db*00000147*auth*MD5*e1facc132ebe3973521a83950ff54994
```

Do you see the issue? There is no escaping for the asterisk within the uri part taking place. As the asterisk is used as the delimiter it won't work in this case as an additional field is introduced which was not intended.
The special treatment of the URI with the colon is only for the case where a port is specified within the uri.

->As the asterisk seems to be valid character in the sip uri AND the asterisk is also used a delimiter in the SIP format for John, either some kind of escaping or another delimiter character should be used.

**Comment by solardiz** [comment]
I think we have enough info here to proceed to look into this issue when one of us - perhaps @kholia - is available for that. Thanks!
