### ISSUE TITLE
zip2john: no output for encrypted archive

### ISSUE THREAD

**Issue by philsmd** [openwall/john#3975]
The following archive only gives me this output, but no hashes:
```
ver 1.0 efh 5455 efh 7875 hc_no_zip2john_output.zip/l6ue6o.gG3L PKZIP Encr: 2b chk, TS_chk, cmplen=13, decmplen=1, crc=3E611DAB
```

The password is: 
```
(9Moxf(,lR>jA/XL0*\_dafPbH~<xbLpeo@IG%[6<|QR;<JGYb@vI<^j]NOuV4]f5nge|Gj1Jsc=0`HYXzT\,i(0V#ab/E/2v)}Ig,vXU&~Z)z<j,+fG}L]xr^vvG)/LGYC]rB& |2=\%oY;~_Y)_|9RZ/#]Ok
```

Yeah, do not get scared by the password, this is just a random pkzip test script that I've used to test some edge cases for the new pkzip support in hashcat.

... but with this zip file I do not even get a hash for hashcat to test with:

[hc_no_zip2john_output.zip](https://github.com/magnumripper/JohnTheRipper/files/3197885/hc_no_zip2john_output.zip)

Thanks

cc: @s3inlc

**update**: after troubleshooting this a little bit and looking at the source code, I think it has to do with the curzip.decomp_len being very small (< 4 bytes). I didn't receive any error message/warning, so it's not very clear what is going on.

**Comment by magnumripper** [comment]
Thank you for reporting! Yes, we do have some limits but it *might* be we're disregarding this file even though it could be used - I'll look into it.

Oh and BTW @s3inlc: - Really awesome work! Kudos!  👍

**Comment by magnumripper** [comment]
We now have a notice "Skipping short file l6ue6o.gG3L" for this situation

**Comment by RadoslavL** [comment]
@magnumripper What causes the "Skipping short file" message? Too long password? Too small file size? I was testing with zip2john and I got no output as well.

**Comment by magnumripper** [comment]
@rlelchev it means the file size was less than four bytes. We could support shorter ones but it would lead to excessive false positives.
