### ISSUE TITLE
zip2john: allow more than 3 files

### ISSUE THREAD

**Issue by s3inlc** [openwall/john#3978]
As the pkzip stuff is included in hashcat now and able to get much higher speeds, it would be beneficial to have some more flexibility in zip2john. Namely, in case of only 1 byte checksums, and enough available files, a hash with 7 or 8 files could be created with the start of the file only, as then still enough data would be available to avoid easy collisions (8x8bit => 64bit).

Also when having 2 byte checksums, 3 checksums might not be enough, depending on the available hardware, so probably could be extended to 4 files (also giving 64bits then) there with the -c flag.

When I implemented the initial kernels with the 8 files, I did some hack to zip2john, but I not able to fully understand the way how zip2john handles all that, so I thought it might be better to let you decide how you could do that.

Thanks in advance :)

**Comment by magnumripper** [comment]
Right, I saw this when I looked into the hascat stuff today. We'll look into it for sure!

**Comment by magnumripper** [comment]
Bump! (so I don't forget this again)
