### ISSUE TITLE
Speed up auto-detection

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#3996]
Related to #3993 (this hit me while considering that issue). I think this might actually solve that issue as well.

I have noticed that given a huge pot file, not using the `--format` option can be extremely slow. The vast majority of formats now have "dollar-tags" (eg `$RAR$`) and *a list of tags presented in their format structs*. Perhaps it can be used to speed things up.

Pseudo-code:
```c
if (first char of line == '$' && second '$' present within 10 chars or so) {
    tag = string up to next '$';
    format(s) = scan our list of tags for tag;
} else {
    currently used auto-detect stuff
```
This will run quickly, (and within caches), while actually calling 500 formats' `valid()` will do neither.

Note: We somehow need to handle OpenCL alternatives but that logic could be similar (look for other formats also supporting this tag).

**Comment by solardiz** [comment]
Wouldn't the "format(s) = scan our list of tags for tag" need to be done for the same "500 formats" that we'd have been calling `valid()` for? Are tag comparisons really much faster than function calls? I suppose that depends on what's inside the functions.

**Comment by magnumripper** [comment]
You may well be right - it was a vague idea and I thought I'd check it out. Perhaps the only "gain" would be for the few formats that doesn't have (or demand) a tag but they are so few we'd just lose in terms of complexity.

I will try out some actual code real quick and either close this or post back.

**Comment by magnumripper** [comment]
Tried it, it was faster but not worth it. I saw evidence of more important stuff to consider though (profiling needed), will revisit that.
