### ISSUE TITLE
Reduce, then remove dependency on OpenSSL

### ISSUE THREAD

**Issue by solardiz** [openwall/john#3998]
We should reduce the number of formats that use OpenSSL by unconditionally(?) switching them to our own crypto primitives where we have those. Then add a way to build without OpenSSL, by disabling the few remaining OpenSSL-dependent formats in such builds. Maybe add compile-time warnings about that. If those formats are numerous or/and deemed important, then we should fail a build by default when there's no OpenSSL, and suggest/require explicit `--without-openssl` or `--disable-openssl` for the build to succeed anyway.

I think not using OpenSSL's crypto primitives unconditionally might have slight performance impact on uses of scalar SHA-256 and SHA-512, because OpenSSL's code for those has SIMD versions of the message scheduling step, whereas our scalar SHA-256 and SHA-512 code is in fact purely scalar. We might want to measure the impact of this vs. the savings of having avoided OpenSSL's context zeroization on `SHA*`_Final()`.

Assigning to @magnumripper at least for the autoconf changes involved in this. I will probably help with changes related to #3917 (if any).

**Comment by magnumripper** [comment]
This is a dupe of #2356

**Comment by magnumripper** [comment]
From #2356 (this issue is a dupe of that one):
*... the penalty for MD4/5 and SHA-1/SHA-512 is more significant than I would have thought ...*

**Comment by solardiz** [comment]
> the penalty for MD4/5 and SHA-1/SHA-512 is more significant than I would have thought

I think we need to start looking at specific performance numbers. For MD4/5, I don't expect much slowdown, if any, but perhaps we need to take care of #3917 (and some related optimizations I have in mind, such as adding an `InitUpdate` call) first or at the same time.

Also, ideally our uses of scalar implementations of primitives should be in relatively non-performance-critical places.

**Comment by magnumripper** [comment]
For less changes in the plenty of existing formats, perhaps we could make `Init()` a macro?

**Comment by magnumripper** [comment]
I could start with adding `--disable-openssl` (keeping it default enabled for now) even though using that will not build properly (we'll soon have it build fine although disable a whole bunch of formats). Then we can work out the issues over time without making a fork.

**Comment by solardiz** [comment]
> For less changes in the plenty of existing formats, perhaps we could make `Init()` a macro?

Yes, but this is probably less efficient: more code in the callers, and we'd need a flag and a runtime check to precompute some operations on the first few steps when operating on a just-initialized context.

> I could start with adding `--disable-openssl` (keeping it default enabled for now) even though using that will not build properly

This is not ideal, but I hope you'll get it to build properly (without many formats) soon enough for this approach to work fine for us. So please proceed. Thanks!

**Comment by solardiz** [comment]
This has been taken care of in #4654.

> If those formats are numerous or/and deemed important, then we should fail a build by default when there's no OpenSSL,

This is what happens now.

> and suggest/require explicit `--without-openssl`

This isn't currently suggested by the failing `./configure` - we should probably add it to the message in there, along with a warning that much functionality will be excluded.

The `--without-openssl` option is currently documented in `./configure --help` output, `INSTALL`, and `README-MIC`.

We should also work on further reducing our usage of OpenSSL - enable more formats to build without OpenSSL (e.g., I think I saw one that directly uses OpenSSL's AES, but could probably be switched to our wrappers and re-enabled) and use our own crypto primitives in more cases even when building with OpenSSL. I dislike how our PBKDF2-HMAC-SHA1 code accesses the internals of OpenSSL-provided context structures - this might very well break with some OpenSSL update - but if we switch it to using in-tree SHA-1 it will be correct. Also, our scalar MD4 and MD5 are apparently often slightly faster than OpenSSL's due to us not zeroizing the context structure in `*_Final`, except perhaps on non-mainstream CPUs with these primitives in hardware and supported by OpenSSL. We also have our own DES implementations, but many formats rely on OpenSSL's.

**Comment by solardiz** [comment]
> enable more formats to build without OpenSSL (e.g., I think I saw one that directly uses OpenSSL's AES, but could probably be switched to our wrappers and re-enabled)

That was the `telegram` format, and also `telegram-opencl`, now taken care of in #4656
