### ISSUE TITLE
Get AppVeyor configs into our tree

### ISSUE THREAD

**Issue by solardiz** [openwall/john#3999]
Claudio, I might not fully understand this, and if so please correct me, but I think that we currently have our CircleCI and Travis configs in the tree, but not our AppVeyor configs. I think we should add the latter as well, especially given that we use AppVeyor as more than CI, but also to produce usable Windows builds.

**Comment by claudioandre-br** [comment]
> I think that we currently have our CircleCI and Travis configs in the tree, but not our AppVeyor configs. 

You are correct. I assigned @magnumripper, he has to perform all necessary tasks (sign up, CI set up, tokens, ...).

**Comment by claudioandre-br** [comment]
AppVeyor builds (jobs) are sequential, so, "upstream" tests should be fast.

**Comment by solardiz** [comment]
Claudio, I thought you could simply make a PR to this repo with the files you already have. Wouldn't this make sense? Is the signup for AppVeyor currently yours and needs to be changed to magnum's? But you're the one who's been managing it so far and you readily know how, so why would we bother magnum with this? I'm confused.

**Comment by claudioandre-br** [comment]
> Claudio, I thought you could simply make a PR to this repo with the files you already have. Wouldn't this make sense? 

No.

> Is the signup for AppVeyor currently yours and needs to be changed to magnum's?

Well, I have one. It is mine. A new one is going to belong to him. Two different things. Two accounts.

> why would we bother magnum with this?

Magnum is someone else. I can not decide in his place.

**Comment by solardiz** [comment]
Claudio, why wouldn't it make sense to include in this repo the files you already have and use with AppVeyor? Aren't they sort of part of our source code (a part relevant to making our Windows builds)?

I'd also like to hear from magnum. Thanks!

**Comment by claudioandre-br** [comment]
Anyone can copy and use the "files" (they are GPL). But it is not enough,
nothing will happen after a PR containing these files. No builds, no tests,
...

Em sáb, 25 de mai de 2019 às 18:45, Solar Designer <notifications@github.com>
escreveu:

**Comment by magnumripper** [comment]
Perhaps we should escalate the "move repo to openwall org" issue? Completing that would be awesome.

**Comment by solardiz** [comment]
> nothing will happen after a PR containing these files got merged: no builds, no tests, no package, ...

Of course. I merely wanted to have the files archived as part of our tree, so that we can easier check how exactly the builds are made and can recreate the setup later if need be. I saw you already made a PR like this today (haven't checked it yet), thanks!

> Perhaps we should escalate the "move repo to openwall org" issue? Completing that would be awesome.

I agree.

**Comment by solardiz** [comment]
Claudio, now that the stripped version of the file has been merged, can you please send us a PR with the advanced file you actually use now? Thanks!

**Comment by solardiz** [comment]
I had created this issue 5 years ago, but I was and still am confused. We've since moved to the Openwall org on GitHub, and we have this in here:

```
$ git log .ci/appveyor.yml
commit cd864cdf54383f9a99b71f5409db860d7577ec55
Author: Claudio André <claudioandre.br@gmail.com>
Date:   Thu Oct 31 22:25:11 2019 -0300

    CI: update images used for CI
    
    To be up to date with stable and LTS software.
```

Is this file just for historical preservation (which may be fine) or is it in use?

Do we use AppVeyor at all? As far as I'm aware, not in this repo, but we do make Windows builds in the `john-packages` repo nearby - what do they use now?

Any suggested action regarding this issue? (Simply closing it is a possible action, too.)

**Comment by ghost** [comment]
> Do we use AppVeyor at all?

No. 

So, you can close the issue and remove the file `.ci/appveyor.yml`. Also do the same for the `.travis.yml` file and folder.

*****

[EDITED]

I said 'may', but I mean 'should' or 'must'. The project doesn't gain anything if we keep this old material around.

**Comment by ghost** [comment]
>  we do make Windows builds in the john-packages repo nearby - what do they use now?

There is a `john-packages/deploy/Windows-Delivery.yml` which is the recipe for compiling on Windows. 

It is the recipe/script used to create the Windows package.

**Comment by solardiz** [comment]
> So, you can close the issue and remove the file `.ci/appveyor.yml`. Also do the same for the `.travis.yml` file and folder.
> 
> [EDITED]
> 
> I said 'may', but I mean 'should' or 'must'. The project doesn't gain anything if we keep this old material around.

While we don't use those CI setups now, I think the files are somewhat valuable in that they allow to re-enable such usage easier, by us or in a fork. A problem is they get progressively out of date, so wouldn't be directly usable without further edits.

**Comment by ghost** [comment]
To some extent and/or over time, they will become useless. 

For example:
- Image versions, Visual Studio version, Docker image, ..., all of that dies. Deprecation, EOL, death. 

But Okay to keep them.
