### ISSUE TITLE
Device-side mask mode: Revisit the fmt_reset() logic

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4012]
This isn't quite perfected yet. It's a two-step rocket:

1. If mask positions or ranges changed at all and `FMT_MASK`, we have to call `crk_process_buffer()` followed by format's `reset()` for updating the GPU-side. Obviously, we currently do.
2. Most or all formats currently always (re-)auto-tune whenever the above happens. This is **not** needed unless the "mask multiplier" (the actual one, not the requested) changed.

So going from eg. `?a?a?d` to `?a?d?a` using a device-side mask format, we always need to call `reset()` but within that function (so unfortunately in every such format, unless I find some short-cut) we should have logic for detecting whether a new auto-tune is needed or not. It's only needed in case the new actual "mask multiplier" is significantly different from the previously used one. Simple example: Going from `?u?l?l` to `?l?l?l` would not change the multiplier so would not need re-tuning.

**Comment by magnumripper** [comment]
This would ~~probably~~ close #3516 as well

**Comment by solardiz** [comment]
Isn't this too invasive and risky to be "Definitely 1.9.0-jumbo-2 material"?

**Comment by magnumripper** [comment]
I think not. It's not complicated really, and it's easily tested.

**Comment by magnumripper** [comment]
Waiting is good. I'm starting to see the light. I'm pretty sure we can do ALL special logic in `opencl_autotune.h` and that's a terrific fact - all formats' `reset()` will be trivial (though a bit less so for internal mask formats currently but again I think I see the light). Still a couple of hours from posting first PR and I'm about to take a break now.
