### ISSUE TITLE
CFLAGS_MAIN should'nt have -mSIMD hint

### ISSUE THREAD

**Issue by ghost** [openwall/john#4013]
Below you can see the content of `CFLAGS_MAIN` in a `make` run:
* From:
`$(CC) -DMAIN_NAME=\"$(MAIN_NAME)\" symlink.c $(CFLAGS_MAIN) -o ../run/john.exe`

* To:
`
gcc -DMAIN_NAME=\"john-avx512bw.exe\" symlink.c -DAC_BUILT -DJOHN_AVX512BW -c -m64 -g -O2 -DARCH_LITTLE_ENDIAN=1 -DPREFER_FLOCK  -Wall -Wno-format-overflow -Wno-format-truncation -fno-omit-frame-pointer --param allow-store-data-races=0 -Wno-deprecated-declarations -Wunused-but-set-variable -std=gnu89 -Wdate-time -D_GNU_SOURCE -D__CYGWIN64__ -D__CYGWIN32__  -fopenmp   -mavx512bw -fno-asynchronous-unwind-tables -DOMP_FALLBACK -DOMP_FALLBACK_BINARY="\"john-avx512bw-non-omp\"" -DCPU_FALLBACK -DCPU_FALLBACK_BINARY="\"john-avx2\""  -DCL_SILENCE_DEPRECATION -DHAVE_OPENCL  -o ../run/john.exe
`

* Problems:
`-mavx512bw` and the produced binary is worthless (`john.exe: cannot execute binary file: Exec format error`).

**Comment by magnumripper** [comment]
This doesn't happen to me. How did you run configure? This may be a bug with the `--enable-simd=...` option in case that was what you used.

**Comment by magnumripper** [comment]
> This may be a bug with the `--enable-simd=...` option in case that was what you used.

No, that's not it:
```
$ ./configure -enable-werror
(...)
$ grep -i avx2 Makefile
CFLAGS_MAIN = -DAC_BUILT -DJOHN_AVX2 $(CFLAGSX)
CFLAGS = -DAC_BUILT -mavx2 -DJOHN_AVX2 $(CFLAGSX)
ASFLAGS = -DAC_BUILT -m64  -DARCH_LITTLE_ENDIAN=1  -mavx2 -DJOHN_AVX2 -c -fopenmp   -DUNDERSCORES -DBSD -DALIGN_LOG
# $ make -s windows-tiny-link-to-john MAIN_NAME=john-avx2.exe

$ ./configure --enable-simd=avx512bw -enable-werror && make -s clean && make -sj8
(...)
$ grep -i avx512 Makefile
CFLAGS_MAIN = -DAC_BUILT -DJOHN_AVX512BW $(CFLAGSX)
CFLAGS = -DAC_BUILT   -mavx512bw -DJOHN_AVX512BW $(CFLAGSX)
ASFLAGS = -DAC_BUILT -m64  -DARCH_LITTLE_ENDIAN=1    -mavx512bw -DJOHN_AVX512BW -c -fopenmp   -DUNDERSCORES -DBSD -DALIGN_LOG
```

**Comment by magnumripper** [comment]
Looks like your `packaging/build.sh` erroneously uses `CPPFLAGS` for adding `-mavx512bw` (Yes I suggested to do so long ago, but it's not correct). This will end up in CFLAGS_MAIN as well. Use `--enable-simd=avx512bw` instead!
