### ISSUE TITLE
zip2john producing large (~90MB) hashes

### ISSUE THREAD

**Issue by zheater** [openwall/john#4018]
Trying to open a zip file containing several pdfs. I'm using a version freshly cloned from here.

Typing "zip2john file.zip > ziphash.hash" creates a 90MB hash file. Typing "zip2john file.zip -o pdf1.pdf > ziphash.hash" creates a hash between 50MB and 95MB depending on which file I try.

Any thoughts?

**Comment by solardiz** [comment]
What issue are you reporting? It is normal for those "hashes" to be this large as they embed the encrypted data.

You say you're able to get a 95MB "hash" from a file in an archive, but only a 90MB hash from the full archive. This 5MB difference is puzzling. I'd expect the full archive to produce a "hash" that is at least as large as one file's.
