### ISSUE TITLE
Review ssh formats

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4028]
See https://www.openwall.com/lists/john-users/2019/06/10/1 and #4026 which added FMT_NOT_EXACT to the GPU format while the CPU format apparently already had that but doesn't need it?!

- [ ] Both formats should set/clear FMT_NOT_EXACT at every `set_salt()` according to the actual conditions for current type. ~Should we instead remove FMT_NOT_EXACT from the CPU format or are *some* of the latter's algos  producing FP's while others doesn't (IIRC the CPU format supports more algos than the GPU format)?~
- [ ] Wouldn't it be trivial to add the needed extra tests to the GPU format, simply post-processing on CPU using code shared by the CPU format?
- [ ] From #4026: "*Another issue is that ssh_fmt_plug.c has custom `split` that converts the "hashes" to all-lowercase, and (correctly for it) sets `FMT_SPLIT_UNIFIES_CASE`. opencl_ssh_fmt_plug.c does neither. I see no reason for the lowercasing there - those are our own custom format "hashes", so we can enforce a particular case - but maybe it changed during our development? Since I don't know the history of this and have no time anyway, I'm not fixing it with this PR. But this inconsistency between the two formats is probably wrong.*"

**Comment by solardiz** [comment]
> are _some_ of the [CPU format]'s algos  producing FP's while others doesn't

I guess this is the case. For some algos `cmp_exact` checks padding or something, while for others it merely returns 1. Maybe we can conditionally drop `FMT_NOT_EXACT` from the format's struct after having loaded "hashes" that are only of the exact types.

**Comment by magnumripper** [comment]
> Maybe we can conditionally drop `FMT_NOT_EXACT` from the format's struct after having loaded "hashes" that are only of the exact types.

Ideally that flag should be set or cleared at each `set_salt()` then. IIRC cracker.c used a stale copy of `format.params` but Jumbo already dropped that for things like this to work.
