### ISSUE TITLE
Unknown option: "--internal-encoding=ISO-8859-1"

### ISSUE THREAD

**Issue by githubranduser** [openwall/john#4030]
John has been running on my system for over a month, up until 1.9.0 jumbo, I could at least check the status of my run ... now i cannot, I get this:

Unknown option: "--internal-encoding=ISO-8859-1"

This was working on previous versions and is now preventing me from checking in on things that are presenting running.

John build-info response:

Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 XOP AC OMP
SIMD: XOP, interleaving: MD4:2 MD5:2 SHA1:2 SHA256:2 SHA512:1
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: XOP
CPU fallback binary: john-avx-omp
OMP fallback binary: john-xop-non-omp
$JOHN is /usr/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 8.3.0
GNU libc version: 2.28 (loaded: 2.28)
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

OpenCL Response:
Section [opencl-devices] not found.
help[:WHAT], subformats, inc-modes, rules, externals, ext-modes, ext-hybrids,
ext-filters, ext-filters-only, build-info, hidden-options, encodings,
formats, format-details, format-all-details, format-methods[:WHICH],
format-tests, sections, parameters:SECTION, list-data:SECTION,
<conf section name>

**Comment by ghost** [comment]
> John has been running on my system for over a month

I would say much more than a month since `-internal-encoding` was dropped in https://github.com/magnumripper/JohnTheRipper/commit/f5b2b19b429e724f277ea41e68a3983fa67efa7e . In fact, the version you **were** using is (at least) three years old.

It is not clear to me if you are specifying "--internal-encoding=ISO-8859-1" in the command line or if it is inside the `REC` file, for example. The commit above says it "still recognize it in restored sessions". So:

* Could you please clarify? Are you using `--internal-encoding` instead of `-internal-codepage`?

**Comment by githubranduser** [comment]
It's possible, I installed the OS a little over 30 days ago.

This was all I did:

Created a hash file with contents like this:

root:$dynamic_25$hash

Then I started it like this:

john --format=dynamic_25 --session=thing --fork=32 hash.txt

Then I have 32 processes running like this:

root      4138 99.9  0.0 208856 29440 ?        RN   May17 42788:21 john --format=dynamic_25 --session=thing --fork=32 hash.txt

So, I never supplied anything in regards to anything with --internal-encoding

I could have sworn the version I had installed was 1.8.0.13-jumbo-1-0; I apt-get updated yesterday and that's when john stopped working. Before that, I should have gotten whatever the current available version was that was there in around March or April of 2019.

**Comment by ghost** [comment]
I was able to reproduce it:
* I run a very old version of JtR (2015 Sept): 
  * `$JtR --format=dynamic_25 --session=ida --fork=32 hash.txt`
* I try to get the status using an updated version of JtR:
```
$ bleeding/run/john-new --status=ida
Unknown option: "--internal-encoding=UTF-8"
```
The `--internal-encoding` is seen inside `.REC` file. I'm using:
- `John the Ripper 1.8.0-jumbo-1-3875-ge6655e1 OMP [linux-gnu 64-bit AVX2-ac]
`

versus
- `John the Ripper 1.9.0-jumbo-1+bleeding-5b30bc0 2019-06-13 23:43:08 +0200 OMP [linux-gnu 64-bit x86_64 AVX2 AC]`

*****

I'm afraid I don't see a bug here. The fix is: stop and restore the session run using the new and released JtR. Probably, not now, I would say.

**Comment by ghost** [comment]
Maybe we can review how JtR is handling `--internal-encoding` versus `--internal-codepage` inside a `.REC`, but only if `--internal-encoding`  was a "released" command line option.

**Comment by githubranduser** [comment]
I'm afraid I'm super new to this, how can I stop my current session and resume it without the command?

**Comment by ghost** [comment]
It (the capacity to recognize `--internal-encoding` in restored sessions) is not working either.

```
$ $JtR --restore=ida
Unknown option: "--internal-encoding=UTF-8"
```

Of course, you can stop John the Ripper and:
```
sed -i 's/--internal-encoding/--internal-codepage/g' *.rec 
```

Then:
```
$JtR --restore=ida
```

**Tested and works.**
****
NOTE: I'm not advising you to do this. At least, backup everything before running these commands.

**Comment by solardiz** [comment]
I think we meant to support seamless restoring of 1.8.0-jumbo-1's sessions with 1.9.0-jumbo-1, or at least we never discussed that this wouldn't work. So I think we should treat this as a bug, and fix it.

**Comment by magnumripper** [comment]
I'm pretty sure there's code in there that is supposed to handle the deprecated option name. Will look into it.

**Comment by magnumripper** [comment]
Apparently support was dropped in f5b2b19b and code was left in `recovery.c` that was supposed to fix resuming but it was possibly never tested :-/

Not sure what to do now, it's kind of too late to be reasonable to fix now. [Claudio's suggestion](https://github.com/magnumripper/JohnTheRipper/issues/4030#issuecomment-502481589) is the best workaround.

**Comment by githubranduser** [comment]
I shall do that, thank you for your help!!!!

**Comment by solardiz** [comment]
> it's kind of too late to be reasonable to fix now.

I think it's still best to fix this now, given that the fix is probably trivial. It isn't unreasonable that someone would be upgrading from 1.8.0-jumbo-1 to bleeding-jumbo or to 1.9.0-jumbo-2, skipping the 1.9.0-jumbo-1 release.
