### ISSUE TITLE
Improve reporting of OpenCL LWS & GWS

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4034]
1. I'd like LWS and GWS to be reported in a form immediately usable for copy-paste onto the command-line, so "LWS=... GWS=...".

2. I'd like to have them printed even when not printing the cracked passwords. I often have to use "-v=1" to disable printing cracked passwords when I expect to have lots of them, but to have LWS and GWS printed I need at least "-v=4". Maybe the best way to tackle this is to introduce a way to mute the cracked passwords from the command-line without lowering verbosity for JtR's other messages - e.g., I am similarly unhappy that when I use "-v=1" to mute the cracked passwords I also miss warnings about less than full buffers. Or alternatively we could want to have Device name and LWS & GWS printed even at verbosity level 1. This is fairly essential information similar to what SIMD type is being used on CPU, and we do print that as part of the "Loaded ..." line at any verbosity level.

**Comment by ghost** [comment]
While at it, at least for the "mandatory" `LWS=... GWS=...` reporting:
- print the information only once (autotune runs more than once in some situations).

**Comment by solardiz** [comment]
There's also custom LWS & GWS printing code in:
```
opencl_DES_bs_b_plug.c
opencl_DES_bs_f_plug.c
opencl_DES_bs_h_plug.c
opencl_lm_b_plug.c
opencl_mscash2_helper_plug.c
opencl_mysqlsha1_fmt_plug.c
opencl_rawmd4_fmt_plug.c
opencl_rawmd5_fmt_plug.c
opencl_rawsha1_fmt_plug.c
opencl_salted_sha_fmt_plug.c
opencl_sl3_fmt_plug.c
```
Moreover, `opencl_mscash2_helper_plug.c` prints a 0-based device number (not yet updated to our new 1-based scheme).

> print the information only once (autotune runs more than once in some situations).

In what cases and why does autotune run more than once, and why would we only care to see the first run's results?

**Comment by ghost** [comment]
> In what cases and why does autotune run more than once, and why would we only care to see the first run's results?

On GPU mask mode, for example (e.g., on a size change). It could be annoying, I guess, when I run using a `-verb=1`. And, it can be confusing. Why it was LWS=N? Why it is LWS=N*2 now?

**Comment by solardiz** [comment]
I think it'd be even more confusing to have LWS/GWS printed just once if they become obsolete the next moment and there isn't another message saying so.

**Comment by ghost** [comment]
In this case, nothing have to be done to control how many times it will be printed.

**Comment by magnumripper** [comment]
> * I'd like LWS and GWS to be reported in a form immediately usable for copy-paste onto the command-line, so "LWS=... GWS=...".

Good idea.

> * I'd like to have them printed even when not printing the cracked passwords. I often have to use "-v=1" to disable printing cracked passwords when I expect to have lots of them, but to have LWS and GWS printed I need at least "-v=4". Maybe the best way to tackle this is to introduce a way to mute the cracked passwords from the command-line without lowering verbosity for JtR's other messages - e.g., I am similarly unhappy that when I use "-v=1" to mute the cracked passwords I also miss warnings about less than full buffers. Or alternatively we could want to have Device name and LWS & GWS printed even at verbosity level 1. This is fairly essential information similar to what SIMD type is being used on CPU, and we do print that as part of the "Loaded ..." line at any verbosity level.

I've been encountering similar problems with the `--verbosity` option. Perhaps we should drop it and introduce a bunch of separate options like `--mute-foo`, `--mute-bar` for things that are printed by default, and `--show-baz`, `--show-bat` for things that are not. However, they ideally would need an options flag each and we're running out of them even though Jumbo uses 64-bit flags. I've been meaning to open an issue for that... how can we get around it?

**Comment by magnumripper** [comment]
I have actually played with the idea of making Jumbo's options flags 128-bit (and simply losing some checks if that's not supported, like on a 32-bit build) but that's not quite the final solution - and it has some caveats, eg. we can't write that big integers in source simply as `0x00001000000000000000000000000000ULLL` but rather as something like `(0x0000100000000000ULL << 64)`

**Comment by magnumripper** [comment]
This is a bit of an issue hi-jack but we could want these and more:
```
--mute-cracks
--mute-rules-logging (this should be default for `--pipe` mode so we may also need `--show-rules-logging`)
--mute-mode-info (eg. for incremental and subsets modes printing state information)
--mute-buffer-fill-warnings

--show-autotune
--show-worksizes
```
BTW @solardiz I never understood how you can not LOVE tab completion - the above would be very tedious without it.

**Comment by magnumripper** [comment]
On another note I tried to start showing LWS/GWS at normal verbosity in 6ea7946f0 but I think I have seen it not always show when expected (I did mute it for incremental length mask, like Claudio said). But I simply haven't had time to look into it.

**Comment by magnumripper** [comment]
Note to self: We should add some new separate issues from the discussion above.

**Comment by solardiz** [comment]
Maybe `--verbosity` could accept not only a number, but also a list of things to show or mute, e.g. `--verbosity=1,ws` would set level 1 but enable printing of LWS/GWS and `--verbosity=-passwords` or `-v=-p` in its shortest form (working as long as it doesn't clash with something else) would keep default verbosity level but mute printing of the cracked passwords.
