### ISSUE TITLE
Simplify or avoid OpenCL kernel copying

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4038]
As discussed in https://github.com/magnumripper/JohnTheRipper/issues/4037#issuecomment-506002082 we currently copy OpenCL kernels from `src/opencl` to `run/kernels` using unnecessarily complicated `make` magic. We should do it simpler, or maybe not do it at all but instead maintain those kernels under `run/kernels` (or call it `run/opencl`?) right away. We already have some other source files reside under `run` in our repository - e.g. `john.conf`.

**Comment by solardiz** [comment]
I assigned this to magnum (and am OK with this not being worked on right away since magnum is unavailable), but I'd also like to hear Claudio's thoughts on the matter.

**Comment by magnumripper** [comment]
Simply moving `src/opencl` to `run/kernels` sounds like a good idea. A problem is that several `opencl_something.h` are also needed in `src`. Can we use symlinks for that (real file in `src`, symlink in `run/kernels`), or will that be a problem under Windows?

**Comment by solardiz** [comment]
Symlinks could be problematic under Windows (and you'd want to symlink in the other direction, so that `run` is usable on its own). We can probably use `#include "../run/kernels/opencl_something.h"`.

We might also want to call the directory `run/opencl` rather than `run/kernels`.

**Comment by magnumripper** [comment]
Right. I'll produce a PR.
