### ISSUE TITLE
diskcryptor2john.py doesn't work under Windows

### ISSUE THREAD

**Issue by Heinz-Olaf** [openwall/john#4042]
I took a test the other day.
1 USB flash drive and 1 external USB-SSD hard drive. Both: NTFS, no bootable, 1 partition each.
I used DiskCryptor GUI v. 1.1.846 and encrypted complete disks.
Algorithm: AES+Twofish or AES (1 time with and 1 time without US DOD 5220.22 M). So far so good.
After that I created a dd-image with FTK 4.2 and (later) with X-Ways 19.4 under Windows.

Now I started diskcryptor2john.py under Windows (python 2.7 installed) or Linux (also python 2.7).

In all cases I got the following message:
!!! Low entropy detected - is this really an encrypted DiskCryptor volume header? !!!

What am I doing wrong???

**Comment by Heinz-Olaf** [comment]
Okay. Okay. It runs under linux. Was my mistake with kraptx. But under windows script doesn't work.

**Comment by solardiz** [comment]
I think it's normal and expected that "under windows script doesn't work." It needs access to the raw disk via a pathname, and that isn't available under Windows. The script's usage instructions give device names for Linux.

Closing.

**Comment by magnumripper** [comment]
Perhaps mention in some docs?

**Comment by solardiz** [comment]
This is already mentioned in `doc/DiskCryptor-HOWTO.md`: "The `diskcryptor2john.py` program requires Linux to run." (Actually, it will probably run on Windows if the disk/partition is dumped into a file from Linux or another such system first.)

Maybe we should rename that file to be more consistent with others; I suggest `README-DiskCryptor`.
