### ISSUE TITLE
oldoffice-opencl, Insufficient work. Cannot distribute work among nodes!

### ISSUE THREAD

**Issue by dosoos** [openwall/john#4055]
##John Version:
\# john
John the Ripper 1.9.0-jumbo-1+bleeding-9b4335e7c 2019-07-18 11:52:24 +0200 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2019 by Solar Designer and others
Homepage: https://www.openwall.com/john/

##Running Error Command:
john --format=oldoffice-opencl --fork=2 --mask=?a test.hash
while say me:
Insufficient work. Cannot distribute work among nodes!
i have multiple opencl device, dont't tell me not have enough opencl device

##Running Success Command:
john --format=oldoffice-opencl --mask=?a test.hash
john --format=oldoffice-opencl --fork=2 --mask=?a?a test.hash
john --format=oldoffice-opencl --fork=4 --mask=?a?a test.hash
john --format=oldoffice-opencl --fork=6 --mask=?a?a test.hash
etc...
it is all success, so i think client distribution password range have some issue

##My "test.hash" Content:
xxooxxoo.file:$oldoffice$0*66fff42aaf5231cd7cb14cf410d2a443*d143df50c79960663c127997433aaeca*5dc969945f79f6f40ff9044cc41c1ac4:::::test.hash

**Comment by ghost** [comment]
> ```
> john --format=oldoffice-opencl --fork=2 --mask=?a test.hash
> ```
> while say me:
> Insufficient work. Cannot distribute work among nodes!
> i have multiple opencl device, dont't tell me not have enough opencl device

John the Ripper is saying you don't have enough _work_, _keys_, _plaintexts_ to distribute between your two GPUs (OpenCL devices). And it is right! JtR will produce only 95 candidates.

```
$  john --mask=?a --stdout
a
[...]
|
95p 0:00:00:00 100.00% (2019-07-23 19:53) 250.0p/s |
```
