### ISSUE TITLE
configure  error :JtR requires libssl being installed

### ISSUE THREAD

**Issue by netzeng** [openwall/john#4058]
[root@app src]# ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether to compile using MPI... no
checking for gcc... gcc

checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
checking for arch.h alternative... x86-64.h
checking for byte ordering according to target triple... little
checking supplied paths for OpenSSL...  
checking additional paths for OpenSSL... none
checking openssl/opensslv.h usability... yes
checking openssl/opensslv.h presence... yes
checking for openssl/opensslv.h... yes
checking for SSL_CTX_new in -lssl... no
configure: error: in `/root/john/src':
configure: error: JtR requires libssl being installed
See `config.log' for more details
[root@app src]# JtR requires libssl being installed
bash: JtR: command not found
[root@app src]# 
[root@app src]# ./configure[root@app src]# ./configure
bash: ./configure[root@app: No such file or directory
[root@app src]# ./confugire
bash: ./confugire: No such file or directory
[root@app src]# ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether to compile using MPI... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking additional paths...  -L/usr/local/lib -I/usr/local/include
checking arg check macro for -m with gcc... yes
checking arg check macro for -Q with gcc... yes
checking if gcc supports -funroll-loops... yes
checking if gcc supports -Os... yes
checking if gcc supports -finline-functions... yes
checking if gcc supports -Og... yes
checking if gcc supports -Wall... yes
checking if gcc supports -Wno-stringop-truncation... no
checking if gcc supports -Wno-format-overflow... yes
checking if gcc supports -Wno-format-truncation... yes
checking if gcc supports -Wno-tautological-constant-out-of-range-compare... no
checking if gcc supports -fno-omit-frame-pointer... yes
checking if gcc supports --param allow-store-data-races=0... yes
checking if gcc supports -Wno-deprecated-declarations... yes
checking if gcc supports -Wformat-extra-args... no
checking if gcc supports -Wunused-but-set-variable... yes
checking if gcc supports -Qunused-arguments... no
checking if gcc supports -std=gnu89... yes
checking if gcc supports -Wdate-time... yes
checking if gcc supports -m64 w/ linking... yes
checking for 32/64 bit... 64-bit
checking additional paths (64 bit)...  -L/usr/local/lib64 -L/usr/lib64 -L/lib64
checking whether ln -s works... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for a sed that does not truncate output... /usr/bin/sed
checking for GNU make... make
checking whether make sets $(MAKE)... yes
checking how to run the C preprocessor... gcc -E
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for sort... /usr/bin/sort
checking for find... /usr/bin/find
checking for perl... /usr/bin/perl
checking for ar... ar
checking for strip... strip
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking if pkg-config will be used... no
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of wchar_t... 4
checking size of int *... 8
checking size of void *... 8
checking for extra ASFLAGS... None needed
checking for X32 ABI... no
checking special compiler flags... Intel x86
configure: Testing build host's native CPU features
checking for MMX... yes
checking for SSE2... yes
checking for SSSE3... yes
checking for SSE4.1... yes
checking for SSE4.2... yes
checking for AVX... yes
checking for XOP... no
checking for AVX2... yes
checking for AVX512F... yes
checking for AVX512BW... yes
checking for arch.h alternative... x86-64.h
checking for byte ordering according to target triple... little
checking supplied paths for OpenSSL...  
checking additional paths for OpenSSL... none
checking openssl/opensslv.h usability... yes
checking openssl/opensslv.h presence... yes
checking for openssl/opensslv.h... yes
checking for SSL_CTX_new in -lssl... no
**configure: error: in `/root/john/src':
configure: error: JtR requires libssl being installed
See `config.log' for more details**
[root@app src]#

**Comment by solardiz** [comment]
It is true that "JtR requires libssl being installed", so there's no issue here.

Can we somehow improve the error reporting here to be more helpful?

Maybe we should refer to doc/INSTALL from configure's error message, and to INSTALL-UBUNTU and INSTALL-FEDORA and INSTALL-WINDOWS from there. Right now, doc/INSTALL does mention needing libssl and gives Debian/Ubuntu package names as an example, but it does not refer to the other INSTALL-something files - perhaps we should improve that.

**Comment by netzeng** [comment]
[root@app src]# cat /etc/*release*
CentOS Linux release 7.6.1810 (Core) 
Derived from Red Hat Enterprise Linux 7.6 (Source)
cat: /etc/lsb-release.d: Is a directory
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core) 
CentOS Linux release 7.6.1810 (Core) 
cpe:/o:centos:centos:7
[root@app src]#

**Comment by netzeng** [comment]
[root@app src]# yum install libssl*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
base                                                                                                    | 3.6 kB  00:00:00     
epel                                                                                                    | 5.3 kB  00:00:00     
extras                                                                                                  | 3.4 kB  00:00:00     
updates                                                                                                 | 3.4 kB  00:00:00     
(1/2): epel/x86_64/updateinfo                                                                           | 997 kB  00:00:00     
(2/2): epel/x86_64/primary_db                                                                           | 6.8 MB  00:00:01     
Package 1:openssl-libs-1.0.2k-16.el7_6.1.x86_64 already installed and latest version
Package 1:dovecot-2.2.36-3.el7.x86_64 already installed and latest version
Package nss-3.36.0-7.1.el7_6.x86_64 already installed and latest version
Package dcap-tunnel-ssl-2.47.12-4.el7.x86_64 already installed and latest version
Package openssl098e-0.9.8e-29.el7.centos.3.x86_64 already installed and latest version
Nothing to do

**Comment by netzeng** [comment]
[root@app src]# yum install libssl-dev
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
No package libssl-dev available.
Error: Nothing to do
[root@app src]#

**Comment by solardiz** [comment]
Maybe we should rename INSTALL-FEDORA to INSTALL-REDHAT, so that people would know it also applies to RHEL? OTOH, now there's also Red Hat CoreOS, and I don't know what would apply to it. And people might not associate their CentOS with Red Hat. And there's the `yum` vs. `dnf` difference for RHEL up to 7 vs. newer Fedora, although I think there's still a `yum` wrapper even in the latest?

@netzeng `yum install openssl-devel` will work for your system. For future occasions, please note that our use of GitHub isn't as a support forum, but is rather to track bugs, hence this issue is now tagged "invalid".
