### ISSUE TITLE
"Almost done" printed for all forks

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4059]
Single crack's message "Almost done: Processing the remaining buffered candidate passwords, if any." introduced with 86185f8aaac6e9b9cc55601ffcbe62fe1d43e073 is printed by all forked processes, whereas batch mode's "Proceeding with single, rules:Single" is printed only by the main process. Perhaps the "Almost done" message should also be limited to only the main process or/and both types of these message(s) printed by all processes and preceded with node numbers like status lines are.

**Comment by magnumripper** [comment]
I think this may be fixed already in my soon-PR branch for fixing a bunch of issues (self-test without mask while benchmarking with mask etc.) - let's keep this open until that is merged.
