### ISSUE TITLE
zip2john: DA field empty for ZipCrypto Deflate encrypted file

### ISSUE THREAD

**Issue by strarsis** [openwall/john#4063]
@magnumripper, @jfoug, @kholia, @loverszhaokai, @frank-dittrich, @claudioandre-br, @philsmd:
### Steps to reproduce ###
Use `zip2john` on a zip file with a `ZipCrypto Deflate` encrypted file.

Output:
````
(`run/` build directory)
$ ./zip2john problem.zip > problem.zip.hashes
ver 2.0 problem.zip/test.pdf PKZIP Encr: cmplen=0, decmplen=12111, crc=0
````
Also, in the ([pkzip2](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/zip2john.c#L37)) hash in output for this `ZipCrypto Deflate` encrypted file, the [`DA` field](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/zip2john.c#L56) is empty.

`john` is skipping that hash, hence cracking the password of the zip file is not possible:
````
$ ./john problem.zip.hashes
[...]
No password hashes loaded (see FAQ)
````

### System configuration ###
Attach details about your OS and about JtR, including:
- `$ ./john --list=build-info`.
````
Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
GNU libc version: 2.27 (loaded: 2.27)
Crypto library: OpenSSL
OpenSSL library version: 01010100f
OpenSSL 1.1.1  11 Sep 2018
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
````

- `$ ./john --list=opencl-devices` (if applicable).
(No OpenCL (no dGPU) is used.)

**Comment by magnumripper** [comment]
Possibly more or less related to #4054

**Comment by magnumripper** [comment]
Does this apply to just any file compressed with ZipCrypto Deflate?

**Comment by magnumripper** [comment]
If you can supply a (small) test archive that has this problem, it'd help a lot.

**Comment by magnumripper** [comment]
I'm hoping this was fixed with #4207

**Comment by magnumripper** [comment]
Closing bc wo

**Comment by strarsis** [comment]
@magnumripper: Just tried it out and it works great! Thanks for following this up and fixing it.

**Comment by magnumripper** [comment]
@srett is the man
