### ISSUE TITLE
JTR Timers getting excessive values. 

### ISSUE THREAD

**Issue by OverlordQ** [openwall/john#4067]
### Steps to reproduce ###
1) Checkout lastest source
2) Build
3) Run `./john --test=1 --format=SSH`
4) Wait
5) Wait
6) Wait

Commit 91332789f works, Commit ece3bb42 exhibits the behavior. 

### System configuration ###
If you look at `john_broken.txt` it says the timer somehow observed 136 years

[john_working.txt](https://github.com/magnumripper/JohnTheRipper/files/3483507/john_working.txt)
[john_broken.txt](https://github.com/magnumripper/JohnTheRipper/files/3483508/john_broken.txt)

**Comment by OverlordQ** [comment]
See also: #3949

**Comment by magnumripper** [comment]
Thanks for reporting. I see the exact same problem on "super" (Openwall HPC village) but I can't recall anyone reporting it before.

I think I see the problem, I believe it's a Linux bug but I'll commit a workaround soon.

**Comment by magnumripper** [comment]
It sure is a Linux bug but I can't find it mentioned anywhere. The result of `clock_getres(CLOCK_MONOTONIC_RAW, &res)` is a negative(!) -3.870068064 seconds. Always same number and the return code is 0 - no error.
