### ISSUE TITLE
Future CI problems (aka, new compiler warnings)

### ISSUE THREAD

**Issue by ghost** [openwall/john#4080]
I updated the images used for CI. In "fresh" images (`-dev` distros) new compiler versions might be available. In fact, clang 9 and gcc 10 debuted recently. 
* That should result in errors upstream (magnumripper, the repo, itself). That said:

E.g., this is `clang version 9.0.0-+rc2-1~exp1 (tags/RELEASE_900/rc2)`. And it is correct, `t` is uninitialized.

```
DES_bs_b.c:1016:27: error: variable 't' is uninitialized when used here [-Werror,-Wuninitialized]
                DES_bs_finalize_keys_LM(t);
                                        ^
DES_bs_b.c:990:7: note: initialize the variable 't' to silence this warning
        int t, n = (keys_count + (DES_BS_DEPTH - 1)) / DES_BS_DEPTH;
             ^
              = 0
DES_bs_b.c:1179:30: error: variable 't' is uninitialized when used here [-Werror,-Wuninitialized]
                DES_bs_finalize_keys_plain(t);
                                           ^
DES_bs_b.c:1152:7: note: initialize the variable 't' to silence this warning
        int t, n = (keys_count + (DES_BS_DEPTH - 1)) / DES_BS_DEPTH;
             ^
              = 0
```

Or, gcc 10.0.0 20190820. But, in this case, gcc is wrong.

```
compiler.c: In function 'c_expr':
compiler.c:514:31: warning: 'stack[0]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  514 |  if (term == ')') stack[sp++] = -1;
      |                   ~~~~~~~~~~~~^~~~
```

And so on.

**Comment by solardiz** [comment]
> And it is correct, `t` is uninitialized.

No, these are inside `for_each_t` blocks, which initializes `t`.

**Comment by solardiz** [comment]
I think there's nothing for us to do on this issue. Closing.

We already took care of recent stable gcc releases' warnings recently. (The warning for `compiler.c` that Claudio shows here is a gcc bug that they've already fixed before making the first stable release in 10.x series.)
