### ISSUE TITLE
Couldn't open wallet.dat

### ISSUE THREAD

**Issue by MrJur1** [openwall/john#4085]
Hello guys,
i try to get the hash of my 6 year old litecoin wallet. Get the following message. Could you help me please?

C:\Users\...\Desktop\hashcat-5.1.0>python bitcoin2john.py wallet.dat
ERROR:root:22:Invalid argument -- wallet.dat: unexpected file type or format
ERROR:root:Couldn't open wallet.dat/main. Try quitting Bitcoin and running this again.

**Comment by ghost** [comment]
The script supports LiteCoin. But, I'm not sure if it supports a 6 year old litecoin wallet. Dhiru?

```
$ run/bitcoin2john.py 
Usage: run/bitcoin2john.py [Bitcoin/Litecoin/PRiVCY wallet (.dat) files]
```

You might need to ask on john-users. Well, real users may be able to give you an answer.

**Comment by magnumripper** [comment]
> The script supports LiteCoin. But, I'm not sure if it supports a 6 year old litecoin wallet. Dhiru?

I too have no idea - but I do see that @kholia created that script over six years ago, so maybe it should!

**Comment by magnumripper** [comment]
Just a completely random thought: Are you using Python 2 for this? It might work better than Python 3.

**Comment by solardiz** [comment]
@MrJur1 You _definitely_ need Python 2 for this script to work (so please check `python --version` and add that to this issue), however the specific error you're getting indicates that this is probably not the only issue. It might also be that whatever Python version you use loads Berkeley DB of a version that doesn't recognize the wallet's Berkeley DB version. This issue might or might not go away along with you switching to another Python version/build.

It would also help us categorize this issue if you provide the output of `file wallet.dat` (using the `file` utility from a Cygwin package, likely of the same name). Thanks.

> Could you help me please?

Our use of GitHub issues is primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. To receive user support from the community, please use the john-users mailing list instead. Thanks.

**Comment by solardiz** [comment]
No point in keeping this issue open without communication with the OP. Meanwhile, we've revised the script so that it works with Python 3 as well.

**Comment by Ahmadreza1994** [comment]
I have encountered these three problems for work, what should I do for them?ERROR:root:(22, 'Invalid argument -- wallet.dat: unexpected file type or format')
ERROR:root:Couldn't open wallet.dat/main. Try quitting Bitcoin and running this again.
ERROR:root:See our doc/README.bitcoin for how to setup and use this script correctly.

**Comment by solardiz** [comment]
@Ahmadreza1994 First of all, please make sure you're using the latest `bitcoin2john.py` from this repository, _not_ the older 1.9.0-jumbo-1 release. Please let us know whether this has helped. Either way, please also describe your setup - OS, Python version, `bitcoin2john.py` script revision, and what wallet type your `wallet.dat` came from. Since the OP here never said anything besides their first comment, we don't know what their issue was and whether our script update has helped or not.
