### ISSUE TITLE
We're out of options flags

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4087]
*I have actually played with the idea of making Jumbo's options flags 128-bit (and simply losing some checks if that's not supported, like on a 32-bit build) but that's not quite the final solution - and it has some caveats, eg. we can't write that big integers in source simply as `0x00001000000000000000000000000000ULLL` but rather as something like `(0x0000100000000000 << (uint128_t)64)`*

_Originally posted by @magnumripper in https://github.com/magnumripper/JohnTheRipper/issues/4034#issuecomment-504219417_

That crazy idea might not even fly. We do have a few low-half bits still usable but we're getting close to really need a solution.

**Comment by magnumripper** [comment]
We could also want to find some canonical way for `options.c` to add support for boolean options with a (possibly not yet known) default, as in `--keep-guessing` vs. `--no-keep-guessing` which is sort of a three-state: True, False or Not given (meaning we should default to the format's `FMT_NOT_EXACT` flag in that case - but the state of it isn't known yet when we process config and options...)

**Comment by magnumripper** [comment]
Hmm I think I can visualize how to implement it by eg. introducing a new `OPT_THREESTATE` flag.

New style could be defined something like this:
```diff
- 	{"keep-guessing", FLG_KEEP_GUESSING, FLG_KEEP_GUESSING,
- 		0, FLG_NO_KEEP_GUESSING},
- 	{"no-keep-guessing", FLG_NO_KEEP_GUESSING, FLG_NO_KEEP_GUESSING,
- 		0, FLG_KEEP_GUESSING},
+ 	{ "keep-guessing", FLG_ZERO, 0, FLG_CRACKING_CHK, OPT_THREESTATE, &options.keep_guessing },
```
This would mean:
1. The `OPT_THREESTATE` would let `options.c` know that you can either say `--keep-guessing` or `--no-keep-guessing` so no extra definition line for the latter.
2. The variable would be set by `options.c` accordingly, to eg. `1` or `0` or, if not given at all, to `-1` (which in this very case would mean we put `FMT_NOT_EXACT` there, from the format - once known).
3. The existing logic for `FMT_ZERO` could be amended to take care of these without requiring a new options flag (let alone two) for each option. So we'd go from two flags needed, to none - per such option.

This logic could be extended to also support an optional parameter, such as `--rules[=SECTION...]` vs. `--no-rules` (which would automagically refuse an argument).

**Comment by solardiz** [comment]
I like your three-state options idea. It has many advantages at once, including simplifying the options list definition.

Alternatives to that would be going for 2x `uint64_t` flag fields (and then calling the constants `FLG1_...` or `FLG2_...` accordingly and using them in the right places), or ditching the notion of flags (and handling detection of option incompatibility only with explicit `if` statements).

**Comment by magnumripper** [comment]
This issue will history
