### ISSUE TITLE
Build with CommonCrypto fails

### ISSUE THREAD

**Issue by fxcoudert** [openwall/john#4098]
### Steps to reproduce ###

- download JohnTheRipper-1.9.0-Jumbo-1
- `./configure --disable-native-tests --without-openssl --with-commoncrypto`
- `make`

This gives the following build error:

```
In file included from sha2.c:26:
./sha2.h:37:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
```

This is unexpected, given I asked to build without OpenSSL, and `configure` was happy about it. The end of the output of `configure` was:

```
Configured for building John the Ripper jumbo:

Target CPU ................................. x86_64 SSE4.1, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. darwin17.7.0
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h

Optional libraries/features found:
Memory map (share/page large files) ........ yes
Fork support ............................... yes
OpenMP support ............................. no
OpenCL support ............................. yes
Generic crypt(3) format .................... yes
libgmp (PRINCE mode and faster SRP formats)  yes
128-bit integer (faster PRINCE mode) ....... yes
libz (pkzip and some other formats) ........ yes
libbz2 (gpg2john extra decompression logic)  yes
libpcap (vncpcap2john and SIPdump) ......... yes
OpenMPI support (default disabled) ......... no
ZTEX USB-FPGA module 1.15y support ......... no
```

### System configuration ###

macOS 10.13, with system tools (Xcode, clang) and gmp provided by Homebrew.

This happened while I was trying to look into https://github.com/Homebrew/homebrew-core/pull/43531

**Comment by magnumripper** [comment]
Thanks for reporting. That `--with-commoncrypto` option has been unattended for years, I guess we should simply remove it. We have a much better plan: #3998

**Comment by solardiz** [comment]
There are plenty of places (edit, clarification: I mean in our current code) where building with CommonCrypto also requires OpenSSL headers. I just assumed this was the case during my work on #4654. As magnum says, we should probably drop CommonCrypto support - or fix it, if anyone wants to.

Right now, you _might_ be able to build with `--without-openssl --with-commoncrypto` _if_ you also have OpenSSL headers installed. I didn't try, but am unaware of a specific reason why this wouldn't build - probably there are some minor reasons, though, as I doubt something complicated like this would just work without ever having been retested after all the changes.

You can also build with `--without-openssl` and without CommonCrypto too, but with greatly reduced functionality.
