### ISSUE TITLE
SingleWordsPairMax is raised automatically for high KPC, it seems inaccurate

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#4110]
I am not sure that it is a problem.

Behaviour of SingleWordsPairMax:
```
$ printf '.include <john.conf>\n[Local:Options]\nSingleWordsPairMax = 0\n' > t.conf

$ cat t.conf
.include <john.conf>
[Local:Options]
SingleWordsPairMax = 0

$ echo 'a11,b22,c33,d44,e55,f66,g77:$0$H' > plaintext.pw

$ ./JohnTheRipper/run/john plaintext.pw --verbosity=6 --single=None --config=t.conf --log-stderr
[...]
0:00:00:00 - SingleWordsPairMax increased to 3 for high KPC (8)
0:00:00:00 - SingleWordsPairMax used is 3
[...]
set_key(a11,b22,c33,d44,e55,f66,g77, 0)
set_key(a11,b22,c33,d44,e55,f66,g77a11, 1)
set_key(aa11, 2)
set_key(a11,b22,c33,d44,e55,f66,g77b22, 3)
set_key(ab22, 4)
set_key(a11,b22,c33,d44,e55,f66,g77c33, 5)
set_key(ac33, 6)
set_key(a11, 7)
set_key(a11a11,b22,c33,d44,e55,f66,g77, 0)
set_key(aa11,b22,c33,d44,e55,f66,g77, 1)
set_key(a11b22, 2)
set_key(a11c33, 3)
set_key(b22, 4)
set_key(b22a11,b22,c33,d44,e55,f66,g77, 5)
set_key(ba11,b22,c33,d44,e55,f66,g77, 6)
set_key(b22a11, 7)
set_key(ba11, 0)
set_key(b22c33, 1)
set_key(bc33, 2)
set_key(c33, 3)
set_key(d44, 4)
set_key(e55, 5)
set_key(f66, 6)
set_key(g77, 7)
[...]
```

So there are much more candidates than the reported KPC:
- full login,
- every single word alone,
- 3x full + word,
- 2x word + full (1+full, 2+full),
- 2x first letter + full,
- 5x first letter + word (the very first letter with 3 words, first letter of second word with words 1 and 3),
- 4x pairs of words (1+2, 1+3, 2+1, 2+3).

Respective code from `single.c`:
```c
	if (log2(key_count) > words_pair_max) {
		words_pair_max = log2(key_count);
		log_event("- SingleWordsPairMax increased to %d for high KPC (%d)",
		          log2(key_count), key_count);
	}
```

I chose 7 words in login to show that full login and words fill KPC well. Total number of candidates is a multiple of KPC, that's good. But for 8 words in login, it would not be a multiple.

Possible problems:
- 2x word + full (1+full, 2+full) does not seem logical; everything else is generated for the first 3 words (plus the very first letter as special case),
- it seems there is intention to fill the buffer better, the code does not satisfy it in all cases.

john is quite fresh:
```
$ ./JohnTheRipper/run/john --list=build-info
Version: 1.9.0-jumbo-1+bleeding-ea33667eb 2019-09-23 12:43:34 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
```

**Comment by magnumripper** [comment]
You're probably correct. My rationale for that log2 was just to find some KISS code[tm] that bumps the limit for formats with an awful high KPC (in terms of single mode) in the least complicated way I could find that was still kind of appropriate.

Single mode is (or should be) run with lots of rules so the exact figure we'll end up with should be more or less unpredictable. I'm a lot more attentive to actual improvement ideas than to theoretical rants ;-)

**Comment by AlekseyCherepanov** [comment]
Hm, there are rules. So the buffer will be filled by them, no?

It looks so (notice the second argument of `set_key()`):
```
$ printf 'a:$0$H:::b' > plaintext.pw
$ ./JohnTheRipper/run/john plaintext.pw --verbosity=6 --single=':$[12]'
[...]
set_key(a1, 0)
set_key(ab1, 1)
set_key(b1, 2)
set_key(ba1, 3)
set_key(a2, 4)
set_key(ab2, 5)
set_key(b2, 6)
set_key(ba2, 7)
[...]
```

So does SingleWordsPairMax need to be raised for high KPC at all?

**Comment by magnumripper** [comment]
I have to correct myself: I do appreciate your experiments and thoughts. On a side note: For years and years I've been tempted to implement an eastern egg option letting you run single mode with `--stdout` instead of adding debug prints like you did there (and like I've done many many times). Just for understanding/testing single mode and/or rules for it. I've yet to come up with a good syntax.

Now, this it's not *actually* about KPC **at all** other than that a very high KPC is much more likely to become starved of candidates so we really don't want unnecessary limits!

`SingleWordsPairMax` is only a limit when you have many (perhaps MANY) seed words. Try your experiments with `SingleWordsPairMax = 4` (the core default) and a stuffed gecos field, like `root:$0$lima_gold:::alpha bravo charlie delta echo foxtrot golf hotel india joliet kilo lima...`  and then compare it to using exact same words in eg. `-single-wordlist=nato_phonetic.lst` which will automagically bump the limit.

**Comment by magnumripper** [comment]
I see no need to change this right now.

**Comment by solardiz** [comment]
FWIW, from a theoretical perspective, given that this is about how many words to combine in _pairs_, perhaps the corresponding function would be `sqrt` rather than `log2`, if the goal is to likely fill KPC with the pairs.

**Comment by solardiz** [comment]
Maybe something like `sqrt(key_count / rule_count)`, but only for potentially increasing `words_pair_max` (never decrease it).

It's somewhat weird that single mode depends on format implementation detail (which KPC is) for how many and which passwords it'd end up guessing or not - but that's what we have. Edit: maybe we need to document this prominently.

**Comment by magnumripper** [comment]
I can't remember how/why I ended up with log2, just that it was a conscious and somewhat careful choice.

**Comment by magnumripper** [comment]
Oh, it was in https://github.com/openwall/john/issues/3467#issuecomment-445395452. I think I wanted to ensure it never end up being dramatically increased.

**Comment by solardiz** [comment]
Makes sense, but I think a dramatic increase would be OK if we divide by the number of rules first. It certainly would be problematic if we didn't do that, like your code does not. Also, a source code comment would be appropriate either way.

Anyway, I don't insist on you doing anything on this - I just offered my thoughts.

**Comment by magnumripper** [comment]
That #3467 issue is still open, I'll note this discussion there.
