### ISSUE TITLE
rules preprocessor is permissive for ranges syntax: unclosed bracket is allowed, unquoted opening bracket inside range is allowed

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#4112]
Unclosed bracket for preprocessor is not reported as error in rules. Opening bracket inside range does not need quoting. It is not a big problem. But there are cases when it may be a bit confusing and hide mistake/typo.

Both `--rules=':$[0-9\]'` and `--rules=':$[0-9\\]'` work. The first variant appends `]`, the second appends `\`.

Both `--rules=':$[1-9\] $[1-9]'` and `--rules=':$[1-9\\] $[1-9]'` work. The first variant appends one char, the second appends two chars.

It might be good to report error in such cases.

**Comment by AlekseyCherepanov** [comment]
There is one more thing close to these. `[a-c-z]` gives all letters (`--rules=':$[a-c-z]'`). Mask mode works the same way.

For comparison in Perl 5 and Python's regexps, `[a-c-z]` would be treated as `[a-c\-z]` (but there would not be error that `-` is not quoted even with 'strict' and 'warnings').

```
$ perl -le 'for (a .. z, "-") { print }' | perl -ne 'print if /[a-c-z]/'
a
b
c
z
-
```

**Comment by solardiz** [comment]
I've added a bunch of labels to this issue, and am closing it - this describes the current behavior, which isn't necessarily wrong, so we don't intend to spend resources on fixing it any time soon, and no point in having this issue hang around.
