### ISSUE TITLE
office2john seems to get wrong hash for ppt protected by edit-only password

### ISSUE THREAD

**Issue by akorn** [openwall/john#4116]
I have a .pps file that I can open in read-only mode, but editing would require entering a password that I no longer have. (This is inconvenient because LibreOffice can't open such documents at all, not even in read-only mode, and Microsoft Office won't let me save it in a different format without the password.)

`office2john.py` (the latest from github) prints:

`file.pps:$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b`

I used hashcat and not John to do the actual cracking, but that should be irrelevant. (If I find the time I'll try to reproduce this with John as well, but I expect it to arrive at the same passwords.)

Cracking the oldoffice hash with `hashcat -m 9810 -w 3 hash.txt -o hash.rc4 -a 3 '?b?b?b?b?b'` results in:

`$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591`

Cracking *that* using `hashcat -m 9820 -D 1 -w 3 hash.rc4 -a 3 '?a?a?a?a?a?a?a?a?a?a' --increment --keep-guessing` yields passwords like

```
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:'+8p`'2
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:'-32oYq 
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:'<(~!}<#
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:'w0cvG$%
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:nmjvnzfrd
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:qcqkwwjhe
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:dlplyllli
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:ywlawrvvv
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:pllzvnwbw
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:pyupfogmaa
$oldoffice$3*c1696ec41fb3c836f5d287c09c5be40f*86c37170b2dca959425254b6cc47bcbe*572496db30edbc07030e77a3b9b4aa59c645b14b:fdb7d40591:rchwnnreha
```

But none of these are actually accepted by Office.

Since cracking Office document passwords seems to work for others, I assume cracking the actual hash went fine, and the problem must be that the wrong hash was extracted.

I can provide the pps in question privately if necessary, but I think this should be easy to reproduce with any edit-only protected document.

FWIW, `office2hashcat` extracts the same hash; I also reported the same issue against that project.

**Comment by magnumripper** [comment]
x-ref https://github.com/stricture/hashstack-server-plugin-hashcat/issues/4

**Comment by magnumripper** [comment]
I believe the read-only feature may be a whole different functionality (the document isn't encrypted!) so the hash you got could be all bogus. We should find a way to detect this situation and either produce a correct hash (if applicable at all) or just bail with a proper error message.

**Comment by magnumripper** [comment]
Good new information from @philsmd - we just need to figure out how to validate a second block of data. I'd expect a simple entropy check to suffice (eg. "expected different"). I have some unfinished code for #3444 that would come handy.
