### ISSUE TITLE
Cyrillic brute force Telegram Passcode

### ISSUE THREAD

**Issue by ZX-zedex** [openwall/john#4119]
Hi.
Is there any capable settings or components that can afford to bruteforce the Telegram Local Passcode hash with cyrillic symbols (with JTP)?

Thank you

**Comment by magnumripper** [comment]
Not sure what JTP refers to. We do have a format for attacking Telegram Desktop passcodes and I would expect the encoding to be UTF-8 so all needed tools should be in place.

**Comment by ZX-zedex** [comment]
Thank you for reply.
I wanted to know how exactly it can be used.

For example.
When I get the hash of the passcode from map0 file I use the commands like:
john <passcode> --incremental --min-length=2 --max-length=3
john <passcode> --mask=?l?l?l?l

What should I add in these commands so it will try all the possibilities with cyrillic symbols, numbers etc. (without latin characters)

Thank you

**Comment by ZX-zedex** [comment]
And I am wondering if there any chance to find out it without bruteforce method or maybe replace it in the map[0-1] file with the simplest one (ex. 1234), cause I don't have any idea about the length of the password, which characters it contains and the strength of it.

Thank you.

**Comment by magnumripper** [comment]
This is not a support forum, it's a bug tracker.

For questions and support, review recent postings on the john-users mailing list at https://www.openwall.com/lists/john-users/ and then subscribe to the list at https://www.openwall.com/john/#lists and post your message to the list by e-mailing john-users 'at' lists.openwall.com.
