### ISSUE TITLE
bitlocker2john hash not opened by John

### ISSUE THREAD

**Issue by fraveau** [openwall/john#4122]
Hi 
The hash generated by bitlocker2john is not opened by john: 

#bitlocker2john -i disk.img > hash.txt
Signature found at 0x3
Version: 8 
Invalid version, looking for a signature with valid version...

Signature found at 0x65c2a000
Version: 2 (Windows 7 or later)

VMK entry found at 0x65c2a18f

VMK encrypted with Recovery Password found at 0x65c2a1b0
Searching AES-CCM from 0x65c2a1cc
Trying offset 0x65c2a25f....
VMK encrypted with AES-CCM!!

VMK entry found at 0x65c2a2af
VMK encrypted with TPM...not supported! (0x65c2a2d0)

Signature found at 0x65c3a000
Version: 2 (Windows 7 or later)

VMK entry found at 0x65c3a18f

VMK entry found at 0x65c3a2af
VMK encrypted with TPM...not supported! (0x65c3a2d0)

VMK entry found at 0xc3a6bb4a

Signature found at 0xcbb40000
Version: 2 (Windows 7 or later)

VMK entry found at 0xcbb4018f

VMK entry found at 0xcbb402af
VMK encrypted with TPM...not supported! (0xcbb402d0)

VMK entry found at 0xfb2a0117

VMK entry found at 0x2a1f15c80

# cat hash.txt 
Encrypted device disk.img opened, size 16661MB
Salt: 3adb3d7f8dfbe03dc3f4cef931aad1e9
RP Nonce: e04a4339a66cd50162000000
RP MAC: 1e93c2f48241aa8af137dee6e6aa3ad5
RP VMK: 584febef62857e0462a674cbe8b21268b1dc7633b302fcc5a268cdd52d44adb5b55cb3e1c082c79d724bc903

Hash type: Recovery Password fast attack
$bitlocker$2$16$3adb3d7f8dfbe03dc3f4cef931aad1e9$1048576$12$e04a4339a66cd50162000000$60$1e93c2f48241aa8af137dee6e6aa3ad5584febef62857e0462a674cbe8b21268b1dc7633b302fcc5a268cdd52d44adb5b55cb3e1c082c79d724bc903
Hash type: Recovery Password with MAC verification (slower solution, no false positives)
$bitlocker$3$16$3adb3d7f8dfbe03dc3f4cef931aad1e9$1048576$12$e04a4339a66cd50162000000$60$1e93c2f48241aa8af137dee6e6aa3ad5584febef62857e0462a674cbe8b21268b1dc7633b302fcc5a268cdd52d44adb5b55cb3e1c082c79d724bc903

# john --format=bitlocker --wordlist=dictionnary.txt hash.txt
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

This should be functionnal isn't?
Regards

**Comment by ghost** [comment]
These hashes are crackable (only) using the OpenCL format.

```
$ ../run/john ~/hash.txt --format=bitlocker
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

```
$ ../run/john ~/hash.txt --format=bitlocker-opencl
Device 1: Tahiti [AMD Radeon HD 7900 Series]
Using default input encoding: UTF-8
Loaded 2 password hashes with 2 different salts (BitLocker-opencl, BitLocker [SHA256 AES OpenCL])
Cost 1 (iteration count) is 1048576 for all loaded hashes
```

```
$ cat ~/hash.txt 
$bitlocker$2$16$3adb3d7f8dfbe03dc3f4cef931aad1e9$1048576$12$e04a4339a66cd50162000000$60$1e93c2f48241aa8af137dee6e6aa3ad5584febef62857e0462a674cbe8b21268b1dc7633b302fcc5a268cdd52d44adb5b55cb3e1c082c79d724bc903
$bitlocker$3$16$3adb3d7f8dfbe03dc3f4cef931aad1e9$1048576$12$e04a4339a66cd50162000000$60$1e93c2f48241aa8af137dee6e6aa3ad5584febef62857e0462a674cbe8b21268b1dc7633b302fcc5a268cdd52d44adb5b55cb3e1c082c79d724bc903
```
***

Issue: improve docs and warnings messages.

**Comment by solardiz** [comment]
On Wed, Oct 16, 2019 at 05:18:58AM -0700, Claudio Andr?? wrote:
> These hashes are crackable (only) using the OpenCL format.
...
> Issue: improve docs and warnings messages.

Please also open an issue to enhance the CPU format to match OpenCL's capabilities, unless we already have an issue like that open (in which case we might need to prioritize it).

**Comment by fraveau** [comment]
ok I  cleaned hash file and tried that but I get another error:

john --format=bitlocker--opencl ./hash.txt 
Unknown ciphertext format name requested

Something to do with my setup?

 john --list=formats --format=cuda
Unknown ciphertext format name requested

Maybe it's because I've installed Cuda et Nvidia drivers on Kali 2019 which as pre-installed Jumbo 1.9? Do I have to re-install JtR to make it work with Opencl?

**Comment by magnumripper** [comment]
> ok I cleaned hash file and tried that but I get another error:
> 
> john --format=bitlocker--opencl ./hash.txt
> Unknown ciphertext format name requested

It should be `--format=bitlocker-opencl`, not `--format=bitlocker--opencl`

**Comment by fraveau** [comment]
```
john --list=formats --format=cuda
Unknown ciphertext format name requested
john --format=bitlocker-opencl ./hash.txt 
Unknown ciphertext format name requested
```

Sorry for typo but same results

**Comment by magnumripper** [comment]
OK so you need to build for OpenCL. That's a support issue and not to be discussed here. See john-users mailing list at https://www.openwall.com/lists/john-users/ - subscribe to the list at https://www.openwall.com/john/#lists and post your message to the list by e-mailing john-users 'at' lists.openwall.com.

**Comment by magnumripper** [comment]
#3310

**Comment by ghost** [comment]
Again, the same issue (and it works on well using OpenCL):
* https://www.openwall.com/lists/john-users/2019/11/04/1

**Comment by joao-vaz-martins** [comment]
My bitlocker disk is proteced with a TPM and a Bitlocker recovery Key
I used "FTK_Imager_4.7.1" to create the RAW dis image and after i used "bitlocker2john -i disk.img > hash.txt" and got two hashes $bitlocker$2$ and $bitlocker$3$.

In order to get recover the Bitlocker recovery key i used "John --format=bitlocker-opencl -mask=?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d target_$3$_hash > Bitlocker_Recovery_Key"

It will take a long time!!!
I'm using a computer with dual GPU in Crossfire. Is it possible to use both GPU's to speed up the process?????

**Comment by solardiz** [comment]
@joao-vaz-martins's question above is repeated and answered in #5355.
