### ISSUE TITLE
Define nt-long as alias for dynamic=md4(utf16($p))

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4132]
@AlekseyCherepanov wrote on john-users:

> John's default length limit is 27 for NT format. Ad-hoc dynamic format
> --format='dynamic=md4(utf16($p))' may be used to extend it.

I think this is useful to a lot of people, but it's obscure. Should we perhaps define e.g. `nt-long` as an alias for this format, so it'd come up in the formats list, in default "--test" benchmarks, etc. And have it listed right after the main `nt` format, similarly to how we have it for `md5crypt` vs. `md5crypt-long`.

FWIW, testing on one core in i7-4770K:

```
[solar@well run]$ ./john -test -form=nt
Benchmarking: NT [MD4 256/256 AVX2 8x3]... DONE
Raw:	90110K c/s real, 90110K c/s virtual

[solar@well run]$ ./john -test -form='dynamic=md4(utf16($p))'
Benchmarking: dynamic=md4(utf16($p)) [256/256 AVX2 8x3]... DONE
Raw:	23056K c/s real, 23056K c/s virtual
```

So there's a performance impact, and we shouldn't redefine `nt` as the dynamic format.

Edit: this is related to issue #4032.

**Comment by solardiz** [comment]
We must also actually test that this dynamic format works right for lengths beyond 27, and include test vectors covering the range of lengths the format is meant to support.

**Comment by magnumripper** [comment]
There are some caveats. One is tagging in the .pot file - they'll get different tags.

Several years ago Jim was working with some kind of generic alias feature but it never aired. Ideally, dynamic formats would be able to register as an arbitrary name (eg. NT-long) and use an arbitrary tag (eg. `$NT$`).

**Comment by magnumripper** [comment]
@jfoug perhaps you could whip up "NT-long" as a thin dynamic?

**Comment by solardiz** [comment]
Some observations from experimenting with this:

I thought `--format=dynamic_33` would behave the same as `--format='dynamic=md4(utf16($p))'` (except for the different format tag), but it actually behaves subtly differently.

I am testing with HIBP v8 hashes with count 100+ (there are 3612950 such hashes), cracking them with RockYou as wordlist. Here are the numbers of cracks in different tests:

1. `--format=nt` (no encoding specified): 1798346
2. `--format=nt --encoding=cp1252`: 1798368
3. `--format=dynamic_33` (no encoding specified): 1798364
4. `--format=dynamic_33 --encoding=cp1252`: 1798368
5. `--format='dynamic=md4(utf16($p))'` (no encoding specified): 1798361
6. `--format='dynamic=md4(utf16($p))' --encoding=cp1252`: 1798369

```
$ ./pwqfilter -o rockyou-ntlm.pwq --create=14637132 --hash-ntlm-cp1252 --optimize-fp-rate-at-high-load < rockyou.txt
Lines 14344391, inserts 14344391, excessive effective duplicates 0, errors 0
$ ./pwqfilter -f rockyou-ntlm.pwq --pre-hashed < pp8-100p | wc -l
1798369
```

So it looks like 1798369 is the correct count. I didn't yet test the actual cracks.

**Comment by solardiz** [comment]
> So it looks like 1798369 is the correct count. I didn't yet test the actual cracks.

I did now. Ran `--format='dynamic=md4(utf16($p))' --encoding=cp1252` on only the 1798369 hashes output by `pwqfilter -f rockyou-ntlm.pwq --pre-hashed < pp8-100p`. All of them got cracked.

Curiously, without `--encoding=cp1252` the number drops to 1798343, which is lower than 1798361 that was seen when running on the full list of 3612950 hashes. This implies that without an encoding specified we end up cracking with the RockYou wordlist (and no rules, etc.) some hashes that did not literally appear in RockYou. Misinterpreting the lines in a different encoding is then kind of a mangling rule.

**Comment by solardiz** [comment]
@magnumripper For my testing here, is there a way to get the original wordlist entries written to pot file (without encoding conversion) even when using `--encoding=cp1252` for conversion during the cracking (edit: or to have the reverse conversion done on `--show`)? Otherwise I am getting pot entries that I cannot then easily match to original RockYou lines.

**Comment by magnumripper** [comment]
For NT it should be `UnicodeStoreUTF8 = N` but I haven't tested that code path for years and years.

**Comment by magnumripper** [comment]
It just hit me we could write a "thin dynamic" format which internally is dynamic=md4(utf16($p)) but will use normal `$NT$` tags for pot entries. It could be named nt-long and we'd be set!

**Comment by solardiz** [comment]
> For NT it should be `UnicodeStoreUTF8 = N` but I haven't tested that code path for years and years.

This worked (edit: I only tested it along with `--format='dynamic=md4(utf16($p))' --encoding=cp1252`). Thank you!

> It just hit me we could write a "thin dynamic" format which internally is dynamic=md4(utf16($p)) but will use normal `$NT$` tags for pot entries. It could be named nt-long and we'd be set!

Exactly.
