### ISSUE TITLE
Enpass support don't work in current implementation

### ISSUE THREAD

**Issue by damien122** [openwall/john#4139]
As described in [old bug](https://github.com/magnumripper/JohnTheRipper/issues/2336), the current Implementation of enpass decryption don't works.
With John the Ripper 1.9.0-jumbo-1 OMP [cygwin 64-bit x86_64 AVX2 AC]
is is not possible to unlock an enpass tresor created with Enpass 6.2.0.

### Steps to reproduce ###
Tested on Environment: Windows 10, Windows 8, Ubuntu and Kali Linux

Steps:

1. Install new Enpass version (not windows store) [Windows bin](https://dl.enpass.io/stable/windows/setup/6.2.0.539/Enpass-setup.exe)  [Linux](https://www.enpass.io/support/kb/general/how-to-install-enpass-on-linux/)
2. Create new tresor with well known password (e.g. "testtest")
3. Find tresor location and copy the walletx.db file to temp directory
4. run `python .\enpass2john.py "C:\Path\to\Tresor\vault.enpassdb" > "C:\Path\to\Tresor\vault_hash_full.txt"`
5. create wordlist.txt with the password from step 2 inside, with some additional random words
6. run `.\john.exe --session=allrulesTest --wordlist="C:\Path\to\Tresor\wordlist.txt" --format=enpass "C:\Path\to\Tresor\vault_hash_full.txt"`

### System configuration ###
`
Version: 1.9.0-jumbo-1
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is /run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
`

**Comment by magnumripper** [comment]
In case this is a new format or PBK, an urgent bug-fix is to detect this instead of creating an uncrackable hash. And obviously, an enhancement would be to support it!

@damien122 could you please create a small test vault (with no real data in it) with a known password (eg. "openwall") and upload here?

**Comment by damien122** [comment]
I have created a tresor with the password "openwall" and with example data from enpass.
![tresor](https://user-images.githubusercontent.com/7516098/68301095-80449600-009f-11ea-946c-41b2fdd98ec3.JPG)


[enpass_tresor.zip](https://github.com/magnumripper/JohnTheRipper/files/3814540/enpass_tresor.zip)

In the ZIp is the tresor (vault.enpassdb) the Json with infos (vault.json) and a backup from the tresor created from enpass (2019-11-06-1573045762-1_vault-4_items.enpassbackup)

**Comment by magnumripper** [comment]
https://www.enpass.io/security/
https://www.zetetic.net/sqlcipher/design/
* It's now 100,000 iterations (in case of Enpass v6 - SQLCipher defaults to 256,000) of PBKDF2-HMAC-SHA512 (current enpass2john hard-codes it to 24,000 iterations and PBKDF2-HMAC-SHA1). Encryption is still aes-256-cbc. The IV is now near the end of each 4K(?) page while salt is the first 16 bytes of the *file*. 
* There's a HMAC-SHA512 we can use for validation at the end of every page (after the IV, which is included).

**Comment by damien122** [comment]
@magnumripper can I maybe help? Because I can't see some changes here and I need this fix.
Of cource I am not good in encription but I can try :)
Or is this just a task for @kholia

**Comment by magnumripper** [comment]
I might be able to do it. What would really help is if you could create a test vector for us, that is, a wallet with [obviously] no value and a known password. Publish it here (the full wallet, not the output of enpass2john) or send it directly to me, and with some luck I can fix it.

**Comment by magnumripper** [comment]
Oh and BTW please use a test vector password including eg. a '€' euro sign or something else above Unicode U+00FF, so we're sure we got such characters cracked correctly. Shouldn't be an issue nowadays but you never know. For example, use a password of "Op€nwall".

**Comment by magnumripper** [comment]
Come to think about it, that's actually a "l33t sp3ak" thing I never tried - replacing 'e' with '€'. Worth trying!

Or maybe I did that lots of times already, I'm not famous for remembering details 🙄.

**Comment by damien122** [comment]
@magnumripper I am not sure what do you mean by "test vector". Do you need additional enpass tresors with example data, or comply empty enpass tresors? Can not already uploaded by me test Tresor be used for that?

**Comment by magnumripper** [comment]
Oh right, I forgot that 🤣 Then we're fine, I'll see if I can figure it out.

**Comment by damien122** [comment]
[test_vectors.zip](https://github.com/magnumripper/JohnTheRipper/files/3854097/test_vectors.zip)

I created additional test tresors on different Operating systems (Mac, Windows 10 and Fedora) with the password "Op€nwall". Hope this helps 😄 
The tresors from Mac and Fedora are filed with the enpass example data which you can see on the screenshot from first test tresor. The tresor from Windows is with just one entry "test".

**Comment by damien122** [comment]
@magnumripper Hi, is there maybe some progress? Or is Enpass now uncrackable? I don't want to be a pain in the ass, but I really need this fix 😃

**Comment by magnumripper** [comment]
This is second on my to-do list, I'll get to it sooner or later :)

**Comment by damien122** [comment]
@magnumripper hi, is there something new about this bug?

**Comment by magnumripper** [comment]
Not yet, sorry. Perhaps within a few weeks

**Comment by damien122** [comment]
Hi @magnumripper ,

![](https://media.giphy.com/media/3ornjSZp9jUtEFlsL6/giphy.gif)

I have tried something arround and try to fix the bug. The build works but a test run show an error at enpass:

`Testing: enpass, Enpass Password Manager [PBKDF2-SHA512 256/256 AVX2 4x]... (2xOMP) FAILED (valid (before init))`

Do you know what this means? You can find my changes in the attached zip file.

[john_code_changes.zip](https://github.com/magnumripper/JohnTheRipper/files/4102997/john_code_changes.zip)

**Comment by damien122** [comment]
also I have a question about your prev. post. You wrote:

`The IV is now near the end of each 4K(?) page while salt is the first 16 bytes of the file.`

What do you mean by "4K page"? In `enpass_common.h` line 32 is also page size, should this be encreased?

And also I am not sure in `enpass2john.py` is 1024 byte still ok?

**Comment by damien122** [comment]
[john_code_changes.zip](https://github.com/magnumripper/JohnTheRipper/files/4117078/john_code_changes.zip)

after try again I could fix the testing problem. But unfortunately every time I run now my own compiled version of john with an enpass hash (created with new version of enpass2john.py) from the test vectory I got the following error:
`Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
`
After changing manually the hash file from 100k iterations to 24k iterations, my john version detect the hash again as SHA1 :disappointed: 
Is there some hidden version detection?

**Comment by magnumripper** [comment]
Looks like your changes make the Enpass format *only* understand the newer SHA-512 hashes. A real fix has to cope with old AND new versions. For example, you could/should bump the first `*0*` to `*1*` indicating that it's not the old 2017 version.

As for your "No password hashes loaded" problem, I'm not sure what's wrong. Did you re-build? Perhaps try `make -s clean && make -sj4` to be sure.

**Comment by damien122** [comment]
Ok I will change the version, but it change nothing in the cracking. I already tried it and change it back.

Yes I do  
```
make -s clean & make -sj4
```
Like it is written in the tutorial. But I don't understand why John then ignored the hash file. 
Is there some tutorial how to debug John?

**Comment by damien122** [comment]
@magnumripper After your hint I did a clean checkout and past my changed files, compile and it works! With this version it is possible to crack the test vectors.
Is the zip file enough for you or do you need a pull request?

**Comment by magnumripper** [comment]
Best would be a PR that supports the old format as well as the new one. Thanks for your efforts so far!
