### ISSUE TITLE
bitcoin2john.py Python 3 compatibility

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4143]
A revision of `bitcoin2john.py` (per #4142) when run on an altcoin wallet with Python 2 produces a "hash", whereas when run with Python 3 says "this wallet is not encrypted!" (missing a linefeed after that message - something we should fix as well).

This could indicate a Python 3 compatibility issue in the script itself, or it might be a side-effect of differences in Berkeley DB versions in use by these two Python builds on this system (although I'd have expected the `db.open` call to fail, like it sometimes does, if the DB type is unsupported). To get the script to work with Python 3 on this throw-away Fedora VM, I had to explicitly install Berkeley DB support for it:

```
dnf install libdb-devel python3-devel
pip3 install bsddb3
```

I hope this is right. For Python 2, the system had working Berkeley DB support out of the box.

Also, the uses of `print` in `if __name__ == '__main__':` are Python 2 specific.

Related: #3591, #4085.

**Comment by solardiz** [comment]
I'm also seeing the same issue with our sample wallets from the wiki, so I hope anyone can reproduce this.

@exploide I'd appreciate your help on this issue after we merge #4145. Thanks!

**Comment by solardiz** [comment]
I started looking into this issue, but with my current non-knowledge of Python I don't intend to complete fixing it - I'd rather leave that to someone familiar with Python, who would manage to have this work with both Python versions cleanly.

The main issue appears to be Python 3's explicit byte strings, so e.g. what used to be `ckey` in Python 2 becomes `b'ckey'` in Python 3, and the if's fail to match it. When I update the if's to match, a further hurdle is that there's no `encode('hex_codec')` in Python 3's byte strings.

If we somehow don't fix this script soon, then we should have it fail on Python 3 with a more reasonable message - saying the script needs Python 2 rather than wrongly claiming the wallet is not encrypted.

**Comment by exploide** [comment]
@solardiz I can give it a try once I find a bit time, though I have zero knowledge of wallets.

I will base my work on your current `bitcoin2john-cleanup2` branch. Are these the relevant test files? https://openwall.info/wiki/john/sample-non-hashes#Bitcoin-Core-wallet-files

Concerning the bsddb import: `bsddb` was once part of Python 2's standard library but it got deprecated in 2.6 and removed in 3. Now, there is the third party module `bsddb3` for Python 3 that needs to be installed manually. That's the reason you see the respective behaviour when running the script with python2 or python3. And as long as this functionality is needed, there is nothing we can do against it. So this script will always have an external dependency for python3.

**Comment by solardiz** [comment]
Thank you, @exploide! Yes, you found the right branch and the right test files.
