### ISSUE TITLE
JTR Win10 btc OpenCL support

### ISSUE THREAD

**Issue by ghost** [openwall/john#4148]
is JTR support OpenCL for bitcoin hash on win10 ?
## System configuration ### 
https://i.imgur.com/RDkMH7h.jpg
in HC: https://i.imgur.com/S1kOdXX.jpg

**Comment by solardiz** [comment]
Assuming you mean a Bitcoin Core / Bitcoin Qt wallet, then the answer is no - these are only supported on CPU. hashcat supports them in OpenCL, using output from our `bitcoin2john.py` script.

Besides, our GitHub is not a user support forum. We use GitHub issues to track JtR development tasks.

**Comment by ghost** [comment]
> Assuming you mean a Bitcoin Core / Bitcoin Qt wallet, then the answer is no - these are only supported on CPU. hashcat supports them in OpenCL, using output from our `bitcoin2john.py` script.
> 
> Besides, our GitHub is not a user support forum. We use GitHub issues to track JtR development tasks.

Thanks for answer. Is 13000 pw/sec is good for my CPU ?

**Comment by solardiz** [comment]
Your speed is fine for that "hash" on your CPU, but this question is again not GitHub material.
