### ISSUE TITLE
PRINCE misreports use of rules when restoring

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4157]
I think the below code is buggy in that it forgets to check the `rules` variable, and thus claims rules are in use when they are not:

```c
  if (rec_restored && john_main_process) {
    fprintf(stderr, "Proceeding with prince%c%s",
            loopback ? '-' : ':',
            loopback ? "loopback" : path_expand(wordlist));
    if (options.activewordlistrules) {
      if (options.rule_stack)
        fprintf(stderr, ", rules:(%s x %s)",
                options.activewordlistrules, options.rule_stack);
      else
        fprintf(stderr, ", rules:%s", options.activewordlistrules);
    }
    if (options.flags & FLG_MASK_CHK)
      fprintf(stderr, ", hybrid mask:%s", options.eff_mask);
    if (!options.activewordlistrules && options.rule_stack)
      fprintf(stderr, ", rules-stack:%s", options.rule_stack);
    if (options.req_minlength >= 0 || options.req_maxlength)
      fprintf(stderr, ", lengths: %d-%d",
              options.eff_minlength + mask_add_len,
              pw_max + mask_add_len);
    fprintf(stderr, "\n");
  }
```

**Comment by magnumripper** [comment]
Oh, you are right. How come I never noticed? On a related note I've been thinking we should have some shared code for this (it's a similar code block in all cracking modes, albeit not identical).

**Comment by magnumripper** [comment]
> I've been thinking we should have some shared code for this

BTW an appealing alternative is to simply print the original (abbreviation-expanded and obviously wildcard-expanded) command line. But there's a catch: If you ran `./john -form:nt *` and the wildcard expanded to tens or hundreds of files not including NT hashes, only the ones that actually did should be kept. That has also been in one of my vaguest to-do lists forever. Probably not that hard to accomplish but there's so much to do and so little time.
