### ISSUE TITLE
rar2john No password hashes loaded

### ISSUE THREAD

**Issue by DemonRem** [openwall/john#4161]
hey guys I have a small Issue with the rar2john

I always get that error after generate the hash.txt

Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

I using the windows version

the txt of the hash is attach I be glad if someone can help me
[hash.txt](https://github.com/magnumripper/JohnTheRipper/files/3882173/hash.txt)

**Comment by magnumripper** [comment]
There's nothing wrong with that hash. My guess is you are running eg. `john` instead of `./john` and end up running an older version of John somewhere in your path.

**Comment by DemonRem** [comment]
read what I say , I using the windows version, the command not work 
see the picture

![1](https://user-images.githubusercontent.com/29927382/69483142-6f7c7a00-0e2c-11ea-985a-6e79edb32e7c.png)

**Comment by magnumripper** [comment]
So what is the output of `john --list=build-info`?

**Comment by magnumripper** [comment]
Ah, I see you opened a new issue and problem was solved.
