### ISSUE TITLE
JTR the issue was closed but I'm having the same problem.

### ISSUE THREAD

**Issue by MikeH0** [openwall/john#4166]
I'm new to Github so I'm not sure if I should have commented on the closed issue or start a new one, sorry if I did this wrong.
The closed issue I was refering to is this one.
https://github.com/magnumripper/JohnTheRipper/issues/4163#event-2826104858
The only real differences are I'm using a Dell and I have 32GB Ram and only one 500GB SSD. I'm using Windows 10 Pro and Kali Linux 2019.4. The GPU is the same a AMD RX 560 4GB. 
I also have some additional information, on Windows if I just download John and run it without Cygwin it says there are no opencl devices. If I run it with Cygwin it only finds my CPU not the GPU stsrts to run then exits out. The CPU is listed as device 0 I don't know if that matters or not. I have tried Bleeding Edge and the Openwall download.
I decided to try Kali I got the AMD drivers installed the Pro drives and opencl, and the opencl from intel. It doesn't matter if I use Openwall the one that's included in Kali or Bleeding Edge the result is the same. When I try to find an opencl device it has no idea what I'm asking for. It doesn't appear in any list or as an option. I don't know if Kali doesn't have opencl and GPU support or not but from what I'm getting I am guessing not, but when I research it I find that it does.
The other odd thing is in Windows I get all the same values basically 0g/s 6763p/s 6521c/s 6767C/s on Kali I get 0g/s 1692p/s 6790c/s 11843C/s. Again I'm not sure if this is correct between the systems or if it's some relevant information. Both runs all eight threads of the CPU but again no opencl. I have double and triple checked opencl is installed. I went as far as to download and try a crypto miner, Phoenix it found and used the GPU and CPU. I can send you screen shots of everything if you want. I didn't include anything because I'm not sure what you need or don't and like I said the issue is from what I'm reading the same as the other guys.
This part I doubt will help but as I keep saying I don't know. When I try to use Hashcat it's just a mess on Windows it doesn't want to use anything it see's everything. The CPU it will use, it skips the GPU inside the CPU. The AMD it see's as Baffin and says the driver is broken or not correct. On the Hashcat WIKI it says to install the Scarlett driver, but that just wrecks everything and doesn't work. On Kali it is good to go with everything then it tells me I'm missing fglrx. The reason I mention this is it sees the CPU and GPU and would run if it where not for the fglrx. So I'm guessing if I could get John to look for and run the GPU it would work everything is there except for in John. 
I hope I posted this in the  correct place, again if I didn't I'm sorry. If I should have posted the logs I'm sorry but i figured the other guy did so there was no reason to make this post 12 screens long.
The steps to recreate are simple use the hardware I have with any of the versions of John The Ripper I listed in either OS I mentioned and then just use it. 
In Kali use the terminal as normal. In Windows install Cygwin64 and run from the command line as normal, or download John move to C:/ go into the run dir. hold shift then right click then run as normal, or put a shortcut to the command prompt into  the run dir. click it then run as normal.
All versions run right out of the box just not with opencl and GPU.
Where I'm really confused is, Why it accepts the -opencl in Windows on Cygwin then just wont run it ?
Again sorry if I did this wrong.

**Comment by ghost** [comment]
There are several reasons why you can't find OpenCL formats (on Linux and, especially, on Windows:
- missing (or wrong) GPU drivers;
- missing (or incompatible) OpenCL SDK;
- ICD problems;

JtR itself loads all needed libraries if it can find them. We can improve how it works, but it works (TM). Unfortunately, what you need is some help configuring you computer and we can't do that inside GitHub.
****
The GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. To receive user support from the community, please use the john-users mailing list instead.

**Comment by Rdgeno** [comment]
I wasn't asking for anything I was stating I had an issue I didnt mean to come off that way. 
The only question I had which your statements didnt make any clearer is basically I dont understand if it's not an issue with John why wont it give the opencl option in Kali Linux? When I input it it just  doesnt exist. I dont know how well Pentesters Framework installs things but I came across it today and tried using it as a way to remove me from the equation I got the same result, being as far as I can see there is no option what so ever for opencl in Kali. 
I'm not arguing or trying to make you mad when I start John in Windows it says the hash is also wpapsk-pmk-opencl or something to that effect with Cygwin I'm not home right now to look. In Kali it doesnt say anything about opencl while as I stated Windows lists it as an option. 
If I do --list=opencl-devices in Windows it finds the opencl in the CPU more importantly it understands the command and gives a response. In kali it doesn't recognize it as a command.
As for the opencl and SDK its installed unless there are special ones for John I'm not being a jerk when I say that I actually searched to see if there where.
Please don't misunderstand I would have asked on the openwall site I have spent a lot of time there trying to get this to work, but I cant find the slightest mention of this anywhere except for the issue I referenced from github so I reported it. 
Hey you guys would know better than me I just dont understand what the issue could be other than John. 
I'll concede it's me I dont see how I didnt think drivers would remove menu options but ok.
Sorry I bothered you.

**Comment by MikeH0** [comment]
I'm sorry but I think there was a misunderstanding I was trying to report what I genuinely felt and to one extent or another still do feel that there is a bug or something.
As far as fixing my computer I know you can't do that I wasn't asking you to or for any help the only question I had was at the end and that was me just trying to understand why the script would have opencl as an option in one place in Windows but not the other and why it's not recognized in Kali at all.
My reasoning for it being an issue is I'm guessing Bleeding edge is built off of your code so if i'm having all the same issues with two separate OS since your code is what their's is built off of that there might be a problem.  
Another reason I decided to report is if I input --list=opencl-devices in Cygwin John sees it in the CPU starts then shuts off no reason no error.
If I run John from cmd and  --list=opencl-devices it doesn't see it, in both John states the hash is wpapsk and also wpapsk-pmk and wpapsk-pmk-opencl, or close to that I'm out right now and am on my phone if you wish i can get you exact wording. Those things where the first thing that made me think there might be a problem, so I switched to Kali.
When Kali wouldn't recognize the command -opencl at the end of the hash type and wouldn't list or recognize it as an option, I checked to make sure I was correct and that John worked with opencl and a GPU. Everything says it does.
I still made sure all the drivers opencl you name it was installed and installed correctly, then I surmised that drivers and what not wouldn't remove an option or the command all together.
I have more than a few copies of Kali on USB clean ones so I can trouble shoot, every time the same thing. No option wont recognize the command.
Back to openwall the kali forums everywhere nothing except the aforementioned post. I actually decided perhaps there are special drivers for John I checked there aren't. I went back through the openwall installation for the drivers again same deal.
I then figured I did something wrong in Windows so I switched back removed all the drivers completely reinstalled as well as John, Cygwin too and that's a time consuming task. Same thing nothing changes.
I know you don't really want to read this or care about this part my brothers wife does some kind of programing or science something I don't get involved. We don't speak not my choice I broke down and called explained the issue what the tools where and the processes and results.
She said this stuff isn't her forte but as far as she can tell I have everything and it is installed correctly. Take that for what it's worth I wouldn't bet money on her opinion but coupled with everything else I felt assured it was a programming error, right up until I read your reply.
If it's not John and it's the drivers as you have said then consistent results as to behavior as per platform and drivers wouldn't change John so that a device isn't just not seen but the option is gone.
I don't know if this will get you to change your mind and check from the tone of your reply I don't think it will not that you where mean or belligerent, rather you seem very sure in your response ,and I respect that and have no hard feelings. I just really believe there has to be a bug the same results lets say human error is a variable out of ten or twelve installs on three platforms given all the right tools surely once out of one of those platforms would have to work. Lets say I installed it wrong every time people just aren't that consistent they deviate they make mistakes if my base line is to install it wrong then a mistake on my part would be something successful. I tried a lot for days. Even a broken clock is right twice a day, is what I'm saying. Out of sheer retarded luck I would have had to get it at least once. Unless the drivers and opencl are broken. I ruled that out due to AMD made 2.5 or 3.5 billion last year that's a lot of bad GPU's and opencl and opengl to be putting out there we would have seen it reported somewhere. It's just not happening, plus everything works except for the tools I mentioned, Oh I asked one other question was it normal for the numbers to be so different between OS's sorry about that one. 
I checked openwall I would have asked there but I couldn't find anything related to my issue there or anywhere else except the post I referenced  here.
Today I found a tool Pentesters Framework I don't know how well it does or doesn't work, what it does do is removes me from the equation as far as installing John on Kali. I got the same result.  
Look you have probably forgotten more about this than Ill ever know, so here's my last ditch plea to get you to at least to glaze over it. The other guy is having pretty much the same problem, and by trade I'm a Industrial Designer I fix things I figure out how to make things work, I'm the guy that figures out how to put the square peg into the round hole elegantly any one can just smash it in I make it pretty. Repetition with slight deviance you test vary and analyze that's what I've done here. my mind is analytical that's the way it works I find the small things. 
You know what that's enough I said my piece I hope you will reconsider, but at the end of the day your not going to tell me how to design a roller coaster  or  with your computer skills maybe you will who knows. I do know this I wont be telling you how to program anytime soon. You say it's the drivers, it's the drivers end of the discussion. I thank you for your time and I just want you to know I had the best intentions ,but so did Hitler and look how that turned out. Have a good night and if you could just gloss over it as I've asked I would be very grateful.
