### ISSUE TITLE
Nokia SL3 - Bad code

### ISSUE THREAD

**Issue by MESWEB** [openwall/john#4169]
### IMPORTANT ###
https://github.com/magnumripper/JohnTheRipper/issues/731#issuecomment-307810114

### Steps to reproduce ###
hashcat64

### System configuration ###
Widnows 10

This solution is not working. After 15 days of calculating password received hash is bad. Nokia don't accept code:
Bad code.

Hash and IMEI:
4F468159AFE884C6A4F9E0155F86FE6174F6AB39:003524170521859200

$ echo 4F468159AFE884C6A4F9E0155F86FE6174F6AB39:003524170521859200 > sl3.hash
Then run it with hex options:

$ hashcat64.exe -w3 -m110 --hex-salt --hex-charset sl3.hash -a3 -1 00010203040506070809 ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1

> Session..........: hashcat
Status...........: Running
Hash.Type........: sha1($pass.$salt)
Hash.Target......: 4f468159afe884c6a4f9e0155f86fe6174f6ab39:003524170521859200
Time.Started.....: Sat Dec 07 03:36:34 2019 (3 days, 7 hours)
Time.Estimated...: Thu Dec 19 10:55:42 2019 (8 days, 23 hours)
Guess.Mask.......: ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1 [15]
Guess.Charset....: -1 00010203040506070809, -2 Undefined, -3 Undefined, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   513.3 MH/s (92.14ms) @ Accel:256 Loops:250 Thr:256 Vec:1
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 601612124160000/1000000000000000 (60.16%)
Rejected.........: 0/601612124160000 (0.00%)
Restore.Point....: 601612025856/1000000000000 (60.16%)
Restore.Sub.#1...: Salt:0 Amplifier:500-750 Iteration:0-250
Candidates.#1....: $HEX[080205030508050200020106010006] -> $HEX[010407060604020202020106010006]
Hardware.Mon.#1..: Core:1227MHz Mem:3003MHz Bus:4

>4f468159afe884c6a4f9e0155f86fe6174f6ab39:003524170521859200:$HEX[090201070604050204060508000106]

>Session..........: hashcat
Status...........: Cracked
Hash.Type........: sha1($pass.$salt)
Hash.Target......: 4f468159afe884c6a4f9e0155f86fe6174f6ab39:003524170521859200
Time.Started.....: Sat Dec 07 03:36:34 2019 (3 days, 12 hours)
Time.Estimated...: Tue Dec 10 16:26:00 2019 (0 secs)
Guess.Mask.......: ?1?1?1?1?1?1?1?1?1?1?1?1?1?1?1 [15]
Guess.Charset....: -1 00010203040506070809, -2 Undefined, -3 Undefined, -4 Undefined
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   502.7 MH/s (94.31ms) @ Accel:256 Loops:250 Thr:256 Vec:1
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 610856386560000/1000000000000000 (61.09%)
Rejected.........: 0/610856386560000 (0.00%)
Restore.Point....: 610856337408/1000000000000 (61.09%)
Restore.Sub.#1...: Salt:0 Amplifier:0-250 Iteration:0-250
Candidates.#1....: $HEX[080200010004070303060508000106] -> $HEX[010402040100040305060508000106]
Hardware.Mon.#1..: Core:1392MHz Mem:3003MHz Bus:4

**Comment by magnumripper** [comment]
So you tried 921764524658016 and it didn't work?

**Comment by magnumripper** [comment]
JtR also cracks it as 921764524658016. If this doesn't work, you probably mistyped a figure somewhere or the phone has some other protection than this.

**Comment by MESWEB** [comment]
Nokia 500
Yes I was try type 921764524658016 in phone soft and Nokia BEST v1.51
I was use hash read from soft BEST v1.51 and IMEI as well.
Where I can confirm correct hash from phone?

**Comment by MESWEB** [comment]
I think every

**Comment by MESWEB** [comment]
@magnumripper 
OK I found solution and first code has been successfully accepted by phone.
![Opera Snapshot_2019-12-12_151009_www francesco-pompili it](https://user-images.githubusercontent.com/2931024/70724320-4e53ce80-1cf2-11ea-8730-c46952cf9c69.png)
Can you explain this how it's work? On this site you need enter your Hash 40 digit + received code in Hash format
Here's a sample script: https://www.autoitscript.com/forum/topic/167722-sl3nck-calculate-ncks-from-target_hash-and-master_sp_code/

**Comment by magnumripper** [comment]
Thanks, I'll look into it at some point. But I don't have any such phone so I can only work in the blind

**Comment by magnumripper** [comment]
While we could document that last step, this is more or less out of our scope. Thanks for mentioning it here though!

**Comment by GabubuAvailable** [comment]
Maybe it's too late or not but hashcat removed SL3 support since lite version 0.10 due to the people "abusing" the free software by reuploading it on their forum as a paid software. _lot of drama but that's the story_

I think that's the reason why hashcat doesn't give you the correct hash code when using it. If someone could confirm this, thanks. If not, that's alright.

**Comment by kkjangra** [comment]
Hi khushwant kumar this side,
I have nokia E7 (RM-626).
IMEI and Hash are
354864040624588:3E4B60A13609477E0996958955497928372F2217

I am cracking it using hashcat brute force but failed once and trying 2nd time with 
\hashcat.exe -a 4500 -a 3 -D 2  .\hash.txt ?dPd?d?d?d?d?d?d?d?d?d?d?d?d?d
Hash.txt contains only hash code.

It will be appreciable if anybody could help to crack it.

Or please give me the cracked code if any of you can.

**Comment by magnumripper** [comment]
FWIW that NCK conversion is described at https://www.autoitscript.com/forum/topic/167722-sl3nck-calculate-ncks-from-target_hash-and-master_sp_code/

Web calculators are at http://www.francesco-pompili.it/Hash2Nck.aspx and https://www.autoitscript.com/forum/topic/167722-sl3nck-calculate-ncks-from-target_hash-and-master_sp_code/

Edit: There apparently are versions of NCK.
