### ISSUE TITLE
How to unlock Nokia Lumia phones?

### ISSUE THREAD

**Issue by MESWEB** [openwall/john#4172]
I know hot to crack old Nokia SL3 sim-lock but what about Nokia Lumia with Windows? I have IMEI but hot to calculate unlock code?
OK Nokia Lumia probably have SL30 - 20 digit and for unlock it is only required IMEI for crack code.

**Comment by ghost** [comment]
The GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. To receive user support from the community, please use the john-users mailing list instead.

**Comment by magnumripper** [comment]
I fully agree with Claudio - please post this to john-users mailing list and hopefully we'll get input enough from the community to add a format. I have absolutely no idea just *what* to implement. Once someone has, I can do it.
