### ISSUE TITLE
Our PKCS#12 PBE functions "convert" to UTF-16BE by casting to uint16_t

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4179]
Apparently our PKCS#12 PBE functions (derived from PolarSSL/mbedTLS) are written by someone believing a UTF-16 conversion is done by inserting nulls to a normal string!? Either that, or actual implementations (eg. Bestcrypt, BKS (BouncyCastle), PFX, SAP-PSE, Signal, Zed Archives) all do exactly that? But, then, what is the expected input? Perhaps non-Latin1 passwords are rejected? Perhaps they all actually use UTF-8 interleaved with nulls (on Windows too? I doubt that).

I'm not sure which - but need to figure it out. I'll dig into OpenSSL and others. **All** formats mentioned above need test vectors added, containing characters outside ISO-8859-1.

We've had this bug (provided it is a bug) ever since June 2016 (directly imported from mbedTLS).

🙄

**Comment by magnumripper** [comment]
> **All** formats mentioned above need test vectors added, containing characters outside ISO-8859-1.

BTW I need help with that! I can do most all other parts of this, but not that (given we need **real** test vectors created by original software, not any kind of "pass_gen.pl" tool).

My preferred test vector password for this is "Op€nwal£" (you can copy/paste from here) because it does contain one non-ASCII character *within* ISO-8859-1 (so this "cast to short" may actually work) as well as one outside that codepage. Once we get that test vector to pass a self-test we can safely assume we've got all cases covered (and until we do, that very password is "debuggable" without too much effort because those two characters can be brute forced).

**Comment by magnumripper** [comment]
OK so I was given a test vector for the (only PR as of yet) Zed! format and it confirmed that mbedTLS and our code derived from it was buggy. Once fixed (adding proper UTF-16BE conversion in `pkcs12_plug.c`) the Zed format works again. But now it turns out the PFX (.p12) format had a UTF-8 test vector, **AND IT NOW FAILS**.

This is intriguing. I'm not sure what exactly @kholia used when he created that test vector - but that software apparently "converts" by interleaving just any input with zeros. Even UTF-8. Wow. Just wow. I can't rule out that Dhiru somehow did something wrong though. Perhaps he was using ISO-8859-1 or CP1252 and called it "UTF-8" just because it was non-ASCII... no, wait. That couldn't ever end up like this. If he was using the real software (as opposed to some "pass_gen.pl"), that software has this idiot bug.

Anyway we should submit a bug report to mbedTLS. Oh, and if you hear some ignorant coder stating "it works for most input", you might want to reply that it actually only works for 0.18% of Unicode characters. A fifth of a percent. Even if we only look at UCS-2 you only get 0.46% of the character set right.

**Comment by magnumripper** [comment]
I suppose I need to revert my bug fix and change our PKCS#12 PBE functions to accept binary data instead of a string. Then convert within the format instead (like we use to do). With that change, we can have seom formats (like Zed) do the correct UTF-16 conversion while others (like PXE) can continue doing it the wrong way, for bug compatibility.

The other solution (it might be better, I haven't decided yet) is to keep my code as-is, feed the PXE format eg. UTF-8 but tell JtR it's ISO-8859-1. That does make the UTF-8 test vector pass because it will be interleaved by zeros, correct or not.

**Comment by magnumripper** [comment]
I now opened an issue with mbedTLS. I need to check out OpenSSL...

**Comment by ghost** [comment]
* In the first approach you do what upstream does.
* On the second you highlight (and accept) the bug.

I prefer the 1st. Reading you I would say the bug is a devil monster (never acceptable here)

**Comment by magnumripper** [comment]
> * In the first approach you do what upstream does.

It's more complicated than that: Let's say we have an implementation of the Signal app linked to mbedTLS. The app will have the bug. On some other platform you have the exact same Signal implementation but compiled with some other lib that doesn't have the bug. So that Signal app wont have the bug. Which of them is our upstream? Both are! So we need to be able to switch between bug compatible or bug free at run time.

Now, here's the thing: My current code (in #4185 where I fixed the bug) **can** actually still replicate the bug, for instance if you feed it with UTF-8 but state `--input-encoding=iso-8859-1`. Doing this makes the PFX format pass self-test again! I think that's how we'll handle this until we see what mbedTLS, OpenSSL and others do to fix this.

The one remaining problem then, is how to explain this to our end users... 🙄

**Comment by magnumripper** [comment]
Apparently OpenSSL doesn't have this bug *if used correctly*. It has functions like `OPENSSL_asc2uni()` which works just like mbedTLS but it also has `OPENSSL_utf82uni()` and as long as the latter is used, you are bug free. The UTF-8 functions were added in November 2015.

Edit:
https://mta.openssl.org/pipermail/openssl-dev/2016-August/008371.html
