### ISSUE TITLE
AMD OpenCL support

### ISSUE THREAD

**Issue by ghost** [openwall/john#4188]
AMD has removed the `OpenCL AMD APP SDK for Windows and Linux` files from their servers.

It seems that the necessary steps to make AMD OpenCL work has changed. Anyway, it is still possible to find and get drivers/SDK for AMD products (I guess):
* https://gpuopen.com/compute-product/opencl-sdk/

We need some tests (hardware and volunteers).

**Comment by ghost** [comment]
See #4187

(Maybe) We should start saying AMD hardware must be avoided.

****
Notes and link(s):
* Previous SDK can be found in the internet, **_use at your own risc_**; E.g.:
  * https://www.softpedia.com/get/Programming/SDK-DDK/ATI-Stream-SDK.shtml

**Comment by FFY00** [comment]
Hey, I have a RX 5700 XT (NAVI10) and I would really like to see this working. I am available to test.

Right no when I run `john --form=wpapsk-opencl dump` john gets stuck in the following output:
```
Device 1: AMD NAVI10 (DRM 3.36.0, 5.5.9-arch1-2, LLVM 11.0.0)
Using default input encoding: UTF-8
Loaded 66 password hashes with no different salts (wpapsk-opencl, WPA/WPA2/PMF/PMKID PSK [PBKDF2-SHA1 OpenCL])
/
```

On ctrl+c it gets stuck on `Wait...`, I have to force close by issuing a ctrl+c again.

**Comment by FFY00** [comment]
By the way:

```
Platform #0 name: Clover, version: OpenCL 1.1 Mesa 20.1.0-devel (git-ee9e0d1eca)
    Device #0 (1) name:     AMD NAVI10 (DRM 3.36.0, 5.5.9-arch1-2, LLVM 11.0.0)
    Device vendor:          AMD
    Device type:            GPU (LE)
    Device version:         OpenCL 1.1 Mesa 20.1.0-devel (git-ee9e0d1eca)
    Driver version:         20.1.0-devel
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          8 GB
    Local Memory:           32 KB (Local)
    Constant Buffer size:   2047 MB
    Max memory alloc. size: 6553 MB
    Max clock (MHz):        2080
    Max Work Group Size:    256
    Parallel compute cores: 40
    Stream processors:      2560  (40 x 64)
    Speed index:            5324800
```

**Comment by solardiz** [comment]
IIRC, things never quite worked with Mesa. I didn't look into what Claudio said here yet, but previously one needed AMD's OpenCL runtime - AMDGPU-Pro or ROCm. Has this really changed?

**Comment by solardiz** [comment]
> AMD has removed the `OpenCL AMD APP SDK for Windows and Linux` files from their servers.

Was this even relevant? As I recall, APP SDK was needed for two purposes: to use CPU as OpenCL device (as a worse alternative to Intel's SDK) or to use GPUs with the old fglrx driver. It was already obsolete for GPUs when AMD switched from fglrx to AMDGPU-Pro and ROCm a few years ago. When installing AMDGPU-Pro / ROCm instead of fglrx, like we've already been doing in recent years, APP SDK was not needed.

Am I missing something? (Not an expert here.)

@FFY00 Please download AMDGPU-Pro from here:

https://www.amd.com/en/support/graphics/amd-radeon-5700-series/amd-radeon-rx-5700-series/amd-radeon-rx-5700-xt

For example, this:

```
Ubuntu x86 64-Bit
Radeon™ Software for Linux® Driver for Ubuntu 18.04.3
Revision Number
19.50
File Size
308 MB
Release Date
12/19/2019
```

or whatever is latest at the time you approach this and fits your operating system.

Please confirm that this works, and I guess we'll close this issue as a non-issue/confusion, which I think it was.

Mesa non-working is a separate issue unrelated to what Claudio opened this issue for.

**Comment by magnumripper** [comment]
> > AMD has removed the `OpenCL AMD APP SDK for Windows and Linux` files from their servers.
> 
> Was this even relevant? As I recall, APP SDK was needed for two purposes: to use CPU as OpenCL device (as a worse alternative to Intel's SDK) or to use GPUs with the old fglrx driver. It was already obsolete for GPUs when AMD switched from fglrx to AMDGPU-Pro and ROCm a few years ago. When installing AMDGPU-Pro / ROCm instead of fglrx, like we've already been doing in recent years, APP SDK was not needed.

Some of our build bots use it, I guess that's what Claudio meant.

**Comment by solardiz** [comment]
> Some of our build bots use it, I guess that's what Claudio meant.

OK, but this is unrelated to us supporting AMD hardware, and besides we can continue using old versions (or final version) of APP SDK for our build bots' testing on CPU, and we can also use Intel's OpenCL there.

**Comment by ghost** [comment]
I give up. Closing. 
****
This is the AMDGPU-Pro proprietary driver (on Linux, the stack is hybrid).

| OS  | Format | Speed |
| -- | -- | --- |
| Windows | sha512crypt-opencl | 14k c/s |
| Linux [2] | sha512crypt-opencl | 6.5k c/s |
| Windows | sha256crypt-opencl | 35k c/s |
| Linux [2] | sha256crypt-opencl | 35k c/s |

IMO:
* I had a hard time looking for the device driver on Linux.
  * note to self: the `--opencl=legacy,pal` installer option.
* AMD GPUs should NOT be considered a good choice on Linux
****
[2] snap binary 1.9J2+6526851X
```
Platform #0 name: AMD Accelerated Parallel Processing, version: OpenCL 2.1 AMD-APP (3075.10)
    Device #0 (1) name:     gfx902
    Board name:             Unknown AMD GPU
    Device vendor:          Advanced Micro Devices, Inc.
    Device type:            GPU (LE)
    Device version:         OpenCL 2.0 AMD-APP (3075.10)
    Driver version:         3075.10 (PAL,HSAIL) - AMDGPU-Pro  
    Native vector widths:   char 4, short 2, int 1, long 1
    Preferred vector width: char 4, short 2, int 1, long 1
    Global Memory:          3584 MB
    Global Memory Cache:    16 KB
    Local Memory:           64 KB (Local)
    Constant Buffer size:   1740 MB
    Max memory alloc. size: 1740 MB
    Max clock (MHz):        1200
    Profiling timer res.:   1 ns
    Max Work Group Size:    256
    Parallel compute cores: 8
    Stream processors:      512  (8 x 64)
    Speed index:            614400
    SIMD width:             16
    Wavefront width:        64
    PCI device topology:    04:00.0

```

**Comment by magnumripper** [comment]
> * AMD GPUs should NOT be considered a good choice on Linux

i never considered them a good choice on any platform 😆
