### ISSUE TITLE
john.bash_completion should possibly include the "shopt -s extglob"

### ISSUE THREAD

**Issue by ghost** [openwall/john#4190]
After cloning the latest code from here, run/john.bash_completion script won't complete due to the following syntax errors:

bash: john.bash_completion: line 478: syntax error near unexpected token '('
bash: john.bash_completion: line 478: '		--regex=?(a|al|alp|alph|alpha))'

I modified line 478 so it would not die by replacing the ( and the first ) with [ and ] respectively, although this won't really work I don't think, and got a second syntax error on line 618 with the same issue:  The first ( is causing issues.

### Steps to reproduce ###
```
[localhost ~]$ git clone git://github.com/magnumripper/JohnTheRipper -b bleeding-jumbo john

[localhost ~]$ cd john/src
[localhost src]$  ./configure && make

[localhost src]$ cd ../run
[localhost run]$ ./john --test

[localhost run]$ . john.bash_completion 
bash: john.bash_completion: line 478: syntax error near unexpected token `('
bash: john.bash_completion: line 478: `		--regex=?(a|al|alp|alph|alpha))'

[localhost run]$ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
### System configuration ###
```
[localhost run]$ ./john --list=build-info .
Version: 1.9.0-jumbo-1+bleeding-97ede4a06 2019-12-24 14:31:32 +0100
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 9.2.1
GNU libc version: 2.29 (loaded: 2.29)
Crypto library: OpenSSL
OpenSSL library version: 01010104f
OpenSSL 1.1.1d FIPS  10 Sep 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer claimed resolution 1 ns, observed 60 ns
Total physical host memory: 15759 MB
Available physical host memory: 13152 MB

[localhost run]$ ./john --list=opencl-devices
Section [opencl-devices] not found.
help[:WHAT], subformats, inc-modes, rules, externals, ext-modes, ext-hybrids,
ext-filters, ext-filters-only, build-info, hidden-options, encodings,
formats, format-details, format-all-details, format-methods[:WHICH],
format-tests, sections, parameters:SECTION, list-data:SECTION,
<conf section name>

[localhost run]$ cat /etc/*-release
Fedora release 30 (Thirty)
NAME=Fedora
VERSION="30 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"



```

**Comment by ghost** [comment]
same/similar error on multiple lines.  they all appear to be issues with using () in case statement options:

bash: john.bash_completion: line 618: syntax error near unexpected token `('
bash: john.bash_completion: line 618: `		--show=?(*))'

bash: john.bash_completion: line 623: syntax error near unexpected token `('
bash: john.bash_completion: line 623: `		--users=?(-)+(L|U)*|--groups=+(-|G)*|--shells=+(-|S)*|--salts=+(-|C)*)'
 
bash: john.bash_completion: line 750: syntax error near unexpected token `('
bash: john.bash_completion: line 750: `		-+(platform|device)=[Ll]?([Ii]|[Ii][Ss]|[Ii][Ss][Tt]))'

bash: john.bash_completion: line 762: syntax error near unexpected token `('
bash: john.bash_completion: line 762: `		--+(platform|device)=)'

bash: john.bash_completion: line 776: syntax error near unexpected token `('
bash: john.bash_completion: line 776: `		--list+(+(=|:)+([a-z_-]):|:+([a-z._-])=)*([A-Za-z0-9:._-]))'

bash: john.bash_completion: line 862: syntax error near unexpected token `('
bash: john.bash_completion: line 862: `		-*+(=|:))'

**Comment by ghost** [comment]
Thanks. Patches are welcome.

If you feel confident, go ahead and make a PR.

**Comment by ghost** [comment]
Planning to work on it but limited time over next week and my initial attempts failed.

**Comment by ghost** [comment]
I am closing this as not a bug after all.  Needed to read the file more closely.  Specifically:
```
# This bash completion script requires bash version >= 4,
# and extended pattern matching features enabled. If
#       shopt -p extglob
# prints
#       shopt -s extglob
# then the extended pattern matching features are enabled. If this command
# prints
#       shopt -u extglob
# then they are disabled.

```

I had to add 

`shopt -s extglob
`

To start of script.

Maybe leave this here though for anyone else who may run into same issue?

**Comment by magnumripper** [comment]
Thanks for reporting - this is interesting though: Perhaps we should add the `shopt -s extglob` to the start of the script? I can't see any reason not to, if it was already enabled it will be silently ignored. Re-opening for considering this.

**Comment by ghost** [comment]
That would've saved me a couple of hours of digging, testing, searching and reading...  I vote yes to making that pretty simple change.

**Comment by frank-dittrich** [comment]
I didn't add this to the begin of the bash completion script for the following reason:
If you source john.bash_completion into your .bashrc, this change will affect not just bash completion for john, but bash completion in general. Some distributions enable this setting by default, some don't.
So I didn't want to mess with this setting.

**Comment by frank-dittrich** [comment]
Something like this seems to work:
```
diff --git a/run/john.bash_completion b/run/john.bash_completion
index 842ab3a6c..4353ad233 100644
--- a/run/john.bash_completion
+++ b/run/john.bash_completion
@@ -30,6 +30,12 @@
 # . <path_to_john's_source_directory>/john.bash_completion
 # to your ~/.bashrc and logout/login.
 #
+
+# Current extglob setting (restored at end of script)
+__JtR_bash_completion_extglob=`shopt -p extglob`
+# Enable extglob setting
+shopt -s extglob
+
 # To use the same completion rules not just for john, but for
 # differently named binaries (say john-omp, john-sse2i, john-avx,
 # john-cuda, john-gpu, ...),
@@ -939,3 +945,6 @@ _unique()
        esac
 } &&
 complete -F _unique unique
+if [[ "$__JtR_bash_completion_extglob" == "shopt -u extglob" ]]; then
+       shopt -u extglob
+fi
```

```
[fd@localhost run]$ shopt -p extglob 
shopt -s extglob
[fd@localhost run]$ shopt -u extglob 
[fd@localhost run]$ . john.bash_completion
[fd@localhost run]$ shopt -p extglob 
shopt -u extglob
[fd@localhost run]$ ./john --l
--length=     --list=       --log-stderr  --loopback    
[fd@localhost run]$ ./john --l
```
