### ISSUE TITLE
telegram2john (and all other similar tools) need to strip `:` from path before using it as "login" field

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4200]
https://www.openwall.com/lists/john-users/2020/01/12/1

telegram2john (and all other similar tools) need to strip/replace any `:` from path before using it as "login" field or any other field. Easiest fix is to always use `basename(3)` on all paths always, although for GECOS fields we might actually want parts of directory names.

**Comment by solardiz** [comment]
Using `basename` on all pathnames is not a sufficient fix: the name of the file or directory itself might contain a colon - unlikely, but possible. I think we should be replacing all colons with e.g. spaces.

**Comment by solardiz** [comment]
I think this was a dupe of #4120.
