### ISSUE TITLE
--cost option no longer pruning self-tests

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4211]
I just noticed that even though using `--cost` we [now] still require all test-vectors to pass self-test. Until some while ago (not sure when this changed) you could use eg. `--cost=2007:2010` to not only skip *benchmarking* for Office 2013 with the Office format, but also skip the *test vectors* for that cost.

There are pros and cons but the old behavior was good for narrowing down problems and I think it was better.

**Comment by solardiz** [comment]
> I just noticed that even though using `--cost` we [now] still require all test-vectors to pass self-test. Until some while ago (not sure when this changed) you could use eg. `--cost=2007:2010` to not only skip _benchmarking_ for Office 2013 with the Office format, but also skip the _test vectors_ for that cost.
> 
> There are pros and cons but the old behavior was good for narrowing down problems and I think it was better.

Interesting observation, but the current behavior isn't a bug, so there's little reason to keep this issue open for 4+ years without plans to work on it.
