### ISSUE TITLE
John is showing: DONE Session completed and when I type: C:\John\run>john —show “john.pot” it says 0 hashes cracked, 0 left it took me four days to crack this hash what do I do to get it back?

### ISSUE THREAD

**Issue by YaBoiTrump** [openwall/john#4213]
### IMPORTANT ###
This is not a support forum, it's a bug tracker. If you don't understand the difference, please do NOT open an issue. For questions and support, review recent postings on the john-users mailing list at https://www.openwall.com/lists/john-users/ and then subscribe to the list at https://www.openwall.com/john/#lists and post your message to the list by e-mailing `john-users at lists.openwall.com`.

We are not interested in bugs in your distro-supplied and/or several years old Jumbo. Please do not open an issue unless you tried the latest version from HERE first.

### Steps to reproduce ###
Try to be clear about your environment and what you are doing. If possible, share a sample hash or file that can be used to reproduce.

### System configuration ###
Attach details about your OS and about JtR, including:
- `$ ./john --list=build-info`.
- `$ ./john --list=opencl-devices` (if applicable).

**Comment by ghost** [comment]
Please, clarify. 

Probably, you only need to specify `--format` in the command line. 
* So, something like `john --show --format=name`

**Comment by ghost** [comment]
The GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. To receive user support from the community, please use the john-users mailing list instead.

**Comment by solardiz** [comment]
This is being discussed on john-users, and as Claudio correctly says is off-topic for our use of GitHub issues. Closing.

https://www.openwall.com/lists/john-users/2020/02/22/2
