### ISSUE TITLE
diskcryptor support issues

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4215]
I've just troubleshooted what looked like a weird segfault within OpenSSL only occurring on a system with AVX-512, but turned out to be a bug in our code, for now fixed in my tree with:

```diff
index 30d4864..1a9d565 100644
--- a/src/diskcryptor_fmt_plug.c
+++ b/src/diskcryptor_fmt_plug.c
@@ -139,11 +139,16 @@ static int crypt_all(int *pcount, struct db_salt *salt)
 #endif
                // kdf
 #ifdef SIMD_COEF_64
-               for (i = 0; i < MIN_KEYS_PER_CRYPT; ++i) {
+               for (i = 0; i < MIN_KEYS_PER_CRYPT && index+i < count; ++i) {
                        lens[i] = saved_len[index+i];
                        pin[i] = (unsigned char*)saved_key[index+i];
                        pout[i] = seed[i];
                }
+               for (; i < MIN_KEYS_PER_CRYPT; ++i) {
+                       lens[i] = 0;
+                       pin[i] = pin[0];
+                       pout[i] = seed[i];
+               }
                pbkdf2_sha512_sse((const unsigned char**)pin, lens, cur_salt->salt, cur_salt->saltlen, 1000, pout, 64, 0);
 #else
 
```

I suspect this kind of problems exist in other formats, as I guess Dhiru copy-pasted this from elsewhere. We'll need to audit all formats for this.

Other issues I noticed:

`opencl_diskcryptor_aes_fmt_plug.c` has:

```c
#define ITERATIONS              10000
```

and apparently uses that for auto-tuning, yet prints 1000 at runtime?

Also, is its use of `FMT_OMP` perhaps stale and wrong (was valid for the non-AES-specific format)?

We don't appear to have the +x bit on `diskcryptor2john.py`, yet the documentation asks to invoke this script directly.

The help output of `diskcryptor2john.py` should probably be revised not to talk about "mounting", and should be included in the documentation as well.

I heard from Dhiru in response to my e-mails on some of this, and he provided some other related answers, but he's unavailable to help further.

**Comment by magnumripper** [comment]
> I suspect this kind of problems exist in other formats, as I guess Dhiru copy-pasted this from elsewhere. We'll need to audit all formats for this.

Yeah, I'd guess a LOT of formats.

> Other issues I noticed:
> 
> `opencl_diskcryptor_aes_fmt_plug.c` has:
> 
> ```c
> #define ITERATIONS              10000
> ```
> 
> and apparently uses that for auto-tuning, yet prints 1000 at runtime?

This is also a very common copy-paste bug, although mostly cosmetical.

**Comment by magnumripper** [comment]
The problems were from having uninitilized `saved_len[index+i]`, right? So using calloc instead of alloc would be an option.

**Comment by solardiz** [comment]
> The problems were from having uninitilized `saved_len[index+i]`, right?

Yes.

> So using calloc instead of alloc would be an option.

I guess so, but then once those indices were ever written to we'd be wasting time on computing SHA-512 of stale data up to that length even in future `crypt_all` calls where those indices are possibly beyond `count`, although with most cracking modes this is rare.
