### ISSUE TITLE
--format=bitlocker-opencl  No OpenCL devices found

### ISSUE THREAD

**Issue by ly20180228** [openwall/john#4223]
我的显卡是RTX2070s，在windows下使用
./john --format=bitlocker-opencl --wordlist=wordlist.txt bitlocker_hash.txt
会提示No OpenCL devices found

在Kali-Linux下使用
sudo john --format=bitlocker-opencl /home/kali/Desktop/bitlocker_hash.txt
会提示Unknown ciphertext format name requested
 

 JtR team developed the CPU version of this attack (--format=bitlocker)  运行正常

**Comment by ghost** [comment]
JtR can't find the OpenCL drivers needed to run an OpenCL format.
- you have to install the needed GPU drivers;
- you have to install the OpenCL SDK.

The procedure depends on your hardware (manufacturer, technology, age, ...). It is NOT related to John the Ripper itself.

That said:
> The GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. To receive user support from the community, please use the john-users mailing list instead.

**Comment by ghost** [comment]
It seems you have an RTX2070. So:
- From https://developer.nvidia.com/opencl:
  OpenCL support is included in the latest NVIDIA GPU drivers, available at www.nvidia.com/drivers

* And:
![image](https://user-images.githubusercontent.com/1702923/76145233-8c992980-6066-11ea-9c82-e73a59116c6a.png)
