### ISSUE TITLE
Windows issue after 0674b69

### ISSUE THREAD

**Issue by ghost** [openwall/john#4227]
The `unix` is defined in Windows CygWin. Probably, we should change the `if` to something like this:

* `if unix && ! __CYGWIN__ // MingW, etc.
`
```
#define __CYGWIN__ 1
[...]
#define unix 1
#define __INT16_MAX__ 0x7fff
```

```
john --list=build-info
Error: Cannot find John home. Invoke the program via full or relative pathname.
For example, /full/path/john or path/john, or set and use a shell alias.
Command exited with code 1
```

**Comment by solardiz** [comment]
Oh. Does Cygwin define any generic macro indicating it's Windows? Like what does this say? -

```
gcc -dM -E - < /dev/null | grep WIN
```

Maybe we can have:

```
#if defined(__unix__) && !defined(_WIN32) && !defined(_WIN64)
```

I now wonder if DJGPP possibly defines `__unix__` as well... if so, we need to exclude it too.

With all those exclusions, we could as well drop the check for `__unix__` and only check for the exclusions.

**Comment by solardiz** [comment]
I've just tried grepping what we already check for in various places, and it's quite inconsistent. Let's not be adding even more inconsistency. In `os.h`, we have this:

```c
#if defined(__DJGPP__) || defined(__CYGWIN__) || defined(_MSC_VER) || defined(__MINGW32__)
```

So I suggest we simply use the inverse of this check, and drop the check for `__unix__`.

In some places, we also check for `__MINGW64__`, but I guess `__MINGW32__` is also set on those builds, so no need to check both.

**Comment by ghost** [comment]
I found none:
* https://ci.appveyor.com/project/claudioandre-br/johntheripper/build/job/6kapis4cg5d8aj75#L330

The most interesting stuff I found is WINT_*. E.g., `__WINT_TYPE__`

**Comment by ghost** [comment]
Running CI now.
