### ISSUE TITLE
Report speed with SI symbol k for kilo

### ISSUE THREAD

**Issue by AlbertVeli** [openwall/john#4230]
According to the international system of units kilo is written with a lower-case **k** while john reports speeds with a capital **K**. See https://en.wikipedia.org/wiki/Kilo-

# Steps to reproduce
Run john and check how it reports performance. If the kilo prefix is used it looks something like this:
```1011Kc/s```

**Comment by solardiz** [comment]
I'd rather not change this. On one hand, yes there's that in SI. On the other hand, capital K doesn't clash with anything relevant (to my knowledge) and is more consistent with our use of M, G, T, which match SI and thus should stay as-is.

https://en.wikipedia.org/wiki/International_System_of_Units#Prefixes

Besides, if we change this now, we'll have a mix of lowercase k and uppercase K in JtR benchmark results and status lines that people report, and probably even in some examples that we ourselves have recorded in documentation, wiki, etc.

Does anyone else have a preference on this?

I also think we have plenty of real issues to spend our time on, whereas this is a bikeshed.

Tentatively setting this to WONTFIX, and will likely close soon.

**Comment by solardiz** [comment]
I guess SI's use of lowercase k is historical, consistent with its similarly historical use of "kg" as a base unit and its use of uppercase K for Kelvin. I think I understand and agree with those choices of theirs, but all of this is mostly irrelevant to us.

**Comment by solardiz** [comment]
A reason in favor of @AlbertVeli's suggestion is that it'd be consistent with hashcat, which uses:

```c
static const char UNITS[7] = { ' ', 'k', 'M', 'G', 'T', 'P', 'E' };
```

**Comment by magnumripper** [comment]
We could claim that our figure shows expected speed of ambient temperature change, in Kelvins per second.

I'd rather keep `K` and shift by 10 instead of dividing by 1000, but that's me and it would give all the legacy problems already mentioned. Let's postpone fixing this issue until all other issues are closed 😇

**Comment by AlbertVeli** [comment]
That is ok. Good to have an issue anyway in case somebody else wonders, then they can look at the comments here.
