### ISSUE TITLE
GPU not working with JtR

### ISSUE THREAD

**Issue by lw3eov** [openwall/john#4253]
Hello,

I am running windows 7, and John 1.9.0 jumbo, I am not sure if I am using the right command or if the software is not working properly when I try to make John use my GPU. Please have a look at the following images and let me know exactly how I should write the command for that. Thanks. Regards. Marcelo.  
![john-win64](https://user-images.githubusercontent.com/54790557/79389804-0d402500-7f45-11ea-9f14-c4a7e98d589f.jpg)

**Comment by solardiz** [comment]
You should use the `--format=wpapsk-opencl` option.

For further user support questions, if any, please use the john-users mailing list and please copy-paste text from your terminal instead of using screenshots.
