### ISSUE TITLE
CL_DEVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by ghost** [openwall/john#4256]
john --list=opencl-devices
0: Error creating context for device 0 (0:0): CL_DEVICE_NOT_AVAILABLE (-2), giving up
#########################################################################

DIST : ARCH
DE : KDE

########################################################################
Currently installed

extra/intel-tbb 2020.2-1
extra/xf86-video-intel 1:2.99.917+906+g846b53da-1
community**/intel-gmmlib** 20.1.1-1 [installed]
community/intel-graphics-compiler 1:1.0.3771-1
community/intel-opencl-clang 10.0.0.1-1
aur/intel-compute-runtime-git 19.21.13
aur/intel-opencl 5.0.r63503-2 (27, 0.047604)
aur/intel-opencl-runtime 1:18.1.0.013-2 (52, 0.104309)
###########################################################################
clinfo
###########################################################################3

Number of platforms                               2
Platform Name                                   Intel(R) OpenCL
Platform Vendor                                 Intel(R) Corporation
Platform Version                                OpenCL 1.2 
Platform Profile                                FULL_PROFILE
Platform Extensions                             cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64
Platform Extensions function suffix             INTEL

Platform Name                                   Clover
Platform Vendor                                 Mesa
Platform Version                                OpenCL 1.1 Mesa 20.0.5
Platform Profile                                FULL_PROFILE
Platform Extensions                             cl_khr_icd
Platform Extensions function suffix             MESA

Platform Name                                   Intel(R) OpenCL
Number of devices                                 1
Device Name                                     Intel(R) Xeon(R) CPU           X5472  @ 3.00GHz
Device Vendor                                   Intel(R) Corporation
Device Vendor ID                                0x8086
Device Version                                  OpenCL 1.2 (Build 475)
Driver Version                                  1.2.0.475
Device OpenCL C Version                         OpenCL C 1.2 
Device Type                                     CPU
Device Profile                                  FULL_PROFILE
Device Available                                Yes
Compiler Available                              Yes
Linker Available                                Yes
Max compute units                               8
Max clock frequency                             3000MHz
Device Partition                                (core)
Max number of sub-devices                     8
Supported partition types                     by counts, equally, by names (Intel)
Supported affinity domains                    (n/a)
Max work item dimensions                        3
Max work item sizes                             8192x8192x8192
Max work group size                             8192
Preferred work group size multiple              <getWGsizes:1171: create context : error -2>
Preferred / native vector sizes                 
char                                                 1 / 16      
short                                                1 / 8       
int                                                  1 / 4       
long                                                 1 / 2       
half                                                 0 / 0        (n/a)
float                                                1 / 4       
double                                               1 / 2        (cl_khr_fp64)
Half-precision Floating-point support           (n/a)
Single-precision Floating-point support         (core)
Denormals                                     Yes
Infinity and NANs                             Yes
Round to nearest                              Yes
Round to zero                                 No
Round to infinity                             No
IEEE754-2008 fused multiply-add               No
Support is emulated in software               No
Correctly-rounded divide and sqrt operations  No
Double-precision Floating-point support         (cl_khr_fp64)
Denormals                                     Yes
Infinity and NANs                             Yes
Round to nearest                              Yes
Round to zero                                 Yes
Round to infinity                             Yes
IEEE754-2008 fused multiply-add               Yes
Support is emulated in software               No
Address bits                                    64, Little-Endian
Global memory size                              20992946176 (19.55GiB)
Error Correction support                        No
Max memory allocation                           5248236544 (4.888GiB)
Unified memory for Host and Device              Yes
Minimum alignment for any data type             128 bytes
Alignment of base address                       1024 bits (128 bytes)
Global Memory cache type                        Read/Write
Global Memory cache size                        6291456 (6MiB)
Global Memory cache line size                   64 bytes
Image support                                   Yes
Max number of samplers per kernel             480
Max size for 1D images from buffer            328014784 pixels
Max 1D or 2D image array size                 2048 images
Max 2D image size                             16384x16384 pixels
Max 3D image size                             2048x2048x2048 pixels
Max number of read image args                 480
Max number of write image args                480
Local memory type                               Global
Local memory size                               32768 (32KiB)
Max number of constant args                     480
Max constant buffer size                        131072 (128KiB)
Max size of kernel argument                     3840 (3.75KiB)
Queue properties
Out-of-order execution                        Yes
Profiling                                     Yes
Local thread execution (Intel)                Yes
Prefer user sync for interop                    No
Profiling timer resolution                      1ns
Execution capabilities
Run OpenCL kernels                            Yes
Run native kernels                            Yes
SPIR versions                                 1.2
printf() buffer size                            1048576 (1024KiB)
Built-in kernels                                (n/a)
Device Extensions                               cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64

Platform Name                                   Clover
Number of devices                                 0

NULL platform behavior
clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
clCreateContext(NULL, ...) [default]            No platform
clCreateContext(NULL, ...) [other]              <checkNullCtx:2758: create context with device from non-default platform : error -2>
clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

**Comment by magnumripper** [comment]
This is not a bug. Consult the john-users mailing list for support

**Comment by ghost** [comment]
Ok after looking into opencl runtime and specs on intel , the latest runtime 18.1 doesn't support xeon processors, the previous version 16.2 supports them , that's what the problem is

please leave it open in case someone else has the same problem

**Comment by magnumripper** [comment]
> please leave it open in case someone else has the same problem

Sorry, no. That's a support issue and this is not a support forum. You would have known if you would have cared to read just a few couple of sentences before wasting our time.

**Comment by ghost** [comment]
no problem, sorry to brother you, it must be that time of the month for you . thanks, you have been most helpful during this difficult time of yours

**Comment by magnumripper** [comment]
It's not that we don't want to help you, it's that you ask for it in the wrong place
