### ISSUE TITLE
Non riesco a proseguire con John the Ripper al secondo passaggio: estrarre le hash

### ISSUE THREAD

**Issue by Antonio716** [openwall/john#4257]
Sto cercando già da due/tre giorni di craccare le password con John the Ripper,il primo passaggio sono riuscito a fare perchè ha mostrato le hash del file protetto da password di cui non conosco nemmeno la password,nel primo passaggio ho utilizzato rar2john (percorso del file) e infine hashes,mentre sul secondo ho provato in tutti i modi scrivendo john hashes,john hash.txt e mi dava 
Using default input encoding: UTF-8;No password hashes loaded (see FAQ).Poi ho fatto un passo in avanti perchè ho scoperto come si fa parzialmente la codifica in UTF-8,ho messo questo comando: john (percorso del file) hashes e mi ha dato: Warning: Only 44 candidates buffered for the current salt, minimum 64 needed for performance,Proceeding with wordlist:password.lst, rules:Wordlist,Error, dictionary file is empty e poi si è bloccato qua e non riesco più ad andare avanti,comunque sto tentando di fare questa cosa su windows 10 sempre vedendo tanti forum e cercando tanti siti su internet e ancora non ho imparato,mi piacerebbe imparare questa cosa perchè sono curioso di sapere, se qualcuno mi può dare gentilmente una risposta riguardo a questa cosa.

**Comment by solardiz** [comment]
We use GitHub issues to track issues with our software, not user support requests. What you write appears to be a user support request. We also use English here.

Please join the john-users mailing list and post your user support request in there, in English:

https://www.openwall.com/john/#lists
