### ISSUE TITLE
index-pack failed error while cloning JRT

### ISSUE THREAD

**Issue by techhaze** [openwall/john#4262]
Hi,

Trying to clone the git repository for JRT. But, I keep getting the following error. 

Trying to figure why it happens. 

Thanks in advance!

![f3fefda0d3373f276962290529eedf10bfd4ad34c7c41a7bf76e93d20ea8c927](https://user-images.githubusercontent.com/65384784/82013492-8c548480-96ce-11ea-828c-b102ee862e40.png)

OS info:  **Ubuntu Virtual Machine 18.04 (bionic)**

**Comment by solardiz** [comment]
Looks like you ran out of RAM in the VM. Please try adding more RAM.

Closing this since it isn't an issue with the repo, as far as we're currently aware.
