### ISSUE TITLE
ld: multiple definition of 'ztex*'

### ISSUE THREAD

**Issue by its5Q** [openwall/john#4264]
There are multiple errors from ld about multiple definitions of variables in ztex .c files. There is a similar pull request regarding this issue but on OpenCL.
https://github.com/magnumripper/JohnTheRipper/pull/4258
Also it's worth noting, that using 1.9.0 release code, it gives the same error.
### Steps to reproduce ###
Clone the bleeding-jumbo branch
Use ./configure --enable-ztex to enable ZTEX FPGA support
Do make -s clean && make -sj4 and get the errors

### System configuration ###
OS: Arch Linux x86_64
Kernel: 5.6.12
CPU: Intel Atom Z3735F
FPGA: ZTEX 1.15y official board

**Comment by solardiz** [comment]
@lev4ukpavel2 What are your versions of gcc and binutils?

**Comment by its5Q** [comment]
@solardiz gcc 10.1.0-1 and binutils 2.34-3

**Comment by solardiz** [comment]
@lev4ukpavel2 I don't currently have versions this recent installed anywhere, so can't readily trigger this problem. Would you like to work on fixing this issue for us? Alternatively, I suppose @claudioandre-br can look into it by building with `--enable-ztex` even though he doesn't have a ZTEX board. Or another one of us will look into it later.

**Comment by its5Q** [comment]
@solardiz I just tested it, it works on GCC 9, so the problem is only present on GCC 10. I don't really have a lot of C++ programming experience, so I won't be able to provide a solution.

**Comment by ghost** [comment]
I can mute the warnings, but I won't be able to test it properly. I guess we can keep JtR as is, for a while, at least.

**Comment by solardiz** [comment]
PR #4270 should fix this issue. @lev4ukpavel2 We'd appreciate it if you test that PR's branch (or just bleeding-jumbo after the PR is merged) with gcc 10 and make sure the code not only compiles, but also works for you and your hardware correctly. Thanks!

**Comment by solardiz** [comment]
@lev4ukpavel2 Can you please confirm that this issue is fixed or let us know if it is not? Thanks!

**Comment by its5Q** [comment]
> @lev4ukpavel2 Can you please confirm that this issue is fixed or let us know if it is not? Thanks!

OK, I will try to build JtR with ztex support tomorrow and see if everything works.

**Comment by its5Q** [comment]
I've tried compiling it on gcc 10.3.0 and it compiled and worked as expected with ZTEX support. Thanks for fixing the issue, I will now close it.
