### ISSUE TITLE
#new feature request: please add OpenCL support for old ZIP files.

### ISSUE THREAD

**Issue by BarrowHill** [openwall/john#4265]
almost 3 days I'm trying to crack ZIP files and discovered that
hash file from old type ZIP files contains only 1 line
$pkzip2$
and does not have OpenCL implementation, in Linux we can get info 
$ zipdetails old_type_ZIP.zip
00008 Compression Method    0008 'Deflated'
such hashes not working with GPU e.g. -format=ZIP-opencl
and we get this error
_______
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

### Steps to reproduce ###
Trying to follow a walk-through here:
https://vulnsec.com/2017/SANS-Holiday-Hack-Challenge-2016/
so taking the zip hash of http://northpolewonderland.com/SantaGram_v4.2.zip <-this is old style zip file, or you can create it with Winrar: add to archive, select ZIP, set password, and enable checkbox Use Traditional (old style) compression.

### System configuration ###
Windows 10 x64, 1050Ti, tryed on 2 different versions:
john-1.9.0-jumbo-1-win64
john-1.8.0.13-jumbo-b7eae75d7-win64
PLEASE dear @magnumripper, add this function.

**Comment by magnumripper** [comment]
You'd use `-format=pkzip` to crack them. We currently don't have GPU support for it, but it's fast on CPU.

As for adding OpenCL support, we have #718 for that.

**Comment by solardiz** [comment]
@magnumripper The description of "invalid" label doesn't say we'd use it for duplicate issues, so I removed it from here. This is a fine feature request here, it's just duplicate.

Besides #718, also related are #3222, #4070, #3971. Perhaps we should make changes to minimize user confusion here. It is wrong when output of `zip2john` gets rejected by `zip-opencl` without explanation.

**Comment by magnumripper** [comment]
A dupe is definitely invalid - although it obviously shouldn't be taken as an insult. It's just that, already an other issue.

**Comment by solardiz** [comment]
@magnumripper I think we need a separate label for duplicate issues, then. Sometimes (inadvertent) duplicate issues have additional detail or additional examples and are still useful to take a look at later (by following links from other issues), whereas other kinds of invalid issues are generally useless for the project.

**Comment by magnumripper** [comment]
When I close and write "this is a dupe of #1234" it will be linked both ways - the new issue will be referenced by the original.

**Comment by magnumripper** [comment]
I'm also of the opinion that a dupe issue is more or less meaning the OP did not do proper research. Users are welcome here, but not lusers.

**Comment by solardiz** [comment]
@magnumripper While you're right about the linking and not doing proper research, I think this label on a dupe is unnecessarily too discouraging. Anyway, this is just another reminder for me to take this repo to Openwall account, as discussed. Hopefully, soon.

**Comment by magnumripper** [comment]
I'm trying to be more open-minded, @solardiz. I'll also try to be more lax until you take over (although this can potentially hit us, mind you)

**Comment by Jasko77** [comment]
Is here any updates in the meanwhile?

**Comment by solardiz** [comment]
@Jasko77 No, and I guess you meant to post your question to the actual issue #718 rather than to this closed dupe. However, the answer would have been the same - we made no progress on this, and are not currently planning to work on it.
