### ISSUE TITLE
Cannot use putty2john to create a hash file for cracking ED25519 ppk

### ISSUE THREAD

**Issue by testcb00** [openwall/john#4267]
I use PuTTYgen Release 0.70 to generate a ED25519 ppk with passphrase "a" and save the private key as ppk file. Then I transfer the ppk to Kali Linux VM (amd64) and use putty2john to generate the hash file by the follow command: putty2john 0520.ppk > 0520.hash
After the process, I use the general john 0520.hash to crack the ppk password, but meet

Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

Before the ED25519 test, I have create a ppk with RSA2048 and same passphrase "a" and successful crack it, not sure it is a build problem or not, I have tried on my Raspberry Pi 3B but no luck.

**Comment by ghost** [comment]
Well, putty format can handle ED25519. Can you share the generated ppk file? Are you sure you have an updated version of JtR? It seems ok here:

```
$ puttygen -t ed25519 -o mykey.ppk

$ ../run/putty2john ~/mykey.ppk 
mykey:$putty$1*16*1*0*aa636dad99f482685f77b10d5a70f74f5098dff6*51*0000000b7373682d6564323535313900000020ad200ba17ec88a23918229817f2449c600dd0fb438228dc9a85b1395df2571d4*48*42dd4be3c856ed21a7da03b88a7917848ab339c2c95aa71ab9adf119ef5e493e92aaad729fd91be3d5b7071400a2472e*ssh-ed25519*aes256-cbc*ed25519-key-20200531

$ ../run/john hash.txt
Using default input encoding: UTF-8
Loaded 1 password hash (PuTTY, Private Key (RSA/DSA/ECDSA/ED25519) [SHA1/AES 32/64])
Will run 32 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 10 candidates buffered for the current salt, minimum 32 needed for performance.
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:../run/password.lst
a                (mykey)
1g 0:00:00:00 DONE 2/3 (2020-05-31 15:08) 2.222g/s 350444p/s 350444c/s 350444C/s 123456..Sssing
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 

```

**Comment by testcb00** [comment]
PuTTYgen platform
PuTTYgen Release 0.70
Windows 7 x64

JtR version in Kali Linux Weekly Build kali-linux-2020-W22
John the Ripper 1.9.0-jumbo-1 OMP [linux-gnu 64-bit x86_64 AVX AC]

I finally found the reason but another problem exist. The reason is that I remove the default Key comment generated by PuTTYgen, then the ppk cannot be cracked. If the comment is remained, the ppk can be cracked.

Here is the ppk files and the hash files. the 1.ppk is the one with Key comment while 2.ppk is the one without.
[JtR-Issue_#4267.zip](https://github.com/magnumripper/JohnTheRipper/files/4707860/JtR-Issue_.4267.zip)

Both the keys are ED25519 type and Key passphrase "a". 1.ppk successful cracked by john but 2.ppk not, seems the Private-MAC is different?. Is the Private-MAC is the "salt"?
I am sorry that I am lack of knowledge in Cryptography.

**Comment by ghost** [comment]
First issue:
- putty2john generates a hash JtR can't crack (after removing the comment line). Reproduced here.

That said, we need to review the format to check if the comment is important for the the cracking process (if it is more than a comment).

**Comment by ghost** [comment]
I confirmed you can't edit the ppk file (as you did). Please, if you can reproduce the bug without editing the file, just reopen the issue.

**Comment by testcb00** [comment]
> 
> 
> I confirmed you can't edit the ppk file (as you did). Please, if you can reproduce the bug without editing the file, just reopen the issue.

Sorry for my confusing, what I mean is that I delete the "Key comment" before I save the private key ppk file. The first image is is the screenshot before I save the 1.ppk and similar second is 2.ppk.

![image](https://user-images.githubusercontent.com/31276953/83357992-17aa6700-a3ab-11ea-8bf4-05e9631320b9.png)
![image](https://user-images.githubusercontent.com/31276953/83358008-2ee95480-a3ab-11ea-884d-94b3c8cf43a9.png)

However, I also tried directly added the Key comment "ed25519-key-20200531" to 2.ppk. Considering this should be a wrong process as the Private-MAC of 1.ppk and 2.ppk is different, I don't mention this try in the first post.

**Comment by ghost** [comment]
Have you confirmed 2.ppk works in putty?

**Comment by testcb00** [comment]
Just tested, both 1.ppk and 2.ppk work in Kali Linux
First image is the result using 1.ppk and second is 2.ppk in PuTTY sessions.

![image](https://user-images.githubusercontent.com/31276953/83358492-e6cc3100-a3ae-11ea-90a0-a68ffb770206.png)
![image](https://user-images.githubusercontent.com/31276953/83358500-f481b680-a3ae-11ea-8f39-dabd9149767e.png)

**Comment by ghost** [comment]
Ok, let's see what the format maintainer thinks about it.

**Comment by kholia** [comment]
Quick patch:

```diff
diff --git a/src/putty_fmt_plug.c b/src/putty_fmt_plug.c
index a8c3bc242..3daea928b 100644
--- a/src/putty_fmt_plug.c
+++ b/src/putty_fmt_plug.c
@@ -184,10 +184,12 @@ static int valid(char *ciphertext, struct fmt_main *self)
                if (strlen(p) > 32)
                        goto err;
                if ((p = strtokm(NULL, "*")) == NULL)   /* comment */
-                       goto err;
+                       goto ok;  // comment is optional
                if (strlen(p) > 512)
                        goto err;
        }
+
+ok:
        MEM_FREE(keeptr);
        return 1;

@@ -244,7 +246,8 @@ static void *get_salt(char *ciphertext)
                p = strtokm(NULL, "*");
                strcpy(cs->encryption, p);
                p = strtokm(NULL, "*");
-               strcpy(cs->comment, p);
+               if (p)
+                       strcpy(cs->comment, p);
        }
        MEM_FREE(keeptr);
        return (void *)cs;
```

**Comment by ghost** [comment]
The patch fixes the issue.  2.ppk is crackable now.

Thanks kholia.
