### ISSUE TITLE
Is ecryptfs2john.py still up to date?

### ISSUE THREAD

**Issue by Staubgeborener** [openwall/john#4276]
Is `ecryptfs2john.py` (with Latest commit 7ff20a8 on 12 Apr 2015) still up to date? I've got this wrapped-passphrase (plaintext: _geheim123_)

```
00000000  3a 02 af 53 29 10 1a 19  3c 34 39 61 34 36 36 61  |:..S)...<49a466a|
00000010  66 31 66 66 65 35 37 31  65 30 2f 9c 74 4c 66 90  |f1ffe571e0/.tLf.|
00000020  c2 e2 db a3 a3 a5 17 21  89 d9 82 63 9e 42 db 5d  |.......!...c.B.]|
00000030  96 5b 29 b8 bf e2 67 fa  49 e2                    |.[)...g.I.|
0000003a
```

`ecryptfs2john.py` produces this string: $ecryptfs$0$1$af5329101a193c34$9a466af1ffe571e0
The structure should be like this, right?

- $ecryptfs -> standard header
- $0 -> dont know
- $1 -> is used when salt is set
- $af5329101a193c34 -> salt
- $9a466af1ffe571e0 -> hash

Is this correct? So it complete ignores the wrapped passphrase inside (bold):

00000020  c2 e2 db a3 a3 a5 17 21  89 d9 **82 63 9e 42 db 5d**
00000030  **96 5b 29 b8 bf e2 67 fa  49 e2**  

The problem: I can not crack this string with JohnTheRipper or Hashcat (Exhausted).

**Comment by ghost** [comment]
> Is ecryptfs2john.py still up to date?

Probably no. Source code refers to a "104" version; I was able to find online a newer "111" version. That said, the issue:
* review `ecryptfs2john.py` script and update it.

will be kept open. Probably, we need volunteers to work on it.

**Comment by Staubgeborener** [comment]
Woops, my fault. The plaintext password was wrong (its just the spacebar). The tool is working fine. I could crack the hash string with hashcat.

**Comment by Staubgeborener** [comment]
Woops, my fault. The plaintext password was wrong (its just the spacebar). The tool is working fine (tested with newest ecryptfs version 111). I could crack the hash string with hashcat.
