### ISSUE TITLE
Not able to install !

### ISSUE THREAD

**Issue by ivasugarg** [openwall/john#4279]
NO INSTALLATION GUIDE!

**Comment by magnumripper** [comment]
Lord give me strength

**Comment by magnumripper** [comment]
@solardiz after considering that fine user's GitHub history, I just blocked him for life. If you disagree, please proceed in taking over the repo. I'm sick of millennials wanting to be spoon fed

**Comment by solardiz** [comment]
@magnumripper OK. I think I'd be marking such issues "support", closing them so they don't clutter the issue list, but nevertheless providing a response. So yes, this is a reminder to me to move the repo to Openwall account.

**Comment by solardiz** [comment]
@magnumripper Our `README.md` in this repo refers to the rest of the documentation files (including `INSTALL`) by name without mentioning that they're in the `doc` subdirectory. Perhaps this could be (part of?) what confused @ivasugarg. Maybe there's room for improvement here.
