### ISSUE TITLE
Total revamp of wordlist.c

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#428]
Solar nags about this and he is right :-)  This file has become a mess in Jumbo over the years. No known bugs now but there may lurk some.

Best approach is probably to not actually rewrite from scratch but to restart with the core file and re-add all Jumbo features.

**Comment by solardiz** [comment]
This issue has been hanging around for 10+ years. A lot of code in jumbo needs a revamp, so there's little reason to single out one component unless we're actually planning to proceed with the work.
