### ISSUE TITLE
OpenCL build's "--test" shouldn't stop mid-way on no-OpenCL systems

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4285]
When testing an OpenCL-enabled build in AWS having launched the previously prepared AMI on one of the tiniest AWS instances (1 vCPU):

```
$ john -te=0
Warning: OpenMP is disabled; a non-OpenMP build may be faster
Testing: descrypt, traditional crypt(3) [DES 256/256 AVX2]... PASS
[...]
Testing: HMAC-SHA512 [password is key, SHA512 256/256 AVX2 4x]... PASS
No OpenCL devices found
```

Most things work sane, but `--test` shouldn't stop mid-way on no-OpenCL systems like this, so that we and our users can fully reuse the same full-featured build for CPU-only no-OpenCL systems.

**Comment by ghost** [comment]
Something like this?
```
OMP_NUM_THREADS=2 ../run/john --test=0; echo $?

Make process completed.
Will run 2 OpenMP threads
Testing: descrypt, traditional crypt(3) [DES 256/256 AVX2]... (2xOMP) PASS
Testing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 256/256 AVX2]... (2xOMP) PASS
...
Testing: tacacs-plus, TACACS+ [MD5 32/64]... (2xOMP) PASS
Testing: plaintext, $0$ [n/a]... PASS
No OpenCL devices found
Testing: dynamic_0 [md5($p) (raw-md5) 256/256 AVX2 8x3]... PASS
Testing: dynamic_1 [md5($p.$s) (joomla) 256/256 AVX2 8x3]... PASS
...
Testing: dynamic_2014 [md5($s.md5($p).$s) (PW > 55 or salt > 11 bytes) 256/256 AVX2 8x3]... PASS
Testing: dummy [N/A]... PASS
Testing: crypt, generic crypt(3) [?/64]... (2xOMP) PASS
All 181 formats passed self-tests!
0

```

**Comment by ghost** [comment]
```diff
diff --git a/src/bench.c b/src/bench.c
index 0a50588a6..c15b413b4 100644
--- a/src/bench.c
+++ b/src/bench.c
@@ -778,9 +778,18 @@ AGAIN:
 		if ((format->params.flags & FMT_DYNAMIC) ||
 		    strstr(format->params.label, "-opencl") ||
 		    strstr(format->params.label, "-ztex") ||
-		    !strcmp(format->params.label, "crypt"))
+		    !strcmp(format->params.label, "crypt")) {
+			if (strstr(format->params.label, "-opencl")) {
+				/* Allow OpenCL build's "--test" to run on no-OpenCL systems */
+				/* It is a like a hack, but it is necessary since OpenCL must be started */
+				/* to get the number of devices. The init() itself is performed only once. */
+				opencl_load_environment();
+
+				if (get_number_of_available_devices() == 0)
+					continue;
+			}
 			fmt_init(format);
-
+		}
 		/* [GPU-side] mask mode benchmark */
 		if (options.mask) {
 			static char benchmark_comment[16];
diff --git a/src/opencl_common.c b/src/opencl_common.c
index e7347d4a7..aa2ec3a2b 100644
--- a/src/opencl_common.c
+++ b/src/opencl_common.c
@@ -883,6 +883,10 @@ void opencl_load_environment(void)
 		// Ensure that there is at least one OpenCL device available
 		if (get_number_of_available_devices() == 0) {
 			fprintf(stderr, "No OpenCL devices found\n");
+			if (benchmark_running) {
+				opencl_initialized = 1;
+				return;
+			}
 			error();
 		}
 
```

**Comment by solardiz** [comment]
Thanks, @claudioandre-br!

Yes, that's one way to do it, although maybe we should instead group all of the `-opencl` formats to be benchmarked after all of the CPU ones. That can be done in one of two ways: (1) change the order in which formats are registered (which will also affect the order of `--format` option suggestions when autodetecting) or (2) go through the formats list twice (first skipping the `-opencl` formats, then skipping the rest).

I think it's weird that right now we're benchmarking and suggesting formats in a weird order. I think we should either group them by hash type (good for suggestions), which we'd do by using more consistent file names between CPU and OpenCL formats, or group them by implementation type (CPU, OpenCL, or ZTEX). All the ZTEX formats are already grouped together (and a ZTEX build is considered so specialized that I'm OK with its `--test` insisting on presence of such boards unless a `--format` is specified), but OpenCL ones are not. So perhaps we should fix that in one way or another.

**Comment by solardiz** [comment]
Claudio, in your sample output somehow the grouping is almost present - it looks like the first OpenCL benchmark is attempted inbetween almost all non-dynamic formats and dynamic+dummy+crypt. And somehow you have only 181 total. In my run, OpenCL is attempted after HMAC formats, and there would have been many more (non-dynamic) CPU formats after that point if the process didn't exit, for a total of 400+. I don't know why your test is different (deliberately excluded formats to speedup the test run?)

**Comment by ghost** [comment]
@magnumripper has something to say about format order. I guess he did this on purpose.

**Comment by solardiz** [comment]
Yes, let's wait to hear from @magnumripper. Thanks.

**Comment by ghost** [comment]
> deliberately excluded formats to speedup the test run?

Yes. The order is CPU - OpenCL -  dynamic.

**Comment by magnumripper** [comment]
The diff looks nice. I deliberately put dynamic formats last-last because they are so numerous, including completely exotic fantasy combinations of old-and-newer hashes. This even though not every dynamic is actually tested by default IIRC. There's some option to test more/all of them

Ideally (by default and IMHO), dynamic should only test code components: Just one of every hash and code-path.

**Comment by magnumripper** [comment]
```
$ ../run/john --test=0 -form:dynamic | headtail -3
Testing: as400-ssha1, AS400-SaltedSHA1 [sha1(utf16be(space_pad_10(uc($s)).$p)) (IBM AS/400 SHA1) 256/256 AVX2 8x1]... PASS
Testing: asa-md5, Cisco ASA [md5($p.$s) (Cisco ASA) 256/256 AVX2 8x3]... PASS
Testing: dynamic=md5($p) [256/256 AVX2 8x3]... PASS
(...)
Testing: dynamic_2011 [md5($s.md5($p.$s)) (PW > 32 or salt > 23 bytes) 256/256 AVX2 8x3]... PASS
Testing: dynamic_2014 [md5($s.md5($p).$s) (PW > 55 or salt > 11 bytes) 256/256 AVX2 8x3]... PASS
All 157 formats passed self-tests!
```
```
$ ../run/john --test=0 -form:all-dynamic | headtail -3
Testing: as400-ssha1, AS400-SaltedSHA1 [sha1(utf16be(space_pad_10(uc($s)).$p)) (IBM AS/400 SHA1) 256/256 AVX2 8x1]... PASS
Testing: asa-md5, Cisco ASA [md5($p.$s) (Cisco ASA) 256/256 AVX2 8x3]... PASS
Testing: dynamic=md5($p) [256/256 AVX2 8x3]... PASS
(...)
Testing: dynamic_2011 [md5($s.md5($p.$s)) (PW > 32 or salt > 23 bytes) 256/256 AVX2 8x3]... PASS
Testing: dynamic_2014 [md5($s.md5($p).$s) (PW > 55 or salt > 11 bytes) 256/256 AVX2 8x3]... PASS
All 475 formats passed self-tests!
```

The default 157 formats test **really** quick on 1-thread intel, but it may take ages on machines with a really serious number of cores and/or slow shite like a Raspberry Pi

**Comment by solardiz** [comment]
@claudioandre-br Please turn your patch posted here into a PR, and we'll get it merged. Thanks!

Also, what's "init()" in your comment "The init() itself is performed only once"? If you're referring to OpenCL initialization rather than some function named "init", then perhaps drop the braces?

**Comment by ghost** [comment]
I removed the braces.

**Comment by solardiz** [comment]
I'm fine with #4341 closing this issue, but I think longer-term we need some message about no OpenCL appearing not (only) in the middle of output, but also at the beginning or/and at the end, e.g. "All 410 formats passed self-tests! (OpenCL formats skipped.)" Claudio, please feel free to implement this now if you can, or leave it for later.
