### ISSUE TITLE
Bitcoin hash False Positive

### ISSUE THREAD

**Issue by mem50** [openwall/john#4298]
Hi,
From my bitcoin wallet I've extracted the hash using latest bitcoin2john.py script., and started john, result is:
`$bitcoin$64$XXXXX$16$XXX$199732$2$00$2$00:1234`
Password found was '1234'

But when I enter this password in Bitcoin Core:
```
bitcoin-cli  walletpassphrase 1234  600
error code: -14
error message:
Error: The wallet passphrase entered was incorrect.
```

Same with GUI.
Same with another tool that can read bitcoin-core wallet.

That's why I think it is a false positive. Let me know how I can debug this.

**Comment by solardiz** [comment]
Knowing how our Bitcoin wallet passphrase cracking works under the hood, I don't see how a false positive is possible.

I'd bet this is either a corrupted wallet or it's somehow incompatible with the tools you try to use it with - e.g., trying to use some altcoin wallet as if it were Bitcoin, etc.

Were you able to access this wallet before?

Edit: Also, does the password 1234 look realistic to you, or are you somehow sure (other than from the tools not working) that the password must be different?

Edit 2: what does `file wallet.dat` say? (Should tell us the Berkeley DB version in use by the wallet.)

**Comment by mem50** [comment]
Wallet is very old and I don't remember the password, but 1234 seems very weak!

file gives: `Berkeley DB (Btree, version 9, native byte-order)`

Any advice on how to repair a corrupted wallet?
Thanks.

**Comment by solardiz** [comment]
I suggest you try putting 1234 in the middle of a large wordlist (e.g., a few million lines, not containing 1234 anywhere else) and re-cracking the wallet's password using that wordlist. If that still finds 1234, all of us would probably be more convinced this is in fact the password. That 1234 is very weak actually indicates it's not some random false positive.

Btree `version 9` is good - can in fact be Bitcoin (with _some_ altcoins, it'd have been `version 10`).

You can try repairing with:

```
db_dump -f dump wallet-old.dat
db_load -f dump wallet-new.dat
```

on a system with compatible Berkeley DB tools installed (should be BDB 4.x or 5.x). This might or might not help. Of course, do not overwrite the old wallet file - you might need it to attempt recovering it differently.

I've tentatively marked this issue "invalid", and plan on most likely closing it soon, as currently there's no indication there's any issue with JtR here. If you manage to convince us that there is (e.g., the wordlist experiment I suggested cracks a _different_ password), we'll change the label and re-open as necessary. Thanks!

**Comment by solardiz** [comment]
@mem50 Have you done the wordlist experiment I suggested?

Also, does hashcat crack this password as 1234, too? I see you also reported https://github.com/hashcat/hashcat/issues/2511 (a real bug, which got fixed) so I guess you must have tested with hashcat as well?
