### ISSUE TITLE
Bug in zip2john or pkzip format: False negative

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4300]
I've been sent a zip file with password '123456' that our pkzip format fails to crack. I'm not sure I can share the file publically but I sent it to @jfoug and I'll be jotting down notes here.

Partial `zipinfo -v` output
```
  version of encoding software:                   2.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   2.0
  compression method:                             deflated
  compression sub-type (deflation):               normal
  file security status:                           encrypted
  extended local header:                          yes
  file last modified on (DOS date/time):          2020 Jul 13 16:45:02
  file last modified on (UT extra field modtime): 2020 Jul 14 01:45:02 local
  file last modified on (UT extra field modtime): 2020 Jul 13 23:45:02 UTC
  32-bit CRC value (hex):                         856d3284
  compressed size:                                14212 bytes
  uncompressed size:                              16909 bytes
```

Partial zip2john output, only the data blob shortened:
```
$pkzip2$1*2*2*0*3784*420d*856d3284*0*64*8*3784*856d*85a1*3d5187246d1612cc (...) 3da334f4de17a560*$/pkzip2$
```

Here's the lines that give false negative:
```c
			/* if the hash is a 2 byte checksum type, then check that value first */
			/* There is no reason to continue if this byte does not check out.  */
			if (salt->chk_bytes == 2 && C != (e&0xFF) && C != (e2&0xFF))
				goto Failed_Bailout;
```

**Comment by magnumripper** [comment]
```
$pkzip2$1*2*2*0*3784*420d*856d3284*0*64*8*3784*856d*85a1*(...DA...)
```
Parsing the above:
* C Hash count: 1
* B Number of valid bytes in checksum: 2
* DT Data type: 2 (inlined full data)
* MT Magic type: 0 (no file magic used)
* CL Compressed length: 0x3784 (14212) bytes
* UL Uncompressed length: 0x420d (16909) bytes
* CR Final CRC32: 856d3284
* OF Offset: 0
* OX Additional offset: 64
* CT Compression type: 8 (imploded)
* DL Length of inlined data: 0x3784 bytes
* CS Checksum from CRC32: 856d (this is the MSB of "Final CRC32" above)
* TC Checksum from timestamp: 85a1

All this look sane to me. Not sure what's wrong here - but if I comment out the mentioned lines in the format, everything is fine (but we lose some performance).

**Comment by magnumripper** [comment]
```c
			do
			{
				C = PKZ_MULT(*b++,key2);
				key0.u = jtr_crc32 (key0.u, C);
				key1.u = (key1.u + key0.c[KB1]) * 134775813 + 1;
				key2.u = jtr_crc32 (key2.u, key1.c[KB2]);
			}
			while(--k);

			/* if the hash is a 2 byte checksum type, then check that value first */
			/* There is no reason to continue if this byte does not check out.  */
			if (salt->chk_bytes == 2 && C != (e&0xFF) && C != (e2&0xFF))
				goto Failed_Bailout;
```
At the time of false negative, `C` is `b9`, `e` is `856d` (the expected CS) and `e2` is `85a1` (the expected TC).

**Comment by jfoug** [comment]
I will not have a lot of time to look into this for a couple days.    First,  If you comment that quick check out, it cracks just fine.

Also, the file name is strange.  I am wondering if there is some encode/decode that needs to be done which we may not be doing.  I honestly do no remember what makes up the computation of the checksum, or other fields in this format.  But since john DOES crack it without this quick check, and since the file name is certainly non-ascii, I wonder (stongly) if the file name is used somehow within this checksum computation.

**Comment by jfoug** [comment]
This is a quick 'hack', but it causes this to crack.  NOTE, I do not know if this is what we want.  It may cause other 2-byte checksum files to continue (and not bail), on some passwords.  I do not know what that would do (possible false positive).

```diff
$ git diff pkzip_fmt_plug.c
diff --git a/src/pkzip_fmt_plug.c b/src/pkzip_fmt_plug.c
index 0e876a8fb..6b1b3badb 100644
--- a/src/pkzip_fmt_plug.c
+++ b/src/pkzip_fmt_plug.c
@@ -1435,12 +1435,21 @@ static int crypt_all(int *pcount, struct db_salt *_salt)
                        }
                        while(--k);

+//printf ("C=%x salt->chk_bytes=%X e=%x e2=%X b=%X\n", C, salt->chk_bytes, e, e2, b);
                        /* if the hash is a 2 byte checksum type, then check that value first */
                        /* There is no reason to continue if this byte does not check out.  */
-                       if (salt->chk_bytes == 2 && C != (e&0xFF) && C != (e2&0xFF))
-                               goto Failed_Bailout;
+                       if (salt->chk_bytes == 2 && C != (e&0xFF) && C != (e2&0xFF)) {
+                               /* found a non-ascii file named zip file where the 2 byte checksum failed
+                                  but where crc/timestamp checksum worked.  So before we bail, we do a
+                                  quick check to see if the 1 byte check would pass.  Only bail if that
+                                  checksum would also fail */
+                               C = PKZ_MULT(*b, key2);
+                               if (C != (e>>8) && C != (e2>>8))
+                                       goto Failed_Bailout;
+                       }

                        C = PKZ_MULT(*b++,key2);
+//printf ("C=%X  e=%X  e2=%X\n\n", C, e, e2);
 #if 1
                        // https://github.com/magnumripper/JohnTheRipper/issues/467
                        // Fixed, JimF.  Added checksum test for crc32 and timestamp.

```

What this does is on the 2 byte checksum fail, it also tests the 1 byte checksum fail. It ONLY bails if both fail.

**Comment by magnumripper** [comment]
I believe the file name being non-ASCII is 100% irrelevant since you can leave it out from the hash line (it's only stored in other fields, eg. login field). The actual 'ciphertext' is only file *content*.

Unless I'm mistaken, that fix of yours isn't any different than merely commenting out the first test (the second test comes right after it anyway). Anyway I'm not too worried about false positives, full CRC-32 is checked later. Dropping first test hits performance though, as it is/was an early reject.

**Comment by magnumripper** [comment]
> Dropping first test hits performance though, as it is/was an early reject.

Best would be if we find "the" exact condition(s) where we need to skip that test, while we keep doing it in other conditions.

**Comment by magnumripper** [comment]
Just thinking out loud:

> ```
> $pkzip2$1*2*2*0*3784*420d*856d3284*0*64*8*3784*856d*85a1*(...DA...)
> ```
> 
> Parsing the above:
> 
> * B Number of valid bytes in checksum: 2

Apparently only one byte is valid... so how does zip2john come to this conclusion? ~~I'm pretty sure~~ (now confirmed) If zip2john would output `$pkzip2$1*1*2*0*3784*(...)` instead, we would crack the file with no changes to pkzip format.

**Comment by magnumripper** [comment]
Here's what might be an important tidbit of info: The archive was created with "ezip under macOS". Some `efh` debug output from zip2john indicates ezip is using what I believe to be [libarchive](https://github.com/libarchive/libarchive) and maybe, just maybe, that lib is where the actual bug/feature hides. Don't know yet but will investigate more. Right now I'm hoping for a certain very odd "efh" (such as `0x6c78`) to hint us that the "2-byte checksum" must be treated as a single byte one.

**Comment by magnumripper** [comment]
A complicating matter is that ezip doesn't seem to be open source.

https://www.macupdate.com/app/mac/61060/ezip

This means I'll need to be running virtual machines and such ninja magic third millenia shite 😢. We hates that.

**Comment by jfoug** [comment]
;Here is what I found out about the efh:   I created my own zip and tested against the zip included:

```
$ bleed-64/run/zip2john *.zip > xx.in
ver 2.0 efh 5455 EFH_ID = 5455
efh 7875 EFH_ID = 7875
efh 6c78 EFH_ID = 6c78
123456-desk.zip/الصين بلد قوي.docx PKZIP Encr: 2b chk, TS_chk, cmplen=14212, decmplen=16909, crc=856D3284 type=8
ver 2.0 efh 5455 EFH_ID = 5455
efh 7875 EFH_ID = 7875
xx.zip/zip.in PKZIP Encr: 2b chk, TS_chk, cmplen=16708, decmplen=28601, crc=5605E502 type=8
```

 (I also changed that efh debugging for better reading)   The first is the problem.  The 2nd is a working info zip made (cygwin64).  What we may have to do is to set 

```c
zfp->check_bytes = 0; 
```

right before the efh checking switch.  That way, only the last extended header is checked for known value.  

It looks like the code spins through all the efh headers, and when it finds one of the magic ones (known infozip type unix builds), it simply assumes that it is 2 byte checksum and uses it.   But using the last only does not mean that it is 100% correct either. There may be zip which are 2 byte checksum (faster john processing), which after this change will fall back to 1 byte checksum logic (testing more often than needed).  I do not at this time know.

**Comment by jfoug** [comment]
Here is the efh checking logic:

```c
static int process_legacy(zip_file *zfp, zip_ptr *p)
{
	FILE *fp = zfp->fp;
	fprintf(stderr, "ver %d.%d ", p->version / 10, p->version % 10);

	if ( (p->flags & FLAG_ENCRYPTED) &&
	     (p->version == 10 || p->version == 20 || p->version == 45)) {
		uint16_t extra_len_used = 0;

		while (extra_len_used < p->extrafield_length) {
			uint16_t efh_id = fget16LE(fp);
			uint16_t efh_datasize = fget16LE(fp);

			fprintf(stderr, "efh %04x ", efh_id);

			if (efh_id == 0x0001) {
				handle_zip64_ef(fp, p, efh_datasize, 1);
				extra_len_used += efh_datasize;
				efh_datasize = 0;
			}
			xfseek(fp, efh_datasize, SEEK_CUR);

			extra_len_used += 4 + efh_datasize;
fprintf (stderr, "EFH_ID = %x\n", efh_id);
			if (efh_id == 0x07c8 ||  // Info-ZIP Macintosh (old, J. Lee)
				efh_id == 0x334d ||  // Info-ZIP Macintosh (new, D. Haase's 'Mac3' field)
				efh_id == 0x4d49 ||  // Info-ZIP OpenVMS (obsolete)
				efh_id == 0x5855 ||  // Info-ZIP UNIX (original; also OS/2, NT, etc.)
				efh_id == 0x6375 ||  // Info-ZIP UTF-8 comment field
				efh_id == 0x7075 ||  // Info-ZIP UTF-8 name field
				efh_id == 0x7855 ||  // Info-ZIP UNIX (16-bit UID/GID info)
				efh_id == 0x7875)    // Info-ZIP UNIX 3rd generation (generic UID/GID, ...)

				// 7zip ALSO is 2 byte checksum, but I have no way to find them.  NOTE, it is 2 bytes of CRC, not timestamp like InfoZip.
				// OLD winzip (I think 8.01 or before), is also supposed to be 2 byte.
				// old v1 pkzip (the DOS builds) are 2 byte checksums.
			{
				zfp->unix_made = 1;
				zfp->check_bytes = 2;
				zfp->check_in_crc = 0;
			}
		}
```

**Comment by jfoug** [comment]
I am not 100% sure how to work around this issue, since I do not fully remember how these enhanced fields are built (or ordered).  In the problem zip, there are 3 of them : 5455, 7875 and 6c78   On the one I made there is 5455 and 7875

Both 5455 and 6c78 are not in the list of signatures we are looking for (from the switch statement).  Both zips have the signature for Info-Zip 3rd gen in them.  But the one with the 6c78 only has the 1 byte checksum.  .....   hmm.

**Comment by magnumripper** [comment]
libarchive is on GitHub, I had the idea to look at its code. Haven't had time yet. I was hoping just maybe we could use 0x6c78 as a "reverse trigger" which will reset to 1-byte check.

I thought the order of these fields weren't important but I really have no idea.

**Comment by magnumripper** [comment]
Another thing that just hit me: Aren't normal zipinfo/unzip tools expected to complain about a 2-byte checksum error? They don't seem to. So perhaps we should look at their code paths and see how come *they* think all is fine...

**Comment by magnumripper** [comment]
So I installed the eZip mac app and created a few archives. All of them got `efh 5455 efh 7875 efh 6c78` and none of them cracks unless I replace `$pkzip2$2*1*` with `$pkzip2$1*1*`.

**Comment by magnumripper** [comment]
Here's a small one: [sboxes.zip](https://github.com/openwall/john/files/5097059/sboxes.zip)

**Comment by magnumripper** [comment]
```
$ zipinfo -v sboxes.zip 
Archive:  sboxes.zip
There is no zipfile comment.

End-of-central-directory record:
-------------------------------

  Zip archive file size:                       255 (00000000000000FFh)
  Actual end-cent-dir record offset:           233 (00000000000000E9h)
  Expected end-cent-dir record offset:         233 (00000000000000E9h)
  (based on the length of the central directory and its expected offset)

  This zipfile constitutes the sole disk of a single-part archive; its
  central directory contains 1 entry.
  The central directory is 82 (0000000000000052h) bytes long,
  and its (expected) offset in bytes from the beginning of the zipfile
  is 151 (0000000000000097h).


Central directory entry #1:
---------------------------

  sboxes.c

  offset of local header from start of archive:   0
                                                  (0000000000000000h) bytes
  file system or operating system of origin:      Unix
  version of encoding software:                   2.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   2.0
  compression method:                             deflated
  compression sub-type (deflation):               normal
  file security status:                           encrypted
  extended local header:                          yes
  file last modified on (DOS date/time):          2019 May 14 19:45:46
  file last modified on (UT extra field modtime): 2019 May 14 19:45:46 local
  file last modified on (UT extra field modtime): 2019 May 14 17:45:46 UTC
  32-bit CRC value (hex):                         53145f96
  compressed size:                                56 bytes
  uncompressed size:                              47 bytes
  length of filename:                             8 characters
  length of extra field:                          28 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  Unix file attributes (100644 octal):            -rw-r--r--
  MS-DOS file attributes (00 hex):                none

  The central-directory extra field contains:
  - A subfield with ID 0x5455 (universal time) and 9 data bytes.
    The local extra field has UTC/GMT modification/creation times.
  - A subfield with ID 0x7875 (Unix UID/GID (any size)) and 11 data bytes:
    01 04 00 00 00 00 04 00 00 00 00.

  There is no file comment.
```
Note that `zipinfo` doesn't mention the 0x6c78 subfield here. Perhaps because it doesn't know what it is, but it's strange it doesn't mention it at all.

**Comment by magnumripper** [comment]
```
$ zipdetails ~/Desktop/sboxes.zip 

0000 LOCAL HEADER #1       04034B50
0004 Extract Zip Spec      14 '2.0'
0005 Extract OS            00 'MS-DOS'
0006 General Purpose Flag  0009
     [Bit  0]              1 'Encryption'
     [Bits 1-2]            1 'Maximum Compression'
     [Bit  3]              1 'Streamed'
0008 Compression Method    0008 'Deflated'
000A Last Mod Time         4EAE9DB7 'Tue May 14 19:45:46 2019'
000E CRC                   00000000
0012 Compressed Length     00000000
0016 Uncompressed Length   0000002F
001A Filename Length       0008
001C Extra Length          0029
001E Filename              'sboxes.c'
0026 Extra ID #0001        5455 'UT: Extended Timestamp'
0028   Length              0009
002A   Flags               '05 mod change'
002B   Mod Time            5CDAFECA 'Tue May 14 19:45:46 2019'
002F   Change Time         5F3D32FD 'Wed Aug 19 16:11:09 2020'
0033 Extra ID #0002        7875 'ux: Unix Extra Type 3'
0035   Length              000B
0037   Version             01
0038   UID Size            04
0039   UID                 00000000
003D   GID Size            04
003E   GID                 00000000
0042 Extra ID #0003        6C78 'xl: '
0044   Length              0009
0046   Extra Payload       07 14 03 00 00 00 00 A4 81
004F PAYLOAD               .~Q...YZU..Q`..nJ_u5F........2.../M.....
                           i..B.5...Goe.@P.

0087 STREAMING DATA HEADER 08074B50
008B CRC                   53145F96
008F Compressed Length     00000038
0093 Uncompressed Length   0000002F

0097 CENTRAL HEADER #1     02014B50
009B Created Zip Spec      14 '2.0'
009C Created OS            03 'Unix'
009D Extract Zip Spec      14 '2.0'
009E Extract OS            00 'MS-DOS'
009F General Purpose Flag  0009
     [Bit  0]              1 'Encryption'
     [Bits 1-2]            1 'Maximum Compression'
     [Bit  3]              1 'Streamed'
00A1 Compression Method    0008 'Deflated'
00A3 Last Mod Time         4EAE9DB7 'Tue May 14 19:45:46 2019'
00A7 CRC                   53145F96
00AB Compressed Length     00000038
00AF Uncompressed Length   0000002F
00B3 Filename Length       0008
00B5 Extra Length          001C
00B7 Comment Length        0000
00B9 Disk Start            0000
00BB Int File Attributes   0000
     [Bit 0]               0 'Binary Data'
00BD Ext File Attributes   81A40000
00C1 Local Header Offset   00000000
00C5 Filename              'sboxes.c'
00CD Extra ID #0001        5455 'UT: Extended Timestamp'
00CF   Length              0009
00D1   Flags               '05 mod change'
00D2   Mod Time            5CDAFECA 'Tue May 14 19:45:46 2019'
00D6   Change Time         5F3D32FD 'Wed Aug 19 16:11:09 2020'
00DA Extra ID #0002        7875 'ux: Unix Extra Type 3'
00DC   Length              000B
00DE   Version             01
00DF   UID Size            04
00E0   UID                 00000000
00E4   GID Size            04
00E5   GID                 00000000

00E9 END CENTRAL HEADER    06054B50
00ED Number of this disk   0000
00EF Central Dir Disk no   0000
00F1 Entries in this disk  0001
00F3 Total Entries         0001
00F5 Size of Central Dir   00000052
00F9 Offset to Central Dir 00000097
00FD Comment Length        0000
Done
```
However, `zipdetails` does list the 0x6c78. It's only present in the "local header", not the "central header". Not sure what that means or could mean.

**Comment by magnumripper** [comment]
I just tried out hashcat. Obviously it too fails to crack my test archives unless I replace `$pkzip2$2*1*` with `$pkzip2$1*1*`.

I'm now convinced this is an issue with zip2john and not the format. Either it's a bug in zip2john, or it's a bug in eZip and/or libarchive that we can probably work around by detecting 0x6c78 and force 1-byte CS for them.

I should have reviewed unzip sources already though. Will do now, but I expect it just skips to full 32-bit CRC since it doesn't have any need for early rejection...

**Comment by magnumripper** [comment]
> I should have reviewed unzip sources already though. Will do now, but I expect it just skips to full 32-bit CRC since it doesn't have any need for early rejection...

That is the case as far as I can see. I reviewed [this code](https://github.com/madler/zlib/blob/master/contrib/minizip/unzip.c).

**Comment by jfoug** [comment]
The zipinfo/unix also must deal with 1 byte checksum. For all we know, the checksum is never even used.  I am not sure if your 'expected to complain' is true or not.  I will see if I can hexedit and bung one up (just the checksum), and report back.

**Comment by magnumripper** [comment]
I whipped up #4302 as a possible quick-and-dirty solution. Unless we find something better

**Comment by magnumripper** [comment]
Just remembered I have another small data point to add: Over the years I've collected a couple handful of pkzips that I could never crack. Just for checking, I ran them all with the 2nd CS byte check commented out over the last days, but none of them cracked soon. Given archives typically have very weak passwords I think this too indicates the problem is specific to either eZip or libarchive (which would mean #4302 is Good Enough[tm] at least for now).

**Comment by solardiz** [comment]
Is there a chance to workaround this in the pkzip format rather than in zip2john? I guess EFH is not available in the "hash", so no?

**Comment by magnumripper** [comment]
Right, we can't. This fix to zip2john is needed for hashcat as well

**Comment by magnumripper** [comment]
New very similar issue (with samples): #4541
