### ISSUE TITLE
In slow debugging builds, have mem_alloc() fill memory with non-zeroes

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4310]
For example, I am now testing an ASan build with this added:

```diff
@@ -78,6 +78,8 @@ void *mem_alloc(size_t size)
                error();
        }
 
+       memset(res, 0x55, size);
+
        return res;
```

but we'll need to make it conditional on some build-time or run-time configuration option.

**Comment by solardiz** [comment]
Apparently, the lack of this prevented us from discovering #4308 sooner (such as before the previous release).

**Comment by solardiz** [comment]
In `bench.c`, we have this:

```c
#if defined(WITH_ASAN) || defined(WITH_UBSAN) || defined(DEBUG)
        if (benchmark_time)
                puts("NOTE: This is a debug build, speed will be lower than normal");
#endif
```

Maybe we should use a similar check, or a subset of it, to enable the memory non-zeroing.

Where do these macros get defined, though? I've confirmed that the above message is in fact printed in my `--enable-asan` build. I didn't check the rest.

**Comment by ghost** [comment]
> Where do these macros get defined, though?

ASAN in misc.h. UBSAN in Makefile (-DWITH_...).
