### ISSUE TITLE
New mode issue

### ISSUE THREAD

**Issue by e2002e** [openwall/john#4323]
Hello, I'm implementing my method in john, yet I'm having two big issues.  
1 I can't get the restore to work  
2 The fork mode is giving as much duplicates as threads  

I took the subset file as a basis but cannot understand the way options.node_count is managed.  
Anything regarding the algorithm is found in my repo named "zhou" .  
Can you have a look at my fork of john ?  
You'll just need to have the Makefile compile rain.o with the same specifications as subsets (I'm letting it manage the character set).

**Comment by ghost** [comment]
@solardiz, what are the rules for creating an issue?
****

@e2002e, your question is a suitable discussion for ML john-dev (developers stuff). It is not a real JtR issue. 
Let's hear from Solar what kind of discussion will take place on GitHub.

**Comment by e2002e** [comment]
I have little knowledge of github, if I could have email someone I would
rather have done so.
Yet I feel like this needs to be sorted out.
I'm relying on you to inspect this files to guide me through completion so
that I can do a pull request.

Le 28 août 2020 1:09 AM, "Claudio André" <notifications@github.com> a
écrit :

@solardiz <https://github.com/solardiz>, what are the rules for creating an
issue?
------------------------------

@e2002e <https://github.com/e2002e>, your question is a suitable discussion
for ML john-dev (developers stuff). It is not a real JtR issue.
Let's hear from Solar what kind of discussion will take place on GitHub.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openwall/john/issues/4323#issuecomment-682235909>, or
unsubscribe

**Comment by magnumripper** [comment]
Cool! Ignoring the github-or-not issue for now, I'll have a look at your repo.

**Comment by magnumripper** [comment]
I think this will be a long discussion. As Claudio suggested you should probably join the john-dev mailing list at https://www.openwall.com/lists/john-dev/ and ask more specific questions.

**Comment by solardiz** [comment]
This isn't really an issue for us, and not something we care to keep track of. Closing.

**Comment by e2002e** [comment]
Ok no problems, I ended up using a displacement of the index so that the words are riddled with moving characters, adding a rotation on top is making the thing interesting.
I'll not delete my fork.

On September 22, 2020 3:41:20 PM UTC, Solar Designer <notifications@github.com> wrote:
>This isn't really an issue for us, and not something we care to keep track of. Closing.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openwall/john/issues/4323#issuecomment-696803738
-- 
Sent from my Android device with Librem Mail. Please excuse my brevity.
