### ISSUE TITLE
[Local:Disabled:Formats] not working

### ISSUE THREAD

**Issue by ghost** [openwall/john#4330]
Since a couple of days [Local:Disabled:Formats] no longer works. 74e896be8d7dd59c744eda3c6a6bc22ab9d29e15 works.

***
CI caught it.

**Comment by magnumripper** [comment]
Works for me as designed:

- Adding a format to `[Disabled:Formats]` in `run/john.conf` works.
- Adding `[Disabled:Formats]` to `run/john-local.conf` and putting a format there also works, but silently discards anything in that section in main `john.conf`
- Adding a format to `[Local:Disabled:Formats]` in `run/john-local.conf` works, and does not discard the main file's section's items (both sections' items are used).

Action tested was `./john -test=0 -form:rar*` and disabling the OpenCL versions of them. What exactly did you do and what happened?

**Comment by ghost** [comment]
Well, I used create a `run/john-local.conf` to "mute" (disable) formats used by TS. I think the behavior has changed since dba12ffd2187a7784fa6c19f849866925153cb36.

Is there a new way to achieve the same behavior?

**Comment by magnumripper** [comment]
So you actually need it to not load even with tagged hashes? I didn't think it'd be a regression IRL. I'm not sure how to handle it - any idea @jfoug?

**Comment by ghost** [comment]
>  I didn't think it'd be a regression IRL

Well, there is no way to disable a format (back to the discussion on the words used).
****

I can remove (before build) all problematic formats. It will be a reasonable solution.

**Comment by magnumripper** [comment]
OK but what is the exact chain of the problem now? What particular difference after dba12ff is it that bites us?

**Comment by ghost** [comment]
I need to disable a format. Disable, so it is not listed and not used by TS (my issue is TS in CI).

I guess formats in `[disabled]` section were not listed by `--list=formats`. But, now they are.

**Comment by magnumripper** [comment]
Confirmed: `--list=formats` now lists "disabled" formats - it didn't before dba12ff.

For dynamic formats we have `--list=subformats` which did not change (it always listed the disabled formats as well).

**Comment by ghost** [comment]
> I can remove (before build) all problematic formats. It will be a reasonable solution.

Ok, I did that. But, I still need to remove `bcrypt`. Is there a clever way to disable bcrypt?

**Comment by magnumripper** [comment]
After #4384 and recent commits to TS, you can do things like `./jtrts.pl -internal enabled` (the `enabled` will end up as `--format=enabled`). You can also skip disabling it in the config and instead `./jtrts.pl -internal -- -bcrypt`

**Comment by ghost** [comment]
I'll close the issue as soon as I test new code.
