### ISSUE TITLE
cl_device_topology_amd not defined in opencl_common.c

### ISSUE THREAD

**Issue by katodev** [openwall/john#4331]
Build failed because cl_device_topology_amd not defined in opencl_common.c
It seems one required latetest devel package in openSUSE Tumbleweed has already defined CL_DEVICE_TOPOLOGY_AMD with a value.
If this happend the type unison can't define cl_device_topology_amd in opencl_common.h

I use this patch to fix it.

```
--- src/opencl_common.h.orig	2020-06-09 21:39:09.000000000 +0200
+++ src/opencl_common.h	2020-08-31 22:08:40.878498873 +0200
@@ -81,6 +81,8 @@
 
 #ifndef CL_DEVICE_TOPOLOGY_AMD
 #define CL_DEVICE_TOPOLOGY_AMD                      0x4037
+#define CL_DEVICE_TOPOLOGY_TYPE_PCIE_AMD            1
+#endif
 typedef union {
 	struct {
 		cl_uint type;
@@ -95,9 +97,6 @@ typedef union {
 	} pcie;
 } cl_device_topology_amd;
 
-#define CL_DEVICE_TOPOLOGY_TYPE_PCIE_AMD            1
-#endif
-
 #ifndef CL_DEVICE_BOARD_NAME_AMD
 #define CL_DEVICE_BOARD_NAME_AMD                    0x4038
 #endif

```

**Comment by magnumripper** [comment]
Weird. If they defined it they should also have the typedef (I think). Can you please try to track down who defines it, where and to what value (if any)?

I'm pretty sure your patch would break on some other platforms so I'm not sure what to do. Possibly we could add a `#define cl_device_topology_amd jtr_cl_device_topology_amd` right before we do the typedef.

**Comment by magnumripper** [comment]
Is `CL_DEVICE_TOPOLOGY_TYPE_PCIE_AMD` also defined already? If not we can probably use that.

BTW we might get away with a redundant typedef as long as it matches any that was already made before.

**Comment by magnumripper** [comment]
> Is `CL_DEVICE_TOPOLOGY_TYPE_PCIE_AMD` also defined already?

If it isn't, this is a better/safer patch:
```diff
diff --git a/src/opencl_common.h b/src/opencl_common.h
index 50428ce97..264825d48 100644
--- a/src/opencl_common.h
+++ b/src/opencl_common.h
@@ -81,6 +81,9 @@
 
 #ifndef CL_DEVICE_TOPOLOGY_AMD
 #define CL_DEVICE_TOPOLOGY_AMD                      0x4037
+#endif
+
+#ifndef CL_DEVICE_TOPOLOGY_TYPE_PCIE_AMD
 typedef union {
 	struct {
 		cl_uint type;
```

**Comment by magnumripper** [comment]
Just an observation: Hashcat seems to just define and typedef without any `#ifndef`. Normally any "clashes" will have the exact same defines/typedefs and I think even the noisiest of compilers ignore that.

**Comment by magnumripper** [comment]
After some more consideration and testing I'm pretty convinced the latter fix (PR in #4332) will be the best solution for now.

**Comment by katodev** [comment]
I found the definition in /usr/include/CL/cl_ext.h with the same value and CL_DEVICE_TOPOLOGY_TYPE_PCIE_AMD isn't define.
Used source are libOpenCL1-2.2.12 and opencl-headers-2.2+git.20200512 with gcc10-10.2.1+git583

I hope this information confirms your decision for this solution.

**Comment by magnumripper** [comment]
Yes, thank you!
