### ISSUE TITLE
Rework usage / --help output

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4340]
I think our hiding of plenty of useful options under `--list=hidden-options` is too obscure. I think we should unhide them all, printing the full options list on `--help`. We're being inconsistent with other projects, including hashcat, by not printing the full options list even on explicit `--help`. This can be confusing to new users, who wouldn't realize there are more options nor how to see those.

If we don't want to flood the screen with all the options when `john` is invoked with no options (not even with `--help`), then we should limit its default output to just a few lines like the current first 5 lines of output (which are: program name and build info, copyright, homepage, empty line, general command-line syntax) plus the suggestion to use `--help`, so maybe 6 or 7 lines total.

Yes, this will make jumbo not print even the option names that core does by default, but so what. Core's full options list fits on screen, and jumbo's doesn't (by far), which justifies the difference. We have a crucial and more confusing difference now: core's options list printed by default is complete, and jumbo's currently isn't - so let's avoid that one.

Related/historical: #1046

**Comment by wsandin** [comment]
Hi, I just read through the related issue #1046, and had a look at the code for a bit better understanding.
I'd be happy to take on this issue.

**Comment by solardiz** [comment]
Thanks @wsandin. Let's also hear from @magnumripper and other key contributors.

This change will probably also need to be reflected in bash completions, see #129 and #319. @frank-dittrich might comment on that.

**Comment by magnumripper** [comment]
I'm fine with the general idea.

I've been considering helper print functions that tries to know the screen width (with fallback to 80 and perhaps never using wider than *n* where *n* could be something like 120 or 240 or even a john.conf option). They would wrap lines at whitespace boundary. One feature would be optional automatic indentation for continuation, like this (examples with miniscule width):

Full width
```                                                 
Lorem ipsum dolor sit amet, consectetur adipisicing
elit, sed do eiusmod tempor incididunt ut labore et
dolore magna aliqua.
```

Indentation for continuation
```
Lorem ipsum: dolor sit amet, consectetur adipisicing
             elit, sed do eiusmod tempor incididunt
             ut labore et dolore magna aliqua.
```

It could be rewarding to write such helper first if we want it. I also considered things like optional colors and "print to screen and to log" with a single call, see #3511.

**Comment by solardiz** [comment]
I think we should avoid scope creep and mixing of different kinds of changes in one PR, or we'd end up with a PR that's hard to agree on and merge (and if things are mixed on one commit, then also no easy way to revert one kind of changes without reverting all if we ever choose to). While introducing helper functions could be nice, I think this should be a separate and perhaps a later change from what I described in my first comment here, not part of the same PR.

**Comment by wsandin** [comment]
While I've already done some research and testing on how some of these helpers (i.e. detecting terminal width) could be implemented, I appreciate you protecting the scope for this issue.

In that case I'll complete this issue as defined by you in the initial post, and ensure that this gets reflected in any shell completion. After that I'd be happy to take on a separate issue to implement such a helper function as kindly suggested by @magnumripper
