### ISSUE TITLE
zip2john: spurious "not encrypted" message on WinZip archive

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4347]
We need to look into the test case is provided in https://www.openwall.com/lists/john-users/2020/09/17/5 and see if there's anything for us to fix (code or documentation), and if so do that.

**Comment by magnumripper** [comment]
#3985 and its fix 28224f39 should be related

**Comment by ghost** [comment]
Have you tested this? Using my snap, I realized that the message is displayed only for Jumbo 1. An important detail is that the support for the zip format was greatly improved after the release.

A Jumbo 2, Reloaded, to fix Office bugs, OpenCL leaks, improve Zip, etc, seems like a good idea to me.

**Comment by solardiz** [comment]
Testing on the provided `Test.zip`, I confirm that this problem was present around the time of 1.9.0-jumbo-1, and is now gone.

> A Jumbo 2, Reloaded, to fix Office bugs, OpenCL leaks, improve Zip, etc, seems like a good idea to me.

I agree we should make a release after having fixed stuff and before we break anything again. I'd appreciate help on the "Definitely 1.9.0-jumbo-2 material" issues.
