### ISSUE TITLE
Add support for 7-Zip files without header encryption,plz!!

### ISSUE THREAD

**Issue by No-Github** [openwall/john#4360]
Add support for 7-Zip files without header encryption,plz!!

https://github.com/openwall/john/blob/bleeding-jumbo/run/7z2john.pl

**Comment by magnumripper** [comment]
7z2john.pl is actually a renamed [7z2hashcat.pl](https://github.com/philsmd/7z2hashcat), please open an issue there instead.

**Comment by magnumripper** [comment]
Having said that, I'm not sure this is a valid request anyway. As far as I know "without header encryption" is the 7z default and already supported.
```
       -mhe=on|off
              7z format only : enables or disables archive header encryption (Default : off)
```

**Comment by magnumripper** [comment]
Just tested: We already handle files with or without header encryption, both in 7z2john and in john.

**Comment by solardiz** [comment]
@No-Github Do you agree with @magnumripper that there's nothing for us to do on your request, and we should simply close it? Please let us know either way.

**Comment by No-Github** [comment]
Thanks, I solved the problem using the method you provided.😊👍❤
![Snipaste_2020-09-24_21-10-48](https://user-images.githubusercontent.com/18167071/94149423-75a71100-feaa-11ea-904e-11598d74c1d0.png)
