### ISSUE TITLE
Add --format=LIST feature

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4366]
From https://github.com/openwall/john/pull/4354#issuecomment-698595869
> I see things like notes-opencl segfaulting on an all-formats test (right after LM-opencl, who would have thought) but not on its own (we've seen that before). I'm actually considering adding option `--format-list=LIST` so I could test with `--format=lm-opencl,notes-opencl`. I'd use the existing list parsing of course, like we do with several other recent-ish options like `--single-seed=WORD[,WORD...]`

Some thoughts right now:
- Perhaps we can use `--format=[FORMAT|WILDCARD|CLASS|LIST]` (with LIST being the only new) instead of a separate `--format-list=LIST`.
- The existing list parsing would (IIRC) cut at the `-` in `foobar-opencl`, which isn't great.
- ~This is not really useful for anything but testing. Perhaps we don't even want it always active? OTOH I can't see it really be in the way or a lot of code.~

**Comment by solardiz** [comment]
> This is not really useful for anything but testing.

It's also useful for running specific sets of benchmarks - not testing JtR for proper operation, but getting benchmark results for specific sets of formats one is interested in without having to run multiple commands. So I want this always compiled in, and as a feature available to end-users.

**Comment by magnumripper** [comment]
With very little coding I've got this:
```
$ ../run/john -test=0 -format:raw-md4,raw-sha1,raw-md5
Testing: Raw-MD4 [MD4 256/256 AVX2 8x3]... PASS
Testing: Raw-MD5 [MD5 256/256 AVX2 8x3]... PASS
Testing: Raw-SHA1 [SHA1 256/256 AVX2 8x]... PASS
All 3 formats passed self-tests!
```
Note that they still come in format struct order, not the order I gave in the `--format` option.

I think we do need them in the **given** order but that'll be less trivial (or at least a more intrusive change). I'll sit on this for a while, maybe it can still be trivial.

**Comment by magnumripper** [comment]
Talking to the duck here, the above was from hacking `john_register_all()` a little. I could of course wait until after that, when we have a complete `fmt_list`, and only then build a **new** `fmt_list` with the content (and order) I like from the original one. Should be trivial.

**Comment by solardiz** [comment]
I suspect next we'll have user confusion about `-format:raw-md4,raw-sha1,raw-md5` not working to actually crack hashes of those types simultaneously. We need to display a clear error message when that is attempted.

**Comment by magnumripper** [comment]
Good thinking, although I think we should only warn, not abort. Actually we do warn as-is:
```
$ ../run/john -form=zip,pkzip all_tests.in -mask:magnum
Warning: only loading hashes of type "PKZIP", but also saw type "ZIP"
Use the "--format=ZIP" option to force loading hashes of that type instead
Using default input encoding: UTF-8
Loaded 9 password hashes with 9 different salts (PKZIP [32/64])
(...)
```
At first I was surprised that pkzip hashes were loaded (while zip was listed first) but that's dictated by which of them is seen first in the input file!

I added checks for other things:
```
$ ./john --list=formats --format=*office
Office, oldoffice

$ ./john --list=formats --format=oldoffice,office
oldoffice, Office

$ ./john -test=0 -form=raw-md4,@md5
Error: Format groups such as '@md5' are not supported in format lists

$ ./john -form=raw-md5*,raw-md4* --list=formats
Error: Format wildcards such as 'raw-md5*' are not supported in format lists

$ ./john -test=0 -form=raw-md4,#ipmi
Error: Format wildcards such as '#ipmi' are not supported in format lists

$ ./john -test=0 -form=raw-md4,dynamic
Error: Format classes such as 'dynamic' are not supported in format lists

$ ./john -test=0 -form=raw-md4,raw-mi6  
Error: 'raw-mi6' not found among formats

$ ./john --test=0 --format=crypt,md5crypt,descrypt
Will run 16 OpenMP threads
Testing: crypt, generic crypt(3) [?/64]... (16xOMP) PASS
Testing: md5crypt, crypt(3) $1$ (and variants) [MD5 256/256 AVX2 8x3]... (16xOMP) PASS
Testing: descrypt, traditional crypt(3) [DES 256/256 AVX2]... (16xOMP) PASS
All 3 formats passed self-tests!
```
The last example not only singles out those three formats but also reverses the "natural" order of them.

**Comment by solardiz** [comment]
Here's a new idea: maybe we can extend this functionality to be able to exclude formats? For example, `--test --format=opencl,-krb5pa-md5-opencl` would let my all-OpenCL-formats test yesterday proceed beyond the segfault in `krb5pa-md5-opencl`.

**Comment by magnumripper** [comment]
That's a good idea. I've also considered supporting wildcard in lists but am not sure it's worth it.

Then
```
--format=raw-*,-*opencl
```
Would match any formats starting with `raw-` but not ending with `-opencl`.

Edit: Classes would also need support in lists, for the exclusion in your example (well or it could be written with wildcard but some other classes can't).

**Comment by solardiz** [comment]
@claudioandre-br was asking just recently how to disable the builtin bcrypt format, presumably for more than just `--test` (which can be done from `john.conf`). I wonder why, but I guess us supporting `--format=-bcrypt` would be a solution for him.

**Comment by ghost** [comment]
> which can be done from john.conf

I need to disable the format, which is no longer possible. The reason is that bcrypt fails in TS.

**Comment by solardiz** [comment]
> bcrypt fails in TS.

Why does it? Can that be fixed? Should we open an issue against TS?

And, would support for `--format=-bcrypt` help you?

**Comment by magnumripper** [comment]
The problem is that disabled formats are now shown in format list - and TS uses that list.

**Comment by solardiz** [comment]
This doesn't explain why bcrypt fails in TS.

Anyway, would adding `--format=-bcrypt` help? Perhaps then the format wouldn't even be shown in format list?

**Comment by magnumripper** [comment]
The TS "-internal" hack basically works like this (originally made for testing formats not specifically implemented in TS):
1. List format's test vectors, to a hash file and a wordlist (I think wordlist is mixed with other random words)
2. Try to crack the hash file using the wordlist
...and then IIRC...
3. Reverse the pot file hash:clear into another set of hashfile and wordlist
4. Try to crack that set too in a similar way

After that, it tries to draw conclusions from stdout and the pot file(s). IIRC, the problem it has with bcrypt is related to the translation from `$2x' and '$2y` to `$2a` (or whas it the other way round) - it's simply a shortcoming in TS. It also has problems with formats that have several versions of basically the same test vector, but listed in two or more different formats. It will think "hey we had 8 test vectors but only cracked 7".

Well, something like that.

**Comment by solardiz** [comment]
> IIRC, the problem it has with bcrypt is related to the translation from `$2x' and '$2y` to `$2a` (or whas it the other way round)

There's no translation. We simply support all of these.

> TS [...] also has problems with formats that have several versions of basically the same test vector, but listed in two or more different formats. It will think "hey we had 8 test vectors but only cracked 7".

This is more likely relevant. Maybe TS should use `NoLoaderDupeCheck = Y` and the problem will go away? Claudio, can you see if this lets TS test bcrypt correctly?

**Comment by ghost** [comment]
From:
```
form=bcrypt                       guesses:   14 -show=  13 0:00:00:00 DONE : Expected count(s) (14)(-show14)  [!!!FAILED3!!!  ret_val=0]
.pot CHK:bcrypt                   guesses:   12 -show=  13 0:00:00:00 DONE : Expected count(s) (14)  [!!!FAILED4!!!   ret_val=0]  (12 val-pwd  0 inval-pwd)
```
To:
```
form=bcrypt                       guesses:   15 -show=  13 0:00:00:00 DONE : Expected count(s) (14)(-show14)  [!!!FAILED1!!!  ret_val=0]
.pot CHK:bcrypt                   guesses:   12 -show=  13 0:00:00:00 DONE : Expected count(s) (14)  [!!!FAILED4!!!   ret_val=0]  (12 val-pwd  0 inval-pwd)
```
