### ISSUE TITLE
New phpass formats' test vectors confuse test suite

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4369]
Claudio helped me realize that my recent hack to phpass formats' test vectors and `valid()` makes JtR exhibit inconsistent behavior externally, in a way that confuses our external test suite. We need to fix that.

https://github.com/openwall/john/commit/976ca28fe3e551f671e8c98353ce8a13482ee6ea#commitcomment-42736429

**Comment by ghost** [comment]
It can be confusing for real users (as I read it).

**Comment by solardiz** [comment]
I fixed this by a `strstr()` hack for now. Calling `valid()` would be another option, but would potentially affect other formats, so would require more testing.
