### ISSUE TITLE
Behavior changes after `--format=LIST`

### ISSUE THREAD

**Issue by ghost** [openwall/john#4391]
It used to be:
> -format=dynamic-all That type will test all dynamic, including any disabled dynamic formats

```
$ ../run/john | head -1
John the Ripper 1.9.0-jumbo-1+bleeding-91f5e35 2020-09-15 22:01:55 +0200 OMP debug [linux-gnu 64-bit x86_64 AVX AC]

```
```
$ ../run/john --test=0 --verbosity=2 --format=dynamic
[...]
All 475 formats passed self-tests! (OpenCL formats skipped)

```
```
$ ../run/john --test=0 --verbosity=2 --format=dynamic-all
[...]
All 475 formats passed self-tests! (OpenCL formats skipped)

```
Now:
```
$ ../run/john --test=0 --verbosity=2 --format=dynamic
[...]
All 159 formats passed self-tests!

```
```
$ ../run/john --test=0 --verbosity=2 --format=+dynamic,all
[...]
All 159 formats passed self-tests!
```

```
../run/john --test=0 --verbosity=2 --format=+dynamic,+all
All 159 formats passed self-tests!
```

Was that on purpose?
> Drop obsolete composite group dynamic-all. New syntax would be, for   example, +dynamic,all.

**Comment by magnumripper** [comment]
Yes, like the docs say all composite classes are gone, they were very inconsistent. TS was updated (for now) with only using "dynamic" but ideally it should detect John version and use "dynamic-all" or "+dynamic,all" as appropriate.

**Comment by magnumripper** [comment]
Oh but your examples indicate a bug. `+dynamic,all` really should be 475 formats

WTF that exact thing was one I tested repeatedly yesterday to ensure it ended up right. Doh!
