### ISSUE TITLE
libreoffice2john does not work with LibreOffice 7.* documents

### ISSUE THREAD

**Issue by Mi-Al** [openwall/john#4392]
### Steps to reproduce ###
Hello! I use the command to extract hash of ODF document:

`./libreoffice2john.py ./file.odt > odf.hash`

It returns the error:

> Traceback (most recent call last):
>   File "./bin/john-bleeding-jumbo/run/libreoffice2john.py", line 152, in <module>
>     process_file(sys.argv[k])
>   File "./bin/john-bleeding-jumbo/run/libreoffice2john.py", line 86, in process_file
>     salt = binascii.hexlify(base64.b64decode(salt)).decode("ascii")
> UnboundLocalError: local variable 'salt' referenced before assignment

Information:
**file.odt** – is Writer document, LibreOffice 7.*
**JtR** – is the last https://github.com/openwall/john/archive/bleeding-jumbo.zip version.

### System configuration ###
- `./john --list=build-info`.

> Version: 1.9.0-jumbo-1+bleeding-5b35db310d 2020-09-30 02:14:29 +0200
> Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
> SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
> CPU tests: AVX2
> $JOHN is ./
> Format interface version: 14
> Max. number of reported tunable costs: 4
> Rec file version: REC4
> Charset file version: CHR3
> CHARSET_MIN: 1 (0x01)
> CHARSET_MAX: 255 (0xff)
> CHARSET_LENGTH: 24
> SALT_HASH_SIZE: 1048576
> SINGLE_IDX_MAX: 2147483648
> SINGLE_BUF_MAX: 4294967295
> Effective limit: Number of salts vs. SingleMaxBufferSize
> Max. Markov mode level: 400
> Max. Markov mode password length: 30
> gcc version: 10.2.0
> GNU libc version: 2.32 (loaded: 2.32)
> OpenCL headers version: 2.2
> Crypto library: OpenSSL
> OpenSSL library version: 01010108f
> OpenSSL 1.1.1h  22 Sep 2020
> GMP library version: 6.2.0
> File locking: fcntl()
> fseek(): fseek
> ftell(): ftell
> fopen(): fopen
> memmem(): System's
> times(2) sysconf(_SC_CLK_TCK) is 100
> Using times(2) for timers, resolution 10 ms
> HR timer claimed resolution 1 ns, observed 173 ns
> Total physical host memory: 31966 MB
> Available physical host memory: 13779 MB

- `./john --list=opencl-devices`.

> Platform #0 name: Intel(R) OpenCL HD Graphics, version: OpenCL 2.1 
>     Device #0 (1) name:     Intel(R) Gen9 HD Graphics NEO
>     Device vendor:          Intel(R) Corporation
>     Device type:            GPU (LE)
>     Device version:         OpenCL 2.1 NEO 
>     Driver version:         1.0.0 
>     Native vector widths:   char 16, short 8, int 4, long 1
>     Preferred vector width: char 16, short 8, int 4, long 1
>     Global Memory:          25573 MB
>     Global Memory Cache:    512 KB
>     Local Memory:           64 KB (Local)
>     Constant Buffer size:   4095 MB
>     Max memory alloc. size: 4095 MB
>     Max clock (MHz):        1100
>     Profiling timer res.:   83 ns
>     Max Work Group Size:    256
>     Parallel compute cores: 24
>     Stream processors:      192  (24 x 8)
>     Speed index:            211200
> 
> Platform #1 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 11.1.70
>     Device #0 (2) name:     GeForce GTX 1050 Ti
>     Device vendor:          NVIDIA Corporation
>     Device type:            GPU (LE)
>     Device version:         OpenCL 1.2 CUDA
>     Driver version:         455.23.04 [recommended]
>     Native vector widths:   char 1, short 1, int 1, long 1
>     Preferred vector width: char 1, short 1, int 1, long 1
>     Global Memory:          4042 MB
>     Global Memory Cache:    288 KB
>     Local Memory:           48 KB (Local)
>     Constant Buffer size:   64 KB
>     Max memory alloc. size: 1010 MB
>     Max clock (MHz):        1620
>     Profiling timer res.:   1000 ns
>     Max Work Group Size:    1024
>     Parallel compute cores: 6
>     CUDA cores:             768  (6 x 128)
>     Speed index:            1244160
>     Warp size:              32
>     Max. GPRs/work-group:   65536
>     Compute capability:     6.1 (sm_61)
>     Kernel exec. timeout:   no
>     NVML id:                0
>     PCI device topology:    01:00.0
>     PCI lanes:              16/16
>     Temperature:            54°C
>     Utilization:            1%
> 
> Platform #2 name: Portable Computing Language, version: OpenCL 1.2 pocl 1.5, Release, LLVM 10.0.0, RELOC, SPIR, SLEEF, POCL_DEBUG
>     Device #0 (3) name:     pthread-Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
>     Device vendor:          GenuineIntel
>     Device type:            CPU (LE)
>     Device version:         OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-znver1
>     Driver version:         1.5 
>     Native vector widths:   char 16, short 16, int 8, long 4
>     Preferred vector width: char 16, short 16, int 8, long 4
>     Global Memory:          29918 MB
>     Global Memory Cache:    9 MB
>     Local Memory:           8 MB (Global)
>     Constant Buffer size:   8 MB
>     Max memory alloc. size: 8 GB
>     Max clock (MHz):        4100
>     Profiling timer res.:   1 ns
>     Max Work Group Size:    4096
>     Parallel compute cores: 12
>     Speed index:            196800

**Comment by solardiz** [comment]
@Mi-Al Does the script work for you on older LibreOffice documents, or is the actual issue possibly that the script doesn't work at all on your system (e.g., with your installed Python version or modules)?

Can you please attach to here a non-security-sensitive sample file with a known password, which we can use for testing? Thanks!

**Comment by ghost** [comment]
The script needs some love (unencrypt file).
```
$ python2 ~/bin/bleeding/run/libreoffice2john.py \[20201.1.JCR51.1I.INT.03395\ \(IBA-1\)\ 247194\]\ Notas.ods 
Traceback (most recent call last):
  File "/home/claudio/bin/bleeding/run/libreoffice2john.py", line 152, in <module>
    process_file(sys.argv[k])
  File "/home/claudio/bin/bleeding/run/libreoffice2john.py", line 54, in process_file
    element = elements[j]
IndexError: list index out of range
```
```
$ python3 ~/bin/bleeding/run/libreoffice2john.py \[20201.1.JCR51.1I.INT.03395\ \(IBA-1\)\ 247194\]\ Notas.ods 
Traceback (most recent call last):
  File "/home/claudio/bin/bleeding/run/libreoffice2john.py", line 152, in <module>
    process_file(sys.argv[k])
  File "/home/claudio/bin/bleeding/run/libreoffice2john.py", line 54, in process_file
    element = elements[j]
IndexError: list index out of range
```
Ok for 6.4
```
$ /snap/john-the-ripper/current/run/libreoffice2john.py Aula\ da\ Prova3.odt > hash1.txt
$ john hash1.txt --mask=claudi?a
Warning: detected hash type "ODF", but the string is also recognized as "ODF-opencl"
Use the "--format=ODF-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (ODF, OpenDocument Star/Libre/OpenOffice [PBKDF2-SHA1 256/256 AVX2 8x BF/AES])
Cost 1 (iteration count) is 100000 for all loaded hashes
Cost 2 (crypto [0=Blowfish, 1=AES]) is 1 for all loaded hashes
Will run 8 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
claudio          (Aula da Prova3.odt)
1g 0:00:00:00 DONE (2020-10-01 15:33) 1.204g/s 77.10p/s 77.10c/s 77.10C/s claudia..claudiV
Use the "--show --format=ODF" options to display all of the cracked passwords reliably
Session completed. 
```
It fails on 7.
```
$ python3 ~/bin/bleeding/run/libreoffice2john.py 7.0.1.2.odt 
Traceback (most recent call last):
  File "/home/claudio/bin/bleeding/run/libreoffice2john.py", line 152, in <module>
    process_file(sys.argv[k])
  File "/home/claudio/bin/bleeding/run/libreoffice2john.py", line 86, in process_file
    salt = binascii.hexlify(base64.b64decode(salt)).decode("ascii")

```

**Comment by Mi-Al** [comment]
**@claudioandre-br**, thank you for confirmation!

> Does the script work for you on older LibreOffice documents

Yes, it works fine, I tested with document created by “LibreOfficePortablePrevious_6.4.6”.

> Can you please attach to here a non-security-sensitive sample file with a known password, which we can use for testing?

I uploaded the file to Google Drive, link: https://drive.google.com/file/d/1N1p3f9J2adV0m17DqiTY7a-REKBsL7VZ/view

Its password: 123456

**Comment by solardiz** [comment]
FWIW, at least on this system with Python 3.3, the script actually fails differently than what we see in previous comments here, and in the same way for both old and new LibreOffice files:

```shell
[solar@super run]$ scl enable python33 bash
[solar@super run]$ python --version
Python 3.3.2
[solar@super run]$ ./telegram2john.py ~/john-samples/Office/LibreOffice_3.5.1/Libre-Default_myhovercraftisfullofeels_.odt
Traceback (most recent call last):
  File "./telegram2john.py", line 179, in <module>
    process_xml_file(sys.argv[j])
  File "./telegram2john.py", line 142, in process_xml_file
    tree = ET.parse(filename)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xml/etree/ElementTree.py", line 1242, in parse
    tree.parse(source, parser)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xml/etree/ElementTree.py", line 1730, in parse
    self._root = parser._parse(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
[solar@super run]$ ./telegram2john.py ~/john-samples/Office/Libre-v7_123456.odt 
Traceback (most recent call last):
  File "./telegram2john.py", line 179, in <module>
    process_xml_file(sys.argv[j])
  File "./telegram2john.py", line 142, in process_xml_file
    tree = ET.parse(filename)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xml/etree/ElementTree.py", line 1242, in parse
    tree.parse(source, parser)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xml/etree/ElementTree.py", line 1730, in parse
    self._root = parser._parse(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
```

So I guess it also depends on a somewhat recent Python 3 version.

**Comment by solardiz** [comment]
Installed Python 3.6, still no luck even with the old LibreOffice version:

```
[solar@super run]$ scl enable rh-python36 bash
[solar@super run]$ python --version
Python 3.6.9
[solar@super run]$ ./telegram2john.py ~/john-samples/Office/LibreOffice_3.5.1/Libre-Default_myhovercraftisfullofeels_.odt
Traceback (most recent call last):
  File "./telegram2john.py", line 179, in <module>
    process_xml_file(sys.argv[j])
  File "./telegram2john.py", line 142, in process_xml_file
    tree = ET.parse(filename)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
[solar@super run]$ ./telegram2john.py ~/john-samples/Office/Libre-v7_123456.odt 
Traceback (most recent call last):
  File "./telegram2john.py", line 179, in <module>
    process_xml_file(sys.argv[j])
  File "./telegram2john.py", line 142, in process_xml_file
    tree = ET.parse(filename)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
```

**Comment by solardiz** [comment]
(Sorry for posting two weird comments in here, now deleted - that's what I get looking into two unrelated yet similar issues at once.)

I confirm the script works and fails exactly as described in prior comments. Looking into it failing for the LibreOffice 7 sample, I see the immediate issue is it never finds a salt. Specifically this code:

```python
                data = element.get("{urn:oasis:names:tc:opendocument:xmlns:manifest:1.0}salt")
                if data:
                    salt = data
```

never reaches the `salt = data` line when run on the LibreOffice 7 sample. That line is reached on an older sample.

**Comment by solardiz** [comment]
This makes it work on the LibreOffice 7 sample, as well as on the older one:

```diff
+++ b/run/libreoffice2john.py
@@ -50,7 +50,7 @@ def process_file(filename):
     for i in range(0, len(elements)):
         element = elements[i]
         if element.get("{urn:oasis:names:tc:opendocument:xmlns:manifest:1.0}full-path") == "content.xml":
-            for j in range(i + 1, i + 1 + 3):
+            for j in range(i + 1, i + 1 + 4):
                 element = elements[j]
                 # print element.items()
                 data = element.get("{urn:oasis:names:tc:opendocument:xmlns:manifest:1.0}checksum")
```

The issue is that the script makes assumptions. It first converts the tree to a list, then goes over the list and expects to find everything it needs in 3 list elements that follow "content.xml" (and were actually at a nested level for that file before the conversion to list). LibreOffice 7 seems to have changed the order of "start-key-generation" (which the script doesn't care about, maybe wrongly) and "key-derivation" (which it needs, and which was now one element too far).

**Comment by solardiz** [comment]
If I understand correctly, by not parsing "start-key-generation" both the script and our ODF format assume that the hash function used for checksum is also the one used in PBKDF2 (both are either SHA-1 or SHA-256), but the fields appear to allow for these to be different (hopefully, is never the case in practice). Maybe we need to harden the script to confirm that these are indeed the same.
