### ISSUE TITLE
Prefix wordlist related parameters with --wordlist

### ISSUE THREAD

**Issue by wsandin** [openwall/john#4399]
From @magnumripper in PR #4394 
```
On a side note we should rename this option to --wordlist-mem-file-size or
something else starting with --wordlist- (such as --wordlist-preload-threshold

We'd do so in another PR though, the deprecated old option name would
need to be handled for a while.
```

This also goes for `--dupe-suppression` and `--loopback`

**Comment by magnumripper** [comment]
In case you take a stab at this, here's some current code handling previously deprectated options:

options.c line 106
```c
	{"internal-codepage", FLG_SECOND_ENC, FLG_SECOND_ENC,
		0, OPT_REQ_PARAM, OPT_FMT_STR_ALLOC, &internal_cp_str},
	/* -internal-encoding is a deprecated alias for -internal-codepage */
	{"internal-encoding", FLG_SECOND_ENC, FLG_SECOND_ENC,
		0, OPT_REQ_PARAM, OPT_FMT_STR_ALLOC, &internal_cp_str},
```

options.c line 243
```c
	{"nolog", FLG_NOLOG, FLG_NOLOG}, // Deprecated!
	{"no-log", FLG_NOLOG, FLG_NOLOG},
```

recovery.c line 266
```c
	while (*++opt) {
		/********* Re-write deprecated options *********/
		if (!strncmp(*opt, "--internal-encoding", 19))
			memcpy(*opt, "--internal-codepage", 19);
		else
		if (!strcmp(*opt, "--nolog"))
			*opt = "--no-log";
		/***********************************************/
```

Ideally the comments above should have mentioned WHEN options got deprecated so we can know (without digging into git) when to drop support for the old ones. Alas, they don't. Anyway I've had the idea that "the next time" we deprecate an option we should write a function in recovery.c for handling them, defined more like a list or something, if possible.

I think the idea so far was that from the point of introducing a deprecated option, once a new release got out we'd continue supporting the new one as well as the old (as seen in `options.c` above) but re-write them in any session file (as seen in `recovery.c` above) until right before *next-next* release.

**Comment by wsandin** [comment]
I just had a look at this, and I realised that we'd need to increase indentation/space between menu options and description by three spaces, to fit in these options prefixed with "wordlist". I guess that's fine, but just wanted to check with you before proceeding - as it may have been the reason they're named like this in the first place.

What's your thoughts?

**Comment by solardiz** [comment]
> we'd need to increase indentation/space between menu options and description by three spaces

I don't mind, but maybe we can instead come up with better option names? Maybe e.g. `--dupe-suppression` can become `--wordlist-unique` (consistent with the name of our `unique` program, as well as with option `-u` to `sort`).

**Comment by magnumripper** [comment]
I'd rather not change option names as it comes with boring backward compatibility support (but yes, if that option would have been added today it'd definitely be named something starting with `--wordlist-`).

Just see to it that the longest lines are 79 or 80 bytes wide (some user reported Microsoft stuff would add a blank line if we use column 80 - how stupid is that?!). Some time soon I'll add a `log_print()` function that knows and/or adapts to column width without us caring much.

**Comment by magnumripper** [comment]
BTW I think `--dupe-suppression` works with PRINCE mode as well.

**Comment by solardiz** [comment]
> I'd rather not change option names as it comes with boring backward compatibility support

In other words, you suggest we don't do anything on this issue? Just close it?

> Microsoft stuff would add a blank line if we use column 80

Yes. We need to use at most 79.

> BTW I think `--dupe-suppression` works with PRINCE mode as well.

Oh, this may be a reason not to rename. We also have `--rules`.

**Comment by magnumripper** [comment]
> In other words, you suggest we don't do anything on this issue? Just close it?

Not sure I quite understood the original question but I think I recall we had different indentation for the old `--list=hidden-options` vs. the normal usage blob so that might be where some "indentation vs. width" issue sneaked in. I suggest we increase indentation (if needed) to accommodate all option names on the left "side" and when doing so, split/add rows if needed to have the descriptions still fit in whatever is left of our 79 columns.

**Comment by solardiz** [comment]
> Not sure I quite understood the original question

The question was about whether we should do any option renames at all, or maybe not. Maybe we actually don't want this issue to be worked on.

**Comment by magnumripper** [comment]
Oh, right, sorry 😆 I thought this was another issue.

Well `--dupe-suppression` isn't a candidate now that we think of it, and `--loopback` is almost a mode in itself and some day it might well be totally separated from `wordlist.c`.

Maybe `--wordlist-mem-file-size` is an actual candidate but that's a rarely used option, perhaps to the point of being a candidate for dropping (perhaps with support kept in john.conf).

So, uh, perhaps we should just let things be, and close the issue for now?

**Comment by solardiz** [comment]
> So, uh, perhaps we should just let things be, and close the issue for now?

Yes, let's do that.
