### ISSUE TITLE
Keyboard input for status/quit vs. stdin or subshell

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4403]
Three ways of using `--stdin` (or `--pipe`):

### 1. stdin is our terminal:
```
$ ./john hashfile -stdin
(...)
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
```
The above works as expected: Obviously the status/quit keys does not work and the message reflects that.

### 2. stdin is a file or fifo:
```
$ ./john hashfile -stdin < some.file
(...)
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
```
Above, the status/quit keys **do** work, so the message is... well it's correct but it should ideally be "Press 'q' or Ctrl-C to abort, almost any other key for status".

### 3. stdin is a pipe:
```
$ cat some.file | ./john hashfile -stdin
(...)
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
```
Here, status/quit keys do not work - but *why don't they*? Can we fix that or is it nigh impossible in this situation?

### 4. Related issue:
Not using -stdin, but running via some front-end script or program. Example:
```
$ cat front-end.sh
#!/bin/sh
../run/john $*

$ ./front-end.sh hashfile -inc
(...)
Press 'q' or Ctrl-C to abort, almost any other key for status
```
Status/quit keys do **not** work so the message is not correct! Can we get them to work in this situation? Failing that, can we get the message right? Or could we amend that script in some way for letting john have the keyboard for status/quit commands?

**Comment by AlekseyCherepanov** [comment]
For a script, `#!/bin/sh -i` may be used, then the status would work but shell would print a prompt in the end. Prompt may be disabled with `export PS1=` in the script. I am not sure about other side effects of `-i` option.

If john is the last command in a script then `exec` may be used. It makes status to work too.

(Minor unrelated note: usually magical `"$@"` (with double quotes) should be used instead of `$*` to pass arguments, otherwise each argument is split by spaces.)

**Comment by AlekseyCherepanov** [comment]
Oops, while `export PS1=` disables last prompt, prompts before it are shown.

**Comment by magnumripper** [comment]
Good input! This opens up for workarounds in some situations, but ideally we'd fix/improve things in Jumbo, if possible.

I believe some differences in actual situation vs. the "Press (...)" message might be due to this inconsistency:

tty.c
```c
/*
 * If we're in "--stdin" mode (reading candidate passwords from stdin), then
 * only initialize the tty if stdin is not a tty.  Otherwise it could be the
 * same tty, in which case we'd interfere with the user's ability to type
 * candidate passwords directly to John.
 */
	if (stdin_mode && !tcgetattr(0, &ti))
		return;
```

cracker.c (simplified)
```c
	if ((options.flags & FLG_STDIN_CHK) || (options.flags & FLG_PIPE_CHK))
		fprintf(stderr, "Press Ctrl-C to abort, or send SIGUSR1 to john process for status\n");
	else
		fprintf(stderr, "Press 'q' or Ctrl-C to abort, almost any other key for status\n");
```
Maybe the latter code (which btw is Jumbo-specific - John proper doesn't even try to put it right) should use `tcgetattr()` the same way as in `tty.c` to better reflect actual situation. I assume it would fix the message for example 2 but not example 4.

However, fixing that isn't the ideal outcome of this issue on its own: I'd really like to be able to read the keyboard in a few more situations. Having the message reflect actual situation is a start though.

**Comment by AlekseyCherepanov** [comment]
Inconvenience was reported in issue #3766. So I'll repeat here some stuff sent over mail earlier.

In bash, it is possible to make a pipe avoiding `|` that disables access to terminal. So status works with such command:
```
$ john t.pw --stdin < <(seq 100000000)
```

In other shell, a named fifo might be used in the same manner.

Also it is possible to dispatch john in background and run a loop to send signals to john. But I don't know how to exit loop when john finishes.
```
$ (seq 100000000 | john --stdin t.pw & while read unused; do kill -USR1 $!; done)
```

Somehow the following works with dash, but not with bash:
```
sh -c 'trap "" CHLD; seq 10 | john --stdin t.pw & while read unused; do kill -USR1 $!; done'
```

IIRC there is a difference also: signal makes john write .rec file, while regular input just emits status line without writing .rec file.

**Comment by AlekseyCherepanov** [comment]
Idea: ssh opens `/dev/tty` to read password from user even if input is from pipe. But it may interfere with input for program that is piped into ssh.

Example where ssh's password reader steals part of input:
```
$ strace -o trace1 cat | strace -o trace2 ssh -o PreferredAuthentications=password [...]
[...]
[... input: "asdf\n" ...]
[... input: "qwer\n" ...]
[...]

$ cat trace1
[...]
read(0, "asdf\n", 131072)               = 5
write(1, "asdf\n", 5)                   = 5
read(0, "wer\n", 131072)                = 4
write(1, "wer\n", 4)                    = 4
[...]

$ cat trace2
[...]
openat(AT_FDCWD, "/dev/tty", O_RDWR)    = 4
close(4)                                = 0
openat(AT_FDCWD, "/dev/tty", O_RDWR)    = 4
[...]
read(4, "q", 1)                         = 1
[...]
```

(Regular open() function uses openat syscall; that's with glibc 2.28.)

**Comment by ghost** [comment]
I just noticed that john's output changes if I use pipe in the command below:
```
$ ../run/john --mask=?a --min-len=0 --max-len=1 --stdout | head
Press 'q' or Ctrl-C to abort, almost any other key for status
1p 0:00:00:00 1,04% (1) (ETA: 04:16:11) 14.28p/s 
96p 0:00:00:00 100,00% (1) (2020-10-11 04:16) 1371p/s |

a
e
1

$ ../run/john --mask=?a --min-len=0 --max-len=1 --stdout
 
1p 0:00:00:00 1,04% (1) (ETA: 04:19:04) 12.50p/s 
a
e
1
```

**Comment by magnumripper** [comment]
Apparently `--stdout` does not emit a message ~unless~ when stdout is a terminal (we don't want to clutter the output). ~We could opt to emit one to stderr though.~ (we always do *when* we print it)

**Comment by magnumripper** [comment]
Our 'doc' directory is over-populated but maybe we should have a file called eg. TRICKS where some of those bash tricks would fit (together with other things like fifo magic - and its caveats).

**Comment by magnumripper** [comment]
> Idea: ssh opens `/dev/tty` to read password from user even if input is from pipe. But it may interfere with input for program that is piped into ssh.

Our `tty_init()` tries to open `/dev/tty` with `O_NONBLOCK`, maybe that's about the same. However, in example 3 it gives up because `tcgetpgrp(fd) != getpid()`.

Here's what's happening in the three cases.
1. `tty_init()` correctly gives up since stdin is the terminal, `cracker.c` prints the correct message.
2. `tty_init()` sets everything up for reading keys, but `cracker.c` considers that stdin is a terminal (is it!?) and prints the wrong message.
3. `tty_init()` gives up because after it opens `/dev/tty` it sees that `tcgetpgrp(fd) != getpid()` (meaning we're not the foreground process). `cracker.c` simply considers that stdin is a terminal and happens to print the right message.
4. `tty_init()` is just like example 3 in that it gives up on `tcgetpgrp(fd) != getpid()`. But `cracker.c` thinks everything is dandy (we're not even using `--stdin` mode) so prints the wrong message.

I just tried commenting out that test of `tcgetpgrp(fd)` and it works like a champ (that is, example 3 can read keystrokes despite getting input from pipe, and example 4 also works just fine without any bash magic). So why do we do that? Perhaps what happens is if I press a `q` it will be picked up by both processes, or just any one of them? Using `cat` it's not a problem but using `john (...) -stdout | john (...) -stdin` we would/could stop the rightmost process prematurely I suppose?

**Comment by magnumripper** [comment]
> I just tried commenting out that test of `tcgetpgrp(fd)` and it works like a champ (that is, example 3 can read keystrokes despite getting input from pipe, and example 4 also works just fine without any bash magic). So why do we do that? Perhaps what happens is if I press a `q` it will be picked up by both processes, or just any one of them? Using `cat` it's not a problem but using `john (...) -stdout | john (...) -stdin` we would/could stop the rightmost process prematurely I suppose?

From limited testing of `../run/john -stdout -mask:?a -len=8 | ../run/john -ses:2 hashfile -stdin` (on macOS) with the `tcgetpgrp(fd)` test disabled:
- The first process in the chain get nearly all keystrokes, but the second one get some (at least if I hold a key down - and I think when it happens, the first one didn't see that one same).
- After such session, my terminal have needed a reset ~every time so far~ most of the times. This even though it seemed the first process got the keystroke (just like in pristine code). So why does this happen?

**Comment by magnumripper** [comment]
At this point I'm considering some expert option like `--force-keys`, for disabling that test on a case by case basis. But is there a nicer way of doing it?

**Comment by magnumripper** [comment]
> * After such session, my terminal have needed a reset ~every time so far~ most of the times. This even though it seemed the first process got the keystroke (just like in pristine code). So why does this happen?

I think I get it: First process saves initial state of terminal and then sets up terminal for reading keystrokes. Then (I assume always after the former) the second process does the same. But the saved state for session 2 is the state **after** first process messed with it.

At exit, if process 2 ends last, we'll end up with a messed-up terminal. This may not be a trivial thing to fix. *Edit: Yes it was: I now simply do `saved_ti.c_lflag |= (ICANON | ECHO)` before restoring - only if `--force-keys` was used of course.*

**Comment by AlekseyCherepanov** [comment]
Some wild fantasies...

`john --stdout ... | john --stdin ...` is an example where left hand side of pipe reads input too. There might be some other interactive generator. I thought that it would be a strange scenario, but generator may use interactivity for status like john.

So for 2/multiple johns, it might be cool to choose one that reads tty and sends signals to other johns on this tty, so one key would trigger status lines from all processes. Particularly john might avoid reading tty if it is not in regular mode at the start. But sending signal to other johns is trickier. It looks like overengineering.

Also there might be other session working in background started with `&`. It may or may not be desirable to trigger status line from it.
