### ISSUE TITLE
pdf2john.pl produces a weird hash

### ISSUE THREAD

**Issue by cchristion** [openwall/john#4417]
I used npdf2john, but still getting the same string

Pdf2john
`pdf:$pdf$23128*-1852116617fb7c2e2dfe7a1a728a24559b97f2d32bfe39e32595b91601aad564d2c5897c80000000000000000000000000000000032*2e24196b68073e33e6f36768f8e03d39923cc66b9cfa32b9768f87798eb19722`

npdf2john
`pdf:$pdf$23128*-1852116617fb7c2e2dfe7a1a728a24559b97f2d32bfe39e32595b91601aad564d2c5897c80000000000000000000000000000000032*2e24196b68073e33e6f36768f8e03d39923cc66b9cfa32b9768f87798eb19722`

Reference issue #2388

**Comment by magnumripper** [comment]
As explained in #4203 your PDF might be read-only with a password (or IIRC it can be protected from printing, or something else), and we can crack that password.

**Comment by clarychristionc** [comment]
> As explained in #4203 your PDF might be read-only with a password (or IIRC it can be protected from printing, or something else), and we can crack that password.

It's password protected.
I tried opening it but it shows

![Uploading Screenshot_2020-10-27-15-06-51-00_e2d5b3f32b79de1d45acd1fad96fbb0f.jpg…]()

**Comment by clarychristionc** [comment]
> As explained in #4203 your PDF might be read-only with a password (or IIRC it can be protected from printing, or something else), and we can crack that password.

I tried opening it, it shows like this
![Screenshot_2020-10-27-15-06-51-00_e2d5b3f32b79de1d45acd1fad96fbb0f](https://user-images.githubusercontent.com/47944263/97283770-451a1480-1866-11eb-95c9-73cc526709af.jpg)

**Comment by clarychristionc** [comment]
> As explained in #4203 your PDF might be read-only with a password (or IIRC it can be protected from printing, or something else), and we can crack that password.

I tried opening it but it's asking for password
![Screenshot_2020-10-27-15-09-12-73_e2d5b3f32b79de1d45acd1fad96fbb0f](https://user-images.githubusercontent.com/47944263/97283965-78f53a00-1866-11eb-8fc5-109920c7d9cf.jpg)

**Comment by cchristion** [comment]
> we can crack that password.

How ?

**Comment by ghost** [comment]
The GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those.
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message Subject when you post).

BTW:
```bash
$ john hash.txt 
Using default input encoding: UTF-8
Loaded 1 password hash (PDF [MD5 SHA2 RC4/AES 32/64])
Cost 1 (revision) is 3 for all loaded hashes
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 2 candidates buffered for the current salt, minimum 8 needed for performance.
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:/snap/john-the-ripper/current/run/password.lst
Proceeding with incremental:ASCII
201301           (pdf)
1g 0:00:00:06 DONE 3/3 (2020-10-27 07:28) 0.1492g/s 111413p/s 111413c/s 111413C/s 201918..201369
Use the "--show --format=PDF" options to display all of the cracked passwords reliably
Session completed. 
```

**Comment by cchristion** [comment]
Did you reformat the hash in anyway  ?

**Comment by magnumripper** [comment]
No, we merely used the latest version of John - you should too.
