### ISSUE TITLE
Skip format initialization on "--show"

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4426]
Any opinions on this? -

```diff
+++ b/src/loader.c
@@ -770,13 +770,15 @@ find_format:
                        retval = valid;
                        *ciphertext = prepared;
                        ldr_set_encoding(alt);
+                       *format = alt;
 #ifdef HAVE_OPENCL
                        if (options.acc_devices->count && options.fork &&
-                           strstr(alt->params.label, "-opencl"))
-                               *format = alt;
-                       else
+                           strstr(alt->params.label, "-opencl")) {
+                               /* skip format initialization here */
+                       } else
 #endif
-                       fmt_init(*format = alt);
+                       if (!source) /* not --show */
+                               fmt_init(alt);
 #ifdef LDR_WARN_AMBIGUOUS
                        if (!source) /* not --show */
                                continue;
```

I noticed that an `--enable-ztex` build would refuse to `--show` ZTEX-supported hashes unless a board was connected and powered on, or unless an explicit e.g. `--format=bcrypt` was used (to use the CPU format instead).

Do we use anything requiring format initialization with `--show`?

**Comment by magnumripper** [comment]
I can't think of a reason the idea of "skip format initialization on --show" would be bad.

But we now have this (simplified):
```c
	if (!source) /* not --show */
		fmt_init(alt);

	if (!source) /* not --show */
		continue;
```
Why init and then continue? Maybe I miss the full picture.

**Comment by solardiz** [comment]
These two are unrelated to each other (except for the same condition): we init when we intend to actually use the format, and we continue to detect other possible formats to print the "Warning" lines. Both of these are suppressed (for different reasons) with "--show".

**Comment by magnumripper** [comment]
I should probably look closer to the code (sorry if so)... but on a quick look `format` is the one we intend to use and `alt` is an alternate format that we just put up a warning for. So why would we init `alt` at all?

As far as I can see (without expanding too much) we only actually use `alt->params.label` and that's not a thing I'd think we'd need to call `init` for.

**Comment by solardiz** [comment]
`*format` and `alt` are the same thing here, it's apparent from the patch context I posted. Previously, we called `fmt_init(*format = alt);` (that line came from core). Now we first `*format = alt;` (so that we don't have to repeat that line in 3 separate cases) and conditionally call `fmt_init(alt);`.

We need to call `init()` because we've just determined we'll actually use the format, including calling its `binary()` and `salt()` during loading.

I am actually wondering how we get away with not doing that when `options.acc_devices->count && options.fork && strstr(alt->params.label, "-opencl")`. Perhaps you can look into this and explain it, and maybe we'll arrive at some further simplification or optimization once we have common understanding. Thanks!

**Comment by magnumripper** [comment]
Oh right. Yes, I think I really need to explain that, if nothing else for my own (re-)understanding of this.
