### ISSUE TITLE
Wifi w of n

### ISSUE THREAD

**Issue by B-cr** [openwall/john#4441]
https://github.com/guardicore/monkey/issues/873

**Comment by magnumripper** [comment]
Can you please elaborate? I don't understand what the linked issue is about at all, never mind what would be the connection to John the Ripper. The name "Wifi w of n" doesn't help.

**Comment by solardiz** [comment]
There's nothing reasonable we can do on this "issue" when it's non-described like that, so I'll close it. @B-cr please feel free to describe the issue properly (adding comments to a closed issue is OK) and if it's in fact an issue with our project we may reopen.
