### ISSUE TITLE
Benchmark passes multi-hash list into crypt_all()

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4450]
Turns out that for descrypt our `--test` benchmark calls `crypt_all` with a list of 3 hashes for the salt, and for LM with a list of 10. If the format's implementation implements hash comparison in `crypt_all`, it ends up doing more work than the user running the benchmark likely expects: we previously benchmarked for 1 hash per salt. We should probably fix this by using 1-entry lists during benchmark, even if we use multi-entry lists during self-test.

**Comment by magnumripper** [comment]
I'm a bit confused with the fact LM is mentioned here given it's not salted?

**Comment by magnumripper** [comment]
I guess it means "single salt" and "raw" benchmarks should always be against a single hash? There are probably a number of "non-hash formats" more or less affected as well. **Edit**: Maybe not, that should be impossible...

**Comment by solardiz** [comment]
This issue applies equally to salted and unsalted formats, and to many vs. single salt or raw benchmarks. It's about the number of "loaded" hashes that a comparison is performed against for the current salt (or for the only salt, or for no salt). For unsalted hashes like LM, our loader creates a one-entry salt list, and our cracker goes over that list. It's just a common way for us to group hashes to perform comparisons against.

In benchmarks, we should always compare against just one hash per salt (for salted formats) or simply against one hash (for unsalted formats and "Only one salt" benchmarks). So we should be passing one-entry lists under the `salt` parameter to `crypt_all()`, not multi-entry like we often do now.

When we and our users interpret our current benchmark results, they/we don't expect there's overhead of comparisons against multiple hashes. Further, they/we reasonably expect the benchmarks won't be affected by addition of test vectors (beyond the first two), whereas right now they might be: add more hashes with the same salts as one of the first two, and there will suddenly and unexpectedly be more comparisons and thus lower reported benchmark speeds - hard to compare against other versions of JtR and against other software. These reasons are why I think we have a bug here.

**Comment by solardiz** [comment]
Once we fix this issue globally, we should drop the workarounds for descrypt and LM that I recently introduced into `DES_bs_b.c`.

**Comment by magnumripper** [comment]
I assume we started doing this with the introduction of `test_db`. So we should basically just delete all entries but one from each salt bucket, between the self-test and the benchmark, right? More or less like calling `crk_remove_hash()` - perhaps by actually doing so.

**Comment by solardiz** [comment]
> So we should basically just delete all entries but one from each salt bucket, between the self-test and the benchmark, right?

Right.

> More or less like calling `crk_remove_hash()` - perhaps by actually doing so.

I thought we'd simply set `list->next` and `bitmap` and `hash` to NULL. Your idea is good, but in the unlikely event that we had so many same-salt test vectors that a bitmap and hash table were created, we'd end up with them containing one entry, which isn't same code and same speed as having a one-entry list. In other words, your idea would mimic actually getting all but one hash cracked and measuring the performance afterwards, whereas what we expect from the benchmark is performance with one hash (per salt when applicable) loaded initially.

**Comment by magnumripper** [comment]
I believe this should do it
```diff
diff --git a/src/bench.c b/src/bench.c
index 3025b744e..005f609a5 100644
--- a/src/bench.c
+++ b/src/bench.c
@@ -472,6 +472,12 @@ char *benchmark_format(struct fmt_main *format, int salts,
 			dbsalt = dbsalt->next;
 		if (dbsalt) {
 			two_salts_db[index] = dbsalt;
+			if (dbsalt->count > 1) {
+				dbsalt->list->next = NULL;
+				dbsalt->count = 1;
+				dbsalt->bitmap = NULL;
+				dbsalt->hash = NULL;
+			}
 		} else {
 			puts("Warning: Could not find salt in db");
 			two_salts_db[index] = test_db->salts;
```

I couldn't spot anything significant using `relbench` before/after this; but OTOH your workarounds were still in place and it's likely no other formats should be expected to show any significant difference even if having comparison in `crypt_all` (they might have it for any weird reasons including brain farts).

Actually both DEScrypt and LM showed slightly lower speed with this patch (and without removing your workarounds) but that might mean nothing.

Anyway this patch seems to do what we want and doesn't seem to break anything.

**Comment by magnumripper** [comment]
Previous relbench test was with CPU formats. Now tried `--format:mask` as well (basically meaning OpenCL device-side mask formats with comparison on GPU) and they showed very little difference, nothing bad of course. All were between 0.4% and 3.5% better but that's probably within normal noise.

**Comment by solardiz** [comment]
I think our OpenCL device-side comparisons are pretty well optimized for having multiple hashes per salt, so it's not surprising this makes little difference.

**Comment by magnumripper** [comment]
> which isn't same code and same speed as having a one-entry list. In other words, your idea would mimic actually getting all but one hash cracked and measuring the performance afterwards, whereas what we expect from the benchmark is performance with one hash (per salt when applicable) loaded initially.

I understand it's not quite the same thing - but I believe Sayantan's GPU formats would trigger on certain thresholds of "salts remaining" (or is it even hashes remaining per salt? **Edit** *of course that must be it, maybe he even only does it with unsalted formats*) and re-calculate the (or some) hash tables. Not sure how important that is, but perhaps cracker could do the same with bitmaps? In the simplest case, ditch them at some point. I'm just talking now, I have no idea if it would make sense - but given that's shared code it could be a decently small change, if it's worthwhile.

**Comment by solardiz** [comment]
Yes, we can enhance cracker.c to skip the bitmap (or even set it to NULL for future calls) once the hash count drops below a threshold (perhaps at least when just one hash is left for the salt).

**Comment by magnumripper** [comment]
>> I believe Sayantan's GPU formats would trigger on certain thresholds (...) and re-calculate the (or some) hash tables. Not sure how important that is, but perhaps cracker could do the same with bitmaps?
>
> Yes, we can enhance cracker.c to skip the bitmap (or even set it to NULL for future calls) once the hash count drops below a threshold (perhaps at least when just one hash is left for the salt).

Stopping and resuming a session would give the same (or better) effect, right? If not, we should definitely fix that. If yes, perhaps this isn't worthwhile unless the boost is much more significant than I picture it. OTOH the "one hash left" is trivial enough that we might consider doing it anyway, just for the sake of it.

**Comment by solardiz** [comment]
> Stopping and resuming a session would give the same (or better) effect, right?

Right.

> OTOH the "one hash left" is trivial enough that we might consider doing it anyway

I also think so.

**Comment by magnumripper** [comment]
I stared at `cracker.c` for a while and then decided I shouldn't even try it. Made a PR with the above fix for `bench.c` though.
