### ISSUE TITLE
--help should list options in a sensible order

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4459]
As a follow up to #4394, we need to adjust the order in which options are listed with `--help` for it to make more sense.

As an example, core keeps `--node` and `--fork` near each other, but in jumbo they're now far apart. Similarly, jumbo's `--subformat` is now far from `--format`.

Perhaps we should also list options in the same order in `doc/OPTIONS` and in the upcoming man page.

**Comment by wsandin** [comment]
I like the idea of consistency. :+1: I've subscribed to keep an eye on this thread as I progress with work on the man pages.

**Comment by solardiz** [comment]
Thanks @wsandin. I was hoping you'd participate in fixing this issue for us more directly. ;-)

**Comment by wsandin** [comment]
That I'd be happy to as well. :-) I'll start to have a look at `--help` in core vs. jumbo to get some more context.

**Comment by solardiz** [comment]
Core's is:

```
Usage: john [OPTIONS] [PASSWORD-FILES]
--single                   "single crack" mode
--wordlist=FILE --stdin    wordlist mode, read words from FILE or stdin
--rules                    enable word mangling rules for wordlist mode
--incremental[=MODE]       "incremental" mode [using section MODE]
--external=MODE            external mode or word filter
--stdout[=LENGTH]          just output candidate passwords [cut at LENGTH]
--restore[=NAME]           restore an interrupted session [called NAME]
--session=NAME             give a new session the NAME
--status[=NAME]            print status of a session [called NAME]
--make-charset=FILE        make a charset, FILE will be overwritten
--show                     show cracked passwords
--test[=TIME]              run tests and benchmarks for TIME seconds each
--users=[-]LOGIN|UID[,..]  [do not] load this (these) user(s) only
--groups=[-]GID[,..]       load users [not] of this (these) group(s) only
--shells=[-]SHELL[,..]     load users with[out] this (these) shell(s) only
--salts=[-]N               load salts with[out] at least N passwords only
--save-memory=LEVEL        enable memory saving, at LEVEL 1..3
--node=MIN[-MAX]/TOTAL     this node's number range out of TOTAL count
--fork=N                   fork N processes
--format=NAME              force hash type NAME: descrypt/bsdicrypt/md5crypt/
                           bcrypt/LM/AFS/tripcode/dummy/crypt
```

So it's mode and mode modifiers, then `--stdout`, then session management, then `--make-charset` and `--show` (both process previously cracked passwords in `john.pot`), then `--test`, then selectors of which entries (not) to load, then `--save-memory`, then two options controlling workload split across nodes and processes, and finally `--format` controlling which hash types to load (that one could logically be near the "selectors", but it's listed last in core because it includes the actual list of possible formats).

**Comment by magnumripper** [comment]
My vague idea is to start with the above, add all --single-foobar options right after --single (sorted, but after) and so on, then ending up with a LOT of stray options not quite attached to anything else. Those stray options we could want to simply sort by name. Then (always) end with --format.

Things like --stress-test or --test-full should obviously go right after --test. Even the --no-mask option should be grouped with (after) them, as it's solely a test option.

**Comment by wsandin** [comment]
Bump - Just started to put in some work today as I'm getting more time for these things during the holidays. :-)

**Comment by solardiz** [comment]
@wsandin Thank you for working on this. I really would like this to be taken care of before our 1.9.0-jumbo-2 release, if possible. Will you?

Please also consider #4399 since it's related.

**Comment by wsandin** [comment]
Hey Solar :) Sure, sorry it got stale for a while. When do you plan to do
the release?

**Comment by solardiz** [comment]
> When do you plan to do the release?

No specific due date. When ready. The sooner the better, because we've fixed bugs and portability issues since the previous release yet they keep biting people using that release.

**Comment by wsandin** [comment]
Ah, I will make it happen ASAP then - as in this week! Cheers and thanks
for pinging, would be a pity to miss the opportunity to contribute.

**Comment by wsandin** [comment]
@solardiz @magnumripper I just had a go at implementing your suggestions. I guess some of the options could be grouped a bit more rather than being stale in alphabetical order. Would be happy to hear your thoughts.

Once we concluded that part, I'll make sure to update the `doc/OPTIONS` file.

**Comment by solardiz** [comment]
This issue has been mostly taken care of, but some further re-ordering might still be desirable (I'll probably give it a try) and then there's @wsandin's kind offer:

> Once we concluded that part, I'll make sure to update the doc/OPTIONS file.

I am leaving the issue open for now for these two things.

**Comment by solardiz** [comment]
This issue was mostly handled and it looks like we're not doing anything further on it now. Sure we want to improve our documentation in general, but I think that's separate.
