### ISSUE TITLE
Multibit Classic key - md5 or scrypt?

### ISSUE THREAD

**Issue by tmoklc** [openwall/john#4462]
I have a few old wallets and keys from Multibit Classic. Having run the multibit2john.py script on them, it returns a hash below (modified for security)

```
jointBit-20140219104928.key: Make sure that this is a MultiBit HD wallet!
jointBit-20140219104928.key:$multibit$2*12345678912345678912345678985a42*123456789123456789123456789a4c6a*123456789123456789123456789385a42
```

From what I can see in the code, and the comment above, the `multibit$2` bit refers to it being a Multibit HD wallet? This is not the case and I have opened this wallet recently in Multibit Classic.

Did Multibit Classic use several different types of hashes for encoding (md5 and scrypt) or is there possibly some issue with the multibit2john.py code?

Relevant lines here:
https://github.com/openwall/john/blob/d41adeda95b9ad9a95cc1180b16be53db9705dee/run/multibit2john.py#L1372

**Comment by magnumripper** [comment]
I assume you wouldn't like to share the wallet :-) so could you perhaps add some debug prints around the try/catch here:
https://github.com/openwall/john/blob/d41adeda95b9ad9a95cc1180b16be53db9705dee/run/multibit2john.py#L1353-L1362
...and see why it triggers? Maybe you can even print all of `pdata` and see "what it looks like". Perhaps some of the assumptions are wrong or just needs adjusting.

**Comment by magnumripper** [comment]
BTW you could even comment out that whole test, forcing version 1 and see if that works (and you can crack it). That would be an important data point for us.

**Comment by tmoklc** [comment]
Thanks @magnumripper for the quick response. I'm happy to [share one of the wallets](https://github.com/openwall/john/files/5559028/jointBit-20140302075329.zip) as it's only got scraps of BTC in it. I'll also try your suggestions, though you are considerably more likely to get to the bottom of this than I am!

**Comment by tmoklc** [comment]
I commented out the test and forced version 1, output is:
`jointBit-20140302075329.key:$multibit$1*58312b4958557743*4d702b4b636836794d6b2b7871652b5433684d6e32507876356e6d5979636775`
Not sure if that's what the MD5 hash should look like. Unfortunately I don't have the password for this so can't easily test cracking it. Is it possible to validate that hash before committing to cracking it?

**Comment by magnumripper** [comment]
> Is it possible to validate that hash before committing to cracking it?

It's all printable ASCII (or even just a Base-64 character set) when un-hexing it, that's normally not a good sign... And none of the test vectors we have are like that.

```
$ unhex <<< 58312b4958557743 
X1+IXUwC

$ unhex <<< 4d702b4b636836794d6b2b7871652b5433684d6e32507876356e6d5979636775 
Mp+Kch6yMk+xqe+T3hMn2Pxv5nmYycgu
```

**Comment by magnumripper** [comment]
@tmoklc this tiny change seems to do the trick for your key file:
```diff
diff --git a/run/multibit2john.py b/run/multibit2john.py
index 583db4167..cec930d44 100755
--- a/run/multibit2john.py
+++ b/run/multibit2john.py
@@ -1359,7 +1359,7 @@ def process_file(filename):
             # return
             version = 2  # MultiBit HD possibly?
     except:
-        version = 2  # MultiBit HD possibly?
+        version = 1
 
     if version == 1:
         encrypted_data = pdata[16:48]  # two AES blocks
```
I get a whole different v1 hash than the one you posted and it doesn't have that "printable ASCII" property.

I have no idea if we should commit that change or not though.

**Comment by magnumripper** [comment]
This should be a proper patch (at least more proper than current code) but I have no v2 wallets to try with:
```diff
diff --git a/run/multibit2john.py b/run/multibit2john.py
index 583db4167..8a91a6608 100755
--- a/run/multibit2john.py
+++ b/run/multibit2john.py
@@ -1344,22 +1344,18 @@ def process_file(filename):
                         return
             return
 
-    version = 1  # MultiBit Classic
     pdata = b"".join(data.split())
     if len(pdata) < 64:
         sys.stderr.write("%s: Short length for a MultiBit wallet file!\n" % bname)
         return
+    pdata = base64.b64decode(pdata[:64])
 
-    try:
-        pdata = base64.b64decode(pdata[:64])
-        if not pdata.startswith("Salted__"):
-            version = 2
-        if len(pdata) < 48:
-            # sys.stderr.write("%s: Short length for a MultiBit wallet file!\n" % bname)
-            # return
-            version = 2  # MultiBit HD possibly?
-    except:
+    if pdata.startswith(b"Salted__"):
+        version = 1  # MultiBit Classic
+    elif len(pdata) < 48:
         version = 2  # MultiBit HD possibly?
+    else:
+        version = 2  # MultiBit HD possibly? We need more tests!
 
     if version == 1:
         encrypted_data = pdata[16:48]  # two AES blocks
```
I believe that code would always end up with `version = 2` as it was 🙃 .  I took the negative test from v2 and turned into the positive test for v1.

Not sure what the try/catch was even supposed to protect!? And that `"Salted__"` string required a b as in `b"Salted__"` but that may be a python3 thing, what do I know. That problem was *hidden* by the try/catch...

**Comment by tmoklc** [comment]
I can confirm this works. Tested with the following hash created with the updated multibit2john.py code using a key generated from Multibit Classic:

`$multibit$1*14f003aace45719b*fd6ab98076b01563dcaf0e229f353b1fc02c1c8cc05acc137a83c35122886a01`

The password is `a` and I succesfully cracked it using simple attack.

Thank you @magnumripper

**Comment by solardiz** [comment]
Thank you, @tmoklc. Can you please add this sample (the original file, not just the script's output) via a pull request to https://github.com/openwall/john-samples?

**Comment by kost123** [comment]
This is weird, I have used this script for my .key file a few times in the past just fine.

**Comment by solardiz** [comment]
@kost123 Can you retest that the currently committed script (with the fix for this issue) still works on your .key file as well? (Assuming this is quick and easy for you.) Thanks!

Edit: oh, and to comment on my own comment above - magnum added that sample to the john-samples repo back then, so that part is done.

**Comment by kost123** [comment]
Compared both the new and old on multiple old .keys I have and they are both the same(so working)
