### ISSUE TITLE
add a LICENSE

### ISSUE THREAD

**Issue by JohnCassavetes** [openwall/john#4467]
add a license

**Comment by ghost** [comment]
There is a License badge in readme and the License file. What do you mean? Please make your point clear.

![image](https://user-images.githubusercontent.com/1702923/99660582-527b8680-2a41-11eb-9364-aa240ad1ffb2.png)

**Comment by solardiz** [comment]
I think we might want to add a `LICENSE` symlink at top level pointing to `doc/LICENSE`, or just move that file (along with `LICENSE.mpi`? or just drop that other file entirely).

GitHub appears to have special handling for top-level `LICENSE` and `README` files, displaying a link to them at top right.

**Comment by JohnCassavetes** [comment]
> I think we might want to add a `LICENSE` symlink at top level pointing to `doc/LICENSE`, or just move that file (along with `LICENSE.mpi`? or just drop that other file entirely).
> 
> GitHub appears to have special handling for top-level `LICENSE` and `README` files, displaying a link to them at top right.

Yeah!

A lot of the time, the `LICENSE` is usually shown like so
![Bootstrap](https://user-images.githubusercontent.com/66259053/99899117-4f9ac300-2cd9-11eb-8823-6512b0225322.jpg)

I was wondering if this repo could also do the same by adding it and displaying it at the top, so it will look highlighted
![john](https://user-images.githubusercontent.com/66259053/99899136-7527cc80-2cd9-11eb-8e01-0a2c59a3f0ed.jpg)

Thanks
