### ISSUE TITLE
Rule reject flag -u should not reject for --enc=raw

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4472]
doc/RULES
```
-u	reject this rule unless the rules engine is running in UTF-8 mode (with
	no internal codepage configured - see doc/ENCODINGS)
-U	reject this rule if the rules engine is running in UTF-8 mode
```
When running `-enc:raw`, the `-u` flag should *not* reject but `-U` should. It seems both of them are rejecting in that situation.

**Comment by solardiz** [comment]
Shouldn't `-enc=raw` mean no specific character encoding mode, so neither flag rejects? It certainly feels counter-intuitive to me that a flag documented to reject "in UTF-8 mode" would do so in raw mode.

**Comment by magnumripper** [comment]
I force-pushed some fixes to the docs while you wrote that :-)
```
-u      reject this rule if an internal codepage is configured (doc/ENCODINGS)
-U      reject this rule unless an internal codepage is configured
```

**Comment by magnumripper** [comment]
We really need `-U` to reject in raw mode, because a rule like `sRЯ` wouldn't be translated to anything single-byte so the rule would fail with an error.
