### ISSUE TITLE
OpenMP autotune broken by hires timer rework

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4489]
This is to track the bug I've just described in: https://github.com/openwall/john/issues/4487#issuecomment-733172500

7c4ac6c89d77b75818fb09f0c5a3d4ab60b68212 aiming at #3991 broke OMP autotune, and we didn't notice for a year. Ouch.

**Comment by solardiz** [comment]
Should we simply revert 7c4ac6c89d77b75818fb09f0c5a3d4ab60b68212 or should we implement other changes required to match that commit?

**Comment by magnumripper** [comment]
Ouch. I recall I planned a lot more work with the shared timer code, but it faded away. I'll try to revisit this ASAP.
