### ISSUE TITLE
Telegram-opencl segfault

### ISSUE THREAD

**Issue by ghost** [openwall/john#4504]
Upstream Travis CI tests are failing now:

https://travis-ci.org/github/claudioandre-br/JohnTheRipper/jobs/747623883
https://travis-ci.org/github/claudioandre-br/JohnTheRipper/jobs/747623884

In short, I'm testing:

Commits on Nov 29, 2020
@davidegirardi
Add support for RACF RVARY command password hashes (openwall#4494)
9dc3333
Commits on Dec 01, 2020
@magnumripper
@solardiz
Telegram CPU format: Support Telegram Desktop >= 2.2.0 …
237ad40
@magnumripper
@solardiz
EditorConfig setting for 7z2john.pl
4dcd90c
@magnumripper
@solardiz
7z2john.pl: Avoid crash when a stream has "no methods"
0edb2c0
Commits on Dec 03, 2020
@magnumripper
@solardiz
Refactor "encoding" ASCII -> ENC_RAW, because that's how it's used …
e2381b7
@magnumripper
@solardiz
Improve handling of UTF-8 rules w/ internal codepage …
741e5ad
@magnumripper
@solardiz
Bugfix for -8 rule reject flag. …
1c7e792
@magnumripper
@solardiz
Mask mode: Improve handling of UTF-8 vs. internal codepage …
338aa98
@mm4rks
@solardiz
fix quotes and brackets in zsh autocomplete file

**Comment by magnumripper** [comment]
Wow, a segfault... what did I do now.

**Comment by magnumripper** [comment]
Our HPC thingy apparently committed suicide when testing on RX Vega

**Comment by magnumripper** [comment]
Up again. Trying the other devices, dev=2 (Intel OpenCL 1.2) segfaulted. Cancelled the MIC after a couple minutes of nothing. All nvidia cards errored with "OpenCL CL_OUT_OF_RESOURCES (-5) error in opencl_telegram_fmt_plug.c:305 - Copy result back"

I seem to have a bad hair day. The telegram-opencl format almost wasn't touched in that commit!

**Comment by magnumripper** [comment]
OK, here a thing that seems to have fallen off that commit
```diff
diff --git a/run/opencl/telegram_kernel.cl b/run/opencl/telegram_kernel.cl
index ef4df1d6f..391568a5e 100644
--- a/run/opencl/telegram_kernel.cl
+++ b/run/opencl/telegram_kernel.cl
@@ -15,6 +15,7 @@ typedef struct {
 
 typedef struct {
 	pbkdf2_salt pbkdf2;
+	uint32_t version;
 	int encrypted_blob_length;
 	uchar encrypted_blob[ENCRYPTED_BLOB_LEN];
 } telegram_salt;
```
Not sure how it could pass bots?!

**Comment by magnumripper** [comment]
> OK, here a thing that seems to have fallen off that commit
> 
> ```diff
> diff --git a/run/opencl/telegram_kernel.cl b/run/opencl/telegram_kernel.cl
> index ef4df1d6f..391568a5e 100644
> --- a/run/opencl/telegram_kernel.cl
> +++ b/run/opencl/telegram_kernel.cl
> @@ -15,6 +15,7 @@ typedef struct {
>  
>  typedef struct {
>  	pbkdf2_salt pbkdf2;
> +	uint32_t version;
>  	int encrypted_blob_length;
>  	uchar encrypted_blob[ENCRYPTED_BLOB_LEN];
>  } telegram_salt;
> ```
> 
> Not sure how it could pass bots?!

**Comment by magnumripper** [comment]
With that fixed, it still fails on every single device I've tried so far (but doesn't segfault).

Going back to `237ad4095^` everything's dandy. My bad - I just need to understand what the heck I did??

**Comment by solardiz** [comment]
You try to exclude the version 2 test vectors from the OpenCL format by:

```c
#define OPENCL_FORMAT
#include "telegram_common.h"
```

but they're actually defined in `telegram_common_plug.c`, which is compiled just once for both formats.

**Comment by solardiz** [comment]
> ```diff
>  typedef struct {
>  	pbkdf2_salt pbkdf2;
> +	uint32_t version;
>  	int encrypted_blob_length;
>  	uchar encrypted_blob[ENCRYPTED_BLOB_LEN];
>  } telegram_salt;
> ```

I suggest that instead you simply drop the `version` field from `telegram_salt` on host. You currently leave it uninitialized anyway (you'd do that in `opencl_telegram_fmt_plug.c: set_salt()`, but rather than fix that I think it's cleaner not to have the field until we need it).

Also, I suggest that you fix `encrypted_blob_length` to be `uint32_t` just like it is on host.

**Comment by ghost** [comment]
> Not sure how it could pass bots?!

There are no bots testing for OpenCL.

**Comment by solardiz** [comment]
> There are no bots testing for OpenCL.

I've just submitted a support request with Travis CI asking for an "OSS allotment" as they had advised in https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Without that, under the new billing they only gave us 10k credits once (just once, not any number of credits per month), and those ran out in mid-November.
