### ISSUE TITLE
No zip2john

### ISSUE THREAD

**Issue by piotrdylag** [openwall/john#4506]
Hi,

I don't see zip2john file in run folder. How I can run this? In src I see zip2john.c. So how I can run this?

**Comment by solardiz** [comment]
Hi @piotrdylag. Obviously, when you obtain JtR in source code form, you need to build it before you can use it. Until you do, you don't have not only `zip2john` and such, but also the main `john` program. We have some `doc/INSTALL*` files giving build instructions, but in general the usual `./configure && make -sj4` or such (when in the `src` directory) works for our project.

Our use of GitHub is for development issues that we need to track and work on. It isn't for user support. In case you have any more user support questions, please use the john-users mailing list for those. Thanks.

**Comment by piotrdylag** [comment]
That works. Thanks
