### ISSUE TITLE
--mkpc doesn't affect log message

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4511]
While testing my changes in #4507, I discovered that while setting a low `--mkpc` reduces speed as expected, the log file message doesn't change. I think that's a bug. Indeed, the code logging that message does not consider this setting:

```c
static void john_log_format2(void)
{
        int min_chunk, chunk;

        /* Messages require extra info not available in john_log_format().
                These are delayed until mask_init(), fmt_reset() */
        chunk = min_chunk = database.format->params.max_keys_per_crypt;
        if (options.flags & (FLG_SINGLE_CHK | FLG_BATCH_CHK) &&
            chunk < SINGLE_HASH_MIN)
                        chunk = SINGLE_HASH_MIN;
        if (chunk > 1)
                log_event("- Candidate passwords %s be buffered and "
                        "tried in chunks of %d",
                        min_chunk > 1 ? "will" : "may",
                        chunk);
}
```

(BTW, we should also add braces around the bitwise AND expression.)

Looking for uses of `options.force_maxkeys`, I notice that we dare to patch `min_keys_per_crypt` to be no higher than that setting if necessary. This leaves me wondering why we don't simply patch `max_keys_per_crypt` in the same place and in the same way. That would be so much simpler and more efficient than having to check `options.force_maxkeys` separately in many other places. Maybe that's the best fix for this issue as well. Would a change of  `max_keys_per_crypt` expose peculiarities of formats and maybe autotune that a change to `min_keys_per_crypt` does not?

**Comment by magnumripper** [comment]
I guess you are right, and that the current code is a result of fixes applied to bodges.

**Comment by solardiz** [comment]
> Would a change of `max_keys_per_crypt` expose peculiarities of formats

Actually, it did - see #1167 and 0a87a0a818b4e1239e8306fa7e025bc1b2fc2076.
