### ISSUE TITLE
Replace --fix-state-delay option with cracker logic

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4519]
I'd like to revisit this. The tests made in #1955 were bogus in several ways (I can elaborate on how, if it's not obvious. There are loads of foot-guns in such benchmarks). I simply can't fathom how the overhead given by the `--fix-state-delay` option would ever in any case be amortized by the alleged win.

`ftell()`, no matter how stupidly implemented, can't be anything other than dereferencing a pointer (at least with non-medieval storage media: It's not I/O for sure - how the heck would your storage know where you were at and where would it store that?!). Right? So our code for avoiding that call to `ftell` **adds** a pointer, increments of it and tests of it - all that for avoiding simply dereferencing the first pointer. I can't believe that can ever render in a real-life boost. If I'm wrong, please explain it to me.

Also, I'm sure (for many reasons apart from just gut feeling) no-one actually uses the option. That means the overhead added by it (be it tiny) is always hurting.

The least we should do is move the code away from all normal code paths (nowadays we'll almost always using memory map and/or memory buffer/indexing), and while at it we should forbid the option to be used without `-wordlist` because it's otherwise rightously ignored. I forgot doing so in my recent review of mutually exclusive options.

In case I'm all wrong and skipping `fix_state()` is actually sensible at some time, I propose we do so in `cracker`, and skip it if our last call to it was eg. no more than `timer_save_interval / 10` ago. (or something such - maybe even `/ 2`).

**Comment by solardiz** [comment]
> The tests made in #1955 were bogus in several ways (I can elaborate on how, if it's not obvious

It is unclear from what @jfoug posted there whether the wordlist was possibly being read from disk the first time but got cached the second time, but I'd expect Jim to know such things and have run the first benchmark a few times before posting.

> `ftell()`, no matter how stupidly implemented, can't be anything other than dereferencing a pointer

Hopefully so, but even then unless it's a macro it's call into a relocatable shared library, which involves some overhead.

I think it does make sense for us to minimize the frequency of `ftell()` calls if we can do so easily and with little overhead, and to do so unconditionally (at least in builds that supposedly benefit from it), not require an obscure command-line options that no one except for @jfoug would know/recall exists.

**Comment by solardiz** [comment]
> `ftell()`, no matter how stupidly implemented, can't be anything other than dereferencing a pointer

Well, there's certainly more than that in Cygwin's/newlib's. There's locking, call into underlying `->seek()`, support for `ungetc()`. _Hopefully_, the linefeed conversions are not in `->seek()`, but I didn't look in there.

**Comment by magnumripper** [comment]
Seeing my old comment that this actually made sense for macOS before some commit, I'm trying to reproduce that and profile it.

**Comment by magnumripper** [comment]
OK, apparently a macOS call to `ftell` take just below 500 ns (although I had to disable mmap and index buffer to make it happen) which is somewhat crappy. Given how Microsoft seem focused to always perform worst I can extrapolate that Windows probably need a few microseconds to do the same.

Anything but the `ftell` was in the order of 20 ns.

I will experiment with some automagic stuff that deprecates the option yet does the trick anyway. Is `timer_save_interval / 2` sensible or what should I aim at?

**Comment by magnumripper** [comment]
> Is timer_save_interval / 2 sensible or what should I aim at?

I believe using a moderate `timer_save_interval / 10` should be plenty enough (diminishing return).

Some benchmarks: Tests on macOS, which apparently also has a ridiculously slow `ftell()` although it's normally hidden by other features of wordlist, and by a larger KPC.

test.in is a single bogus NT hash, test.lst is 200 MB (~2.1M lines) wordlist already cached in FS.

### Crippled conditions (no mmap, no memory buffer, -mkpc=1)

#### Current code, w/o Jim's option:
```
$ ../run/john test.in -form:nt -w:test.lst -ru -mem-file-size=1 -mkpc=1
0g 0:00:07:58 DONE (2020-12-11 16:56) 0g/s 569373p/s 569373c/s 569373C/s Cbcbishopping
```

#### As above plus using the old option with Jim's recommended setting:
```
$ ../run/john test.in -form:nt -w:test.lst -ru -mem-file-size=1 -mkpc=1 -fix-state-delay=50
0g 0:00:02:14 DONE (2020-12-11 16:47) 0g/s 2022Kp/s 2022Kc/s 2022KC/s Cbcbishopping
```

#### As above but using a higher setting:
```
$ ../run/john test.in -form:nt -w:test.lst -ru -mem-file-size=1 -mkpc=1 -fix-state-delay=10000
0g 0:00:02:09 DONE (2020-12-11 16:45) 0g/s 2097Kp/s 2097Kc/s 2097KC/s Cbcbishopping
```

#### New code in cracker (and the wordlist code dropped):
```
$ ../run/john test.in -form:nt -w:test.lst -ru -mem-file-size=1 -mkpc=1
0g 0:00:01:27 DONE (2020-12-11 16:41) 0g/s 3102Kp/s 3102Kc/s 3102KC/s Cbcbishopping
```

### Normal conditions (mem-map + indexing & higher KPC)

### Current code, w/o Jim's option:
```
$ ../run/john test.in -form:nt -w:test.lst -ru
0g 0:00:00:46 DONE (2020-12-11 16:20) 0g/s 5854Kp/s 5854Kc/s 5854KC/s Cerberusdroolsing..Cbcbishopping
```

#### Using the old option with a high setting (slower!?):
```
$ ../run/john test.in -form:nt -w:test.lst -ru --fix-state-delay=10000
0g 0:00:00:47 DONE (2020-12-11 16:22) 0g/s 5770Kp/s 5770Kc/s 5770KC/s Cerberusdroolsing..Cbcbishopping
```

#### New code in cracker:
```
$ ../run/john test.in -form:nt -w:test.lst -ru
0g 0:00:00:45 DONE (2020-12-11 16:36) 0g/s 5979Kp/s 5979Kc/s 5979KC/s Cerberusdroolsing..Cbcbishopping
```

### Using some other "typical" mode not using fseek():

#### Before:
```
$ ../run/john test.in -form:nt -max-run=60 -inc
0g 0:00:01:00  0g/s 48319Kp/s 48319Kc/s 48319KC/s tridlm17..tridll24
0g 0:00:01:00  0g/s 48557Kp/s 48557Kc/s 48557KC/s d4qr0..dziv6
0g 0:00:01:00  0g/s 48627Kp/s 48627Kc/s 48627KC/s milf2go..miltshi
```

#### After (sTimer_GetNano as a function):
```
$ ../run/john test.in -form:nt -max-run=60 -inc
0g 0:00:01:00  0g/s 48961Kp/s 48961Kc/s 48961KC/s redlo3a..redlk5.
0g 0:00:01:00  0g/s 49507Kp/s 49507Kc/s 49507KC/s bbvg6r..bbv7hv
0g 0:00:01:00  0g/s 48583Kp/s 48583Kc/s 48583KC/s KJ9vn..marict2
```

#### After (sTimer_GetNano as a macro):
```
$ ../run/john test.in -form:nt -max-run=60 -inc
0g 0:00:01:00  0g/s 48368Kp/s 48368Kc/s 48368KC/s 2297bb1!..2297b2an
0g 0:00:01:00  0g/s 49326Kp/s 49326Kc/s 49326KC/s n1ck6lp..n1camcc
0g 0:00:01:00  0g/s 50392Kp/s 50392Kc/s 50392KC/s KJZ5n..09322002306
```

### Conclusions
OK, that `--fix-state-delay` option was apparently great - provided you somehow ended up using a format lacking SIMD and/or having a "too low" KPC, an OS not supporting mmap and for some reason (eg. file too large) not even getting the other memory buffer.

With this timer thingy in cracker, we seem to get all the benefits without any extra option - and I can't really see any regression.

**Comment by magnumripper** [comment]
Here's the experimental patch (just the cracker part of it).
```c
diff --git a/src/cracker.c b/src/cracker.c
index c7a9886a6..abcdebc3b 100644
--- a/src/cracker.c
+++ b/src/cracker.c
@@ -67,6 +67,7 @@
 #endif
 #include "rules.h"
 #include "tty.h"
+#include "timer.h"
 
 #ifdef index
 #undef index
@@ -90,6 +91,8 @@ static struct db_keys *crk_guesses;
 static uint64_t *crk_timestamps;
 static char crk_stdout_key[PLAINTEXT_BUFFER_SIZE];
 static int kpc_warn, kpc_warn_limit, single_running;
+static sTimer crk_timer;
+static uint64_t fix_state_delay, last_fixed, last_hybrid_fixed;
 
 int crk_stacked_rule_count = 1;
 rule_stack crk_rule_stack;
@@ -162,6 +165,14 @@ void crk_init(struct db_main *db, void (*fix_state)(void),
 	char *where;
 	size_t size;
 
+	/* Don't call fix_state() more often than 1/10 of save interval */
+	sTimer_Init(&crk_timer);
+	sTimer_Start(&crk_timer, 1);
+	fix_state_delay = cfg_get_int(SECTION_OPTIONS, NULL, "Save");
+	if (fix_state_delay < 0)
+		fix_state_delay = TIMER_SAVE_DELAY;
+	fix_state_delay *= 1000000000;
+	fix_state_delay /= 10;
 /*
  * We should have already called fmt_self_test() from john.c.  This redundant
  * self-test is only to catch some more obscure bugs in debugging builds (it
@@ -815,8 +826,10 @@ static int crk_password_loop(struct db_salt *salt)
 	if (event_pending && crk_process_event())
 		return -1;
 
-	if (fp_fix_state)
+	if (fp_fix_state && sTimer_GetNano(&crk_timer) - last_hybrid_fixed > fix_state_delay) {
+		last_hybrid_fixed = sTimer_GetNano(&crk_timer);
 		fp_fix_state();
+	}
 
 	if (kpc_warn_limit && crk_key_index < kpc_warn) {
 		static int last_warn_kpc, initial_value;
@@ -1060,10 +1073,14 @@ static int crk_salt_loop(void)
 	crk_process_key_max_keys = 0; /* use slow path next time */
 	crk_key_index = 0;
 	crk_last_salt = NULL;
-	if (options.flags & FLG_MASK_STACKED)
-		mask_fix_state();
-	else
-	crk_fix_state();
+
+	if (sTimer_GetNano(&crk_timer) - last_fixed > fix_state_delay) {
+		last_fixed = sTimer_GetNano(&crk_timer);
+		if (options.flags & FLG_MASK_STACKED)
+			mask_fix_state();
+		else
+			crk_fix_state();
+	}
 
 	if (ext_abort)
 		event_abort = 1;
@@ -1149,10 +1166,13 @@ static int process_key(char *key)
 			event_abort = event_pending = 1;
 	}
 
-	if (options.flags & FLG_MASK_STACKED)
-		mask_fix_state();
-	else
-	crk_fix_state();
+	if (sTimer_GetNano(&crk_timer) - last_fixed > fix_state_delay) {
+		last_fixed = sTimer_GetNano(&crk_timer);
+		if (options.flags & FLG_MASK_STACKED)
+			mask_fix_state();
+		else
+			crk_fix_state();
+	}
 
 	if (ext_abort)
 		event_abort = 1;
```

**Comment by ghost** [comment]
> OK, that --fix-state-delay option was apparently great 

I would say a test on Windows will be interesting. I bet Jim run his tests using it.

**Comment by magnumripper** [comment]
> > OK, that --fix-state-delay option was apparently great
> 
> I would say a test on Windows will be interesting. I bet Jim run his tests using it.

I believe Windows builds have mmap though, even in Jim's special VC builds - and NT should have a KPC of 192 or so. I can't really understand how he ended up with such poor figures without disabling stuff like I did above in the "Crippled conditions" tests. Perhaps Windows store the file position in the cloud? 🤣

**Comment by solardiz** [comment]
@magnumripper What's in `sTimer_GetNano()`? We don't appear to have it yet, do we? I'm concerned it might be slower than some modes' `fix_state()` on some systems. It can become a problem similar to the original one with `ftell()`.

**Comment by solardiz** [comment]
BTW, see how `idle_yield()` avoids calling `times()` too often. Maybe something similar could be done here.

**Comment by magnumripper** [comment]
> @magnumripper What's in `sTimer_GetNano()`? We don't appear to have it yet, do we? I'm concerned it might be slower than some modes' `fix_state()` on some systems. It can become a problem similar to the original one with `ftell()`.

For these tests it was nearly identical to `sTimer_GetSecs` although using/returning `uint64_t` throughout, for nanoseconds instead of `double` for seconds. I'd like to simplify it but that requires some compatibility research. Jim's original code was dubbed "Portable hi-res timer" IIRC and I'd like not to break that although some of the fallbacks might be overkill?

Anyway for this use in cracker a lower resolution would do perfectly fine, such as `gettimeofday()` but that one isn't monotonic so in obscure cases it could bite us. I'll experiment a little with something akin to what `idle_yield()` does.

**Comment by magnumripper** [comment]
> but that one isn't monotonic so in obscure cases it could bite us

Perhaps just capping the values, such as `microsecs & 0x3fff` would be good enough for tackling that in this application? (Edit: not 0x3fff but some sane figure and ensuring fixed_state_delay is never too large for it)

**Comment by magnumripper** [comment]
Apparently POSIX obsoleted `gettimeofday` and recommends `clock_gettime` but anyway my point was to just use something sane without too much fallbacks (except perhaps with clever macros).

**Comment by solardiz** [comment]
Thinking of this some more, I really don't like having this in the shared cracker code and calling any system-provided timer function there. Most modes have fast `fix_state()`, so it's cheap enough and safer to just call it.

That said, out of the timer functions I still like `times()` best. It's portable and monotonic and provides sufficient precision for most of our uses (typically about 10ms). A drawback is it isn't commonly optimized to avoid a syscall, unlike `gettimeofday()` (which we should definitely avoid) and `clock_gettime()` (which is great, but less portable), so only use it where we can guarantee we call it infrequently - but we should do that for all of these functions anyway, or we'd have the `ftell()` kind of issue again (fast on some systems, slow on others). I don't mind using `clock_gettime()` in our shared timer code, though - perhaps with fallback to `times()`.

**Comment by magnumripper** [comment]
How about just this:
```diff
diff --git a/src/signals.c b/src/signals.c
index 7344c215a..d681d6044 100644
--- a/src/signals.c
+++ b/src/signals.c
@@ -58,6 +58,7 @@ volatile int event_pending = 0, event_reload = 0;
 volatile int event_abort = 0, event_save = 0, event_status = 0, event_delayed_status = 0;
 volatile int event_ticksafety = 0;
 volatile int event_mpiprobe = 0, event_poll_files = 0;
+volatile int event_fix_state = 0;
 
 volatile int timer_abort = 0, timer_status = 0;
 static int timer_save_interval;
@@ -336,6 +337,8 @@ static void sig_handle_timer(int signum)
 		sig_install(sig_handle_reload, SIGUSR2);
 #endif
 	}
+	if (event_fix_state)
+		event_fix_state--;
 	if (!--timer_save_value) {
 		event_save = event_pending = 1;
 		event_reload = options.reload_at_save;
diff --git a/src/signals.h b/src/signals.h
index 964130355..1d9f5f9ff 100644
--- a/src/signals.h
+++ b/src/signals.h
@@ -37,6 +37,7 @@ extern volatile int event_save;		/* Save the crash recovery file */
 extern volatile int event_status;	/* Status display requested */
 extern volatile int event_delayed_status;	/* Status display requested after current batch */
 extern volatile int event_ticksafety;	/* System time in ticks may overflow */
+extern volatile int event_fix_state;    /* For cracker */
 #ifdef HAVE_MPI
 extern volatile int event_mpiprobe;	/* MPI probe for messages requested */
 #endif
```

And basically just this in cracker.c (first part is in `crk_init`):
```c
	/* Don't call fix_state() more often than 1/10 of save interval */
	fix_state_delay = cfg_get_int(SECTION_OPTIONS, NULL, "Save");
	if (fix_state_delay < 0)
		fix_state_delay = TIMER_SAVE_DELAY;
	if (options.max_run_time && abs(options.max_run_time) < fix_state_delay)
		fix_state_delay = abs(options.max_run_time);
	fix_state_delay /= 10; /* May end up as 0, which is fine */

(...)

	if (!event_fix_state) {
		if (options.flags & FLG_MASK_STACKED)
			mask_fix_state();
		else if (crk_fix_state)
			crk_fix_state();
		event_fix_state = fix_state_delay;
	}
```
This adds virtually nothing to cracker.

Edit: It should probably be renamed `event_fix_state_countdown` or something, better describing it's characteristic.

**Comment by solardiz** [comment]
I think this `event_fix_state` approach is the right one.

Nitpick: we may `event_fix_state_countdown--;` unconditionally and check for `<= 0` in cracker, which is one instruction anyway. This saves the extra read of this volatile variable in the signal handler.

... In fact, I think we don't need to calculate `fix_state_delay` and to have the countdown: we can simply be calling `fix_state()` once per second. For this, we simply need to set `event_fix_state` on every timer signal, and check for it and reset it in cracker.
