### ISSUE TITLE
Confusing encodings error message

### ISSUE THREAD

**Issue by ghost** [openwall/john#4521]
```
$ ../run/john --stdout --mask='ab[ö,¿|\?,e|¡,!]' --internal-codepage=claudio
Invalid encoding 'claudio'. Supported encodings:
ASCII (or RAW), UTF-8, ISO-8859-1 (or Latin1 or ANSI),
ISO-8859-2, ISO-8859-7, ISO-8859-15, KOI8-R,
CP437, CP720, CP737, CP850, CP852, CP858, CP866, CP868,
CP1250, CP1251, CP1252, CP1253, CP1254, CP1255, CP1256
```
```
$ ../run/john --stdout --mask='ab[ö,¿|\?,e|¡,!]' --internal-codepage=UTF-8
Error: Mask contains UTF-8 characters; --internal-codepage is required!
```
I guess UTF-8 can be used only in some encoding options. Anyway, that is confusing for me, at least. Can we improve the message about supported encodings?

**Comment by magnumripper** [comment]
UTF-8 is an encoding but not a codepage. All the other supported encodings are also codepages (well, except ASCII/raw) and can be used with `--internal-codepage` to support non-ASCII characters.

In a similar message, we say eg. "Error: Can't use ?L placeholder without setting an 8-bit legacy codepage with --internal-codepage (UTF-8 is not a codepage)." Is that better?

**Comment by ghost** [comment]
Yes, It is better.
