### ISSUE TITLE
Weird reporting of formats "passed self-tests" vs. "benchmarked"

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4536]
I was surprised by this discrepancy:

```
$ ../run/john -test=0 -form=lm,nt
Will run 64 OpenMP threads
Testing: LM [DES 64/64]... (64xOMP) PASS
Testing: NT [MD4 32/64]... PASS
All 2 formats passed self-tests!
$ ../run/john -test-full=0 -form=lm,nt
Will run 64 OpenMP threads
Testing: LM [DES 64/64]... (64xOMP) PASS
Testing: NT [MD4 32/64]... PASS
2 formats benchmarked.
```

Perhaps it shouldn't be "benchmarked" in the latter case. I went to look at the code, and it looks even worse to me there:

```c
#ifndef BENCH_BUILD
                        if (options.flags & FLG_MASK_CHK)
                                printf("%u formats benchmarked.\n", total);
                        else
#endif

#ifdef HAVE_OPENCL
/*
 * Allow OpenCL build's "--test" to run on no-OpenCL systems.
 * Print a message about no OpenCL at the end of the run.
 */
                                if (opencl_unavailable)
                                        opencl_was_skipped = " (OpenCL formats skipped)";
#endif

                                printf("All %u formats passed self-tests!%s\n",
                                       total, opencl_was_skipped);
```

The last `printf` above is part of `else` branch in non-OpenCL builds, but with OpenCL it's on its own. Perhaps that's unintentional and also wrong.

**Comment by ghost** [comment]
> The last printf above is part of else branch in non-OpenCL builds, but with OpenCL it's on its own. Perhaps that's unintentional and also wrong.

Maybe I'm missing something, but this seems correct. BTW: do you mean `else` or `#else`?:
* printf is after the `#endif` in OpenCL builds; so, it targets non-OpenCL and OpenCL builds;

The final status says: 
* All Ok "" (blank) if non-OpenCL
* All Ok "" (blank) if OpenCL and all is ok.
* All Ok "some formats skipped" if OpenCL and no OpenCL devices was found.

**Comment by ShadoW7452** [comment]
Halo.. how to install john and use john on termux

**Comment by solardiz** [comment]
@ShadoW7452 We do not provide user support via GitHub, especially not in response to off-topic comments posted to unrelated issues. There's the john-users mailing list, which you can join and post to.

I'll delete both your comment and my reply comment shortly, as they're off-topic here.

**Comment by solardiz** [comment]
@claudioandre-br I mean `else`. I find it weird that the "All ... formats passed self-tests" line would be printed only if non-mask in non-OpenCL builds, but unconditionally in OpenCL builds. I think this discrepancy is unintentional.

**Comment by magnumripper** [comment]
I believe it's an artefact from when OpenCL `-test -mask` would silently (?) skip the self-tests.
