### ISSUE TITLE
Restic issues

### ISSUE THREAD

**Issue by ghost** [openwall/john#4537]
I will amend when/if I get more errors.

* MacOS + clang (upstream Travis CI).
```
poly1305-donna.c:18:6: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if (HAS_SIZEOF_INT128_64BIT || HAS_MSVC_64BIT || HAS_GCC_4_4_64BIT)
     ^
poly1305-donna.c:14:34: note: expanded from macro 'HAS_SIZEOF_INT128_64BIT'
#define HAS_SIZEOF_INT128_64BIT (defined(__SIZEOF_INT128__) && defined(__LP64__))
                                 ^
poly1305-donna.c:18:6: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
poly1305-donna.c:14:64: note: expanded from macro 'HAS_SIZEOF_INT128_64BIT'
#define HAS_SIZEOF_INT128_64BIT (defined(__SIZEOF_INT128__) && defined(__LP64__))
                                                               ^
poly1305-donna.c:18:33: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if (HAS_SIZEOF_INT128_64BIT || HAS_MSVC_64BIT || HAS_GCC_4_4_64BIT)
                                ^
poly1305-donna.c:15:25: note: expanded from macro 'HAS_MSVC_64BIT'
#define HAS_MSVC_64BIT (defined(_MSC_VER) && defined(_M_X64))
                        ^
poly1305-donna.c:18:33: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
poly1305-donna.c:15:46: note: expanded from macro 'HAS_MSVC_64BIT'
#define HAS_MSVC_64BIT (defined(_MSC_VER) && defined(_M_X64))
                                             ^
poly1305-donna.c:18:51: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if (HAS_SIZEOF_INT128_64BIT || HAS_MSVC_64BIT || HAS_GCC_4_4_64BIT)
                                                  ^
poly1305-donna.c:16:28: note: expanded from macro 'HAS_GCC_4_4_64BIT'
#define HAS_GCC_4_4_64BIT (defined(__GNUC__) && defined(__LP64__) && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 4))))
                           ^
poly1305-donna.c:18:51: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
poly1305-donna.c:16:49: note: expanded from macro 'HAS_GCC_4_4_64BIT'
#define HAS_GCC_4_4_64BIT (defined(__GNUC__) && defined(__LP64__) && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 4))))
                                                ^
6 errors generated.
make[2]: *** [poly1305-donna.o] Error 1
make[1]: *** [poly1305-donna/poly1305-donna.a] Error 2
make[1]: *** Waiting for unfinished jobs....
```

* Linux + clang
```
poly1305-donna.c:18:6: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if (HAS_SIZEOF_INT128_64BIT || HAS_MSVC_64BIT || HAS_GCC_4_4_64BIT)
     ^
poly1305-donna.c:14:34: note: expanded from macro 'HAS_SIZEOF_INT128_64BIT'
#define HAS_SIZEOF_INT128_64BIT (defined(__SIZEOF_INT128__) && defined(__LP64__))
                                 ^
poly1305-donna.c:18:6: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
poly1305-donna.c:14:64: note: expanded from macro 'HAS_SIZEOF_INT128_64BIT'
#define HAS_SIZEOF_INT128_64BIT (defined(__SIZEOF_INT128__) && defined(__LP64__))
                                                               ^
poly1305-donna.c:18:33: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if (HAS_SIZEOF_INT128_64BIT || HAS_MSVC_64BIT || HAS_GCC_4_4_64BIT)
                                ^
poly1305-donna.c:15:25: note: expanded from macro 'HAS_MSVC_64BIT'
#define HAS_MSVC_64BIT (defined(_MSC_VER) && defined(_M_X64))
                        ^
poly1305-donna.c:18:33: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
poly1305-donna.c:15:46: note: expanded from macro 'HAS_MSVC_64BIT'
#define HAS_MSVC_64BIT (defined(_MSC_VER) && defined(_M_X64))
                                             ^
poly1305-donna.c:18:51: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
#if (HAS_SIZEOF_INT128_64BIT || HAS_MSVC_64BIT || HAS_GCC_4_4_64BIT)
                                                  ^
poly1305-donna.c:16:28: note: expanded from macro 'HAS_GCC_4_4_64BIT'
#define HAS_GCC_4_4_64BIT (defined(__GNUC__) && defined(__LP64__) && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 4))))
                           ^
poly1305-donna.c:18:51: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
poly1305-donna.c:16:49: note: expanded from macro 'HAS_GCC_4_4_64BIT'
#define HAS_GCC_4_4_64BIT (defined(__GNUC__) && defined(__LP64__) && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 4))))
                                                ^
6 errors generated.
Makefile:21: recipe for target 'poly1305-donna.o' failed
make[2]: *** [poly1305-donna.o] Error 1
Makefile:1435: recipe for target 'poly1305-donna/poly1305-donna.a' failed
make[1]: *** [poly1305-donna/poly1305-donna.a] Error 2
make[1]: *** Waiting for unfinished jobs....
ar: creating aes.a
ar: creating secp256k1.a
ar: creating ed25519-donna.a
Makefile:189: recipe for target 'default' failed
make: *** [default] Error 2
```
SIMD nothing better than AVX (?) (seems it is).
```
Testing: restic, Restic Repository [scrypt Salsa20/8 128/128 AVX, Poly1305]... (2xOMP) PASS
```
BSD
```
Fails (it is also clang)
```

**Comment by solardiz** [comment]
@juergenhoetzel You want to take a look?

@claudioandre-br Thank you! Still no luck with Travis CI for the org - their cheapest plan is $69/month + separate purchase of macOS credits, and it's worse than what we had before (limited to 1 job at a time, and during signup for that plan there's some scary mention of being also charged per actual user count at the end of each month), and they haven't replied to my suggestion that we'd simply buy some credits while they figure out their continued Open Source support or not. I am considering switching to that paid plan for a month - we kind of owe them for all they had provided free of charge to Open Source projects including ours before - then try to negotiate a reasonable plan from there, with the alternative being they lose a (would be) paying customer completely. ;-)

**Comment by ghost** [comment]
IMO
* I wouldn't put so much money on Travis. I agree they have really good infra, but ... No, it is too much money and I won't be able to, e.g., play with OpenCL. They have Windows, ARM, ..., but, again, it is not clear if we will be able to use it.

**Comment by solardiz** [comment]
Regarding these specific clang errors, could we possibly trigger them when using Circle CI? With clang on Linux?

**Comment by ghost** [comment]
> could we possibly trigger them when using Circle CI?

Since they are clang related, yes.

**Comment by solardiz** [comment]
Paid the $69, good until Feb 5. Now have 1 concurrent job and 0 credits, but can purchase 25k credits for $15. I wonder if any unused credits can stay with us upon switching back to Free plan, or if they at least give us another 10k credits with it. We'll see.

Now need to re-enable use of Travis CI for `john`. We had only left it enabled for `lkrg`.

**Comment by solardiz** [comment]
> SIMD nothing better than AVX (?) (seems it is).

Yes, can't easily and efficiently use wider than 128-bit for scrypt.

**Comment by solardiz** [comment]
I seem to have re-enabled the Travis CI integration for this repo, and merged a PR, but somehow this didn't trigger a pending build on Travis CI yet. Weird. Claudio, magnum - if you can spot any setting I missed, let me know. Thanks.

**Comment by ghost** [comment]
It seems it is not enabled yet.

![image](https://user-images.githubusercontent.com/1702923/103691265-a819dd00-4f74-11eb-9fe0-e1eac5970599.png)

**Comment by solardiz** [comment]
@claudioandre-br Where did you try to trigger that build? I don't have that "Requests" tab in there.

Anyway, please don't try to request anything yet - that may increase our user count, increasing what they'd end up charging at the end of the month on top of the monthly fee.

**Comment by ghost** [comment]
Upper right -> more options -> trigger build.

**Comment by solardiz** [comment]
OK, I have that option, but was reluctant to use it. Did now, and a build seems running. I wonder what that means in terms of user count.

I had also bought the 25k credits for $15, so maybe that helped, or maybe I was authorized to trigger this and you were not.

I still do not have the Requests tab in there, though.

**Comment by ghost** [comment]
**[edited]**
> maybe I was authorized to trigger this and you were not

No. You are the author of the rejected request seen "11 minutes ago" (in the print screen). Magnum did the request seen "26 days ago".

**Comment by solardiz** [comment]
> No. You did the rejected request seen "11 minutes ago".

I don't understand what you mean here.

**Comment by claudioandre-br** [comment]
edited previous post

**Comment by solardiz** [comment]
Maybe the lack of macOS credits prevented these previously, because our configuration does include a macOS build.

**Comment by solardiz** [comment]
Meanwhile, we already have the clang build failure in there. So Travis is back with us, for now.

**Comment by solardiz** [comment]
The macOS build failed because of the same clang issue. And cost us 100 credits.

**Comment by solardiz** [comment]
@claudioandre-br BTW, were these clang errors, or warnings promoted by us to errors with `-Werror` or such?

**Comment by ghost** [comment]
> were these clang errors, or warnings

Documentation says it is a warning, but (I mean, I like it): 
```
If a defined operator appears as the result of a macro expansion, the C standard specifies the behavior as undefined. The [...]
warning is a portability and standards compliance warning, issued because other compliant compilers may have different
behavior.
```
