### ISSUE TITLE
multiple definition of `poly1305_init'

### ISSUE THREAD

**Issue by bannsec** [openwall/john#4546]
### Steps to reproduce ###
Compile with libmusl static. I have a Dockerfile to do so here:

https://github.com/bannsec/hashcrack-jtr/blob/master/Dockerfile.linux

Looks like @solardiz changed a bunch of stuff in poly1305-donna/poly1305-donna-64.h on Jan 7 2021. Up to that point, my building Docker worked fine. However, since those changes, I'm getting an error when compiling and am unsure how to fix it.

Error:
```
/opt/cross/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: poly1305-donna/poly1305-donna.a(poly1305-donna.o): in function `poly1305_init':
/opt/JohnTheRipper/src/poly1305-donna/poly1305-donna-64.h:76: multiple definition of `poly1305_init'; /opt/cross/lib//libcrypto.a(poly1305-x86_64.o):(.text+0x0): first defined here
```

The commit that this started happening on is 4e924f2.

Not sure what to do at this point to successfully compile again.

### System configuration ###
Latest from master

**Comment by ghost** [comment]
The culprit should be f77367194ce6a1bab0e31553021270a4206350d8. 

A workaround could be rename `poly1305_init` in `src/poly1305-donna/poly1305-donna-64.h` to something like `jtr_poly1305_init` (also, rename all calls to the method inside JtR's source code).

**Comment by solardiz** [comment]
@juergenhoetzel I think we need to add near the beginning of `poly1305-donna.h`:

```c
#define poly1305_context john_poly1305_context
#define poly1305_init john_poly1305_init
#define poly1305_update john_poly1305_update
```

and so on for the remaining few functions.

**Comment by solardiz** [comment]
@bannsec @juergenhoetzel Does one of you intend to try implementing that fix I've just suggested, and send us a PR? Let's figure out who does it, so that we don't have 2 or 3 people doing duplicate work. And clearly @bannsec is the one to test if the fix addresses the original issue.

**Comment by bannsec** [comment]
Happy to test the fix, though work has me super busy rn so probably don't
have time to implement.

**Comment by juergenhoetzel** [comment]
The proposed solution is:

Change the `poly1305_` prefix to `jtr_poly1305_`? 

```C
#define poly1305_context john_poly1305_context
#define poly1305_init john_poly1305_init
#define poly1305_update john_poly1305_update
```
should not be needed if we also adapt `restic_fmt_plug.c` to the new prefix. 

I can send a PR.

**Comment by solardiz** [comment]
> Change the `poly1305_` prefix to `jtr_poly1305_`?

No, please literally add the `#define` lines I suggested and a few more like them. The added prefix would be `john_` (not `jtr_`), and no renames would be needed anywhere else - we'd keep changes from upstream code to a minimum (only some lines added, no edits to any lines) and would keep the rest of our code as-is (no changes in `restic_fmt_plug.c`). If this sounds OK to you, please implement it and send us a PR. Thanks!

**Comment by juergenhoetzel** [comment]
> No, please literally add the `#define` lines I suggested and a few more like them. The added prefix would be `john_` (not `jtr_`), and no renames would be needed anywhere else - we'd keep changes from upstream code to a minimum (only some lines added, no edits to any lines) and would keep the rest of our code as-is (no changes in `restic_fmt_plug.c`). If this sounds OK to you, please implement it and send us a PR. Thanks!

I see :+1:

**Comment by solardiz** [comment]
@bannsec We think we've fixed the issue. Can you please test and let us know whether the issue is in fact fixed for you? Thanks!

**Comment by bannsec** [comment]
Can confirm build is working again for me. Thanks all!!
