### ISSUE TITLE
Import mosquitto_passwd hashes

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4550]
@Blackfell wrote a Python script that converts `mosquitto_passwd` files to formats understood by John and hashcat. (The script can also crack hashes on its own, slower.) https://github.com/Blackfell/python_widgets/blob/main/mosquito_passwd_crack.py https://mosquitto.org/man/mosquitto_passwd-1.html

@Blackfell Thank you for writing and publishing this script! If you don't mind, I'd like to see it included in jumbo. Would you contribute this to us via a PR, please? I imagine the PR would include your Python script with a copyright statement and license comment added at top (similar to what we have in Dhiru's scripts), `doc/README-mosquitto` with content from your README's `mosquitto_passwd_crack` section, and an update to `doc/NEWS`.

Alternatively or additionally, we could enhance the JtR format to be able to parse those files/hashes directly. For the alias to `dynamic_82`, this would probably be a task for @jfoug. For the alias in `PBKDF2-HMAC-SHA512`, it's probably something many of us could do. But without clear plans on this, I think we should get the Python script in first.

Nitpick: BTW, I think it's `mosquitto` with two t's. `mosquito_passwd_crack.py` has that wrong in its name and in a couple of places instead.

**Comment by Blackfell** [comment]
Hey, I'd be more than happy to do this, I'll try and get something in over the next few days. As you said, I'll have a look at the existing scripts and neaten everything up first (good spot on typos, I like nitpicks so keep em coming 😊). Also keen to support any of the other changes, I'll keep it in mind as I read up.

**Comment by Blackfell** [comment]
I've popped a [PR](https://github.com/openwall/john/pull/4551) in with a bit of a re-hashed script. The main outstanding issue I'm having is that format auto-detection for dynamic_82 isn't working well on a Kali VM I've been using to test (surprise!). I've put more detail in the PR comments.

Note also that the original script has been renamed and (hopefully) de-typod - [https://github.com/Blackfell/python_widgets/blob/main/mosquito_passwd_crack.py](https://github.com/Blackfell/python_widgets/blob/main/mosquitto_passwd_crack.py)

**Comment by solardiz** [comment]
Fixed in #4551. Closing.
