### ISSUE TITLE
Making john XDG compliant

### ISSUE THREAD

**Issue by sawshep** [openwall/john#4552]
Right now, john will write `john.log` and `john.pot` to `~/.john`. According to [XDG](https://github.com/adrg/xdg), a more sensible location would be in `$XDG_DATA_HOME/john` (by default this is `~/.local/share/john`).
`params.h` defines `JOHN_PRIVATE_HOME` as `"~/.john"`. It would seem like a simple solution to just define it instead as `"$XDG_DATA_HOME/john"`, but the [specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) states that if `XDG_DATA_HOME` is not defined, the program should use the default.
Another issue that comes up is handling the folders when an XDG compliant version of john is run when the `~/.john` folder exists. It could copy the files to the XDG location and remove the old folder, but IMO it is easier to just use the old folder if it exists.

**Comment by solardiz** [comment]
@sawshep Thank you for bringing this up. Is there a specific context/reason for you to suggest/request this? For example, are you packaging JtR for some distro where this is encouraged or even mandated by policy?

I'd rather not have us waste time on this, creating issues out of thin air. At least not at this time. If we were to fully follow the specification, it's quite some complexity and special cases, and there are also different directory paths for macOS and Windows.

For a related higher priority issue, see #4281.

**Comment by sawshep** [comment]
@solardiz Nope, I just thought it was a general improvement that could be made. I'll close the issue.

**Comment by xambroz** [comment]
Talking about XDG I would rather say pot and log should go to ~/.local/state or even ~/.cache rather than ~/.local/share as it is not static data (to be possibly shared with somebody else) , but it is dynamic data produced by the run. Same for the possible session files. 
Local config of john.conf should probably go to .config/john/
