### ISSUE TITLE
Restic format can't be built with legacy Makefile

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4563]
#4562 fixes "generic" builds, but any legacy build still fails unless the restic format plugin is deleted. The new subdir for poly1305-donna isn't handled at all.

**Comment by magnumripper** [comment]
I do not intend to fix this (I did have a quick look and it didn't look really trivial). @juergenhoetzel introduced the problem but I don't blame him - how would he know about this weird legacy stuff?  o.O

**Comment by solardiz** [comment]
@juergenhoetzel Are you going to fix this for us, please?
