### ISSUE TITLE
Confusion around Subsets mode not testing all possible permutations

### ISSUE THREAD

**Issue by LucasGaleano** [openwall/john#4575]
Hello there!
I have a problem with the subsets, it does not create all the possible permutations, for example I use this command and the word 'abcdefgh' should appear but it does not.
I don't know if I don't understand how this feature works or if it is a bug or something, I would appreciate your help.
I used this command exactly:

`./john   --max-len:8 --subset:abcdefgh --stdout | grep 'abcdefgh'`

I tested it on the latest version on a kali and the latest version of JtR.

**Comment by magnumripper** [comment]
If you look at the log it will say "`0:00:00:00 - Lengths: 1-8, max. subset size 7`".

Try this
```
./john --max-len:8 --subset:abcdefgh --stdout --subsets-max-diff=8 | grep 'abcdefgh'
```
You can also change the `MaxDiff = 7` in `john.conf`, section `[Subsets]`, to something higher. Whatever you put there will of course be capped by your current max length anyway.

Perhaps we should set this default higher?

**Comment by solardiz** [comment]
My guess is this might be a misunderstanding of what the subsets mode is, treating it as an exhaustive search mode, which it isn't meant to be. The "sub" in its name literally means that it isn't supposed to test all characters at once, but only in smaller subsets (although as a special case it can be configured to eventually test all at once, as well).

Perhaps @LucasGaleano would actually want to use mask mode (e.g. `-2=abcdefgh -mask='?2' -max-len=8` or `-mask='[abcdefgh]' -max-len=8` or for this specific case even `-mask='[a-h]' -max-len=8`) or incremental mode.

@LucasGaleano Can you clarify whether this was the above misunderstanding on your part, or whether you think we should change the default for the Subsets mode to eventually proceed to testing all characters at once (so not a subset, and commonly running essentially "forever" until interrupted)?

**Comment by LucasGaleano** [comment]
Thanks for both answers, now it's clearer to me how the subset mode works, I didn't know that the subsets-min-diff was set to 7, I should have paid more attention or read the logs.
I normally use the mask mode but as I love this tool I wanted to try the other modes.
Regarding the question, I think it's ok that the default is set to 7.

Thanks for your time

**Comment by solardiz** [comment]
Thanks @LucasGaleano. I think there's nothing for us to do on this issue, so I'm closing it.

**Comment by magnumripper** [comment]
I think I'll add a line or two to the docs actually, making this more clear.

**Comment by solardiz** [comment]
Sounds good, @magnumripper. Thank you!
