### ISSUE TITLE
not able to decrypt error

### ISSUE THREAD

**Issue by kaal-kali** [openwall/john#4580]
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
this error is shown while typing command
zip2john --format=zip hash.txt

**Comment by ghost** [comment]
This is not an error, this is a warning. No (non-cracked) zip hashes was found inside `hash.txt`. 

In fact, I guess you used `john --format=zip hash.txt` (BTW: you can/should remove the format option and allow john detect the hash type). FAQ explains a lot of use cases where the message "No password hashes loaded" is expected.

**Comment by kaal-kali** [comment]
while john hash.txt same error show

**Comment by solardiz** [comment]
@kaal-kali You tried to use our GitHub for user support, but we don't use it like that. You're welcome to join the john-users mailing list and describe in there what you're actually trying to achieve and how, and perhaps the friendly community in there will help figure out why you're getting that error and how to avoid it. You might have created that `hash.txt` file wrongly, or with a different/incompatible version of `zip2john`, etc. There are many possibilities here. And this is john-users material, not GitHub. So please don't feel discouraged, but please use the right place for this discussion. Thank you!

**Comment by solardiz** [comment]
@kaal-kali One final comment - Claudio's advice for you to drop the `--format=zip` option is good. You'd definitely want to drop the option. I guess you're using it based on some third-party blog post or such, but that's actually bad practice, and can very well be the reason for you getting that error. So just:

```
john hash.txt
```

and that's it - no options.
