### ISSUE TITLE
Set TIMER_SAVE_DELAY to 60 seconds for consistency with default john.conf

### ISSUE THREAD

**Issue by sectroyer** [openwall/john#4583]
I think it affects any mode but here is sample command:
```john  -1=?u?d --min-len=1 --mask=?1?1?1?1?1?1?1?1 - ./tmp/sort_cameras.pwd --format=descrypt```
I think session file updates are stopped/blocked until john is stopped. If on second terminal I try to check session status I get this:
```
john --status
0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
```
Once I ctrl+c john status is displayed correctly and session restoring also works. However when I kill it with -9 It starts from the beginning. So looks session file is updated only on start and graceful quit.

[test.pwd.zip](https://github.com/openwall/john/files/6074576/test.pwd.zip)

**Comment by solardiz** [comment]
This suggests the timer isn't working. If so, I guess the status line printing on a keypress in an interactive session is also not working?

**Comment by sectroyer** [comment]
It works as a charm. Also I noticed john --status command DOES update sometimes but rarely and it never displays last status from stdout.

**Comment by solardiz** [comment]
@sectroyer Well, with default settings the updates should be once a minute. Just how rare are yours?

**Comment by sectroyer** [comment]
On other nodes it's updated every time I press enter and every time I see new info auto updated in console window. Now made a test from start and I saw an update after around 10 minutes. I have written simple script that runs john --status in a loop with 30 seconds sleep. It was started at around 11:54 and here is when output changed:

```
śr.  3 mar 2021 12:03:30 CET
1 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
2 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
3 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
4 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
5 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
6 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
7 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
8 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
9 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
10 0g 0:00:00:01  0g/s 0p/s 0c/s 0C/s
śr.  3 mar 2021 12:04:00 CET
1 0g 0:00:10:01 41,00% (ETA: 12:18:54) 0g/s 2236Kp/s 11181Kc/s 11181KC/s
2 0g 0:00:10:01 39,00% (ETA: 12:20:10) 0g/s 2114Kp/s 10570Kc/s 10570KC/s
3 0g 0:00:10:01 41,00% (ETA: 12:18:54) 0g/s 2234Kp/s 11171Kc/s 11171KC/s
4 0g 0:00:10:01 40,00% (ETA: 12:19:31) 0g/s 2201Kp/s 11009Kc/s 11009KC/s
5 0g 0:00:10:01 42,00% (ETA: 12:18:19) 0g/s 2274Kp/s 11370Kc/s 11370KC/s
6 0g 0:00:10:01 40,00% (ETA: 12:19:31) 0g/s 2162Kp/s 10810Kc/s 10810KC/s
7 0g 0:00:10:01 38,00% (ETA: 12:20:50) 0g/s 2093Kp/s 10465Kc/s 10465KC/s
8 0g 0:00:10:01 41,00% (ETA: 12:18:54) 0g/s 2259Kp/s 11299Kc/s 11299KC/s
9 0g 0:00:10:01 41,00% (ETA: 12:18:54) 0g/s 2239Kp/s 11196Kc/s 11196KC/s
10 0g 0:00:10:01 40,00% (ETA: 12:19:31) 0g/s 2186Kp/s 10933Kc/s 10933KC/s
śr.  3 mar 2021 12:04:30 CET
```

**Comment by solardiz** [comment]
Looks like the timer is off by a factor of 10. We'll need to look into that. Meanwhile, you can change `Save = 60` to `Save = 6` in `john.conf`. Does this help?

Also, are you possibly getting this warning during build (see `os.h`)? -

```c
#warning ITIMER_REAL is not available - will emulate timers
```

**Comment by solardiz** [comment]
Unrelated to the issue, but:

> --min-len=1 --mask=?1?1?1?1?1?1?1?1

FWIW, with JtR you don't have to repeat the same mask character like that to have the mask length grow (I think you do with hashcat). You can use:

`--max-len=8 --mask='?1'`

and it will repeat the last mask placeholder (in this case, the only one) as many times as necessary for the current length.

**Comment by sectroyer** [comment]
Okay I can confirm this is NOT freebsd specific issue. On one linux machine I get an  update every minute seconds whereas on other every 10 minutes. Same with jumbo1 and git head. On freebsd no such warning. Okay once I put Save=60 (now even switched to Save=30) in ~/.john/john.conf it all started to work. Let's continue the discussion about Linux machine that was behaving incorrectly. Here is info about build I have:
System-wide exec: /usr/libexec/john
```
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: AVX2
$JOHN is /etc/john/
Format interface versi
```
I have john.conf in /etc/john (with Save=60) and in ~/.john/john.conf (file was almost empty, only policy filter defined). Once I put Save=60 in ~/.john/john.conf it all started working correctly (same on freebsd) so it's this setting "ignored" when in "main" conf file ? 😄 

> FWIW, with JtR you don't have to repeat the same mask character like that to have the mask length grow (I think you do with hashcat). You can use:
> 
> `--max-len=8 --mask='?1'`
> 
> and it will repeat the last mask placeholder (in this case, the only one) as many times as necessary for the current length.

Yes I understand that I use not only for compatibility but to "visualise" for my own sake. Also usually one of those ?1 is replaced with ?u or ?s and that way it's easier to keep track on and not rethink everything each time I try something new. I just simplified this command for reporting this issue.

**Comment by solardiz** [comment]
Oh, now it's clear, and this isn't really a bug. We have the compile-time default of 600 in `params.h`. We override it to 60 in our default `john.conf`. We might want to change the compile-time default to 60 as well, for consistency. (Both were 600 in core, but jumbo changed one to 60.)

You're messing with system-wide builds. These are easier to get wrong than to get them right. I think you'd want to stop using system-wide builds. They're for packagers, not directly for end-users. Yes, it sounds like your `/etc/john/john.conf` isn't being processed - probably not only this setting, but also all others. The recommended fix is to avoid system-wide builds.

**Comment by sectroyer** [comment]
For now my setup requires john to be in PATH I might change that in the future but for now I recompiled git with system-wide set to /etc/john and it looks it's working correctly. About speed up I got up to around 145-150 MH/s with openmp but still far 300 with --fork so now trying to implement that :) However on node with 32 cores and --fork enabled I do get different status output every 30 seconds (that's what I set in john.conf) however it looks output is "lagging". I attach a screen shot. On left real time stdout on the right --status.

<img width="1142" alt="Zrzut ekranu 2021-03-3 o 15 31 47" src="https://user-images.githubusercontent.com/6706818/109820955-c844e000-7c35-11eb-9b03-499fd189d5b7.png">

My bad it was stdout that was lagging as I disabled key press functionality while switching to --status.  Sorry too much time spent on single bug and confusion arises 😄

**Comment by solardiz** [comment]
@sectroyer Can you please send us a PR fixing this issue (per its current title) - change the 600 to 60 in `params.h`? Thanks!

Trivial for anyone to do, but we'd like to gain a contributor who might send us more PRs later. ;-)

**Comment by sectroyer** [comment]
Ouch it hurt my brain :D Finally figured out you mean pull request ;) Ok will do so but first how to check up how to mirror on my github ;) And yes I hope I can help more in the future 😄 👍

**Comment by ghost** [comment]
> but first how to check up how

For patches like this, you can work 100% online (directly on your forked GitHub repo).

**Comment by sectroyer** [comment]
> For patches like this, you can work 100% online (directly on your forked GitHub repo).

Yeah, when you know where to click ;) But I think I have done it. Please check if all is ok?
