### ISSUE TITLE
Allow fork divisible node values

### ISSUE THREAD

**Issue by sectroyer** [openwall/john#4584]
I have played around with using --fork instead of openmp as @solardiz suggested and on some nodes I am getting pretty good results. Therefore I would like to implement it on my system. However I have see2, avx and avx2 nodes. As @solardiz suggested "overbooking" them does work however this bring up the issue that some of those machines I do NOT want to use all cores for john (they also have other tasks to do ;)). I understand why --node is connected with --fork and making them independent won't be an easy task. However if I am able to "overbook" --fork it should be also possible (with --fork divisible number) to "overbook" --node. I hope this would be much simpler to implement and won't require big code changes?

**Comment by solardiz** [comment]
What I was thinking is that we should allow e.g. `--fork=32 --node=200-263/333`, which would run only 32 processes yet use up 64 node numbers (each process would correspond to two virtual nodes, taking their portions of the keyspace). Is this the same as your suggestion?

**Comment by sectroyer** [comment]
Yes, that's exactly what would solve my issues. Both --node and --fork look are very powerful but strict relation between them really hurts. I don't know if adding support for virtual nodes is necessary. I think even simple "divide node numbers by two" would be a good start (and I think enough for my needs). In other words whole code path would stay the same but if number of nodes is divisible by number of forks and at the same time total number of nodes is divisible but the result of previous division (2 in our case) this john instance could simply divide all nodes by "2" and follow same code path as I think rest won't matter?

**Comment by solardiz** [comment]
@sectroyer That special case hack you describe now sounds too confusing to users. It'd introduce the notion of translated node numbers. Ouch.

**Comment by sectroyer** [comment]
> @sectroyer That special case hack you describe now sounds too confusing to users. It'd introduce the notion of translated node numbers. Ouch.

Okay I understand, I will do more tests of git head and maybe try hacking it myself just to see how it behaves :)

**Comment by solardiz** [comment]
Implemented in https://github.com/openwall/john-core, now need to merge into jumbo and retest.

**Comment by solardiz** [comment]
Thinking of this some more, with node number ranges much larger than fork count we don't have to require strict multiples. For example, with a range of 10000 nodes and 32 forks, it would be quite OK if some processes represented 312 virtual nodes and some others 313. This would require slightly different implementation - I currently implemented a fixed nodes per fork (`npf` local variable in a couple of places), which would need to be replaced with a multiply and a divide for each fork, allowing the numbers to vary. I'm not implementing this just yet, but I think it would be a fine change to make later.
