### ISSUE TITLE
--status of a --fork session fails to consider --node range found in main .rec file

### ISSUE THREAD

**Issue by sectroyer** [openwall/john#4589]
I have switched to fork in system and as a result had to scale down nodes. Now I think I have encountered another issue with --status switch. Half of the nodes have always status completed. Here is the cmd:
`OMP_NUM_THREADS=1 john --format=descrypt '-2=[opqrstuvwxyz0123456789]' -1=?l?d --min-len=1 --mask=?2?1?1?1?1?1?1?u --node=16-47/47 --fork=32 ./test.pwd --session=test`
When I remove --session and use default session instead of "completed" they simply stop showing progress. I attach relevant screenshots 
[test.pwd.zip](https://github.com/openwall/john/files/6082193/test.pwd.zip)
<img width="1263" alt="Zrzut ekranu 2021-03-4 o 09 59 47" src="https://user-images.githubusercontent.com/6706818/109939392-4bffda80-7cd1-11eb-856a-817436e607d3.png">
<img width="1272" alt="Zrzut ekranu 2021-03-4 o 09 56 31" src="https://user-images.githubusercontent.com/6706818/109939403-4efacb00-7cd1-11eb-8b19-4f2dd469c58a.png">
<img width="1261" alt="Zrzut ekranu 2021-03-4 o 10 04 33" src="https://user-images.githubusercontent.com/6706818/109939422-54581580-7cd1-11eb-961f-67cf11a68fe1.png">

**Comment by sectroyer** [comment]
I changed the title I just noticed similar issue on 10 core node:

<img width="1203" alt="Zrzut ekranu 2021-03-4 o 10 26 58" src="https://user-images.githubusercontent.com/6706818/109942199-41931000-7cd4-11eb-9c3e-0477f9bde1c9.png">

**Comment by solardiz** [comment]
At first glance, looks like an issue with mask mode's work splitting resulting in some processes given no work and actually completing right away. Not an issue limited to status reporting.

(Unrelated, instead of `OMP_NUM_THREADS=1` you could consider `./configure --disable-openmp` for slightly better speeds. Also, JtR automatically lowers its per-process OpenMP thread count, even all the way down to 1, when the number of forks increases. But it doesn't hurt to use `OMP_NUM_THREADS=1` explicitly to have it consistently regardless of number of forks.)

**Comment by solardiz** [comment]
@sectroyer Just to make sure, is this with the latest code from this repo and without any custom changes of yours? (I recall you were going to experiment with halved node numbers in a source code hack to accommodate your SSE/AVX vs. AVX2 systems, and indeed such attempts can easily cause this sort of breakage.)

**Comment by sectroyer** [comment]
@solardiz I gave up with those changes :D Also it works with bleeding edge and jumbo1. Only NON standard change I have was the "big num candidates fix" for previous node bug I reported but I think this only affects ETA?

> At first glance, looks like an issue with mask mode's work splitting resulting in some processes given no work and actually completing right away. Not an issue limited to status reporting.

But it looks like whole attack was finished. I was getting even status updates for ALL nodes in stdout just NEVER in --status.

> (Unrelated, instead of `OMP_NUM_THREADS=1` you could consider `./configure --disable-openmp` for slightly better speeds. Also, JtR automatically lowers its per-process OpenMP thread count, even all the way down to 1, when the number of forks increases. But it doesn't hurt to use `OMP_NUM_THREADS=1` explicitly to have it consistently regardless of number of forks.)

Yes I noticed that and on some nodes I was getting "Disabling openmp blah blah" message but others not so for the sake of consistency I have defined this switch. For now I prefer to have openmp as an option to use same code base on all nodes (due to node/fork issue we discussed I had to fallback to openmp on slower nodes) and switch dynamically using single binary.

**Comment by sectroyer** [comment]
Or maybe it's not... I have sent SIGUSR1 to all john pids (pressed enter few times to have clear lines before output) and I got this:
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/6706818/109952786-87090a80-7cdf-11eb-812a-ecf67b81a60f.png">
I don't see any output from nodes 1-16...

**Comment by magnumripper** [comment]
Well you are running `--node=16-47/47` so you can't expect anything from node 1-15, right?

**Comment by sectroyer** [comment]
K my bad I am constantly being confused by those "node numbers" I expect them to be fork numbers 🤦 All 32 nodes ARE reporting status so all correct here HOWEVER --status ALSO "thinks" as I do and tries to report status for nodes from 1-32 so that's why output starts at node 17 😄

**Comment by magnumripper** [comment]
Exactly. This is very confusing, I agree. Perhaps even a bug?

**Comment by sectroyer** [comment]
Confirmed the issue. I changed --node to --node=4-35/47  and EXACTLY 4 nodes are NOT displayed in output:

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/6706818/109955047-5080bf00-7ce2-11eb-8102-8d79d9e51aeb.png">

**Comment by sectroyer** [comment]
> Well you are running `--node=16-47/47` so you can't expect anything from node 1-15, right?

I am not exepcting anything from nodes 1-15 but I do from forks 1-15 which are nodes 16-32 in --status output but nowhere is output from forks 16-32 which are nodes 33-47 😄

**Comment by solardiz** [comment]
So it looks like the problem is `--status` doesn't consider a `--node` option found in the master `.rec` file. Does `--restore` of such a session still work correctly, though?

**Comment by sectroyer** [comment]
Well I assume it does. I stopped a session and looks it continued tough is internally "everything ok" no idea 😄 But you should be able to reproduce the issue with provided command, looks it's nothing specific to my setup :)
Okay noticed one issue with restored session. Both in --status and stdout ETA stops working:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/6706818/109964485-0b628a00-7cee-11eb-8512-b46c3fffd785.png">

**Comment by ghost** [comment]
I see a bug here.
* A key press reports from 16 up to 47. 
* A `--status` reports from 2 to 32 (16 appears twice). And it shows some 'session completed'.

**Comment by solardiz** [comment]
> A `--status` reports from 2 to 32 (16 appears twice).

I don't see 16 appear twice on the screenshot. I assume it reported the full range from 1 to 32, with 1 having scrolled off screen.

**Comment by ghost** [comment]
In the first screenshot you can see 16 twice: before 2 and before 17.

**Comment by solardiz** [comment]
> In the first screenshot, you can see 16 twice: before 2 and before 17.

Ah, right. There's also a screenshot with 4 appearing twice when the node range started at 4.

**Comment by ghost** [comment]
I believe the patch below is correct [1].

I tested using `--node` + `--fork`, using `--fork` and using a regular session.
```
diff --git a/src/options.c b/src/options.c
index f6561bcdf..9698edbe2 100644
--- a/src/options.c
+++ b/src/options.c
@@ -607,8 +607,8 @@ void opt_init(char *name, int argc, char **argv)
 		status_print();
 #if OS_FORK
 		if (options.fork) {
-			unsigned int i;
-			for (i = 2; i <= options.fork; i++) {
+			unsigned int i, pos = options.node_min;
+			for (i = 1 + pos; i < (options.fork + pos); i++) {
 				rec_name = rec_name_orig;
 				rec_name_completed = 0;
 				rec_restoring_now = 0;
```

[1] The `ETA disappears at 7th character bug` patch might be correct (I think it is better than the current code). There are too many possibilities, real testing is needed.

**Comment by sectroyer** [comment]
Is the "disappearing ETA/percentage after restore"  same issue or is this something separate?

**Comment by ghost** [comment]
Unrelated (but, I test using both "fixes").
****

**[EDITED]** I improved the use case to add some cracks (at 46 and 47). Things are ok IMO (ETA for size 6+ and "thread" number).
```
$ ../run/john --status=test 
16 0g 0:00:06:17 37.00% (ETA: 20:13:24) 0g/s 1049Kp/s 2099Kc/s 2569KC/s
17 0g 0:00:06:18 23.00% (ETA: 20:23:48) 0g/s 638592p/s 1277Kc/s 1709KC/s
18 0g 0:00:06:19 26.00% (ETA: 20:20:41) 0g/s 744436p/s 1488Kc/s 2066KC/s
19 0g 0:00:06:20 26.00% (ETA: 20:20:44) 0g/s 722668p/s 1445Kc/s 2075KC/s
20 0g 0:00:06:21 34.00% (ETA: 20:15:02) 0g/s 957923p/s 1915Kc/s 2439KC/s
21 0g 0:00:06:22 25.00% (ETA: 20:21:49) 0g/s 710417p/s 1420Kc/s 1964KC/s
22 0g 0:00:06:23 26.00% (ETA: 20:20:53) 0g/s 734921p/s 1469Kc/s 2032KC/s
23 0g 0:00:06:24 24.00% (ETA: 20:22:59) 0g/s 680956p/s 1361Kc/s 1826KC/s
24 0g 0:00:06:25 31.00% (ETA: 20:16:59) 0g/s 868616p/s 1737Kc/s 2479KC/s
25 0g 0:00:06:26 24.00% (ETA: 20:23:05) 0g/s 677572p/s 1355Kc/s 1850KC/s
26 0g 0:00:06:27 29.00% (ETA: 20:18:30) 0g/s 807383p/s 1614Kc/s 2395KC/s
27 0g 0:00:06:28 38.00% (ETA: 20:13:16) 0g/s 1044Kp/s 2088Kc/s 2578KC/s
28 0g 0:00:06:29 26.00% (ETA: 20:21:10) 0g/s 704324p/s 1408Kc/s 1910KC/s
29 0g 0:00:06:30 25.00% (ETA: 20:22:13) 0g/s 676853p/s 1353Kc/s 1908KC/s
30 0g 0:00:06:31 30.00% (ETA: 20:17:55) 0g/s 819775p/s 1639Kc/s 2466KC/s
31 0g 0:00:06:32 26.00% (ETA: 20:21:18) 0g/s 704069p/s 1408Kc/s 1984KC/s
32 0g 0:00:06:34 28.00% (ETA: 20:19:36) 0g/s 769524p/s 1539Kc/s 2211KC/s
33 0g 0:00:06:34 30.00% (ETA: 20:18:02) 0g/s 803208p/s 1606Kc/s 2411KC/s
34 0g 0:00:06:35 24.00% (ETA: 20:23:33) 0g/s 639440p/s 1278Kc/s 1767KC/s
35 0g 0:00:06:36 34.00% (ETA: 20:15:31) 0g/s 921736p/s 1843Kc/s 2412KC/s
36 0g 0:00:06:37 23.00% (ETA: 20:24:52) 0g/s 631817p/s 1263Kc/s 1756KC/s
37 0g 0:00:06:38 28.00% (ETA: 20:19:46) 0g/s 738076p/s 1476Kc/s 2144KC/s
38 0g 0:00:06:39 24.00% (ETA: 20:23:46) 0g/s 637800p/s 1275Kc/s 1759KC/s
39 0g 0:00:06:40 25.00% (ETA: 20:22:43) 0g/s 666700p/s 1333Kc/s 1838KC/s
40 0g 0:00:06:41 25.00% (ETA: 20:22:46) 0g/s 674549p/s 1349Kc/s 1854KC/s
41 0g 0:00:06:42 26.00% (ETA: 20:21:47) 0g/s 690061p/s 1380Kc/s 1963KC/s
42 0g 0:00:06:43 29.00% (ETA: 20:19:09) 0g/s 775963p/s 1551Kc/s 2281KC/s
43 0g 0:00:06:45 24.00% (ETA: 20:24:05) 0g/s 623741p/s 1247Kc/s 1742KC/s
44 0g 0:00:06:45 28.00% (ETA: 20:20:04) 0g/s 726980p/s 1453Kc/s 2087KC/s
45 0g 0:00:06:46 43.00% (ETA: 20:11:41) 0g/s 1116Kp/s 2232Kc/s 3025KC/s
46 1g 0:00:06:48 24.00% (ETA: 20:24:15) 0.002450g/s 618829p/s 1237Kc/s 1492KC/s
47 1g 0:00:06:49 25.00% (ETA: 20:23:10) 0.002444g/s 660319p/s 1320Kc/s 1488KC/s
```

**Comment by sectroyer** [comment]
> Unrelated (but, I test using both "fixes").


Okay I feared it has because of those N/A I had above. BTW not related but is it a known issue that using opencl in bleeding edge only causes segfault (where jumbo1 works correctly)?

**Comment by ghost** [comment]
> is it a known issue that using opencl in bleeding edge only causes segfault (where jumbo1 works correctly)?

No (probably, maybe). Please, create a new issue and post what you are doing and manufacturer plus GPU driver version.

**Comment by sectroyer** [comment]
Okay have N/A with restored session issue once again after letting it run some time:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/6706818/110002723-031e4500-7d16-11eb-81ca-7d23cf6d6213.png">
@claudioandre-br  this is with your fix applied. First "few minutes" it worked but then it goes to N/A no idea at which point as I let it run for a while.

**EDIT:**
```
It looks it wasn't too long. I restored here:
john --restore=./sessions/apic_brute_des_john_2                                                                                                                
Loaded 14 password hashes with 14 different salts (descrypt, traditional crypt(3) [DES 256/256 AVX2])                                                                                
Remaining 5 password hashes with 5 different salts                                                                                                                                   
Warning: OpenMP was disabled due to --fork; a non-OpenMP build may be faster                                                                                                         
Node numbers 16-47 of 47 (fork)                                                                                                                                                      
17 0g 0:02:10:58 76.77% (8) (ETA: 17:54:50) 0g/s 1964Kp/s 9823Kc/s 9823KC/s v$n8tify                                                                                                 
24 0g 0:02:10:58 76.78% (8) (ETA: 17:54:49) 0g/s 1964Kp/s 9823Kc/s 9823KC/s q*0teo6g                                                                                                 
25 0g 0:02:10:58 76.80% (8) (ETA: 17:54:47) 0g/s 1965Kp/s 9825Kc/s 9825KC/s r/oy2zqp                                                                                                 
32 0g 0:02:10:58 76.72% (8) (ETA: 17:54:57) 0g/s 1963Kp/s 9819Kc/s 9819KC/s 8'13cxix       
```

**Comment by solardiz** [comment]
@sectroyer For the ETA, please post to the proper issue you had created. Not here. Thanks.

**Comment by solardiz** [comment]
@claudioandre-br Your fix to `options.c` here looks correct to me. Since this is a core issue, I'll probably test it in core first. Thanks!

**Comment by sectroyer** [comment]
@solardiz OK, done here: https://github.com/openwall/john/issues/4591

**Comment by solardiz** [comment]
Fixed slightly differently in https://github.com/openwall/john-core, now need to merge into jumbo and retest.
