### ISSUE TITLE
Subsets bug: Some subsets could be processed more than once

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4617]
To my surprise, I noticed I got some dupes from the Subsets mode. This makes it go away:
```diff
@@ -762,14 +762,14 @@ int do_subsets_crack(struct db_main *db, char *req_charset)
 		 * A larger subset size than next, of *same* length, can actually be
 		 * smaller - but we never pick that.
 		 */
 		num_comb = min_comb;
 		while (done_len[num_comb] == maxlength && num_comb < maxdiff)
-			word_len = done_len[++num_comb];
+			num_comb++;
 
 		/* Are we done yet? */
-		if (++word_len > maxlength)
+		if ((word_len = done_len[num_comb] + 1) > maxlength)
 			break;
 
 		if (num_comb < maxdiff && done_len[num_comb + 1] + 1 < maxlength &&
 		    numwords(num_comb + 1, charcount, done_len[num_comb + 1] + 1,
 		             required) <
```
@solardiz help me here, how is this diff ANY functionally different from the original? No more context should be needed and as far as I can tell it should be a no-op. I actually came up with this fix after throwing stones at it and watched what stuck. Either I'm a moron or there's a compiler bug showing up (judging by statistics I'm a moron).

Bug is reproduced with eg.
```
./john -stdout --subsets=0123456789 -min-len=2 -max-len=5 --subsets-max-diff=3 --subsets-min-diff=2 -log >/dev/null
```
...and you'll see a very short log where the `Subset size 2, word length 4` is seen twice.

**Comment by magnumripper** [comment]
It's hardly a compiler bug - I can reproduce both the bug and the fix with clang. Not that I ever thought it was, it's just that for the life of me I can't see how the result should be any different.

**Comment by solardiz** [comment]
> how is this diff ANY functionally different from the original?

The difference that I see is if the `while` condition is never met, not even once. In that case, the original code would use whatever value `word_len` had before plus one, the revised code would use `done_len[min_comb]` plus one. I don't know which is right, but the difference is there.

**Comment by magnumripper** [comment]
Oh, right. It's that simple. Thanks!
