### ISSUE TITLE
Capitalize option descriptions in --help

### ISSUE THREAD

**Issue by wsandin** [openwall/john#4623]
Created as a follow-up to #4572. We want to start all new descriptions with a capital letter. ~~just as in `core`~~. 

This aids in readability, and helps to distinguish where there's a multi-line description for the same argument.

**Comment by solardiz** [comment]
> start all new descriptions with a capital letter, just as in `core`.

FWIW, descriptions _don't_ start with a capital letter in core, but we want to do it in jumbo because it has multi-line descriptions.

**Comment by wsandin** [comment]
@solardiz Can I sneak in the update of `doc/OPTIONS` here too that was missed before merge of the updating `--help` PR? I can create a separate PR otherwise.

**Comment by solardiz** [comment]
@wsandin What do you want to fix in `doc/OPTIONS`? Re-ordering to match the order in `--help`?

**Comment by wsandin** [comment]
> @wsandin What do you want to fix in `doc/OPTIONS`? Re-ordering to match the order in `--help`?

@solardiz Yup, but I realise it may be worth postponing until we're entirely happy with the `--help` ordering in the CLI. And when that happens, tag it in the other issue, forget about above question. :)

**Comment by solardiz** [comment]
Fixed in #4624. Closing.
