### ISSUE TITLE
DPAPImk2john.py is Python 2 only

### ISSUE THREAD

**Issue by NonoLePoulet** [openwall/john#4638]
When i am trying to run DPAPImk2john.py, it return an error :
  File "PathToJohn\run\DPAPImk2john.py", line 339
    print "%s-%s-%s-%s-%s%s" % (format(GUID[0], '08x'), format(GUID[1], '04x'), format(GUID[2], '04x'), format(GUID2[0], '04x'), format(GUID2[1], '08x'), format(GUID2[2], '04x'))
          ^
SyntaxError: invalid syntax

**Comment by solardiz** [comment]
This is a Python 2 script, but you appear to run it with Python 3. Not really a bug, but we should make this script Python 3 compatible.

**Comment by solardiz** [comment]
@Fist0urs @clavoillotte @jagotu Does one of you possibly want to make `DPAPImk2john.py` Python 3 compatible (ideally keeping it Python 2 compatible as well) and test that? (The three of you are recent committers to this script.) Or maybe @exploide wants to take care of this (having made related contributions to other scripts)? Thanks!

**Comment by NonoLePoulet** [comment]
Ok, thanks for the reply. 
You should specify in the readme that some scripts require python 2, because it wasn't very clear witch version of python you needed.

**Comment by solardiz** [comment]
Maybe we should have such scripts themselves use `python2` in the shebang line.

**Comment by exploide** [comment]
Yes, changing the shebang to `python2` would be the correct short term fix.

The [DPAPImk2john.py](https://github.com/openwall/john/blob/bleeding-jumbo/run/DPAPImk2john.py) script is comparably complex and I'm not deep into the DPAPI stuff. Maybe I find some time to see at least how much effort it requires or if it is just an easy fix.

Sample data along with complete command line invocations would be important to check if porting the script goes successful. Unfortunately there are no DPAPI samples in [john-samples](https://github.com/openwall/john-samples).

**Comment by solardiz** [comment]
> Yes, changing the shebang to `python2` would be the correct short term fix.

@exploide I'd appreciate it if you identify all of our scripts that are Python 2 only (I think grepping for "print " gives something close) and change their shebangs accordingly (in a PR). Thanks!

I doubt the changed shebang would have been of much help to @NonoLePoulet, though, who appears to be on Windows (judging by the backslashes) and is probably invoking `python` manually. The hope there would be that after seeing the error the user would then take a look inside the script and see the `python2` there.

I also don't readily know how to (re)test this script, having never used it before. Yes, we need samples.
