### ISSUE TITLE
John fails to crack zip file when the filename is a valid hash

### ISSUE THREAD

**Issue by baxitaurus** [openwall/john#4647]
### BUG ###
John is failing to crack a zip file whose filename is a valid hash. I didn't try to reproduce the bug with another file type.

### Steps to reproduce ###
Create a zip with filename `9fdaa46e100f0dc089d68662db2f5759` and encrypt with `infected`. Try to crack it:
- `zip2john 9fdaa46e100f0dc089d68662db2f5759 > hash`
- `echo 'infected' | john --stdin hash`
- `john --show hash`
`0 password hashes cracked, 1 left`

Rename the file to `z9fdaa46e100f0dc089d68662db2f5759` and retry to crack, and it should correctly detect the password.

### System configuration ###
- OS: `Ubuntu 18.04.5 LTS (Bionic Beaver)`
- `john --list=build-info`
```
Version: 1.9.0-jumbo-1+bleeding-f44e2814d 2021-03-10 15:49:07 +0100
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is /opt/john/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.5.0
GNU libc version: 2.27 (loaded: 2.27)
Crypto library: OpenSSL
OpenSSL library version: 01010100f
OpenSSL 1.1.1  11 Sep 2018
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 134 ns
Total physical host memory: 31997 MiB
Available physical host memory: 24018 MiB
Terminal locale string: it_IT.UTF-8
Parsed terminal locale: UTF-8
```

**Comment by magnumripper** [comment]
If I reproduced correctly, here's the first lines of output from john:
```
Warning: detected hash type "NT", but the string is also recognized as "PKZIP"
Use the "--format=PKZIP" option to force loading these as that type instead
```
Given this informational message, how is it a bug?

**Comment by solardiz** [comment]
@magnumripper Can you show what the `zip2john` output line looks like?

I think it's sort of a bug in that it unnecessarily becomes a special case where use of the `--format` option is required even though a `*2john` tool explicitly labels its output with a hash prefix like `$zip$` or `$pkzip$`. This is especially nasty in that `zip2john` can produce both of these kinds, so we recommend against using any `--format` option with its output hashes.

**Comment by solardiz** [comment]
BTW, the suggested password "infected" tells me this might have to do with automatic testing of files for malware - to include even encrypted archives in such testing when their passwords are weak enough for that. That's dangerous, but I guess some people are actually doing it. I hope they do it in temporary VMs or such.

In that use case, there's no one to see the warning messages, the filename might be under remote attacker's control (which probably means there are other issues as well, e.g. having it pass options to `zip2john` if it starts with a dash), and no specific `--format` option can be used because of the WinZip vs. PKZIP uncertainty (unless some script is written to see which kind of hash `zip2john` produced and choose one of the two `--format` options).

**Comment by solardiz** [comment]
... or maybe the filename is a hash of file contents, which is reasonable in that malware detection use case, although it lowers the chances of successfully recovering the password unless the original filename and its portions are inserted into a wordlist.

**Comment by magnumripper** [comment]
Well my first try (creating an archive from `arm*h`) actually "failed" to misdetect, likely becuase of restrictions in NT format's `prepare()` but this one reproduced it:
```
$ cp ../../john-samples/ZIP/winzip-zip2-testpassword#.zip 9fdaa46e100f0dc089d68662db2f5759
$ ../run/zip2john 9fdaa46e100f0dc089d68662db2f5759 | tee hash
ver 2.0 9fdaa46e100f0dc089d68662db2f5759/test.txt PKZIP Encr: cmplen=16, decmplen=4, crc=D87F7E0C ts=7862 cs=d87f type=0
9fdaa46e100f0dc089d68662db2f5759/test.txt:$pkzip$1*1*2*0*10*4*d87f7e0c*0*26*0*10*d87f*544fb90c5a2447a462e1c402e659a0ad*$/pkzip$:test.txt:9fdaa46e100f0dc089d68662db2f5759::9fdaa46e100f0dc089d68662db2f5759
```
```
$ ../run/john hash -mask:testpassword#
Warning: detected hash type "NT", but the string is also recognized as "PKZIP"
Use the "--format=PKZIP" option to force loading these as that type instead
Warning: detected hash type "NT", but the string is also recognized as "NT-opencl"
Use the "--format=NT-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (NT [MD4 256/256 AVX2 8x3])
Warning: no OpenMP support for this hash type, consider --fork=16
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 1 candidate left, minimum 24 needed for performance.
0g 0:00:00:00  (1) 0g/s 100.0p/s 100.0c/s 100.0C/s testpassword#
Session completed. 
```

**Comment by magnumripper** [comment]
I thought the problem was the first field, but it isn't. That one ended up as `9fdaa46e100f0dc089d68662db2f5759/test.txt` as opposed to just the hash. The misdetection is actually caused by 4th field being hex of len 32.

Here's the function
```c
// here to 'handle' the pwdump files:  user:uid:lmhash:ntlmhash:::
// Note, we address the user id inside loader.
static char *prepare(char *split_fields[10], struct fmt_main *self)
{
        static char out[33 + TAG_LENGTH + 1];

        if (!valid(split_fields[1], self)) {
                if (split_fields[3] && strlen(split_fields[3]) == 32) {
                        sprintf(out, "%s%s", FORMAT_TAG, split_fields[3]);
                        if (valid(out, self))
                                return out;
                }
        }
        return split_fields[1];
}
```
It sees the file name in `split_fields[3]` and reckons it's pwdump format.

**Comment by magnumripper** [comment]
> Well my first try (creating an archive from `arm*h`) actually "failed" to misdetect, likely becuase of restrictions in NT format's `prepare()`

The reason for the above was the total line length from `zip2john` was longer than `LINE_BUFFER_SIZE` so only formats with `FMT_HUGE` flag would get a chance to try it.

**Comment by magnumripper** [comment]
OK so zip2john puts the filename-inside-archive in the uid field, and the archive filename in the gid field. I think this is done for being able to pick stuff from an input file that contains many hashes ([ab]using `-user` and/or `-group` options) as well as for single mode to permute those names. We could opt to tweak where they are placed.

**Comment by solardiz** [comment]
I think the second field starting with a '$' makes this invalid as PWDUMP format file, so perhaps we could check for that in the NT formats' `prepare()` (add an exclusion)?

> OK so zip2john puts the filename-inside-archive in the uid field, and the archive filename in the gid field.

Does it? I think those would be more like the GECOS and home directory fields.

**Comment by solardiz** [comment]
I think it's a `zip2john` bug to abuse the fields like that. We should fix that.

**Comment by baxitaurus** [comment]
Hi guys, thanks for the fast reply. Don't mind the `infected` password, it was just an example.

I just inspected the issue deeper and found out that despite adding the `--format=pkzip` fixes the brute forcing, John is unable to show the found password.

Let me show you an example where the targets are `asd-with-password.zip` and `b1597b75ac1a109df50f5f0dcf381952` which are the same zip file covered by `infettamelo` password:

```
$ file asd-with-password.zip 
asd-with-password.zip: Zip archive data, at least v2.0 to extract

$ sha256sum asd-with-password.zip 
dca11cd097a02d553d9a603bdf90e7178a19c7681b01dcc278b16dd49e2c80bc  asd-with-password.zip

$ sha256sum b1597b75ac1a109df50f5f0dcf381952 
dca11cd097a02d553d9a603bdf90e7178a19c7681b01dcc278b16dd49e2c80bc  b1597b75ac1a109df50f5f0dcf381952

$ ./crack.sh 
Cracking b1597b75ac1a109df50f5f0dcf381952


Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 256/256 AVX2 8x])
Will run 12 OpenMP threads
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
Warning: Only 1 candidate left, minimum 96 needed for performance.
infettamelo      (b1597b75ac1a109df50f5f0dcf381952/asd.py)     
1g 0:00:00:00  100.0g/s 100.0p/s 100.0c/s 100.0C/s infettamelo
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 

0 password hashes cracked, 1 left



Cracking asd-with-password.zip


Using default input encoding: UTF-8
Loaded 1 password hash (ZIP, WinZip [PBKDF2-SHA1 256/256 AVX2 8x])
Will run 12 OpenMP threads
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
Warning: Only 1 candidate left, minimum 96 needed for performance.
infettamelo      (asd-with-password.zip/asd.py)     
1g 0:00:00:00  100.0g/s 100.0p/s 100.0c/s 100.0C/s infettamelo
Use the "--show" option to display all of the cracked passwords reliably
Session completed. 

asd-with-password.zip/asd.py:infettamelo:asd.py:asd-with-password.zip:./test-data/archives/asd-with-password.zip

1 password hash cracked, 0 left
```
where `crack.sh` is:
```
#! /bin/bash
rm /opt/john/run/john.pot

echo 'Cracking b1597b75ac1a109df50f5f0dcf381952'
echo ''
/opt/john/run/zip2john ./b1597b75ac1a109df50f5f0dcf381952 > hash1
echo ''
echo 'infettamelo' | /opt/john/run/john --stdin --no-log --format=pkzip hash1
echo ''
/opt/john/run/john --show hash1
echo ''

rm /opt/john/run/john.pot

echo 'Cracking asd-with-password.zip'
echo ''
/opt/john/run/zip2john ./asd-with-password.zip > hash2
echo ''
echo 'infettamelo' | /opt/john/run/john --stdin --no-log --format=pkzip hash2
echo ''
/opt/john/run/john --show hash2
```

I've tried with `--format=pkzip --show` too.

The `hash1` file content is:
```
b1597b75ac1a109df50f5f0dcf381952/asd.ps1:$pkzip$1*1*2*0*47*9c*b0608de1*0*41*8*47*4b84*d33f76352a0b465d137628b5daddd5fabedb5d11b0664c916d9417cbef26b4db66ddee02827d2f2eeb65e2a10b585900bc6ac96962fe55af784eca19ef40ce3a7116458892359c*$/pkzip$:asd.ps1:b1597b75ac1a109df50f5f0dcf381952::./b1597b75ac1a109df50f5f0dcf381952
```

while `hash2` is:
```
asd-with-password.zip/asd.ps1:$pkzip$1*1*2*0*47*9c*b0608de1*0*41*8*47*4b84*d33f76352a0b465d137628b5daddd5fabedb5d11b0664c916d9417cbef26b4db66ddee02827d2f2eeb65e2a10b585900bc6ac96962fe55af784eca19ef40ce3a7116458892359c*$/pkzip$:asd.ps1:asd-with-password.zip::./asd-with-password.zip
```

**Comment by ghost** [comment]
> I've tried with `--format=pkzip` --show too

It works (here) when I use the format option.

```
$ john --show hash1
0 password hashes cracked, 1 left

$ john --show --format=pkzip hash1
b1597b75ac1a109df50f5f0dcf381952/asd.ps1:infettamelo:$pkzip$1*1*2*0*47*9c*b0608de1*0*41*8*47*4b84*d33f76352a0b465d137628b5daddd5fabedb5d11b0664c916d9417cbef26b4db66ddee02827d2f2eeb65e2a10b585900bc6ac96962fe55af784eca19ef40ce3a7116458892359c*$/pkzip$:asd.ps1:b1597b75ac1a109df50f5f0dcf381952::./b1597b75ac1a109df50f5f0dcf381952

1 password hash cracked, 0 left
```

**Comment by baxitaurus** [comment]
Yes sorry it was mine mistake, I just looked at the bash history and I noticed an error when trying with `--show --format=pkzip`, with the format option it works fine. 

> > I've tried with `--format=pkzip` --show too
> 
> It works (here) when I use the format option.
> 
> ```
> $ john --show hash1
> 0 password hashes cracked, 1 left
> 
> $ john --show --format=pkzip hash1
> b1597b75ac1a109df50f5f0dcf381952/asd.ps1:infettamelo:$pkzip$1*1*2*0*47*9c*b0608de1*0*41*8*47*4b84*d33f76352a0b465d137628b5daddd5fabedb5d11b0664c916d9417cbef26b4db66ddee02827d2f2eeb65e2a10b585900bc6ac96962fe55af784eca19ef40ce3a7116458892359c*$/pkzip$:asd.ps1:b1597b75ac1a109df50f5f0dcf381952::./b1597b75ac1a109df50f5f0dcf381952
> 
> 1 password hash cracked, 0 left
> ```

**Comment by magnumripper** [comment]
> I think the second field starting with a '$' makes this invalid as PWDUMP format file, so perhaps we could check for that in the NT formats' `prepare()` (add an exclusion)?

Yes, definitely. We should do so for both NT formats and have a look at the LM formats as well.

> > OK so zip2john puts the filename-inside-archive in the uid field, and the archive filename in the gid field.
> 
> Does it? I think those would be more like the GECOS and home directory fields.

```
root:*:0:0:System Administrator:/var/root:/bin/sh
```
For my arm32.h test file, zip2john placed `9fdaa46e100f0dc089d68662db2f5759/arm32le.h` in the 1st (login) field. The hash goes in the second of course. The third is `arm32le.h` and the fourth is `9fdaa46e100f0dc089d68662db2f5759`. I do believe those are `uid:gid`. After them, again `9fdaa46e100f0dc089d68662db2f5759` in the 6th field (5th is empty). I'm not sure why the last one is there at all but it might be that it's not basename'd, so it could hold the full path given to zip2john (there was just no path involved in my test). The idea was probably to be able to permute even path components but it should be in the 5th, GECOS, field then. Or maybe it's just for traceability. Anyway we've seen many problems with full path names, such as Windows `C:` and silly lengths so we might want to drop that.

> I think it's a `zip2john` bug to abuse the fields like that. We should fix that.

Well it does come handy sometimes. We do it for WPA as well: Mac addresses are stripped from `:` and placed in uid:gid, so from a large input file you can opt to attack only certain AP(s) and/or certain client(s). Maybe for archives we shouldn't do it at all, or make it optional.

> It works (here) when I use the format option.

After we add that check to NT's `prepare()` I assume `--show` will work fine without a specific `--format` option as well.

**Comment by solardiz** [comment]
To me, `zip2john` abusing the uid:gid fields is the real bug here, and must be fixed. This is what I added the "bug" label for.

Adding an exclusion to LM & NT formats is something we may do, but it's less obvious. (Yes, I did suggest it, but I am still unsure.)

**Comment by magnumripper** [comment]
I'm all for changing zip2john as well, but IMHO the added check in LM&NT is great and we should keep it. For one, I'm pretty sure something along the lines of this issue could happen with other files as well, maybe even files not created by our tools.

**Comment by solardiz** [comment]
You're right, magnum. OTOH, I am concerned that some tool could be creating PWDUMP-style files with LM/NT hashes where they put some identifiers that just might happen to start with a '$' into the second field (which is normally a UID in PWDUMP files).

**Comment by magnumripper** [comment]
I did test it with several thousands of hashes scraped from pastebin (so likely created with all sorts of pwdump tools) and nothing changed in numbers of loaded hashes.

**Comment by magnumripper** [comment]
> To me, `zip2john` abusing the uid:gid fields is the real bug here, and must be fixed. This is what I added the "bug" label for.

I would call it repurposing, not really abusing. Exactly why is it a bug? Do you want us to stop using them for WPAPSK as well? That would be a pity, it's very very useful.

**Comment by solardiz** [comment]
Are any users aware of such repurposing? If no one knows, then it's more of a bug. I didn't recall WPAPSK doing this as well.

**Comment by magnumripper** [comment]
I guess it isn't properly documented but I believe the use of it has been discussed in the ML and other fora. I could document it better, but not sure where. Add a `doc/README.wpapsk`? Or it could be noted (in a more general sense) in `doc/OPTIONS` for the `--users/--groups` options.
