### ISSUE TITLE
Request to support FPGAs that are more easily available

### ISSUE THREAD

**Issue by MojoMoe** [openwall/john#4648]
Question/Request rather than issue.

Since Ztex 1.15y are unobtanium. Are JtR developers working on supporting any other FPGAs that are more easily available?

**Comment by solardiz** [comment]
> Question/Request rather than issue.

Which makes it a better fit for the john-users mailing list than for GitHub, but I don't mind.

> Are JtR developers working on supporting any other FPGAs that are more easily available?

Currently, no. You want to sponsor such effort?

See also #4019, #4526.

**Comment by solardiz** [comment]
@MojoMoe Seeing the issues you opened with other projects, it looks like you're currently only(?) into Bitcoin wallet password recovery. We do not currently support that on _any_ FPGA. #4526 includes discussion on how such support might be added, but there's currently no incentive to do so.

**Comment by MojoMoe** [comment]
Thank you very much for your quick response. That is correct. I have a focus on bitcoin password recovery for now, because of the potential there with forgotten passwords. So it looks like for now we are just stuck with the unobtanium GPUs at triple MSRP. Please feel free to close this issue. Thanks again.
