### ISSUE TITLE
Bug 'base64.decodestrings(data)' in ssh2john.py in Jumbo John

### ISSUE THREAD

**Issue by Foalic** [openwall/john#4652]
Bug:  ssh2john.py throws an error when used with Python 3.9.1. 
The error states that the "AttributeError: module 'base64' has no attribute 'decodestring'" for line 103. 

Workaround: I changed the 'decodestrings' to 'b64decode' and the file ran perfectly. 

I saw this being mentioned in the issue "Make a new release soon as the previous one has Python 3 compatibility issues and known-fixed bugs #4564" but I downloaded john after this. 
I checked on the Openwall site and the 64-bit version zip files for jumbo and bleeding-jumbo. Bleeding-jumbo has a change using codecs, but jumbo is still 'decodestrings'.

### Steps to reproduce ###
Use ssh2john.py with Python 3.9.1. 

### System configuration ###
OS: Windows 10 Home edition

Python 3.9.1

John Build info: 
   
Version: 1.9.0-jumbo-1
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is /run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by ghost** [comment]
> I checked on the Openwall site and the 64-bit version zip files for jumbo and bleeding-jumbo. Bleeding-jumbo has a change using codecs, but jumbo is still 'decodestrings'.

Because what you called Jumbo is the (two years) old release: the previous release. 

Issues like this are the main reason ticket # 4564 is open.

That said, could you please use bleeding? You can find here (in the GitHub repo). BTW: we will probably close this issue (we already have #4564).

**Comment by Foalic** [comment]
Alright, sorry I had gone to the Openwall site for the tool. 
I will use bleeding then, thank you.
