### ISSUE TITLE
Problem trying to crack hashes extracted from VRRPv2 packets with AH - IPSEC authentication enabled

### ISSUE THREAD

**Issue by mp77-arch** [openwall/john#4653]
Hello,

I'm encountering a problem trying to crack hashes extracted from VRRPv2 packets with AH - IPSEC authentication enabled.

I've set up a VRRP service on a linux box using Keepalived.

I configured Keepalived to use AH authentication, with the password "Blabla" (without the double-quotes).

Then I captured the packet using Wireshark, saved them into pcap format and ran pcap2john.py to extract it's hashes (the pcap file contains 8 VRRP packets).

pcap2john.py returned the 8 following lines:

$net-ah$0$450003b000c10000ff3300000a00020fe0000012700400000a00020f000000c10000000000000000000000002114ff0102011b42c0a801fe0000000000000000$40628119fc4d96e13518dfbf
$net-ah$0$4500011800c20000ff3300000a00020fe0000012700400000a00020f000000c20000000000000000000000002114ff0102011b42c0a801fe0000000000000000$edba2a675ae4523b2dcc6aaa
$net-ah$0$450003f800c30000ff3300000a00020fe0000012700400000a00020f000000c30000000000000000000000002114ff0102011b42c0a801fe0000000000000000$73325d321f2a22f3a58f6edb
$net-ah$0$4500037c00c40000ff3300000a00020fe0000012700400000a00020f000000c40000000000000000000000002114ff0102011b42c0a801fe0000000000000000$18711a16494600d4bc369da6
$net-ah$0$4500039000c50000ff3300000a00020fe0000012700400000a00020f000000c50000000000000000000000002114ff0102011b42c0a801fe0000000000000000$6f2704e4fba05ad9c74264c1
$net-ah$0$450003d400c60000ff3300000a00020fe0000012700400000a00020f000000c60000000000000000000000002114ff0102011b42c0a801fe0000000000000000$650d55fe1dd4bceab914b707
$net-ah$0$4500034400c70000ff3300000a00020fe0000012700400000a00020f000000c70000000000000000000000002114ff0102011b42c0a801fe0000000000000000$d8a74572d96762c6fdd5d12e
$net-ah$0$450000a800c80000ff3300000a00020fe0000012700400000a00020f000000c80000000000000000000000002114ff0102011b42c0a801fe0000000000000000$6f9a8beafd4ee81fc027e4a8

I've tried to crack these hashes with John (I used JTR bleeding jumbo version, downloaded today 04/04/2021) but John cannot crack them.

The dictionnay I'm using contains "Blabla", so it should have worked.

Are VRRPv2 - AH hashes supported by John?
Is the algorithm "net-ah" the good one to crack VRRPv2 - AH hashes or should I use another one?

Best regards,

Matthieu

**Comment by solardiz** [comment]
I confirm current John doesn't crack the hashes posted above using "Blabla" in the wordlist. However, this doesn't tell us where the issue is.

@mp77-arch Can you test with samples from https://github.com/openwall/john-samples/tree/main/VRRP and if those are getting cracked for you, then try and see how yours differ? Thanks!

**Comment by solardiz** [comment]
Also searched the code in https://github.com/acassen/keepalived - looks like it doesn't use anything newer than HMAC-MD5 for VRRP.

**Comment by mp77-arch** [comment]
I tried to crack tests samples coming from the sub-directory "auth_hdr" from https://github.com/openwall/john-samples/tree/main/VRRP,  John doesn't crack any of them.

**Comment by solardiz** [comment]
@mp77-arch Thanks!

What is your output of `pcap2john.py` for our samples?

What version of Python are you using? If it's Python 3, then can you easily try with 2, or vice versa? Does the output change?

**Comment by ghost** [comment]
1. `pcap2john.py `prints nothing when I run it using python3. 
2. It produces valid hashes when run with Python 2 (hashes that `john` can load), but all hashes produced are uncrackable. 
3. I even tried the script and JtR from 2017.

From 2017 7cf01f75464d312a737eb57c1adbd08e89065d04 and nothing is cracked.
- `John the Ripper CUDA-189-g7cf01f7 OMP [linux-gnu 64-bit AVX2-ac]`

**Comment by solardiz** [comment]
@claudioandre-br Do you mean "it produces valid hashes" when run with Python 2?

@kholia We'd appreciate your help here. Thanks!

**Comment by claudioandre-br** [comment]
Yes

**Comment by mp77-arch** [comment]
> 
> 
> @mp77-arch Thanks!
> 
> What is your output of `pcap2john.py` for our samples?
> 
> What version of Python are you using? If it's Python 3, then can you easily try with 2, or vice versa? Does the output change?

I'm using Python 2.7.18 to run pcap2john.py.

Here's the hash produced by pcap2john.py when I run it against VRRP-AH-Müller.pcap file, using Python 2.7.18 :

net-ah$0$45000208001e0000ff330000c0a87c01e000001270040000c0a87c010000001e0000000000000000000000002133650102016dc00a00000a0000000000000000$7c6ba14741b4597750ffe6a1

**Comment by ghost** [comment]
The 2john tool interprets/converts part of the information it saves in salt. If I undo that (I mean, use binary values I found inside the `.pcap`), I can crack the samples. Two bytes are wrong in the final hash.

**Comment by solardiz** [comment]
Thanks @claudioandre-br! So I guess some of the zeroization here is actually undesirable:

```python
                # zero mutable fields (tos, flags, chksum)
                salt[1] = 0  # tos
                salt[6] = 0  # flags
                salt[10:12] = b"\x00\x00"  # checksum
                icv_offset = iphdr_len + icv_length
                h = salt[icv_offset:icv_offset+icv_length]
                # zero ah icv
                salt[icv_offset:icv_offset+icv_length] = b"\x00" * icv_length
```

@kholia @exploide Can you please look into this and likely drop the problematic lines (just the checksum? or maybe most or all of them?)

**Comment by exploide** [comment]
It's not the zeroing. There is something weird going on with the dpkt library.

I tested with the file `VRRP-AH-Müller.pcap` and compared the working test vector from https://github.com/openwall/john/blob/bleeding-jumbo/src/net_ah_fmt_plug.c#L53 with the non-working output of `pcap2john.py`.

The working test vector begins with `4500004000` (conforms to what I see in the file with Wireshark or hexdump). But pcap2john outputs something starting with `4500020800`. This mismatch occurs early in the script.

```python
    f = open(fname, "rb")
    pcap = dpkt.pcap.Reader(f)

    for _, buf in pcap:
        eth = dpkt.ethernet.Ethernet(buf)
```

The `buf` variable holds the correct value. After applying the `dpkt.ethernet.Ethernet` constructor, the value is wrong. I don't know why, haven't digged deep into it yet.

Does someone know why it changes the raw value of the ethernet data?

pcap2john uses two packet parsing libraries at the moment, dpkt and scapy. Maybe I will change the affected section to use scapy instead of dpkt and see if it works better.

EDIT: Yep, it's the dpkt library which changed. The last version where this is working is `dpkt==1.8.6`. If I see correctly, the version is ancient.

**Comment by solardiz** [comment]
> pcap2john uses two packet parsing libraries at the moment, dpkt and scapy. Maybe I will change the affected section to use scapy instead of dpkt and see if it works better.

Sounds good. Thanks!

Better yet, but longer-term, we'd switch pcap2john to just one of those libraries, avoiding dependency on the other.

**Comment by solardiz** [comment]
@mp77-arch @claudioandre-br Will you test @exploide's changes in #4662 from his branch, or should we merge first?

**Comment by solardiz** [comment]
@mp77-arch @claudioandre-br No interest from you in helping test @exploide's changes in #4662 from his branch? If so, I guess we'll just merge and wait for further problem reports in case anything is still broken.

**Comment by ghost** [comment]
I tested using known samples (I guess he also did this). +1 merge.
