### ISSUE TITLE
JTR flagged by Virus scan on MacOS

### ISSUE THREAD

**Issue by intergalactic-overlords** [openwall/john#4668]
I have built the latest version of JTR (john-1.9.0-jumbo-1) on Mac OS (11.2.3) and Avast File Shield flags it as a threat when trying to run.
It says it contains a threat named Agent.JX. Probably a false positive?

### Steps to reproduce ###
* download john-1.9.0-jumbo-1 from openwall
* in src, run `./configure` `make -s clean` and `make -sj4` in terminal
* in run, run `./john` in terminal
* Avast File Shield pops up the following:

<img width="643" alt="Screenshot at Apr 16 11-54-53" src="https://user-images.githubusercontent.com/2363710/115007817-ae402380-9eaa-11eb-9a6a-7632e604a944.png">

### System configuration ###
I cannot run the `./john` command because of above issue

**Comment by intergalactic-overlords** [comment]
The 1.8.0.9-jumbo-1-bleeding version does not have the same issue

**Comment by solardiz** [comment]
@intergalactic-overlords Thank you for letting us know. Can you please report this as undesired behavior to Avast? You're a customer of theirs (right?), and we are not.

**Comment by solardiz** [comment]
Meanwhile, another thing you can try is building the latest code from this repo, not the release. This is what we currently recommend anyway, and what we expect any GitHub issues to be reported against.

This would test how good their heuristics are at detecting whatever "threat" they thought there was. ;-)

**Comment by solardiz** [comment]
No further communication from OP, and nothing for us to do on this anyway. Closing.
