### ISSUE TITLE
Oldoffice read-only mode hash

### ISSUE THREAD

**Issue by MiLeG** [openwall/john#4676]
Greetings,

I believe this feature isn't included in the current office2john, but I'm not that well versed in this code, so I could very well be wrong.
The attached office 2003 presentation is both password protected on opening (the password is Lucic) and also write-protected.
After running hashcat for a while, I could only get the first password, but not the second write permission password.

Is there any way to choose which permission hash to export, or are both passwords included in the same hash (also attached)?

Cheers
[oldPres.zip](https://github.com/openwall/john/files/6338724/oldPres.zip)

**Comment by magnumripper** [comment]
I take it you mean the write permission password is different from "Lucic"?

**Comment by MiLeG** [comment]
Naturally 😁

**Comment by magnumripper** [comment]
Interesting. I'll take a look

**Comment by ghost** [comment]
Isn't "PPS files are used to immediately begin a presentation, opening one by regular means will not let you edit the file"? 

It is not password related, right? I don't have Office, can't say for sure.

**Comment by MiLeG** [comment]
As far as I know after using them, they are essentially the same. Both files have the full editable data written in them.

The only real difference is that .pps files are being started in a slideshow after opening, to make them more convenient or something.

You can still edit them through to the File > Open menu though.

**Comment by magnumripper** [comment]
I can edit it with macOS' Keynote, just using "Lucic". If Office doesn't let you, perhaps LibreOffice or some other alternative will.

**Comment by MiLeG** [comment]
LibreOffice doesn't work for me, but if Keynote works then I guess this issue doesn't make much sense.

So can you confirm for me that you can edit and save this file in Keynote?

**Comment by magnumripper** [comment]
It asks for a password upon opening, I use "Lucic" and then I can view it, edit it, save it - no sign of any other password needed. BTW it does start up in presentation mode, I simply left it and got to editing.
