### ISSUE TITLE
--devices --fork broken

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4679]
Looks like we got a regression?

On a certain system (where I currently happen to observe this) with many NVIDIA GPUs, hashcat can use all the GPUs simultaneously just fine. JtR, on the other hand, ends up allocating memory on multiple (or all) GPUs as requested, yet puts all computation on just one GPU (the first one, or the first listed in `--devices`). So, for example, `-dev=5,6 -fork=2` results (per `nvidia-smi`) in memory consumption on devices 5 and 6, but in 100% GPU utilization only on device 5 (and 0% on device 6), and actual per-forked-process speeds are then half of one GPU's (indeed, we're overbooking device 5). When using any one device on its own, everything works just right. Puzzling.

In fact, it even prints `Device 5: ...` twice!

**Comment by solardiz** [comment]
Introduced between Feb 25 and Mar 9.

**Comment by solardiz** [comment]
Looks like we need this:

```diff
+++ b/src/john.c
@@ -544,14 +544,6 @@ static void john_fork(void)
 
                case 0:
                        sig_preinit();
-#if HAVE_OPENCL
-                       /* Poor man's multi-device support */
-                       if (options.acc_devices->count &&
-                           strstr(database.format->params.label, "-opencl")) {
-                               /* Postponed format init in forked process */
-                               fmt_init(database.format);
-                       }
-#endif
 #if HAVE_ZTEX
                        if (strstr(database.format->params.label, "-ztex")) {
                                list_init(&ztex_use_list);
@@ -579,6 +571,14 @@ static void john_fork(void)
                        }
                        options.node_min += i * npf;
                        options.node_max = options.node_min + npf - 1;
+#if HAVE_OPENCL
+                       /* Poor man's multi-device support */
+                       if (options.acc_devices->count &&
+                           strstr(database.format->params.label, "-opencl")) {
+                               /* Postponed format init in forked process */
+                               fmt_init(database.format);
+                       }
+#endif
                        sig_init_child();
                        return;
 
```

Works for me, but I haven't yet tested it along with `--restore`.

**Comment by solardiz** [comment]
> I haven't yet tested it along with `--restore`.

Seems to work fine as well.

**Comment by solardiz** [comment]
Perhaps the ZTEX section should be moved as well, so:

```diff
+++ b/src/john.c
@@ -544,23 +544,6 @@ static void john_fork(void)
 
                case 0:
                        sig_preinit();
-#if HAVE_OPENCL
-                       /* Poor man's multi-device support */
-                       if (options.acc_devices->count &&
-                           strstr(database.format->params.label, "-opencl")) {
-                               /* Postponed format init in forked process */
-                               fmt_init(database.format);
-                       }
-#endif
-#if HAVE_ZTEX
-                       if (strstr(database.format->params.label, "-ztex")) {
-                               list_init(&ztex_use_list);
-                               list_extract_list(ztex_use_list, ztex_detected_list,
-                                       i * ztex_devices_per_fork, ztex_devices_per_fork);
-                               ztex_fork_num = i;
-                               usleep(i * 100000);
-                       }
-#endif
                        if (rec_restoring_now) {
                                unsigned int save_min = options.node_min;
                                unsigned int save_max = options.node_max;
@@ -579,6 +562,23 @@ static void john_fork(void)
                        }
                        options.node_min += i * npf;
                        options.node_max = options.node_min + npf - 1;
+#if HAVE_OPENCL
+                       /* Poor man's multi-device support */
+                       if (options.acc_devices->count &&
+                           strstr(database.format->params.label, "-opencl")) {
+                               /* Postponed format init in forked process */
+                               fmt_init(database.format);
+                       }
+#endif
+#if HAVE_ZTEX
+                       if (strstr(database.format->params.label, "-ztex")) {
+                               list_init(&ztex_use_list);
+                               list_extract_list(ztex_use_list, ztex_detected_list,
+                                       i * ztex_devices_per_fork, ztex_devices_per_fork);
+                               ztex_fork_num = i;
+                               usleep(i * 100000);
+                       }
+#endif
                        sig_init_child();
                        return;
 
```

I'm also unsure about `sig_preinit();` - it wasn't in core - but then in jumbo it was prior to writes to `options.node_min` before our recent changes, so I guess its placement is right.

And we need to retest ZTEX.

**Comment by magnumripper** [comment]
Looking at the sum of changed under that period, the proposed move makes sense to me.

**Comment by solardiz** [comment]
Actually, ZTEX probably wasn't broken and this move is probably a no-op for it - due to the explicit use of `i` there. I guess the OpenCL piece implicitly used `options.node_min` from `fmt_init()`?

**Comment by magnumripper** [comment]
> Looking at the sum of changed under that period, the proposed move makes sense to me.

I take that back. While the move should be fine, I can't quite see why it would matter... What format was this?

**Comment by magnumripper** [comment]
> > Looking at the sum of changed under that period, the proposed move makes sense to me.
> 
> I take that back. While the move should be fine, I can't quite see why it would matter... What format was this?

OK, some (or many?) formats do have things in `init()` that may need this change (such as `opencl_load_environment()`) - just not all of them.

**Comment by ghost** [comment]
> I guess the OpenCL piece implicitly used options.node_min from fmt_init()

Yes, it uses `options.node_min` as the `node_id` (ID) when, e.g., you use `--dev=2,2,3 --fork=6`:
```
node ID 1: dev=2
node ID 2: dev=2
node ID 3: dev=3
node ID 4: dev=2
node ID 5: dev=2
node ID 6: dev=3
```

If `options.node_min` is always 1, JtR always uses the same `--device` (`gpu_id` doesn't change).

**Comment by solardiz** [comment]
> What format was this?

I tested with my new bitcoin-opencl, and just to make sure this is unrelated to the new format also with md5crypt-opencl. Both demonstrated the problematic behavior before the changes I copy-pasted in here, and both worked correctly with the change (move).
