### ISSUE TITLE
OpenCL is broken.

### ISSUE THREAD

**Issue by ghost** [openwall/john#4697]
According to Travis upstream CI.

```
Testing: agilekeychain-opencl, 1Password Agile Keychain [PBKDF2-SHA1 AES OpenCL]... Options used: -I opencl -cl-mad-enable -D__CPU__ -DDEVICE_INFO=33 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=1800 -DDEV_VER_MINOR=11 -D_OPENCL_COMPILER -DKEYLEN=28 -DSALTLEN=64 -DOUTLEN=16 ../run/opencl/agile_kernel.cl
Build log: "opencl/pbkdf2_hmac_sha1_unsplit_kernel.cl", line 208: error: identifier
          "SHA1_DIGEST_LENGTH" is undefined
  	loops = (skip_bytes + outlen + (SHA1_DIGEST_LENGTH-1)) / SHA1_DIGEST_LENGTH;
 
```

**Comment by solardiz** [comment]
Must be side-effect of first commit of #4694. Who's to fix this?

**Comment by solardiz** [comment]
> Who's to fix this?

@magnumripper Maybe you?

**Comment by magnumripper** [comment]
Ouch, I'm on it. I was planning to test that before declaring the PR ready but it slipped my mind. It's a pity we have no OpenCL testing on CI now.

**Comment by magnumripper** [comment]
I don't get it though... `agile_kernel.cl` includes `pbkdf2_hmac_sha1_unsplit_kernel.cl` which includes `opencl_sha1.h`, and there we have the declaration. How can it not be defined?

**Comment by magnumripper** [comment]
Oh, I see it now, it's `SHA_DIGEST_LENGTH` vs `SHA1_DIGEST_LENGTH`. What a foot gun.
