### ISSUE TITLE
sha1crypt-opencl auto-tune stuck at LWS=256 on Kepler

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4703]
I realized I didn't know to update `ITERATIONS` in `opencl_sha1crypt_fmt_plug.c` when I introduced hashcat's test vector, and was about to do that, but found another issue, also seen e.g. on a build from January:

On the Titan Kepler in "super", auto-tune for this format exhibits this behavior:

```
Calculating best LWS for GWS=16384
Testing LWS=32 GWS=16384 ... 244.709ms+
Testing LWS=64 GWS=16384 ... 196.442ms+
Testing LWS=128 GWS=16384 ... 196.738ms
Testing LWS=256 GWS=16384 ... 213.286ms
Testing LWS=256 GWS=16384 ... 213.683ms
Testing LWS=256 GWS=16384 ... 213.609ms
Testing LWS=256 GWS=16384 ... 212.117ms
Testing LWS=256 GWS=16384 ... 212.752ms
```

and so on - it doesn't complete. I wonder how we managed to test all formats including on that GPU before?

**Comment by solardiz** [comment]
Testing my old builds, August 2018 works, December 2018 fails like above. However, this is really weird - surely we previously ran all formats on that GPU after that date?

**Comment by solardiz** [comment]
@magnumripper @claudioandre-br I'd appreciate your help on this issue. This device is currently idle.

**Comment by solardiz** [comment]
> I realized I didn't know to update `ITERATIONS` in `opencl_sha1crypt_fmt_plug.c` when I introduced hashcat's test vector, and was about to do that

This is now done, but as expected didn't make a difference for the stuck auto-tune issue reported here.

**Comment by magnumripper** [comment]
Could it be we never tested anything but `-test=0`?

**Comment by magnumripper** [comment]
Never mind how we didn't notice - what in the code allows/results in this behavior?

**Comment by magnumripper** [comment]
```c
	for (optimal_work_group = my_work_group = wg_multiple;
	        (int)my_work_group <= (int)max_group_size;
	        my_work_group += wg_multiple) {
(...)
		if ((double)(sumRunTime) / kernelExecTimeNs < 0.997) {
			kernelExecTimeNs = sumRunTime;
			optimal_work_group = my_work_group;
		} else {
			if (my_work_group >= 256 || (my_work_group >= 8 && wg_multiple < 8)) {
				/* Jump to next power of 2 */
				size_t x, y;
				x = my_work_group;
				while ((y = x & (x - 1)))
					x = y;
				x *= 2;
				my_work_group = GET_NEXT_MULTIPLE(x, wg_multiple);
				/* The loop logic will re-add wg_multiple */
				my_work_group -= wg_multiple;
			}
		}
```
When we get stuck, `wg_multiple` is 32 and `my_work_group` is 256. We hit the else clause, and end up with `x` being 512. Then `GET_NEXT_MULTIPLE(512, 32)` results in 256... why is that?!

```c
#define GET_NEXT_MULTIPLE(dividend, divisor)	  \
	(divisor) ? ((dividend + (ocl_v_width * divisor - 1)) / (ocl_v_width * divisor)) * divisor : (dividend) / ocl_v_width;
```

**Comment by magnumripper** [comment]
OK, so `ocl_v_width` is actually 2!

**Comment by magnumripper** [comment]
OK, it's actually supposed to be 2, but our `find_best_lws()` function doesn't deal with it very good.

```c
static void init(struct fmt_main *_self)                                                                                
{                                                                                                                       
    static char valgo[sizeof(ALGORITHM_NAME) + 12] = "";                                                                
                                                                                                                        
    self = _self;                                                                                                       
                                                                                                                        
    opencl_prepare_dev(gpu_id);                                                                                         
    /* Nvidia Kepler benefits from 2x interleaved code */                                                               
    if (!options.v_width && nvidia_sm_3x(device_info[gpu_id]))                                                          
        ocl_v_width = 2;                                                                                                
    else                                                                                                                
    /* VLIW5 does better with just 2x vectors due to GPR pressure */                                                    
    if (!options.v_width && amd_vliw5(device_info[gpu_id]))                                                             
        ocl_v_width = 2;                                                                                                
    else                                                                                                                
        ocl_v_width = opencl_get_vector_width(gpu_id, sizeof(cl_int));                                                  
(...)
```

This is simply a bug in `find_best_lws()` that doesn't seem to surface very often.

I'll take a break until tomorrow.

**Comment by magnumripper** [comment]
I really wonder if `ocl_v_width` should be in that macro at all, and if should, maybe it's currently put there in some incorrect way.

Or, if it is sometimes to be used (such as in count -> GWS calculation unlike here), perhaps it should be in the *arguments*, not in the *macro*? I need to boil this a bit longer.

**Comment by magnumripper** [comment]
Here's the same bug seen with same format but an `ocl_v_width` of 4 (Apple CPU):
```
Calculating best LWS for GWS=512
Testing LWS=1 GWS=512 ... 198.638 ms+
Calculating best GWS for LWS=1; max. 200 ms single kernel invocation.
```
It aborts prematurely, which is harder to notice than when it continues forever...

EDIT: This might also be caused by some code forcing LWS to 1 when device is a CPU. If I add `-lws=8` it's silently ignored and I still get 1.

**Comment by magnumripper** [comment]
Here's the output for same format with POCL CPU, width 8 (for AVX2):
```
Calculating best LWS for GWS=256
Testing LWS=8 GWS=256 ... 220.880 ms+
Testing LWS=16 GWS=256 ... 220.726 ms
Testing LWS=32 GWS=256 ... 194.533 ms+
Testing LWS=64 GWS=256 ... 233.910 ms
Testing LWS=128 GWS=256 ... 4.905 s
Calculating best GWS for LWS=32; max. 200 ms single kernel invocation.
```
So the forcing of LWS=1 for CPU might be Apple-specific. And for some reason, everything works well here. Is it just x2 that gets problems?

**Comment by magnumripper** [comment]
Same POCL CPU with `--force-vector-width=4`
```
Calculating best LWS for GWS=8
Testing LWS=8 GWS=8 ... 206.995 ms+
Calculating best GWS for LWS=8; max. 200 ms single kernel invocation.
```
It does seem to abort prematurely (I'll need to dry run the numbers). **EDIT** that's obviously because GWS was only 8.

And with `--force-vector-width=2`
```
Calculating best LWS for GWS=8
Testing LWS=8 GWS=8 ... 157.650 ms+
Calculating best GWS for LWS=8; max. 200 ms single kernel invocation.
```
I really thought this would reproduce the original never-end behavior, but it doesn't. OTOH it does seem to abort prematurely. **EDIT** that's obviously because GWS was only 8.

Going back to that Kepler device:

With `--force-scalar`
```
Calculating best LWS for GWS=65536
Testing LWS=32 GWS=65536 ... 292.570 ms+
Testing LWS=64 GWS=65536 ... 244.026 ms+
Testing LWS=128 GWS=65536 ... 254.844 ms
Testing LWS=256 GWS=65536 ... 240.867 ms+
Testing LWS=512 GWS=65536 ... 234.644 ms+
Testing LWS=1024 GWS=65536 ... 222.744 ms+
Calculating best GWS for LWS=1024; max. 200 ms single kernel invocation.
```
Bug obviously is hidden.

With `--force-vector-width=4`
```
Calculating best LWS for GWS=8192
Testing LWS=32 GWS=8192 ... 265.218 ms+
Testing LWS=64 GWS=8192 ... 264.962 ms
Testing LWS=128 GWS=8192 ... 264.975 ms
Testing LWS=256 GWS=8192 ... 400.304 ms
Testing LWS=128 GWS=8192 ... 264.695 ms
Testing LWS=256 GWS=8192 ... 400.320 ms
Testing LWS=128 GWS=8192 ... 264.964 ms
Testing LWS=256 GWS=8192 ... 401.259 ms
(...)
Testing LWS=256 GWS=8192 ...^CSession aborted
```
This is interesting. It doesn't end up like the POCL did. Why is that?

**Comment by magnumripper** [comment]
I should probably stop this testing and instead figure out what we *do* want to calculate, but I'm not clear about that yet, lol.

**Comment by magnumripper** [comment]
OK, here's a fact: *Every single use of this macro* except this very one are of this type:
```c
    global_work_size = GET_NEXT_MULTIPLE(count, local_work_size);
```
...and all of those are fine - it's just this call from `find_best_lws()` that should NOT take vector width into account.

Still, I'm thinking with a name like that, `GET_NEXT_MULTIPLE()` really *shouldn't* have `ocl_v_width` in it. We should refactor it either to a name that specifically indicates it's using vector width, or something that specifically indicates what it can be used for (such as `KPC_TO_GWS()`).

Here's sha1crypt when using a proper macro without `ocl_v_width`:
```
Calculating best LWS for GWS=16384
Testing LWS=32 GWS=16384 ... 240.340 ms+
Testing LWS=64 GWS=16384 ... 196.272 ms+
Testing LWS=128 GWS=16384 ... 196.169 ms
Testing LWS=256 GWS=16384 ... 214.136 ms
Testing LWS=512 GWS=16384 ... 219.587 ms
Calculating best GWS for LWS=64; max. 200 ms single kernel invocation.
```

**Comment by magnumripper** [comment]
Besides, the `Nvidia Kepler benefits from 2x interleaved code` doesn't seem to be true (anymore?). With default vector width of 2, we end up at 35691 c/s but running scalar gets us all the way to 49245 c/s.
