### ISSUE TITLE
oldOffice document with 56-bit key

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4705]
Original issue: https://www.openwall.com/lists/john-users/2021/04/27/1

I got a private copy of such document. Using some debug prints, I get
```
em1.doc : 
flags 4 providerType d provider "microsoft base dss and diffie-hellman cryptographic provider" algId 6801 algHashId 8004 keySize 56
```
According to [MS-OFFCRYPTO](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-offcrypto/3c34d72a-1a61-4b52-a893-196f9157f083):
- "Flags 4" seem to mean "CryptoAPI RC4".
- providerType d (`0x0d`) doesn't seem normal. It should be `0x01` for RC4 or `0x18` for AES.
- provider: "microsoft base dss and diffie-hellman cryptographic provider"
- algId 6801 means RC4
- algHashId 8004 means SHA-1
- keySize can be any even 8 between 40 and 128 according to the doc, so 56 should be OK

The question is if we should simply truncate to 56 bits instead of 40, all else equal? It appears this might be the case but we can't know until we crack such document.

**Comment by magnumripper** [comment]
> * providerType d (`0x0d`) doesn't seem normal. It should be `0x01` for RC4 or `0x18` for AES.
> * provider: "microsoft base dss and diffie-hellman cryptographic provider"

This doesn't make sense. https://docs.microsoft.com/en-us/windows/win32/seccrypto/prov-dss-dh-provider-algorithms says it provides MD5 and SHA hashing, but not RC4.

**EDIT** diving a bit deeper in the docs, RC4 is there as well: https://docs.microsoft.com/en-us/windows/win32/seccrypto/microsoft-enhanced-dss-and-diffie-hellman-cryptographic-provider

---

Our 40-bit sample `XP-RC4-40bit-base-1.0_myhovercraftisfullofeels_.doc` show this with same debug outputs:
```
XP-RC4-40bit-base-1.0_myhovercraftisfullofeels_.doc : 
flags 4 providerType 1 provider "microsoft base cryptographic provider v1.0" algId 6801 algHashId 8004 keySize 40
```
That providerType 1, and the provider name, makes more sense: https://docs.microsoft.com/en-us/windows/win32/seccrypto/base-provider-algorithms says it does provide RC4 as well.

**Comment by magnumripper** [comment]
Like I said in original ML thread
> one problem is our current $oldoffice$ hash format: Instead of separately storing hash algorithm and key size, we have just a "type" which currently boils down to
> 
> 0 ... MD5, RC4, 40-bit
> 1 ... MD5, RC4, 40-bit
> 2 ... currently never used but treated as MD5, RC4, 40 bit
> 3 ... SHA1, RC4, 40-bit
> 4 ... SHA1, RC4, 128-bit
> 
> I would rather put the actual algHashId, algId and keySize figures in  there but to be backwards compatible that's a bad idea. So maybe I should just pick type 5 for "SHA1, RC4, 56-bit". This would also stop older versions of John from accepting it then handle it incorrectly - so probably better than repurposing type 2.
> 
> Also, until we know how to reproduce *creating* such document samples, or we crack one of Ian's, we can't be sure it's simply a matter of truncating to 56 instead of 40 all else equal: There may be some other magic involved.

**Comment by magnumripper** [comment]
Just to see the difference: A 128-bit key sample document show this debug output:
```
XP-RC4-128bit-Strong-Crypto_myhovercraftisfullofeels_.doc :
flags 4 providerType 1 provider "microsoft strong cryptographic provider" algId 6801 algHashId 8004 keySize 128
```
https://docs.microsoft.com/en-us/windows/win32/seccrypto/enhanced-provider-algorithms

For future tests, here's the patch for getting debug output from office2john:
```diff
diff --git a/run/office2john.py b/run/office2john.py
index a4bc3f51f..44ae929dc 100755
--- a/run/office2john.py
+++ b/run/office2john.py
@@ -2514,17 +2514,17 @@ def find_rc4_passinfo_doc(filename, stream):
         # RC4 CryptoAPI Encryption Header
         unpack("<I", stream.read(4))[0]  # encryptionFlags
         headerLength = unpack("<I", stream.read(4))[0]
-        unpack("<I", stream.read(4))[0]  # skipFlags
+        flags = unpack("<I", stream.read(4))[0]  # flags
         headerLength -= 4
         unpack("<I", stream.read(4))[0]  # sizeExtra
         headerLength -= 4
-        unpack("<I", stream.read(4))[0]  # algId
+        algId = unpack("<I", stream.read(4))[0]  # algId, 6801 == RC4
         headerLength -= 4
-        unpack("<I", stream.read(4))[0]  # algHashId
+        algHashId = unpack("<I", stream.read(4))[0]  # algHashId 8004 == SHA-1
         headerLength -= 4
         keySize = unpack("<I", stream.read(4))[0]  # keySize
         headerLength -= 4
-        unpack("<I", stream.read(4))[0]  # providerType
+        providerType = unpack("<I", stream.read(4))[0]  # providerType
         headerLength -= 4
         unpack("<I", stream.read(4))[0]  # unused
         headerLength -= 4
@@ -2541,6 +2541,7 @@ def find_rc4_passinfo_doc(filename, stream):
         else:
             sys.stderr.write("%s : invalid keySize %u\n" % (filename, keySize))
 
+        sys.stderr.write("%s : flags %x providerType %x provider \"%s\" algId %x algHashId %x keySize %u\n" % (filename, flags, providerType, provider, algId, algHashId, keySize))
         # Encryption verifier
         saltSize = unpack("<I", stream.read(4))[0]
         assert(saltSize == 16)
```

**Comment by magnumripper** [comment]
Note to self: MITM is not applicable for 56-bit: If you can get a hit every 40 minutes for 40-bit, it will be once every 5 years for 56-bit.

**Comment by magnumripper** [comment]
From [original post](https://www.openwall.com/lists/john-users/2021/04/27/1)
> Looking with a hex editor it seems to be a valid Word document, MS Word certainly recognises it and asks for the forgotten password, LibreOffice refuses with unsupported encryption.

FWIW, trying to open in macOS Pages nothing odd is seen, it just asks for a password.

Trying LibreOffice, the message is "The encryption method used in this document is not supported. Only Microsoft Office 97/2000 compatible password encryption is supported."

**Comment by magnumripper** [comment]
> Also, until we know how to reproduce _creating_ such document samples

For various hysterical reasons I expect this is how you would do so:
1. Install Windows XP or something like that in a VM
2. Install some version of Word or Office ~pre-2003~ <= 2003
3. Google '`"RC4" "40-bit" "56-bit" "registry"`' and try to find posts around the turn of the millennium that tells you how to change a few registry settings so you end up with 56-bit RC4 instead of 40-bit.
4. Save the document with a known password

This from recalling such registry settings changes suggestions for SSL. I believe [this document](https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-security/restrict-cryptographic-algorithms-protocols-schannel) is close to what I have in mind (it specifically mentions 56-bit RC4) but again that is about SSL and not about Word.

It might be that some Service Pack is needed as well - and it might even be hard or impossible to find it now.

**Comment by solardiz** [comment]
Didn't any versions of Windows/Office have 56-bit enabled by default? Maybe those intended solely for the US market, since the 40-bit limitation was because of export regulations.

**Comment by magnumripper** [comment]
> Didn't any versions of Windows/Office have 56-bit enabled by default? Maybe those intended solely for the US market, since the 40-bit limitation was because of export regulations.

"US domestic" versions always allowed 128-bit but ["Acquiring the 'U.S. domestic' version turned out to be sufficient hassle that most computer users, even in the U.S., ended up with the 'International' version"](https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States#PC_era). That quote was in context of 40-bit but it probably holds for 56-bit as well. The increase from 40-bit to 56-bit happened in 1999 but was soon followed by great simplifications leading to more-or-less what we have today:

"*In 2000, the Department of Commerce implemented rules that greatly simplified the export of commercial and open source software containing cryptography, including allowing the key length restrictions to be removed after going through the Commodity Classification process (to classify the software as "retail") and adding an exception for publicly available encryption source code.*"

**Comment by magnumripper** [comment]
[This Wikipedia page](https://en.wikipedia.org/wiki/Microsoft_Office_password_protection#History_of_Microsoft_Encryption_password) says
"*The default protection in Office XP and 2003 was not changed [from 40-bit], but an opportunity to use a custom protection algorithm was added. Choosing a non-standard Cryptographic Service Provider allows increasing the key length.*"

[This Elcomsoft page](https://blog.elcomsoft.com/2019/10/microsoft-office-encryption-evolution-from-office-97-to-office-2019/) says
"*While never fully lifting the export restrictions on cryptographic products, the export control restrictions became mostly nonexistent by 2000. However, Microsoft continued using weak encryption for several more years in Office 2000, XP and 2003 (...) Starting with Office 2003, Microsoft enables the use of external cryptographic service providers to increase key length. If an external cryptographic provider is used (which is rarely the case), one must attack the original plain-text password instead of recovering the 40-bit encryption key.*"

Office versions are listed [here (Wikipedia)](https://en.wikipedia.org/wiki/History_of_Microsoft_Office).

I take it the safest bet for creating a sample would be to use Office 2003 and tweak some registry setting. It's unclear how the OS version affects things (in particular, it's unclear to me where the "Cryptographic Service Provider" come from - maybe from the OS, maybe from a Service Pack, maybe from Office itself if newer than the OS) but to enable 56-bit I'd assume you would need at least Windows XP.

**Comment by magnumripper** [comment]
To anyone arriving at this page from seeing this message:
```
Note: The support for OldOffice type 5 is experimental and may be incorrect.
      For latest news see https://github.com/openwall/john/issues/4705
```

Please report here if you either managed to crack such document with current code, or was able to produce a sample with a known password that was or was not cracked.

We'd like such sample (with known password) to be added to [our samples collection here](https://github.com/openwall/john-samples) as well.
