### ISSUE TITLE
CircleCI (build) does not work with Fedora 34

### ISSUE THREAD

**Issue by ghost** [openwall/john#4711]
I expect the EOL of the current image (f32) to be at the end of this year. We need to think about an alternative. I'm thinking about moving upstream CircleCI to Ubuntu.

It fails like this:
```bash
./configure: This script requires a shell more modern than all
./configure: the shells that I found on your system.
./configure: Please tell bug-autoconf@gnu.org and john-users mailing
./configure: list at openwall.com about your system, including any
./configure: error possibly output before this message. Then install
./configure: a modern shell, or manually run the script under such a
./configure: shell if you do have one.
```
Env:
```bash
System information:
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Kernel Version: 4.15.0-1092-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
[...]
Starting container claudioandre/john:fedora.34
[...]
fedora.34: Pulling from claudioandre/john

eb97e9b3: Pulling fs layer 
Digest: sha256:f4c8ea1f4c54536069fdac96c0efa846bd0562ecd03f849ad603e1600ce1d07f02GB/1.602GBB

```
If fails here: `{ $as_echo "$as_bourne_compatible""$as_required" | as_run=a "$SHELL"; }` (line 234) 

There is a nasty and known bug in `seccomp`/`glibc` that makes a simple `test -x` fail inside a container. 
* Testing locally I can't reproduce (so it's not this bug).
* I bet Fedora tried to fix the bug and did it partially (because I can build a Docker image using F34 but still can't do the same using Ubuntu 21.04, where the bug is still open).

**Comment by solardiz** [comment]
Thank you for bringing this up, Claudio!

I find this confusing. The title says "does not work on Fedora 34", but then you show a failure on (apparently) "Ubuntu 18.04.5 LTS" and write that "I can build a Docker image using F34 but still can't do the same using Ubuntu 21.04". So reading this I don't know what issues there are and what works and what does not. I also don't understand what exactly "EOL of the current image (f32)" means. Would we somehow not be able to use it after EOL? Why not?

Anyway, if we move to Ubuntu then perhaps it'd be better investment of our time if we move to the latest LTS, which would be 20.04 now. Right?

Separately, I'd like us to start using GitHub Actions. We already do for passwdqc and LKRG. This doesn't mean we should stop using CircleCI while it still works well for us, but we'd have this alternative.

**Comment by ghost** [comment]
Ok, I updated the above statement. Ubuntu is the "host" machine.

I can't use `docker build` if the 'guest OS' is Ubuntu 21.04, I can run `docker build` (build a Docker image) if the 'guest OS' is Fedora 34.

**Comment by ghost** [comment]
> I also don't understand what exactly "EOL of the current image (f32)" means. Would we somehow not be able to use it after EOL? Why not?

The recent decommission of CentOS 6 has resulted in the removal of upstream repositories. I had to move away from CentOS6. So, maybe we will not able to keep using F32. 

Well, since the build is reproducible (I have everything installed inside the Docker image), we won't need to stop using F32. I stop maintaining the image, but I DO NOT remove it while someone else uses it (not even Docker Hub will do it). If people stop using it, the image can be removed **automatically**.

**Comment by solardiz** [comment]
Thanks. I still don't understand what this issue's title refers to - what "does not work on Fedora 34"?

Regarding the F32 image:

> If people stop using it, the image can be removed **automatically**.

Do you know after which period of non-use this happens?

**Comment by ghost** [comment]
> I still don't understand what this issue's title refers to - what "does not work on Fedora 34"?

IMO, CircleCI itself. (Maybe) they shouldn't be using Ubuntu 18 (since I can't reproduce using Ubuntu 20.04) locally. I need to run other tests inside Circle, but they should probably update to a new default image.

> Do you know after which period of non-use this happens?

No. Docker (Hub service) has postponed this new rule.

**Comment by solardiz** [comment]
If I finally correctly understand what you meant, maybe the issue title should be "Our CircleCI build uses Fedora 32, which will be EOL'ed soon". Fedora 34 is merely what you thought would be the most straightforward upgrade, and isn't otherwise relevant.

**Comment by ghost** [comment]
I moved the Docker images to (Openwall's) GitHub Container Registry. These images should be considered unmaintained.

I am not re-purposing my Ubuntu images to perform the tasks CircleCI performs using Fedora because I created them for another purpose (they would need to be changed).

Maybe it's time to give up Wine (at least Wine 32 which is tied to F32).

**Comment by ghost** [comment]
This has been fixed (CircleCI has updated its base distro/runtime). 

Since F30 and F32 are now EOL, it's up to you to decide what should be done.
