### ISSUE TITLE
ssh2john working only in Python 2

### ISSUE THREAD

**Issue by W-Hamra** [openwall/john#4719]
I see you guy have already fixed some of the scripts in #4641 , there's also ssh2john that's working only in python2, though I think that could be only a recent issue. In Python 3 I get: 
`AttributeError: module 'base64' has no attribute 'decodestring'`

Which to my understanding is due to `decodestring` getting deprecated and removed in Python 3.9.

**Comment by ghost** [comment]
I'm afraid you are using an outdated version. This was fixed at 660de879bd06a2edbe228b7c742d4a98ec989248. Could you please confirm that you are using the latest source from this repo?

I'm closing this. If you think I’ve misunderstood your problem, please reopen it.
