### ISSUE TITLE
--make-charset doesn't work correctly together with --format

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4725]
The `--format` option is simply ignored. After quite some time bisecting (due to build problems of very old versions of Jumbo vs. newer OpenSSL) I believe the current behavior stems from 7264c19d back in March 2017, but the initial problem was 0ceedb2 of December 2016(!). Between those versions, using `--make-charset` *with*  `--format` actually still worked fine, but leaving `--format` option out did not (it hung indefinitely). When I fixed it I apparently wasn't even aware that `--make-charset` was supposed to work together with `--format`.

**Comment by magnumripper** [comment]
I have yet to digest those two patches... it might take me a while to figure out what was intended and what was b0rked.

**Comment by magnumripper** [comment]
Re-applying this fixes the problem
```diff
diff --git a/src/loader.c b/src/loader.c
index 73ad84ebf..d55e39590 100644
--- a/src/loader.c
+++ b/src/loader.c
@@ -2169,6 +2169,10 @@ static void ldr_show_pot_line(struct db_main *db, char *line)
        ciphertext = ldr_get_field(&line, db->options->field_sep_char);
 
        if (line) {
+/* If just one format was forced on the command line, insist on it */
+               if (!fmt_list->next && !fmt_list->methods.valid(ciphertext, fmt_list))
+                       return;
+
                pos = line;
                do {
                        if (*pos == '\r' || *pos == '\n') *pos = 0;
```
However, it does not handle cases like `--format=rar,zip` (accepting those two for makechr but no others) - that will again ignore the format option. I guess that was never supported but I'd like to see if we can do that as well. Or am I creating a new footgun with that?

**Comment by solardiz** [comment]
> does not handle cases like `--format=rar,zip` (accepting those two for makechr but no others) - that will again ignore the format option.

We don't have to support this, but if we don't support it we should print a message, not ignore the option silently.
