### ISSUE TITLE
Support building and repackaging without unRAR

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4731]
hashcat 6.2.1 was just released making their use of unrar optional. Perhaps we should make ours optional, too. This is because of the unrar license, which some distributions/packagers find unsuitable: https://github.com/hashcat/hashcat/issues/2614

**Comment by magnumripper** [comment]
Not sure if/how it matters but I think they used the original unrar, while we use ClamAV's unrar.

**Comment by solardiz** [comment]
What we use carries this notice:

```
 *  Copyright (C) 2005-2006 trog@uncon.org
 *  Patches added by Sourcefire, Inc. Copyright (C) 2007-2013
 *
 *  This code is based on the work of Alexander L. Roshal (C)
 *
 *  The unRAR sources may be used in any software to handle RAR
 *  archives without limitations free of charge, but cannot be used
 *  to re-create the RAR compression algorithm, which is proprietary.
 *  Distribution of modified unRAR sources in separate form or as a
 *  part of other software is permitted, provided that it is clearly
 *  stated in the documentation and source comments that the code may
 *  not be used to develop a RAR (WinRAR) compatible archiver.
```

As I understand, the "may not be used to" restriction is incompatible with the FSF's free software definition and with OSI's Open Source definition. It is also incompatible with GNU GPL, which is why we had to add an exception to ours:

```
As a special exception to the GNU General Public License terms,
permission is hereby granted to link the code of this program, with or
without modification, with any version of the OpenSSL library and/or any
version of unRAR, and to distribute such linked combinations.  You must
obey the GNU GPL in all respects for all of the code used other than
OpenSSL and unRAR.  If you modify this program, you may extend this
exception to your version of the program, but you are not obligated to
do so.  (In other words, you may release your derived work under pure
GNU GPL version 2 or later as published by the FSF.)

(This exception from the GNU GPL is not required for the core tree of
John the Ripper, but arguably it is required for -jumbo.)
```

Now we've made OpenSSL an optional dependency for JtR, and besides it was external rather than bundled (so less of a problem). We really could want to make unRAR optional as well (or find a free software reimplementation? or maybe there's a relicensed upstream one by now?)

That said, I think @xvitaly's "Fedora, Debian and most of other GNU/Linux distributions strictly forbid shipping non-free components even in source tarballs." isn't literally true. Surely there are non-free components (binary blobs for device firmware) inside the Linux kernel source tree, and only some derivative distros, not the main Fedora and Debian distros, strip those out. It may be that these distros' current line is drawn between host-side code (must be free software) vs. device-side code, though.

**Comment by magnumripper** [comment]
So if we add `--without-unrar` to `configure` we might be good? That way a distro can build a binary without the unrar code - but they'd still not be able to distribute a source package unless they remove `unrar*.[ch]` from it (which would work fine though - BTW we should have `configure` detect such missing files and infer `--without-unrar` from it with a warning).

Edit: We should also ensure that the RAR formats still work, only with limited functionality (only stored files or header-protected archives). And perhaps they (and/or rar2john) should emit some warning/information about the situation and how to fix it.

**Comment by magnumripper** [comment]
> they'd still not be able to distribute a source package unless they remove unrar*.[ch] from it

According to https://github.com/hashcat/hashcat/issues/2614#issuecomment-841451936 this would be fine and normal.

**Comment by magnumripper** [comment]
> configure (...) with a warning

I guess we'd make it a line like these
```
Optional libraries/features found:
Memory map (share/page large files) ........ yes
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
OpenCL support ............................. yes
Generic crypt(3) format .................... yes
OpenSSL (many additional formats) .......... yes
libgmp (PRINCE mode and faster SRP formats)  no
128-bit integer (faster PRINCE mode) ....... yes
libz (pkzip and some other formats) ........ yes
libbz2 (gpg2john extra decompression logic)  yes
libpcap (vncpcap2john and SIPdump) ......... yes
OpenMPI support (default disabled) ......... no
ZTEX USB-FPGA module 1.15y support ......... no
```
Something like
```
unrar code (for full RAR formats) .......... yes/no
```

**Comment by magnumripper** [comment]
Another possibility is we could ditch the ClamAV unrar code (which was chosen because it's C and not C++) and instead port "unrar-free" (eg. https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/unrar-free/1:0.0.1+cvs20140707-4~build0.16.04.1/unrar-free_0.0.1+cvs20140707.orig.tar.gz) to plain C. It's GPLv2 but it does have a comment "Can't handle some archives in  the RAR 3.0 format natively" so that might end up more limited than our current code (we might want to dig into that statement and see what it means exactly).

BTW our current code is a modified version of ClamAV's in that it only inflates to calculate the CRC - the full inflated data is never stored. Apart from saving memory I presume it's also good for performance.

**Comment by magnumripper** [comment]
A third possibility might be to nick code from unar (not unrar but "The Unarchiver"), which is LGPL and doesn't seem to have any functionality limitation. We *might* even be able to dlopen its library (so the unrar-or-not could be a runtime choice) but then we'd no longer just inflate-to-CRC.

https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/unar/1.10.1-2build3/unar_1.10.1.orig.tar.xz

**Comment by solardiz** [comment]
> unrar code (for full RAR formats) .......... yes/no

I think that's what we should do for now. I think switching to a different/external unrar code base is too much of a change now - maybe something to consider after the next release.

We could also want to research how distros are packaging ClamAV. Do they exclude unrar, and how, or do they find it not a problem, or have they not noticed it is a problem yet?

**Comment by xvitaly** [comment]
> Surely there are non-free components (binary blobs for device firmware) inside the Linux kernel source tree, and only some derivative distros, not the main Fedora and Debian distros, strip those out.

We have a special exception for firmware blobs. No other non-free components are allowed: https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/

**Comment by xvitaly** [comment]
> We could also want to research how distros are packaging ClamAV. Do they exclude unrar, and how, or do they find it not a problem, or have they not noticed it is a problem yet?

Fedora removes it from sources: https://src.fedoraproject.org/rpms/clamav/blob/rawhide/f/clamav.spec#_52

**Comment by magnumripper** [comment]
Thanks Vitaly. I'll just implement `--without-unrar` (including inferring it from missing files) soon then. Likely this week.

**Comment by magnumripper** [comment]
Saw this warning now, not many compilers show it. Better enclose that function in `#if HAVE_UNRAR`
```
rar_common.c:491: warning: 'check_huffman' defined but not used
```
