### ISSUE TITLE
wordlist change/grew as we read it; but it did not - integer overflow?

### ISSUE THREAD

**Issue by BotPass** [openwall/john#4734]
### problem ###
I used a big file with more than 2^32 lines, forks and I get a lot of "wordlist change as we read it" and "wordlist grew as we read it" messages. That was strange because it was a local file and no other application used it. The size and timestamp of the file did not change and the problem was reproducible.
Not all forks run properly.

### assumed reason ###
After search for the messages I found it in src/wordlist.c in function `do_wordlist_crack`.
Conditions are `if (i > my_size) {`for error "grew" and `if (nWordFileLines != myWordFileLines)` for warning "changed".
Now looking at the data types:
```
static int64_t nWordFileLines;
int i,
long my_size
unsigned int myWordFileLines
```
Thus only `nWordFileLines` has a fixed size while (as far as I know) `i`, `my_size` and `myWordFileLines` differ depending on multiple circumstances; e.g. `my_size` should be 32 bit under 64 bit Windows (using LLP64) while it is 64 bit under 64 bit Linux (using LP64). It's probably more complicated with cygwin and cross build with mingw under Linux for Windows.

But in this case my system was Linux. Thus the second one, the changed warning could be explained because `myWordFileLines` is 32 bit (unsigned), `nWordFileLines` is 64 bit (signed) and the number of lines was to big for `myWordFileLines` but not for `nWordFileLines`.

The possible explanation for the first one -- the grew error -- is more complicated. Because even if there is an overflow in `i` it could not lead to be bigger than `my_size`. I am not sure if this is the problem, but the values of `i` and `my_size` are updated based on `skip` while `skip` based on `for_node` (both 32 bit signed). For `i` `for_node` is based on `myWordFileLines` and for `my_size` it is based on `nWordFileLines`. Thus they are probably updated differently.

### workaround ###
For test purpose all those variables (and some other variables) were changed to 64 bit. Now no of these message appear and it seems that all forks were running.

Because I only looked up the source code and did not debug I am not sure if the overflow is really the problem here. But in my case the change seems to fix the problem. However there could be other negative side effects by this change.

**Comment by magnumripper** [comment]
Thank you for reporting. We've tried to support whatever larger-than-32-bit `seek` and similar functions is available but we might have missed the case where the number of *lines* overflows 32-bit signed.

Just for the record, please post the output of `./john --list=build-info`

**Comment by BotPass** [comment]
Ubuntu 20.04 is used
```
Version: 1.9.0-jumbo-1+bleeding-2f5b0ef335 2021-04-25 20:56:40 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 9.3.0
GNU libc version: 2.31 (loaded: 2.31)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 01010106f
OpenSSL 1.1.1f  31 Mar 2020
GMP library version: 6.2.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 40 ns
Total physical host memory: [...] GiB
Available physical host memory: [...] GiB
Terminal locale string: [...].UTF-8
Parsed terminal locale: UTF-8
```

**Comment by magnumripper** [comment]
@BotPass could you please verify that #4764 fixes your problems? I couldn't reproduce those warning messages (it probably only surfaces for certain sizes) but that PR should hopefully fix it.

**Comment by BotPass** [comment]
Way to reproduce it is a good point. It seems that just a big wordlist is not enough. But after using a wordlist with billions of lines and rules ALL I get messages like 
```
Error: wordlist grew as we read it - aborting
Warning: wordlist changed as we read it
```
in the "old" version I used before.

With your version and the same start arguments, the messages were gone. 

Thus yes, I would say this fix it. Thank you!
