### ISSUE TITLE
pdf2john - Unsupported PDF files?

### ISSUE THREAD

**Issue by solipsistinc** [openwall/john#4739]
1. Received a PDF file, and tried to extract the hash using pdf2john (i.e. pdf2john pdfile.pdf > output.hash)
2. Output was unconventional `$pdf$2*3*128*4294967232*1*16*XXXX*32*XXXX*32*XXXX`
3. XXXX has been redacted
4. The "4294967232" seems to be an error.
5. When I run john with this hash, I get the "No password hashes loaded" error even if I specify format as PDF.
6. When I try other encrypted PDF files the above steps work (and the 4294967232 is a signed #).

Could this be a pdf format that is unsupported?

Build info
Version: 1.9.0-jumbo-1
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is 
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by ghost** [comment]
Could you test your use case using the most recent version from this repository? The `pdf2john` tool was changed AFTER the launch of the jumbo-1 release.

**Comment by solardiz** [comment]
@solipsistinc Since you seem to be on Windows, you can download a recent Windows build through the "Download Windows Build" badge in `README.md` in this repo. This currently points to https://github.com/openwall/john-packages/releases/tag/jumbo-dev and the file to download would be `winX64_1_JtR.7z`. Alternative, you can build from source. Thanks!

**Comment by solipsistinc** [comment]
Thanks for your responses above. 

Yes I downloaded the latest Windows build and repeated the above steps. 

The output is no different from previously described. 

I just realised the hash above was auto-formatted. Please see below for the correct one.

$pdf$2(asterisk)3(asterisk)128(asterisk)4294967232(asterisk)1(asterisk)16(asterisk)(32 chars)(asterisk)32(asterisk)(64 chars)(asterisk)32(asterisk)(64 chars)

So the issue seems to be the "4294967232", some kind of overflow?

Build info
Version: 1.9.0-jumbo-1+bleeding-a46120a 2021-05-27 21:56:13 -0300
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is 
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 10.2.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010106f
OpenSSL 1.1.1f  31 Mar 2020
GMP library version: 6.2.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 1000
Using times(2) for timers, resolution 1 ms
HR timer: QueryPerformanceCounter(), latency 100 ns
Total physical host memory: 32711 MiB
Available physical host memory: 26379 MiB
Terminal locale string: C.UTF-8
Parsed terminal locale: UTF-8

**Comment by ghost** [comment]
> So the issue seems to be the "4294967232", some kind of overflow?

Yes, it is failing at https://github.com/openwall/john/blob/bleeding-jumbo/src/pdf_fmt_plug.c#L145

```
$ ../run/john ~/hash.txt --format=pdf

Using default input encoding: UTF-8
V: 2, P: 3, length: 128, res: 128, P: 4294967232, Failed isdec_negok(4294967232)
```

**Comment by frank-dittrich** [comment]
May be this can be unsigned instead, so the max. value would be 4294967295?

**Comment by magnumripper** [comment]
> $pdf$2(asterisk)3(asterisk)128(asterisk)4294967232(asterisk)1(asterisk)16(asterisk)(32 chars)(asterisk)32(asterisk)(64 chars)(asterisk)32(asterisk)(64 chars)

So a crippled test vector would be
```
$pdf$2*3*128*4294967232*1*16*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*32*bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb*32*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
```

**Comment by magnumripper** [comment]
For whatever reason, we do have test vectors in that format where this field is actually negative, such as `*-4*` and `*-1028*`. There are also older hashes (commented as "following are old-style hashes") that have a negative field near the end.

I guess we need to search for older commits and discussions so we don't break backwards compatibility.

BTW 4294967232 should correspond to -64, I assume manually replacing it in `output.hash` will work around the problem.

**Comment by kenspeckle1** [comment]
That field corresponds to the permissions field (/P) in the [PDF Specs page 117](https://web.archive.org/web/19961219053721if_/http://www.adobe.com:80/supportservice/devrelations/PDFS/TN/PDFSPEC.PDF#page=117) . 
As such it should be a 32 bit unsigned int. But also the bits 7-32 need to be set to 1. So if a PDF library is using int for this field, it will be interpreted as a negative value which can result in wrong string serializations.

These negative values also occur in the wild. 
I created a new test PDF with `pandoc` and encrypted it with `qpdf` and the /P field was set to -4 (open the attached file and search for `b1db56a883cab5a22dd5fc390618a0f8e16cab8af14e67ccba5f90837aac898b` in a text editor.
[test_enc.pdf](https://github.com/openwall/john/files/8453115/test_enc.pdf)
 
I had not time to look at the newer specs, but I think the best option would be to handle both the signed and unsigned cases.

**Comment by magnumripper** [comment]
Thanks. Trying that file with current Jumbo tree, `pdf2john` will output `-4` for that field and the PDF format will accept it and crack it in a jiffie.
So what was the original problem? Can someone post a PDF that will end up with a large unsigned int from pdf2john?

**Comment by kenspeckle1** [comment]
I have a file similar to the original author with the /P value beeing a unsinged 32 bit value but sadly I cannot post a complete file as it contains sensitive data.
But here is an excerpt of the relevant data from the file:
```
trailer << /Size 27 /Root 2 0 R /Info 1 0 R /Encrypt << /Filter /Standard
/V 1
/R 2
/O <31b9921fb81d7310c5c8b0e37124713c4ceb217a8a73a73186d3b711406b17ea>
/U <afd2e437fb31ae88a193ce317b684b964e0445c2e0b9024bc63b875d086c10a6>
/P 4294967239
>>
>>
```

I will have a look if I can provide a different sample file.

**Comment by kenspeckle1** [comment]
@magnumripper Here is a valid test file containing a permission value of 4294967239 resulting in the hash `$pdf$1*2*40*4294967239*1*0**32*585e4cc4113bbd8ff4012dce92dd7df1e1216fb630b29cf5aeea10a820066c26*32*b1db56a883cab5a22dd5fc390618a0f8e16cab8af14e67ccba5f90837aac898b`
[test_with_unsinged_int.pdf](https://github.com/openwall/john/files/8453847/test_with_unsinged_int.pdf)
Password is 123456

Edit:
On a side note: I noticed that most encryption tools indeed output signed values, even the official Adobe one. The only library which outputs unsigned values which I could find in this short period was [Prawn](https://github.com/prawnpdf/prawn) (which I used to created this test file). Perhaps there is some more info in the specs and indeed only negative values are valid.

**Comment by magnumripper** [comment]
Great, thanks!

**Comment by magnumripper** [comment]
That last sample also has an id length of zero, which also has to be allowed.
