### ISSUE TITLE
Solarwinds OpenCL format crashes on OpenCL alloc on AMD Vega

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4744]
```
Benchmarking: solarwinds-opencl, SolarWinds Orion [PBKDF2-SHA1 OpenCL]... 0: OpenCL CL_INVALID_BUFFER_SIZE (-61) error in opencl_solarwinds_fmt_plug.c:131 - Error allocating mem out
```
Can't recall seeing a crash during alloc before, should be looked into.

**Comment by solardiz** [comment]
> Can't recall seeing a crash during alloc before

Maybe it's the first time you ran this test with a concurrent job on the GPU running (but paused)? That specific concurrent job wasn't supposed to be consuming a lot of GPU memory, though (it had GWS of 16384, which is low).

**Comment by magnumripper** [comment]
Good point, I'll check this later then. That message doesn't really say there wasn't enough available though, it's more like we requested some invalid size such as a negative one. We'll see.

BTW and note to self: If the `0:` was intending to report node number, it got it off by one. And for that matter I wasn't even using fork or MPI so it should better be left out.

**Comment by solardiz** [comment]
> If the `0:` was intending to report node number, it got it off by one. And for that matter I wasn't even using fork or MPI so it should better be left out.

Yes, please look into that as well. Thanks!

**Comment by magnumripper** [comment]
I first got this problem on a `--test --format=opencl` run, but specifying that format alone yields the same result.

**Comment by magnumripper** [comment]
Problem went away with no change. It probably actually ran out of memory somehow.
