### ISSUE TITLE
Zip2john empty output

### ISSUE THREAD

**Issue by Hollerith98T** [openwall/john#4768]
When I call the "zip2john" command on the attached zip file, the result is always an empty text file.

I tried using the latest version of John The Ripper but also trying others, the result doesn't change.

If I call the same command on other zip files I can easily get the hash.

I kindly ask for your opinion.

About build-info:
Version: 1.9.0-jumbo-1
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is /run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

[demo.zip](https://github.com/openwall/john/files/6822469/demo.zip)

**Comment by ghost** [comment]
The good news is that it is fixed in latest bleeding code (you are using the latest released john):

```
$ john-the-ripper.zip2john Downloads/demo.zip > demo-hash.txt
ver 1.0 efh 5455 efh 7875 demo.zip/Package_3070509_20180627124501.zip PKZIP Encr: 2b chk, TS_chk, cmplen=1145311, decmplen=1145299, crc=C3612193 ts=65A1 cs=65a1 type=0
```

[demo-hash.txt](https://github.com/openwall/john/files/6823342/demo-hash.txt)

John can then load and, eventually, crack it (do you know the password so we can test it?) :

```
$ john demo-hash.txt 
Using default input encoding: UTF-8
Loaded 1 password hash (PKZIP [32/64])
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:/snap/john-the-ripper/current/run/password.lst
Proceeding with incremental:ASCII
0g 0:00:00:12  3/3 0g/s 1040Kp/s 1040Kc/s 1040KC/s cb0232..cb3c14
Session aborted
```

**Comment by ghost** [comment]
BTW: there is a link to download the latest development build from this repo, at the main page. So, you can test it yourself.

![image](https://user-images.githubusercontent.com/1702923/125797087-2f3e8011-fb4e-4ebe-bc0b-34ecc12709fa.png)
