### ISSUE TITLE
Mismatch of bcrypt salt revisions between input and potfile

### ISSUE THREAD

**Issue by its5Q** [openwall/john#4769]
- The output of `./john --list=build-info`.
```Version: 1.9.0-jumbo-1+bleeding-2e6eba49f 2021-07-07 17:16:06 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is /home/*****/src/john/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 10.3.0
GNU libc version: 2.32 (loaded: 2.32)
Crypto library: OpenSSL
OpenSSL library version: 01010106f
OpenSSL 1.1.1f  31 Mar 2020
GMP library version: 6.2.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 40 ns
Total physical host memory: 125 GiB
Available physical host memory: 124 GiB
Terminal locale string: en_US.UTF-8
Parsed terminal locale: UTF-8
```
- The problem
With bcrypt format, there is a mismatch between the input hash and the hash written in the potfile. Running this command: `john --format=bcrypt --wordlist="wordlist.txt" --pot="potfile.txt" "hashes.txt"`, where the contents of `hashes.txt` is `$2y$10$SVO91fOz/flQ2ZeHrKPnyu2qRKJlCFhDCnwW0ReCQWkWg7SgvJjb.` gives the following output in potfile: `$2a$10$SVO91fOz/flQ2ZeHrKPnyu2qRKJlCFhDCnwW0ReCQWkWg7SgvJjb.:1234`, but I think it's expected to be the same input hash, with the same salt revision

**Comment by ghost** [comment]
This is not a problem in itself (unifying when saving in `.pot` file). In fact, it's on purpose, see https://github.com/openwall/john/commit/d3998824d5538c8a3e46c7494d891df6a9dca5a1.

If you are having problems using bcrypt format, please, specify it in more detail.

**Comment by solardiz** [comment]
Hi @its5Q. @claudioandre-br is correct - this is a feature, not a bug. We can see how this can be confusing, but the alternative was differently confusing and problematic. It's with several hash types (not only bcrypt) that we have to perform some unification (or in some cases even splitting the hashes in half, such as for LM and bigcrypt) when storing them in `john.pot` to avoid other subtle issues and limitations. Overall, there's no guarantee that `john.pot` contains exact and complete hashes for the cracked passwords. Instead, you're supposed to use `john --show` to have proper and reliable matching of your hashes to what's been cracked. Makes sense?
