### ISSUE TITLE
A question about remote tasking windows via linux

### ISSUE THREAD

**Issue by jamieduk** [openwall/john#4771]
Hi great job i love it, currently im running linux web server and wonder how much faster it would be on windows as thats where the gpu is, is there a way i can task the windows side to crack it on behalf of a linux web server using apache2 and php 7.2 ?

**Comment by solardiz** [comment]
Hi @jamieduk. We appreciate your appreciation, but we currently use GitHub issues to track literal issues with the project, not to provide user support. Please feel free to join the john-users mailing list (see instructions on John the Ripper homepage) and post the question in there. If/when you do that, you'll also need to provide more detail on what you have and what you're trying to do. Thanks.
