### ISSUE TITLE
Can I run john with `john` command?

### ISSUE THREAD

**Issue by f0rizen** [openwall/john#4774]
### How can I run john with `john` (not /full/path/john)?

I use:
- OS: Fedora Workstation 34
- Shell: zsh 5.8

I tried:
`$ sudo cp ~/tools/john/run/john /usr/bin`
`$ john`
`Error: Cannot find John home. Invoke the program via full or relative pathname.`
`For example, /full/path/john or path/john, or set and use a shell alias.`

Build information:
`Version: 1.9.0-jumbo-1+bleeding-e791b84e0 2021-07-12 15:50:15 -0300`
`Build: linux-gnu 64-bit x86_64 AVX2 AC OMP`
`SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1`
`CPU tests: AVX2`
`$JOHN is /home/f0rizen/tools/john/run/`
`Format interface version: 14`
`Max. number of reported tunable costs: 4`
`Rec file version: REC4`
`Charset file version: CHR3`
`CHARSET_MIN: 1 (0x01)`
`CHARSET_MAX: 255 (0xff)`
`CHARSET_LENGTH: 24`
`SALT_HASH_SIZE: 1048576`
`SINGLE_IDX_MAX: 32768`
`SINGLE_BUF_MAX: 4294967295`
`Effective limit: Max. KPC 32768`
`Max. Markov mode level: 400`
`Max. Markov mode password length: 30`
`gcc version: 11.1.1`
`GNU libc version: 2.33 (loaded: 2.33)`
`Crypto library: OpenSSL`
`OpenSSL library version: 0101010bf`
`OpenSSL 1.1.1k  FIPS 25 Mar 2021`
`File locking: fcntl()`
`fseek(): fseek`
`ftell(): ftell`
`fopen(): fopen`
`memmem(): System's`
`times(2) sysconf(_SC_CLK_TCK) is 100`
`Using times(2) for timers, resolution 10 ms`
`HR timer: clock_gettime(), latency 186 ns`
`Total physical host memory: 7848 MiB`
`Available physical host memory: 4027 MiB`
`Terminal locale string: en_US.UTF-8`
`Parsed terminal locale: UTF-8`

**Comment by f0rizen** [comment]
So, can I do it without aliasing john to /usr/bin/john? (like `alias john='/usr/bin/john'`)

**Comment by ghost** [comment]
Thank you for participating.

Yes, you can. From doc/install:
```
System-wide installation is also supported, but it is intended for use
by packagers of John for *BSD "ports", Linux distributions, etc., rather
than by end-users.  (If you're in fact preparing a package of John,
please refer to the JOHN_SYSTEMWIDE setting in src/params.h or the
Jumbo/autoconf-specific README-DISTROS.)
```

I can think of other ways to achieve this without a system-wide build, using your OS skills.  Anyway, the GitHub issues are primarily to keep track of bugs or other shortcomings of our software, and fix those. It is not to help individual users with their specific tasks. To receive user support from the community, please use the john-users mailing list instead.

**Comment by f0rizen** [comment]
Thanks a lot!

**Comment by solardiz** [comment]
I typed the below before Claudio's comment above appeared. I am posting this anyway as I think Claudio's comment doesn't make it sufficiently clear that installing `john` system-wide without being a distro is _really_ not something you should do.

Our use of GitHub issues is to track literal issues with the project, not to provide user support. There's the john-users mailing list for the latter. That said,

The short answer is that unless you're packaging JtR for a distro, you really shouldn't be installing `john` on the system globally. You'd run into other issues by doing so (e.g., where would the `john.pot` file be and how would `john` be able to write into it). Just run `john` from the tree where you built it, which avoids those issues.

If you're in fact packaging JtR for a distro, then you can do a system-wide build and package that. This can be non-trivial.
