### ISSUE TITLE
error while using --format=raw-sha256 flag

### ISSUE THREAD

**Issue by resteex0** [openwall/john#4775]
john --format=raw-sha256 --wordlist=/home/go/ww.mnf.txt hash.txt                                                                                              4 ⚙

Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA256 [SHA256 128/128 SSE2 4x])
No password hashes left to crack (see FAQ)

**Comment by ghost** [comment]
Looks like you cracked all hashes. 

John loads a hash and it was cracked. You can use the `--show` option to confirm this.
