### ISSUE TITLE
Newbie - Opening single file

### ISSUE THREAD

**Issue by CSCheng1** [openwall/john#4776]
hi, all

i am a very new user.
i tried to open a password zip file containing multiple password protected files.

after running "zip2john.exe" to the file, here is the result i got:
   ver 2.0 Document.zip/Allison 2008.pdf PKZIP Encr: cmplen=209845, decmplen=224352, crc=F4CFB701
   ver 2.0 Document.zip/Banerjee et al 1999.pdf PKZIP Encr: cmplen=1163508, decmplen=1233575, crc=5790C486
   ver 2.0 Document.zip/Collins & Lanza 2010 Ch 2 & 3.pdf PKZIP Encr: cmplen=3804810, decmplen=3982820, crc=B4CE574F
   ver 2.0 Document.zip/Graham et al 2012.pdf PKZIP Encr: cmplen=626038, decmplen=916941, crc=3F97E32F
   NOTE: It is assumed that all files in each archive have the same password.
   If that is not the case, the hash may be uncrackable. To avoid this, use
   option -o to pick a file at a time.

could anyone help me how to extract the invidual files using JTR?
what comment should I use?

thank you.

**Comment by magnumripper** [comment]
This is not a support forum, but anyway the answer was right in front of you, in the text "*use option -o to pick a file at a time*". As always, quotes are needed for file names with spaces. For example:
```
./zip2john -o "Allison 2008.pdf" > hashes.txt
./zip2john -o "Banerjee et al 1999.pdf" >> hashes.txt
./zip2john -o "Collins & Lanza 2010 Ch 2 & 3.pdf" >> hashes.txt
./zip2john -o "Graham et al 2012.pdf" >> hashes.txt
./john hashes.txt
```

BTW be sure to use the latest zip2john (from here) - it had important updates since the 1.9.0-jumbo-1 release.
