### ISSUE TITLE
FORMAT_TAG for oracle11 hash format

### ISSUE THREAD

**Issue by rom1sqr** [openwall/john#4791]
oracle and oracle12c have a FORMAT_TAG, but oracle11 does not.
it's pretty common to dump hashes for several versions at a time into
the same file, and the autodetect works for the two first ones, but for
the latter, you need to run john with a mandatory --format=oracle11
separately (a bit of a pain).

i'm currently working on a pull request to add that feature to the oracle11
format source code. any warning about this? any "DONT!"?

thanks

**Comment by ghost** [comment]
Thanks for working on this. 

I can't think of anything. Well, please take a look at https://github.com/openwall/john/blob/bleeding-jumbo/CONTRIBUTING.md

**Comment by rom1sqr** [comment]
Ok! You'll find it there: #4792

**Comment by magnumripper** [comment]
> the autodetect works for the two first ones, but for
> the latter, you need to run john with a mandatory --format=oracle11
> separately (a bit of a pain).

It autodetects for me
```
$ echo B9E7556F53500C8C78A58F50F24439D79962DE68117654B6700CE7CC71CF > test.in
$ ../run/john test.in -mask:?d?d?l
Using default input encoding: UTF-8
Loaded 1 password hash (oracle11, Oracle 11g [SHA1 256/256 AVX2 8x])
Press 'q' or Ctrl-C to abort, almost any other key for status
11g              (?)     
1g 0:00:00:00 DONE (2021-08-30 17:33) 100.0g/s 170400p/s 170400c/s 170400C/s 57k..31g
No remaining hashes
```
Did I misunderstand what you are saying?

**Comment by magnumripper** [comment]
> It autodetects for me

As discussed in #4792, some ways of extracting hashes will produce lower-case hex hashes, which was probably the original problem. The format tag itself didn't solve the original problem but has other advantages.
