### ISSUE TITLE
pfSense/OPNsense user hash extract script

### ISSUE THREAD

**Issue by privwolf** [openwall/john#4806]
Hello,
I would like to create a pfSense/OPNsense hash extract script PR

**Comment by ghost** [comment]
Good. JtR developers encourage you to contribute. 

- Get some tips at https://github.com/openwall/john/blob/bleeding-jumbo/CONTRIBUTING.md. 
- Take a look at the source code for other 2john tools (examples).
- If you choose Python, please make it compatible with 3.x versions.

Once you have a tool that works, post a draft PR and ask for guidance in the review process.

**Comment by solardiz** [comment]
This is taken care of in #4807. Thank you for the contribution, @privwolf!
