### ISSUE TITLE
Possible problem in a couple of internal-mask formats

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4816]
In some formats (the below is oldoffice-opencl), we have this at the end of `set_key()`:
```c
	/* Early partial transfer to GPU */
	if (index && !(index & (256*1024 - 1))) {
		HANDLE_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], cl_saved_key, CL_FALSE, key_offset, key_idx - key_offset, saved_key + key_offset, 0, NULL, NULL), "Failed transferring keys");
		key_offset = key_idx;
		HANDLE_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], cl_saved_idx, CL_FALSE, idx_offset, 4 * index - idx_offset, saved_idx + (idx_offset / 4), 0, NULL, NULL), "Failed transferring index");
		idx_offset = 4 * index;
		HANDLE_CLERROR(clFlush(queue[gpu_id]), "failed in clFlush");
		new_keys = 0;
	}
```

Then we have this in `crypt_all()`. Note the `if (!mask_gpu_is_static)` thing there:
```c
	if (new_keys || ocl_autotune_running) {
		/* Self-test kludge */
		if (idx_offset > 4 * (gws + 1))
			idx_offset = 0;

		BENCH_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], cl_saved_key, CL_FALSE, key_offset, key_idx - key_offset, saved_key + key_offset, 0, NULL, multi_profilingEvent[0]), "Failed transferring keys");
		BENCH_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], cl_saved_idx, CL_FALSE, idx_offset, 4 * (gws + 1) - idx_offset, saved_idx + (idx_offset / 4), 0, NULL, multi_profilingEvent[1]), "Failed transferring index");
		if (!mask_gpu_is_static)
			BENCH_CLERROR(clEnqueueWriteBuffer(queue[gpu_id], buffer_int_key_loc, CL_FALSE, 0, 4 * gws, saved_int_key_loc, 0, NULL, NULL), "failed transferring buffer_int_key_loc.");

		new_keys = 0;
	}
```
I think this means we might theoretically miss transfering `saved_int_key_loc` in rare cases: If last call to `set_key()` was with index 262144 (or a multiple of it), a partial transfer sets off and `new_keys` becomes zero. If that was actually the very last key, `crypt_all()` will not transfer `saved_int_key_loc`.

However, if we did call `set_key(262144)` it's not likely it was the last key in a batch (KPC would need to be 262145, or 0x40001, which is very odd). BUT it could happen in the very end of a session (such as wordlist end) or possibly when running single mode but that can't be used with internal mask so shouldn't be a problem. Anyway I think we need to fix this.

As far as I have found so far, only oldoffice-opencl, cryptoSafe-opencl (brand new) ~and the PR for revised zip-opencl~ are affected by this problem - but IIRC more formats have had this "early partial transfer" thing at least back in the days.

**Comment by magnumripper** [comment]
I'm not even 100% sure what `mask_gpu_is_static` means... I think it's only for hybrid masks, such as for `-mask:?w?a`, where the initial `?w` depicts the index for the `?a`, *per parent word*.

**Comment by ghost** [comment]
> but IIRC more formats have had this "early partial transfer" thing at least back in the days.

I was thinking I was affected by this (the bug itself). I reviewed the code and it is **not** the case. 

But I think I should think about mask again sooner or later. It works, but something else might be hidden.
