### ISSUE TITLE
Can it crack on a minecraft launcher

### ISSUE THREAD

**Issue by FreeMoneyHyb** [openwall/john#4830]
can this work for a external sorce like a minecraft launcher? i could edit it to do so but i was woundering if there was a way to do that before i make a ipswitching minecraft account cracker cuz that would take a week to make.

**Comment by solardiz** [comment]
No, JtR can not directly work on (what I think you mean by) an external source. However, you can use its `--stdout` option to feed the candidate passwords stream it generates into another program.
