### ISSUE TITLE
7z formats: Support BZIP2 compression

### ISSUE THREAD

**Issue by dosoos** [openwall/john#4843]
Version: 1.9.0-jumbo-1+bleeding-56f1d7312 2021-10-05 16:32:08 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is /usr/local/john/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 10.2.1
GNU libc version: 2.31 (loaded: 2.31)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 0101010bf
OpenSSL 1.1.1k  25 Mar 2021
GMP library version: 6.2.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 133 ns
Total physical host memory: 7875 MiB
Available physical host memory: 7021 MiB
Terminal locale string: en_HK.UTF-8
Parsed terminal locale: UTF-8

my hash content:
$7z$6$19$0$$16$16dfc8dcee3ee53c3418c66e3f0245b3$1028653670$3680$3680$9823929e0f711de5b9ad3cd402cba21cc058b7d027cf30ab6222eab176617abe573d191edc753cf1dd39d8dda778401f5ec67d2ea33105dc7e6cdd06b5736772f7e34662c628fbdd7b526bd029234d59de30e1e5cf47597efbc173a819f327a9ec70c32550433d923de5a526998f67e9edcb5a4f4096c4e54c9dee49bb9e7d0abf50a5473f07e437b0f3426434e569808d28edd3f5fa071c987c9bd37c27a651d981596cacc909d859d30fbc39c2c0fcde44bc043ce37fc31bac12117e5348d1412a14b9c551f3e77769dd8dda9c50c66b45599b1e6d70ec520bc55878172559386cc329f7551b686a08aaad6ee4b44cc70a440b91b58459a30f1ab0658c290af26dfd9d8ef972de6112aa7fefefee23af667384fccfb922329c301b5a19da06cfc61ba83e6aa47704540553c6df3292a885d7669caa1f3d1383155fcafbbab9a6dbcc97be2c6561d1759f413c5957dd5e89343797741ac53122e936ff6539a5725e0a5560a8152de616d69013ba746bf60a601263c6b89eaddd06727aaac4db95bff6fc885425cf204d3107fedf2dcc2cc7fd52438f5beee75bb372c34f2eb503eccc8bd410639d3ed3320ed8c28f020697911857539a5af1288a17aaa864b624bc9109249ae0975bda3794d5ffa8da1584b5dfe0bc50fc534a75af62161eb1dade1463fb371e358f721d43998abc9a0249cb90729850ee649cba8bb02957f72c4542c87fabc9f30156c5f3ee5828529dca42a8857c047eb96b1a292630071d0c91820c4b5635afb805060e6ad2e97742ac197a025e47fd9f08e760add0d8b3b55bfd80016c5ea5f4bc4c6d98b3e29b31863519dbf27c5e04772e12fae9dd1a037384c6f764f840e260c6a9b619d04e83fa197c6fd52cfc6bf1a65185d842f99514f9dd7c3ccf4f857c619ff956491cb5cf0a8c821f7718c79b067cef729cabf56cfa2cc420c35a879fa68dee59b943f684229193252b69b594bdaccd7980992321d3dd8b63a833a17832083866a4c98f6163f7c50a4d0d5445c5474a5c8ec864c61b6b384f8415eea02ffdbb1833b984a6b8f415249e3c870e04b1999fa00e3665b3009975fffe717de2e82a0dccd7a269c91c81ba5159d10f6a2278f2690ec2a8aee594cd7eceb85c0adb4f599577b89b0eed6f6739d9ee465de29ae1ca7804c40879df0555b31c5852ec0ac617045376194a6c982df3ee195922ee2b0b0c0f304801e6fcc4ac644c132d63e8404461cc8796fb74aae5bdfac87c9b9e5ecac8d94b25903588e8d20171c4d375898ef2d41fc1f57acd7fd41657fbf817f66f93444db4f7a5496e951cf92906da3593f9f46f16e81c059317eadda72e138afee0a553c9d6ca4d1871e7617c584dd841b55744ecc22a1ba8201c270de1eb011c46a4c6766f70b079647a760e58d7448db2d7e67edddfd67d6c88088086a7150cdc5f2ce49b2c68f0c7f59063f79d95527ba98a9c230074f49400b923bcdd4e7a4b56442e4068cb739d8ac6457ffd4e4c4c63a9e81b1c9d13ac843c3d84e1cd5631c44c59c0c310eac60714e2505eb425d23fda3da16f1b0c41940dc08cea866735a3b70b6b9fa41af3cda4c224fd2e5206141264fa9e2ad9cd60c59ddf9e6ae071fa34e452c1ef979c536c8556c403238158d67f2b7b856920b66a31df39212c2cdbd64be191fc14d227ae353e6c4960e863142ad36841c047e36987f31c22702583385d7fcd7c59b6d688285cc5ff50f55566a3e719de68a67e1efe80dceb00f7b7ac2122b55f0c34199fb22acd89451baf36927857f1c285678b325380e73a566fee9bf66841e780c1ef8adfc77e8e31d72445d854cd4dd8d39806ed526cdd83fc1516e472fec708fa478b34a017668397191ecb113e63e050fd0fb9b23ca0675e94203d2cbb0b102f57b6c0c49a3bdd6d65435717c8debc4f6c7f31b81017bbe7b74abf171fc9b5cf05e831b5560c39b1bcc4b63740f10848a59d378b6eda85bff790907d2662828d7697d52a2474f3f4f1edcedd3472212c86b5b36426e65e6eab84c42ad7b5f8fad7c33c57fee644909ac35e294e6ea25ec553cc45188a8ab6aa1a07d8b46322de8265ed9dfb50ec409723b364323af1c8c33d5ed2f65371a4a44da5ec688a2bf403cf4ba513b16eea88f84084ea4be3dc2b68e20b11e484c4f400abfa57738c44eba3f2384b9f082bbfde71e8d94ec4eb897bbf76c944d6ed2428f8a071c251e211bce392db5517c6fb1aa5e327d1984ef58d0024862024bb1d08a8af0e7cfc796717ccd052c0e3b0dd1a1e46079a8ec74bff87f020ee533e72cd70dad53e005626b323734e5e0644d16a452325d9293e21306fb32e8988553a98b439d57f1b62ab6699a1fd17ec424b43afe99a3999632964d9ac7295806564ba0c2769b1004de7cc6dbe5940e8a3a0a51e1d5bbca8da9d61cf00eadd39e59373e0b41f3018651f6797ae96d01de992864e87edb46a3431873d91500e78d656c137495fef0f347d344512e7b665f7af119cd28e36baa0b57129e0c5fb517d9358135d5f0676d6bb798a589344f508574097556fae63b6d4023d75f82fd020309d59c4fc4ebbd0a9b12195e76e443a77e109307e43f5cf8bad26b57b8040e9386785f77ad96dc60a47aa02a9eb5b8cd7d3274ebbf9bf8aa62101849ae4fb6d5a39b94856d5f81124e5473b6540ce8af989258ffcd0783413a069baaf8c7b9cf154a720d8b205d7854f2320a6f8e1717d95fcc45ca165a6eeb37fcdaa5254d941e5cbd0f6a1eea3a2699adc532b08540356cdeffbd6e35fac0839b981276e58802b6fce340418fa3fd5df623cdd84b28d134344ed661655c973e101c840a0694e8039e6d4cfe55648063c104d482749c4b45573288e5b144b97682729b4e45bfce842459ff08aa54f0fe4440d44d41de0b51ed1cd73710554889dbe3ade15dd84d21af26dcb738dacdec2b705b0be99a0ad9a24db90883efe4024c973afaea880018a1d90b0fb3783e4d0f29f6a3f76f1a683d7e6628eb50ad473e6b432e5b9e24e4cb0d2f1676523bfcd2d2e85816a933f42a6e0db1fdb89cf99ec10aa689c887af30cbe580376adb25992c3aae339faf35bffa7024e64c684bfcff4c0fd00c886108b906eec950c00c262a963391053655911a3f846a4c15a353c6c139868bc1ecd2301e86b50c941ca860ac02b04fc2a155e9cb510b2cfcb46b38460fa1912d8877ccb03406b5d2aadb356c2efd33061e72feb2149fdbb73ce96256afabdcc02026e4c4b24ef21220cd644e19e9ecd2b9057e7f7fd62bb481e7d2ba01f66a2d980b0e6f6c542f019bd24479148042a7be43a1fe2f0225b8da0fd2d5adcc7a58e660de254ab193cda13dd396c5610cc3a4136f608d4b2ee8a1d4fe160fcc7dd154070eceecfaf380cb336bfed684e4ff0f2806d6ff33c2c644fd88d7e3694ad616073c0697ab6070abaf76a1a4e97b09432bc43cf792390322a6e0ac89caf5371a2ca2fcb1239797926bc23f88b017dc13164f72f3513bc29969b5cf7475dd7e36c9a0c0b74f5802b40bb9dde66f4e1589ab1f5ad227f96eb98cbcac40bb929a0395919604fdb47ad9e6d63d83c2b166dfcb138bbf6ff8a11ee98546e220067e570b80b01691d55219143e7eb49fc050d30e1a55b40ae6bbb505c71d3b8e57a6c3f8d8947dd7440fd399b2d0beb3add1b9286d927aef8595117371e2dec45ded0904f8ba8e1d04bf449b3924230fdf95cb32b75c9d9ed870db373aa71f1f9ab5889c484691ee45188358bb0a8fc1553287cbf7728954da1926229cea836385dd8bf7b461d2d08250c7c19ea54e3ae473be5b1f20fcd9bcb68df993b6910ecce01953df05cec935a8494d67288e8b9a22d59bde17dd96e3aa48c559c65d2221e55458c50f6b258c998e495135d7a8ae2db2fdfd5a68937d2333e8b36a690b89f86d8f3330537ba64ef324a574ed357e77e7e68b0e4ef3d85441b802d43226f5629704d0195fd26c5bfcad3138f8ece752e63277a977af2732632bb0651cd733c66575877a0d1c970c7da9ce43236b3e30da669ab9d95342e2514edd200345355b079635d127a2f3c305abba59da9be24f42386481e89a99c4f30164387037b028593e221e1a22165cfb685071146b7586f1cba9cf529ea832a4e5570cdb7340e12b46a921ecf4403c9b75ad55bbaa086b64e87b110495b28a5f02566acbcb70df0ea96fb0f03d32bed4173002ea8fbb814f9c1218e9136732e4efb0bbca6956ee3c130e885807cb3822858d8909f71824a49e008cda2bb70eb12824c2dee5781017001fcbf68751a6367406ff5ea287a78621232b57b5ddd7c0d760e6ff4efb28f03fa82910735c186d23816109a26ac4acfbd9ba0d3927fe6bfb52ac427275c6d581150e7c449c7a0bd5863a30bcfe903eb6882f6d672fb677e5ef8b31314f90b50233f905a64d131325302eed5a7d87bd890d29136ca2752296a2ada2ecbe341665fc0bc0f3422f55ecd9201dcff65011722d7a284c98de5a15fc1fca9bf97d090200d147e3ed1a7addf6198920932ce1594aba5c3074b5e1fe162c9b70e89f0b20671554488704ff4d61100e7dacb51c30b675c39aedb3fddff90af48f326023c342e02d0923cb70c9d12f2b76c4c13dc2317f5e214ced16c98436457604389de1f3db975f3cc71d6d1bda2775dfa59bf6337e5b3af86c0c223e3e653a6e8c34fe1dcecff213c8fa7c1aec6d47ef490b78daa7d1886aab63a926451777057061cb7301c3bf464651480a1448d7538ad605bba1f9c10a52c6d9ac3361f63b0f104232750ed1d0e017743fb7edac046e74a0210d3687c92914cd7ee03934f7d36dedf7d7fe7d3f45dc72898723f00638ce315b814d966f890748f0d8913e3400ac55f9ae98186eb614dbde1a3af382d528d07c5bc84d8b8303e87775bda2c3cfd9ccc4e03418a59a9e3ece67dd56bfee83ceabbd80721523cc59d7a23d58fd2fc87238361092fc927b85b9b62297828ad8bfe329eaf3ec72bd307841a8b6b76ca5e61c71378273a6b76ac02f0da360171cbbc4dda72c4133b2825f97a0aef97605ce3c3d6d23924b75a58d73380452287a1b8ab18e51c8d1a38bdb92f1d7794c6a1850560438d8e64551c6b63770ed75216b4f42aa728d3cb9aa19b716819e0397bab8a5e2cbc34f8f5ecbbe0c245d09400168eefbae6bfc2be3c41c5$3464$

**Comment by ghost** [comment]
Your 7z file is not supported. 
You could tell how you created this file. Maybe some developer is interested in adding the unsupported compression type.

```
$ john hash.txt 
Warning: Not loading files with unsupported compression type BZIP2 (0x06)
[...]
```

To tell you the truth, BZIP2 doesn't sound like something new, it's the other way around.

**Comment by magnumripper** [comment]
@dosoos support was added now! Pull latest version, rebuild and try again.
