### ISSUE TITLE
Trying to recover a dmg file password on Apple M1

### ISSUE THREAD

**Issue by Rebnerd** [openwall/john#4864]
how this happend?can anyone tell me how to solve this
![Uploading Screen Shot 2021-11-10 at 9.53.30 PM.png…]()

**Comment by Rebnerd** [comment]
<img width="590" alt="Screen Shot 2021-11-10 at 9 53 30 PM" src="https://user-images.githubusercontent.com/73422330/141125762-444dbcd5-1332-4882-afd7-cbbc355d40db.png">

**Comment by solardiz** [comment]
@fansinatingRu The program does work on Apple M1. However, with the `--show` option you're asking it to display a previously cracked password, which it doesn't have, and tells you so - there's "1 left" to crack. Omit that option.
