### ISSUE TITLE
I am against the concept of publishing this

### ISSUE THREAD

**Issue by francogrex** [openwall/john#4866]
The concept is unethical

**Comment by solardiz** [comment]
@francogrex OK, that's your opinion, but why open the issue?

**Comment by francogrex** [comment]
You may delete or close this, I didn't know how else to signal it, I was surprised to find such a project on github. My comments have nothing to do with the quality of the work itself. Regards.

**Comment by solardiz** [comment]
Trying to take your feedback in a positive manner, I think we as a community need a public resource summarizing the offensive security tool debate of the 1990s and its outcome (publishing of such tools generally accepted as ethical). There is for the full disclosure debate e.g. https://en.wikipedia.org/wiki/Full_disclosure_(computer_security) but frankly and surprisingly I cannot easily find similar for the tools now. If anyone reading this knows of such a resource, please share.

**Comment by magnumripper** [comment]
This project, along with similar projects such as hashcat, has helped showing weaknesses and bugs in major things such as Cisco routers, 1Password vaults and macOS (or rather OS X at that time). That's some "big names" off the top of my head but there's many, many more including web site engines, SQL servers and what not. Most of these systems (including all three I mentioned with name) are much more secure nowadays, often as a direct result of our work.
