### ISSUE TITLE
blockchain2john.py --base64 doesn't generate a 12700 hash from a blockchain-V0 wallet for hashcat

### ISSUE THREAD

**Issue by shoutmarble** [openwall/john#4872]
blockchain2john.py --base64 produces no output

Here are the steps that I tried

https://github.com/openwall/john/
./blockchain2john.py --base64 blockchain-v0.0-wallet.aes.json
Produces no hash output

I then wanted to plugin the hash from "blockchain2john.py --base64" into hashcat

I verified the wallet with BTCRecover and I wanted to verify cracking this wallet with HASHCAT

The V0 Blockchain wallet
https://github.com/gurnec/btcrecover
/btcrecover/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json

python btcrecover.py --wallet btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json --typos-capslock --tokenlist ./docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/tokenListTest.txt

Password found: 'btcr-test-password'

I want to reproduce the crack from BTCRecover with HASHCAT below 

###HASHCAT 12700 HASH COMPATIBLITY CHECK
docker pull dizcza/docker-hashcat:cuda
docker run --gpus all --privileged -v $PWD/:/root/wallets/ -it dizcza/docker-hashcat:cuda /bin/bash
hashcat -w 3 -S --session sessiontestwalletdat -m 12700 -o decryptedpassphrase.txt -a 3 V0HASH.HASH INCR_MASK.hcmask

I want to be able to crack the 12700 V0 blockchain wallet with HASHCAT

**Comment by magnumripper** [comment]
[blockchain-v0.0-wallet.aes.json](https://raw.githubusercontent.com/gurnec/btcrecover/master/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json)

> blockchain2john.py --base64 produces no output

Works for me:
```
$ ../run/blockchain2john.py --base64 ~/Desktop/blockchain-v0.0-wallet.aes.json
blockchain-v0.0-wallet.aes.json:$blockchain$688$e6030fc5ab3c979335a0273bb2ceed88f59f72d49eba71e60a92b5f2d75987476c6964052d76c557deea106fefe11bdba58e0d32fd5424d826f1ee86f541fa6ccdc7d0ba0345cb778ad76e28eca7ee48e2ba584b09139a2a583fd17b78e36bfbb7555f6f24b2fef8eaeac306613f41624c2d59f31c945922b33d06fcf722348a3336478cad4548fb46c41494a7f89c98a9327744ec12bc8b3c9561691343c6533d2c1f3f4496dcaccf95f0e5a217c5d97ff5cdf3a3b731e268e84856464dcd753cbf45e00f0e8bfc9b575b9de816cbbd5f4ad3c6d1c0f34f8a3bc0ce62a8a74da055e2c72c0285e33a299ef57b9ef9d06e894713abb61d9f4b5157c348248b635e99c4643b6210525e9fac2dde3334d883e2ee167c008de6173e5af753d64259eaf782c54aceb7c0873e63657735b289b09a2e1f9a39342315da36428d140ac6662bb94cda70e7bfa4d8b8ff8f85d1a9ca63e62a02d6891c294ea05cf3c9e8ed5a8402e41c76650fb8c10d5a44ca8f549b2ea92f125e8458c7fc8c4f88135c08b8cb40755493b318805c4d2939da3489cba5f4a2e6d4bed64d5b54f56df36929fd7479766150e830b213a6bc85accffd3b8517746f1470092e634c62b068682cd0ff015b09f0d520a4f99d171e57c847c54b33aeaa86de34c413f7007d88022c679b74b2f55706f647fd79958411af904f9574b9d7c622848ce4fe4690f795769fe124572160d9196745f5fe1a34a927d3a50b1b007ffb83f6361a9f52411cc2c67d03936a0510d5833058ebd4bce5ce4b513a1df26fa5529ec6e80550d733b84d7481db9f3cdb940a36766dc7a5ffd48684fd7bfc915d88542a02790c4e6a6da718893712fa2311f3c722bd98b2be2570f5dc57bc936b20ef5a8bf982f610079b1e9baf12ae03c69dc1432d7f941544672d3a1df86c1c741e95b2f2f796ba7edfe2ed98a2040481158a3b9ab39ccbde
```

I could also crack that hash with the mentioned password, using CPU or GPU.

On a side note, the wallet is a file containing 100% Base64. Without using the `--base64` option, I get another (good looking) hash that I can't crack. It would be more sensible for `blockchain2john.py` to detect that the file is all Base64 and do the Right Thing[tm] automagically.

**Comment by magnumripper** [comment]
> I want to be able to crack the 12700 V0 blockchain wallet with HASHCAT

This is the JtR repo, but I also tried cracking with hashcat and it worked just fine as well.

**Comment by magnumripper** [comment]
Another note: I get the correct hash with python2 as well as python3 but the latter emits this warning:
```
../run/blockchain2john.py:57: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
  ddata = base64.decodestring(data)
```
If I do that change though, the script no longer outputs anything under python2.

**Comment by solardiz** [comment]
> On a side note, the wallet is a file containing 100% Base64. Without using the `--base64` option, I get another (good looking) hash that I can't crack. It would be more sensible for `blockchain2john.py` to detect that the file is all Base64 and do the Right Thing[tm] automagically.

@magnumripper What you describe is indeed problematic - we need to fix that. Would you open an issue for that? (Or maybe a PR right away if you can.) Thank you!

**Comment by shoutmarble** [comment]
I don't get the same hash value for blockchain-v0.0-wallet.aes.json from blockchain2john.py

This is the test Blockchain V0 wallet I'm verifying with my blockchain2john.py and hashcat 12700


> https://github.com/gurnec/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json

Wallet
> 5gMPxas8l5M1oCc7ss7tiPWfctSeunHmCpK18tdZh0dsaWQFLXbFV97qEG/v4RvbpY4NMv1UJNgm8e6G9UH6bM3H0LoDRct3itduKOyn7kjiulhLCROaKlg/0Xt442v7t1VfbySy/vjq6sMGYT9BYkwtWfMclFkisz0G/PciNIozNkeMrUVI+0bEFJSn+JyYqTJ3ROwSvIs8lWFpE0PGUz0sHz9Eltysz5Xw5aIXxdl/9c3zo7cx4mjoSFZGTc11PL9F4A8Oi/ybV1ud6BbLvV9K08bRwPNPijvAzmKop02gVeLHLAKF4zopnvV7nvnQbolHE6u2HZ9LUVfDSCSLY16ZxGQ7YhBSXp+sLd4zNNiD4u4WfACN5hc+WvdT1kJZ6veCxUrOt8CHPmNldzWyibCaLh+aOTQjFdo2Qo0UCsZmK7lM2nDnv6TYuP+PhdGpymPmKgLWiRwpTqBc88no7VqEAuQcdmUPuMENWkTKj1SbLqkvEl6EWMf8jE+IE1wIuMtAdVSTsxiAXE0pOdo0icul9KLm1L7WTVtU9W3zaSn9dHl2YVDoMLITpryFrM/9O4UXdG8UcAkuY0xisGhoLND/AVsJ8NUgpPmdFx5XyEfFSzOuqobeNMQT9wB9iAIsZ5t0svVXBvZH/XmVhBGvkE+VdLnXxiKEjOT+RpD3lXaf4SRXIWDZGWdF9f4aNKkn06ULGwB/+4P2NhqfUkEcwsZ9A5NqBRDVgzBY69S85c5LUTod8m+lUp7G6AVQ1zO4TXSB258825QKNnZtx6X/1IaE/Xv8kV2IVCoCeQxOam2nGIk3EvojEfPHIr2Ysr4lcPXcV7yTayDvWov5gvYQB5sem68SrgPGncFDLX+UFURnLTod+GwcdB6VsvL3lrp+3+LtmKIEBIEVijuas5zL3g==
> 
>


> $ python3 ./blockchain2john.py blockchain-v0.0-wallet.aes.json 
>
> blockchain-v0.0-wallet.aes.json:$blockchain$920$35674d50786173386c354d316f436337737337746950576663745365756e486d43704b313874645a68306473615751464c5862465639377145472f76345276627059344e4d7631554a4e676d3865364739554836624d3348304c6f4452637433697464754b4f796e376b6a69756c684c43524f614b6c672f305874343432763774315666627953792f766a7136734d4759543942596b777457664d636c466b69737a30472f5063694e496f7a4e6b654d725556492b306245464a536e2b4a795971544a33524f7753764973386c57467045305047557a3073487a39456c7479737a3558773561495878646c2f3963337a6f376378346d6a6f53465a4754633131504c39463441384f692f7962563175643642624c7656394b3038625277504e50696a76417a6d4b6f7030326756654c484c414b46347a6f706e7656376e766e51626f6c4845367532485a394c555666445343534c5931365a784751375968425358702b734c64347a4e4e6944347534576641434e3568632b57766454316b4a5a367665437855724f74384348506d4e6c647a5779696243614c682b614f54516a46646f32516f305543735a6d4b376c4d326e446e7636545975502b5068644770796d506d4b674c57695277705471426338386e6f3756714541755163646d5550754d454e576b544b6a3153624c716b76456c3645574d66386a452b4945317749754d74416456535473786941584530704f646f306963756c394b4c6d314c3757545674553957337a61536e3964486c325956446f4d4c495470727946724d2f394f3455586447385563416b75593078697347686f4c4e442f4156734a384e556770506d644678355879456646537a4f75716f62654e4d515439774239694149735a3574307376565842765a482f586d56684247766b452b56644c6e5878694b456a4f542b527044336c586166345352584957445a47576446396634614e4b6b6e3036554c4777422f2b3450324e687166556b456377735a3941354e7142524456677a4259363953383563354c55546f64386d2b6c5570374736415651317a4f3454585342323538383235514b4e6e5a747836582f314961452f5876386b56324956436f436551784f616d326e47496b3345766f6a45665048497232597372346c635058635637795461794476576f763567765951423573656d363853726750476e6346444c582b554655526e4c546f642b4777636442365673764c336c72702b332b4c746d4b494542494556696a756173357a4c33673d3d 


 
(python2 output is identical to python3 output)
 

(I renamed the blockchain2john.py output hash to V0.hash)  And, I removed "blockchain-v0.0-wallet.aes.json:" from beginning of the blockchain2john.py hash file.


> V0.hash


> $blockchain$920$35674d50786173386c354d316f436337737337746950576663745365756e486d43704b313874645a68306473615751464c5862465639377145472f76345276627059344e4d7631554a4e676d3865364739554836624d3348304c6f4452637433697464754b4f796e376b6a69756c684c43524f614b6c672f305874343432763774315666627953792f766a7136734d4759543942596b777457664d636c466b69737a30472f5063694e496f7a4e6b654d725556492b306245464a536e2b4a795971544a33524f7753764973386c57467045305047557a3073487a39456c7479737a3558773561495878646c2f3963337a6f376378346d6a6f53465a4754633131504c39463441384f692f7962563175643642624c7656394b3038625277504e50696a76417a6d4b6f7030326756654c484c414b46347a6f706e7656376e766e51626f6c4845367532485a394c555666445343534c5931365a784751375968425358702b734c64347a4e4e6944347534576641434e3568632b57766454316b4a5a367665437855724f74384348506d4e6c647a5779696243614c682b614f54516a46646f32516f305543735a6d4b376c4d326e446e7636545975502b5068644770796d506d4b674c57695277705471426338386e6f3756714541755163646d5550754d454e576b544b6a3153624c716b76456c3645574d66386a452b4945317749754d74416456535473786941584530704f646f306963756c394b4c6d314c3757545674553957337a61536e3964486c325956446f4d4c495470727946724d2f394f3455586447385563416b75593078697347686f4c4e442f4156734a384e556770506d644678355879456646537a4f75716f62654e4d515439774239694149735a3574307376565842765a482f586d56684247766b452b56644c6e5878694b456a4f542b527044336c586166345352584957445a47576446396634614e4b6b6e3036554c4777422f2b3450324e687166556b456377735a3941354e7142524456677a4259363953383563354c55546f64386d2b6c5570374736415651317a4f3454585342323538383235514b4e6e5a747836582f314961452f5876386b56324956436f436551784f616d326e47496b3345766f6a45665048497232597372346c635058635637795461794476576f763567765951423573656d363853726750476e6346444c582b554655526e4c546f642b4777636442365673764c336c72702b332b4c746d4b494542494556696a756173357a4c33673d3d


> hashcat -w 3 -S --session HCSession -m 12700 -o password.txt -a 3 V0.hash INCR_MASK.hcmask


> INCR_MASK.hcmask
> ?l,btcr-?1?1?1?1-password
> ?l,btcr-test-password


Your hash was successful in my Hashcat also, can you make a hash from this wallet?
> https://github.com/gurnec/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json


> $blockchain$688$e6030fc5ab3c979335a0273bb2ceed88f59f72d49eba71e60a92b5f2d75987476c6964052d76c557deea106fefe11bdba58e0d32fd5424d826f1ee86f541fa6ccdc7d0ba0345cb778ad76e28eca7ee48e2ba584b09139a2a583fd17b78e36bfbb7555f6f24b2fef8eaeac306613f41624c2d59f31c945922b33d06fcf722348a3336478cad4548fb46c41494a7f89c98a9327744ec12bc8b3c9561691343c6533d2c1f3f4496dcaccf95f0e5a217c5d97ff5cdf3a3b731e268e84856464dcd753cbf45e00f0e8bfc9b575b9de816cbbd5f4ad3c6d1c0f34f8a3bc0ce62a8a74da055e2c72c0285e33a299ef57b9ef9d06e894713abb61d9f4b5157c348248b635e99c4643b6210525e9fac2dde3334d883e2ee167c008de6173e5af753d64259eaf782c54aceb7c0873e63657735b289b09a2e1f9a39342315da36428d140ac6662bb94cda70e7bfa4d8b8ff8f85d1a9ca63e62a02d6891c294ea05cf3c9e8ed5a8402e41c76650fb8c10d5a44ca8f549b2ea92f125e8458c7fc8c4f88135c08b8cb40755493b318805c4d2939da3489cba5f4a2e6d4bed64d5b54f56df36929fd7479766150e830b213a6bc85accffd3b8517746f1470092e634c62b068682cd0ff015b09f0d520a4f99d171e57c847c54b33aeaa86de34c413f7007d88022c679b74b2f55706f647fd79958411af904f9574b9d7c622848ce4fe4690f795769fe124572160d9196745f5fe1a34a927d3a50b1b007ffb83f6361a9f52411cc2c67d03936a0510d5833058ebd4bce5ce4b513a1df26fa5529ec6e80550d733b84d7481db9f3cdb940a36766dc7a5ffd48684fd7bfc915d88542a02790c4e6a6da718893712fa2311f3c722bd98b2be2570f5dc57bc936b20ef5a8bf982f610079b1e9baf12ae03c69dc1432d7f941544672d3a1df86c1c741e95b2f2f796ba7edfe2ed98a2040481158a3b9ab39ccbde:btcr-test-password


I'm tryin to crack the below test file with blockchain2john.py and Hashcat 12700 with this blockchain V0 wallet
> https://github.com/gurnec/btcrecover/blob/master/btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json
from BTCRecover

This wallet is crackable as I tested with btcrecover 


https://github.com/gurnec/btcrecover

> python btcrecover.py --wallet btcrecover/test/test-wallets/blockchain-v0.0-wallet.aes.json --typos-capslock --tokenlist ./docs/Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/tokenListTest.txt
> 
> Password found: 'btcr-test-password'


On Wednesday 17 November 2021 04:03:10 AM (-06:00), magnum wrote:



Another note: I get the correct hash with python2 as well as python3 but the latter emits this warning:

../run/blockchain2john.py:57: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
  ddata = base64.decodestring(data)


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Comment by magnumripper** [comment]
@shoutmarble you need to use the `--base64` option to get the correct hash, just like in your OP.

**Comment by shoutmarble** [comment]
***@***.*** Downloads]$ python2 ./blockchain2john.py blockchain-v0.0-wallet.aes.json 
blockchain-v0.0-wallet.aes.json:$blockchain$920$35674d50786173386c354d316f436337737337746950576663745365756e486d43704b313874645a68306473615751464c5862465639377145472f76345276627059344e4d7631554a4e676d3865364739554836624d3348304c6f4452637433697464754b4f796e376b6a69756c684c43524f614b6c672f305874343432763774315666627953792f766a7136734d4759543942596b777457664d636c466b69737a30472f5063694e496f7a4e6b654d725556492b306245464a536e2b4a795971544a33524f7753764973386c57467045305047557a3073487a39456c7479737a3558773561495878646c2f3963337a6f376378346d6a6f53465a4754633131504c39463441384f692f7962563175643642624c7656394b3038625277504e50696a76417a6d4b6f7030326756654c484c414b46347a6f706e7656376e766e51626f6c4845367532485a394c555666445343534c5931365a784751375968425358702b734c64347a4e4e6944347534576641434e3568632b57766454316b4a5a367665437855724f74384348506d4e6c647a5779696243614c682b614f54516a46646f32516f305543735a6d4b376c4d326e446e7636545975502b5068644770796d506d4b674c57695277705471426338386e6f3756714541755163646d5550754d454e576b544b6a3153624c716b76456c3645574d66386a452b4945317749754d74416456535473786941584530704f646f306963756c394b4c6d314c3757545674553957337a61536e3964486c325956446f4d4c495470727946724d2f394f3455586447385563416b75593078697347686f4c4e442f4156734a384e556770506d644678355879456646537a4f75716f62654e4d515439774239694149735a3574307376565842765a482f586d56684247766b452b56644c6e5878694b456a4f542b527044336c586166345352584957445a47576446396634614e4b6b6e3036554c4777422f2b3450324e687166556b456377735a3941354e7142524456677a4259363953383563354c55546f64386d2b6c5570374736415651317a4f3454585342323538383235514b4e6e5a747836582f314961452f5876386b56324956436f436551784f616d326e47496b3345766f6a45665048497232597372346c635058635637795461794476576f763567765951423573656d363853726750476e6346444c582b554655526e4c546f642b4777636442365673764c336c72702b332b4c746d4b494542494556696a756173357a4c33673d3d

***@***.*** Downloads]$ python2 ./blockchain2john.py --base64 blockchain-v0.0-wallet.aes.json 
blockchain-v0.0-wallet.aes.json:$blockchain$688$e6030fc5ab3c979335a0273bb2ceed88f59f72d49eba71e60a92b5f2d75987476c6964052d76c557deea106fefe11bdba58e0d32fd5424d826f1ee86f541fa6ccdc7d0ba0345cb778ad76e28eca7ee48e2ba584b09139a2a583fd17b78e36bfbb7555f6f24b2fef8eaeac306613f41624c2d59f31c945922b33d06fcf722348a3336478cad4548fb46c41494a7f89c98a9327744ec12bc8b3c9561691343c6533d2c1f3f4496dcaccf95f0e5a217c5d97ff5cdf3a3b731e268e84856464dcd753cbf45e00f0e8bfc9b575b9de816cbbd5f4ad3c6d1c0f34f8a3bc0ce62a8a74da055e2c72c0285e33a299ef57b9ef9d06e894713abb61d9f4b5157c348248b635e99c4643b6210525e9fac2dde3334d883e2ee167c008de6173e5af753d64259eaf782c54aceb7c0873e63657735b289b09a2e1f9a39342315da36428d140ac6662bb94cda70e7bfa4d8b8ff8f85d1a9ca63e62a02d6891c294ea05cf3c9e8ed5a8402e41c76650fb8c10d5a44ca8f549b2ea92f125e8458c7fc8c4f88135c08b8cb40755493b318805c4d2939da3489cba5f4a2e6d4bed64d5b54f56df36929fd7479766150e830b213a6bc85accffd3b8517746f1470092e634c62b068682cd0ff015b09f0d520a4f99d171e57c847c54b33aeaa86de34c413f7007d88022c679b74b2f55706f647fd79958411af904f9574b9d7c622848ce4fe4690f795769fe124572160d9196745f5fe1a34a927d3a50b1b007ffb83f6361a9f52411cc2c67d03936a0510d5833058ebd4bce5ce4b513a1df26fa5529ec6e80550d733b84d7481db9f3cdb940a36766dc7a5ffd48684fd7bfc915d88542a02790c4e6a6da718893712fa2311f3c722bd98b2be2570f5dc57bc936b20ef5a8bf982f610079b1e9baf12ae03c69dc1432d7f941544672d3a1df86c1c741e95b2f2f796ba7edfe2ed98a2040481158a3b9ab39ccbde

Success!


On Wednesday 17 November 2021 05:45:22 AM (-06:00), magnum wrote:



@shoutmarble you need to use the --base64 option to get the correct hash, just like in your OP.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com
