### ISSUE TITLE
Unknown option: "-zsh-zsh" when putting unquoted hash on command-line on macOS (usage error)

### ISSUE THREAD

**Issue by dvvvsh** [openwall/john#4873]
first off I'll start by saying, I apologize if I missed something and this isn't new but I get this message  -Unknown option: "-zsh-zsh", I'm fairly new at this so please forgive me.

Version: 1.9.0-jumbo-1+bleeding-0a8bb63e9 2021-11-08 17:08:17 +0100
Build: darwin20.6.0 64-bit arm ASIMD AC
SIMD: ASIMD, interleaving: MD4:2 MD5:2 SHA1:1 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
clang version: 13.0.0 (clang-1300.0.29.3) (gcc 4.2.1 compatibility)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 0101010cf
OpenSSL 1.1.1l  24 Aug 2021
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: mach_absolute_time(), resolution 41 ns
Total physical host memory: 8 GiB
Available physical host memory: 2871 MiB
Terminal locale string: en_US.UTF-8
Parsed terminal locale: UTF-8
jonathandoe@MacBook-Air run %

**Comment by solardiz** [comment]
@dvvvsh What command are you typing that triggers that message about zsh?

**Comment by dvvvsh** [comment]
./john hashes

**Comment by solardiz** [comment]
@dvvvsh Well, this shouldn't be happening. Can you show a piece of copy-paste from your terminal, including the command and its output? Like you did for the build info.

**Comment by solardiz** [comment]
This is pretty obviously a usage error. We don't need to track this as an issue, so I'll close the issue now. However, @dvvvsh please feel free to post further comments/questions to this (closed) issue if you need.

**Comment by dvvvsh** [comment]
jonathandoe@MacBook-Air run % python bitcoin2john.py 11.dat
$bitcoin$64$bd2d86dd1d3e766e3273dc8587fec8abb530d2e780c1ab1fb4116a5e898b591c$16$cc279a2c74dacc43$62210$2$00$2$00
jonathandoe@MacBook-Air run % ./john $bitcoin$64$...............................$16$cc279a2c74dacc43$62210$2.........

Unknown option: "-zsh-zsh"
jonathandoe@MacBook-Air run %

**Comment by solardiz** [comment]
@dvvvsh As expected, that's not correct usage. You need to save the `bitcoin2john.py` output to a file and then run `john` on the file. Like this:

```shell
python bitcoin2john.py 11.dat > 11.txt
./john 11.txt
```

Please be careful when posting cryptocurrency wallet info online. Luckily, our latest revision of `bitcoin2john.py` produces sufficiently non-revealing output that no one can access your funds just from knowing that string and cracking the password - so you're safe now - but some older revisions were not as good at that and some other wallet type and extraction script combinations aren't safe in this respect.

**Comment by dvvvsh** [comment]
thanks a lot you are greatly appreciated!
