### ISSUE TITLE
Consider adding a --mask-int-target=N option

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4876]
See https://github.com/openwall/john/issues/4871#issuecomment-972959657

We could add an option for overriding any figure set by the format. The best-effort algorithms used for determining the size of the internal mask is far from perfect so in some cases we might want to set it manually for an actual cracking session. Apart from that it would be handy for testing as well.

**Comment by magnumripper** [comment]
Perhaps `--mask-internal-target=N` is a tad better. Or maybe `--mask-acceleration-target=N`.

**Comment by ghost** [comment]
I actually have something like this at: https://github.com/openwall/john/blob/3844f06b7a4175123e65f96c5f1ba8bc065b8f23/src/opencl_rawsha512_gpl_fmt_plug.c#L584

In my tests, I found it is not really important/useful. The mask mode's inability to "partition" the mask further is the real problem. The ability to turn, for example, a `?d` into two "mask calls"; the 1st one from zero to 4 and the 2nd from 5 to 9. 

When we use a mask like (from a recent LM issue) `?a?a?a?a`, the engine will use multiples of 95, obligatorily: so the values grow too fast. These values don't suit GPUs well. Notice, we either have 100 (actually 95) or 10000 (9025). An average GPU maybe 3000 would be the best value, on a powerful one maybe 8000. 

Some users might find the option useful for sure, but, IMO, it wasn't interesting to me when and how I used it.

**Comment by magnumripper** [comment]
> The mask mode's inability to "partition" the mask further is the real problem. The ability to turn, for example, a `?d` into two "mask calls"; the 1st one from zero to 4 and the 2nd from 5 to 9.

That's definitely the bottom-line problem for #4880 and some other issues. I'm just not sure how to solve it without complex code.
