### ISSUE TITLE
"CUDA cores" reporting is wrong on Ampere

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4892]
I think we should halve the number of "cores" in the computation in `opencl_speed_index()` when we're on NVIDIA Ampere and above, because half of their reported cores are FP-only, thus currently unusable for us.

Alternatively, we could halve our reported number of cores (fits our current code better, with GPU type checks all in one place), but then we need to adjust the wording from "CUDA cores" e.g. to "INT32 CUDA cores". Unfortunately, this might then become incorrect in some future NVIDIA architecture - not just incorrect speed index, but incorrect reporting of something that we claim to be so specific (INT32 cores). That's not ideal.

**Comment by solardiz** [comment]
Ideally, someone with one (or more) of those GPUs handy should do this and run benchmarks. While I think the change is correct anyway, even _if_ it'd happen to hurt some speeds, we should at least be aware of that and should then try and repair the speeds by tweaks elsewhere.

**Comment by magnumripper** [comment]
Apparently Ampere's "compute capability" is 8.0

**Comment by magnumripper** [comment]
We currently don't make any CUDA calls to ask for number of "CUDA cores" so there's no figure to halve. We merely ask for the "compute capability" and then decide we have 64 cores per MP for (currently) anything >= 7.0.

The Wikipedia page for Ampere says it has "64 (+64 mixed INT/FP32 cores)". Not sure what that means, 96 INT32 cores?

**Comment by magnumripper** [comment]
On a side note I have considered re-adding some (optional) CUDA code for things like this. We get more info from CUDA than from (even nvidia proprietary) OpenCL calls.

**Comment by magnumripper** [comment]
> Not sure what that means, 96 INT32 cores?

If so, it'd just be something like
```diff
diff --git a/src/opencl_common.c b/src/opencl_common.c
index 986261526..ebecc9147 100644
--- a/src/opencl_common.c
+++ b/src/opencl_common.c
@@ -2531,8 +2531,10 @@ cl_uint get_processors_count(int sequential_id)
 			core_count *= (ocl_device_list[sequential_id].cores_per_MP = 128);
 		else if (major == 6)    // 6.x Pascal
 			core_count *= (ocl_device_list[sequential_id].cores_per_MP = 128);
-		else if (major >= 7)    // 7.x Volta, 8.x Turing?
+		else if (major == 7)    // 7.x Volta, Turing
 			core_count *= (ocl_device_list[sequential_id].cores_per_MP = 64);
+		else if (major >= 8)    // 8.x Ampere, "64 INT + 64 mixed INT/FP"
+			core_count *= (ocl_device_list[sequential_id].cores_per_MP = 96);
 /*
  * Apple, VCL and some other environments don't expose get_compute_capability()
  * so we need this crap - which is incomplete.
```
We should probably add stuff in other places (such as `run/opencl/opencl_device_info.h`) as well, but that's not really related to this issue.

**Comment by magnumripper** [comment]
> The Wikipedia page for Ampere says it has "64 (+64 mixed INT/FP32 cores)". Not sure what that means, 96 INT32 cores?

No wait, it says "FP32 cores / SM" is what I said. So the number of INT32 cores is 64, and our current code actually emits the correct speed index.

Still, we should add code here and there (such as in `run/opencl/opencl_device_info.h`) for recognizing Ampere, and we should change the wording of "CUDA cores".

**Comment by solardiz** [comment]
Oh, you're right. So the number is already what we need, and the wording "CUDA cores" is not. Can this issue be for changing the wording, then? Maybe just make it "INT32 cores". We can even use that on non-NVIDIA, removing the ternary operator.

**Comment by magnumripper** [comment]
I'll whip something up and make a PR

**Comment by magnumripper** [comment]
I think I'll have it as "CUDA integer cores" provided it fits width.

**Comment by solardiz** [comment]
There are also INT8 cores in recent NVIDIA GPUs, which by the way we could possibly use for Lotus/Domino and such. So I prefer we explicitly say INT32 here.
