### ISSUE TITLE
mask stretching shows percent in progress counting previous lengths

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#4911]
I noticed that I don't get 0% when mask stretching goes onto next stage and prints status line.

A grotesque example to demonstrate:
```
$ echo '$0$A' > t.pw
$ ./run/john t.pw --mask='[ -~][ -~][ -~]a' --min-length=4 --max-length=10
Using default input encoding: UTF-8
Loaded 1 password hash (plaintext, $0$ [n/a])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:00  (4) 0g/s 0p/s 0c/s 0C/s
0g 0:00:00:00 50.00% (5) (ETA: 22:33:17) 0g/s 85735Kp/s 85735Kc/s 85735KC/s f~~a..)! aa
0g 0:00:00:00 66.67% (6) (ETA: 22:33:17) 0g/s 57156Kp/s 57156Kc/s 57156KC/s M~~aa..o  aaa
0g 0:00:00:00 75.00% (7) (ETA: 22:33:17) 0g/s 51441Kp/s 51441Kc/s 51441KC/s 4~~aaa..V  aaaa
0g 0:00:00:00 80.00% (8) (ETA: 22:33:17) 0g/s 48991Kp/s 48991Kc/s 48991KC/s z}~aaaa..=  aaaaa
0g 0:00:00:00 83.33% (9) (ETA: 22:33:17) 0g/s 47630Kp/s 47630Kc/s 47630KC/s a}~aaaaa..$  aaaaaa
0g 0:00:00:00 85.71% (10) (ETA: 22:33:17) 0g/s 46765Kp/s 46765Kc/s 46765KC/s k~~aaaaaa...! aaaaaaa
0g 0:00:00:00 DONE (10) (2021-12-05 22:33) 0g/s 46166Kp/s 46166Kc/s 46166KC/s R~~aaaaaaa..~~~aaaaaaa
Session completed.
```

Obviously percents show progress counting all tried candidates versus all previous levels plus size for mask with current length. So for the last length, the percents are meaningful as progress of full attack.

Usually I set max-length so high that I don't care about global progress. Also usually percents are quite small because longer mask is much bigger. And it may be nice to understand the growth of keyspace. So usually things look quite good. But it does not seem 100% right too.

I am not sure if it is the intended behaviour. Hence the issue.

**Comment by magnumripper** [comment]
This is intended. It's briefly mentioned in the docs as "Whenever using incremental mask, the ETA at any given time shows estimated time to complete the *current* length, as opposed to the whole run".

Changing this behavior (if we wanted to, which I don't) would be very tricky: The ETA and that percent figure are tied together.

**Comment by solardiz** [comment]
To me, @AlekseyCherepanov's description reads inconsistent with @magnumripper's clarification, and the example given is a poor illustration because of way too short (0 seconds) duration of that session.

**Comment by magnumripper** [comment]
What was inconsistent?

Here's an example of normal use
```
$ ../run/john -mask:?l -max-len=5 -stdout -v:1
Warning: Verbosity decreased to minimum, candidates will not be printed!
0p 0:00:00:00 0.00% (1) 0p/s
26p 0:00:00:00 3.70% (2) (ETA: 09:04:30) 650.0p/s q
702p 0:00:00:00 3.84% (3) (ETA: 09:04:30) 17550p/s qq
18278p 0:00:00:00 3.85% (4) (ETA: 09:04:30) 456950p/s qqq
475254p 0:00:00:00 3.85% (5) (ETA: 09:04:30) 11881Kp/s qqqq
12356630p 0:00:00:00 100.00% (5) (2021-12-06 09:04) 77228Kp/s qqqqq
```
At the time we get to len 2, the progress/ETA is counted against 26+26² (= 702) and we already did 26 candidates for earlier lengths. So we get a percentage of 3.70% at the time of length switching.

**Comment by magnumripper** [comment]
> the example given is a poor illustration because of way too short (0 seconds) duration of that session.

You mean for ETA. The important thing in the examples given are the percentages. The ETA is calculated from percentage in status.c, same way for any cracking mode. If the percentage is correct, ETA will be too (given steady performance and a reasonable time frame to finish).

**Comment by AlekseyCherepanov** [comment]
In a real run for 6+ days with stable speed, I had opportunity to be around less than 10 minutes after planned switch and the switch happened already, so ETA seemed correct.

It turned out that early status lines can have too optimistic ETA. There are optimistic status on switch and timely status with better ETA:
```
$ while :; do sleep 1; date; done &
[...]
Mon Dec  6 15:30:08 +03 2021
./run/john t.pw --mask='[ -~][ -~][ -~][ -~][ -~]a' --min-length=4 --max-length=7 --progress-every=1
Using default input encoding: UTF-8
Loaded 1 password hash (plaintext, $0$ [n/a])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:00  (4) 0g/s 0p/s 0c/s 0C/s
Mon Dec  6 15:30:09 +03 2021
0g 0:00:00:00 1.04% (5) (ETA: 15:30:09) 0g/s 108600Kp/s 108600Kc/s 108600KC/s \~~~..~    
0g 0:00:00:01 1.38% (5) (ETA: 15:31:21) 0g/s 107789Kp/s 107789Kc/s 107789KC/s 4Ed> ..VFd> 
Mon Dec  6 15:30:10 +03 2021
```

But ETA just before other switches are quite precise:
```
Mon Dec  6 15:31:22 +03 2021
0g 0:00:01:14 99.92% (5) (ETA: 15:31:23) 0g/s 105585Kp/s 105585Kc/s 105585KC/s  ~)x~..B *x~
0g 0:00:01:14 50.26% (6) (ETA: 15:32:36) 0g/s 105665Kp/s 105665Kc/s 105665KC/s p}~~~..3    a
Mon Dec  6 15:31:23 +03 2021
```

```
Mon Dec  6 15:32:39 +03 2021
0g 0:00:02:31 99.38% (6) (ETA: 15:32:40) 0g/s 102383Kp/s 102383Kc/s 102383KC/s WcYl}a..ydYl}a
Mon Dec  6 15:32:40 +03 2021
0g 0:00:02:31 66.78% (7) (ETA: 15:33:55) 0g/s 103026Kp/s 103026Kc/s 103026KC/s H~~~~a..j    aa
0g 0:00:02:32 66.79% (7) (ETA: 15:33:56) 0g/s 102362Kp/s 102362Kc/s 102362KC/s  %@" aa..B&@" aa
Mon Dec  6 15:32:41 +03 2021
```

Somehow speed decreases steadily. The same happens with nt format:
```
$ echo '$NT$aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' > nt.pw
$ ./run/john nt.pw --mask='[ -~][ -~][ -~][ -~][ -~]a' --min-length=4 --max-length=7 --progress-every=1
[...]
0g 0:00:00:00  (4) 0g/s 0p/s 0c/s 0C/s
0g 0:00:00:01 77.54% (4) (ETA: 15:47:55) 0g/s 63154Kp/s 63154Kc/s 63154KC/s nc^i..oe^i
0g 0:00:00:01 1.04% (5) (ETA: 15:49:31) 0g/s 63140Kp/s 63140Kc/s 63140KC/s ~~~~.. "   
0g 0:00:00:02 1.58% (5) (ETA: 15:50:00) 0g/s 61673Kp/s 61673Kc/s 61673KC/s t7rP ..u9rP 
[...]
0g 0:00:02:12 99.60% (5) (ETA: 15:50:06) 0g/s 59002Kp/s 59002Kc/s 59002KC/s r.wZ~..s0wZ~
0g 0:00:02:12 50.26% (6) (ETA: 15:52:17) 0g/s 59236Kp/s 59236Kc/s 59236KC/s ~}~~~.. !   a
0g 0:00:02:13 50.44% (6) (ETA: 15:52:17) 0g/s 59000Kp/s 59000Kc/s 59000KC/s moB@ a..nqB@ a
[...]
0g 0:00:04:25 99.97% (6) (ETA: 15:52:19) 0g/s 58689Kp/s 58689Kc/s 58689KC/s oo{y~a..pq{y~a
0g 0:00:04:25 66.78% (7) (ETA: 15:54:30) 0g/s 58705Kp/s 58705Kc/s 58705KC/s ~|~~~a..     aa
0g 0:00:04:26 66.99% (7) (ETA: 15:54:31) 0g/s 58667Kp/s 58667Kc/s 58667KC/s 54XX aa..66XX aa
[...]
0g 0:00:06:52 99.83% (7) (ETA: 15:54:46) 0g/s 56447Kp/s 56447Kc/s 56447KC/s @j~Q~aa..Al~Q~aa
0g 0:00:06:52 DONE (7) (2021-12-06 15:54) 0g/s 56540Kp/s 56540Kc/s 56540KC/s !~~~~aa..~~~~~aa
```

While speed did not increase anywhere on timely status lines, the status lines for the switches and for DONE reported slightly higher speed.

**Comment by magnumripper** [comment]
Any mode basically reports `100.0 * status.cands / total` and `status.c` just does the math, factoring in elapsed time: "If we're at 50.26% after 2:12 minutes, the ETA is 130 seconds from now" and then it adds 130 seconds to current wall clock and displays that as the ETA.

> While speed did not increase anywhere on timely status lines, the status lines for the switches and for DONE reported slightly higher speed.

Are you talking about p/s figures now? They are not related at all (when it comes to code paths). But yes, sometimes I have a hard time understanding p/s figures (such as speed decreasing but ETA improving).

**Comment by magnumripper** [comment]
I'm closing this as I see nothing to fix, but we can continue the discussion if you like

**Comment by solardiz** [comment]
> sometimes I have a hard time understanding p/s figures (such as speed decreasing but ETA improving).

Maybe you were running wordlist mode? In there, the ETA could be by file offset, so would be affected by average line length changing across the file. IIRC, I was getting ETA improve when the wordlist was length-sorted (shorter words first), presumably because with shorter words the file offset was advancing slower per-word than it started to after advancing to longer words.

**Comment by magnumripper** [comment]
Oh, right. And also if using lots of rules that reject, right?

**Comment by AlekseyCherepanov** [comment]
Yes, I was talking about p/s or c/s:
```
59002Kp/s 59002Kc/s
59236Kp/s 59236Kc/s <- this is a peak
59000Kp/s 59000Kc/s
```

I noticed that there were rare peaks in reported speeds. I believe respective lines to be emitted due to switch of length (plus one for DONE status). I find this coincidence suspicious.

**Comment by AlekseyCherepanov** [comment]
Relative deviation of speed is comparable to ratio of 0.5s to current duration of session. My guess is that duration is used as integer number of seconds (I did not check code). So status lines happening in the same second would have slightly different c/s: later status line would have more candidates tried and higher c/s because number of seconds is the same. NT format is fast and has small batches, so timely status lines should be quite precise and happen early in each second. While status lines on switches happen randomly.

```
>>> (59236 - 59002) / 59236.0  # length 5->6 at 2:12
0.003950300492943481
>>> 0.5 / (2 * 60 + 12)
0.003787878787878788

>>> (58705 - 58689) / 58705.0  # length 6->7 at 4:25
0.0002725491866110212
>>> 0.5 / (4 * 60 + 25)
0.0018867924528301887

>>> (56540 - 56447) / 56540.0  # DONE at 6:52
0.0016448532012734347
>>> 0.5 / (6 * 60 + 52)
0.0012135922330097086
```
