### ISSUE TITLE
--pipe truncates lines sometimes

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#4923]
Working on #4921 @magnumripper mentioned "a race between fgetl() and a growing buffer so lines could be truncated" and possible affection of `--pipe`. The problem turned out true.

(`$.` is current line number in Perl. I print it to see that input passes through. It is counted from 1 while the first line is "0aa...".)
```
$ perl -le 'print $a++ . "a" x 100 while 1' | ./run/john --pipe --stdout | perl -lne 'print $. if $. % 1000000 == 0; print "wrong $. >$_<" if !/^\d+a{100}$/'
[...]
39000000
wrong 39505289 >39505288aaaaaaaaaaaaaaa<
wrong 39505290 ><
40000000
[...]
59000000
wrong 59206966 ><
wrong 59206967 ><
60000000
[...]
```
The numbers repeat on reruns, so it seems deterministic.

```
$ ./run/john
John the Ripper 1.9.0-jumbo-1+bleeding-5d450f267 2021-12-03 21:27:35 +0100 [linux-gnu 64-bit x86_64 SSE4.2 AC]
```

**Comment by magnumripper** [comment]
I think we should change pipe (and FIFO) mode to simply read a single word at a time and (if applicable) run it through all rules, reset *rules* and move to next word. There are pros and cons where it comes to performance (depending on situation though) but it would simplify code and IMHO work a lot better in most situations.

**Comment by magnumripper** [comment]
> I think we should change pipe (and FIFO) mode to simply read a single word at a time

Oh and I *think* that would solve this issue as well.

**Comment by magnumripper** [comment]
OTOH if we do so, `--pipe` mode becomes obsolete, because we could do the same for `--stdin` as well.

We could deprecate the `--pipe` option and (until dropping it) make it an alias for `--stdin`.

**Comment by AlekseyCherepanov** [comment]
I rechecked using files with the same result:
```
$ perl -le 'print $a++ . "a" x 100 for 0 .. 59207000' > t
$ ls -sh t
6.1G t
$ ./run/john --pipe --stdout < t > t2
[...]
$ perl -lne 'print $. if $. % 1000000 == 0; print "wrong $. >$_<" if !/^\d+a{100}$/' < t2
[... same as in the first message ...]
$ tail -n +39505280 t2 | head -n 20
[...]
39505288aaaaaaaaaaaaaaa

[...]
$ tail -n +39505280 t | head -n 20
[... ok ...]
```

**Comment by magnumripper** [comment]
Just putting this out to clear my head:
- wordlist + rules will run all of the wordlist through first rule, `seek()` to first line of wordlist and proceed to second rule.
- pipe + rules will fill a (d*mn good sized) buffer of words, run them through all rules, reset *to first rule* and proceed to fill the next batch of words. Unless EOF, it will do absolutely nothing untill the buffer is filled.

Oh, and anything + rules-stack will run each word through all rules, then reset *to first rule* and look for next word.

**Comment by magnumripper** [comment]
I've been tempted to rewrite wordlist.c from scratch for years.

#4923
#4907
#4906
#2354 
#428

Apart from these issues, `--loopback` should probably be completely separated from `wordlist.c` and have its own code (file).

**Comment by AlekseyCherepanov** [comment]
I tried `--pipe --stdout --rules=':'` and `--stdin --stdout` with 200M lines and the problem did not occur. `--pipe --stdout --rules-stack=':'` has the problem at the same positions as without rules.

**Comment by magnumripper** [comment]
> `--pipe --stdout --rules-stack=':'` has the problem at the same positions as without rules.

Then the million dollar question is: What about `--stdin --stdout --rules-stack=:`

**Comment by magnumripper** [comment]
> Then the million dollar question is: What about `--stdin --stdout --rules-stack=:`

I'm not 100% sure the above wouldn't be optimized away, so if you see no problems with it, try `--stdin --stdout --rules-stack=:l`

**Comment by AlekseyCherepanov** [comment]
Collecting together:

`--pipe --stdout` has the problem

`--pipe --stdout --rules=':'` -- no problem (17439M lines passed through)

`--pipe --stdout --rules=':l'` -- no problem (4313M)

`--pipe --stdout --rules-stack=':'` has the problem

`--pipe --stdout --rules-stack=':l'` has the problem

`--stdin --stdout` -- no problem (320M)

`--stdin --stdout --rules-stack=':'` -- no problem (202M)

`--stdin --stdout --rules-stack=':l'` -- no problem (1689M)

So it looks like `--rules-stack=':'` is not optimized out (at least for `--pipe`).

**Comment by AlekseyCherepanov** [comment]
I tried `--stdout --wordlist=/dev/stdin` and variations with rules. Plain and `--rules-stack=` variants have the problem. I posted it onto wrong page. The comments:
https://github.com/openwall/john/pull/4921#issuecomment-989920244
https://github.com/openwall/john/pull/4921#issuecomment-989926194

**Comment by magnumripper** [comment]
This was affected by e68baf2a78 because pipe mode use the same buffer size as `--mem-file-size`. After that commit, it happens much more often.
```
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
1000000
2000000
wrong 2788047 >2788046aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<
wrong 2788048 ><
3000000
4000000
wrong 4176929 ><
wrong 4176930 ><
5000000
wrong 5565810 ><
wrong 5565811 ><
6000000
6329929p 0:00:00:07 0.00% 838401p/s 6329928aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Session aborted
```

**Comment by magnumripper** [comment]
This is very strange. I have confirmed that right after filling the buffer, everything is fine and dandy - rules or not. Yet somehow when rules are not in use, the very last word of the buffer sometimes gets truncated or completely lost.

This does not happen with the very first batch of words. For the second, the last word gets truncated (last 5 characters missing) and an empty line is added. For the third and on, the whole last line is missing and two empty lines are instead output.

**Comment by magnumripper** [comment]
Found the problem. As expected it wasn't at all related to any race condition - it was due to an initialization of `last` re-occuring in pipe mode.
```diff
diff --git a/src/wordlist.c b/src/wordlist.c
index b3f3c4358..8527994aa 100644
--- a/src/wordlist.c
+++ b/src/wordlist.c
@@ -1055,6 +1055,7 @@ REDO_AFTER_LMLOOP:
                prerule = rpp_next(&ctx);
 
 /* A string that can't be produced by fgetl(). */
+       last = aligned.buffer[1];
        last[0] = '\n';
        last[1] = 0;
 
```
On second batch of words, `last` would still point to near the end of the buffer (now rewritten) so `last` could not be used reliably anyway. Even worse, we wrote "\n\0" into it.
