### ISSUE TITLE
Improve message for masks for format names that do not match

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#4925]
A cosmetic problem.

Current behaviour:
```
$ ./run/john --list=formats --format=asdf*
Unknown ciphertext format name requested

$ ./run/john --list=formats --format=asdf*,*
Error: No format matched 'asdf*'

$ ./run/john --list=formats --format=asdf,*
Error: No format matched 'asdf'
```

Expected:
```
$ ./run/john --list=formats --format=asdf*
Error: No format matched 'asdf*'

$ ./run/john --list=formats --format=asdf*,*
Error: No format matched 'asdf*'

$ ./run/john --list=formats --format=asdf,*
Unknown ciphertext format name requested
```

`Unknown ciphertext` is expected if the name is not a format class. Format class can be empty (e.g. vector, see #4903) and #4917 fixed message to be correct.

**Comment by magnumripper** [comment]
The easiest thing really would be to always say "Error: No format matched (...)" - and IMHO that wouldn't be too weird a message for any of the cases.

**Comment by AlekseyCherepanov** [comment]
Oops, my expected case 3 is really bad: it does not include name of offending format.

**Comment by AlekseyCherepanov** [comment]
I am very unsure, but "No format matched ..." might be confusing together with hash file, like "no format matched hashes from file".

Message should definitely include name for cases with comma. It will be slightly better for single format too: usage like `for f in raw-md5 raw-sha256; do john --format="$f" ...` would benefit from more informative message, but it is a matter of `echo $f`.

Now I realized clearly: it might be helpful to show word name/mask/class in the message. For instance, it would provide feedback that john treated 'vector' as class (currently john prints device name for this class, so I know that it was used for matching). It is not the easiest thing and I am not sure about real usefulness.

Like that:
```
$ ./run/john --list=formats --format=asdf
Error: No format matched the name 'asdf'

$ ./run/john --list=formats --format=asdf,*
Error: No format matched the name 'asdf'

$ ./run/john --list=formats --format=asdf*
Error: No format matched the mask 'asdf*'

$ ./run/john --list=formats --format=asdf*,*
Error: No format matched the mask 'asdf*'

$ ./run/john --list=formats --format=vector
Error: No format matched the class 'vector'

$ ./run/john --list=formats --format=vector,*
Error: No format matched the class 'vector'
```

I like word "requested" in "Unknown ciphertext format name requested". The word suggests that user should check options.

I played a bit with English->Russian google translate: "none of formats" works better in longer phrases than "no format". I have to admit that I don't know English good enough to talk about this difference. For me both variants are good.

My best variant:
```
Error: None of formats matched the requested class 'vector'
```

Or even
```
Error: None of formats matched the requested class 'vector' (--format= option)
```

Or maybe
```
Error: None of formats matched the class 'vector' (--format= option)
```

**Comment by magnumripper** [comment]
> I am very unsure, but "No format matched ..." might be confusing together with hash file, like "no format matched hashes from file".

I always meant the actual parameter filled in, as in "No format matched asdfg".

> name/**mask**/class

I prefer not to call it "mask" in this context as we use that term for `--mask` a lot. I think "wildcard" is better.

I will have a look at overall improving these messages.

**Comment by AlekseyCherepanov** [comment]
Indeed "mask" for format names would be confusing due to mask mode.

> > I am very unsure, but "No format matched ..." might be confusing together with hash file, like "no format matched hashes from file".
> 
> I always meant the actual parameter filled in, as in "No format matched asdfg".

I meant, after a command with a hash file, "no format matched asdfg" might be read like asdfg refers to a line in the file.

**Comment by magnumripper** [comment]
PR now #4931

**Comment by magnumripper** [comment]
```
$ for i in asdf "asdf,*" "asdf*" "asdf*,*" vector "vector,*" cpu,+opencl ; do echo -e "\n--format=$i: " ; ../run/john --list=formats --format=$i ; done

--format=asdf: 
Error: No format matched requested name 'asdf'

--format=asdf,*: 
Error: No format matched requested name 'asdf'

--format=asdf*: 
Error: No format matched requested wildcard 'asdf*'

--format=asdf*,*: 
Error: No format matched requested wildcard 'asdf*'

--format=vector: 
Device 1: Apple M1
Error: No format matched requested class 'vector'

--format=vector,*: 
Device 1: Apple M1
Error: No format matched requested class 'vector'

--format=cpu,+opencl: 
Error: No format matched requested 'cpu,+opencl' after processing '+opencl'
```

**Comment by magnumripper** [comment]
New version
```
$ for i in asdf "asdf,*" "asdf*" "asdf*,*" @sha513 "#SHA-4" vector "vector,*" cpu,+opencl ; do echo -e "\n--format=$i: " ; ../run/john --list=formats --format=$i ; done

--format=asdf: 
Error: No format matched requested name 'asdf'

--format=asdf,*: 
Error: No format matched requested name 'asdf'

--format=asdf*: 
Error: No format matched requested wildcard 'asdf*'

--format=asdf*,*: 
Error: No format matched requested wildcard 'asdf*'

--format=@sha513: 
Error: No format matched requested wildcard '@sha513'

--format=#SHA-4: 
Error: No format matched requested wildcard '#sha-4'

--format=vector: 
Device 1: Apple M1
Error: No format matched requested class 'vector'

--format=vector,*: 
Device 1: Apple M1
Error: No format matched requested class 'vector'

--format=cpu,+opencl: 
Error: No format matched requested 'cpu,+opencl' after processing '+opencl'
```

**Comment by AlekseyCherepanov** [comment]
Wow! Wow! Wow! I did not know about advanced selectors and underestimated complexity of fixes. I really like the fixes!

(Selectors are awesome! Just yesterday I thought to exclude format that hangs and it turns out I could just write `--format='vector,-krb5asrep-aes-opencl'`.)

That's nice:
```
--format='**,*':
Error: '**': Only one wildcard allowed in a format name
```

**Comment by AlekseyCherepanov** [comment]
It interacts with ad-hoc dynamic strangely:
```
--format='dynamic=sha256($p),dynamic=md5($p)':
dynamic=sha256($p)
1 formats

--format='dynamic':
as400-ssha1, asa-md5, dynamic=, [...]

--format='dynamic,dynamic=sha256($p)':
as400-ssha1, asa-md5, dynamic=sha256($p), [...]

--format='dynamic,dynamic=sha256($p),dynamic=md5($p)':
Error: No format matched requested name 'dynamic=md5($p)'

--format='dynamic,dynamic=sha256($p),dynamic=sha256($p)':
as400-ssha1, asa-md5, dynamic=sha256($p), [...]

--format='dynamic,dynamic=sha256($p),dynamic*':
as400-ssha1, asa-md5, dynamic=sha256($p), [...]

--format='dynamic,dynamic=sha256($p),*ynamic=sha256($p)':
as400-ssha1, asa-md5, dynamic=sha256($p), [...]

--format='dynamic,dynamic=sha256($p),dynamic=*':
Error: No format matched requested wildcard 'dynamic=*'

--format='dynamic,dynamic=sha256($p),dynamic=s*':
Error: No format matched requested wildcard 'dynamic=s*'

--format='dyna*mic=':
dynamic_n
1 formats (1 dynamic formats shown as just "dynamic_n" here)

--format='dynamic=':
dynamic=
1 formats

--format='nt,dynamic=,raw-md5':
NT, dynamic=, Raw-MD5
3 formats

--format='dynamic=,raw-md5':
Error: dynamic hash must start with md4/md5/sha1 and NOT a *_raw version. This expression one does not

--format='nt,dynamic=,raw-md5,dynamic=md5($p)':
NT, dynamic=md5($p), Raw-MD5
3 formats
```

`doc/OPTIONS`:
> The ad-hoc dynamic, or "dynamic compiler" format can not be used in a format list or with wildcards, only on it's own.  This is because the expression may need to include commas, wildcard etc.

Nevertheless it looks like john can handle commas:
- if list of formats starts with `dynamic=` then everything is a formula
- if list of formats starts with regular name/class/wildcard, then everything is split by comma
- after split, first ad-hoc dynamic replaces `dynamic=` format
  - `dynamic=` without further chars is a regular name
- so next ad-hoc should match full(?) string or it would fail as "name"
  - if name starts with `dynamic=`, the name is treated literally, so wildcards are not processed and it does not match any formats (while reported as wildcard)

This theory does not cover result of `--format='dyna*mic='`.

Problem in the example: `dynamic=s*` is reported as wildcard, but it does not seem to work like wildcard.

**Comment by AlekseyCherepanov** [comment]
Problem with `dynamic=s*` does not seem requiring a fix. Logic behind reporting is not tied to other parts of code, so it is a purely cosmetic problem. Fix would add code. I think user should be deliberate to hit the problem. Natural way to hit it would be to use `*@#` in a constant and to make 2 ad-hoc dynamics together, but constants require commas.

**Comment by AlekseyCherepanov** [comment]
Hm, builds without opencl/ztex get "name" in messages for these classes.
```
--format=ztex:
Error: No format matched requested name 'ztex'

--format=opencl:
Error: No format matched requested name 'opencl'
```

BTW I noticed that any string is ok for exclusion. It may be convenient using same command with several builds which have or lack some format.
```
--format=nt,-asdf:
NT
1 formats
```

**Comment by AlekseyCherepanov** [comment]
Ok example:
```
--format=all,-all:
Error: No format matched requested class 'all' after exclusions
```

BTW exclusions / all steps could be printed one by one with higher `--verbosity`. (Just idea. I don't think it should be implemented.)

Somehow "name" is printed instead of "class". I guess `-` kept in the name affects `fmt_is_class()`. Anyway message seems wrong.
```
--format=-all:
Error: No format matched requested name '-all'
```

Similar behaviour with more confusing(?) message:
```
--format='-*':
Error: No format matched requested wildcard '-*'
```

segfault excluding all formats and not specifying any:
```
--format=,-all:
Segmentation fault

--format=-enabled,-dynamic:
Segmentation fault
```

Hm, `+` and `-` are handled differently alone and on list:
```
--format='+':
Error: No format matched requested name '+'

--format=',+':
Error: '+' in format list doesn't make sense

--format='-':
Error: No format matched requested name '-'

--format='-,':
Error: '-' in format list doesn't make sense
```

**Comment by magnumripper** [comment]
I made some changes, addressing some things you found and the segfaults. Not everything is easy to make better without adding too much code.

Newest version:
```
$ for i in asdf "asdf,*" "asdf*" "asdf*,*" @sha513 "#SHA-4" vector "vector,*" cpu,+opencl ztex "-all" "-*" ",-all:" "-enabled,-dynamic" ; do echo -e "\n--format=$i: " ; ../run/john --list=formats --format=$i ; done

--format=asdf: 
Error: No format matched requested name 'asdf'

--format=asdf,*: 
Error: No format matched requested name 'asdf'

--format=asdf*: 
Error: No format matched requested wildcard 'asdf*'

--format=asdf*,*: 
Error: No format matched requested wildcard 'asdf*'

--format=@sha513: 
Error: No format matched requested wildcard '@sha513'

--format=#SHA-4: 
Error: No format matched requested wildcard '#sha-4'

--format=vector: 
Device 3: AMD Radeon Pro Vega 20 Compute Engine
Error: No format matched requested class 'vector'

--format=vector,*: 
Device 3: AMD Radeon Pro Vega 20 Compute Engine
Error: No format matched requested class 'vector'

--format=cpu,+opencl: 
Error: No format matched requested 'cpu,+opencl' after processing '+opencl'

--format=ztex: 
Error: No format matched requested class 'ztex'

--format=-all: 
Error: No format matched requested class '-all'

--format=-*: 
Error: No format matched requested wildcard '-*'

--format=,-all:: 
Error: No format matched requested name ',-all:'

--format=-enabled,-dynamic: 
Error: No format matched requested criteria '-enabled,-dynamic'
```
That last line is a catch-all for odd input so it wont give any more details (it fixed the segfaults).

**Comment by AlekseyCherepanov** [comment]
BTW empty elements on list are ignored. I don't think it should be fixed. I just saw a check for starting comma.
```
--format='nt,,,nt,,':
NT
1 formats
```

`@` and `#` ignore everything on the left hand side:
```
--format='asdf@':
[...]
507 formats (149 dynamic formats shown as just "dynamic_n" here)

--format='asdf#':
[...]
```

Also I noticed that excluding anything enables disabled formats:
```
--format='-asdf':
[...]
823 formats (465 dynamic formats shown as just "dynamic_n" here)
```

**Comment by magnumripper** [comment]
Thanks, I'll have a look at those two last issues too.

**Comment by magnumripper** [comment]
Now
```
--format=asdf@: 
Error: No format matched requested name 'asdf@'

--format=as#df: 
Error: No format matched requested name 'as#df'
```
I deliberately don't call them "wildcard" in the messages because they are now only wildcards at the beginning of a string.

> Also I noticed that excluding anything enables disabled formats

This is done deliberately so I don't dare changing it - it'd probably break something I can't remember!

**Comment by magnumripper** [comment]
> `--format='-asdf'`

If you need to do that IRL and the disabled formats hits you, you can always disable them explicitly as in `--format=-asdf,-disabled`

**Comment by AlekseyCherepanov** [comment]
Just to document:

Theoretical problem: code to handle `*` is placed before code for `@`/`#` in `fmt_match()`, so `#*` would fail searching for format labels starting with `#` instead of search `*` in the long format names. But `*` does not occur there anyway. Empty output:
```
$ ./run/john --list=format-all-details --format=all | grep -v '^Example ciphertext' | grep -F '*'
```

Hm, the check for comma in the first char changed behaviour slightly:
```
--format=',,,,':
Error: No format matched requested name ',,,,'
```

Without the check:
```
--format=',,,,,,,,':
Error: Format list ',,,,,,,,' made no sense
```

Another change in behaviour: `@`/`#` without any chars on the right hand do not match anything, previously they matched everything.

**Comment by AlekseyCherepanov** [comment]
Just to document:

I tried to disable all formats. It turned out that I cannot disable `dynamic=` because syntax is `formatname = Y`.

Preparations:
```
$ grep -v -e Disabled:Formats -e dynamic_disabled run/john.conf > john.conf
$ ./run/john --config=john.conf --list=formats --format=all,dynamic | perl -pe 's/\n//; s/, /\n/g' > allformats
$ (printf '.include \x27john.conf\x27\n[Disabled:Formats]\n'; perl -pe 's/$/ = Y/' < allformats) > dis.conf
```

Result:
```
$ ./run/john --config=dis.conf --list=formats
dynamic_n
1 formats (1 dynamic formats shown as just "dynamic_n" here)

$ ./run/john --config=dis.conf --list=formats --format=-disabled
dynamic=
1 formats
```
