### ISSUE TITLE
Bitlocker OpenCL format can't crack its own test vectors

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4929]
The last two test vectors, "Recovery Password attack" and "Same test with MAC verification" (neither supported at all by the CPU version) somehow pass self-test but fails if you put them in a file and try to crack them.

```
$ ./jtrts.pl -internal bitlocker-opencl 
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, JimF & others
- Testing:  John the Ripper 1.9.0-jumbo-1+bleeding-79cb84652 2021-12-10 18:46:29 +0100 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
--------------------------------------------------------------------------------

John Jumbo build detected.
Running JTRTS in -internal mode

form=bitlocker-opencl             guesses:    7 -show=   7 0:00:00:33 DONE : Expected count(s) (9)(-show9)  [!!!FAILED1!!!  ret_val=0]
.pot CHK:bitlocker-opencl         guesses:    7 0:00:00:26 DONE  [PASSED] (0 val-pwd)
Some tests had Errors. Performed 1 tests.  1 errors
Time used was 74 seconds
```

**Comment by magnumripper** [comment]
@claudioandre-br I assume this problem went under your radar because you disable this format for being extremely slow?

**Comment by magnumripper** [comment]
The support for that format was added by @e-ago in 6c1e2a46317

**Comment by ghost** [comment]
> @claudioandre-br I assume this problem went under your radar because you disable this format for being extremely slow?

I used to have `--internal` enabled for all CI executions. It is not the case nowadays.

Anyway, I actually have a note of bitlocker failing with TS --internall specifically.

**Comment by solardiz** [comment]
> The last two test vectors, "Recovery Password attack" and "Same test with MAC verification" (neither supported at all by the CPU version) somehow pass self-test but fails if you put them in a file and try to crack them.

I'm playing with the first one of these, and I cannot reproduce the issue - it gets cracked fine when the recovery code is put in a wordlist. Tried different GPUs with auto-detected as well as adjusted (low) LWS/GWS, different placement of the recovery code in wordlist file - still cracks fine. I did not try the second test vector yet, nor the test suite.

I observe another bug, though - even once already cracked, the "hash" can be loaded and cracked again, producing a duplicate line in the pot file. Yet `--show` finds it. That's weird. Maybe this was also the bug detected by TS?

**Comment by solardiz** [comment]
OK, reproduced - needed to have two different "hashes" loaded at once (User Password and Recovery Password). The bug is that `set_key` relies on `set_salt`, which isn't how these were meant to work. We normally do it the other way around - first set all keys, then iterate the salts - and even then, such inter-dependencies are not intentionally supported.

> I observe another bug, though - even once already cracked, the "hash" can be loaded and cracked again

This other bug also affects User Password "hashes".

**Comment by solardiz** [comment]
> > I observe another bug, though - even once already cracked, the "hash" can be loaded and cracked again
> 
> This other bug also affects User Password "hashes".

Oh, I guess `FMT_NOT_EXACT` does that. It's OK then.

**Comment by solardiz** [comment]
> The bug is that `set_key` relies on `set_salt`, which isn't how these were meant to work.

Besides, User and Recovery passwords are just not meant to be cracked in the same session, because they require very different candidate password streams. Yet since such mixes of "hashes" can technically be loaded at once, and some of our users wrongly will do just that, we need to support this right.
