### ISSUE TITLE
bcrypt-opencl prints additional newline after lws/gws

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#4930]
bcrypt-opencl prints newline after `LWS=4 GWS=4096`. So `DONE` is put onto a separate line. Also other opencl formats print either blocks and/or mask's multiplier (except mscash2-opencl that is special).

```
$ ./run/john --device=2 --test --format=bcrypt-opencl
Device 2: Hawaii [AMD Radeon (TM) R9 390 Series]
Benchmarking: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... LWS=4 GWS=4096
DONE
```

Both lws/gws and the newline are printed onto stderr:
```
$ ./run/john --device=2 --test --format=bcrypt-opencl 2>/dev/null
Benchmarking: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... DONE
```

Examples of other formats:
```
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=256 GWS=20480 (80 blocks) DONE

Benchmarking: NT-opencl [MD4 OpenCL/mask accel]... LWS=64 GWS=163840 (2560 blocks) x8580 DONE

Benchmarking: raw-MD4-opencl [MD4 OpenCL/mask accel]... LWS=128 GWS=131072 x8580 DONE
```

**Comment by solardiz** [comment]
@AlekseyCherepanov We're well aware that `bcrypt-opencl` badly needs a rewrite for plenty of other/real reasons. Even removing printing of this newline isn't a trivial fix, because while the newline is excessive in `--test`, it probably is not when the format is actually used. We could spend/waste time on this cosmetic fix (please feel free to send a PR removing this newline printing conditionally), but is this worth the bother? Would you contribute a proper rewrite of the format? Thanks!

I reluctantly label this issue a "bug", although the real bug is the format needs a rewrite.

**Comment by AlekseyCherepanov** [comment]
Indeed this newline is needed during a regular attack.

I hoped it would be something trivial, maybe introduced with recent fixes, or maybe reflecting other more important problem. Well, it reflects a need of rewrite... Unfortunately I will not pick it up.

#3673 mentions rewrite.

Feel free to close the issue.

**Comment by AlekseyCherepanov** [comment]
There is still a very small difference: formats using `opencl_autotune.h` print space on the end of line during attacks, while bcrypt-opencl (and sl3-opencl, des-opencl, lm-opencl and some others) do not print it.

```
$ ../run/john --format=raw-SHA256-opencl --mask='?a?a?a?a?a' --fork=2 <(echo 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
[...]
Device 1: AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.40.0, 5.10.0-9-amd64, LLVM 11.0.1)
Device 1: AMD Radeon (TM) R9 390 Series (HAWAII, DRM 3.40.0, 5.10.0-9-amd64, LLVM 11.0.1)
```

```
2: LWS=256 GWS=40960 (160 blocks) x9025 <-- there is space here
1: LWS=64 GWS=40960 (640 blocks) x9025 <-- there is space here
```

```
Press 'q' or Ctrl-C to abort, almost any other key for status
2 0g 0:00:00:05 N/A 0g/s 699621Kp/s 699621Kc/s 699621KC/s aal"{..aal"{
1 0g 0:00:00:06 N/A 0g/s 643743Kp/s 643743Kc/s 643743KC/s aaPEq..aaPEq
Waiting for 1 child to terminate
Session completed. 
```

Also space is printed after `Session completed.`, but that's other problem.

BTW should not node be printed before devices?

**Comment by AlekseyCherepanov** [comment]
Rerunning `bcrypt-opencl` it turned out that output can be mixed:
```
$ ../run/john --format=bcrypt-opencl --mask='?a?a?a?a?a' --fork=2 <(echo '$2a$05$000000000000000000004.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW')
[...]
1: 2: LWS=4 GWS=4096 (1024 blocks)
LWS=4 GWS=4096 (1024 blocks)
[...]
```

I cannot reproduce it with other format. But code looks similar and `strace -e trace=write` suggests that each `fprintf` becomes a separate `write` syscall, so lines can be intermixed.

**Comment by solardiz** [comment]
> BTW should not node be printed before devices?

That's a separate issue, but yes, I think it would be helpful. Please feel free to create a PR for that. Thanks!

**Comment by magnumripper** [comment]
> each `fprintf` becomes a separate `write` syscall, so lines can be intermixed.

I use to fix interleaved writing when I see it but in this case I haven't (I usually run MPI as opposed to fork, so greater chance of being delayed slightly differently).

The shared code in `opencl_autotune.h` is (I think) too complex to reduce to a single `fprintf` call (would be an unreadable mess of ternaries) so the most sane solution would probably be to `sprintf` to a buffer and then output the completed buffer in one call like we do in `status.c`.
