### ISSUE TITLE
Review and make consistent the new_keys logic in OpenCL formats

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4932]
In most OpenCL formats, we transfer the keys to device `if (ocl_autotune_running || new_keys)`. In some, the `ocl_autotune_running ||` part of the condition is missing - should we add it? If we do, perhaps we need to see the effect it has on auto-tuning and the resulting speeds for those formats.

```$ grep 'if (.*new_keys' opencl_*.c
opencl_7z_fmt_plug.c:   if (ocl_autotune_running || new_keys) {
opencl_androidbackup_fmt_plug.c:        if (ocl_autotune_running || new_keys) {
opencl_bitcoin_fmt_plug.c:      if (new_keys) {
opencl_blockchain_fmt_plug.c:   if (ocl_autotune_running || new_keys) {
opencl_cryptosafe_fmt_plug.c:   if (new_keys || ocl_autotune_running) {
opencl_dashlane_fmt_plug.c:     if (ocl_autotune_running || new_keys) {
opencl_dmg_fmt_plug.c:  if (ocl_autotune_running || new_keys) {
opencl_encfs_fmt_plug.c:        if (ocl_autotune_running || new_keys) {
opencl_enpass_fmt_plug.c:       if (ocl_autotune_running || new_keys) {
opencl_ethereum_presale_fmt_plug.c:     if (new_keys || ocl_autotune_running || global_work_size > keys_done) {
opencl_iwork_fmt_plug.c:        if (ocl_autotune_running || new_keys) {
opencl_keystore_fmt_plug.c:     if (new_keys || ocl_autotune_running) {
opencl_krb5_asrep_aes_fmt_plug.c:       if (ocl_autotune_running || new_keys) {
opencl_krb5pa-md5_fmt_plug.c:   if (set_new_keys || ocl_autotune_running) {
opencl_krb5pa-sha1_fmt_plug.c:  if (ocl_autotune_running || new_keys) {
opencl_lastpass_cli_fmt_plug.c: if (new_keys || ocl_autotune_running) {
opencl_lastpass_fmt_plug.c:     if (new_keys || ocl_autotune_running) {
opencl_md5crypt_fmt_plug.c:     if (new_keys)
opencl_mscash_fmt_plug.c:       if (set_new_keys || ocl_autotune_running) {
opencl_ntlmv2_fmt_plug.c:       if (set_new_keys || ocl_autotune_running) {
opencl_office_fmt_plug.c:       if (ocl_autotune_running || new_keys) {
opencl_oldoffice_fmt_plug.c:    if (new_keys || ocl_autotune_running) {
opencl_openbsdsoftraid_fmt_plug.c:      if (ocl_autotune_running || new_keys) {
opencl_pbkdf2_hmac_md4_fmt_plug.c:      if (ocl_autotune_running || new_keys) {
opencl_pbkdf2_hmac_md5_fmt_plug.c:      if (ocl_autotune_running || new_keys) {
opencl_pbkdf2_hmac_sha1_fmt_plug.c:     if (ocl_autotune_running || new_keys) {
opencl_pem_fmt_plug.c:  if (ocl_autotune_running || new_keys) {
opencl_phpass_fmt_plug.c:       if (new_keys) {
opencl_rawsha512_gpl_fmt_plug.c:        if (new_keys && key_idx > offset)
opencl_rawsha512_gpl_fmt_plug.c:        if (new_keys && mask_int_cand.num_int_cand > 1) {
opencl_sha1crypt_fmt_plug.c:    if (ocl_autotune_running || new_keys) {
opencl_sha256crypt_fmt_plug.c:  if (new_keys) {
opencl_sha512crypt_fmt_plug.c:  if (new_keys) {
opencl_solarwinds_fmt_plug.c:   if (ocl_autotune_running || new_keys) {
opencl_strip_fmt_plug.c:        if (new_keys || ocl_autotune_running) {
opencl_telegram_fmt_plug.c:     if (ocl_autotune_running || new_keys) {
opencl_vmx_fmt_plug.c:  if (ocl_autotune_running || new_keys) {
opencl_zip_fmt_plug.c:  if (new_keys || ocl_autotune_running) {
```

**Comment by solardiz** [comment]
Besides, at least three salted formats mysteriously lack this logic - it's not in `opencl_pbkdf2_hmac_sha256_fmt_plug.c`, `opencl_pbkdf2_hmac_sha512_fmt_plug.c`, nor in `opencl_tezos_fmt_plug.c`. There might be more.

**Comment by solardiz** [comment]
#4933 fixes this for tezos-opencl.

**Comment by solardiz** [comment]
What is the reason to have `ocl_autotune_running ||`? Don't we use a separate profiling event for the actual kernel invocation anyway, and use that for the auto-tuning?

Moreover, in formats that use a split kernel we could actually want to exclude the transfer time from the auto-tuning, because otherwise its share would be disproportionately high (would not reflect what happens in actual cracking, where the split kernel would be invoked in a loop). To do this, should we omit the `ocl_autotune_running ||` or does such exclusion happen automatically due to the separate profiling event?

**Comment by magnumripper** [comment]
> What is the reason to have `ocl_autotune_running ||`? Don't we use a separate profiling event for the actual kernel invocation anyway, and use that for the auto-tuning?

Off the top of my head that's just to be sure to get event profiling for it (mostly for developers), and... see below:

> Moreover, in formats that use a split kernel we could actually want to exclude the transfer time from the auto-tuning, because otherwise its share would be disproportionately high (would not reflect what happens in actual cracking, where the split kernel would be invoked in a loop). To do this, should we omit the `ocl_autotune_running ||` or does such exclusion happen automatically due to the separate profiling event?

During autotune, the loop kernel is only ran once but its duration will be multiplied with the second argument to `autotune_run()` - i.e. (or e.g.) `ITERATIONS`.

**Comment by solardiz** [comment]
> Off the top of my head that's just to be sure to get event profiling for it (mostly for developers)

Can something break if we don't re-transfer the keys? Maybe the real issue is that the GWS may have changed yet no new calls to `set_key()` made before we call `crypt_all()` again? If so, we'd be processing uninitialized data on device side. OTOH, wouldn't we be transferring uninitialized data from host to device, which is about as bad?

BTW, I notice that many of our kernels are written such that they trust length fields received from host, and can crash the device if those are invalid (e.g., genuinely exceed the kernel's limitations, were uninitialized on host, not actually transferred, in wrong endianness for a given device, or corrupted during transfer). I think we should generally want to fix the kernels to be safe (not crash, not overwrite adjacent work-items' data) even on invalid inputs. I fixed `tezos_kernel.cl` in this respect yesterday. Today I noticed `pfx_kernel.cl` is similarly risky.

> During autotune, the loop kernel is only ran once but its duration will be multiplied with the second argument to autotune_run() - i.e. (or e.g.) ITERATIONS.

OK, so during autotune we extrapolate to full duration for `ITERATIONS` or such:

```c
                runtime += (looptime * rounds) / (hash_loops * total);
```

**Comment by magnumripper** [comment]
> Can something break if we don't re-transfer the keys?

If the normal code path (not autotuning) works fine, then all is good.

However, if we *are* in autotune and skip that code block, that profiling event will be undefined (IIRC). If it had merely returned the kernel duration for an earlier call it would be fine, but it doesn't.

**Comment by solardiz** [comment]
> if we _are_ in autotune and skip that code block, that profiling event will be undefined (IIRC).

So do you suggest we standardize on `new_keys || ocl_autotune_running` for all formats? Would you create a PR with this, fixing this issue, if so? Thanks!

**Comment by magnumripper** [comment]
As long as the code block in question has profiling enabled, yes I suppose we should.

**Comment by magnumripper** [comment]
I created an issue for it, but now realized *this* is the issue. I'll review it and make a PR.

**Comment by magnumripper** [comment]
Like I said in the PR:
*After testing this I'm starting to think the `ocl_autotune_running || ` isn't needed anymore. Absolutely nothing changed! All profiling data is there anyway. I'll review the functions in `opencl_common.c`. My current guess is it was needed for some earlier versions of them (I guess we re-send the keys each time now).*

Reviewing `opencl_common.c`, I see that `opencl_find_best_lws()` will call `crypt_all()` several times (first a warm-up run, then a timing run, then a loop with increasing LWS) after only setting keys before the first time. However *it only checks the main event*, ie. the loop kernel. So that's fine.

`gws_test()` on the other hand, sets keys before each `crypt_all()`.

So my conclusion is we could instead make things consistent by *dropping* the `ocl_autotune_running || ` from the `new_keys` checks. On the other hand, it wont make any difference.

**Comment by magnumripper** [comment]
BTW just to be "safe from core changes" we could just as well have it this way:
```c
	if (new_keys || multi_profilingEvent[0]) {
		(... some code using multi_profilingEvent[0] ...)
	}
```
That way, if caller wants profiling, we will comply. The last thing autotune does is turn off profiling and set all multi_profilingEvent's to NULL.

But I think we should just drop the `ocl_autotune_running` and be done with it. Should I make a PR for that?

**Comment by solardiz** [comment]
BTW, I was wondering whether I could reasonably use the profiling events instead of my `john_get_nano()` calls in 35712a565039153e5b5b82cba945474e152c0eb3, but I felt that would be more complicated.

> I think we should just drop the `ocl_autotune_running` and be done with it. Should I make a PR for that?

Yes, I think so - but make sure to test it. Thanks!

**Comment by magnumripper** [comment]
So (note to self) I'll make a PR with that, and a separate commit in same PR with adding `new_keys` logic to any salted format that lacks it

**Comment by magnumripper** [comment]
> ```
> opencl_rawsha512_gpl_fmt_plug.c:        if (new_keys && key_idx > offset)
> opencl_rawsha512_gpl_fmt_plug.c:        if (new_keys && mask_int_cand.num_int_cand > 1) {
> ```
This had me confused for a while, but that file also contain XSHA512-opencl, which is salted. And anyway it doesn't need any fix.

**Comment by magnumripper** [comment]
> BTW, I was wondering whether I could reasonably use the profiling events instead of my `john_get_nano()` calls in [35712a5](https://github.com/openwall/john/commit/35712a565039153e5b5b82cba945474e152c0eb3), but I felt that would be more complicated.

That would mean profiling enabled while cracking - not sure if that hurts in any significant way (I guess it would not) but it would definitely be more complicated. I think `john_get_nano()` is as simple as it gets.
