### ISSUE TITLE
Warning about too few candidates is confusing on salt restore and GWS increase

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4939]
When restoring a multi-salt session and GWS increases, we get e.g.:

```
LWS=256 GWS=262144 (1024 blocks)
Proceeding with wordlist:words.lst, lengths: 5-125
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 60:19:10:42 60.13% (ETA: 2022-01-22 23:18) 0g/s 1087p/s 4350c/s 4350C/s mclean2361
Warning: Only 65536 candidates left, minimum 262144 needed for performance.
```

I think we'd rather suppress that warning in such case, or maybe adjust its wording - in fact, how about we change the word "left" to "buffered" (for all cases, not just the above)? Also, how about "un-warning" when the number of buffered candidates becomes sufficient? Something like:

```
Warning: Only 65536 candidates buffered, minimum 262144 needed for performance
OK: Enough candidates buffered now
```

This "un-warning" can then also happen in batch mode.

**Comment by solardiz** [comment]
We already use the word "buffered" in some cases:

```c
			fprintf(stderr, "Warning: Only %d%s candidate%s %s, "
			        "minimum %d needed for performance.\n",
			        crk_key_index,
			        mask_int_cand.num_int_cand > 1 ? " base" : "",
			        crk_key_index > 1 ? "s" : "",
			        single_running ? "buffered for the current salt" :
			        mask_increments_len ? "buffered" : "left",
			        crk_params->min_keys_per_crypt);
```

I think there are more cases where the word "left" is confusing, so maybe we should just change `mask_increments_len ? "buffered" : "left"` to unconditional `"buffered"`, or simplifying this further move `"buffered "` into the main printf format string and keep only `"for the current salt"` conditional.

**Comment by magnumripper** [comment]
Agreed, although the "un-warning" could be non-trivial (just a gut feeling, didn't look).
