### ISSUE TITLE
macOS can't build Tezos kernel

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4945]
```
Build log: In file included from <program source>:196:
In file included from opencl/ed25519-donna/ed25519-donna.c:7:
In file included from opencl/ed25519-donna/ed25519-donna.h:13:
opencl/ed25519-donna/curve25519-donna-32bit.h:325:83: error: parameter may not be qualified with an address space
curve25519_mul_const(bignum25519 out, const bignum25519 a, __constant bignum25519 b) {
                                                                                  ^
opencl/ed25519-donna/curve25519-donna-32bit.h:537:71: error: parameter may not be qualified with an address space
curve25519_move_conditional_bytes(uint8_t out[96], __constant uint8_t in[96], uint32_t flag) {
                                                                      ^
In file included from <program source>:196:
In file included from opencl/ed25519-donna/ed25519-donna.c:7:
In file included from opencl/ed25519-donna/ed25519-donna.h:42:
opencl/ed25519-donna/ed25519-donna-impl-base.h:96:75: error: parameter may not be qualified with an address space
ge25519_scalarmult_base_choose_niels(ge25519_niels *t, __constant uint8_t table[256][96], uint32_t pos, signed char b) {
                                                                          ^
opencl/ed25519-donna/ed25519-donna-impl-base.h:124:62: error: parameter may not be qualified with an address space
ge25519_scalarmult_base_niels(ge25519 *r, __constant uint8_t basepoint_table[256][96], const bignum256modm s) {
                                                             ^

Error building kernel ../run/opencl/tezos_kernel.cl. DEVICE_INFO=522
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1294 - clBuildProgram
```

**Comment by magnumripper** [comment]
Other warnings:
```
Build log: <program source>:167:27: warning: comparison of integers of different signs: 'int' and 'unsigned int'
                for (int i = saltlen; i < saltlen + (8 - saltlen % 8); i++)  // zeroize buffer correctly
                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
<program source>:177:27: warning: comparison of integers of different signs: 'int' and 'unsigned int'
                for (int i = passlen; i < passlen + (8 - passlen % 8); i++)  // zeroize buffer correctly
                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from <program source>:194:
In file included from opencl/ed25519-donna/ed25519-donna.c:9:
opencl/ed25519-donna/ed25519-hash.h:6:1: warning: unused function 'ed25519_hash_init'
ed25519_hash_init(ed25519_hash_context *ctx) {
^
opencl/ed25519-donna/ed25519-hash.h:11:1: warning: unused function 'ed25519_hash_update'
ed25519_hash_update(ed25519_hash_context *ctx, const uint8_t *in, size_t inlen) {
^
opencl/ed25519-donna/ed25519-hash.h:16:1: warning: unused function 'ed25519_hash_final'
ed25519_hash_final(ed25519_hash_context *ctx, uint8_t *hash) {
^
```

**Comment by magnumripper** [comment]
It seems we can have `__constant uint8_t *in` but not `__constant uint8_t in[96]`. I recall having had same problems with other code ported to OpenCL.

**Comment by magnumripper** [comment]
If memory serves me, I had to replace `__global unsigned char iv[16]` in some kernel function argument with `__global unsigned char *iv` when I ported AES-CBC or something like that.

In this case, apparently `__constant uint8_t basepoint_table[256][96]` is tricker. Shouldn't `__constant uint8_t **basepoint_table` do the trick? It doesn't.

**Comment by magnumripper** [comment]
I could work around it by simply stop passing it along at all (it's a constant table after all). But I'm not sure this is the solution?

**Comment by solardiz** [comment]
> If memory serves me, I had to replace `__global unsigned char iv[16]` in some kernel function argument with `__global unsigned char *iv` when I ported AES-CBC or something like that.

I actually made several changes of this sort when porting ed25519-donna from C to OpenCL - you can diff against the original (which we have under `src`) and see. I wonder why I didn't run into this one you're seeing now. I tested with all OpenCL compilers we have on "super" and "well".

**Comment by magnumripper** [comment]
My workaround experiment is #4946

**Comment by solardiz** [comment]
BTW, I am considering also porting BLAKE2b and using it in the Tezos kernel. I'll probably start with this small implementation that was initially prepared for the BLAKE2 RFC: https://github.com/mjosaarinen/blake2_mjosref

**Comment by magnumripper** [comment]
> I wonder why I didn't run into this one you're seeing now. I tested with all OpenCL compilers we have on "super" and "well".

When I googled it, I got the impression Intel's OpenCL wouldn't allow it. But then again there's several incarnations of them.

**Comment by magnumripper** [comment]
I still don't understand why `uint8_t **basepoint_table` wouldn't do it. Isn't that normally just fine in C?

**Comment by magnumripper** [comment]
> I still don't understand why `uint8_t **basepoint_table` wouldn't do it. Isn't that normally just fine in C?

Hmm no I tried it in C and it didn't work at all. Not sure I understand why... is there no way around it?

**Comment by solardiz** [comment]
> I still don't understand why `uint8_t **basepoint_table` wouldn't do it.

Because that would be right for an array of pointers (like e.g. `argv`), but not for a two-dimensional array. While you can index these two kinds using the same syntax (e.g., `argv[1][1]` works even though `argv` is an array of pointers), it's different under the hood, and the compiler needs to be told which kind it's dealing with.
