### ISSUE TITLE
Some OpenCL format struct names are weird

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4957]
Somehow some of these names start with `fmt_ocl_` while most start with `fmt_opencl_`. Is this intentional? It causes the `fmt_ocl_` to be listed/tested/benchmarked first. Then there's `fmt_opencl_1otus5` with a `1` (one) in there. So the first OpenCL formats become:

```c
john_register_one(&fmt_ocl_cryptosafe);
john_register_one(&fmt_ocl_cryptsha1);
john_register_one(&fmt_ocl_KeePass);
john_register_one(&fmt_ocl_oldoff);
john_register_one(&fmt_ocl_pbkdf2_md4);
john_register_one(&fmt_ocl_pbkdf2_md5);
john_register_one(&fmt_ocl_pbkdf2_sha1);
john_register_one(&fmt_ocl_rar);
john_register_one(&fmt_ocl_rar5);
john_register_one(&fmt_ocl_tc);
john_register_one(&fmt_opencl_1otus5);
```

I think this is a bug and we should rename them to `fmt_opencl_` and change the `1` to `l`.

**Comment by magnumripper** [comment]
Some of our format struct names (for CPU as well) was renamed for tweaking precedence but I'm not aware of that being the case of `fmt_ocl_` vs. `fmt_opencl_` (nor for the 1otus5).
