### ISSUE TITLE
Review README.coding-style

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#4960]
We've drifted from a max. recommended line width of 80 to 120 but the document doesn't reflect it. I saw a few typos in there as well.

BTW I thought we had a recommendation against Yoda speak like `if (1 == foo)` but apparently it didn't make it into that document. I guess I can live with it but my brain hiccups every time I need to read things in reverse order.

**Comment by solardiz** [comment]
> We've drifted from a max. recommended line width of 80 to 120

In practice, I use 132-wide terminal windows now, and let lines go to 131 (although they very rarely do). That's with 8-char tabs.

**Comment by solardiz** [comment]
Apparently, we also need to update `CONTRIBUTING.md`.

**Comment by magnumripper** [comment]
> > We've drifted from a max. recommended line width of 80 to 120
> 
> In practice, I use 132-wide terminal windows now, and let lines go to 131 (although they very rarely do). That's with 8-char tabs.

I use 120 but a tab width of 4 so it's the same ballpark. Not sure how to put it in that document?

**Comment by magnumripper** [comment]
> Apparently, we also need to update `CONTRIBUTING.md`.

This was fixed in d95c9834bb3
