### ISSUE TITLE
tezos-opencl fails self-test on 2080Ti with 465.19.01 after BLAKE2b-on-device commit

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4963]
As @magnumripper wrote in #4955:

> I just noticed tezos now fails on my 2080ti with 465.19.01
> 
> $ make -s kernel-cache-clean
> $ ../run/john -test -form:tezos-opencl
> Device 2: NVIDIA GeForce RTX 2080 Ti
> Benchmarking: tezos-opencl, Tezos Key [PBKDF2-SHA512 OpenCL]... FAILED (cmp_all(1))
> 
> Reverting to f683f0f fixes it. I can try to see if I can workaround it when I get some time.

**Comment by solardiz** [comment]
According to @Promethus029 in #4964, this issue is also seen on:

```
Platform #0 name: NVIDIA CUDA, version: OpenCL 3.0 CUDA 11.4.158
    Device #0 (1) name:     NVIDIA GeForce GTX 1070
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 3.0 CUDA
    Driver version:         470.86 [recommended]
```

**Comment by solardiz** [comment]
For me, this format as currently committed (with BLAKE2b on device) passes self-test even on Tahiti with Catalyst. It's weird it apparently fails with new NVIDIA drivers.

**Comment by solardiz** [comment]
Works with `Driver Version: 418.87.00    CUDA Version: 10.1`:

```
$ ./john -te -form=tezos-opencl
Device 1: Tesla V100-SXM2-16GB
Benchmarking: tezos-opencl, Tezos Key [PBKDF2-SHA512 OpenCL]... LWS=256 GWS=20480 (80 blocks) DONE
Raw:	519641 c/s real, 5802K c/s virtual
```

FWIW, the old speeds were (prior to this month's many changes):

```
$ john -te -form=tezos-opencl
Will run 8 OpenMP threads
Device 1: Tesla V100-SXM2-16GB
Benchmarking: tezos-opencl, Tezos Key [PBKDF2-SHA512 OpenCL]... (8xOMP) LWS=256 GWS=327680 (1280 blocks) DONE
Speed for cost 1 (iteration count) of 2048
Raw:	141852 c/s real, 23557 c/s virtual
```

(was bumping into the 8 vCPUs that go along with one V100 on AWS).

Fails with `Driver Version: 450.119.01   CUDA Version: 11.0`:

```
$ ../run/john -test -form=tezos-opencl
Device 1: Tesla V100-SXM2-16GB
Benchmarking: tezos-opencl, Tezos Key [PBKDF2-SHA512 OpenCL]... FAILED (cmp_all(1))
```

**Comment by solardiz** [comment]
Confirmed that "Reverting to f683f0f fixes it."

```
Will run 8 OpenMP threads
Device 1: Tesla V100-SXM2-16GB
Benchmarking: tezos-opencl, Tezos Key [PBKDF2-SHA512 OpenCL]... (8xOMP) LWS=256 GWS=20480 (80 blocks) DONE
Raw:	504433 c/s real, 769924 c/s virtual
```

**Comment by solardiz** [comment]
New code with `-skip-self-test` is just as fast as it is with the older driver (where it works right):

```
$ ../run/john -test -form=tezos-opencl -skip-self-test
Device 1: Tesla V100-SXM2-16GB
Benchmarking: tezos-opencl, Tezos Key [PBKDF2-SHA512 OpenCL]... LWS=256 GWS=20480 (80 blocks) DONE
Raw:	519641 c/s real, 5802K c/s virtual
```

So this last change does provide some speedup - from 504k to 519k.

**Comment by solardiz** [comment]
This fixes it (same 519k speed, smaller kernel binary):

```diff
+++ b/run/opencl/blake2_mjosref/blake2b.c
@@ -130,6 +130,7 @@ void blake2b_update(blake2b_ctx *ctx,
     size_t i;
 
     for (i = 0; i < inlen; i++) {
+#if 0
         if (ctx->c == 128) {            // buffer full ?
             ctx->t[0] += ctx->c;        // add counters
             if (ctx->t[0] < ctx->c)     // carry overflow ?
@@ -137,6 +138,7 @@ void blake2b_update(blake2b_ctx *ctx,
             blake2b_compress(ctx, 0);   // compress (not last)
             ctx->c = 0;                 // counter to zero
         }
+#endif
         ctx->b[ctx->c++] = ((const uint8_t *) in)[i];
     }
 }
```

Indeed, the buffer is never supposed to become full on update - we're processing a tiny input, so it's only to be hashed on final. We can probably even call the compress function from the kernel directly.

**Comment by solardiz** [comment]
Actually, a clean workaround is as simple as this:

```diff
diff --git a/run/opencl/blake2_mjosref/blake2b.c b/run/opencl/blake2_mjosref/blake2b.c
index f74ddf88a..c9687dbe8 100644
--- a/run/opencl/blake2_mjosref/blake2b.c
+++ b/run/opencl/blake2_mjosref/blake2b.c
@@ -130,6 +130,7 @@ void blake2b_update(blake2b_ctx *ctx,
     size_t i;
 
     for (i = 0; i < inlen; i++) {
+#ifndef B2B_ONE_BLOCK_ONLY
         if (ctx->c == 128) {            // buffer full ?
             ctx->t[0] += ctx->c;        // add counters
             if (ctx->t[0] < ctx->c)     // carry overflow ?
@@ -137,6 +138,7 @@ void blake2b_update(blake2b_ctx *ctx,
             blake2b_compress(ctx, 0);   // compress (not last)
             ctx->c = 0;                 // counter to zero
         }
+#endif
         ctx->b[ctx->c++] = ((const uint8_t *) in)[i];
     }
 }
diff --git a/run/opencl/tezos_kernel.cl b/run/opencl/tezos_kernel.cl
index 4ca78be1e..cc7c556d4 100644
--- a/run/opencl/tezos_kernel.cl
+++ b/run/opencl/tezos_kernel.cl
@@ -192,6 +192,7 @@ __kernel void pbkdf2_sha512_tezos_init(__global const pass_t *inbuffer,
 
 #include "ed25519-donna/ed25519-donna.c"
 #define ROTR64 ror64 /* Reuse our SHA-512's optimized macro */
+#define B2B_ONE_BLOCK_ONLY
 #include "blake2_mjosref/blake2b.c"
 
 __kernel void pbkdf2_sha512_tezos_final(__global const crack_t *in, __global tezos_pkh_t *out)
```

Good thing it's also a (minor) optimization.

**Comment by solardiz** [comment]
With this fix, all 87 formats in this `--without-openssl` build passed tests on the V100 with this new driver (although I used low LWS/GWS to have this complete quicker).

**Comment by magnumripper** [comment]
Confirmed it works here too. And speedup was ~4%

**Comment by solardiz** [comment]
Thanks, @magnumripper. BTW, what speeds are you getting in absolute terms?

**Comment by solardiz** [comment]
Bad news: while this change is an optimization at source code level and makes the kernel binary smaller (approx. from 3000 to 2800 KB), it appears to slow things down with the old driver at least on GTX 1080 (approx. from 175k to 170k). Somehow the register usage by the final kernel increases a little bit, from 168 to 170. I don't know if that increase is notable, but FWIW 170 is very close to 512/3.

Adding a further tiny optimization like this to inside of `blake2b_final` doesn't help (but we may do it anyway).

```c
void blake2b_final(blake2b_ctx *ctx, void *out)
{
    size_t i;

    ctx->t[0] += ctx->c;                // mark last block offset
#ifndef B2B_ONE_BLOCK_ONLY
    if (ctx->t[0] < ctx->c)             // carry overflow
        ctx->t[1]++;                    // high word
#endif
```

**Comment by solardiz** [comment]
The speed is regained by adding `#pragma unroll 1` here:

```c
#pragma unroll 1
    for (i = keylen; i < 128; i++)      // zero input block
        ctx->b[i] = 0;
    if (keylen > 0) {
        blake2b_update(ctx, key, keylen);
        ctx->c = 128;                   // at the end
    }
```

Register usage drops to 168, too.

The weird thing is that the entire piece above is actually unneeded - it only matters for `keylen > 0` (and that `for` loop could as well have been inside the `if`). However, removing the above piece doesn't result in the improvement that the `#pragma unroll 1` provides. Well, maybe having this buffer pre-zeroed helps optimize further writes to it somehow... or maybe it's just random effect on register allocation by a particular compiler version.

**Comment by solardiz** [comment]
BTW, I suppose it could make sense to split the final kernel into two, so that blake2b's surprisingly higher register usage doesn't impact ed25519's LWS, and so that they don't compete for instruction cache concurrently. But the above workaround works fine for now.

**Comment by solardiz** [comment]
@magnumripper I've just force-pushed with the above workaround, so can you please retest on your system? I hope fixing the performance here doesn't break things there again.

**Comment by magnumripper** [comment]
> Thanks, @magnumripper. BTW, what speeds are you getting in absolute terms?

I re-ran now with consistent GWS (autotune picks the one below it more often than not) and best speed of five runs:
At f683f0f: 490798 c/s (two times of five).
First patch: 501852 c/s (three times of five).

So 2.3% boost. Last two patches seem to make little difference (if any) but I didn't look at register usage.

**Comment by magnumripper** [comment]
Oh, and I now fetched your PR and diffed against it - the last code I tested was identical bar the comment after unroll

**Comment by magnumripper** [comment]
> I re-ran now with consistent GWS (autotune picks the one below it more often than not) and best speed of five runs: At [f683f0f](https://github.com/openwall/john/commit/f683f0f2e02db8c39d117bc4d1236522a8372d22): 490798 c/s (two times of five). First patch: 501852 c/s (three times of five).

BTW the speed at f683f0f was just 459833 c/s if running on a single CPU, best of five. Comparing *that* to current speed of 506414 c/s (after #4976), the gain is over 10%.

**Comment by solardiz** [comment]
@Promethus029 Can you please confirm that this issue is fixed for you? (It is in our testing.)
