### ISSUE TITLE
Bug? [Nvidia 1070] format=NT-opencl fails to crack password within wordlist but format=NT does.

### ISSUE THREAD

**Issue by Promethus029** [openwall/john#4964]
Hi, this is my first time posting, so I apologize if something is incorrect. Bleeding-jumbo john was build about two hours ago with Regex enabled. Attempting to run '/opt/john/run/john --pot=john.pot --wordlist=rockyou-modified.txt --format=NT-opencl passwords.txt' does not yield Dark's password but finds the empty admin password.
![NT-opencl](https://user-images.githubusercontent.com/23091547/147169064-ca39fb6b-45b7-47ba-bc83-54c61a3268bb.png)
Re-running the command only adds the password at the edge of the GPU temp.
![NT-result-edit](https://user-images.githubusercontent.com/23091547/147169199-7e73a9c9-1827-4dfd-805a-ec1761771990.png)
However, running the command without opencl gives Dark's password.
![NT](https://user-images.githubusercontent.com/23091547/147167677-8569716e-7e80-48b9-8012-cf88028546e5.png)

Looking at console I see that the CPU is using MD4 128/128 XOP 4x2 while GPU is using MD4 opencl. Which it should?

I've been on the fence about posting because i don't know if this is an actual bug or I'm just using john incorrectly and this report shouldn't be here. Thank you for your time.

(john -test=0 reports all passed except for that tezos-opencl, which you know about.)

'john --show --format=NT-opencl' ->[checking-passwords.txt](https://github.com/openwall/john/files/7765793/checking-passwords.txt)
[john_build_info.txt](https://github.com/openwall/john/files/7765794/john_build_info.txt)
[lscpu-info.txt](https://github.com/openwall/john/files/7765795/lscpu-info.txt)
Nvidia Card -[opencl-devices-info.txt](https://github.com/openwall/john/files/7765796/opencl-devices-info.txt)
Hashes - [passwords.txt](https://github.com/openwall/john/files/7765797/passwords.txt)
file to crack hash - [rockyou-modified.txt](https://github.com/openwall/john/files/7765798/rockyou-modified.txt)

**Comment by solardiz** [comment]
@Promethus029 Thank you for reporting. This does look like a bug - apparently, the correct password was detected by on-device comparison (which is how it'd get exactly to the beginning of the returned "range"), but not fully seen that way by host.

> except for that tezos-opencl, which you know about

Actually, no - the only report so far was @magnumripper's for a very particular card and driver version. In my testing, all formats pass tests on NVIDIA, including tezos-opencl. So thank you for letting us know this wasn't such an isolated occurrence of the issue.

**Comment by solardiz** [comment]
For further occasions, instead of screenshots please use textual copy-paste and wrap it in triple backticks like this:

```
your copy-paste here
```

> apparently, the correct password was detected by on-device comparison (which is how it'd get exactly to the beginning of the returned "range")

No, that was because it was the only one in your wordlist file.

**Comment by ghost** [comment]
A better example (after adding an empty line to the wordlist):
```
@well:~/bleeding/src$ rm *.pot; ../run/john --pot=john.pot --wordlist=/home/claudio/rockyou-modified.txt --format=NT ~/passwords.txt
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (NT [MD4 256/256 AVX2 8x3])
Warning: no OpenMP support for this hash type, consider --fork=8
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 2 candidates left, minimum 24 needed for performance.
Password01!      (Dark)     
                 (Administrator)     
2g 0:00:00:00 DONE (2021-12-23 03:49) 12.50g/s 12.50p/s 12.50c/s 25.00C/s Password01!
Warning: passwords printed above might not be all those cracked
Use the "--show --format=NT" options to display all of the cracked passwords reliably
Session completed. 
```
```
@well:~/bleeding/src$ rm *.pot; ../run/john --pot=john.pot --wordlist=/home/claudio/rockyou-modified.txt --format=NT-opencl ~/passwords.txt
Device 4: Tahiti [AMD Radeon HD 7900 Series]
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (NT-opencl [MD4 OpenCL])
Note: This format may be a lot faster with --mask acceleration (see doc/MASK).
LWS=64 GWS=2048 (32 blocks) 
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 2 candidates left, minimum 2048 needed for performance.
                 (Administrator)     
1g 0:00:00:01 DONE (2021-12-23 03:51) 0.6535g/s 1.307p/s 1.307c/s 2.614C/s 
Warning: passwords printed above might not be all those cracked
Use the "--show --format=NT-opencl" options to display all of the cracked passwords reliably
Session completed. 
```

It must be a bug, I see no other explanation.

**Comment by solardiz** [comment]
Yes, I'm also able to reproduce both aspects of the bug: Dark's password not getting cracked, and Administrator's _sometimes_ (on 1 of 3 GPUs I tried) getting cracked even without empty line in the wordlist. Perhaps uninitialized memory is used somewhere.

**Comment by Promethus029** [comment]
The problem is consistent with the originial rockyou.txt file. I uploaded and tested with 'rockyou-modified.txt' due to the size restrictions.on github. (file is like 139MB)

**Comment by solardiz** [comment]
Yes, I also already confirmed it with the full RockYou file.

**Comment by ghost** [comment]
> The problem is consistent with the originial rockyou.txt file. I uploaded and tested with 'rockyou-modified.txt' due to the size restrictions.on github. (file is like 139MB)

In fact, this is a perfect test case. Thank you.

**Comment by solardiz** [comment]
@claudioandre-br Since this is reproducible on NVIDIA, no need to bother the fragile AMD GPUs with that, please. You can use one of the NVIDIA GPUs on "super" if you like to play with this. (Yes, all of them are currently in use, but that's safer with NVIDIA.)

**Comment by ghost** [comment]
Testing is done. 

BTW: if `bull` is still alive, it could be useful now that you are using JtR.

**Comment by solardiz** [comment]
Things start working as soon as any non-trivial mask is used:

```
[solar@super run]$ rm john.pot; LWS=64 GWS=2560 ./john -se=tmp -no-log nt-bug/passwords.txt -form=nt-opencl -dev=4 -mask='Password01!'
Device 4: GeForce GTX 1080
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (NT-opencl [MD4 OpenCL])
LWS=64 GWS=2560 (40 blocks) 
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 1 candidate left, minimum 2560 needed for performance.
                 (Administrator)     
1g 0:00:00:00  9.090g/s 9.090p/s 9.090c/s 18.18C/s Dev#4:93C 
Warning: passwords printed above might not be all those cracked
Use the "--show --format=NT-opencl" options to display all of the cracked passwords reliably
Session completed. 
[solar@super run]$ rm john.pot; LWS=64 GWS=2560 ./john -se=tmp -no-log nt-bug/passwords.txt -form=nt-opencl -dev=4 -mask='Passwor[cd]01!'
Device 4: GeForce GTX 1080
Using default input encoding: UTF-8
Loaded 2 password hashes with no different salts (NT-opencl [MD4 OpenCL])
LWS=64 GWS=2560 (40 blocks) x2 
Press 'q' or Ctrl-C to abort, almost any other key for status
Warning: Only 1 base candidate left, minimum 2560 needed for performance.
Password01!      (Dark)     
1g 0:00:00:00  7.692g/s 15.38p/s 15.38c/s 30.76C/s Dev#4:93C Password01!
Warning: passwords printed above might not be all those cracked
Use the "--show --format=NT-opencl" options to display all of the cracked passwords reliably
Session completed. 
```

> BTW: if `bull` is still alive, it could be useful now that you are using JtR.

It's unfortunately physically disconnected - I will probably ask someone to reconnect it soon.

**Comment by solardiz** [comment]
Here are the results for 4 old builds, by date:

20190331 cracks only Dark (as it should)

20190409 cracks Dark and Administrator (slightly wrong, but not necessarily a bug - clearly a GPU can't test just one password, so it processing some empty passwords and detecting a guess makes sense)

20190922 is the same as above

20200228 cracks only Administrator, but not Dark (this bug)

All of these are with:

```
rm john.pot; LWS=64 GWS=2560 ./john passwords.txt -form=nt-opencl -dev=4 -mask='Password01!'
```

Indeed, it's embarrassing we have a bug like that unnoticed for ~2 years. OTOH, it's understandable why it wouldn't surface in reasonable usage - mask acceleration is mandatory for decent speeds anyway, and a simple wordlist run (without a mask added on top of it) is better done on CPU. So hopefully people have been using `nt-opencl` only with real masks (possibly along with other modes, like in the examples we give in `doc/MASK`).

**Comment by solardiz** [comment]
> 20190922 is the same as above

Either this changed or I didn't look closely - it doesn't crack Dark now. An older build, 20190619, does.

What changed between 20190619 and 20190922, as seen when running with `-v=5`, is that previously the kernel was first built for the test db's hash count and then rebuilt for the actual loaded hash count, and this rebuild step disappeared between these versions. Perhaps a kernel built for a different hash count (43 instead of 2 in this case) is not supposed to work right since Sayantan's building of the perfect hash tables could very well depend on the exact count.

Indeed, adding `-skip-self-test` gets Dark cracked with the current code, as then the one kernel build is for the right hash count (no build for test db).

**Comment by solardiz** [comment]
I think we broke this with bd7b8267764bfda5bce9df40cf1a6dfcf89e0329 when fixing #4012. Probably also other formats by Sayantan.

**Comment by solardiz** [comment]
Here's a fix (works for me):

```diff
+++ b/src/opencl_nt_fmt_plug.c
@@ -556,7 +556,7 @@ static void reset(struct db_main *db)
 {
        static int last_int_cand;
 
-       if (!crypt_kernel || last_int_cand != mask_int_cand.num_int_cand) {
+       if (!crypt_kernel || last_int_cand != mask_int_cand.num_int_cand || num_loaded_hashes != db->salts->count) {
                release_base_clobj();
                release_clobj();
 
```

However, I wonder whether we should possibly prefer checking the `db` pointer instead, or maybe even doing those things unconditionally - why not, `reset()` isn't supposed to be called often.

The way I wrote it above, we'd have a special case when the number of loaded hashes happens to be exactly the same as the number in the test db (currently 43). I think that's actually an optimization, but I dislike having an extra special case that we'd need to test (or have untested functionality, which is bad).

Once we decide on how to fix this best, we need to do the same to other formats sharing this pattern and retest those.

**Comment by solardiz** [comment]
Looking at this problem differently, it's not good that we're testing one kernel build and then using another build (effectively untested). Maybe we should come up with a more elaborate fix that would make the self-test use a kernel built for the loaded hash count, somehow filling up to that count with test vectors. However, then we'd have the problem of having no place to fit all of the test vectors when the loaded hash count is small. Luckily, we only have this problem with Sayantan's formats that use his perfect hash tables.

**Comment by solardiz** [comment]
> doing those things unconditionally - why not, `reset()` isn't supposed to be called often.

Looks like e.g. `opencl_rawmd4_fmt_plug.c` just does those things `if (initialized)`, so I think it doesn't share this same bug. I don't see why we'd do it differently between NT and raw-MD4.

Kernels that use the perfect hash tables:

```
$ fgrep -l shift64_ot_sz opencl_*.c
opencl_krb5pa-md5_fmt_plug.c
opencl_mscash_fmt_plug.c
opencl_mysqlsha1_fmt_plug.c
opencl_nt_fmt_plug.c
opencl_ntlmv2_fmt_plug.c
opencl_rawmd4_fmt_plug.c
opencl_rawmd5_fmt_plug.c
opencl_rawsha1_fmt_plug.c
opencl_salted_sha_fmt_plug.c
opencl_sl3_fmt_plug.c
```

However, some of them appear to be passing the hash table size/offset at runtime rather than kernel compile time. These pass that info at compile time:

```
$ fgrep -l SHIFT64_OT_SZ opencl_*.c
opencl_mysqlsha1_fmt_plug.c
opencl_nt_fmt_plug.c
opencl_rawmd4_fmt_plug.c
opencl_rawmd5_fmt_plug.c
opencl_rawsha1_fmt_plug.c
opencl_salted_sha_fmt_plug.c
opencl_sl3_fmt_plug.c
```

Out of them, only `opencl_nt_fmt_plug.c` appears to be affected by this bug - the rest use the simple `if (initialized)` logic. Wow.

**Comment by solardiz** [comment]
Actually, the `if (initialized)` logic in those formats is also weird - the `else` branch does much of the same thing. So why not just do these things unconditionally, like they were done before?

```diff
+++ b/src/opencl_nt_fmt_plug.c
@@ -554,21 +554,14 @@ static int crypt_all(int *pcount, struct db_salt *salt)
 
 static void reset(struct db_main *db)
 {
-       static int last_int_cand;
-
-       if (!crypt_kernel || last_int_cand != mask_int_cand.num_int_cand) {
-               release_base_clobj();
-               release_clobj();
-
-               num_loaded_hashes = db->salts->count;
-               ocl_hc_128_prepare_table(db->salts);
-               init_kernel(num_loaded_hashes,
-                           ocl_hc_128_select_bitmap(num_loaded_hashes));
+       release_base_clobj();
+       release_clobj();
 
-               create_base_clobj();
+       num_loaded_hashes = db->salts->count;
+       ocl_hc_128_prepare_table(db->salts);
+       init_kernel(num_loaded_hashes, ocl_hc_128_select_bitmap(num_loaded_hashes));
 
-               last_int_cand = mask_int_cand.num_int_cand;
-       }
+       create_base_clobj();
 
        size_t gws_limit = MIN((0xf << 21) * 4 / BUFSIZE,
                               get_max_mem_alloc_size(gpu_id) / BUFSIZE);
```

This passes my test.

**Comment by solardiz** [comment]
@Promethus029 Can you please confirm that this issue is fixed for you? (It is in our testing.)

**Comment by Promethus029** [comment]
@solardiz I can reliably get Dark's password using nt-opencl. Thanks :)
