### ISSUE TITLE
nt-opencl reports wrong password instead of implicitly cracked empty password

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4965]
While working on #4964, I noticed that this command:

```
rm john.pot; LWS=64 GWS=2560 ./john -w=rockyou.txt passwords.txt -form=nt-opencl -dev=4 -mask='?w!' -v=5
```

correctly cracks Dark's password as `Password01!`, but also incorrectly cracks Administrator's empty password as:

```
$ tail -1 john.pot | od -tx1
0000000 24 4e 54 24 33 31 64 36 63 66 65 30 64 31 36 61
0000020 65 39 33 31 62 37 33 63 35 39 64 37 65 30 63 30
0000040 38 39 63 30 3a fa 74 76 61 72 70 21 0a
```

That is, the byte value 0xfa followed by the string `tvarp!`.

This is reproducible, including on a build from 20190619 that wasn't yet affected by #4964, as well as with our current code with that bug fixed.

The exact same issue (including the same wrong password) is seen when retesting on a different GPU and with auto-tuning enabled.

With the CPU format (`--format=nt`), this issue does not occur (Administrator's password is not cracked by the equivalent command).

My guess is that with the OpenCL format the password gets cracked for real, because it's empty and an under-full buffer just happened to have that, however in that case some stale candidate password (from a previous fill of the buffer?) gets reported. That wouldn't explain why the exact same wrong password is reported for different GWS figures, though. So that guess is at least incomplete, or wrong.

**Comment by solardiz** [comment]
BTW, the source lines in `rockyou.txt` for these passwords are 60804 and 2459760. Quite far from each other - not in the same batch, and also not in the last batch.

This issue also occurs when targeting only `-u=Administrator`, so it's unrelated to the other crack.

Further, the exact same wrong password is reported for `Administrator` on a randomly shuffled wordlist, where that is line 10154231.

So there's something special about this one password and hash combination. Maybe it's a partial collision that we should reject later, but somehow fail to.

**Comment by solardiz** [comment]
Ran more tests on a larger hash list (a 1M total representative sample from HIBPv7, 820683 unique - and only the unique are preserved by the loader). Simply running a large wordlist cracks the same 713398 with both CPU and OpenCL (`sort -u | md5sum` matches). However, running with `-mask=?w!` results in differences. CPU cracks 3713, OpenCL cracks 3729. Reviewing those differences, there are two kinds:

1. CPU format truncates at 27, so cracks some passwords that are exactly length 27 and do not actually end in `!`. OpenCL also cracks them, but wrongly logs them with the `!` still in there (as length 28). Shouldn't both have rejected those candidates, though, since the truncation wouldn't occur on target systems?
2. OpenCL cracked many passwords with different 8-bit characters in them, which the CPU format did not recognize as valid for those hashes.

That was without any encoding specification. With `-encoding=cp1252`, surprisingly both issues are gone, and CPU and OpenCL crack exactly the same 3709 passwords (`sort -u | md5sum` matches).

So the issue here looks related to encodings support, yet somehow manifests itself differently and worse with OpenCL?

**Comment by solardiz** [comment]
Similarly, the issue from my original comment here is gone with either `-encoding=cp1252` or `-encoding=cp1251` (tried just these two for 8-bit encodings), but is present with `-encoding=utf8`. So something in our multi-byte encodings support?

@magnumripper I think this is now yours, and I assume you'll update the issue title as we learn more. Thanks!

**Comment by magnumripper** [comment]
> 1. CPU format truncates at 27, so cracks some passwords that are exactly length 27 and do not actually end in `!`. OpenCL also cracks them, but wrongly logs them with the `!` still in there (as length 28). Shouldn't both have rejected those candidates, though, since the truncation wouldn't occur on target systems?

Both should have rejected the words in parent wordlist code: Wordlist mode is supposed to run with a max. length of 26, knowing that the hybrid mask will add 1.

**Comment by magnumripper** [comment]
No wait, this is tricky with UTF-16 formats being fed with UTF-8... The max. length is actually 27 *characters* so Wordlist will cap at 26*3 == 78 bytes (actually checking UTF-8 length would obviously be trivial but far too expensive). That explains how we get the ones lacking an ending `!`. The OpenCL format must be fixed though, not add the `!` to those in get_key().

**Comment by magnumripper** [comment]
> Shouldn't both have rejected those candidates, though, since the truncation wouldn't occur on target systems?

Why? I think the CPU format does it perfectly right (assuming the reported password are indeed correct for those hashes). It's kinda odd that we crack some passwords not matching the hybrid mask we give, but it's not quite a bug - just an effect of that quick-cap in wordlist mode when using UTF-8.

**Comment by solardiz** [comment]
> > Shouldn't both have rejected those candidates, though, since the truncation wouldn't occur on target systems?
> 
> Why?

The behavior we're seeing here would correspond to having the `FMT_TRUNC` flag set, but it is correctly not set for the NT format. My understanding is that in jumbo we want to have formats where the truncation is part of our code and not part of the target systems' behavior to skip candidates that would be truncated, instead of testing them truncated. You effectively confirm the same by saying that wordlist's max would be lowered for the mask to fit. This is just tricky/expensive to implement for this format.

**Comment by magnumripper** [comment]
Oh, right, I just misinterpreted what you said. The *format* never rejects any candidates but the modes should, so the formats should obviously behave the same. In this case the internal mask adds another level of complexity.

So we have two separate problems identified: The second one is easy: NT-opencl's `get_key()` should not append a mask past max. length. The first and original issue is harder to picture, but it might be some kind of worse effect of the same bug. I'm looking forward to delve into this but have little time now for a couple of days 🙄

**Comment by magnumripper** [comment]
> In this case the internal mask adds another level of complexity.

That's actually not the case... internal mask is not used for `?w!`, the mask stuff is all CPU-side. I was never sure of this until now.
