### ISSUE TITLE
OpenCL crack_count_ret race condition

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4975]
The two OpenCL formats that use `crack_count_ret` are `ZIP-opencl` and `cryptosafe-opencl`. Both set `*crack_count_ret = 0;` when `get_global_id(0)` is 0. Both do it from the same OpenCL kernel that can also update that variable with `atomic_inc` or `atomic_max`.

We assume `get_global_id(0)` of 0 will be tried before all others, or at least no later than others. I think in practice it's typically part of the first batch along with many others, so when the first `atomic_*` update is possibly reached the `*crack_count_ret = 0;` would have already been issued.

However, there are issues with that:

1. I doubt the assumption above is guaranteed by OpenCL spec, or is it?

2. While the updates are atomic and are such that it doesn't matter which of them occurs first (if there's more than one), I don't know if the write of 0 is guaranteed to be atomic by the OpenCL spec - but maybe it is.

3. Even if the write is atomic and is issued before the first `atomic_*` is reached, that doesn't imply it completes before the `atomic_*`. Atomicity of operations isn't the same as guaranteeing their order of completion, even if they're issued in the desired order.

To get around these issues, maybe we should perform the zeroing on host or in a prior kernel invocation, not in the same kernel invocation that updates the variable.

Alternatively, maybe we don't need to zero this variable at all (except initially, to avoid using it uninitialized). We can accept it as ever-growing across multiple `crypt_all` calls, and on host use the difference between its current and previous value. Since it's unsigned, we can let it wrap and the difference would still be correct.

Edit: I think inserting a global memory write and read barrier(s) after the `*crack_count_ret = 0;` would address issues 2 and 3, but not issue 1. So if it is not guaranteed that `get_global_id(0)` of 0 is always part of the first batch, then it's not a sufficient fix.

**Comment by ghost** [comment]
> 1. I doubt the assumption above is guaranteed by OpenCL spec, or is it?

I'm almost sure the assumption is NOT guaranteed. In fact, concurrency and item 3 make this bet quite dangerous, by design (think about OpenCL CUs doing their job).

> we should perform the zeroing on host or in a prior kernel invocation

I'm using this approach (one prior kernel invocation) on 'my' fast formats.

**Comment by solardiz** [comment]
> we should perform the zeroing on host

That's what I'm testing in my pending update of `tezos-opencl` now. Works well so far.

**Comment by magnumripper** [comment]
Sounds sensible to me. Good thing we get it all straight before starting to use it as boilerplate code as I called it somewhere.

**Comment by magnumripper** [comment]
Just looked at Sayantan's formats. He does it when creating that buffer, and then right after reading a non-zero return from it (after using it to read the full output). That's a good way to not introduce any overhead.

In NT-opencl it's called `buffer_hash_ids` and `hash_ids` on host side and `output` in the compare kernels.

Oh, and he does this (just as discussed in #4958)
```c
	if (hash_ids[0] > num_loaded_hashes) {
		fprintf(stderr, "Error, crypt_all kernel.\n");
		error();
	}
```
