### ISSUE TITLE
--fuzz --format=luks consumes too much memory

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4979]
The process gets OOM-killed on Linux. This could be a memory leak or an input-dependent memory allocation with no limit.

**Comment by solardiz** [comment]
Looks like we won't care to get this fixed any time soon, if there's anything to fix here at all. Closing.

On a related note, I am far more concerned about possible integer overflows resulting in incorrect allocation size, than in memory consumption per se.

**Comment by AlekseyCherepanov** [comment]
I got similar problem with `KeePass` and `KeePass-opencl` formats after 3 hours with `--fuzz=run/fuzz.dic`.

**Comment by solardiz** [comment]
Turns out that fuzzing this format makes the loader stuck in `ldr_sort_salts`, eating memory until OOM.

```
2152            for (i = 0; i < mysalt->dyna_salt.salt_cmp_size; ++i) {
(gdb) bt
#0  0x00000000008ad7ec in fmt_default_dyna_salt_hash (salt=Unhandled dwarf expression opcode 0xf3
) at formats.c:2152
#1  0x00000000008c22cc in ldr_sort_salts (db=0x2766240, by_count=Unhandled dwarf expression opcode 0xf3
) at loader.c:1522
#2  0x00000000008cacef in ldr_fix_database (db=0x2766240) at loader.c:2069
#3  0x0000000000c0a3e8 in fuzz_test (db=0x2766240, format=0x1323540) at fuzz.c:742
#4  0x0000000000c0a7f3 in fuzz (db=Unhandled dwarf expression opcode 0xf3
) at fuzz.c:838
#5  0x00000000008bafcf in john_run (argc=Unhandled dwarf expression opcode 0xf3
) at john.c:1683
```

**Comment by solardiz** [comment]
> Turns out that fuzzing this format makes the loader stuck in `ldr_sort_salts`, eating memory until OOM.

No, I was wrong. That call to `ldr_fix_database` (and thus to `ldr_sort_salts`) was added in 8201f174810e2c0cbda288d231a40f683d18f6de in June 2022, so it couldn't have been the original issue here. What really happens is that the fuzzing loop ends up allocating a lot of memory (for the dynamic salts?), and if/when that loop ends (if it didn't run out of memory first), then `ldr_fix_database` is reached and consumes even more memory. Nevertheless, all of this can complete just fine given enough RAM for the number of test passwords. Specifically, with a limit of 1 million introduced here:

```c
        while (!event_abort && index < 1000000) {
                ret = get_next_fuzz_case(format->params.label, current->ciphertext);
                save_index(index++);
                line = fuzz_hash;
                ldr_load_pw_line(db, line);

                if (!ret) {
                        if (!(++current)->ciphertext)
                                break;
                }
        }
        if (fclose(s_file)) pexit("fclose");
        remove(status_file_path);
        fmt_done(format);
        ldr_fix_database(db);
        ldr_free_db(db, 0);
        if (!event_abort)
                printf("   Completed\n");
```

this completes just fine in half an hour on our 128 GB machine, but it does use almost all of this RAM at peak. The same fails when fuzzing of this format is reached after many other formats had been fuzzed by the same process (so on top of memory leaks incurred in those).

The main memory leak is probably the `psalt` allocation in `get_salt`:

```c
        psalt = (struct custom_salt_LUKS*)mem_alloc_tiny(sizeof(struct custom_salt_LUKS)+size, 4);
        memcpy(psalt, &cs, sizeof(cs));
        memcpy(psalt->cipherbuf, buf, size);
        MEM_FREE(buf);
        psalt->dsalt.salt_alloc_needs_free = 0;

        // set the JtR core linkage stuff for this dyna_salt
        psalt->dsalt.salt_cmp_offset = SALT_CMP_OFF(struct custom_salt_LUKS, myphdr);
        psalt->dsalt.salt_cmp_size = SALT_CMP_SIZE(struct custom_salt_LUKS, myphdr, cipherbuf, size);

        memcpy(ptr, &psalt, sizeof(struct custom_salt*));
        return (void*)ptr;
```

I guess this will remain a WONTFIX.
