### ISSUE TITLE
--wordlist=fifo misses cracks with --fork

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#5000]
#4921 introduced ability to use a fifo as argument for `--wordlist=`. `--stdin`/`--pipe` did not allow use of `--fork`. `--wordlist=` allows `--fork=`. But with a fifo, fork works badly.

Setup:
```
main$ mkfifo fifo

main$ seq 100 | sed -e 's/^/$0$/' > t.pw
```

Test without `--fork`: there should be 100 cracks.
```
main$ ./run/john --wordlist=fifo t.pw --pot=t.pot

other$ seq 100 > fifo
```

Test with `--fork`:
```
main$ rm t.pot

main$ ./run/john --wordlist=fifo t.pw --pot=t.pot --fork=2

other$ seq 100 > fifo
```

There are 50 cracks only instead of 100. All cracks are either odd or even numbers. So I guess one process consumes the whole input and skips half of candidates expecting other process to try them.

**Comment by magnumripper** [comment]
I wonder if this is a problem inherent of fifos rather than much anything else. Perhaps we should just disable it for forked runs

**Comment by solardiz** [comment]
Of course, we should disallow this combination. Perhaps right after setting `file_is_fifo`, check if we're running with `--fork` and print an error and `error();` out. @AlekseyCherepanov You want to send us a PR fixing this? Thanks!

**Comment by AlekseyCherepanov** [comment]
`--loopback` can use fifo as argument. But it opens the fifo twice.
```
$ ./run/john --loopback=fifo --log-stderr --rules=':' --stdout
Using default input encoding: UTF-8
[... waits; entered in other shell: echo :asdf > fifo ]
0:00:00:00 Command line: ./run/john --loopback=fifo --log-stderr --rules=: --stdout 
0:00:00:00 - UTF-8 input encoding enabled
0:00:00:00 - Passwords will be stored UTF-8 encoded in .pot file
0:00:00:00 Proceeding with loopback mode
Permutation rules: :
0:00:00:00 - Rules: :
[... waits; entered in other shell: echo :qwer > fifo ]
0:00:00:00 - Loopback pot FIFO: fifo
0:00:00:00 - No stacked rules
0:00:00:00 - 1 preprocessed word mangling rules
0:00:00:00 Enabling duplicate candidate password suppressor
Enabling duplicate candidate password suppressor
0:00:00:00 - Rule #1: '' accepted
qwer
1p 0:00:00:47 100.00% (2022-05-10 23:41) 0.02102p/s qwer
```

So it seems fifos should be prohibited for loopback.

**Comment by AlekseyCherepanov** [comment]
Both problems were fixed. I close the issue.
