### ISSUE TITLE
Grammar for dynamic function

### ISSUE THREAD

**Issue by rodrigozanatta** [openwall/john#5001]
I am having bad times trying to test a dynamic function.

- First I study[ this document](https://miloserdov.org/?p=5960) to show how to make this in the command line. 
- Then, I read the [john/doc/DYNAMIC_SCRIPTING](https://github.com/openwall/john/blob/bleeding-jumbo/doc/DYNAMIC_SCRIPTING) and see I can create a "script" in john.conf with my needs. 

But what I didn't found was:

- What is the grammar of the Expression? To be fair, this is not a big deal, the first documentation does a good job.
- Where was the list of all DynamicFunc_? Ok, I can find it in the code [john/src/dynamic_parser.c](https://github.com/openwall/john/blob/a19784d685ea6dde598d3519f641844df47bd211/src/dynamic_parser.c). Well, some are easy to understand, others not. 
- But the most important: How the HELL I write the hash password to input to decrypt?  **This really needs grammar and I can't find it**.

What I am trying to do is this function:

- sha512($s.$p.$s2)  
- sha512($u.$p.$s)

That means
$SALT + PASSWORD + $SALT_2
The first SALT can be the user, no problems with that. 

Now... How  i write the Test function or even the hash to input the program:
`user:hash$salt`
and (in john.conf)
`Test=$dynamic_1666$user:hash$salt:clean_pass`

But none works. How do I do it? Where can I read about it! How do I use two different salts??

**Comment by solardiz** [comment]
@rodrigozanatta You already [brought this up on john-users](https://www.openwall.com/lists/john-users/2022/01/17/1), which is a more appropriate place for it. Please be patient, and we or others in the community will help you in replies on john-users.

As to this GitHub issue, we can either close it now (as duplicate of the upcoming discussion on john-users), or we can reuse it as request for improving the documentation. I can see how the documentation is confusing, in part because it evolved along with the code.

**Comment by rodrigozanatta** [comment]
> @rodrigozanatta You already [brought this up on john-users](https://www.openwall.com/lists/john-users/2022/01/17/1), which is a more appropriate place for it. Please be patient, and we or others in the community will help you in replies on john-users.
> 
Really sorry about it. I thought that e-mail didn't work because my gmail don't show the reply :) And I really try to see all the messages from the email list but don't found...

I need to learn more how to use the mail list!

**Comment by rodrigozanatta** [comment]
And I can close this issue. So I will do the correct thing and wait there.

**Comment by magnumripper** [comment]
Here's a copy of the answer I sent to [john-users](https://www.openwall.com/lists/john-users/2022/01/17/2):

The easy way is to use the "dynamic ad-hoc" (or dynamic compiler) format  because you can use that literal formula you wrote above, like this:
```
$ ./john -test -format:'dynamic=sha512($u.$p.$s)'
Benchmarking: dynamic=sha512($u.$p.$s) [256/256 AVX2 4x]... DONE
Many salts:	5278K c/s real, 5278K c/s virtual
Only one salt:	4710K c/s real, 4710K c/s virtual
```
Please note that you need hyphens around the formula so your shell  doesn't act up with the dollar signs.

The input format is:
```
user:<hex hash>$<salt>
```
So here's a hash with username "JRLuser", salt "TheSalt" and a password  of "magnum":
```
echo > test.in 'JRLuser:23750433e3685f544c02884cd622570f3d73b359be7dc5d9d5e87c3e394fc53f16dfad34d02680f24d99036aba63014be1343fe60e5391d8366d7be7b432db17$TheSalt'
```
```
$ ./john -format:'dynamic=sha512($u.$p.$s)' test.in
Using default input encoding: UTF-8
Loaded 1 password hash (dynamic=sha512($u.$p.$s) [256/256 AVX2 4x])
Warning: no OpenMP support for this hash type, consider --fork=16
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:./password.lst
magnum           (JRLuser)
1g 0:00:00:00 DONE 2/3 (2022-01-17 21:39) 100.0g/s 2137Kp/s 2137Kc/s 
2137KC/s 123456..Geronimo
No remaining hashes
Use the "--show --format=dynamic=sha512($u.$p.$s)" options to display 
all of the cracked passwords reliably
Session completed.
```

In case you need/want to put the salt in hex, use HEX$ like this:
```
user:<hex hash>$HEX$<hex salt>
```

**Comment by magnumripper** [comment]
Now here's some bonus material: You can add `,debug` after the ad-hoc format, like this:
```
$ ./john -test -format:'dynamic=sha512($u.$p.$s)',debug
push
app_u
.
app_p
.
app_sh
f512h

crc32 = 24FA07FF
pExpr=sha512($u.$p.$s)
extraParams=,debug
signature=@dynamic=sha512($u.$p.$s)@
line0=@dynamic=sha512($u.$p.$s)@07c5d9bbae97717925cfe1e7390b245483f0a8a4582fb3cf52b4ccb7340e0a9f8d785657fff8cfa34dc0a146a3da795662b9107a2400be871ddc8d12504a1aae$719a288e$$U3d85c237
line1=@dynamic=sha512($u.$p.$s)@4de0221227bb11fca7f389d5304396582c44af2603a3188b8d441bfa24ddf37f5fca2b3cbdd21a63ad14403f8605a13f5c3ae7339f976f88fcba79b8390e0146$7184f1d5$$U85b68792
line2=@dynamic=sha512($u.$p.$s)@53de1f12e3c69383d11a166ffd884deb47654f2041454fb4e54427dd7a6e853dad6de7e9eabf515fc04c4452b59b9ef5a6a4e59adf735769742ce40d01bd5fae$83213d35$$Uf018d1cb
line3=@dynamic=sha512($u.$p.$s)@14e86f61f73e18ad92e9ecaa08f937d599a8e207a85dfe5738187058437bfeca8ca69e311070c86ea98b7fb492511184edac4f36229aab19ae6ba85cb4d72c0c$25914842$$Uc4a7aa58
line4=@dynamic=sha512($u.$p.$s)@8355f543ad9dd6a9a75dbc65113b5c6b2a85f749a854c7889d8d730f23a233c5d3e52497c22876f0c665ec3e496899bb5834fd04b2ede64638a99d824013cf33$951045a5$$Ubd967815
##############################################################
#  Dynamic script for expression sha512($u.$p.$s),debug
##############################################################
Expression=dynamic=sha512($u.$p.$s)
#  Flags for this format
Flag=MGF_FLAT_BUFFERS
Flag=MGF_SALTED
Flag=MGF_USERNAME
Flag=MGF_INPUT_64_BYTE
#  Lengths used in this format
SaltLen=-32
MaxInputLenX86=110
MaxInputLen=110
#  The functions in the script
Func=DynamicFunc__clean_input_kwik
Func=DynamicFunc__append_userid
Func=DynamicFunc__append_keys
Func=DynamicFunc__append_salt
Func=DynamicFunc__SHA512_crypt_input1_to_output1_FINAL
#  The test hashes that validate this script
Test=@dynamic=sha512($u.$p.$s)@07c5d9bbae97717925cfe1e7390b245483f0a8a4582fb3cf52b4ccb7340e0a9f8d785657fff8cfa34dc0a146a3da795662b9107a2400be871ddc8d12504a1aae$719a288e$$U3d85c237:abc
Test=@dynamic=sha512($u.$p.$s)@4de0221227bb11fca7f389d5304396582c44af2603a3188b8d441bfa24ddf37f5fca2b3cbdd21a63ad14403f8605a13f5c3ae7339f976f88fcba79b8390e0146$7184f1d5$$U85b68792:john
Test=@dynamic=sha512($u.$p.$s)@53de1f12e3c69383d11a166ffd884deb47654f2041454fb4e54427dd7a6e853dad6de7e9eabf515fc04c4452b59b9ef5a6a4e59adf735769742ce40d01bd5fae$83213d35$$Uf018d1cb:passweird
Test=@dynamic=sha512($u.$p.$s)@14e86f61f73e18ad92e9ecaa08f937d599a8e207a85dfe5738187058437bfeca8ca69e311070c86ea98b7fb492511184edac4f36229aab19ae6ba85cb4d72c0c$25914842$$Uc4a7aa58:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEF
Test=@dynamic=sha512($u.$p.$s)@8355f543ad9dd6a9a75dbc65113b5c6b2a85f749a854c7889d8d730f23a233c5d3e52497c22876f0c665ec3e496899bb5834fd04b2ede64638a99d824013cf33$951045a5$$Ubd967815:
```
Et voila, that's a script right there which you can sometimes optimize manually and put in `john.conf` (leave out everything above the first `########` line). Also, test vectors are shown but in this case the username is encoded as `$U<username>` (which is the format used in the .pot file).
