### ISSUE TITLE
New default wordlist

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5002]
I think we need to extend or replace the default `password.lst`. I've prepared a generated common password list based on HIBP v8 and RockYou - can describe the criteria and algorithm and simulated cracking with it vs. alternatives. The criteria are such that a password used by just one person many times is very unlikely to be included (I use the numbers of occurrences in HIBP and RockYou such that the password has to come from more than one set). The list is currently 1.8M lines, 15 MB. Sounds acceptable, given we have `.chr` files approaching this size (and larger than that combined)?

**Comment by solardiz** [comment]
A related question is whether we should have the list sorted for decreasing frequency (like we have it now) or sort it alphabetically or maybe have the initial portion (corresponding to the current tiny `password.lst`?) sorted by frequency and the rest alphabetically. A reason to sort alphabetically is it results in fewer dupes (produced by rules) getting through our poor man's check against the previous candidate. The total number of candidates to test (including dupes that got through) reduces by about 0.5% with alphabetic sorting.

#4728 would likely remove the alphabetic sorting advantage. If we don't want our `.git` to grow too large, maybe we should commit only the frequency sorted wordlist right away.

**Comment by solardiz** [comment]
Starting to record the methodology in here, before I forget:

```shell
sed -n '/:99^M/ q; p' < pwned-passwords-ntlm-ordered-by-count-v8.txt | cut -f1 -d: > pp8-100p # pressed ^V ^M
./pwqfilter -o rockyou-ntlm.pwq --create=14637132 --hash-ntlm-cp1252 --optimize-fp-rate-at-high-load < rockyou.txt
./pwqfilter -f rockyou-ntlm.pwq --pre-hashed < pp8-100p > pp8-100p-rock
./pwqfilter -f rockyou-ntlm.pwq --pre-hashed < pwned-passwords-ntlm-ordered-by-count-v8.txt > pp8-rock-by-count # could use pp8-100p-rock here
tr -d '\r' < pp8-rock-by-count | awk -F: '{ print $2 ":" $1 }' > pp8-count-by-rock

# set UnicodeStoreUTF8 = N
./john -w=rockyou.txt --format='dynamic=md4(utf16($p))' -encoding=cp1252 -verb=1 pp8-100p-rock
./john -show --format='dynamic=md4(utf16($p))' pp8-count-by-rock | head -n -2 > count-pp8-100p-r

bzcat rockyou-withcount.txt.bz2 | sed 's/^ *//; s/ /:/' > count-r

./count-filter.pl < count-pp8-100p-r > pp8-100p-rfd97
```

count-filter.pl:
```perl
#!/usr/bin/perl

open(R, "< count-r") || die;
while (<R>) {
        ($c, $p) = /^(\d+):(.*)$/;
        $r{$p} = $c;
}
close(R);

while (<>) {
        ($c, $p) = /^(\d+):(.*)$/;
        if (defined($r{$p})) {
                next if ($c - $r{$p} < 97);
        } else {
                print STDERR "$c:$p NOT FOUND\n";
        }
        print "$p\n";
}
```

Line counts:
```
1798369 count-pp8-100p-r
1795679 pp8-100p-rfd97
```

Cracks with `-form=nt -encoding=cp1252 -ru=single` on 1M representative sample of HIBP v8 (826973 unique):

`count-pp8-100p-r` (with the count field removed):
```
355532g 0:00:02:42 DONE (2022-01-18 14:41) 2184g/s 8787Kp/s 8787Kc/s 4564GC/s nayera1900..sambarock1900
519765 password hashes cracked, 480235 left
```

`pp8-100p-rfd97`:
```
355445g 0:00:02:43 DONE (2022-01-18 14:36) 2179g/s 8753Kp/s 8753Kc/s 4529GC/s sky2461900..sambarock1900
519678 password hashes cracked, 480322 left
```

This mild filtering against RockYou passwords that have too few additional hits in HIBP reduces the wordlist size to 99.850% while preserving 99.975% cracks.

There are only 11 passwords in our current `password.lst` that aren't in `pp8-100p-rfd97` above - empty line and 10 passwords below:

```
4055
allo
basf
kcin
kissa2
notused
plus
test2
unix
zzz
```

Many of these do appear to be about as common in HIBP and as efficient at cracking HIBP with rules as some lines that do get into `pp8-100p-rfd97` above.

Maybe these 10 should be added to the above processing along with `rockyou.txt` or maybe they should be added to almost final wordlist file or maybe `pp8-100p-rfd97` should be added to our `password.lst` (excluding dupes).

We should include the empty line somewhere in there. Its optimal location can't be determined from RockYou and HIBP. Maybe we should assume it's around line 20 like we had it before (based on Unix password cracking dating back to 1990s).

Maybe the above procedure should be separately applied e.g. for HIBP 1000+, 200+, 100+, and then the resulting lists combined with comments inserted between them, to allow for easy separation later (e.g., in case we later enhance batch mode to allow more rules for a smaller wordlist first, then fewer rules for the rest).

**Comment by solardiz** [comment]
For comparison, with our current tiny `password.lst` and `-ru=single`:

```
59364g 0:00:00:00 DONE (2022-01-20 17:39) 72395g/s 3653Kp/s 3653Kc/s 2364GC/s zzz1900..sss1900
162214 password hashes cracked, 837786 left
```

With our current tiny `password.lst` and current default wordlist rules:

```
3129g 0:00:00:00 DONE (2022-01-20 17:40) 12034g/s 13638p/s 13638c/s 11256MC/s !@#$%..sss
66346 password hashes cracked, 933654 left
```

These are almost instant, but then the proposed new wordlist almost instantly gets to 200k+. Its substantial running time (or rather time that would be substantial for a slow hash) is to get beyond 200k to 300k+ (or 500k+ non-unique), which the tiny wordlist doesn't reach (by far).

**Comment by solardiz** [comment]
Top 20 of `pp8-100p-rfd97` above are:

```
123456
123456789
qwerty
password
12345678
111111
qwerty123
1q2w3e
1234567
abc123
1234567890
123123
DEFAULT
password1
000000
12345
iloveyou
1q2w3e4r5t
qwertyuiop
123321
```

Some of these are just right, some are not. Most notably, `DEFAULT` is probably an artifact specific to HIBP. It is in RockYou (or it wouldn't get in here, like most other HIBP noise did not), but it ranks very low there. I think we can remedy this in one or both of two ways:

1. Append `pp8-100p-rfd97` to our current `password.lst` (sans dupes). Then our top ~3.5k would stay as-is, not be influenced by HIBP's flawed ranking.
2. Apply RockYou ranking, on its own (replacing HIBP's) or additionally. For the latter, I can repeat my approach above initially using subsets of RockYou (start with a top N list, then top 10N or such, and finally full) and then concatenate the results in that order.

**Comment by solardiz** [comment]
> ```shell
> ./count-filter.pl < count-pp8-100p-r > pp8-100p-rfd97
> ```

Curiously, for HIBP 1000+ hits, this step (still requiring only 97+ hits on top of RockYou's) does not remove any lines. For HIBP 200+, it removes 8 lines. Indeed, we could adjust the threshold e.g. to 197, but that would be inconsistent with us also planning on running with 100+ later.

Wordlist size and crack counts for HIBP 1000+ (overlap with RockYou, 97+ on top of RockYou):

```
286797 pp8-1000p-rfd97
262552g 0:00:00:31 DONE (2022-01-20 18:28) 8372g/s 7088Kp/s 7088Kc/s 4385GC/s mop1900..1121151900
424900 password hashes cracked, 575100 left
```

Ditto for 200+

```
1117689 pp8-200p-rfd97
332292g 0:00:02:03 DONE (2022-01-20 18:34) 2686g/s 7202Kp/s 7202Kc/s 3916GC/s whisperwind1900..ericaj11900
496058 password hashes cracked, 503942 left
```

Incidentally, 200+'s size is very close to RockYou 3+ hits, so let's also compare to that:

```
1136144 rtop1M-3p
314763g 0:00:02:07 DONE (2022-01-20 18:37) 2478g/s 7074Kp/s 7074Kc/s 3949GC/s !paolina!1900..  nam1900
476896 password hashes cracked, 523104 left
```

We kind of do have improvement over using RockYou 3+, but then when ranking/selecting by HIBP our testing against a sample from HIBP becomes in-sample. So this is not certain.

**Comment by solardiz** [comment]
The `pp8-1000p-rfd97` run above produces 222315159 candidates (with `-stdout`). Limiting a `pp8-100p-rfd97` run to that count produces slightly more cracks:

```
271688g 0:00:00:35 17.92% (ETA: 18:45:02) 7561g/s 6187Kp/s 6187Kc/s 3688GC/s Littlebigplaneti..Guitar11i
Session stopped (max candidates reached)
434331 password hashes cracked, 565669 left
```

So the larger wordlist not only helps ultimately have more cracks, but also doesn't hurt early cracking.

I disregard the differences in c/s rates and real times here because those are inexact (e.g., turbo boost varies here) and more importantly because I only use this fast hash type for simulations while I mostly care about slow/salted hashes, where this wouldn't be minutes, but days or worse. For those, only the candidate password count matters.

**Comment by solardiz** [comment]
> when ranking/selecting by HIBP our testing against a sample from HIBP becomes in-sample.

To reduce this effect, here's also testing against an arbitrary (beginning of hash-sorted list) sample of 1M unique HIBP hashes (out of the 800M+ without bias towards higher-count ones, so with little overlap with the top lists used for wordlist generation).

HIBP 200+:

```
82711g 0:00:02:05 DONE (2022-01-20 19:58) 658.1g/s 7089Kp/s 7089Kc/s 6759GC/s whisperwind1900..ericaj11900
```

RockYou 3+ (a tiny bit larger than the above):

```
74927g 0:00:02:07 DONE (2022-01-20 19:59) 586.0g/s 7028Kp/s 7028Kc/s 6739GC/s !paolina!1900..  nam1900
```

**Comment by solardiz** [comment]
Given the lack of comments by anyone else in 2 days, I assume the corresponding PR is OK to merge now. ;-)

**Comment by magnumripper** [comment]
I trust your decisions and methods 👍

**Comment by magnumripper** [comment]
Oh, there's one thing I'd prefer doing that I assume you didn't do here:

I would ensure the resulting wordlist is UTF-8 (eg. using cprepair). That way it can be used with any encoding. Having it as a mix of legacy codepages will be mostly useless. I assume the non-ASCII words that went into this are few, so manual auditing of codepage conversion is probably doable.

Edit: Checked it out and all is fine. Only 21 words contain non-ASCII and all of them are UTF-8.

**Comment by solardiz** [comment]
> A reason to sort alphabetically is it results in fewer dupes (produced by rules) getting through our poor man's check against the previous candidate. The total number of candidates to test (including dupes that got through) reduces by about 0.5% with alphabetic sorting.

Another reason is alphabetic sorting greatly improves the compression ratio (in `.git` and when we distribute releases) because it effectively removes information on the frequencies. However, this time I felt these two reasons are not good enough, because the frequency sorting is important while running the first few rules on the slowest hashes.

We can also consider (for later) length sorting (and alphabetic within each length?), which would help formats like md5crypt-opencl. Maybe some hybrid approach with such sorting separately within HIBP 1000+, 200+ and 100+ would be best. Within the 100+ additions, it would not hurt the frequency ordering much (the range is only 100 to 199, so 2x). Within 200+, it would hurt more (the range is 200 to 999, so 5x).

**Comment by solardiz** [comment]
Another reason to preserve perfect frequency sorting is to allow for efficient use of rules-first, such as with `--rules-stack`.

**Comment by solardiz** [comment]
New idea for the next update: rather than filter by RockYou, we could start with maximally-cracked HIBP top N (perhaps for some moderately larger N than our current wordlist size) and try wordlist+rules cracking of more HIBP (unique hashes only) by that, collecting "word stats" similarly to how my new "rules stats" feature works (that is, record number of cracks that each word achieves with all rules). Then filter and re-order by decreasing word score in such cracking (and drop words that cracked too few - like only cracked themselves). That way, even a password with very high count in HIBP would not get into the final list if it doesn't not crack enough other passwords when mangled. This should be quite effective at filtering out the HIBP noise, yet not as limiting as RockYou (which excludes any new common passwords that appeared after 2009).
