### ISSUE TITLE
AGAIN with: Error: No OpenCL-capable platforms were detected by the installed OpenCL driver

### ISSUE THREAD

**Issue by MikTur** [openwall/john#5005]
Hi, a topic covering this issue has just been opened and closed.
The problem is that any  path-to\john-1.9.0-jumbo-1-win64\etc\OpenCL\vendors\nvidia.icd  update with the proper nvopencl64.dll does not make the john executable recognize any nvidia opencl capable device.

*Files were read only :)

**Comment by solardiz** [comment]
@MikTur While we're aware of related issues discussed in #3191, what you posted here is confusing. Anyway, were you able to work around the issue, and exactly how?

**Comment by magnumripper** [comment]
His edit before closing dropped "Plese fix this annoying bug, thanks" in favor of "Files were read only :)" so I assume the problem was related to file system rights.
