### ISSUE TITLE
rar2john error

### ISSUE THREAD

**Issue by kanatovnurzhas** [openwall/john#5058]
rar2john photos/photo.rar > hash.txt
! file name: photo\2018\Photos (1).zip
! file name: photo\2018\Photos.zip
! file name: photo\2019\Photos (2).zip
! file name: photo\2019\Photos (3).zip
! file name: photo\2019\Photos (4).zip
! file name: photo\2019\Photos (5).zip
! file name: photo\2019\Photos (6).zip
! file name: photo\2020\Photos (1).zip
! file name: photo\2020\Photos (2).zip
! file name: photo\2020\Photos (3).zip
! file name: photo\2020\Photos (4).zip
! file name: photo\2020\Photos (5).zip
! file name: photo\2020\Photos.zip
! file name: photo\2021\10e148384c3c473aac8b24498687cbc5.mov
! file name: photo\2021\IMG_0383.MOV
! file name: photo\2021\IMG_9784.MOV
! file name: photo\2021\IMG_9927.MOV
! file name: photo\2021\Photos (1).zip
! file name: photo\2021\Photos (1)11.zip
! file name: photo\2021\Photos (1)77.zip
! file name: photo\2021\Photos (10).zip
! file name: photo\2021\Photos (11).zip
! file name: photo\2021\Photos (12).zip
! file name: photo\2021\Photos (13).zip
! file name: photo\2021\Photos (14).zip
! file name: photo\2021\Photos (15).zip
! file name: photo\2021\Photos (16).zip
! file name: photo\2021\Photos (2).zip
! file name: photo\2021\Photos (2)1.zip
! file name: photo\2021\Photos (3).zip
! file name: photo\2021\Photos (4).zip
! file name: photo\2021\Photos (5).zip
! file name: photo\2021\Photos (6).zip
! file name: photo\2021\Photos (7).zip
! file name: photo\2021\Photos (8).zip
! file name: photo\2021\Photos (9).zip
! file name: photo\2021\Photos.zip
! file name: photo\2021\Photos111.zip
! file name: photo\2021\Photos7.zip
! Unicode:   photo\2021 до 5,09\IMG_2342.png
! Unicode:   photo\2021 до 5,09\IMG_2343.png
! Unicode:   photo\2021 до 5,09\Photos (1).zip
! Unicode:   photo\2021 до 5,09\Photos (10).zip
! Unicode:   photo\2021 до 5,09\Photos (11).zip
! Unicode:   photo\2021 до 5,09\Photos (12).zip
! Unicode:   photo\2021 до 5,09\Photos (13).zip
! Unicode:   photo\2021 до 5,09\Photos (14).zip
! Unicode:   photo\2021 до 5,09\Photos (15).zip
! Unicode:   photo\2021 до 5,09\Photos (2).zip
! Unicode:   photo\2021 до 5,09\Photos (3).zip
! Unicode:   photo\2021 до 5,09\Photos (4).zip
! Unicode:   photo\2021 до 5,09\Photos (5).zip
! Unicode:   photo\2021 до 5,09\Photos (6).zip
! Unicode:   photo\2021 до 5,09\Photos (7).zip
! Unicode:   photo\2021 до 5,09\Photos (8).zip
! Unicode:   photo\2021 до 5,09\Photos (9).zip
! Unicode:   photo\2021 до 5,09\Photos.zip
! Unicode:   photo\2021 до 5,09\RPReplay_Final1630150734.mp4
! file name: photo\2018
! file name: photo\2019
! file name: photo\2020
! file name: photo\2021
! Unicode:   photo\2021 до 5,09
! file name: photo

john hash.txt                                                      130 ⨯
Using default input encoding: UTF-8
Loaded 1 password hash (rar, RAR3 [SHA1 256/256 AVX2 8x AES])
No password hashes left to crack (see FAQ)

john hash.txt --show
photo.rar:2020:1::photo\2018\Photos (1).zip photo\2018\Photos.zip photo\2019\Photos (2).zip photo\2019\Photos (3).zip photo\2019\Photos (4).zip photo\2019\Photos (5).zip photo\2019\Photos (6).zip photo\2020\Photos (1).zip photo\2020\Photos (2).zip photo\2020\Photos (3).zip photo\2020\Photos (4).zip photo\2020\Photos (5).zip photo\2020\Photos.zip photo\2021\10e148384c3c473aac8b24498687cbc5.mov photo\2021\IMG_0383.MOV photo\2021\IMG_9784.MOV photo\2021\IMG_9927.MOV photo\2021\Photos (1).zip photo\2021\Photos (1)11.zip photo\2021\Photos (1)77.zip photo\2021\Photos (10).zip photo\2021\Photos (11).zip photo\2021\Photos (12).zip photo\2021\Photos (13).zip photo\2021\Photos (14).zip photo\2021\Photos (15).zip photo\2021\Photos (16).zip photo\2021\Photos (2).zip photo\2021\Photos (2)1.zip photo\2021\Photos (3).zip photo\2021\Photos (4).zip photo\2021\Photos (5).zip photo\2021\Photos (6).zip photo\2021\Photos (7).zip photo\2021\Photos (8).zip photo\2021\Photos (9).zip photo\2021\Photos.zip photo\2021\Photos111.zip photo\2018 photo 

1 password hash cracked, 0 left

john --list=build-info
Version: 1.9.0-jumbo-1+bleeding-aec1328d6c 2021-11-02 10:45:52 +0100
Build: linux-gnu 64-bit x86_64 AVX2 AC
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: AVX2
$JOHN is /usr/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 65535
Effective limit: Max. KPC 4096 at length 16, down to 525 at length 125
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 11.2.0
GNU libc version: 2.32 (loaded: 2.32)
Crypto library: OpenSSL
OpenSSL library version: 0101010cf
OpenSSL 1.1.1l  24 Aug 2021
GMP library version: 6.2.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 41 ns
Total physical host memory: 4700 MiB
Available physical host memory: 3531 MiB
Terminal locale string: ru_RU.UTF-8
Parsed terminal locale: UTF-8

The file weighs 24 GB, the password hash in the form of a file came out but there is no password there

**Comment by magnumripper** [comment]
The password was already cracked, as "2020".

Maybe we should change `--show` so it doesn't show the gecos etc. fields.

**Comment by solardiz** [comment]
> Maybe we should change `--show` so it doesn't show the gecos etc. fields.

Maybe, but this is also sometimes useful, so it'd need to become an option. As an alternative, maybe we can highlight the passwords in color when output is to a tty? We already do use color during cracking.

**Comment by solardiz** [comment]
@magnumripper Do we close this "issue" or maybe repurpose it for "highlight the passwords in color when output is to a tty"?

Edit: actually I think we should close, and open a separate issue if we like.
