### ISSUE TITLE
Add rule command for unicode decomposition "stripping"

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#506]
Add a rule that performs “stripping” of codepage characters like é → e and č → c. This is easy using Unicode decomposition and just using the base character.

**Comment by solardiz** [comment]
I think this is mostly obsoleted by the ruleset added in 99f6b0c798cf039f8f4efef3d5423988f98af8fe, which implements similar functionality through pre-existing rule commands. So closing this for now. If anyone disagrees, we can reopen.
