### ISSUE TITLE
TrueCrypt formats: ciphertexts contain filenames

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#5068]
TrueCrypt formats (`TrueCrypt-opencl`, `tc_aes_xts`, `tc_ripemd160`, `tc_ripemd160boot`, `tc_sha512-out`, `tc_whirlpool`) support keyfiles. They are referenced by filenames from ciphertexts.

I see that zip or pkzip format was changed to avoid files and to embed files into hash. I guess similar change might be needed here.

In practice, I have problem that `--fuzz` exits because `get_salt` cannot open file with synthetic name. Sample:
```
$ python -c 'print "truecrypt_SHA_512$" + "aa" * 512 + "$1$2$3"' > t.pw
$ ./run/john t.pw
Warning: detected hash type "tc_aes_xts", but the string is also recognized as "tc_sha512"
Use the "--format=tc_sha512" option to force loading these as that type instead
fopen 2$3: No such file or directory
```

`strace` suggests that actual name is `2`. So name is reported wrongly.

Respective code:
```c
		fp = fopen(tpath, "rb");
		if (!fp)
			pexit("fopen %s", p);
```

This part of code is same in `truecrypt_fmt_plug.c` and in `opencl_tc_fmt_plug.c`.

Also I guess that `jtr_fopen` macro should be used instead of regular `fopen`.

(Backreference to #5067, where I mentioned it.)

**Comment by AlekseyCherepanov** [comment]
`1$2$3` suffix is the number of filenames + 2 filenames, but the second filename is not used due to provided number lower than actual number of filenames. So `valid` could check that.

Changing syntax of ciphertext to embed files number of keyfiles might be removed.

**Comment by solardiz** [comment]
Aleksey, I think we should fix actual bugs (and you're working on just that - thanks!), but keep the files external (not embed them in the "hashes").

In fact, I think we should (later, perhaps after our next release) rework the rest of `*2john` and formats to never embed large files in "hashes", but reference them externally. It's just ridiculous and confusing and inconvenient and wasteful to have huge "hashes". We have an open issue to have the tools tell the users this is OK - to hopefully reduce the confusion - but a better fix would be for us to stop being ridiculous in this respect.

**Comment by AlekseyCherepanov** [comment]
Theoretical advantage of embedding is that it would be possible to open all input files (and .pot files), prohibit most syscalls through seccomp and then parse input.

**Comment by solardiz** [comment]
I see no reason to keep this issue open, so I'll close. If we ever have time (not only for discussion, but also for implementation of changes), we may instead open an issue about approach to large target files in general.
