### ISSUE TITLE
TrueCrypt formats: incorrect handling of keyfiles, works only for single ciphertext

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#5072]
Working on #5069 I did not realize real problem here:
```c
static unsigned char (*keyfiles_data)[MAX_KFILE_SZ];
[...]
static void init(struct fmt_main *self)
[...]
	keyfiles_data = mem_calloc(MAX_KEYFILES,
			sizeof(*keyfiles_data));
[...]
static void* get_salt(char *ciphertext)
[...]
	for (idx = 0; idx < s->nkeyfiles; idx++) {
[...]
		/* read this into keyfiles_data[idx] */
		fp = fopen(tpath, "rb");
```

So keyfiles for all ciphertexts are read into the same place in memory. So it would work for single ciphertext and would not work for two ciphertexts with different keyfiles (one ciphertext would become uncrackable). Data from keyfiles should be a part of salt.

(It is purely theoretical. I don't have samples.)

Fix would require switching onto dynamic salt. Or it is possible to exit with error when two ciphertexts with keyfiles are loaded.

Keyfiles in `john` do not seem popular. Their support in OpenCL format did not work due to allocation happening after loading (fixed in #5069).

**Comment by AlekseyCherepanov** [comment]
There might be some related notes in #5068 in the future.

**Comment by solardiz** [comment]
I don't fully understand this issue, but perhaps at least this must be implemented before our next release:

> it is possible to exit with error when two ciphertexts with keyfiles are loaded.

@AlekseyCherepanov Can you take care of this, please?

**Comment by AlekseyCherepanov** [comment]
I can. Maybe I could do proper fix too.

**Comment by AlekseyCherepanov** [comment]
`john-samples` has TrueCrypt volumes with keyfiles.

Also `truecrypt2john.py` has the following bug: single keyfile is not included into ciphertext. That's a matter of `>` vs `>=`. So I can produce in practice the original problem I described.

`TrueCrypt/TC-Volume` has 2 volumes (normal and hidden) that use different keyfiles. So I get 12 ciphertexts in 2 invocations of `truecrypt2john.py` (2 volumes x 3 algos x 2 sets of keyfiles).

Depending on the order of ciphertexts I can crack either one volume or the other.
```
$ rm run/john.pot
$ ./run/truecrypt2john.py ../john-samples/TrueCrypt/TC-Volume/TC-Normal-Volume.txt ../john-samples/TrueCrypt/TC-Volume/Whirlpool-Keyfile-3 ../john-samples/TrueCrypt/TC-Volume/RIPEMD-160-Keyfile-1 ../john-samples/TrueCrypt/TC-Volume/SHA-512-Keyfile-2 > tc.pw
$ ./run/truecrypt2john.py ../john-samples/TrueCrypt/TC-Volume/TC-Normal-Volume.txt ../john-samples/TrueCrypt/TC-Volume/RIPEMD-160-hidden-kf  >> tc.pw
$ ./run/john tc.pw --wordlist=<(echo truecrypt; echo TRUECRYPT)
[...]
TRUECRYPT        (TC-Normal-Volume.txt)     
```

```
$ rm run/john.pot
$ ./run/truecrypt2john.py ../john-samples/TrueCrypt/TC-Volume/TC-Normal-Volume.txt ../john-samples/TrueCrypt/TC-Volume/RIPEMD-160-hidden-kf  > tc.pw
$ ./run/truecrypt2john.py ../john-samples/TrueCrypt/TC-Volume/TC-Normal-Volume.txt ../john-samples/TrueCrypt/TC-Volume/Whirlpool-Keyfile-3 ../john-samples/TrueCrypt/TC-Volume/RIPEMD-160-Keyfile-1 ../john-samples/TrueCrypt/TC-Volume/SHA-512-Keyfile-2 >> tc.pw
$ ./run/john tc.pw --wordlist=<(echo truecrypt; echo TRUECRYPT)
[...]
truecrypt        (TC-Normal-Volume.txt)     
```

That's because the latest loaded ciphertext overwrites keyfiles in memory.

Taking into account that `truecrypt2john.py` prints 3 ciphertexts for each volume, simple check that only one ciphertext uses keyfiles does not seem very helpful.

**Comment by AlekseyCherepanov** [comment]
`TrueCrypt-opencl` shows binary garbage in status line cracking ciphertexts with keyfiles. So I excluded the format from my work on #5120.

Also I could not crack `TC-STD-Volume` sample. (Note for myself to avoid closing this issue without fix or new issue.)

**Comment by AlekseyCherepanov** [comment]
I've sent a pull request to john-samples with output from tcplay.

tcplay reports that tc-hackthis, TC-Volume-2 (normal and hidden) use cipher cascades. It looks like they are not implemented in john.

Also I could not crack TC-STD-Volume. It is sha512 + serpent. It can be cracked with `--disable-simd` build. Both sha512 and serpent work in self tests with other algos.

**Comment by AlekseyCherepanov** [comment]
Password of length 64 causes crash under ASan. `crypt_all()` uses buffer with length 64 and `strncpy()` to copy there, while `apply_keyfiles()` passes this buffer into `strlen()`.

**Comment by solardiz** [comment]
@AlekseyCherepanov Looks like you now use this issue for anything TrueCrypt, and that makes it hard to track individual bugs. Your latest two comments here look to me like each is reporting a different bug, and if so they should be separate issues - will you open them? Also, is the original issue here perhaps fixed by now - and if so will you please close it? Thank you!

**Comment by AlekseyCherepanov** [comment]
The original issue is not ready: the same changes should be ported onto `truecrypt-opencl` format. But indeed, now I know that non-crackable samples are not related to my changes. I intend to fix everything easy and open issues for everything else.

Support for cascaded ciphers is discussed in #1876.

**Comment by AlekseyCherepanov** [comment]
> `TrueCrypt-opencl` shows binary garbage in status line cracking ciphertexts with keyfiles.

Keyfiles are applied onto `inbuffer` corrupting candidates given to the format.

**Comment by solardiz** [comment]
@AlekseyCherepanov Well, perhaps you should open an issue for "Password of length 64 causes crash under ASan" and another for "could not crack TC-STD-Volume. It is sha512 + serpent. It can be cracked with --disable-simd."

**Comment by AlekseyCherepanov** [comment]
Everything got fixed. I close the issue.
