### ISSUE TITLE
Unicode NFC/NFD functions

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#508]
Issue #506 would be trivial once we have functionality in unicode.c for conversion between composed (NFC) and decomposed (NFD) versions of characters. Example: Decomposed version of LATIN SMALL LETTER A WITH DIAERESIS (U+00E4) is LATIN SMALL LETTER A (U+0061) COMBINING DIAERESIS (U+0308),

These functions can be used for other good stuff as well. We'd add rules for calling them, for a starter.

**Comment by solardiz** [comment]
If #506 isn't to be worked on, then this one shouldn't be either. So closing for now. Both can be reopened.
