### ISSUE TITLE
John doesn't recognize my gpu

### ISSUE THREAD

**Issue by DanielsBerlin** [openwall/john#5087]
I tested john, and it seems that it only uses my cpu for cracking
and doesn't recognize my gpu
I have Geforce GTX 860 m and invidia graphic driver 461.72 has been installed
when I use this command I get:
```
C:\john\run>john --list=opencl-devices
Error: No OpenCL-capable platforms were detected by the installed OpenCL driver.
Error: No OpenCL-capable devices were detected by the installed OpenCL driver.
```

**Comment by ghost** [comment]
See [#4327](https://github.com/openwall/john/issues/4327#issuecomment-683474420) or https://github.com/openwall/john/issues/3191#issuecomment-639818020

Please report if your issue is not fixed after doing this.

**Comment by solardiz** [comment]
Not an issue we need to track, so I'm closing it, but please feel free to add comments.
