### ISSUE TITLE
Hide hwloc warnings

### ISSUE THREAD

**Issue by noraj** [openwall/john#5088]
## Issue

john is displaying this hwloc warning at every command due to this upstream issue https://github.com/open-mpi/hwloc/issues/354:

```
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
```

## Workaround

Add `export HWLOC_HIDE_ERRORS=2` to `~/.zshrc`, `~/.bashrc` or whatever to hide the warnings.

## Context

I can't find where in code john is calling hwloc, it must be an indirect call via an abstraction library.

**Comment by magnumripper** [comment]
I take it the messages you are seeing are from OpenMPI (possibly related to your OpenCL driver's probing of PCI bus), not john. If you try a non-MPI build the warnings should be gone.

Thus, I believe there's nothing for us to fix in john.

The workaround is good to have noted, thanks!

**Comment by noraj** [comment]
Yes it's what I said, I just wrote that here so that people having the same issue will know the workaround. It's not a bug report or feature request.
