### ISSUE TITLE
Problem with multibit2john.py: TypeError: Descriptors should not be created directly, but only retrieved from their parent.

### ISSUE THREAD

**Issue by cbrooks42** [openwall/john#5089]
I'm having a problem using the latest version of multibit2john.py.  When I try to execute the script with a Multibit Classic .key file, I get the following error:

~/Desktop$ python3 multibit2john.py multibit.key 
Traceback (most recent call last):
  File "multibit2john.py", line 56, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/crypto/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 731, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

I have verified that I'm using the latest version of the multibit2john.py script, found here: https://github.com/openwall/john/blob/bleeding-jumbo/run/multibit2john.py

I'm using python 3.8.10 on Ubuntu:
~/Desktop$ python -V
Python 3.8.10

I have also verified that I have the latest version of the google protobuf module:
~/Desktop$ sudo pip install --user protobuf
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (3.6.1)

The only workaround that I've found to date is to remove all of the protobuf code, lines 20 - 1295.  

If I remove those lines of code, multibit2john.py appears to execute correctly, and it generates a reasonable looking hash (according to https://hashcat.net/wiki/doku.php?id=example_hashes).  

But, I'm concerned that, perhaps, the protobuf code was included for a reason -- and I have routed around that reason.

Any suggestions for fixing the error?

Thanks, Chris

**Comment by willcbanks** [comment]
i'm having the exact same issue. I thought it might be something to do with using python 2 or python 3 but not having any luck fixing it

**Comment by willcbanks** [comment]
> I'm having a problem using the latest version of multibit2john.py.  When I try to execute the script with a Multibit Classic .key file, I get the following error:
> 
> ~/Desktop$ python3 multibit2john.py multibit.key Traceback (most recent call last):   File "multibit2john.py", line 56, in     _descriptor.EnumValueDescriptor(   File "/home/crypto/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 731, in **new**     _message.Message._CheckCalledFromGeneratedFile() TypeError: Descriptors should not be created directly, but only retrieved from their parent.
> 
> I have verified that I'm using the latest version of the multibit2john.py script, found here: https://github.com/openwall/john/blob/bleeding-jumbo/run/multibit2john.py
> 
> I'm using python 3.8.10 on Ubuntu: ~/Desktop$ python -V Python 3.8.10
> 
> I have also verified that I have the latest version of the google protobuf module: ~/Desktop$ sudo pip install --user protobuf Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (3.6.1)
> 
> The only workaround that I've found to date is to remove all of the protobuf code, lines 20 - 1295. 
> 
> If I remove those lines of code, multibit2john.py appears to execute correctly, and it generates a reasonable looking hash (according to [https://hashcat.net/wiki/doku.php?id=example_hashes). ](https://hashcat.net/wiki/doku.php?id=example_hashes).%C2%A0)
> 
> But, I'm concerned that, perhaps, the protobuf code was included for a reason -- and I have routed around that reason.
> 
> Any suggestions for fixing the error?
> 
> Thanks, Chris

If removing that code works, you could try to make a new multibit wallet, then try to make the hash and try to decrypt it to see if it worked I guess. What does protobuf do in the code anyway?
Thanks - I deleted those lines and now it's working too.
I'll try to hash a new wallet and dehash to see if the script still works!

**Comment by willcbanks** [comment]
I can confirm this works. hashcat found the password.

**Comment by solardiz** [comment]
The protobuf code was added by @kholia in 6c55ea09ac494164e351fd51d457be267b6769da. It is unclear to me whether it was actually needed or not.

@kholia @exploide Can you take a look and comment, and possibly send us a PR removing this code or making its importing conditional upon detection of the wallet type that needs it (if any)? Thanks!

**Comment by exploide** [comment]
I have neither experience with Multibit nor Protobuf, but I had a quick look on `multibit2john.py`.

Protobuf is used to dynamically generate some classes useful for parsing the data structure. This is indeed used by the file processing logic in https://github.com/openwall/john/blob/75667e266c2b9356504a86c6013b91a9a3e48c4e/run/multibit2john.py#L1323 which is only relevant for `.wallet` files. And that's the reason the reporters did not have the problem with their `.key` files.

The `TypeError: Descriptors should not be created directly, but only retrieved from their parent.` sounded like changed behavior in Protobuf to me, so I googled it. And indeed, there is a weird check that was introduced eventually. The library requires that files containing Protobuf definitions end in `_pb2`. Probably because usually you don't have the definitions within a standalone script but within includable definition files or the like.

So the easy fix was `mv multibit2john.py multibit2john_pb2.py` :smile: However, this might be an unusual file name for the John scripts.

**Comment by solardiz** [comment]
Thank you, @exploide! Maybe a clean fix would be to actually move the protobuf definitions into a separate file that we'd include from the script (keeping the main script's name)? Can we do that without difficulties with the main script finding that included file even when run from a different current directory (via full or relative path)? Also without the main script trusting its current directory.
