### ISSUE TITLE
John with --format=dmg-opencl --test=1 GIVES ERROR: Build log: <kernel>:113:21: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type

### ISSUE THREAD

**Issue by pm2r** [openwall/john#5095]
Hello everybody,
this is my first issue so forgive me in case I miss something important.
I was trying to run john with OPENCL on a Win10 machine with Intel x86 and Nvidia GPU 1080 class.

I tried this line on Windows CMD (not Powershell since I read that is not working OK with open CL in windows)  :
 **..\john-1.9.0-jumbo-1-win64\run>.\john-avx.exe --format=dmg-opencl --test=1**

The output is this one:

**..\john-1.9.0-jumbo-1-win64\run>.\john-avx.exe --format=dmg-opencl --test=1**
Device 1: NVIDIA GeForce GTX 1080
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL]... Options used: -I ./kernels -cl-mad-enable -DSM_MAJOR=6 -DSM_MINOR=1 -D__GPU__ -DDEVICE_INFO=524306 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=512 -DDEV_VER_MINOR=15 -D_OPENCL_COMPILER -DHASH_LOOPS=500 -DOUTLEN=32 -DV_WIDTH=1 ./kernels/dmg_kernel.cl
Build log: <kernel>:113:21: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
        hmac_sha1(key, 20, (const uchar*)&cno, 4, iv, 20);
                           ^~~~~~~~~~~~~~~~~~
./kernels\opencl_hmac_sha1.h:28:43: note: passing argument to parameter '_data' here
                      HMAC_MSG_TYPE void *_data, uint data_len,
                                          ^
<kernel>:118:31: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
        AES_cbc_decrypt(salt->chunk, outbuf, salt->data_size, &aes_decrypt_key, iv);
                                     ^~~~~~
./kernels\opencl_aes.h:159:60: note: passing argument to parameter '_out' here
AES_cbc_decrypt(AES_SRC_TYPE void *_in, AES_DST_TYPE void *_out,
                                                           ^
<kernel>:128:22: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
                hmac_sha1(key, 20, (const uchar*)&cno, 4, iv, 20);
                                   ^~~~~~~~~~~~~~~~~~
./kernels\opencl_hmac_sha1.h:28:43: note: passing argument to parameter '_data' here
                      HMAC_MSG_TYPE void *_data, uint data_len,
                                          ^
<kernel>:133:33: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
                AES_cbc_decrypt(salt->zchunk, outbuf, 4096, &aes_decrypt_key, iv);
                                              ^~~~~~
./kernels\opencl_aes.h:159:60: note: passing argument to parameter '_out' here
AES_cbc_decrypt(AES_SRC_TYPE void *_in, AES_DST_TYPE void *_out,
                                                           ^

Error building kernel ./kernels/dmg_kernel.cl. DEVICE_INFO=524306
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1386 - clBuildProgram

Here is the build info:
**Version: 1.9.0-jumbo-1
Build: cygwin 64-bit x86_64 AVX AC OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX
CPU fallback binary: john-sse41
OMP fallback binary: john-avx-non-omp
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's**

**Comment by ghost** [comment]
Please download and update your version of john. You can find the Windows version download button on the main page of this repository or at https://github.com/openwall/john-packages/releases/tag/jumbo-dev.

After the update, please check again and, if any problem persists, let us know.

**Comment by pm2r** [comment]
Now it works ! 
Thanks a lot
