### ISSUE TITLE
Support KeePass database format 4.x

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5097]
Our `keepass2john.c` has:

```c
uint32_t FileVersion32 = 0x00040000;
uint32_t FileVersion32_4 = 0x00040000;  // from KeePass 2.36 sources

// We currently support database formats up to KDBX v3.x. KDBX 4.x is not
// supported yet. See "KdbxFile.cs" in KeePass 2.36 for more information on
// KDBX 4.x format.
```

```c
        if (uVersion >= FileVersion32_4) {
                fprintf(stderr, "! %s : File version '%x' is currently not supported!\n", encryptedDatabase, uVersion);
                goto bailout;
        }
```

This was actually triggered by a user (on Kali Linux 2021.1, but our `keepass2john.c` hasn't changed in this respect since 2017):

```
$ keepass2john test.kdbx
! test.kdbx : File version '40001' is currently not supported!

$ file test.kdbx
test.kdbx: Keepass password database 2.x KDBX
```

(The reporting by `file` doesn't mean much - it probably is unaware of newer versions.)

**Comment by solardiz** [comment]
Apparently, KDBX 4 uses Argon2 by default. We might want to handle that as a new format with its own set of tunable costs (Argon2's) or add the algorithm choice as a first tunable cost (but I'd prefer separate format, so that it's separately benchmarked, etc).

**Comment by krillin666** [comment]
Is there any update on this issue ? :smile:

**Comment by solardiz** [comment]
@krillin666 No, and moreover no update is currently expected - as you can see, this issue isn't part of a milestone. So it just sits here. Maybe a new contributor would appear and take care of it.

**Comment by sinand99** [comment]
2 years and still nothing?

**Comment by solardiz** [comment]
@sinand99 Exactly. You want to contribute?

**Comment by sinand99** [comment]
Latest windows build Bleeding john 20241102.1 gives me this error:

![Screenshot 2024-11-14 174759](https://github.com/user-attachments/assets/361a5448-de2b-4aa9-a9a1-89eb2016ce41)

**Comment by magnumripper** [comment]
You'll need a newer build. @claudioandre-br are those builds triggered manually, or just periodically?

**Comment by ghost** [comment]
> are those builds triggered manually, or just periodically?

Manually, at specific periods.

If magnum doesn't push a last-minute change, something new will be available tomorrow or, more likely, on Saturday.

**Comment by Mek7** [comment]
I was able to extract a hash from kdbx file of the new format. I used keepass2john from [Bleeding john 20241119.1](https://github.com/openwall/john-packages/releases/tag/bleeding)
But trying to load it into hashcat I get an error: salt-value exception (yes, I removed file name and leading colon from keepass2john output).
```
Hashfile '.\hashfile.txt' on line 1 ($keepa...a8f535f266298d53df88c4fbabc4574c): Salt-value exception
No hashes loaded.
```
Considering that hashcat's last release was very long ago, maybe it isn't prepared for this kind of hashes? Or has anyone had success with hashcat and using the keepass2john on new kdbx format?

**Comment by solardiz** [comment]
@Mek7 Why load it into hashcat? Please load it into `john`. This is brand new functionality we have here, so indeed hashcat isn't expected to recognize it yet (and I think in general it doesn't have Argon2 code yet, they have an open issue for that).

**Comment by Mek7** [comment]
I tried hashcat because I know it well :)
Tried john now and after some fiddling it seems to be working. Thanks.

**Comment by solardiz** [comment]
@Mek7 Thank you for helping us test this. If you don't mind sharing, are you running this on CPU or GPU? Can you show `john` startup lines (where it says what format, what costs, what device, etc.) and the speeds you're getting?

**Comment by Mek7** [comment]
I'm trying this on a laptop - MSI Katana 17 B13VGK.

3 hashes/s on CPU - Intel Core i9-13900H
2 hashes/s on integrated Intel graphics
12 hashes/s on NVIDIA GeForce RTX 4070 Laptop GPU

The hash seems to be very complicated and slow:
```
Device 1: NVIDIA GeForce RTX 4070 Laptop GPU
Loaded 1 password hash (KeePass-Argon2-opencl [BlaMka OpenCL])
Cost 1 (t) is 4 for all loaded hashes
Cost 2 (m) is 1022976 for all loaded hashes
Cost 3 (p) is 8 for all loaded hashes
Cost 4 (KDF [0=Argon2d 2=Argon2id]) is 0 for all loaded hashes
Note: Passwords longer than 41 [worst case UTF-8] to 124 [ASCII] rejected
Trying to compute 7 hashes at a time using 6993 of 8187 MiB device memory
LWS=[32-64] GWS=[1792-1792] ([28-56] blocks) => Mode: WARP_SHUFFLE
Proceeding with wordlist:D:\Slovniky\CZSK\CZSK.txt
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
0g 0:00:00:41 0.05% (ETA: 20:15:07) 0g/s 12.29p/s 12.29c/s 12.29C/s Alt/Ins
0g 0:00:00:46 0.06% (ETA: 19:53:42) 0g/s 12.30p/s 12.30c/s 12.30C/s AntiCAD..Antichrist
0g 0:00:00:51 0.06% (ETA: 19:23:23) 0g/s 12.31p/s 12.31c/s 12.31C/s Astr-IX..Atlantic
0g 0:00:00:56 0.07% (ETA: 19:06:07) 0g/s 12.32p/s 12.32c/s 12.32C/s BAM-LAN..BANK-IV
...etc...
```
didn't find the password yet.
On the Intel GPU it even caused my mouse cursor to stutter, and CPU was very slow too but since JtR cannot run on both GPU and CPU simultaneously (not by itself, only if I split the wordlist or by other method) I decided to use the NVIDIA GPU only. At least I learned that Argon2 is designed to be memory-intensive. So my CPU or GPU utilization is very low, contrary to other common hash algorithms.

**Comment by solardiz** [comment]
@Mek7 Thanks. This looks good to me. You may try letting it use almost the full GPU memory, if you don't need to use this GPU simultaneously for anything else.

> Trying to compute 7 hashes at a time using 6993 of 8187 MiB device memory

Looks like you could increase this from 7 to 8 by `GWS=2048 john ...` (doesn't get saved in `.rec` file, so you can easily resume without it if you choose so) or the `--gws=2048` option (is saved/restored). The speed may then improve a little.

**Comment by solardiz** [comment]
> GWS=2048 john ...

That syntax is for a Unix shell (if you're e.g. on Linux or if you use Cygwin on Windows). If you use the normal Windows command line, I guess the `--gws` option is easier for you. I got the value 2048 by multiplying the auto-detected 1792 by 8/7.

For anyone else reading this, please note that it'd almost certainly be different for you - this advice would not apply, or at least the GWS values would likely be different.

**Comment by Mek7** [comment]
Yes, that makes sense. So I tried the GWS parameter, got this:
```
Trying to compute 8 hashes at a time using 7992 of 8187 MiB device memory
LWS=32 GWS=2048 (64 blocks) => Mode: WARP_SHUFFLE
P
```
but my speed somehow dropped to 8 hashes/s.

**Comment by solardiz** [comment]
The speed drop is puzzling. What's the actual GPU memory usage per `nvidia-smi`?

What would the speed be with GWS 1536? I wonder if the memory is somehow non-uniform, or maybe we're spilling into host memory already.
