### ISSUE TITLE
PDFs without FileID field cannot be cracked

### ISSUE THREAD

**Issue by kenspeckle1** [openwall/john#5108]
I noticed that `john` require the `FileID` field in PDFs to be set (it is part of the hash). The problem is, that this field may be set in a PDF, but it is not required ([PDF Specs see page 115](https://web.archive.org/web/19961219053721/http://www.adobe.com:80/supportservice/devrelations/PDFS/TN/PDFSPEC.PDF) ).

[Here](https://github.com/openwall/john/files/8453996/id_missing.pdf) is a test file which is missing the /ID field. The resulting hash is `$pdf$1*2*40*4294967239*1*0**32*585e4cc4113bbd8ff4012dce92dd7df1e1216fb630b29cf5aeea10a820066c26*32*b1db56a883cab5a22dd5fc390618a0f8e16cab8af14e67ccba5f90837aac898b`

The interesting part is `0**`.

A solution could be to change [Line 158](https://github.com/openwall/john/blob/bleeding-jumbo/src/pdf_fmt_plug.c#L158) to `if (strlen(p) != 0 && !ishexlc(p))`.

**Comment by magnumripper** [comment]
Will be fixed by #5110
