### ISSUE TITLE
formatting a salted SHA-256 hash

### ISSUE THREAD

**Issue by vuccinett** [openwall/john#5121]
So i was using john to crack this password hash:
$SHA$cb62f38e01edfd97$36306c5d0ca620319bef125fe5439c8f827b0039c5696562533dd61c1762a004

but when i try to run the command: john --wordlist=wordlist.txt hash.txt it says: No password hashes loaded (see FAQ)

i already read the faq but it didn't help so im asking here why it is not working

i think that the password is encrypted like this but im not sure:

"$SHA$" + salt + "$" + sha256(sha256(password) + salt);

[build info.txt](https://github.com/openwall/john/files/8599642/build.info.txt)

im using win10 21H2

**Comment by solardiz** [comment]
@sheeeeesh123 We don't normally use GitHub issues to provide user support, but let's keep your issue open for a while in case someone does feel like providing the support here. Your other option is to bring this up for discussion on the john-users mailing list.

**Comment by solardiz** [comment]
Now answered here: https://www.openwall.com/lists/john-users/2022/05/02/4
