### ISSUE TITLE
zip2john output not accepted by john, in snap package of 1.9.0-jumbo-1

### ISSUE THREAD

**Issue by nekromoff** [openwall/john#5134]
Attach details about your OS and about john, including:
- The output of `./john --list=build-info`.
```
Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
Deploy: sandboxed as a Snap app
System-wide exec: /snap/john-the-ripper/current/run
System-wide home: /snap/john-the-ripper/current/run
Private home: ~/.john
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-non-omp
$JOHN is /snap/john-the-ripper/current/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.5.0
GNU libc version: 2.27 (loaded: 2.27)
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010100f
OpenSSL 1.1.1  11 Sep 2018
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
```
- The command line you are using.
```
john-the-ripper hash
```
before that hash extracted using:
```
john-the-ripper.zip2john ~/xxxx.zip > hash
```

**Comment by solardiz** [comment]
@nekromoff Can you show the output of `wc hash`? In general, you're likely to have better luck by building the latest JtR as found in this repo from source, and in fact we normally expect issues here to be opened against our latest code only.

@claudioandre-br Why is this reporting 1.9.0-jumbo-1 and not a newer git revision, I thought you updated the snap package since?

**Comment by nekromoff** [comment]
`$ wc hash`
```1   3 405 hash```

I am sorry about the version, I understand I am reporting regarding older release. This is the one I can get my hands on via snap. Otherwise I would have to compile. That I might do.

PS: I have tried installing the `edge` channel version:
```
$ snap install john-the-ripper --channel=latest/edge
john-the-ripper (edge) 1.9J1+eecd305X from Claudio André (claudioandre-br) installed
```

But the same result:
```
$ john-the-ripper --format=zip hash
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

Info:
```
Version: 1.9.0-jumbo-1+bleeding-eecd305 2022-05-10 13:54:49 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP OPENCL
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
Deploy: sandboxed as a Snap app
System-wide exec: /snap/john-the-ripper/current/run
System-wide home: /snap/john-the-ripper/current/run
Private home: ~/.john
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-non-omp
$JOHN is /snap/john-the-ripper/current/run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.5.0
GNU libc version: 2.27 (loaded: 2.27)
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010100f
OpenSSL 1.1.1  11 Sep 2018
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 1.396 us
Total physical host memory: 31522 MiB
Available physical host memory: 20391 MiB
Terminal locale string: C
Parsed terminal locale: UNDEF
```

**Comment by ghost** [comment]
@nekromoff you should run `john-the-ripper.zip2john ~/xxxx.zip > hash` again using the latest/edge `john`.

**Comment by ghost** [comment]
> @claudioandre-br Why is this reporting 1.9.0-jumbo-1 and not a newer git revision, I thought you updated the snap package since?

Because one must specify he/she needs the edge version. E.g.
```
sudo snap refresh --channel=edge john-the-ripper
# or, clean install
sudo snap install --channel=edge john-the-ripper
```

Otherwise, it is the stable/released version of john.

We can change that, I mean the default will be the bleeding version from git, but this is something that requires acknowledgment from the dev team, at least.
*****
IMO. No, a new release is a better approach.

**Comment by nekromoff** [comment]
> @nekromoff you should run `john-the-ripper.zip2john ~/xxxx.zip > hash` again using the latest/edge `john`.

I did. Same result, unfortunately.

**Comment by nekromoff** [comment]
> @nekromoff you should run `john-the-ripper.zip2john ~/xxxx.zip > hash` again using the latest/edge `john`.

Sorry, I tried again and now it works! Thanks!

So `Edge` works, `1.9.0-jumbo-1` does not.

**Comment by ghost** [comment]
> > @nekromoff you should run `john-the-ripper.zip2john ~/xxxx.zip > hash` again using the latest/edge `john`.
> 
> Sorry, I tried again and now it works! Thanks!
> 
> So `Edge` works, `1.9.0-jumbo-1` not.

As expected. Zip tools changed a lot since jumbo-1.

**Comment by nekromoff** [comment]
> > > @nekromoff you should run `john-the-ripper.zip2john ~/xxxx.zip > hash` again using the latest/edge `john`.
> > 
> > 
> > Sorry, I tried again and now it works! Thanks!
> > So `Edge` works, `1.9.0-jumbo-1` not.
> 
> As expected. Zip tools changed a lot since jumbo-1.

Unfortunately, other users might encounter this issue as well since the latest stable version is `1.9.0-jumbo-1` for Snap (or even older versions for standard deb packages).

**Comment by solardiz** [comment]
> We can change that, I mean the default will be the bleeding version from git, but this is something that requires acknowledgment from the dev team, at least.
> 
> IMO. No, a new release is a better approach.

Of course, it'd be better to have a new release, but while we don't I think it's better to change the default for snap to use edge - perhaps something that's easy for you to do now? Thanks!

**Comment by ghost** [comment]
It will be 52a9bedb58ecc2685518523549ff699a07d3abb9. 

All, please refrain from committing for the next few hours (unless it's a desired fix or something).

See also: https://github.com/openwall/john-packages/pull/21.

****

Done, we must warn/announce to users.

**Comment by solardiz** [comment]
> Done, we must warn/announce to users.

Thank you, @claudioandre-br! Do you have specific suggestions on that? Why "warn" the users - warn them of what?

**Comment by ghost** [comment]
> Why "warn" the users - warn them of what?

For multiple users, John will be updated automatically (and all behavior changes introduced in the last 3 years). I feel it's best to be, shall we say, transparent about it.

**Comment by solardiz** [comment]
> For multiple users, John will be updated automatically (and all behavior changes introduced in the last 3 years). I feel it's best to be, shall we say, transparent about it.

That makes sense. Will you post to john-users, @claudioandre-br? Thank you!
