### ISSUE TITLE
-show option misssing hash

### ISSUE THREAD

**Issue by e2002e** [openwall/john#5138]
The show options does output only the password but not the hash that encodes it.

John the Ripper 1.9.0-jumbo-1+bleeding-3075053a5 2022-05-15 20:25:33 +0200 OMP [linux-gnu 64-bit x86_64 AVX2 AC]

**Comment by magnumripper** [comment]
If you format your hashes like this:
```
username:hash
```
then the user name will be shown with `--show`.

See also #5074

**Comment by solardiz** [comment]
@e2002e What you describe is as [it was] intended. We can use #5074 to discuss possible changes in what to show.
