### ISSUE TITLE
gcc 11.3 warnings

### ISSUE THREAD

**Issue by ghost** [openwall/john#5151]
gcc (GCC) 11.3.0

```

In file included from subsets.c:25:
subsets.c: In function ‘do_subsets_crack’:
subsets.c:498:68: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  498 |                 if (strlen(req_charset) == 1 && isdigit(req_charset[0])) {
      |    
```

**Comment by solardiz** [comment]
Looks like an actual bug to me, not just a warning. glibc has workarounds for things like that, but some other libc's might not, and for chars with 8th bit set would index a ctype array out-of-bounds.
