### ISSUE TITLE
Document that dynamic_38 also works for Opencart

### ISSUE THREAD

**Issue by e2002e** [openwall/john#5164]
Hi, possible to add opencart format ?
Hashcat has them.

**Comment by solardiz** [comment]
Hi @e2002e. I thought this could be your opportunity to contribute a PR that we'd actually likely merge, but turns out the algorithm is so simple that it fits in our existing dynamic formats, so on CPU we already have it. Here's hashcat's test vector formatted so that it's cracked by JtR:

```
$dynamic_38$058c1c3773340c8563421e2b17e60eb7c916787e$827500576
```

We might want to make these changes for clarity:

```diff
+++ b/doc/DYNAMIC
@@ -162,7 +162,7 @@ dynamic_34  | md5(md4($p))            | No    |
 dynamic_35  | sha1(uc($u).:.$p)       | Yes   | ManGOS
 dynamic_36  | sha1($u.:.$p)           | Yes   | ManGOS2
 dynamic_37  | sha1(lc($u).$p)         | Yes   | SMF
-dynamic_38  | sha1($s.sha1($s.sha1($p)))| Yes | Wolt3BB
+dynamic_38  | sha1($s.sha1($s.sha1($p)))| Yes | Wolt3BB, OpenCart
 dynamic_39  | md5($s.pad_16($p))      | Yes   | Net-md5.  Long salt, passwords are 16 bytes, null padded for under 16 bytes
 dynamic_40  | sha1($s.pad_16($p))     | Yes   | Net-sha1.  Long salt, passwords are 16 bytes, null padded for under 16 bytes
 dynamic_50  | sha224($p)              | No    |
diff --git a/src/dynamic_preloads.c b/src/dynamic_preloads.c
index dcedf20..a0fba4a 100644
--- a/src/dynamic_preloads.c
+++ b/src/dynamic_preloads.c
@@ -113,7 +113,7 @@
 //dynamic_35 -->sha1(uc($u).:.$p) (ManGOS)
 //dynamic_36 -->sha1($u.:.$p) (ManGOS2)
 //dynamic_37 -->sha1(lc($u).$p) (SMF)
-//dynamic_38 -->sha1($s.sha1($s.sha1($p))) (Wolt3BB)
+//dynamic_38 -->sha1($s.sha1($s.sha1($p))) (Wolt3BB, OpenCart)
 //dynamic_39 -->md5($s.pad16($p))      (Net-md5 passed password, long salts)
 //dynamic_40 -->sha1($s.pad20($p))     (Net-sha1 passed password, long salts)
 
@@ -3315,7 +3315,7 @@ static DYNAMIC_Setup Setups[] =
        { "dynamic_35: sha1(uc($u).:.$p) (ManGOS)", _Funcs_35,_Preloads_35,_Const_35,     MGF_FLAT_BUFFERS|MGF_USERNAME_UPCASE, MGF_INPUT_20_BYTE, -6
        { "dynamic_36: sha1($u.:.$p) (ManGOS2)",    _Funcs_36,_Preloads_36,_Const_36,     MGF_FLAT_BUFFERS|MGF_USERNAME, MGF_INPUT_20_BYTE, -64, 110,
        { "dynamic_37: sha1(lc($u).$p) (SMF)",      _Funcs_37,_Preloads_37,_ConstDefault,MGF_FLAT_BUFFERS| MGF_USERNAME_LOCASE, MGF_INPUT_20_BYTE, -6
-       { "dynamic_38: sha1($s.sha1($s.sha1($p))) (Wolt3BB)",  _Funcs_38,_Preloads_38,_ConstDefault, MGF_SALTED|MGF_FLAT_BUFFERS, MGF_INPUT_20_BYTE, 
+       { "dynamic_38: sha1($s.sha1($s.sha1($p))) (Wolt3BB, OpenCart)",  _Funcs_38,_Preloads_38,_ConstDefault, MGF_SALTED|MGF_FLAT_BUFFERS, MGF_INPUT
        { "dynamic_39: md5($s.pad16($p)) (net-md5)",  _Funcs_39,_Preloads_39,_ConstDefault, MGF_SALTED|MGF_FLAT_BUFFERS, MGF_NO_FLAG, -230, 16, 16 },
        { "dynamic_40: sha1($s.pad20($p)) (net-sha1)",  _Funcs_40,_Preloads_40,_ConstDefault, MGF_SALTED|MGF_FLAT_BUFFERS, MGF_INPUT_20_BYTE, -230, 2
 
```

Also, even without a pre-defined dynamic format, this could be scripted on the command-line, as follows (tested, cracks the test vector above just as well):

```
--format=dynamic='sha1($s.sha1($s.sha1($p)))'
```

Somehow the command-line-scripted version runs significantly faster than the pre-defined one for me.

**Comment by e2002e** [comment]
Thanks I missed the point about dynamic formats and thought a lot of hashes weren't crackable with john.
Actually I have no experience with cuda so I'm not going to be the man of the situation.
I take the opportunity (since you recognize me) to encourage you to check my modifications to the mask on my fork:
There is mangling and alternative lengths. This would be better with a markov like thing I guess but that is still better (with due respect) than a straight bruteforce.

**Comment by solardiz** [comment]
The documentation update I suggested above hasn't been merged to our tree yet - re-opening.

**Comment by e2002e** [comment]
Is there not an easy modification to be done so that dynamic format support opencl via mask mode ?
Even the most expensive cpu is less powerfull than a middleware GPU.

**Comment by solardiz** [comment]
> Is there not an easy modification to be done so that dynamic format support opencl via mask mode ?

There is not - that is, this is not easy.

**Comment by e2002e** [comment]
Ok, thanks.
I must say that I had some hints about that when seeing the mask's placeholder generated on gpu took no part in my mangling.

**Comment by solardiz** [comment]
> Somehow the command-line-scripted version runs significantly faster than the pre-defined one for me.

BTW, this is one of the tests performed by `dyna-speed.sh`, which (along with `dyna-speed.pl`) we have only in `src`.
