### ISSUE TITLE
Explicitly reject VeraCrypt volumes until we support them

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5168]
I don't know if this is do-able - are VeraCrypt volumes distinguishable from TrueCrypt when we don't know the password yet? If they are, then we should implement such detection and rejection until we have support. If they are not, then let's just comment so in here and close this issue. See also #2012 and https://www.openwall.com/lists/john-users/2022/07/04/1

**Comment by magnumripper** [comment]
I expect them not to be distinguishable. As far as I know you can't even tell TrueCrypt from random data (perhaps with an exception for bootable volume), and that's intended.

**Comment by solardiz** [comment]
We currently assume this is not do-able. If someone figures out otherwise, we can reopen.
