### ISSUE TITLE
Community wiki link not working

### ISSUE THREAD

**Issue by Paippi** [openwall/john#5178]
Hey,

Tried looking into community wiki for more information but the link in https://www.openwall.com/ doesn't work. It directs to https://openwall.info/wiki/ which doesn't work. I've also tried https://www.openwall.com/wiki in case it was a domain name issue but that doesn't work either.

**Comment by ghost** [comment]
I think you are on your school or work network and access is restricted or blocked. It's working normally (now).

And I live on the other side of the world.

**Comment by Paippi** [comment]
Oh sorry about the hassle, it definetly seems to work on my phone so I guess it was blocked.
Thanks for the reply.
