### ISSUE TITLE
Misaligned pointer on s390

### ISSUE THREAD

**Issue by ghost** [openwall/john#5193]
This smells like (kind of) new stuff (but I'm not sure).

```
Testing: telegram [PBKDF2-SHA1/SHA512 32/64 AES]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
Testing: oldoffice, MS Office <= 2003 [MD5/SHA1 RC4 32/64]... (4xOMP) Warning: salt() returned misaligned pointer
PASS
```

```
Version: 1.9.0-jumbo-1+bleeding-3b8b28b 2022-09-04 15:21:50 +0200
Build: linux-gnu 64-bit s390x  AC OMP
```

All other archs are ok.

**Comment by magnumripper** [comment]
Both should be `sizeof(uint32_t)`. Telegram specifies `sizeof(uint64_t)` which is never correct, while oldOffice says `MEM_ALIGN_WORD`, only correct on 32-bit builds.

Both seem to be long standing bugs: The pointers often happen to end up aligned good enough anyway, so not triggering the warnings.
