### ISSUE TITLE
Missing function definition

### ISSUE THREAD

**Issue by e2002e** [openwall/john#5197]
Hi, from my fork I pulled the changes and now cannot compile with
john/src/cardano_fmt_plug.c:161: undefined reference to `ed25519ext_publickey'.

**Comment by ghost** [comment]
Probably some merge conflict happened and your fork is somehow not fully updated.

Upstream code compiles as you can see in CI history or just cloning and trying to compile yourself.

Please check if you have a file called src/ed25519-donna/ed25519-donna.c

**Comment by e2002e** [comment]
Hi claudio, I forgot to clean the project after coming from one of my branch.
I found no use for the algorithm we talked about some times ago, so I'm just keeping a fork with a branch 'rain',
It's a tweak on the mask, with two main points:
- Shuffling
- Multiple length
We can argue on a matter of scale: is it better to crack more short passwords or having collisions on longer lengths ?
In anyway, this was just some mean for me to keep myself busy at home.
What you should really consider though, seeing what hashcat does, is a full opencl markov mask and, if wanting this to be better than their, do multiple lengths in the meantime.
