### ISSUE TITLE
Shouldn't skip #include <altivec.h> in DES_bs_b.c at least on FreeBSD

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5203]
As reported by @danfe in https://github.com/openwall/john/commit/48382b86d1d1cbc121ed206392e35c8bf76a59c0#r86752702:

> Would it be possible to adjust, if not completely remove this guard? This breaks at least FreeBSD build, and perhaps others as well. Note that similar `#include <arm_neon.h>` earlier in this file is not guarded.

My reply there was:

> IIRC, at the time the AltiVec support was for just two platforms - macOS (first) and Linux (added later). If this guard of `#include <altivec.h>` was needed, then I guess we can replace the `#ifdef __linux__` with `#ifndef __APPLE__` for the same effect on old macOS. Ideally someone would test that, but please feel free to open a pull request with this change anyhow. Thank you!
> 
> It is also possible that the guard was never required, and I just didn't want to break some macOS (when adding Linux support), which I knew didn't need the `#include`. Maybe I never investigated this and put the guard in just in case.

**Comment by solardiz** [comment]
Here's the history behind this:

```diff
commit 25c84339fc532ef716a5c1522d920b53534bc582
Author: solar <solar>
Date:   Wed May 4 17:48:04 2005 +0000

    Don't #include <altivec.h> on Mac OS X since it was not present on older
    versions and -faltivec eliminates the need for it.

diff --git a/src/ppc-alti.c b/src/ppc-alti.c
index b07e355..5b25b29 100644
--- a/src/ppc-alti.c
+++ b/src/ppc-alti.c
@@ -7,7 +7,9 @@
 #include "common.h"
 #include "DES_bs.h"
 
+#ifdef __linux__
 #include <altivec.h>
+#endif
 
 typedef vector signed int altivec;
 
```

**Comment by solardiz** [comment]
@danfe or @pkubaj - would one of you give this a try on FreeBSD/ppc64 and send us a PR like this? Thanks!

It'd also help if anyone can try this on macOS / Mac OS X when building for ppc/ppc64 (can be done off an Intel Mac due to their support for cross-compilation and Rosetta, although building on a version old enough for the actual gear would be good).

```diff
+++ b/src/DES_bs_b.c
@@ -94,7 +94,7 @@ typedef uint32x2_t vtype;
        (dst) = vshr_n_u32((src), (shift))
 
 #elif defined(__ALTIVEC__) && DES_BS_DEPTH == 128
-#ifdef __linux__
+#ifndef __APPLE__
 #include <altivec.h>
 #endif
 
```

Edit: I've tested this patch on Linux/ppc64 with a POWER8 CPU, where it obviously made no difference.

**Comment by solardiz** [comment]
> @danfe or @pkubaj - would one of you give this a try on FreeBSD/ppc64 and send us a PR like this? Thanks!

Nevermind, I happened to work on other changes today, and will get a commit like this in while I'm at it. I wouldn't mind your testing, though.

**Comment by danfe** [comment]
Thanks, yes, that's the patch FreeBSD port had been using after our initial discussion and I don't think we've seen build breakages across all different arches our ports support.
