### ISSUE TITLE
Solarwinds Orion formats should lowercase the username

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#5208]
The shared `solarwinds_get_salt()` should lowercase the username for good measure. See
https://www.atredis.com/blog/2018/10/24/fun-with-the-solarwinds-orion-platform
and
https://github.com/hashcat/hashcat/issues/3491

**Comment by magnumripper** [comment]
We might have a worse bug in there as well (or not):

https://github.com/hashcat/hashcat/issues/3491#issuecomment-1290618977
>
> *BTW it's not perfectly clear from that article what happens with a username that is longer than 8... will it be used in full (and not padded), or even truncated to 8? The JtR format currently truncates it, but I wouldn't bet that is correct - might as well be a guess or a misunderstanding. Ideally we should have a test vector created by the real deal.*
>
> *EDIT: The [Ruby script mentioned in the article](https://github.com/atredispartners/solarwinds-orion-cryptography/blob/master/hash-password.rb) does not truncate it. But again, I wouldn't really trust anything other than a test vector generated by the actual SolarWinds Orion software.*

**Comment by msrspsr** [comment]
> The shared `solarwinds_get_salt()` should lowercase the username for good measure. See
> https://www.atredis.com/blog/2018/10/24/fun-with-the-solarwinds-orion-platform
> and
> [hashcat/hashcat#3491](https://github.com/hashcat/hashcat/issues/3491)

Would using ctype's tolower(3) be sufficient here?
