### ISSUE TITLE
Update hccap2john with changes in wpapcap2john

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#521]
The changes in f403aff1f6a8367e4bf9af17e49706d74b511670 should be "ported" to hccap2john too.

**Comment by claudioandre** [comment]
- if you need support as an end-user, ask for help on the mailing list john-users at lists.openwall.com (but first see the archives at http://www.openwall.com/lists/john-users/ and make sure you set a descriptive message **subject** when you post).

```
current/run$ ls -lah pcap*
-rwxr-xr-x 1 root root 56K mai  4 20:54 pcap2john.py

```
