### ISSUE TITLE
(solved) PBKDF2-HMAC-SHA512 opencl sourcecode is definitely working correctly? 

### ISSUE THREAD

**Issue by Lavshyak** [openwall/john#5214]
I just did not find where to ask, but maybe it does not work.

```
//defines from sourcecode
#define PLAINTEXT_LENGTH 110
#define PBKDF2_64_MAX_SALT_SIZE 107 /* 1 limb w/ 4 byte loop counter */

#define PASS_V_SIZE (((PLAINTEXT_LENGTH + 7) / 8) * sizeof(uint64_t))
#define SALT_V_SIZE (PBKDF2_64_MAX_SALT_SIZE+1+4+7)/8
```

```
//pass
auto passesCount = 1;
pass_t* h_passes = new pass_t[passesCount];
memset(&h_passes[0].v, 0, PASS_V_SIZE);
string passStr = "aaac";
memcpy(h_passes[0].v, (uint8_t *) passStr.c_str(), passStr.size());
h_passes[0].length = 8;//passStr.size(); // keep 64 bit aligned. length is overkill, but easiest way to stay aligned. (but does not matter: 8 or 4)

//salt
salt_t* h_salt = new salt_t();
memset(&h_salt->salt, 0, SALT_V_SIZE);
h_salt->rounds = 1;
string saltStr = "meme";

memcpy(h_salt->salt, (uint8_t *) saltStr.c_str(), saltStr.size());
memcpy(&h_salt->salt[saltStr.size()], "\x0\x0\x0\x1\x80", 5);
h_salt->length = saltStr.size()+5;

//state
state_t* h_states = new state_t[passesCount];
h_states[0].rounds = 0;
memset(h_states[0].W, 0, (8 * sizeof(cl_ulong)));
memset(h_states[0].hash, 0, (8 * sizeof(cl_ulong)));
memset(h_states[0].ipad, 0, (8 * sizeof(cl_ulong)));
memset(h_states[0].opad, 0, (8 * sizeof(cl_ulong)));
```

next i correctly run kernel from pbkdf2_hmac_sha512_kernel.cl
and extract the result
```
auto* h_statesResult = new state_t[passesCount];
shrCheckError(clEnqueueReadBuffer(commands, d_states, CL_TRUE, 0, sizeof(state_t)*passesCount, h_statesResult, 0, NULL, NULL));

size_t resultBytesSize = 64;
auto resultBytes = new uint8_t[resultBytesSize];
memcpy(resultBytes, h_statesResult[0].hash, resultBytesSize);
auto hex = Tools::BytesToHex(resultBytes, resultBytesSize);

cout << "OpenCL result: " << printChars(hex, 128);
```
but:
right result:    {682e6363c4fa65986f7676711547f1f5fe79994e25fbdb717161af54755eed5b520ce6b28252e9854cee7242feaf86454ec0490d
f155b2d5da646ede23fa51a5}
OpenCL result: {30d9336f284e0c7490ce53202091a345fa6d98f1dac194d994033866a03fab6252965e4a228a6af9ce5db2dac76b88ac87e9fece
e6cb9769aedc59689ab39a44}

Or maybe I'm writing data to structs (pass_t, salt_t) incorrectly?

**Comment by ukasz** [comment]
Looks like you're copying password into salt:
`memcpy(h_salt->salt, (uint8_t *) passStr.c_str(), passStr.size());`

**Comment by Lavshyak** [comment]
> Looks like you're copying password into salt: `memcpy(h_salt->salt, (uint8_t *) passStr.c_str(), passStr.size());`

it's true. i edited and the hash result is still wrong. maybe the byte order is different? I tried to convert small endians to big endians and and vice versa, but the result is still wrong.

**Comment by magnumripper** [comment]
There's nothing wrong with the kernel, you must be doing something wrong. You need to do a 64-bit endian-swap of the results read from the kernel:

Raw results:
```
9865fac463632e68 f5f147157176766f (...)
```

Swapped:
```
682e6363c4fa6598 6f7676711547f1f5 (...)
```

Here's how to format your sample hash for JtR:
```
$pbkdf2-hmac-sha512$1.6d656d65.682e6363c4fa65986f7676711547f1f5fe79994e25fbdb717161af54755eed5b520ce6b28252e9854cee7242feaf86454ec0490df155b2d5da646ede23fa51a5
```
The first `1` is number of iterations, next `6d656d65` is the "meme" salt encoded as hex. It cracks just fine.

**Comment by Lavshyak** [comment]
> You need to do a 64-bit endian-swap of the results read from the kernel:

`682e6363c4fa6598 6f7676711547f1f5 (...)` - it is right result.

my results:

unswapped:
`30d9336f284e0c74 90ce53202091a345 (...)`

swapped:
`740c4e286f33d930 45a391202053ce90 (...)`

**Comment by magnumripper** [comment]
Well this is no issue for us, so I'm closing. Feel free to post more to this issue despite that! Are you enqueueing buffer writes correctly prior to running the kernel? You could add a few `printf` to the kernel to verify correct data.

**Comment by Lavshyak** [comment]
https://pastebin.com/j2p1Miiu
https://pastebin.com/3ca59jFV
...and convert result to hex

I figured it out. if anyone has questions, this is how it works
