### ISSUE TITLE
hash problem

### ISSUE THREAD

**Issue by Darkrevengehack** [openwall/john#5215]
Hello, there is a big problem with the hash decryption in termux armv7l, and that is that the decryption does not appear when using the command ./john --format=raw-md5 --wordlist=$HOME/johndic.txt $HOME/md5.txt inside the john/run directory, the problem and the message without the decrypted hash is the following: Using default input encoding: UTF-8
 Loaded 1 password hash (Raw-MD5 [MD5 128/128 NEON 4x2])
 No password hashes left to crack (see FAQ)

Nota: The first time I used it it worked completely the 2nd time and the following times the 2nd time, John the ripper no longer worked for me to decrypt hash.

![Screenshot_20221119-193958](https://user-images.githubusercontent.com/103399387/202874300-9637dcc0-d5a1-4341-a72d-7ceb970be4d3.png)

**Comment by solardiz** [comment]
Please use `--show`. See also #5195.
