### ISSUE TITLE
Bitcoin wallet - Token length exception

### ISSUE THREAD

**Issue by coldner** [openwall/john#5218]
```
$ python bitcoin2john.py wallet.dat > hash.txt
```

```
$ cat hash.txt 
$bitcoin$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XX$XXXXXXXXXXXXXXXX$XXXXXX$X$XX$X$XX
```

```
$ hashcat -m 11300 hash.txt 
hashcat (v5.1.0) starting...

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
OpenCL Platform #1: NVIDIA Corporation
======================================
* Device #1: NVIDIA GeForce GTX 1050 Ti, 1009/4036 MB allocatable, 6MCU

Hashfile 'hash.txt' on line 1 ($bitco...XXXXXXXXXXXXXXX$XXXXXX$X$XX$X$XX): Token length exception
No hashes loaded.

Started: Fri Nov 25 14:05:22 2022
Stopped: Fri Nov 25 14:05:22 2022
```

**X** is used for hiding hexadecimal characters.
I'm using python 3.8.10.
bitcoin2john.py comes from 438daf5a4314db4cee33ec549ac8da270ba9eb4f
wallet.dat comes from Bitcoin Core 0.21.0

**Comment by ghost** [comment]
Did `bitcoin2john.py` print any warnings?. And paraphrasing magnum:

> Could you please test the same samples with JtR [...]?

_Originally posted by @magnumripper in https://github.com/openwall/john/issues/4799#issuecomment-916310484_

**Comment by solardiz** [comment]
> $bitcoin$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XX$XXXXXXXXXXXXXXXX$XXXXXX$X$XX$X$XX

The lengths of fields here look correct for the current version of `bitcoin2john.py`.

> hashcat (v5.1.0) starting...

That version of hashcat is way out of date, and quite possibly does not support our latest `bitcoin2john.py` "hashes". Please either use JtR itself like @claudioandre-br suggested or use a current version of hashcat.

This isn't an issue we need to track further, so I'll close, but please feel free to add further comments - such as to say that the "hash" is indeed getting loaded correctly by current JtR and current hashcat... or to let us know if it somehow does not (that would be unexpected by me).

**Comment by coldner** [comment]
It's working in hashcat 6.2.6
Thanks for help, and I'm sorry for wasting your time
