### ISSUE TITLE
Uninstall/remove

### ISSUE THREAD

**Issue by eva7280** [openwall/john#5224]
I get a laptop from other person and I found some files named John the Ripper, so I think is installed on the computer, Is a Windows 11 SO. Now I want to uninstall/remove it but I don't know how it works and how to do it. Please explain me step by step cause I don't have any knowledge about this.
Help me! Thank you very much.

**Comment by magnumripper** [comment]
Similar to https://github.com/hashcat/hashcat/issues/3578, you can typically just delete John's folder and anything in or below it.

**Comment by ghost** [comment]
Well, since this is not an issue, I'll close it. Anyway, feel free to add further comments if needed.

**Comment by Kingzyz** [comment]
Can u do a step to step on how to delete it i dont know how to

**Comment by ghost** [comment]
As magnum stated above:

> Similar to https://github.com/hashcat/hashcat/issues/3578, you can typically just delete John's folder and anything in or below it.

Using Windows File Explorer or GNOME Nautilus, GNOME Files, KDE Dolphin or your preferred tool, simply remove John's  top dir. I'm afraid there is no way to be more precise than this.

And it's that simple. There are no hidden file or system libraries elsewhere.
