### ISSUE TITLE
ReloadAtDone = Y appears to have no effect

### ISSUE THREAD

**Issue by snooppr** [openwall/john#5247]
Problem reproduction (sha1)
`$ printf 4276100015931808 | sha1sum | awk '{print $1}' > сберкарта`
`$ cat сберкарта`
>8f6278abe40ee2b014696548401804f918aaf82

`$ john --format=Raw-sha1 --mask=427610001593180?d сберкарта --fork=2`

![sha1](https://user-images.githubusercontent.com/61022210/224349576-f857d411-dcb8-4479-8c5e-02cac405c5a5.png)

The data is restored, but JtR releases only 1 core and работать/run/arbeiten to idle. Without the "--fork=2" option, there is no such behavior.

Fix: in moder "--fork=x" stop JtR after data recovery.

`$ john --list=build-info`
> Version: 1.9.0-jumbo-1+bleeding-bf2a9b4bd 2022-02-16 16:19:42 +0100
> Build: linux-gnu 64-bit x86_64 SSE4.1 AC OMP OPENCL
> SIMD: SSE4.1, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
> CPU tests: SSE4.1
> $JOHN is /home/user/Desktop/john/john/run/
> Format interface version: 14
> Max. number of reported tunable costs: 4
> Rec file version: REC4
> Charset file version: CHR3
> CHARSET_MIN: 1 (0x01)
> CHARSET_MAX: 255 (0xff)
> CHARSET_LENGTH: 24
> SALT_HASH_SIZE: 1048576
> SINGLE_IDX_MAX: 2147483648
> SINGLE_BUF_MAX: 4294967295
> Effective limit: Number of salts vs. SingleMaxBufferSize
> Max. Markov mode level: 400
> Max. Markov mode password length: 30
> gcc version: 9.2.1
> GNU libc version: 2.29 (loaded: 2.29)
> OpenCL headers version: 1.2
> Crypto library: OpenSSL
> OpenSSL library version: 01010104f	(loaded: 0101010bf)
> OpenSSL 1.1.1d  10 Sep 2019	(loaded: OpenSSL 1.1.1k  25 Mar 2021)
> GMP library version: 6.2.0
> File locking: fcntl()
> fseek(): fseek
> ftell(): ftell
> fopen(): fopen
> memmem(): System's
> times(2) sysconf(_SC_CLK_TCK) is 100
> Using times(2) for timers, resolution 10 ms
> HR timer: clock_gettime(), latency 1.816 us
> Total physical host memory: 3905 MiB
> Available physical host memory: 2514 MiB
> Terminal locale string: ru_RU.UTF-8
> Parsed terminal locale: UTF-8

**Comment by magnumripper** [comment]
Well it does, but only for less than a minute until a "pot sync" occurs, letting the other process know about the crack.

Here's how it ended up on my laptop:
```
$ rm -f ../run/john.pot && ../run/john -form:raw-sha1 -mask:427610?d -len=16 test -fork:2
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA1 [SHA1 256/256 AVX2 8x])
Node numbers 1-2 of 2 (fork)
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
4276100015931808 (?)     
2 1g 0:00:00:06 DONE (2023-03-10 16:23) 0.1457g/s 21916Kp/s 21916Kc/s 21916KC/s 
No remaining hashes after pot sync
1 0g 0:00:01:02 DONE (2023-03-10 16:24) 0g/s 21961Kp/s 21961Kc/s 21961KC/s 4276105891150530..4276103591150530
Waiting for 1 child to terminate
Use the "--show --format=Raw-SHA1" options to display all of the cracked passwords reliably
Session completed. 
```

**Comment by solardiz** [comment]
I was about to write the same as what @magnumripper wrote above, but then I noticed we have `ReloadAtDone = Y` by default - shouldn't it have helped?

```
# If set to Y, a session using --fork or MPI will signal to other nodes when
# it has written cracks to the pot file, so they will re-sync. Note that this
# may be delayed by buffers and the "Save" timer setting near top of this file.
ReloadAtCrack = N

# If set to Y, a session using --fork or MPI will signal to other nodes when
# it has cracked all hashes (there's nothing more to do!). This is ignored
# when ReloadAtCrack = Y because it's redundant.
ReloadAtDone = Y

# If set to Y, resync pot file when saving session. This does not involve any
# signalling, we just detect that someone else wrote to the pot file.
# This will sync with concurrent sessions even when not using --fork or MPI
# but it may be delayed by the "Save" timer setting near top of this file.
ReloadAtSave = Y
```

**Comment by magnumripper** [comment]
> I noticed we have `ReloadAtDone = Y` by default - shouldn't it have helped?

Maybe we should look into that... I'm pretty sure it works fine with MPI.

**Comment by ghost** [comment]
You noticed that @snooppr is using an old commit, right? Just to let you know, here JtR ends almost instantly after the first crack.

**[edited]**
- it takes approx 60s to sync.

**Comment by solardiz** [comment]
One year ago isn't that old, I don't recall us making related changes during the year. Also, I think magnum's test was with the latest, wasn't it, or did it not have `ReloadAtDone = Y`?

Maybe the issue here is the compile-time default for `ReloadAtDone` is `N`, and we could want to change it to match our default `john.conf`.

**Comment by solardiz** [comment]
@snooppr I hope that wasn't a valid card number you posted (or else we need to delete several comments now), but anyhow you could want to consider `--external=AppendLuhn`.

**Comment by magnumripper** [comment]
> Maybe the issue here is the compile-time default for `ReloadAtDone` is `N`, and we could want to change it to match our default `john.conf`.

This sounds plausible to me. Not much of any issue anyway, as ReloadAtSave would be 'Y' anyway so the session should end within a minute.

**Comment by solardiz** [comment]
@magnumripper Perhaps you can directly test/confirm that `john.conf` with `ReloadAtDone = Y` wasn't loaded in your test?

Indeed not much of an issue, but I think it's best for us to keep compile-time and default `john.conf` settings in sync, except when there's a specific good reason not to. So I think we should change the compile-time default here.

**Comment by snooppr** [comment]
> @snooppr I hope that wasn't a valid card number you posted (or else we need to delete several comments now), but anyhow you could want to consider `--external=AppendLuhn`.

This is my virtual card. I give good:
https://github.com/snooppr/snoop/blob/master/snoopbanner.py#L58

**Comment by magnumripper** [comment]
It turns out the `ReloadAtDone` sending of `SIGUSR2` happens in `john_wait()`. The problem is that function is only called by the parent process, and in this case it was the children who cracked it.

Using MPI, it works regardless which node cracked the last one.

**Comment by snooppr** [comment]
> You noticed that @snooppr is using an old commit, right? Just to let you know, here JtR ends almost instantly after the first crack.
> 
> **[edited]**
> 
>     * it takes approx 60s to sync.

Yes, JtR compilation date is in the log.

I will add that if you restore, for example, only one digit, then with "--fork=2" JtR releases resources instantly after a successful hack, and if you sort through ten digits, then I did not wait for the completion (perhaps a minute of the break time) and interrupted . I thought that the more difficult the hash cracking, the longer JtR does not release resources after cracking (in any case, this is the case if there is one digit and if there are 10 of them, and if another hash?).

**Comment by magnumripper** [comment]
> The problem is that function is only called by the parent process, and in this case it was the children who cracked it.

This fixes it (tested) and I can't think of any bad side effects of it.
```diff
diff --git a/src/john.c b/src/john.c
index 70ef8b4ce..37869dbf0 100644
--- a/src/john.c
+++ b/src/john.c
@@ -1849,8 +1849,18 @@ static void john_run(void)
 			mask_destroy();
 
 #if OS_FORK
-		if (options.fork && john_main_process)
-			john_wait();
+		if (options.fork) {
+			if (john_main_process)
+				john_wait();
+			else {
+				log_flush();
+
+				/* Tell our friends there is nothing more to crack! */
+				if (!database.password_count && !options.reload_at_crack &&
+				    cfg_get_bool(SECTION_OPTIONS, NULL, "ReloadAtDone", 0))
+					raise(SIGUSR2);
+			}
+		}
 #endif
 
 #if HAVE_MPI
```

**Comment by solardiz** [comment]
@magnumripper Great. I think we just need to clean this up to avoid code duplication. Perhaps have this logic inside a `john_wait_or_tell` function. Also, let's change the compile-time default. Thanks!

**Comment by magnumripper** [comment]
Using #5248
```
$ rm -f ../run/john.pot && ../run/john -form:raw-sha1 -mask:427610?d -len=16 test -fork:2
Using default input encoding: UTF-8
Loaded 1 password hash (Raw-SHA1 [SHA1 256/256 AVX2 8x])
Node numbers 1-2 of 2 (fork)
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
4276100015931808 (?)     
2 1g 0:00:00:06 DONE (2023-03-10 17:33) 0.1497g/s 22506Kp/s 22506Kc/s 22506KC/s 4276106115931808..4276108015931808
No remaining hashes after pot sync
1 0g 0:00:00:06 DONE (2023-03-10 17:33) 0g/s 22544Kp/s 22544Kc/s 22544KC/s 4276105716077901..4276103106077901
Waiting for 1 child to terminate
Use the "--show --format=Raw-SHA1" options to display all of the cracked passwords reliably
Session completed. 
```

**Comment by snooppr** [comment]
I updated JtR to test the patch. I confirm that everything is working correctly now, resources are returned immediately. Thank you, amazing work!

**Comment by solardiz** [comment]
@snooppr Thank you for reporting the problem and testing the fix!
