### ISSUE TITLE
Possible issue with large $RAR3$*1* hashes

### ISSUE THREAD

**Issue by blandyuk** [openwall/john#5258]
Hi all,

I've been having an issue with large $RAR3$\*1\* hashes, below is an example:

https://paste.blandyuk.co.uk/6MZkD2Se

They will not work in john for some reason, They are large, 400k in size. Any ideas?

Output from john (john-1.9.0-jumbo-1-win64):

Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

**Comment by ghost** [comment]
Could you share a (problematic) example RAR file for us to test? We cannot find out if there is a bug and where using just this information.

**Comment by blandyuk** [comment]
I just tried again and It's now working! My bad, please ignore.
