### ISSUE TITLE
"Enable fallback if binary name given" bugs

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5280]
While the idea behind #5270 is reasonable, the implementation we merged here needs more work. As it is, I think it introduced bugs.

In `x86-sse.h`, we have:

```c
#ifndef CPU_FALLBACK_BINARY_DEFAULT
#define CPU_FALLBACK_BINARY_DEFAULT     "john-non-sse"
#endif

#ifndef CPU_FALLBACK
#define CPU_FALLBACK                    0
#endif
#if !defined(CPU_FALLBACK_BINARY) && defined(CPU_FALLBACK_BINARY_DEFAULT)
#define CPU_FALLBACK_BINARY             CPU_FALLBACK_BINARY_DEFAULT
#endif
```

In `x86-mmx.h`, we have:

```c
#ifndef CPU_FALLBACK
#define CPU_FALLBACK                    0
#endif
#ifndef CPU_FALLBACK_BINARY
#define CPU_FALLBACK_BINARY             "john-non-mmx"
#endif
```

So building with these now, we'll end up with fallback enabled where that wasn't intended. We probably need to revise these.

Also, while the old behavior is documented in a comment in `params.h` and in some files under `doc/`, the new behavior is undocumented. Maybe that's fine as documenting both the old and the new behavior would be cryptic, and the old behavior is also still relevant when default filenames are used and not overridden.

**Comment by ghost** [comment]
I've tried it (at least using SSE2) and I can't find the bug. CI is also good for testing this.
When I tested it, it seems to me that it's some kind of dead code or something similar.

I have an IDE, I can see the above lines from `x86-sse.h` are enabled (they are in use by the compiler), but `john.c` and `listconf.c` don't have the fallback enabled/defined  (the new code are not going to be compiled). So, `CPU_FALLBACK_BINARY` is disabled somehow/somewhere.

Could you please try to specify a build where do you expect this to happen?

I took a look at the legacy makefile to no avail.

**Comment by ghost** [comment]
In order to skip Makefile.legacy weirdness, I think I can add something like this (BTW: is Makefile.legacy working for you guys? I cant' use it):

```diff
diff --git a/src/john.c b/src/john.c
index 1bbee9c11..5ce05b3d7 100644
--- a/src/john.c
+++ b/src/john.c
@@ -2016,7 +2016,7 @@ int main(int argc, char **argv)
 	}
 #endif
 
-#if CPU_FALLBACK || OMP_FALLBACK || defined(CPU_FALLBACK_BINARY) || defined(OMP_FALLBACK_BINARY)
+#if CPU_FALLBACK || OMP_FALLBACK || ((defined(CPU_FALLBACK_BINARY) || defined(OMP_FALLBACK_BINARY)) && defined(AC_BUILT))
 	/* Needed before CPU fallback */
 	path_init(argv);
 #endif
@@ -2061,7 +2061,7 @@ int main(int argc, char **argv)
 		return base64conv(argc, argv);
 	}
 
-#if !(CPU_FALLBACK || OMP_FALLBACK || defined(CPU_FALLBACK_BINARY) || defined(OMP_FALLBACK_BINARY))
+#if !(CPU_FALLBACK || OMP_FALLBACK || ((defined(CPU_FALLBACK_BINARY) || defined(OMP_FALLBACK_BINARY)) && defined(AC_BUILT)))
 	path_init(argv);
 #endif
 
diff --git a/src/listconf.c b/src/listconf.c
index d33e993f0..2763f0bd7 100644
--- a/src/listconf.c
+++ b/src/listconf.c
@@ -158,10 +158,10 @@ static void listconf_list_build_info(void)
 #if CPU_REQ
 	printf("CPU tests: %s\n", CPU_req_name);
 #endif
-#if CPU_FALLBACK || defined(CPU_FALLBACK_BINARY)
+#if CPU_FALLBACK || (defined(CPU_FALLBACK_BINARY) && defined(AC_BUILT))
 	puts("CPU fallback binary: " CPU_FALLBACK_BINARY);
 #endif
-#if OMP_FALLBACK || defined(OMP_FALLBACK_BINARY)
+#if OMP_FALLBACK || (defined(OMP_FALLBACK_BINARY) && defined(AC_BUILT))
 	puts("OMP fallback binary: " OMP_FALLBACK_BINARY);
 #endif
 	printf("$JOHN is %s\n", path_expand("$JOHN/"));
diff --git a/src/x86-sse.h b/src/x86-sse.h
index 09b060a66..2038afff8 100644
--- a/src/x86-sse.h
+++ b/src/x86-sse.h
@@ -203,6 +203,7 @@
 #endif
 #if !defined(CPU_FALLBACK_BINARY) && defined(CPU_FALLBACK_BINARY_DEFAULT)
 #define CPU_FALLBACK_BINARY		CPU_FALLBACK_BINARY_DEFAULT
+#warning build aqui
 #endif
 
 #ifdef _OPENMP
```

**Comment by solardiz** [comment]
Those `AC_BUILT` checks would over-complicate things. Let's not do that. Let's fix the two header files instead.

I am able to reproduce the problem by `make -sj32 -f Makefile.legacy linux-x86-64-32-sse2` (a weird make target for testing this from a 64-bit system).

> is Makefile.legacy working for you guys? I cant' use it

It works for me. Why can't you use it? Generally, it's tricky to test 32-bit from a 64-bit system because you then need 32-bit libraries. So I had to comment out the autodetection of GMP, and then applied the below fix (which I think we should merge):

```diff
diff --git a/src/clipperz_srp_fmt_plug.c b/src/clipperz_srp_fmt_plug.c
index e54a975..eb14229 100644
--- a/src/clipperz_srp_fmt_plug.c
+++ b/src/clipperz_srp_fmt_plug.c
@@ -53,10 +53,6 @@
 #include "autoconfig.h"
 #endif
 
-#if !AC_BUILT && !__MIC__
-#define HAVE_LIBGMP 1 /* legacy build uses libgmp by default, except for MIC */
-#endif
-
 #if HAVE_LIBGMP || HAVE_LIBCRYPTO /* we need one of these for bignum */
 
 #if FMT_EXTERNS_H
diff --git a/src/wow_srp_fmt_plug.c b/src/wow_srp_fmt_plug.c
index 5efeb99..a4244df 100644
--- a/src/wow_srp_fmt_plug.c
+++ b/src/wow_srp_fmt_plug.c
@@ -45,10 +45,6 @@
 #include "autoconfig.h"
 #endif
 
-#if !AC_BUILT && !__MIC__
-#define HAVE_LIBGMP 1 /* legacy build uses libgmp by default, except for MIC */
-#endif
-
 #if HAVE_LIBGMP || HAVE_LIBCRYPTO /* we need one of these for bignum */
 
 #if FMT_EXTERNS_H
```

I think those checks above were not needed because we do set `-DHAVE_LIBGMP` in `Makefile.legacy` when needed.
