### ISSUE TITLE
configure's gmake auto-detection is incomplete

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5287]
Some systems, notably Solaris, traditionally have their own `make`, and GNU make is then installed as `gmake`. Our generated configure script auto-detects that and suggests a build command accordingly, yet the generated `Makefile` has simply `MAKE=make` and thus fails. Worse, `Makefile` files in subdirectories also have this wrong line, and fail if the top-level one is fixed.

```
Configure finished.  Now "gmake -s clean && gmake -sj4" to compile.
-bash: make: command not found
solar@gcc-solaris10:~/john/src$ gmake -s clean && gmake -sj4
/bin/sh: make: not found
gmake: *** [Makefile:1751: clean] Error 1
```

Looks like out `configure.ac` puts the detected make program name into `use_make`, but a macro coming from autoconf (not in our tree) then does `SET_MAKE="MAKE=${MAKE-make}"`, so expects the program name in the `MAKE` shell variable. Maybe we can fix this issue by using the variable name `MAKE` instead of `use_make`?

**Comment by solardiz** [comment]
> Maybe we can fix this issue by using the variable name `MAKE` instead of `use_make`?

No, our setting of `use_make` is near the end of script, way after invocation of the macro that results in that `Makefile` line.

Curiously, this kind of works:

```diff
+++ b/src/configure.ac
@@ -331,6 +331,7 @@ dnl AC_PROG_EGREP Do not trust this one
 AC_PROG_SED
 dnl AC_PROG_CXX
 AX_CHECK_GNU_MAKE()
+export MAKE=$_cv_gnu_make_command
 AC_PROG_MAKE_SET
 AC_PROG_CPP
 AC_PROG_MKDIR_P
```

but not the way I had expected - it results in the `MAKE=` line no longer appearing at all.

I am lucky to have on this system same autoconf version 2.69 that we had used, so there are no unrelated changes. OTOH, the very issue here might be an autoconf macros bug, and if so maybe generating with a newer version would avoid it.

**Comment by solardiz** [comment]
> it results in the `MAKE=` line no longer appearing at all.

Actually, maybe this is right - what `AC_PROG_MAKE_SET` does is `checking whether ${MAKE-make} sets \$(MAKE)...`, and GNU's does and so does not need to be listed in each `Makefile`.

So I think we can use this patch as the fix for this issue, @magnumripper?

**Comment by solardiz** [comment]
Separately, I have to pass `gmake AR=/usr/ccs/bin/ar` on this Solaris 10 system. Older Solaris is weird about these things like that. Maybe we should auto-detect this path to `ar`. On a Solaris 11 system, there's `/usr/bin/ar`, so I don't have to pass any custom `AR`.

**Comment by solardiz** [comment]
> I have to pass `gmake AR=/usr/ccs/bin/ar` on this Solaris 10 system. Older Solaris is weird about these things like that. Maybe we should auto-detect this path to `ar`.

This is now implemented and tested on the Solaris 10.

**Comment by magnumripper** [comment]
> > it results in the `MAKE=` line no longer appearing at all.
> 
> Actually, maybe this is right - what `AC_PROG_MAKE_SET` does is `checking whether ${MAKE-make} sets \$(MAKE)...`, and GNU's does and so does not need to be listed in each `Makefile`.
> 
> So I think we can use this patch as the fix for this issue, @magnumripper?

Sounds fine to me
