### ISSUE TITLE
timeroast format fails on big-endian

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5289]
Solaris 10, sparc64, 32-bit `configure` build, OpenMP:

```
Testing: timeroast, SNTP-MS [MD4+MD5 32/32]... (3xOMP) FAILED (cmp_all(1))
```

Solaris 11, sparc64, 64-bit `Makefile.legacy` non-OpenMP build:

```
Testing: timeroast, SNTP-MS [MD4+MD5 32/64]... FAILED (cmp_all(1))
```

**Comment by ghost** [comment]
Dupe of #5244

**Comment by solardiz** [comment]
Oh, I'll close this one then. Let's discuss on #5244.
