### ISSUE TITLE
Update configure script

### ISSUE THREAD

**Issue by ghost** [openwall/john#5297]
I've seen odd things on recent platforms (not sure if an update will make things better).

Procedure to do so:
`
$ docker run --rm -v $(pwd):/host -w /host ubuntu:22.04 bash -c \
    "apt update && apt install -y autoconf && autoconf --version && cd src && autoupdate -f && autoreconf -i -f"
`

```
autoconf (GNU Autoconf) 2.71
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
```
The patch is huge:
[0001-autotools.txt](https://github.com/openwall/john/files/11344102/0001-autotools.txt)

****
**[Edited]**
To use 2.69 (Ubuntu adds some `rundir` that needed to be removed manually).
```
docker run --rm -v $(pwd):/host -w /host ubuntu:18.04 bash -c \
  "apt update && apt install -y autoconf sudo; autoconf --version && cd src && useradd -U -m JtR; sudo -u JtR autoreconf -i"
```

**Comment by magnumripper** [comment]
> I've seen odd things on recent platforms (not sure if an update will make things better).

I assume you mean odd things when running `./configure`. Any examples?

> The patch is huge: [0001-autotools.txt](https://github.com/openwall/john/files/11344102/0001-autotools.txt)

Yes - the last couple of times I changed configure.ac I ran autoreconf on some LTS Ubuntu, just to postpone this update but sooner or later we'll probably want to do this, and regression test the results at least a little...

**Comment by ghost** [comment]
Well, I'd say I've seen strange things happening on Solaris, M1, and RISCV64. Helping `configure` by adding a `--build=` or whatever solved all the weird stuff.

Anyway, the 2.69 tag is 11 years old. We should probably follow Fedora and Ubuntu and move on. Not now, but ...

**Comment by ghost** [comment]
Dupe of #4738
