### ISSUE TITLE
Derivate of dynamic_25 with UTF-16 Unicode support

### ISSUE THREAD

**Issue by danielmarschall** [openwall/john#5318]
In order to recover passwords built with the Unicode builds of the well-known installer InnoSetup, it is required that a hash is found that is constructed using `sha1(salt_binary || password_utf16)`.

For ANSI builds of InnoSetup, the scheme `sha1(salt_binary || password_ansi)` (which is `$dynamic_25$`) works fine.

My suggestion is that a new `$dynamic_xx$` is added to the main distribution, since I think it might be useful for many.
Thank you very much.

**Comment by solardiz** [comment]
@danielmarschall Can you please include at least one sample hash and its corresponding known password in here (and preferably two different ones)? Thanks!

**Comment by danielmarschall** [comment]
@solardiz Thank you for your quick reply!

Here are a few passwords I have extracted from a test setup:

```
ANSI InnoSetup with Seed 0011223344556677 and password "HelloWorld!"
$dynamic_25$4857b2e86f838bc2b2736f9f4926a92a70297fec$HEX$50617373776f7264436865636b486173680011223344556677

Unicode InnoSetup with Seed 0011223344556677 and password "HelloWorld!"
$innosetup_unicode$b6a8b8ba9078d05a0ff1e26043e3ef21278095bf$HEX$50617373776f7264436865636b486173680011223344556677
```

and second example:

```
ANSI InnoSetup with Seed AABBCCDDEEFF1122 and password "FooBar123"
$dynamic_25$381ea34f98d6d5179fc59bea7e324d149a198cdf$HEX$50617373776f7264436865636b48617368AABBCCDDEEFF1122

Unicode InnoSetup with Seed AABBCCDDEEFF1122 and password "FooBar123"
$innosetup_unicode$97305bbc2f279dcd243450387d7aba5239d85165$HEX$50617373776f7264436865636b48617368AABBCCDDEEFF1122

```

**Comment by kholia** [comment]
@danielmarschall I have updated and retested the https://github.com/kholia/inno2john utility program. I am hoping that it still works, and is able to extract hashes from all of your test setup files.

**Comment by danielmarschall** [comment]
@kholia It will only work for ANSI builds of InnoSetup,
because the ANSI setup encodes the input password "TEST" as 54 45 53 54 (ANSI),
and the Unicode setup encodes the input password "TEST" as 54 00 45 00 53 00 54 00 (UTF-16),
and JtR cannot brute-force UTF-16 encoded passwords yet.

**Comment by magnumripper** [comment]
Yay, welcome back @kholia, nice to hear from you!

**Comment by kholia** [comment]
@danielmarschall Thanks! Is there a way for us to distinguish between the EXE files generated by the ANSI InnoSetup versus those generated by the Unicode InnoSetup?

This will allow us to generate different hashes for the different types of EXEs and eventually crack them (with a modified format).

**Comment by danielmarschall** [comment]
@kholia 
inno2john detects the version and the unicode-flag and saves it in the "Version" field:
https://github.com/kholia/inno2john/blob/tweaks-v3/Setup/Inno/Interpret.pm#L115

In the Unicode EXE file, you can search for the string:
`Inno Setup Setup Data (6.1.0) (u)`
this will result in `...->{IsUnicode} = true` and `...->{Version} = "6100u"`

In the ANSI EXE file, you can search for the string:
`Inno Setup Setup Data (6.1.0)`
this will result in `...->{IsUnicode} = false` and `...->{Version} = "6100"`

Once JtR has the new format, we need to change inno2john ([here](https://github.com/kholia/inno2john/blob/tweaks-v3/Setup/Inno.pm#L128)) to output `$innosetup_unicode$` for Unicode hashes and `$dynamic_25$` for ANSI hashes.


By the way, @kholia what is your inno2john repository based on? I forked from PancakeSparkle/inno2john who forked from onitake/uninno. I wonder if your code base is newer than my one?

**Comment by kholia** [comment]
@danielmarschall Nice! This is exactly the information I was looking for.

> By the way, @kholia what is your inno2john repository based on?

I believe I am the original author of this `inno2john` hack. I made my repository private for some reason which I can't recall now. Recently, I freshly rebased my repository on top of `onitake/uninno`. So my fork should have the latest good stuff (TM).

It has been a while since I hacked on JtR stuff, so it may take me a while to get this stuff sorted out. Thanks for the help!

**Comment by kholia** [comment]
Here is a patch for inno2john:

```diff
diff --git a/Setup/Inno.pm b/Setup/Inno.pm
index a1d2487..bf92d38 100644
--- a/Setup/Inno.pm
+++ b/Setup/Inno.pm
@@ -125,7 +125,18 @@ sub FileLocations {
                my $setup0 = $self->Setup0();
                $self->{Input}->seek($setup0->{OffsetLocations}, Fcntl::SEEK_SET);
                my $struct = $self->{Interpreter}->StructReader($self->{Input});
-               print '$dynamic_25$';
+               # https://jrsoftware.org/ishelp/index.php?topic=unicode says,
+               # Prior to Inno Setup 6 two versions of Inno Setup were
+               # available: Non Unicode Inno Setup and Unicode Inno Setup.
+               # Starting with Inno Setup 6 there's only one version
+               # available: Unicode Inno Setup.
+               # // my $version = $bareversion . $self->{IsUnicode};
+               my $version = $self->{Interpreter}->Version;
+               my $tag = '$dynamic_25$';
+               if ($version =~ /u\z/) {
+                       $tag = "\$innosetup_unicode\$";
+               }
+               print $tag;
                my $h = unpack("H*", $setup0->{Header}->{PasswordHash});
                print $h, '$HEX$';
                print unpack("H*", "PasswordCheckHash");
```


```
$ ./inno2john.pl samples/mysetup.exe
Installer version: 6000u
Number of files: 2
$innosetup_unicode$d91d81ffd3ce0a64b4687391e2ce9b5055ee2680$HEX$50617373776f7264436865636b48617368a10cfd998d3442a8
```

```
$ ./inno2john.pl samples/Output/setup.exe       
Installer version: 5500
Number of files: 2
$dynamic_25$6d29001f8a5062d7b6f5b32b30a8cf64da6567e0$HEX$50617373776f7264436865636b48617368463243d92abc14cc
```

Does this work for you @danielmarschall? Thanks!

**Comment by danielmarschall** [comment]
@kholia Thank you very much.
Yes, I can verify that both of your hashes match the password "openwall".

**Comment by kholia** [comment]
Here is the  `dynamic` patch to support these newer hashes:

```diff
ff --git a/src/dynamic_preloads.c b/src/dynamic_preloads.c
index a0fba4a48..54adc68ad 100644
--- a/src/dynamic_preloads.c
+++ b/src/dynamic_preloads.c
@@ -850,6 +850,27 @@ MTL({"$dynamic_25$1b8cde0e3ecaed9abfa4deaf37addc7adcb8a932$123456789012345678901
        {NULL}
 };
 
+static DYNAMIC_primitive_funcp _Funcs_41[] =
+{
+       //MGF_INPUT_20_BYTE
+       //MGF_SALTED
+       //MGF_FLAT_BUFFERS
+       DynamicFunc__clean_input_kwik,
+       DynamicFunc__append_salt,
+       DynamicFunc__setmode_unicode,
+       DynamicFunc__append_keys,
+       DynamicFunc__SHA1_crypt_input1_to_output1_FINAL,
+       NULL
+};
+
+static struct fmt_tests _Preloads_41[] =
+{
+       // Inno Setup (Unicode version)
+       {"$dynamic_41$d91d81ffd3ce0a64b4687391e2ce9b5055ee2680$HEX$50617373776f7264436865636b48617368a10cfd998d3442a8", "openwall"},
+       {NULL}
+};
+
+
 // dynamic_26  raw-sha1
 static DYNAMIC_primitive_funcp _Funcs_26[] =
 {
@@ -3302,6 +3323,7 @@ static DYNAMIC_Setup Setups[] =
        { "dynamic_23: sha1(md5($p))",              _Funcs_23,_Preloads_23,_ConstDefault, MGF_NO_FLAG, MGF_INPUT_20_BYTE|MGF_KEYS_INPUT },
        { "dynamic_24: sha1($p.$s)",                _Funcs_24,_Preloads_24,_ConstDefault, MGF_FLAT_BUFFERS|MGF_SALTED, MGF_NO_FLAG|MGF_INPUT_20_BYTE, -64, 110, 110 },
        { "dynamic_25: sha1($s.$p)",                _Funcs_25,_Preloads_25,_ConstDefault, MGF_FLAT_BUFFERS|MGF_SALTED, MGF_NO_FLAG|MGF_INPUT_20_BYTE, -64, 110, 110 },
+       { "dynamic_41: sha1($s.utf16($p))",         _Funcs_41,_Preloads_41,_ConstDefault, MGF_UTF8|MGF_FLAT_BUFFERS|MGF_SALTED, MGF_NO_FLAG|MGF_INPUT_20_BYTE, -64, 110, 110 },
        { "dynamic_26: sha1($p) raw-sha1",          _Funcs_26,_Preloads_26,_ConstDefault, MGF_FLAT_BUFFERS, MGF_KEYS_INPUT|MGF_INPUT_20_BYTE },
 // Dyna 27/28 have been removed, Spring of 2013.  These dyna numbers should NOT be reused for any purpose.
 //dynamic_27 --> FreeBSD MD5
```

I am using the `$dynamic_41$` tag for these newer hashes now. I have updated `inno2john` accordingly.

**Comment by danielmarschall** [comment]
Thank you for this super fast implementation!
I also updated my fork  https://github.com/danielmarschall/inno2john/commit/83e2b80c5fba38523353a1b8765e6e3214560920

**Comment by kholia** [comment]
Nice 👍

I will cleanup the patch a bit, and open a PR soon.
