### ISSUE TITLE
Compiler not emiting inline code

### ISSUE THREAD

**Issue by ghost** [openwall/john#5326]
See #1093 and #5324.

As the original fix could be improved, some discussion might be needed. As stated in #5325:

> if we still have those changes/hacks, we'll need to revisit them.
****

This happens in ASAN + make check build only. Everything else is ok.
```
/usr/bin/ld: bt_hash_type_128.o: in function `calc_ht_idx_128':
/home/JtR/project/src/bt_hash_type_128.c:59: undefined reference to `add128'
/usr/bin/ld: bt_hash_type_192.o: in function `calc_ht_idx_192':
/home/JtR/project/src/bt_hash_type_192.c:61: undefined reference to `add192'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1442: ../run/john] Error 1
make: *** [Makefile:194: default] Error 2
```

**Comment by ghost** [comment]
This patch fixes the problem:

```diff
From 4dbc6d107432f7dc9d3fdea2af4800fd31b54344 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Claudio=20Andr=C3=A9?= <claudioandre.br@gmail.com>
Date: Sat, 24 Jun 2023 18:24:40 -0300
Subject: [PATCH] maint: force gcc to emit code for 'inline'

---
 src/bt_hash_type_128.c | 2 +-
 src/bt_hash_type_192.c | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/bt_hash_type_128.c b/src/bt_hash_type_128.c
index 1f92d352c..c1d5cb2c6 100644
--- a/src/bt_hash_type_128.c
+++ b/src/bt_hash_type_128.c
@@ -23,7 +23,7 @@ inline unsigned int modulo128_31b(bt_uint128_t a, unsigned int N, uint64_t shift
 	return (unsigned int)p;
 }
 
-inline bt_uint128_t add128(bt_uint128_t a, unsigned int b)
+extern inline bt_uint128_t add128(bt_uint128_t a, unsigned int b)
 {
 	bt_uint128_t result;
 	result.LO64 = a.LO64 + b;
diff --git a/src/bt_hash_type_192.c b/src/bt_hash_type_192.c
index b00ce6e60..f96b08e5d 100644
--- a/src/bt_hash_type_192.c
+++ b/src/bt_hash_type_192.c
@@ -24,7 +24,7 @@ inline unsigned int modulo192_31b(bt_uint192_t a, unsigned int N, uint64_t shift
 	return (unsigned int)p;
 }
 
-inline bt_uint192_t add192(bt_uint192_t a, unsigned int b)
+extern inline bt_uint192_t add192(bt_uint192_t a, unsigned int b)
 {
 	bt_uint192_t result;
 	result.LO = a.LO + b;
-- 
2.39.2


```

https://www.gnu.org/software/gnulib/manual/html_node/extern-inline.html

**Comment by solardiz** [comment]
My understanding is `extern inline` is for use in header files. What we're doing here is its misuse. We need to figure out and fix the real issue we have, for which this just happens to be a workaround, instead of using this workaround.

**Comment by solardiz** [comment]
The `extern inline` hack introduced in e2e868db3e153b3f959e119a51703d4afb99c624 was reverted later same day in 1c29d04c0aed3cddf4ea0c9263e9a29e854464c2 in favor of a different change, which was further revised in 3f4466ab91bb2c3dfd03082d07df5e1503b3f4a0 as discussed in #2743.

@claudioandre-br The problem you report here looks different to me, and perhaps is a compiler bug. While adding `extern` might happen to workaround it, would adding `static` instead possibly also do so? Those two functions appear to be used only once in the corresponding source files, so I suspect a compiler bug causes them to be both omitted (assuming they'd be inlined) and not actually inlined.

> This happens in ASAN + make check build only. Everything else is ok.

What versions of gcc are you seeing this with?

**Comment by ghost** [comment]
`static inline` also fixes the problem and makes sense (thinking about how the functions are used).

It is gcc (GCC) 13.1.1 20230511 (Red Hat 13.1.1-2)
