### ISSUE TITLE
Using default input encoding: UTF-8 No password hashes loaded (see FAQ)

### ISSUE THREAD

**Issue by aragon5956** [openwall/john#5329]
hello , 
whereas i  have hash in my txt , when i launch my command ` ./john --format=bcrypt  --wordlist=/media/alexandre/4TO/RockYou2021/RockYou2021.7z/rockyou2021.txt  /home/alexandre/Documents/hash.txt  --fork=12
,` i have this problem `Using default input encoding: UTF-8 No password hashes loaded (see FAQ)`
could you make an update please ?i use bcrypt
Cordially

**Comment by ghost** [comment]
Hello, it seems you don't have bcrypt hashes in the file. BTW, please, prefer to show in here the full output as seen in #5195.

Anyway, below are some reasons you see this message (from FAQ):
* All of the password hashes found in the file is already cracked.
* (if there other "hash types" in hash.txt file) If you're using the "--format" option, try dropping it.
* Your password hash or cipher type(s) might not be supported by John.
...

Have you tried?:
```
./john --show  /home/alexandre/Documents/hash.txt
./john --show --format=bcrypt /home/alexandre/Documents/hash.txt
```

**Comment by aragon5956** [comment]
the command `./john --show --format=bcrypt /home/alexandre/Documents/hash.txt` display 
`0 password hashes cracked, 0 left` but there is an hash in the file hash.txt
`

**Comment by ghost** [comment]
Please try:
```
./john --format=bcrypt -list=format-tests | cut -f3 > ~/alltests.in
```

And compare hashes in `~/alltests.in` with yours. 

Any change you are dealing with bcrypt seen in https://github.com/openwall/john/issues/4095?

**Comment by aragon5956** [comment]
my hash is not inside this file

**Comment by solardiz** [comment]
@alex5956 Chances are that you do not actually have a bcrypt hash in that file, or the file is not plain text. Please try omitting the `--format=bcrypt` option to let `john` figure out the hash type. Run simply this command:

```
./john /home/alexandre/Documents/hash.txt
```

and show us its full output.

If it still does not detect a hash in there, then either you do not have a supported hash in that file, or again the file is not in fact plain text.

Also, try this command:

```
file /home/alexandre/Documents/hash.txt
```

The `file` command, if installed on your system, will try and detect the file type.

What makes you think there's a bcrypt hash in that file? What operating system are you on? What version/build of John the Ripper do you use?

I'll close this issue now as it's not something we need to track (it's user support rather than issue with our project), but please proceed to add comments.

**Comment by aragon5956** [comment]
okok, 
`./john 
John the Ripper 1.9.0-jumbo-1+bleeding-2ad75ba45f 2023-06-25 21:48:00 +0200 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2022 by Solar Designer and others
Homepage: https://www.openwall.com/john/

Usage: john [OPTIONS] [PASSWORD-FILES]

Use --help to list all available options.
`
for this command 've :`john /home/alexandre/Documents/hash.txt
No password hashes loaded (see FAQ)
`
and for this command i 've:  `/home/alexandre/Documents/hash.txt: ASCII text`
my ubuntu is 22.x

**Comment by solardiz** [comment]
Thanks. So there's something unsupported inside that file you have - unsupported hash type, wrong file formatting, etc. I guess the hash itself is sensitive and not to be shared here, but maybe you can show e.g. the first 4 characters of that file and its size? -

```shell
head -c 4 /home/alexandre/Documents/hash.txt
wc /home/alexandre/Documents/hash.txt
```

**Comment by ghost** [comment]
> the command `./john --show --format=bcrypt /home/alexandre/Documents/hash.txt` display `0 password hashes cracked, 0 left` but there is an hash in the file hash.txt `

I'm afraid there is no valid and supported hash in your file.

**Comment by aragon5956** [comment]
ok thanks you !:)

**Comment by codi639** [comment]
Hey @solardiz,
I kinda have the same issue working with the Grafana sqlite base. The hash itself isn't sensitive, it's "admin" but I still would like to crack it using John:
59acf18b94d7eb0694c61e60ce44c110c7a683ac6a8f09580d626f90f4a242000746579358d77dd9e570e83fa24faa88a8a6
Running:
```
john hash_ad.txt 
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```
and the size of the file is:
```
wc hash_ad.txt                       
  1   1 101 hash_ad.txt
```
___
update:
I've found out that Grafana use PBKDF2 with SHA-256 + a random salt.
But I don't understand why John can't find it's a sha hash...

**Comment by solardiz** [comment]
@codi639 Not the same issue, so let's not be adding more comments on your different issue to here. If you like, you can open a new issue for yours, focusing on Grafana.
