### ISSUE TITLE
dmg-opencl gets stuck at 0% GPU utilization

### ISSUE THREAD

**Issue by ghost** [openwall/john#5340]
See #5338

Cracking a certain "hash" with dmg-opencl gets stuck at 0% GPU utilization, but cracking a same iteration count PBKDF2-HMAC-SHA1-opencl hash works.

Thinking out loud:
- AMD seems ok.
- `dmg_opencl` has this new code 050cfaf2bd3ac5637f8b6ba45ae050117f3768aa (It looks like it could "hurt" on crazy circumstances).[1][2]
- `PBKDF2-HMAC-SHA1-opencl` doesn't have.

[1] it is Windows
[2] `sha512crypt-opencl` can also be used to compare (Jumbo 1 x bleeding) performance. It also has the nvidia busy-waits patch.

We still need more information. Verbosity at most, other formats being tested, test using low values for lws and gws, ...

**Comment by solardiz** [comment]
> dmg_opencl has this new code https://github.com/openwall/john/commit/050cfaf2bd3ac5637f8b6ba45ae050117f3768aa

Good point, @claudioandre-br!

@blandyuk Can you please try changing `AvoidBusyWait = Y` to `AvoidBusyWait = N`? This is in `john.conf`, section `[Options:GPU]`. Thank you!

**Comment by blandyuk** [comment]
OK, it's working now! Full output with speed below. I presume this means you know what's happening now.

https://paste.blandyuk.co.uk/uzZCpXQR

Also set it off with all 3x RTX 2080 Ti GPUs and all working. Speeds are as expected.

**Comment by solardiz** [comment]
> I presume this means you know what's happening now.

We know what part of the code triggers the problem, but not what exactly the problem is, so we can't fix it easily other than by disabling this useful functionality.

**Comment by solardiz** [comment]
Related yet very different issue: #5048.

**Comment by solardiz** [comment]
Tried cracking a 181818 iteration count `dmg` "hash" (one of our test vectors) on an NVIDIA GPU under Linux - works fine - high GPU utilization (99%+), low CPU utilization (2% of one core).

@blandyuk Can you test if the problem is also seen with these other formats and features? -

```
$ fgrep -l WAIT_DONE *.c
opencl_7z_fmt_plug.c
opencl_bitcoin_fmt_plug.c
opencl_dmg_fmt_plug.c
opencl_hash_check_128_plug.c
opencl_hash_check_64_plug.c
opencl_keepass_fmt_plug.c
opencl_md5crypt_fmt_plug.c
opencl_office_fmt_plug.c
opencl_oldoffice_fmt_plug.c
opencl_pwsafe_fmt_plug.c
opencl_rar5_fmt_plug.c
opencl_rar_fmt_plug.c
opencl_sha1crypt_fmt_plug.c
opencl_sha256crypt_fmt_plug.c
opencl_sha512crypt_fmt_plug.c
opencl_tezos_fmt_plug.c
opencl_wpapsk_fmt_plug.c
opencl_zip_fmt_plug.c
```

where these two are not formats, but correspond to fast hashes' on-device mask mode (e.g., with `nt-opencl`):

```
opencl_hash_check_128_plug.c
opencl_hash_check_64_plug.c
```

I suggest you test with: `bitcoin-opencl`, `tezos-opencl`, `md5crypt-opencl`, and with `--mask` also nt-opencl.

You can obtain sample inputs for them (and others) by `--list=format-tests` (and extract first tab-delimited field from there).

**Comment by ghost** [comment]
To make your life easier, for sha512crypt you can use the attached file:

[sha512crypt.txt](https://github.com/openwall/john/files/12062479/sha512crypt.txt)

Both are instantaneous (under "normal" circumstances).
```
# Rounds 5000, will crack the empty password
john --format=opencl --cost=5000:5000 ~/bin/sha512crypt.txt --mask=''

# Rounds 391939, will crack one hash
john --format=opencl ~/bin/sha512crypt.txt --mask=amy?d?d
```

**Comment by blandyuk** [comment]
OK, run tests with a few algos below. All use john example hashes, except the second dmg-open one:

With [AvoidBusyWait = Y]
bcrypt-opencl = OK
Bitcoin-opencl = FAILED
md5crypt-opencl = OK
sha256crypt-opencl
dmg-opencl = FAILED (john example hash used)
dmg-opencl = FAILED (my hash used)
rar-opencl = OK, but slow to start. Noticed its slower speed than RAR5 below, that correct?
RAR5-opencl = OK
sha512crypt-opencl = OK

With [AvoidBusyWait = N]
bcrypt-opencl = OK
Bitcoin-opencl = OK
md5crypt-opencl = OK
sha256crypt-opencl
dmg-opencl = OK (john example hash used)
dmg-opencl = OK (my hash used)
rar-opencl = OK, but slow to start. Noticed its slower speed than RAR5 below, that correct?
RAR5-opencl = OK
sha512crypt-opencl = OK

Interesting that "Bitcoin-opencl" failed also.

**Comment by solardiz** [comment]
@blandyuk Thank you for testing.

Yes, `rar-opencl` can be slower than `rar5-opencl` for reasons unrelated to this issue, which you've essentially confirmed by seeing the same behavior with both settings.

Which particular hash did you use in `dmg-opencl = FAILED (john example hash used)`?

I suspect we're triggering some kind of overflow in timing-related code on Windows. This could be in our own interface to the timers or it could be inside Cygwin- or system-provided code.

One thing to test would be to see if Cygwin's `usleep` behaves as intended or not for relatively high durations.

Another would be to try lowering `HASH_LOOPS` in `opencl_bitcoin_fmt_plug.c` and `opencl_dmg_fmt_plug.c`, although the current values don't look too high to me.

@claudioandre-br You can try to reproduce the issue on your system by patching this check to `if (1)` (so the same code would also be enabled on AMD, even though it's unnecessary there):

```c
#ifndef __APPLE__
        if (gpu_nvidia(device_info[sequential_id])) {
                opencl_avoid_busy_wait[sequential_id] = cfg_get_bool(SECTION_OPTIONS, SUBSECTION_GPU,
                                                                     "AvoidBusyWait", 1);
```

I suggest focusing on `bitcoin-opencl` for further debugging (on systems where the issue is reproducible with that format) because it uses the waits in just one place, whereas `dmg-opencl` has them in 3 places.

**Comment by ghost** [comment]
It hurts. I opened two CMD shell windows and run interleaving executions: one with busy-wait on then one using busy-wait off:

``` diff
diff --git a/src/opencl_common.c b/src/opencl_common.c
index 02f4acd4f..737c0c50f 100644
--- a/src/opencl_common.c
+++ b/src/opencl_common.c
@@ -2402,7 +2402,7 @@ int opencl_prepare_dev(int sequential_id)
 		                                  "AlwaysShowWorksizes", 0);

 #ifndef __APPLE__
-	if (gpu_nvidia(device_info[sequential_id])) {
+	if (1) {
 		opencl_avoid_busy_wait[sequential_id] = cfg_get_bool(SECTION_OPTIONS, SUBSECTION_GPU,
 		                                                     "AvoidBusyWait", 1);
 		static int warned;
@@ -2411,7 +2411,7 @@ int opencl_prepare_dev(int sequential_id)
 		if (!opencl_avoid_busy_wait[sequential_id])
 		if (!warned) {
 			warned = 1;
-			log_event("- Busy-wait reduction %sabled", opencl_avoid_busy_wait[sequential_id] ? "en" : "dis");
+			printf("- Busy-wait reduction %sabled", (opencl_avoid_busy_wait[sequential_id] ? "en" : "dis"));
 		}
 	}
 #endif
``` 
****
# Patched binary

AvoidBusyWait=Y (CMD Shell Windows 1)
```powershell
C:\Temp\johntheripper>run\john --test --format=sha512crypt-opencl
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=64 GWS=32768 (512 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:    2654 c/s real, 704688 c/s virtual

C:\Temp\johntheripper>run\john --test --format=sha512crypt-opencl -verb=6
initUnicode(UNICODE, RAW/RAW)
RAW -> RAW -> RAW
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... Loaded 6 hashes with 4 different salts to test db from test vectors
TestDB LWS=7 GWS=49 (7 blocks) PASS,
Test mask: ?a?a?l?u?d?d?s
Calculating best GWS for LWS=64; max. 100 ms single kernel invocation.
Raw speed figures including buffer transfers:
Tuning for iteration count of 5000 and password length 7
xfer: 6.560 us [808864725780, 808868974900, 808863311300, 5000, 84], crypt: 59x4.249 ms, xfer back: 8.640 us, prep: 3.428 ms, pp: 39.840 us, final: 1.376 ms, var: 4.202 ms/3.292 ms
gws:      1024     4304 c/s    21520000 rounds/s  237.882 ms per crypt_all()!
xfer: 8.640 us [808927512620, 808934209900, 808915677700, 5000, 84], crypt: 59x6.697 ms, xfer back: 10.880 us, prep: 3.319 ms, pp: 53.280 us, final: 1.828 ms, var: 6.365 ms/6.487 ms
gws:      2048     5209 c/s    26045000 rounds/s  393.110 ms per crypt_all()+
xfer: 13.440 us [808990256880, 809000189200, 808979492500, 5000, 84], crypt: 59x9.932 ms, xfer back: 38.720 us, prep: 6.490 ms, pp: 97.280 us, final: 3.932 ms, var: 9.827 ms/9.411 ms
gws:      4096     6949 c/s    34745000 rounds/s  589.369 ms per crypt_all()+
xfer: 25.120 us [809068421380, 809086708900, 809055270400, 5000, 84], crypt: 59x18.287 ms, xfer back: 338.400 us, prep: 13.068 ms, pp: 233.280 us, final: 7.448 ms, var: 18.216 ms/17.543 ms
gws:      8192     7491 c/s    37455000 rounds/s     1.093 s per crypt_all()+
xfer: 41.120 us [809193020400, 809228497200, 809190815800, 5000, 84], crypt: 59x35.476 ms, xfer back: 577.280 us, prep: 25.210 ms, pp: 482.720 us, final: 10.422 ms, var: 35.535 ms/31.193 ms
gws:     16384     7935 c/s    39675000 rounds/s     2.064 s per crypt_all()+
xfer: 228.960 us [809396294120, 809465217000, 809392644200, 5000, 84], crypt: 59x68.922 ms, xfer back: 1.013 ms, prep: 45.111 ms, pp: 1.011 ms, final: 20.761 ms, var: 67.962 ms/61.389 ms
gws:     32768     8187 c/s    40935000 rounds/s     4.002 s per crypt_all()+
xfer: 715.680 us [809756953440, 809877413600, 809748265300, 5000, 84], crypt: 59x120.460 ms (exceeds 100 ms)
xfer: 41.440 us [810203946640, 810237762000, 810203296900, 5000, 84], crypt: 59x33.815 ms, xfer back: 566.400 us, prep: 23.161 ms, pp: 482.720 us, final: 9.459 ms, var: 33.033 ms/30.431 ms
gws:     16384     8342 c/s    41710000 rounds/s     1.963 s per crypt_all()!!
xfer: 24.960 us [810345729360, 810361150800, 810345378600, 5000, 84], crypt: 59x15.421 ms, xfer back: 475.040 us, prep: 8.369 ms, pp: 232 us, final: 5.165 ms, var: 17.240 ms/14.975 ms
gws:      8192     8538 c/s    42690000 rounds/s  959.450 ms per crypt_all()!!
xfer: 13.440 us [810430118500, 810438899300, 810429941500, 5000, 84], crypt: 59x8.780 ms, xfer back: 37.920 us, prep: 5.207 ms, pp: 95.680 us, final: 3.508 ms, var: 9.485 ms/9.677 ms
gws:      4096     7271 c/s    36355000 rounds/s  563.300 ms per crypt_all()-
Calculating best LWS for GWS=8192
Testing LWS=64 GWS=8192 ... 219.643 ms+
Testing LWS=128 GWS=8192 ... 225.120 ms
Testing LWS=256 GWS=8192 ... 222.200 ms
Calculating best GWS for LWS=64; max. 200 ms single kernel invocation.
Raw speed figures including buffer transfers:
xfer: 4.480 us [821190947280, 821195764400, 821190788700, 5000, 84], crypt: 59x4.817 ms, xfer back: 5.280 us, prep: 3.189 ms, pp: 36.960 us, final: 1.991 ms, var: 4.312 ms/5.019 ms
gws:       512     1790 c/s     8950000 rounds/s  285.974 ms per crypt_all()!
xfer: 6.240 us [821243716480, 821249336800, 821232174300, 5000, 84], crypt: 59x5.620 ms, xfer back: 7.520 us, prep: 4.268 ms, pp: 41.440 us, final: 2.355 ms, var: 4.675 ms/5.004 ms
gws:      1024     3300 c/s    16500000 rounds/s  310.260 ms per crypt_all()+
xfer: 8 us [821321890080, 821327762400, 821310788000, 5000, 84], crypt: 59x5.872 ms, xfer back: 11.040 us, prep: 4.418 ms, pp: 51.840 us, final: 2.242 ms, var: 5.455 ms/6.163 ms
gws:      2048     5789 c/s    28945000 rounds/s  353.770 ms per crypt_all()+
xfer: 13.440 us [821400067140, 821409798500, 821391706000, 5000, 84], crypt: 59x9.731 ms, xfer back: 38.560 us, prep: 7.132 ms, pp: 96 us, final: 4.483 ms, var: 10.303 ms/9.805 ms
gws:      4096     6783 c/s    33915000 rounds/s  603.840 ms per crypt_all()+
xfer: 26.560 us [821478236020, 821495700500, 821474663900, 5000, 84], crypt: 59x17.464 ms, xfer back: 308.160 us, prep: 12.077 ms, pp: 222.720 us, final: 8.012 ms, var: 17.826 ms/18.696 ms
gws:      8192     7502 c/s    37510000 rounds/s     1.091 s per crypt_all()+
xfer: 42.880 us [821618689080, 821656396600, 821616033000, 5000, 84], crypt: 59x37.707 ms, xfer back: 690.080 us, prep: 28.038 ms, pp: 538.880 us, final: 14.715 ms, var: 34.221 ms/34.232 ms
gws:     16384     7619 c/s    38095000 rounds/s     2.150 s per crypt_all()+
xfer: 230.080 us [821853486880, 821920172000, 821845450700, 5000, 84], crypt: 59x66.685 ms, xfer back: 806.080 us, prep: 53.418 ms, pp: 1.021 ms, final: 24.753 ms, var: 64.428 ms/65.780 ms
gws:     32768     8219 c/s    41095000 rounds/s     3.986 s per crypt_all()+
xfer: 290.400 us [822228786140, 822359390300, 822218450600, 5000, 84], crypt: 59x130.604 ms, xfer back: 2.148 ms, prep: 81.211 ms, pp: 2.133 ms, final: 40.655 ms, var: 120.213 ms/128.939 ms
gws:     65536     8554 c/s    42770000 rounds/s     7.661 s per crypt_all()+
xfer: 1.655 ms [822932400680, 823206266600, 822925611300, 5000, 84], crypt: 59x273.865 ms (exceeds 200 ms)
xfer: 85.120 us [823975301020, 824048078300, 823974821100, 5000, 84], crypt: 59x72.777 ms, xfer back: 1.080 ms, prep: 53.852 ms, pp: 1.053 ms, final: 22.803 ms, var: 73.406 ms/73.696 ms
gws:     32768     7377 c/s    36885000 rounds/s     4.441 s per crypt_all()-
TestDB LWS=64 GWS=65536 (1024 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:    2280 c/s real, 8738K c/s virtual
```
AvoidBusyWait=N (CMD Shell Windows 1)
```powershell
C:\Temp\johntheripper>run\john --test --format=sha512crypt-opencl
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
- Busy-wait reduction disabledBenchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=256 GWS=65536 (256 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:    7639 c/s real, 2730K c/s virtual
```

# john-dev binary

(CMD Shell Windows 2)
```powershell
C:\Users\claud\jul-10\JtR>run\john --test --format=sha512crypt-opencl
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=128 GWS=16384 (128 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:    7907 c/s real, 414784 c/s virtual

C:\Users\claud\jul-10\JtR>run\john --test --format=sha512crypt-opencl
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Benchmarking: sha512crypt-opencl, crypt(3) $6$ (rounds=5000) [SHA512 OpenCL]... LWS=128 GWS=16384 (128 blocks) DONE
Speed for cost 1 (iteration count) of 5000
Raw:    8410 c/s real, 224438 c/s virtual
```

**Comment by solardiz** [comment]
@claudioandre-br Can you test actual cracking with `bitcoin-opencl` and `dmg-opencl`? Does this reproduce the 0% GPU utilization problem?

**Comment by ghost** [comment]
dmg

No good native tools to see GPU utilization (it is Windows and AMD). I saw nothing interesting using Windows tools.

AvoidBusyWait=N
```
0g 0:00:02:24 0.00% 2/3 (ETA: 2023-09-25 23:50) 0g/s 876.4p/s 876.4c/s 876.4C/s lolhaha..kyle24
```

AvoidBusyWait=Y
```
0g 0:00:03:24 0.00% 2/3 (ETA: 2024-02-18 06:24) 0g/s 280.6p/s 280.6c/s 280.6C/s azert123..111275
```

**Comment by solardiz** [comment]
To summarize, force-enabling this `AvoidBusyWait` with AMD GPU on Windows results in a slowdown, but not in a complete halt like what @blandyuk observed with NVIDIA. Nevertheless, this does suggest the wait duration is somehow wrong.

@blandyuk When you're running with `AvoidBusyWait = N`, what CPU usage do you observe? This setting (when set to `Y`) is meant to lower CPU usage, but maybe that problem doesn't even exist with NVIDIA driver on Windows (it does on Linux)? If the original problem doesn't exist, then our fix would be simply to exclude this logic on Windows.

**Comment by solardiz** [comment]
I think let's currently limit the `AvoidBusyWait` feature to Linux, where we know it's needed and it works (except for the moderate slowdown for `nt-opencl` that @magnumripper observed on a multi-socket system). Longer-term, let's look into switching to the callback and signals approach that @magnumripper discovered and also experimented with - if it works, it should be more efficient anyway.

**Comment by blandyuk** [comment]
Sorry, not been able to test and check CPU util. I'll check when I get back.
