### ISSUE TITLE
ssh2john.py failing for Python v3.9

### ISSUE THREAD

**Issue by kkarnik22** [openwall/john#5354]
The script ssh2john.py fails for Python v3.9

**Command**
`ssh2john.py idrsa.id_rsa > output.txt`

**Error message** 
AttributeError: module 'base64' has no attribute 'decodestring'

**Reason**
decodestring() no longer exists from v3.9
Line 102 in the code: `data = base64.decodestring(data)`

**Resolution**
Replace decodestring() with b64decode()
`data = base64.b64decode(data)`

**Reference**
https://stackoverflow.com/questions/69187685/getting-attributeerror-module-base64-has-no-attribute-decodestring-error-wh

**Comment by ghost** [comment]
I'm afraid you are using an outdated version of John the Ripper. This is already fixed in this repository https://github.com/openwall/john/blob/c798c3f39215f6e08c67677eb9b79f65cfe08e40/run/ssh2john.py#L118.

Anyway, this is another reminder to make a new release.

Thanks.

**Comment by ghost** [comment]
See #4564 

Nothing new here that we need to track.

**Comment by kkarnik22** [comment]
Thanks for highlighting, sorry for the inconvenience!
