### ISSUE TITLE
Can John use multiple GPU's when using Bitlocker-opencl mode???

### ISSUE THREAD

**Issue by joao-vaz-martins** [openwall/john#5355]
My bitlocker disk is proteced with a TPM and a Bitlocker recovery Key

I used "FTK_Imager_4.7.1" to create the RAW dis image and after i used "bitlocker2john -i disk.img > hash.txt" and got two hashes $bitlocker$2$ and $bitlocker$3$.

In order to get recover the Bitlocker recovery key i used "John --format=bitlocker-opencl -mask=?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d target_$3$_hash > Bitlocker_Recovery_Key"

It will take a long time!!!
I'm using a computer with dual GPU in Crossfire. Is it possible to use both GPU's to speed up the process?????

**Comment by solardiz** [comment]
@joao-vaz-martins Yes, it is possible to use both GPUs, perhaps by giving the `--fork=2` option. However, in your case this does not matter - you're not going to recover this key in your lifetime on any number of GPUs. Such recovery is only realistic for mostly-known keys (e.g., if you wrote a recovery key down on paper, but a few digits are illegible), not for completely unknown ones.

**Comment by joao-vaz-martins** [comment]
@solardiz Thank you.
 I have a few mining rigs laying arround
would 10 GPU's would make any difference ?

or would it be possible to fork the work between different rigs??

Kind regards
Joao Vaz Martins

**Comment by joao-vaz-martins** [comment]
@solardiz 
Thank you, i can see now that the work has been shared with two devices.
The Hash file includes the bitlocker$2$ qne bilocker$3$ hashes.
When i kept both hashes in the text file "john" kept informing me that the process would produce false positives and continued the crack work.
In the example below I;m using the Bitlocker$3$ hash only to avoid false positives (removed the bilocker$2$ from the hash text file). Now the message about the possible false positives do not show (example below).

Althought the Hash text file includes the Salt and the MAK, do i need to add any parameter to use the MAK or John takes it from the hash text file when reads it?


F:\john-1.9.0-jumbo-1-win64\john-1.9.0-jumbo-1-win64\run>John --format=bitlocker-opencl -mask=?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d[-]?d?d?d?d?d?d --fork=2 d_hash_3.txt > d_key.txt
Using default input encoding: UTF-8
Node numbers 1-2 of 2 (fork)
Device 2: Pitcairn [AMD Radeon HD 7970M]
Device 1: Pitcairn [AMD Radeon HD 7970M]
Note: This format may emit false positives, so it will keep trying even after
finding a possible candidate.
Note: Minimum length forced to 8 by format
Press 'q' or Ctrl-C to abort, almost any other key for status
Device 1 probably invalid temp reading (-1°C).
Device 2 probably invalid temp reading (-1°C).
1 0g 0:00:16:27  0g/s 269.5p/s 269.5c/s 269.5C/s 192552-111111-111111-111111-111111-111111-111111-111111..704562-111111-111111-111111-111111-111111-111111-111111
2 0g 0:00:16:26  0g/s 269.9p/s 269.9c/s 269.9C/s 579564-080680-816968-911022-221101-111000-155111-114811..847516-080680-816968-911022-221101-111000-155111-114811
1 0g 0:00:17:01  0g/s 260.5p/s 260.5c/s 260.5C/s 192552-111111-111111-111111-111111-111111-111111-111111..704562-111111-111111-111111-111111-111111-111111-111111
2 0g 0:00:17:01  0g/s 260.6p/s 260.6c/s 260.6C/s 579564-080680-816968-911022-221101-111000-155111-114811..847516-080680-816968-911022-221101-111000-155111-114811
1 0g 0:00:20:53  0g/s 261.4p/s 261.4c/s 261.4C/s 165423-111111-111111-111111-111111-111111-111111-111111..780693-111111-111111-111111-111111-111111-111111-111111
2 0g 0:00:20:52  0g/s 278.0p/s 278.0c/s 278.0C/s 509656-080680-816968-911022-221101-111000-155111-114811..876666-080680-816968-911022-221101-111000-155111-114811

**Comment by solardiz** [comment]
@joao-vaz-martins No, like I said the number of GPUs doesn't matter. Even a billion. Your other questions here are similarly irrelevant. You're completely out of luck with this approach no matter what you do. See also: https://www.openwall.com/lists/john-users/2022/07/15/2
