### ISSUE TITLE
bitlocker2john: VMK not encrypted with AES-CCM

### ISSUE THREAD

**Issue by s2mael** [openwall/john#5362]
Hello, 

I'm trying find a hash from disk but I get a error:

![Screenshot_1](https://github.com/openwall/john/assets/140153594/fbabfd8f-876c-43e4-93a5-0ec859a68aba)

[dev_sda2_first_256k.zip](https://github.com/openwall/john/files/12749496/dev_sda2_first_256k.zip)

**Comment by solardiz** [comment]
Hi @s2mael. What version/build of JtR are you getting this with?

Overall, it looks to me that `bitlocker2john` doesn't find what it supports, and instead finds headers that look very much like what it supports but are not quite it. Note how the reported `Salt` values do not look random, so something is probably wrong already by that point. OTOH, it could be helpful to compare this against output of a successful run (against another disk image).

Thank you for attaching the first 256k, but unfortunately these almost-supported headers are way outside of that range. You can possibly provide an excerpt starting at 0xc1880000:

```
dd if=/dev/sda2 bs=64k skip=49544 count=4 of=0xc1880000_256k.bin
```

**Comment by solardiz** [comment]
@s2mael Also, I notice you're running `bitlocker2john` on Windows against a 1.5 TB image file, right? But then the attached filename suggests you also access the disk on Linux? I suggest you run the whole thing on Linux.

Also, going through 1.5 TB of data should be taking a very long while... but I guess for you the search is aborting somewhere within the first 4 GiB because of a bug we had in older versions, fixed in #5099.

How long does the search take for you?

**Comment by s2mael** [comment]
@solardiz You're right, I run it on Windows, I also runed Linux, but it was version 7 of bitlocker2john, I'll try to run version 8 next week and let you know, also attach the file.  About Windows, it takes a couple of hours, maybe 4-5 or more.

**Comment by s2mael** [comment]
@solardiz You're right, I run it on Windows, I also runed Linux, but it was version 7 of bitlocker2john, I'll try to run version 8 next week and let you know. About Windows, it takes a couple of hours, maybe 4-5 or more.

**Comment by solardiz** [comment]
> it was version 7 of bitlocker2john, I'll try to run version 8 next week

This makes no sense to me - there isn't a `bitlocker2john` version number at all. I asked you about JtR version numbers and specific builds of it that you use (as you get `bitlocker2john` from a JtR tree, right?)

Maybe you're confused by `Version: 8` in your screenshot. That's part of data coming from your disk image, not related to the version of code that you run.

**Comment by s2mael** [comment]
John the Ripper 1.9.0-jumbo-1+bleeding-c798c3f392 I hope this is what you asking for, I get it from there
https://github.com/openwall/john-packages/releases/tag/jumbo-dev

**Comment by s2mael** [comment]
[0x1880000_256b.zip](https://github.com/openwall/john/files/12788375/0x1880000_256b.zip)

**Comment by solardiz** [comment]
> 0x1880000_256b.zip

I assume this actually corresponds to `0xc1880000_256k.bin` that I requested, and is missing the `c` from the filename inadvertently. It certainly looks that way, matching the screenshot:

```
$ ./bitlocker2john -i 0x1880000_256b.bin 
Encrypted device 0x1880000_256b.bin opened, size 0MB

Signature found at 0x0
Version: 2 (Windows 7 or later)

VMK entry found at 0xb7

VMK encrypted with Recovery Password found at 0xd8
Salt: 73006b00500061007300730077006f00
Searching AES-CCM from 0xf4
Trying offset 0x187....
Error: VMK not encrypted with AES-CCM (0x48,0x4c)
Salt: 0000ac000000030001000010000086ac
Searching AES-CCM from 0x108
Trying offset 0x19b....
Error: VMK not encrypted with AES-CCM (0x83,0x61)

Signature found at 0x10000
Version: 2 (Windows 7 or later)

VMK entry found at 0x100b7

VMK encrypted with Recovery Password found at 0x100d8
Salt: 73006b00500061007300730077006f00
Searching AES-CCM from 0x100f4
Trying offset 0x10187....
Error: VMK not encrypted with AES-CCM (0x48,0x4c)
Salt: 0000ac000000030001000010000086ac
Searching AES-CCM from 0x10108
Trying offset 0x1019b....
Error: VMK not encrypted with AES-CCM (0x83,0x61)

Signature found at 0x20000
Version: 2 (Windows 7 or later)

VMK entry found at 0x200b7

VMK encrypted with Recovery Password found at 0x200d8
Salt: 73006b00500061007300730077006f00
Searching AES-CCM from 0x200f4
Trying offset 0x20187....
Error: VMK not encrypted with AES-CCM (0x48,0x4c)
Salt: 0000ac000000030001000010000086ac
Searching AES-CCM from 0x20108
Trying offset 0x2019b....
Error: VMK not encrypted with AES-CCM (0x83,0x61)
Error while extracting data: No signature found!
```

So we should be able to use it to try and figure out the issue, thanks!

**Comment by solardiz** [comment]
Some observations so far:

1. What the code thinks are salts indeed are not - some are even part of UCS2 strings.
2. The code and its logic are pretty awful, fixing this is not trivial.
3. The offsets seen in `VMK entry found at ` are off by one, actual ones are one byte earlier (so e.g. 0xb7 should be 0xb6).
4. The code looks for VMK entries by signature `0x02, 0x00, 0x08, 0x00`. There are at least 6 instances of that in the file (two per top-level signature `-FVE-FS-`), but the code only finds 3 (one per top-level signature, due to the code's logic).
5. Forcing it to find more (by commenting out a `match = 0;` line, which I think isn't a proper long-term fix since it'd misbehave on a full disk image) results in the output below, which does not bring us any closer to obtaining anything usable for attack with our existing support in JtR, but may be preferable anyway (if we come up with a proper code fix to obtain it). Apparently, the extra entries are, at least in this case, for "Startup Key".

```
Encrypted device 0x1880000_256b.bin opened, size 0MB

Signature found at 0x0
Version: 2 (Windows 7 or later)

VMK entry found at 0xb6

VMK encrypted with Recovery Password found at 0xd8
Salt: 73006b00500061007300730077006f00
Searching AES-CCM from 0xf4
Trying offset 0x187....
Error: VMK not encrypted with AES-CCM (0x48,0x4c)
Salt: 0000ac000000030001000010000086ac
Searching AES-CCM from 0x108
Trying offset 0x19b....
Error: VMK not encrypted with AES-CCM (0x83,0x61)

VMK entry found at 0x248
VMK encrypted with Startup Key...not supported! (0x26a)

Signature found at 0x10000
Version: 2 (Windows 7 or later)

VMK entry found at 0x100b6

VMK encrypted with Recovery Password found at 0x100d8
Salt: 73006b00500061007300730077006f00
Searching AES-CCM from 0x100f4
Trying offset 0x10187....
Error: VMK not encrypted with AES-CCM (0x48,0x4c)
Salt: 0000ac000000030001000010000086ac
Searching AES-CCM from 0x10108
Trying offset 0x1019b....
Error: VMK not encrypted with AES-CCM (0x83,0x61)

VMK entry found at 0x10248
VMK encrypted with Startup Key...not supported! (0x1026a)

Signature found at 0x20000
Version: 2 (Windows 7 or later)

VMK entry found at 0x200b6

VMK encrypted with Recovery Password found at 0x200d8
Salt: 73006b00500061007300730077006f00
Searching AES-CCM from 0x200f4
Trying offset 0x20187....
Error: VMK not encrypted with AES-CCM (0x48,0x4c)
Salt: 0000ac000000030001000010000086ac
Searching AES-CCM from 0x20108
Trying offset 0x2019b....
Error: VMK not encrypted with AES-CCM (0x83,0x61)

VMK entry found at 0x20248
VMK encrypted with Startup Key...not supported! (0x2026a)
Error while extracting data: No signature found!
```

**Comment by s2mael** [comment]
Do I understand you correctly, that unfortunately no solution for this at the moment? Is it possible that "Startup Key.match = 0" is due to the fact that the bitlocker itself was made incorrectly and the key was created incorrectly, cuz the bitlocker made by script. I want to say that maybe the problem is not in the code but in the bitlocker

**Comment by solardiz** [comment]
> Do I understand you correctly, that unfortunately no solution for this at the moment?

Yes. At least as a volunteer project, I think this won't advance further now. This code is no longer maintained by the person who wrote it, and it'd take significant effort for someone else to get into it now - reading of BitLocker specs, rewriting code, etc.

> Is it possible that "Startup Key.match = 0"

This is confusing different things, so a direct answer would make no sense.

> the bitlocker made by script. I want to say that maybe the problem is not in the code but in the bitlocker

This is possible. Did this BitLocker setup ever work?

**Comment by s2mael** [comment]
Yes, Bitlocker setup script works, this happened 1 time out of 1000 computers

**Comment by s2mael** [comment]
> Yes. At least as a volunteer project, I think this won't advance further now. This code is no longer maintained by the person who wrote it, and it'd take significant effort for someone else to get into it now - reading of BitLocker specs, rewriting code, etc.
> 
I got you, Thank you so much.

**Comment by solardiz** [comment]
Is there even a human-chosen or partially-lost password involved? (If not, this isn't a problem to be solved by JtR.)

> Yes, Bitlocker setup script works, this happened 1 time out of 1000 computers

So what exactly did happen on this 1 computer? Did the BitLocker install work at first, then fail? Did the password work at first, then was forgotten? Or is it unknown whether this BitLocker install ever worked at all?

Also, if you have 1000 computers with such configuration, perhaps you can try `bitlocker2john` on another one of those as well? On one where you know BitLocker works and where you know what the correct password is?

**Comment by s2mael** [comment]
> Is there even a human-chosen or partially-lost password involved? (If not, this isn't a problem to be solved by JtR.)

Nope, but I thought that using JtR I could find the hash of recovery password(

> So what exactly did happen on this 1 computer? Did the BitLocker install work at first, then fail? Did the password work at first, then was forgotten? Or is it unknown whether this BitLocker install ever worked at all?

Unfortunately, we didn't know out exactly what happened, we only know that after encrypting the disk it became locked, and the key that was supposed to be sent to the domain controller did not arrive

> Also, if you have 1000 computers with such configuration, perhaps you can try `bitlocker2john` on another one of those as well? On one where you know BitLocker works and where you know what the correct password is?

Same result

**Comment by solardiz** [comment]
> Nope, but I thought that using JtR I could find the hash of recovery password(

Where would the recovery password have come from, and why would it be realistically crackable?

So I assume this is confusion about what is potentially crackable, and what JtR can potentially help with. In this case, it looks like it couldn't help anyway, even if everything worked perfectly.

**Comment by s2mael** [comment]
Got it

**Comment by s2mael** [comment]
Thanks a lot
