### ISSUE TITLE
zip2john on AES Encrypted Zip prints error to stdout even when producing a valid hash.

### ISSUE THREAD

**Issue by freeman412** [openwall/john#5366]
### Checklist ###
- :1st_place_medal: I've read and understood these instructions;
  - This is not a support forum, it's a bug tracker. For questions and support, review postings on the [john-users mailing list](https://www.openwall.com/lists/john-users/).
- :thumbsup: I've tested using latest bleeding version from this repository.
  - Be clear about your environment and what you are doing. Share a sample hash or file that can be used to reproduce.
- :confused: I'm confused and I need guidance.
  - Please, read the instructions at https://www.openwall.com/john/#lists, then join the list before posting.

### IMPORTANT ###
We expect only reports of issues with the latest revision found in this GitHub repository. We do not expect in here, and have little use for, reports of issues only seen in a release or in a distro package.

Attach details about your OS and about john, including:
- The output of `./john --list=build-info`.
- The command line you are using.

**Comment by freeman412** [comment]
I confirmed that zip2john.exe does report that the file is not encrypted, or has a non-handled compression, but it in fact does print the correct extracted hash on AES256 zip files to stdout, while printing the error to stderr. Line 781 in zip2john.c should not run if it successfully extracted hash, but is getting executed. There is not an error for ZipCrypto files.

		if (p->cmptype != 0 && p->cmptype != 8) {
			fprintf(stderr, "%s/%s is not encrypted, or stored with non-handled compression type=%"PRIu16"\n",
			        zfp->fname, p->file_name, p->cmptype);
			return 0;
		}
[AES256.zip](https://github.com/openwall/john/files/12832887/AES256.zip)
[AES256.zip.hash.txt](https://github.com/openwall/john/files/12832894/AES256.zip.hash.txt)

I have attached examples file that replicates the issue. Since this is old and marked invalid, I will open a new related issue. Example password is "password".

Command:
→ ~\source\test_files› .\john-1.9.0-jumbo-1-win64\run\zip2john.exe .\AES256.zip
AES256.zip/test.txt:$zip2$*0*3*0*8174cd8662c48b9cbd09b7642b84a952*d138*4*22f4010b*a3f17bd07597155ec409*$/zip2$:test.txt:AES256.zip:.\AES256.zip
ver 5.1 .\AES256.zip/test.txt is not encrypted, or stored with non-handled compression type

→ ~\source\test_files\john-1.9.0-jumbo-1-win64\run› .\john.exe --list=build-info
Version: 1.9.0-jumbo-1
Build: cygwin 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-xop
OMP fallback binary: john-avx2-non-omp
$JOHN is /run/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 7.4.0
OpenCL headers version: 2.2
Crypto library: OpenSSL
OpenSSL library version: 01010102f
OpenSSL 1.1.1b  26 Feb 2019
GMP library version: 6.1.2
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

**Comment by ghost** [comment]
I'm afraid you are using an outdated version of the software (circa 1600 days old). This is already fixed in the code available in this repository, as you can see below.

No warnings at all:
```powershell
[pwd]\rolling-2310>run\zip2john.exe ..\AES256.zip
AES256.zip/test.txt:$zip2$*0*3*0*8174cd8662c48b9cbd09b7642b84a952*d138*4*22f4010b*a3f17bd07597155ec409*$/zip2$:test.txt:AES256.zip:..\AES256.zip

# cd ..

[pwd]>rolling-2310\run\zip2john.exe .\AES256.zip
AES256.zip/test.txt:$zip2$*0*3*0*8174cd8662c48b9cbd09b7642b84a952*d138*4*22f4010b*a3f17bd07597155ec409*$/zip2$:test.txt:AES256.zip:.\AES256.zip
```

BTW: a link for download a new version is available in the readme file of this repository.
```
C:\Temp\rolling-2310>run\john --list=build-info
Version: 1.9.0-jumbo-1+bleeding-39db7dd63e 2023-09-20 17:02:33 -0300
Build: cygwin 64-bit x86_64 AVX2 AC OMP OPENCL
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-avx-omp
OMP fallback binary: john-avx2
$JOHN is run/
[...]
```

**Comment by solardiz** [comment]
@freeman412 Thank you for reporting this to us anyway. You clearly tried to do your best, and please don't feel discouraged. We understand it's a problem that our latest release is so out of date.

> BTW: a link for download a new version is available in the readme file of this repository.

Claudio refers to the "Download Windows Build" badge, which currently points to:

https://github.com/openwall/john-packages/releases/tag/jumbo-dev

Most of us working on this project just `git clone` this repo and build from source on Linux, but we understand you're using a Windows build. That's fine.

**Comment by freeman412** [comment]
Thank you guys for such great and detailed answers. I am silly for assuming the bleeding was included in what I downloaded. I'll be sure to build the bleeding in my Linux machine or dicker and test there soon.
