### ISSUE TITLE
Hashes filtered out due to --cost or --salts constraints, show up as cracked

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#5368]
This is a regression caused by 201637cfc5, 471720fe2 (#5195)
```
$ ./john -form:7z 7z-samples.in -show
0 password hashes cracked, 9 left      <--- correct

$ ./john -form:7z 7z-samples.in -inc -cost=:,1
Using default input encoding: UTF-8
Loaded 9 password hashes with 9 different salts (7z, 7-Zip archive encryption [SHA256 256/256 AVX2 8x AES])
Cracked 1 password hash (is in ../run/john.pot), use "--show"     <--- Not correct!
Remaining 8 password hashes with 8 different salts
Remaining hashes with cost 1 (iteration count) varying from 262144 to 524288
Remaining hashes with cost 2 (padding size) varying from 4 to 14
Remaining hashes with cost 3 (compression type) varying from 0 to 1
Remaining hashes with cost 4 (data length) varying from 9 to 387
Will run 32 OpenMP threads
```
The hash stated as cracked wasn't in fact cracked but has a padding size of 0 so was filtered out by the `--cost` option. Same goes (I presume) for using the `--salts` option because that too happens in `ldr_fix_database()`.  I tried whipping up a quick fix for this (just calling `ldr_fix_database()` after the "Cracked" printout) but this doesn't work because `database.password_count` isn't updated by then so it would always show 0 cracked.

**Comment by solardiz** [comment]
I think we should suppress the "Cracked" line or replace the word with "Excluded" and drop the pot and `--show` reference in those cases, or even simpler when the `--costs` or/and `--salts` options are in use regardless of whether they had any effect.

**Comment by solardiz** [comment]
> suppress the "Cracked" line [...] when the `--costs` or/and `--salts` options are in use regardless of whether they had any effect.

This turned out to be not so easy to implement, because those options don't set a flag and the variables they set directly are `static`. We could infer from other variables (which the loader uses), but this is tricky and fragile. So maybe we should instead modify `ldr_fix_database`, splitting it into two functions or having it return a value indicating what it really did.

**Comment by magnumripper** [comment]
> the variables they set directly are `static`

We could just add getter functions for them - or a single function checking both. We (as in your's truly, and perhaps Jim) widened the scope of several variables over the years where a better fix would have been to add getter/setter functions.

> maybe we should instead modify `ldr_fix_database`, splitting it into two functions or having it return a value indicating what it really did.

I had that idea too when I had that quick look at it.

**Comment by magnumripper** [comment]
> We could just add getter functions

Totally OT but this reminds me I've had the idea to add many more things to "detailed status", such as session name and what rule we're currently processing (eg. `rule 18/3068, rejected 4`). A bunch of getters would be needed but it's all very trivial.
