### ISSUE TITLE
pdf2john major overhaul

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#5369]
https://github.com/benjamin-awd/pdf2john/issues

@benjamin-awd will you honor us a PR once you're done with it please? And we/you can try it for [our open issues](https://github.com/openwall/john/issues?q=is%3Aopen+pdf2john) as well as [hashcat's](https://github.com/hashcat/hashcat/issues?q=is%3Aopen+pdf2john).

**Comment by benjamin-awd** [comment]
hi magnum, yeah happy to do that. 

Do you have any thoughts on how to add in the code? The only blocker is the pyhanko dependency, but it'd be relatively easy to do:
```python
try:
    from pyhanko.pdf_utils.reader import PdfFileReader
except ImportError:
    print("pyhanko is missing, run 'pip install pyhanko==0.20.1' to install it!")
    exit(1)
```

**Comment by magnumripper** [comment]
IMHO something like that would be fine but let's here from @solardiz as well.

**Comment by benjamin-awd** [comment]
@magnumripper I've raised a PR https://github.com/openwall/john/pull/5370, let me know if there's anything I should change.

**Comment by benjamin-awd** [comment]
> And we/you can try it for [our open issues](https://github.com/openwall/john/issues?q=is%3Aopen+pdf2john) as well as [hashcat's](https://github.com/hashcat/hashcat/issues?q=is%3Aopen+pdf2john).

Don't think I can help with most of the older issues, but I've added in a debug flag that should help with troubleshooting for future issues:

```python
python3 pdf2john.py r6-test-bad-password.pdf --debug

$pdf$5*6*256*-4*1*16*fce2fe96b7e142b4a0576f61e2e9c441*48*aef6c4bf5e8a0f3bb1adef2b8ac2367d1ce95ecc1ddc3243ce49786086a023aa310aa9f7d1d103f837e4d4f738ac913d*48*eabf37f3f1f1b208f7c8ddfad3b817c689889ecbadd30f4581382cfbf79806304fb438e9ca227a023138a38eadcf82f3*32*37afcbfcbb32d4e1bca1eb10165693a1633ebb742c00045177a284ba22196937*32*3459a644d5f4c4f7cee562b754b30df48d598e1911ea513ef29bb3928593caf3
Encryption Dictionary:
/CF: {'/StdCF': {'/AuthEvent': '/DocOpen', '/CFM': '/AESV3', '/Length': 32}}
/Filter: /Standard
/Length: 256
/O: b'\xea\xbf7\xf3\xf1\xf1\xb2\x08\xf7\xc8\xdd\xfa\xd3\xb8\x17\xc6\x89\x88\x9e\xcb\xad\xd3\x0fE\x818,\xfb\xf7\x98\x060O\xb48\xe9\xca"z\x0218\xa3\x8e\xad\xcf\x82\xf3'
/OE: b'7\xaf\xcb\xfc\xbb2\xd4\xe1\xbc\xa1\xeb\x10\x16V\x93\xa1c>\xbbt,\x00\x04Qw\xa2\x84\xba"\x19i7'
/P: -4
/Perms: b'\x00\xe2p@\xe8I\xe5\xc8\xcd^\xb1\x8c\xba\x99\xceI'
/R: 6
/StmF: /StdCF
/StrF: /StdCF
/U: b'\xae\xf6\xc4\xbf^\x8a\x0f;\xb1\xad\xef+\x8a\xc26}\x1c\xe9^\xcc\x1d\xdc2C\xceIx`\x86\xa0#\xaa1\n\xa9\xf7\xd1\xd1\x03\xf87\xe4\xd4\xf78\xac\x91='
/UE: b'4Y\xa6D\xd5\xf4\xc4\xf7\xce\xe5b\xb7T\xb3\r\xf4\x8dY\x8e\x19\x11\xeaQ>\xf2\x9b\xb3\x92\x85\x93\xca\xf3'
/V: 5
```
