### ISSUE TITLE
office2john fails on python 3.10+

### ISSUE THREAD

**Issue by nastyagrifon** [openwall/john#5371]
### Checklist ###
- :1st_place_medal: I've read and understood these instructions;
  - This is not a support forum, it's a bug tracker. For questions and support, review postings on the [john-users mailing list](https://www.openwall.com/lists/john-users/).
- :thumbsup: I've tested using latest bleeding version from this repository.
  - Be clear about your environment and what you are doing. Share a sample hash or file that can be used to reproduce.
- :confused: I'm confused and I need guidance.
  - Please, read the instructions at https://www.openwall.com/john/#lists, then join the list before posting.

### IMPORTANT ###
We expect only reports of issues with the latest revision found in this GitHub repository. We do not expect in here, and have little use for, reports of issues only seen in a release or in a distro package.

Attach details about your OS and about john, including:
<details> 
  <summary>The output of `./john --list=build-info`. </summary>
```

Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX AC MPI + OMP
SIMD: AVX, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: AVX
CPU fallback binary: john-non-avx
$JOHN is /usr/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 13.2.1
GNU libc version: 2.38 (loaded: 2.38)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 030100020	(loaded: 030100040)
OpenSSL 3.1.2 1 Aug 2023	(loaded: OpenSSL 3.1.4 24 Oct 2023)
GMP library version: 6.3.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's ```


</details>

<details> 
  <summary>The command line you are using. </summary>
`./office2john ./N.docx > hash_N`
</details>

<details> 
  <summary>Traceback</summary>

Traceback (most recent call last):
  File "/usr/bin/office2john", line 3082, in <module>
    ret = process_file(sys.argv[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/office2john", line 3005, in process_file
    return process_new_office(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/office2john", line 2813, in process_new_office
    xml_metadata_parser(data, filename)
  File "/usr/bin/office2john", line 2857, in xml_metadata_parser
    for node in tree.getiterator('{http://schemas.microsoft.com/office/2006/keyEncryptor/password}encryptedKey'):
                ^^^^^^^^^^^^^^^^
AttributeError: 'ElementTree' object has no attribute 'getiterator'
</details>

`getiterator` method was depreciated in Python 3.9, so it would not work with newer versions

**Comment by solardiz** [comment]
Thank you @NastyaGrifon for trying to contribute. Our understanding is that this specific issue had already been fixed, so I'll close it. However, please feel free to contribute to addressing issues still relevant to our current git code, such as these: 
https://github.com/openwall/john/labels/good%20first%20issue
