### ISSUE TITLE
Get rid of modulo division in Argon2

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5385]
See https://github.com/P-H-C/phc-winner-argon2/pull/306

We need this for both CPU and OpenCL formats. For CPU, perhaps do it after #2738.

**Comment by solardiz** [comment]
Done for OpenCL via #5401, yet to do for CPU.

**Comment by solardiz** [comment]
We may implement this by merging @Sc00bz's https://github.com/P-H-C/phc-winner-argon2/pull/306 or by implementing changes ourselves like I did in 2434e3fac2c10b28dc6cb78d67272016296a141f for argon2-opencl or f1f81589b6edbfb5b6aa75b83398004aa344c726 for Armory. It is easy to get this wrong for corner cases, so reusing tested code or/and thorough retesting with different lane counts (powers of 2 and not) is desirable.

@Sc00bz Maybe you want to contribute a pull request? We'd likely be much quicker to merge it than upstream not doing so. ;-)

**Comment by magnumripper** [comment]
FWIW when running a port of the same (ref) Argon2 code on nvidia, these fixes consistently result in a 3% regression. Not sure why but binary size increases with 602 bytes.

**Comment by solardiz** [comment]
> FWIW when running a port of the same (ref) Argon2 code on nvidia, these fixes consistently result in a 3% regression. Not sure why but binary size increases with 602 bytes.

Thanks for letting us know. That's another reason to actually test performance of these changes on CPU. And likely exclude the unneeded changes for `% ARGON2_ADDRESSES_IN_BLOCK`. cc: @Sc00bz

As to the related changes I actually got into our OpenCL kernel, I benchmarked those and ensured at least no regressions. Some other revisions I didn't commit did in fact cause performance regressions in some cases on some devices I tested.

**Comment by magnumripper** [comment]
> exclude the unneeded changes for `% ARGON2_ADDRESSES_IN_BLOCK`

Just for curiosity I tried that now for the nvidia. Somehow this made the binary size even larger (with 34 bytes, now 636), and speed regression remained. That's a bit strange but optimizer's results can be strange (and impressing: I also tried manually optimizing away the `zero_block` completely and that ended up 100% same when compiled).

Edit: The regressions aren't so strange considering we're way out of registers on GPU.

**Comment by solardiz** [comment]
@magnumripper I assume you continue to experiment with your reference Argon2 based OpenCL kernel just to improve your own understanding, not as something you intend to get in here, since we already have much faster code, correct?

**Comment by magnumripper** [comment]
That is sort of correct, except I may "have to" use it at some point for *some* format (given costs are sane, so maybe wont happen). Alain's kernel is not precisely a plug and play thing like the shared algos we have. The very slow experimental ref code is - just include it and call it. 

To use Alain's kernel for keepass, I would "have to" make it a standalone keepass-argon2-opencl, probably even in the same source file as argon2-opencl for sharing all host-side support code it has. The details of that quickly get very tricky and very ugly (I tried once so far, and scratched it).

Also, I think keepass cost settings for Argon2 might be excessive for most GPU's of today *regardless* of code. I tried a hash with similar cost with Argon2-opencl and it even crashed - I'll open a ticket for that. Maybe it tried to allocate more memory than available.

I will probably end up not supporting Argon2 at all in keepass-opencl, just KDBX4 using AES.

**Comment by solardiz** [comment]
Oh, I thought it was a quick question with an easy answer. I think we shouldn't have reference Argon2 in OpenCL at all - it is 32x worse in terms of memory needs for same GWS compared to the code we currently have in `argon2-opencl`. Like you say, the reference code isn't expected to perform meaningfully for Keepass settings.

As to `argon2-opencl` crashing at those settings, this shouldn't be happening. IIRC, I tested it up to 256 MiB per hash if not more, and it worked reasonably well even then. Please do open a ticket for whatever crash you observed.

I don't see why it'd be so tricky and ugly to revise and reuse our current `argon2-opencl` code also for `keepass-argon2-opencl`. Indeed, it'd require some cleanup and generalization, so it's significant effort, but it should be do-able. And I do think it should be a separate format anyhow, at least because the LWS/GWS would be very different than for non-Argon2-using Keepass "hashes".
