### ISSUE TITLE
Trying to build JtR Jumbo on Win11 WSL Ubuntu

### ISSUE THREAD

**Issue by xbbdc** [openwall/john#5414]
I get the following error when I run the make command

xbbdc@5800x3d:~/.john/john/src$ make -s clean && make -sj4
7z_common_plug.c:18:2: warning: #warning "Notice: 7z format will lack DEFLATE support (needs zlib)" [-Wcpp]
   18 | #warning "Notice: 7z format will lack DEFLATE support (needs zlib)"
      |  ^~~~~~~
7z_common_plug.c:23:2: warning: #warning "Notice: 7z format will lack BZIP2 support (needs libbz2)" [-Wcpp]
   23 | #warning "Notice: 7z format will lack BZIP2 support (needs libbz2)"
      |  ^~~~~~~

I have both zlib and libbz2 installed including the dev versions. Not sure why this error is happening. I ran git clone https://github.com/openwall/john -b bleeding-jumbo john - 2 days ago so I'm using latest version.

**Comment by solardiz** [comment]
Hi @xbbdc. My best guess is you did not have the dev versions of those packages installed the first time you ran `configure`. If so, you need to re-run `configure` after you've installed those packages. Does this help?

**Comment by xbbdc** [comment]
Yes, that did it! Thanks!

Configure finished.  Now "make -s clean && make -sj4" to compile.
xbbdc@5800x3d:~/.john/john/src$ make -s clean && make -sj4
/usr/bin/ar: creating aes.a
/usr/bin/ar: creating poly1305-donna.a
/usr/bin/ar: creating ed25519-donna.a
/usr/bin/ar: creating secp256k1.a

Make process completed.

**Comment by xbbdc** [comment]
I didn't try using this until now and was getting this error now

Can't locate Compress/Raw/Lzma.pm in @INC

Ran this to fix it - sudo apt-get install libcompress-raw-lzma-perl
