### ISSUE TITLE
zip2john output is large, unidentified by other tools

### ISSUE THREAD

**Issue by Subhankar210** [openwall/john#5432]
[zip_hash.txt](https://github.com/openwall/john/files/14129237/zip_hash.txt)
this is the output hash. which is almost 13.7 mb in size  & zip file was 2.79 gb .  ( don't ask for original file , it's confidential) 

buildinfo: ┌─[parrot@parrot]─[~]
└──╼ $john --list=build-info
Version: 1.9.0-jumbo-1
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
System-wide exec: /usr/lib/john
System-wide home: /usr/share/john
Private home: ~/.john
CPU tests: AVX2
CPU fallback binary: john-xop-omp
OMP fallback binary: john-avx2-non-omp
$JOHN is /usr/share/john/
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 10.2.1
GNU libc version: 2.31 (loaded: 2.36)
Crypto library: OpenSSL
OpenSSL library version: 0101010bf	(loaded: 01010117f)
OpenSSL 1.1.1k  25 Mar 2021	(loaded: OpenSSL 1.1.1w  11 Sep 2023)
GMP library version: 6.2.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's

terminal: bash shell

**Comment by solardiz** [comment]
Hi. What's your reason to open this issue? There appears to be nothing wrong here, and nothing for us to do on it, but apparently you thought otherwise? Please explain. Thanks.

**Comment by Subhankar210** [comment]
hash unidentified by all the password cracking program ( hashcat , other tools ) & why output hash size is so big ?? unable to use HASHCAT( for GPU use)  with against the  hash output !!!!!!!!!!!!!

**Comment by solardiz** [comment]
Is the "hash" identified by `john` itself? I don't know as much about other tools. The size is just fine, it is not really a hash - there's no such thing as a ZIP file hash that you'd crack its password from.

Anyway, we recommend that you use our latest code from this repo, both `zip2john` and `john`, especially if you're running into issues with our previous release, which is rather dated. We did make improvements related to ZIP file support since then.

**Comment by solardiz** [comment]
Regarding GPU use, if your file is of WinZip format, then you can use GPUs with `john --format=zip-opencl`. If your file is PKZIP, then unfortunately we only support it on CPU currently. `zip2john` will process either kind of file, and then `john` without arguments (do not specify any `--format` option yet!) should detect which one it is and if it's WinZip and your build is with OpenCL support, it'd suggest you use `--format=zip-opencl`.

**Comment by solardiz** [comment]
Anyway, by the "hash" size, I can tell it's PKZIP. Also, looking at hashcat source code for its PKZIP modes, it appears to need an encrypted file in the archive that's at most 320 KiB. It appears that the smallest file in your PKZIP archive is much larger than that. So you'd have to use `john` itself to crack it, on CPU. You could also try other tools/approaches, like https://github.com/kimci86/bkcrack (also on CPU, but recovering the encrypted data without finding the password). Good luck!

I'll close this issue since it's not an issue with our code that we need to track, but please feel free to add comments.

**Comment by solardiz** [comment]
> Anyway, by the "hash" size, I can tell it's PKZIP.

Oops, I was wrong! I didn't notice/forgot you actually attached the "hash" here. Looking at it, it's actually WinZip. Well, `john --format=zip-opencl` works on it, so you can use GPUs in this way.

**Comment by Subhankar210** [comment]
Actually i know the password of the zip file , but the size of ### zip2john abc.zip >hash ### output file hash is so big that i can't use the output zip hash with any other password cracker, I know john is a best password cracker tool . But i want to use GPU  for cracking because of speed and also use Hashcat for Incremental feature because i don't want to save the wordlist file in my disk because wordlist file was very Big. 


Due to Hash file can't understand by any other program except john .  Is there any way to extract the ZIP file hash that understandable for other zip password 🔑 hash cracking program? 


Thanks for your precious time & quick respond 😊. 


I already provided the zip2john output hash file ...

**Comment by solardiz** [comment]
> i want to use GPU for cracking because of speed

Like I said, you can - with `john --format=zip-opencl`.

> also use Hashcat for Incremental feature because i don't want to save the wordlist file in my disk because wordlist file was very Big.

You may want to get more familiar with `john`, as you definitely don't need to save any large wordlist to disk with it either. I'm actually not very familiar with hashcat, but I think you're referring to its ability to increase mask length within one invocation, or maybe you used the wrong word and you meant the mask support in general? Either way, JtR can do that too. And either tool can do so much more than that, so you'll likely want to use some of their more advanced features once you're more familiar with them.

I'm not saying which tool is best, it's just that you're asking in here, and I tell you what I know and what I recommend.

> Is there any way to extract the ZIP file hash that understandable for other zip password 🔑 hash cracking program?

To my knowledge, probably not in your case and given existing tools.

**Comment by solardiz** [comment]
If you really want to get hashcat to work on this, you can _try_ editing its source code (and rebuilding) to change the instances of `0x200000` to `0x400000` (so doubling them) in all places seen in https://github.com/hashcat/hashcat/commit/51adbbbe53b100a94f7235af53c3a6ad3f01d17b - however, this is a hack that may or may not work (it's totally untested), and I'm not aware of the rationale of the hashcat project choosing the smaller value there (@philsmd may know). It appears that your file would just fit then.

**Comment by Subhankar210** [comment]
Thanks for your valuable Information.
