### ISSUE TITLE
Integrate ZLUDA for AMD CUDA brute

### ISSUE THREAD

**Issue by GermanAizek** [openwall/john#5444]
hi everyone
https://github.com/vosen/ZLUDA
it can give higher speed on amd video cards if cuda code is optimized

**Comment by solardiz** [comment]
Hi. I had read about ZLUDA on tech news sites, just like you probably did. We dropped support for CUDA some years ago, focusing solely on OpenCL. So this is currently irrelevant for us, except as a possible reason to reintroduce CUDA at some point, which I currently don't see us doing given our other priorities and lack of resources. So I'm going to close this issue as it's not something we currently need to keep track of. Thanks for suggesting this anyway.
