### ISSUE TITLE
Not ISSUE: GPG SYMMETRIC ENCRYPTION 

### ISSUE THREAD

**Issue by gigoplast** [openwall/john#5455]
Need To Know is there a way to Decypt this File .
i have sceenshot 
![Untitled](https://github.com/openwall/john/assets/11947255/161a9522-4027-42b8-b7a7-49286ab083c1)

Mobo = Second Gen Intel "ASUS PRIME Z270-P"
CPU = Intel Kaby LaKe I5 5400
GPU = GTX 1080 FE
Ram = 16Gb ddr4 2400

Please What is The right SYNTAX to decrypted  .   Thank you a Lot
Devs Appology For Posting as issue .

 ./john --list=build-info
Version: 1.9.0-jumbo-1+bleeding-3c2e19c0db 2024-03-20 20:30:26 +0100
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP OPENCL
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 11.4.0
GNU libc version: 2.35 (loaded: 2.35)
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 030000020
OpenSSL 3.0.2 15 Mar 2022
GMP library version: 6.2.1
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 45 ns
Total physical host memory: 7882 MiB
Available physical host memory: 2621 MiB
Terminal locale string: en_US.UTF-8
Parsed terminal locale: UTF-8
-------------------------------------------------------------------------------
./john --list=opencl-devices
Platform #0 name: NVIDIA CUDA, version: OpenCL 3.0 CUDA 12.1.68
    Device #0 (1) name:     NVIDIA GeForce GTX 1080
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 3.0 CUDA
    OpenCL version support: OpenCL C 1.2 
    Driver version:         530.30.02 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          8110 MiB
    Global Memory Cache:    960 KiB
    Local Memory:           48 KiB (Local)
    Constant Buffer size:   64 KiB
    Max memory alloc. size: 2027 MiB
    Max clock (MHz):        1847
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 20
    CUDA INT32 cores:       2560  (20 x 128)
    Speed index:            4728320
    Warp size:              32
    Max. GPRs/work-group:   65536
    Compute capability:     6.1 (sm_61)
    Kernel exec. timeout:   yes
    NVML id:                0
    PCI device topology:    01:00.0
    PCI lanes:              8/16
    Fan speed:              35%
    Temperature:            43°C
    Utilization:            3%
--------------------------------------------------------------------------------------------------------------
brav.hash:

https://raw.githubusercontent.com/gigoplast/Docs/main/brav.hash

is this right ? possible to decrypt !
my gpg file pass-code might-be a copy past from scratch paragraph text ?
is that a confirmation of copy/past form  to encode the file .
Thank you for Let me Know . 
Sincerely Grateful

**Comment by gigoplast** [comment]
[brav.png.gpg.zip](https://github.com/openwall/john/files/14808841/brav.png.gpg.zip)
For Better understanding File Characteristic .
Appology Devs

**Comment by ghost** [comment]
You need to run the applicable 2john tool (in this case, `gpg2john`) to extract the "relevant information", and then run a cracking session using `john`. Simple as:

```sh
$ john-the-ripper.gpg2john brav.png.gpg > hash.txt

File brav.png.gpg

$ john hash.txt 
Warning: detected hash type "gpg", but the string is also recognized as "gpg-opencl"
Use the "--format=gpg-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (gpg, OpenPGP / GnuPG Secret Key [32/64])
Cost 1 (s2k-count) is 65011712 for all loaded hashes
Cost 2 (hash algorithm [1:MD5 2:SHA1 3:RIPEMD160 8:SHA256 9:SHA384 10:SHA512 11:SHA224]) is 2 for all loaded hashes
Cost 3 (cipher algorithm [1:IDEA 2:3DES 3:CAST5 4:Blowfish 7:AES128 8:AES192 9:AES256 10:Twofish 11:Camellia128 12:Camellia192 13:Camellia256]) is 9 for all loaded hashes
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:/snap/john-the-ripper/current/run/password.lst
Enabling duplicate candidate password suppressor
0g 0:00:01:05 0.00% 2/3 (ETA: 2028-07-06 00:33) 0g/s 45.05p/s 45.05c/s 45.05C/s dead..doitnow
Session aborted

```
In fact, everything works fine. Any tutorial from the internet will give you this same information.  

The real problem here is that you will need to know something about the lost password and/or have a good set of hardware to be able to crack it. As you can see the speed is not very good (I am using a recent CPU).

**Comment by solardiz** [comment]
I'm closing this since it's not an issue that we need to track. More comments may be added anyway.
