### ISSUE TITLE
mssql05 misses some cracks in AVX512BW builds

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5488]
As @claudioandre-br reported/confirmed in https://github.com/openwall/john/issues/4177#issuecomment-2132212146 the mssql05 format misses some cracks in AVX512BW builds, even though it cracks all in AVX2 builds.

**Comment by solardiz** [comment]
@claudioandre-br Can you please identify the specific 3 test hashes that failed to get cracked, and post them in here along with the expected plaintexts? Do they get cracked when they're the only ones to crack?

**Comment by ghost** [comment]
```
u7-mssql05:0x0100784F6743D124B6A56A78144A3DEC5FF53E96CEE86EFD2221
u16-mssql05:0x01004F64554525A4F4B0507B5993D06EED42650859B8249FAEE3
u6-mssql05:0x010077356E4E9412F32BBCAC5F3835BB619121987B25800C0448
```

```
$ diff avx512.txt  avx2.txt
6a7,8
> u6-mssql05::6:0:::
> u7-mssql05: :7:0: ::
14a17
> u16-mssql05:�:16:0:�::
1499c1502
< 1497 password hashes cracked, 3 left
---
> 1500 password hashes cracked, 0 left
```

****
Empty: ''
One space: ' '

```
Cracked 1497 password hashes (are in tst-.pot), use "--show"
Remaining 3 password hashes with 3 different salts
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
                 (u7-mssql05)     
                 (u6-mssql05)     
�                (u16-mssql05)     
3g 0:00:00:00 DONE (2024-05-26 16:55) 150.0g/s 542400p/s 1158Kc/s 1158KC/s password..admin
Use the "--show --format=mssql05" options to display all of the cracked passwords reliably
Session completed. 
```

**Comment by solardiz** [comment]
> Do they get cracked when they're the only ones to crack?

I assume the answer is yes? At least that's the case for my AVX512BW build, running with `-inc=utf8`.

**Comment by ghost** [comment]
> > Do they get cracked when they're the only ones to crack?
> 
> I assume the answer is yes? At least that's the case for my AVX512BW build, running with `-inc=utf8`.

Yes, they are crackable in AVX512. But there are some caveats:

```
echo 'u6-mssql05:0x010077356E4E9412F32BBCAC5F3835BB619121987B25800C0448' > hash.txt

$ rm -f *.pot; ../run/john -config=jtrts.conf -ses=tst-  -pot=tst-.pot hash.txt --wordlist=tst-pw3
Loaded 1 password hash (mssql05, MS SQL 2005 [SHA1 512/512 AVX512BW 16x2])
Note: Passwords longer than 25 rejected
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
0g 0:00:00:00 DONE (2024-05-26 18:22) 0g/s 75000p/s 75000c/s 75000C/s DOGBERT__17..late&*night__17
Session completed. 

$ rm -f *.pot; ../run/john -pot=tst-.pot hash.txt --wordlist=tst-pw3
Using default input encoding: UTF-8
Loaded 1 password hash (mssql05, MS SQL 2005 [SHA1 512/512 AVX512BW 16x2])
Note: Passwords longer than 25 rejected
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
                 (u6-mssql05)     
1g 0:00:00:00 DONE (2024-05-26 18:23) 100.0g/s 3200p/s 3200c/s 3200C/s qerwt.. 
Use the "--show --format=mssql05" options to display all of the cracked passwords reliably
Session completed. 

$ rm -f *.pot; ../run/john -ses=tst-  -pot=tst-.pot hash.txt --wordlist=tst-pw3
Using default input encoding: UTF-8
Loaded 1 password hash (mssql05, MS SQL 2005 [SHA1 512/512 AVX512BW 16x2])
Note: Passwords longer than 25 rejected
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
                 (u6-mssql05)     
1g 0:00:00:00 DONE (2024-05-26 18:23) 100.0g/s 3200p/s 3200c/s 3200C/s qerwt.. 
Use the "--show --format=mssql05" options to display all of the cracked passwords reliably
Session completed. 
```

```
$ cat jtrts.conf
.include "$JOHN/john.conf"

[Local:Options]

# we might want to look at these.
reloadatcrack = N
verbosity = 3
idle = Y

# we undo the 'defaults' for now, until we update the TS properly.
cpstoreutf8 = N
unicodestoreutf8 = N
alwaysreportutf8 = N
warnencoding = N
DefaultInternalCodepage = RAW
DefaultInternalEncoding = RAW
DefaultMSCodepage = RAW
DefaultEncoding = RAW
StatusShowCandidates = N
SessionFileProtect = disabled
LogFileProtect = disabled
LogCrackedPasswords = Y

[List.Rules:appendNumNum]
$[0-9]$[0-9]

[List.Rules:appendNum]
$[0-9]

[List.Rules:append12Num]
$[12]$[0-9]
```

Sometimes does, sometimes doesn't?
```
$ cat hash.txt 
u6-mssql05:0x010077356E4E9412F32BBCAC5F3835BB619121987B25800C0448
```

BTW: is it possible to print the cracked passwords in hex or something?

**Comment by solardiz** [comment]
So it looks like TS's config file override triggers this. Are you sure this only happens with AVX512 and not AVX2? Was your AVX2 test using TS's config file as well?

I'd suspect this is working as intended since different character encoding settings can reasonably result in such differences, however this shouldn't depend on SIMD and it shouldn't affect the empty string and one space character (it may reasonably affect the Unicode character).

> BTW: is it possible to print the cracked passwords in hex or something?

Currently, no. We have related open issues #2354, #3645.

**Comment by ghost** [comment]
> Are you sure this only happens with AVX512 and not AVX2?

See AVX512 https://github.com/openwall/john/issues/4177#issuecomment-2132212146 and AVX2 https://github.com/openwall/john/issues/4177#issuecomment-2132221001. History at https://github.com/openwall/john/issues/4177#issuecomment-570645200

I don't see how I did something in the remote past and managed to repeat it today if there isn't some error in `john`. There is no need to change source code. 

One build and test. Then, build again with `--enable-simd=avx2`.
*****

At least it's harder to see the error using AVX2. I've never seen this.

**Comment by ghost** [comment]
BTW, if you would like to rename `John`, how about thinking about it now. The line is so long that you can't see AVX2 below (no wait, it is not AVX2).

```
John the Ripper 1.9.0-jumbo-1+bleeding-4509390 2020-01-03 14:19:47 -0300 OMP [linux-gnu 64-bit x86_64 AVX512BW AC]
```

**Comment by solardiz** [comment]
I cannot reproduce this issue. Neither with manual testing, nor even with TS itself:

```
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, JimF & others
- Testing:  John the Ripper 1.9.0-jumbo-1+bleeding-ba463680f5 2024-05-27 22:21:07 +0200 OMP [linux-gnu 64-bit x86_64 AVX512BW AC]
--------------------------------------------------------------------------------

John Jumbo build detected.

form=MSSql05                      guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:MSSql05                  guesses: 1500 0:00:00:00 DONE  [PASSED] (0 val-pwd)
```

**Comment by solardiz** [comment]
Oh, I now see back in 2020 you wrote:

> John's AVX512BW build is NOT reliable. It misses cracks if I use clang. It might work if one uses gcc.

I'm using gcc. Claudio, was your recent retesting of this issue with clang or gcc?

**Comment by solardiz** [comment]
OK, reproduced it with TS + clang.

Still not reproducible without TS, even when I supply the conf file above but use `-inc=utf8` to crack.

**Comment by solardiz** [comment]
This avoids the problem:

```diff
+++ b/src/x86-64.h
@@ -266,7 +266,7 @@
 #if defined(__INTEL_COMPILER)
 #define SIMD_PARA_SHA1                 1
 #elif defined(__clang__)
-#define SIMD_PARA_SHA1                 2
+#define SIMD_PARA_SHA1                 1
 #elif defined(__llvm__)
 #define SIMD_PARA_SHA1                 2
 #elif defined(__XOP__)
```

Speeds change from:

```
Benchmarking: mssql05, MS SQL 2005 [SHA1 512/512 AVX512BW 16x2]... DONE
Many salts:	88379K c/s real, 91098K c/s virtual
Only one salt:	61457K c/s real, 61457K c/s virtual
```

to:

```
Benchmarking: mssql05, MS SQL 2005 [SHA1 512/512 AVX512BW 16x]... DONE
Many salts:	92715K c/s real, 94120K c/s virtual
Only one salt:	56539K c/s real, 56539K c/s virtual
```

Many salts faster, Only one slower. No obvious speed change for raw-SHA1.

So we have a valid workaround, but it would be proper to also figure out and fix whatever breaks at interleaving of 2 regardless.

**Comment by solardiz** [comment]
This made no difference in behavior of either build, but is probably good to have anyway:

```diff
+++ b/src/mssql05_fmt_plug.c
@@ -30,6 +30,8 @@ john_register_one(&fmt_mssql05);
 
 #ifdef SIMD_COEF_32
 #define NBKEYS (SIMD_COEF_32 * SIMD_PARA_SHA1)
+#define FMT_IS_BE
+#include "common-simd-getpos.h"
 #endif
 #include "simd-intrinsics.h"
 
@@ -62,12 +64,6 @@ john_register_one(&fmt_mssql05);
 #ifdef SIMD_COEF_32
 #define MIN_KEYS_PER_CRYPT             NBKEYS
 #define MAX_KEYS_PER_CRYPT             NBKEYS
-#if ARCH_LITTLE_ENDIAN==1
-#define GETPOS(i, index)               ( (index&(SIMD_COEF_32-1))*4 + ((i)&(0xffffffff-3))*SIMD_COEF_32 + (3-((i)&3)) + (unsigned int)index/SIMD_COEF_32*SHA_BUF_SIZ*SIMD_COEF_32*4 ) //for endianity conversion
-#else
-#define GETPOS(i, index)               ( (index&(SIMD_COEF_32-1))*4 + ((i)&(0xffffffff-3))*SIMD_COEF_32 + ((i)&3) + (unsigned int)index/SIMD_COEF_32*SHA_BUF_SIZ*SIMD_COEF_32*4 ) //for endianity conversion
-#endif
-
 #else
 #define MIN_KEYS_PER_CRYPT             1
 #define MAX_KEYS_PER_CRYPT             1
@@ -314,7 +310,7 @@ static void set_key_utf8(char *_key, int index)
 {
 #ifdef SIMD_COEF_32
        const UTF8 *source = (UTF8*)_key;
-       unsigned int *keybuf_word = &((unsigned int*)saved_key)[(index&(SIMD_COEF_32-1)) + (unsigned int)index/SIMD_COEF_32*SHA_BUF_SIZ*SIMD_COEF_32];
+       uint32_t *keybuf_word = &((uint32_t*)saved_key)[GETPOSW32(0,index)];
        UTF32 chl, chh = 0x80;
        unsigned int len;
 
@@ -446,7 +442,7 @@ static char *get_key(int index) {
        static UTF16 out[PLAINTEXT_LENGTH + 1];
        unsigned int i,s;
 
-       s = ((((unsigned int *)saved_key)[15*SIMD_COEF_32 + (index&(SIMD_COEF_32-1)) + (unsigned int)index/SIMD_COEF_32*SHA_BUF_SIZ*SIMD_COEF_32] >> 3) - SALT_SIZE) >> 1;
+       s = ((((uint32_t*)saved_key)[GETPOSW32(15,index)] >> 3) - SALT_SIZE) >> 1;
        for (i=0;i<s;i++) {
                out[i] = saved_key[GETPOS(i<<1, index)] |
                        (saved_key[GETPOS((i<<1) + 1, index)] << 8);
```

**Comment by solardiz** [comment]
Making the `key_cleaning:` loop in the main `set_key` go until the length field, rather than until finding a zero, makes the problem go away. However, I don't see what makes this one `set_key` so special. We use the same approach in many other places. So either the approach is broken everywhere and that just didn't show up elsewhere yet, or the root cause is elsewhere in this format.

> This made no difference in behavior of either build, but is probably good to have anyway

That patch only touched a few of the many instances in this source file that we'd need to clean up like that.

**Comment by solardiz** [comment]
> I don't see what makes this one `set_key` so special.

OK, I think I do now, but this also applies to other `set_key` implementations in this format. We skip over a word here:

```c
                keybuf_word += SIMD_COEF_32;
        }
        keybuf_word += SIMD_COEF_32;
```

I guess this implies the skipped word stays at 0 from the previous calls. Hopefully, that's right on its own, but this means the cleaning loop will then stop at that 0 word and not overwrite the previous padding field.

**Comment by solardiz** [comment]
I've prepared a fix to all 3 `set_key` in this format. (Edit: speeds removed from comment as that fix was not final.)
