### ISSUE TITLE
Zip2john trows me a lot of zeros in hash

### ISSUE THREAD

**Issue by titomaldad** [openwall/john#5497]
### Checklist ###
- :1st_place_medal: I've read and understood these instructions;
  - This is not a support forum, it's a bug tracker. For questions and support, review postings on the [john-users mailing list](https://www.openwall.com/lists/john-users/).
- :thumbsup: I've tested using latest bleeding version from this repository.
  - Be clear about your environment and what you are doing. Share a sample hash or file that can be used to reproduce.
- :confused: I'm confused and I need guidance.
  - Please, read the instructions at https://www.openwall.com/john/#lists, then join the list before posting.

### IMPORTANT ###
We expect only reports of issues with the latest revision found in this GitHub repository. We do not expect in here, and have little use for, reports of issues only seen in a release or in a distro package.

Attach details about your OS and about john, including:
- The output of `./john --list=build-info`.
- The command line you are using.

**Comment by titomaldad** [comment]
With a zipfile it trows a rare hash of a lot and only zeros
https://drive.google.com/file/d/1Hda1v2CWxLdcjTEUjWHsD_zA7tpqYaGJ/view?usp=drivesdk

**Comment by ghost** [comment]
I bet you are using old version 1.9 Jumbo 1. It has some issues when dealing with zip files. **_Please update._**

Your hash should look like this:
```
$ head -c 128 zip-5497.hash 
MOVD4VGB.zip/BRRiP.x264.mkv:$zip2$*0*1*0*e8c3f9322944ff3d*4d17*67dc4a2e*7bb057233984a32685b158c938077963dd18b4bac2f58a102eeff4f8
```

```
$ tail  -c 128 zip-5497.hash 
d0884e4c41e453a6c53dd36b64702c5bd6f81d837e6856e59a0d9b01e*693359394a2a747e2991*$/zip2$:BRRiP.x264.mkv:MOVD4VGB.zip:MOVD4VGB.zip
```
****

BTW: the hash will be huge.

**Comment by titomaldad** [comment]
Yes the hash is now correct. Otherwhise i don't know if supposed to crack the password is there for a time
![20240624_151155](https://github.com/openwall/john/assets/103604388/8117f717-0e47-49b5-9b83-9b20e7365ad1)

**Comment by solardiz** [comment]
Good to know this seems to be working now. I'll close the issue as it's not something we need to track, but please feel free to add comments.
