### ISSUE TITLE
The zip2John command extracts encrypted zip compressed file hash, with garbled file names.

### ISSUE THREAD

**Issue by xhc-code** [openwall/john#5505]
![image](https://github.com/openwall/john/assets/28866025/08254ec8-b7d5-488b-b0a5-c3213132e6c4)
My Linux environment is a UTF-8 environment, but I don't know why this problem still occurs. The folders and files in compressed Boai are in Chinese.

The starting content generated by zip2John xxx. zip>hash.txt is very long and complete
![image](https://github.com/openwall/john/assets/28866025/8d2fd7f0-ab87-486a-8db8-f45f0c3aedbd)

I don't know where else the encoding hasn't been set, why is there a warning about encoding issues

**Comment by solardiz** [comment]
> My Linux environment is a UTF-8 environment, but I don't know why this problem still occurs. The folders and files in compressed Boai are in Chinese.

My best guess is those filenames are in an encoding other than UTF-8.

> The starting content generated by zip2John xxx. zip>hash.txt is very long and complete

This looks correct.

> I don't know where else the encoding hasn't been set, why is there a warning about encoding issues

A warning may be shown when our loader of the "hash" sees that it contains portions in a weird encoding. This could matter for deriving candidate passwords from the filenames, in case the password is related to a filename.

I'm not sure you can improve this with our encoding options, maybe @magnumripper has a better idea as he had made some of the related code changes, but he's been inactive with the project for the recent few months.

I'm closing this issue as I don't expect to add anything further and it's not an issue we need to track, but please feel free to add more comments if you have any.

**Comment by xhc-code** [comment]
ok
