### ISSUE TITLE
Using John's garbled characters and loading dictionary files

### ISSUE THREAD

**Issue by xhc-code** [openwall/john#5506]
![image](https://github.com/openwall/john/assets/28866025/b37ae61a-22c6-4032-82f8-a877cc31f72c)
When using the following command for execution, the crack shown in the above figure appears to have been completed, but it was not actually cracked successfully.
```bash
./john --format=PKZIP --wordlist="$DICT" --session=john_session "$HASH_FILE" > "$OUTPUT_FILE"
```

I have multiple dictionary files, cannot I use all dictionary files in this way?
![image](https://github.com/openwall/john/assets/28866025/34f3cb14-2779-4a9d-94f8-ddd471aaed80)

When executing the './john pojie_ziti.zip --show' command, the output content is completely garbled.
![image](https://github.com/openwall/john/assets/28866025/d43b0d6e-2a39-4b2b-b909-9ff87ec754a4)

**Comment by solardiz** [comment]
> I have multiple dictionary files, cannot I use all dictionary files in this way?

Yes, you can use them with a script like this, except that we do not use process exit code to indicate successful crack. If you're running on only one hash, then subsequent invocations after a successful crack will be instant anyway - they will just detect the password was already cracked and exit. You also don't need to redirect the output to a file - instead, you'd use `john --show` to retrieve the cracked password. For the session names, you could want to reuse the wordlist names.

> When executing the './john pojie_ziti.zip --show' command, the output content is completely garbled.

That's a wrong command. You wanted to use `john_hash.txt` there, not the ZIP file.

I'm closing this issue as I think I've addressed all of your questions here and it's not an issue we need to track - but please feel free to add more comments if needed.

Instead of (most) screenshots, please use plain text copy-paste from the terminal if you can (except when you need to show garbled characters or such, in which case a screenshot makes sense).

**Comment by xhc-code** [comment]
The usage of the `john --show` parameter, You are right, thank you.


Do you mean that John will immediately exit the hash file after successfully cracking it, and when he tries to crack it again?

I have a password dictionary directory (each password dictionary is a line by line password), which will have multiple password dictionary files. My usage is to first use all dictionary files for cracking, but if none of them are successful, then use the original method of the John command for incremental cracking.

![image](https://github.com/openwall/john/assets/28866025/0175cc68-4e86-469c-9333-27de3e11a280)
That is to remove the if judgment and just use the for loop, right?

**Comment by xhc-code** [comment]
At this time, the modified bash code

```bash
dictionary_crack() {
  for DICT in "$DICTIONARY_DIR"/*; do
    ./github/john/run/john --format=PKZIP --wordlist="$DICT" --session=john_session "$HASH_FILE" > "$OUTPUT_FILE"
  done
}
```

**Comment by xhc-code** [comment]
> > I have multiple dictionary files, cannot I use all dictionary files in this way?
> 
> Yes, you can use them with a script like this, except that we do not use process exit code to indicate successful crack. If you're running on only one hash, then subsequent invocations after a successful crack will be instant anyway - they will just detect the password was already cracked and exit. You also don't need to redirect the output to a file - instead, you'd use `john --show` to retrieve the cracked password. For the session names, you could want to reuse the wordlist names.
> 
> > When executing the './john pojie_ziti.zip --show' command, the output content is completely garbled.
> 
> That's a wrong command. You wanted to use `john_hash.txt` there, not the ZIP file.
> 
> I'm closing this issue as I think I've addressed all of your questions here and it's not an issue we need to track - but please feel free to add more comments if needed.
> 
> Instead of (most) screenshots, please use plain text copy-paste from the terminal if you can (except when you need to show garbled characters or such, in which case a screenshot makes sense).

Hello, please look at the latest reply information, those messages forgot to choose to reply to you

**Comment by solardiz** [comment]
> Do you mean that John will immediately exit the hash file after successfully cracking it, and when he tries to crack it again?

Yes.

> the original method of the John command for incremental cracking.

OK. Note that John's default isn't to start incremental mode right away, but first run through its `password.lst` with lots of rules, with both this wordlist and the rules having been optimized. This is likely more effective than your non-optimized wordlists without rules are. Also, you probably have duplicates across your wordlists, so you could want to combine them into one with e.g.:

```shell
cat $DICTIONARY_DIR/* | ./unique -buf=2 combined.lst
```

and then use `--wordlist=combined.lst --rules`. (Adjust the parameter to `-buf` depending on how many GB of RAM you can use for this.)

Also drop the output redirection of `john`. It's usually more convenient to have terminal output. And there's `john.log` (or a different `.log` file for your session name).

> Hello, please look at the latest reply information, those messages forgot to choose to reply to you

You don't need to explicitly reply to me nor (over-)quote. I do see all comments to an issue I previously commented on anyway.

**Comment by xhc-code** [comment]
okay, thank you.
