### ISSUE TITLE
What information is outputted by the `./john --status` command? I have reviewed the documents but have not explained the meaning of the output information.

### ISSUE THREAD

**Issue by xhc-code** [openwall/john#5507]
What information is outputted by the `./john --status` command? I have reviewed the documents but have not explained the meaning of the output information.
![image](https://github.com/openwall/john/assets/28866025/7d9fe7cf-97f6-43b3-b465-4ea5c02f0992)

**Comment by solardiz** [comment]
This is in `doc/FAQ`. Where else in the documentation do you think we should possibly have it?

```
Q: What do the various numbers printed on the status line mean?
A: As of version 1.8.0, the status line may include: successful guess
count ("g"), session duration (in the D:HH:MM:SS format for days, hours,
minutes, and seconds), progress indicator (percent done and optionally
pass number out of the total number of passes), up to four speed metrics
("g/s", "p/s", "c/s", and "C/s"), and the current (range of) candidate
password(s) being tested (John is often able to test multiple candidate
passwords in parallel for better performance, hence a range).  The four
speed metrics are as follows: g/s is successful guesses per second (so
it'll stay at 0 until at least one password is cracked), p/s is
candidate passwords tested per second, c/s is "crypts" (password hash or
cipher computations) per second, and C/s is combinations of candidate
password and target hash per second.  Versions of John prior to 1.8.0
displayed only the C/s rate (calling it c/s).  When you restore a
pre-1.8.0 session with version 1.8.0 or newer, only the g/s and C/s
rates will be displayed, because the older .rec file format lacked
information needed to compute p/s and c/s.
```

**Comment by xhc-code** [comment]
Okay, so it was explained here, https://www.openwall.com/john/doc/ Is the website's documentation outdated?

**Comment by xhc-code** [comment]
Suggest adding other files at the `--status` command line for explanation. Initially, I filtered all the files in the doc directory through `--status`, but couldn't find them, thinking there was no explanation.
Thank you, big shot.

**Comment by solardiz** [comment]
> Okay, so it was explained here, https://www.openwall.com/john/doc/

Yes, in https://www.openwall.com/john/doc/FAQ.shtml linked from that URL you gave. But also in doc/FAQ inside the jumbo tree here.

> Is the website's documentation outdated?

Yes, it pertains to what we used to call "core", whereas jumbo has a lot more functionality and will be the only maintained version starting with the next release. However, in this case the relevant FAQ entry is the same between core and jumbo.

> Suggest adding other files at the --status command line for explanation. Initially, I filtered all the files in the doc directory through --status, but couldn't find them, thinking there was no explanation.

Does the below proposed edit look good to you? -

```diff
+++ b/doc/OPTIONS
@@ -219,6 +219,11 @@ Unix-like system, you can get a detached running session to update its
 session file by sending a SIGHUP to the appropriate "john" process;
 then use this option to read in and display the status.
 
+The status line printed by this option contains a subset of fields that
+are seen on the more complete status line printed on a keypress in an
+interactive session.  Please refer to a FAQ entry we have on the meaning
+of the fields.
+
 --catch-up=NAME                        catch up with paused session
 
 Limit the session to running only until it reaches the candidates tried
```

**Comment by solardiz** [comment]
Incidentally, I think part of the reason you ran into this issue at all is you're unnecessarily redirecting command output, which breaks the normal interactive session behavior. For most uses, it'd have been easier and more informative for you to press a key during the session instead of using `--status`.

**Comment by xhc-code** [comment]
Okay, that's great
