### ISSUE TITLE
I made Hydra-John and it's done!

### ISSUE THREAD

**Issue by sojoyork** [openwall/john#5530]
I finally made Hydra-John!!! It could be stupid or good but whatever! It does work! The GitHub link is: https://github.com/sojoyork/Hydra-John

**Comment by solardiz** [comment]
Happy that you seem to be enjoying this. Have fun!

You still don't seem to explain anywhere what exactly Hydra-John does and why anyone would want to use it. You could want to add that.

Please don't open new issues here. If you want, you can add comments to this issue (which I'm now closing).

For others reading this, the previous discussion was in #5515.
