### ISSUE TITLE
Upgrade to new Unicode spec 16.0.0+

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5537]
Our last update seems here:

```
commit 74e896be8d7dd59c744eda3c6a6bc22ab9d29e15
Author: magnum <magnumripper@hushmail.com>
Date:   Tue Aug 25 16:03:26 2020 +0200

    Upgrade Unicode stuff from version 11.0.0 to 13.0.0.
```

Current is apparently 16.0.0: https://x.com/thorsheim/status/1835612002237972490

```
Per Thorsheim
@thorsheim
Unicode 16.0.0 adds 5185 new symbols, including 7 complete alphabets from India, Albania and West Africa. Unicoe 16.0.0 is now 154998 symbols in total.

Can't wait to see what @CrackMeIfYouCan will do with this next year! :D

@hashcat @solardiz @yiannistox
```

**Comment by magnumripper** [comment]
> Unicode 16.0.0 adds 5185 new symbols

In our case it adds 11,131 new characters, as we missed version 14 and 15.  I consider the new characters mostly useless but we have fairly cool scripts that just parses official Unicode Database files and produce character tables, defines classes, adds casing logic and so on.
