### ISSUE TITLE
PDF-opencl, four/five algorithms with different mask target needs

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#5548]
I implemented OpenCL support for PDF. There are four different algorithms/kernels depending on document version/revision and initially my OpenCL format was one-for-all just like the CPU format.

Two of the algos however, are really fast (several G c/s), one is medium (tens of M c/s) and one is really slow (tens of K c/s). At first I didn't care, we have plenty of such formats and there are pros and cons with making them separate formats. This time though, there is the issue of picking an internal mask target (or not!).

The fastest formats (rev 2 and 5, two separate kernels) can benefit from a target of 1000, the medium fast ones (rev 3 and 4, one same kernel) is better off with a figure in the order of 100. The slowest algo (rev 6, with its own kernel) runs best at 0 - internal mask disabled.

So what are our options?
- Just leave it alone, as one single format. For benchmarking when using `-cost=n` for picking a rev, we can adjust the mask target optimally. For cracking we could use a default target of 100, which works with all revisions but is suboptimal for some. Advanced users could then tune it manually with `--mask-internal-target` option, or use the `-cost` option (so the format can optimize for the given cost[s]). Of course in theory we could adjust the target depending on what hashes were actually loaded and remaining - but with the current format interface and scheme, we need to set the target in `init()` at which point we don't yet know what costs will be loaded. Duh.
- Split the format to one per rev (four or five formats). That's what hashcat does. Not sure what to name them but it could be things like `pdf-2008-opencl` or `pdf-rev3-opencl`. Pros: We could use really optimal targets (even separating r2 and r5). Cons: It wouldn't be ideal to split rev 3 and rev 4, so what to call that one? `pdf-rev3-4-opencl` isn't beatiful.
- Split the format to one per needed mask target. What would we call them? It could be like `pdf-fast-opencl` and `pdf-slow-opencl` but now we're talking outright awful names and totally unintuitive for a novice user (actually for any user, I think).
- Go crazy and hack around in core/mask so we can set the mask target depending on what hashes are actually loaded. I could have considered this if I had some particular idea on how to achieve it... but I don't.

I'm leaning towards just making this a single format and be done with it. Note that such a format with a `-cost=2:2` option added will behave _exactly_ like a separate `pdf-rev2-opencl` would - when you need that. If you just want to run a wordlist against 20 pdf hashes of various versions, a single format is much more user friendly, suboptimal or not. And internal mask doesn't even come to play in that case.

**Comment by magnumripper** [comment]
> Go crazy and hack around in core/mask

The reason an oversized mask multiplier ends up with lower speed is that autotune will limit GWS due to kernel duration (as opposed to speed). I wonder if we can get autotune to detect this particular situation and allow larger durations in this case, perhaps with a notice that using `--mask-internal-target` may be beneficial. This would also help when mask mode has to pick eg. one of 0 or 95 although the target is more like 40: When benchmarking with mask the available placeholders to pick from are optimal but in a real run we may only have `?a`. This situation could also be solved with a mask mode capable to put "parts of a placeholder" to device side but that is a bigger task and I think we have an existing issue for it.

Another idea BTW is we could autotune not only workgroup sizes but also mask multiplier (again given the actually used mask). That too is well beyond this issue.

**Comment by magnumripper** [comment]
> detect this particular situation

I described two different situations above. The OP issue of an incorrect target given in the first place is not so easy but hardly impossible. The issue of "we picked 95 because the alternative was 0" should be trivial (seeing 95 and knowing the target was just 40, we can double the max. allowed kernel duration).

**Comment by ghost** [comment]
I believe that "keeping it simple" is a good starting point.

The difficulty is that all the extra alternatives listed will require (a lot of) time, time that you probably don't have right now.

**Comment by solardiz** [comment]
I agree about keeping it simple at least for the initial merge, since the work on it has already been done and since we need to maintain change history. We may also end up just keeping it that way.

> we have plenty of such formats and there are pros and cons with making them separate formats.

Yes. This isn't only about the mask multiplier, but also about speed reporting on our default `--test` runs, especially multi-format, where we currently see the speeds for only one "subformat" per format. So we need an improvement in this area for many formats. Maybe we'll come up with some way to expose each submit in a default `--test`, without having to split the formats. We may also detect that multiple "subformats" were loaded for cracking at once, and suggest specific `--cost` options to use to split them into 2+ more optimal runs. Conversely, we may also detect that "hashes" corresponding to only one "subformat" (or a subset smaller than all) are loaded for cracking and adjust the mask multiplier to what works best for that one (or that subset or range). In general, autotune should consider the actually loaded "hashes" - and I think in some ways already does?

**Comment by magnumripper** [comment]
>  In general, autotune should consider the actually loaded "hashes" - and I think in some ways already does?

Yeah we usually (or always?) autotune using the highest cost loaded in the "real" db, avoiding extreme kernel durations later on. But that thing has only been about kernel duration - this is the first time we got this mask target problem.
