### ISSUE TITLE
Unable to unsubscribe from emails for this thread

### ISSUE THREAD

**Issue by WonderWoman1977** [openwall/john#5556]
Hello,

I have been trying for approximately 1 1/2 weeks to unsubscribe from getting emails from this repository and have been unsuccessful.  Is there anyone that can help me?  I am also not “following” this repository which additionally baffles me as to why I am getting constant emails.

Thank you.

### Checklist ###
- :1st_place_medal: I've read and understood these instructions;
  - This is not a support forum, it's a bug tracker. For questions and support, review postings on the [john-users mailing list](https://www.openwall.com/lists/john-users/).
- :thumbsup: I've tested using latest bleeding version from this repository.
  - Be clear about your environment and what you are doing. Share a sample hash or file that can be used to reproduce.
- :confused: I'm confused and I need guidance.
  - Please, read the instructions at https://www.openwall.com/john/#lists, then join the list before posting.

### IMPORTANT ###
We expect only reports of issues with the latest revision found in this GitHub repository. We do not expect in here, and have little use for, reports of issues only seen in a release or in a distro package.

Attach details about your OS and about john, including:
- The output of `./john --list=build-info`.
- The command line you are using.

**Comment by solardiz** [comment]
@WonderWoman1977 We cannot directly check your subscription nor unsubscribe you ourselves, but it sounds like you're "watching" the repository, so you need to click "Unwatch" at https://github.com/openwall/john - does this help?

**Comment by WonderWoman1977** [comment]
Thank you for that…..Yes, I was watching it…..On Nov 2, 2024, at 11:19 PM, Solar Designer ***@***.***> wrote:﻿
@WonderWoman1977 We cannot directly check your subscription nor unsubscribe you ourselves, but it sounds like you're "watching" the repository, so you need to click "Unwatch" at https://github.com/openwall/john - does this help?

**Comment by ghost** [comment]
Since “unwatch” sounds incorrect in some contexts/repositories, you can select how you want to watch it.

![image](https://github.com/user-attachments/assets/ba378984-c8fb-42a0-a239-c21d1ce63a27)

The first or the last one are probably the best choices for people that care about a project.

**Comment by solardiz** [comment]
I assume we've provided sufficient information here. I'm closing this issue since we don't need to track it, but more comments can be added if needed.
