### ISSUE TITLE
Format detection warnings

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#5577]
As noticed in #5574 

"keepass-opencl" can only do AES-based hashes. "keepass-argon2-opencl" can only do Argon2-based ones. The "Keepass" CPU format can do both. Somehow when I load a bunch of samples (all types) without specifying a format...
```
Warning: detected hash type "KeePass", but the string is also recognized as "KeePass-opencl"
Use the "--format=KeePass-opencl" option to force loading these as that type instead
```
...it doesn't suggest also trying keepass-argon2-opencl.

If I specify `--format=opencl`, I get the other variant of the warning, and it's correct. Not sure how they differ in logic.
```
Warning: only loading hashes of type "KeePass-opencl", but also saw type "KeePass-Argon2-opencl"
Use the "--format=KeePass-Argon2-opencl" option to force loading hashes of that type instead
```

**Comment by magnumripper** [comment]
If I mix oldoffice and office hashes in one file, I get
```
Warning: detected hash type "Office", but the string is also recognized as "office-opencl"
Use the "--format=office-opencl" option to force loading these as that type instead
Warning: only loading hashes of type "Office", but also saw type "oldoffice"
Use the "--format=oldoffice" option to force loading hashes of that type instead
Warning: only loading hashes of type "Office", but also saw type "oldoffice-opencl"
Use the "--format=oldoffice-opencl" option to force loading hashes of that type instead
```
So the first one is "detected ... but" and the following are "only loading ... but also saw". I expected something like that from the keepass case.

**Comment by solardiz** [comment]
My first guess was that `keepass_valid` somehow has shared state between its calls from the 3 formats. But I don't see such shared state except for the `warned` variables, and those shouldn't cause this effect. So I'm puzzled. But I still do think the problem is more likely in these formats rather than in our loader code. I think we can revisit after merging #5574 and likely find and fix whatever issue there is with a separate commit.

**Comment by solardiz** [comment]
Oh, speaking of possible shared state, maybe the CPU format's `init` somehow breaks `valid` of `KeePass-Argon2-opencl`?

**Comment by solardiz** [comment]
> speaking of possible shared state, maybe the CPU format's `init` somehow breaks `valid` of `KeePass-Argon2-opencl`?

No, I don't see anything like that in there (in the pending PR).

**Comment by magnumripper** [comment]
keepass_valid() lives in keepass_common.h and is static, not even the warned variables are shared.  The reason for it to be in the header as opposed to keepass_common_plug.c is it behaves differently depending on macros KEEPASS_AES and KEEPASS_ARGON2.

**Comment by magnumripper** [comment]
This may be a data point:

No format specified:
```
Warning: detected hash type "KeePass", but the string is also recognized as "KeePass-opencl"
Use the "--format=KeePass-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 21 password hashes with 21 different salts (KeePass [AES/Argon2 256/256 AVX2])
Loaded hashes with cost 1 (t (rounds)) varying from 2 to 31578948
Loaded hashes with cost 2 (m) varying from 0 to 65536
Loaded hashes with cost 3 (p) varying from 0 to 3
Loaded hashes with cost 4 (KDF [0=Argon2d 2=Argon2id 3=AES]) varying from 0 to 3
```
The above should have a "KeePass-Argon2-opencl: AES hash(es) not supported, skipping." message. Looks like its valid() was never called?

--format=opencl,cpu
```
Warning: detected hash type "KeePass-opencl", but the string is also recognized as "KeePass"
Use the "--format=KeePass" option to force loading these as that type instead
KeePass-opencl: Argon2 hash(es) not supported, skipping.   <----   <----   <----
Warning: only loading hashes of type "KeePass-opencl", but also saw type "KeePass-Argon2-opencl"
Use the "--format=KeePass-Argon2-opencl" option to force loading hashes of that type instead
Warning: only loading hashes of type "KeePass-opencl", but also saw type "KeePass"
Use the "--format=KeePass" option to force loading hashes of that type instead
Using default input encoding: UTF-8
Loaded 15 password hashes with 15 different salts (KeePass-opencl [AES OpenCL])
Loaded hashes with cost 1 (t (rounds)) varying from 6000 to 31578948
```
In this case, we do see the "opposite" message.

**Comment by magnumripper** [comment]
Even stranger, if I give `-format=cpu,keepass-argon2-opencl`, it totally behaves like I had only said `-format=cpu`. None of the three warning messages emitted.

**Comment by magnumripper** [comment]
If I put an argon2 hash at the top of the samples file, it locks on that one (as expected)

-form:opencl,cpu
```
KeePass-opencl: Argon2 hash(es) not supported, skipping.
Warning: detected hash type "KeePass-Argon2-opencl", but the string is also recognized as "KeePass"
Use the "--format=KeePass" option to force loading these as that type instead
KeePass-Argon2-opencl: AES hash(es) not supported, skipping.
Warning: only loading hashes of type "KeePass-Argon2-opencl", but also saw type "KeePass-opencl"
Use the "--format=KeePass-opencl" option to force loading hashes of that type instead
Warning: only loading hashes of type "KeePass-Argon2-opencl", but also saw type "KeePass"
Use the "--format=KeePass" option to force loading hashes of that type instead
Using default input encoding: UTF-8
Loaded 4 password hashes with 4 different salts (KeePass-Argon2-opencl [BlaMka OpenCL])
Loaded hashes with cost 1 (t) varying from 2 to 34
Loaded hashes with cost 2 (m) varying from 16 to 65536
Loaded hashes with cost 3 (p) varying from 2 to 3
Loaded hashes with cost 4 (KDF [0=Argon2d 2=Argon2id]) varying from 0 to 2
```
In this case we have "locked" on a format, and _that format_ rejects other hashes in the file. In some other cases, we have locked on a format, and then there are lines that are accepted by it and some other format. This is tricky.

**Comment by magnumripper** [comment]
I think I see what's happening and I believe this is core behavior "as designed". I think the _"Warning: detected hash ... but"_ is only emitted with the first accepted line in mind. The following _"Warning: only loading .. but"_ are only emitted for lines rejected by the chosen format.

This was just never a problem until now, or perhaps it was but we missed it.

**Comment by solardiz** [comment]
> I believe this is core behavior "as designed". I think the _"Warning: detected hash ... but"_ is only emitted with the first accepted line in mind. The following _"Warning: only loading .. but"_ are only emitted for lines rejected by the chosen format.

Oh, you're probably right. The latter kind of warning wasn't meant to show all formats that would recognize those other lines not accepted by the detected format. It's just to tell you that something isn't being loaded. So for the first hash you do get a complete list of formats that could load it, then one format is chosen, and for further hashes you're only told they're not being loaded and are informed of one format that would load them.

I don't know if we want to change that.
