### ISSUE TITLE
Executable Stack

### ISSUE THREAD

**Issue by ghost** [openwall/john#5588]
>> We now have some programs that have executable stack regions
>
>Oh, indeed. We should have expected that when we let extra asm files into the tree.
>
>While we keep the `yasm` files at all, the proper fix would be to add the equivalent of these to those:
>
>```
>$ tail -3 src/x86.S
>#if defined(__ELF__) && defined(__linux__)
>.section .note.GNU-stack,"",@progbits
>#endif
>```
>
>... hoping that `yasm` does support specifying this in some way as well.
>
>This is also a reason for us to get rid of `yasm` usage sooner.
***

See also https://github.com/openwall/john-packages/pull/657#issuecomment-2504013982

**Comment by magnumripper** [comment]
Executable stack is fun and profit 😎 

I should focus on #4314, hopefully it's not too much work.

**Comment by magnumripper** [comment]
>While we keep the `yasm` files at all, the proper fix would be to add the equivalent of these to those:
>
>```
>$ tail -3 src/x86.S
>#if defined(__ELF__) && defined(__linux__)
>.section .note.GNU-stack,"",@progbits
>#endif
>```

@claudioandre-br can you check if the branch magnumripper/yasm-no-exec-stack fixes the problem? Right now I sit in a place lacking linux/yasm (and super doesn't seem to have yasm anywhere).

It adds this to the asm files:
```
%ifidn __OUTPUT_FORMAT__,elf
section .note.GNU-stack noalloc noexec nowrite progbits
%endif
%ifidn __OUTPUT_FORMAT__,elf32
section .note.GNU-stack noalloc noexec nowrite progbits
%endif
%ifidn __OUTPUT_FORMAT__,elf64
section .note.GNU-stack noalloc noexec nowrite progbits
%endif
```
I got that from https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart#Causes_of_executable_stack_markings and it says it's for nasm/yasm.

@solardiz does it look right? I'm not sure if/why noalloc and nowrite should be there.

**Comment by ghost** [comment]
Testing it!

**Comment by ghost** [comment]
It works (no files with executable stack was found):

```bash
$ john --test --format=o5logon
Will run 8 OpenMP threads
Benchmarking: o5logon, Oracle O5LOGON protocol [SHA1 AES 32/64]... (8xOMP) DONE
Many salts:	27787K c/s real, 3510K c/s virtual
Only one salt:	16269K c/s real, 2055K c/s virtual
```

Versus:
```
Will run 8 OpenMP threads
Benchmarking: o5logon, Oracle O5LOGON protocol [SHA1 AES 32/64]... (8xOMP) DONE
Many salts:	7684K c/s real, 1067K c/s virtual
Only one salt:	6053K c/s real, 849072 c/s virtual
```
