### ISSUE TITLE
Phrase recovery 

### ISSUE THREAD

**Issue by Bola730** [openwall/john#5592]
I want to recover the crypto account

**Comment by solardiz** [comment]
That's great, but this is our issue tracker and you haven't even asked a question.

**Comment by Bola730** [comment]
> That's great, but this is our issue tracker and you haven't even asked a question.

Will you help me do it

**Comment by solardiz** [comment]
> Will you help me do it

Probably not, and certainly not without any specifics from you.

In general, if you mean a 12+ word seed phrase, then we currently have no support for recovering those at all, and even if we did it would only be reasonable to do for a mostly-known seed phrase with only some little bits missing.

**Comment by doge2021** [comment]
> I want to recover the crypto account

can only brute force the correct seed words. it takes time. you can reach https://btc2doge.org/. they recovered my 386k doge in 2021.

**Comment by solardiz** [comment]
FWIW, almost all GitHub comments @doge2021 ever posted in 3+ years (to various issues they and others created in various orgs/repos) advertise the above btc2doge website. Chances are @doge2021 has some undisclosed incentive to search for related issues and post these ads.

> can only brute force the correct seed words

I assume you mean the seed phrase has to be known, and only the optional extra human-chosen seed word searched by a tool.

As I recall, btcrecover can also attempt to recover missing bits from a seed phrase, provided that the phrase is _almost_ entirely known and only some little detail is uncertain (e.g., illegible handwriting).
