### ISSUE TITLE
Consider adding -std=c99 globally

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#5595]
Currently (off the top of my head) the PRINCE mode and the new AES needs it. Perhaps we should just enable it globally. I don't care a lot but I think it would be nice.

**Comment by solardiz** [comment]
If we have the dependency anyway, including in non-optional and non-arch-specific code such as PRINCE, then yes we should enable this globally. However, ideally we shouldn't try to add this option unless we know the compiler recognizes it, which means gcc starting with a certain version or compatible. Edit: OTOH, if it's a version of gcc so old it doesn't recognize the option, then it's also too old to build the code anyway, so for gcc we should probably add this option unconditionally.

**Comment by magnumripper** [comment]
gcc 4.4 (only) does not allow anonymous structs/unions with `-std=c99`. According to [this](https://fa.openbsd.tech.narkive.com/kcvsYBoj/allow-anonymous-structs-unions-with-gcc-std-c99), "_after gcc 4.4 `--std=c89` and `--std=c99` starting allowing anonymous unions/structs when this behaviour was otherwise only accepted with `--std=gnu99`, `--std=c99 -fms-extensions` or omitting a `--std` option entirely._"

Using `--std=gnu99` works fine, when supported.

**Comment by magnumripper** [comment]
While investigating this I also found out that [strictly speaking](https://en.cppreference.com/w/c/language/bit_field), only `int` (plain, signed or unsigned) is allowed for bitfields. It's used with `size_t` in dyna_salt and needs to be larger than int. gcc seems to allow it regardless of `--std` option though, so I'm not changing it now.
