### ISSUE TITLE
Iteration count for eCryptfs?

### ISSUE THREAD

**Issue by frank-dittrich** [openwall/john#562]
I was almost removing the int iterations component from struct custom_salt in ecryptfs_fmt_plug.c, but wasn't sure whether the 2nd component, char unsigned salt[ECRYPTFS_SALT_SIZE + 1], would have trouble with alignment when I remove iterations.
So I briefly searched the source, and found:

```
#define ECRYPTFS_DEFAULT_NUM_HASH_ITERATIONS 65536
...
for (j = 1; j <= ECRYPTFS_DEFAULT_NUM_HASH_ITERATIONS; j++) {
```

So, the current implementation always uses 65536 iterations.
But the name ECRYPTFS_DEFAULT_NUM_HASH_ITERATIONS suggests that the iteration count is somehow configurable.

So, will the current format implementation fail if the iteration count is not the default iteration count, or is the "DEFAULT" misleading, and the value really is 65536?

```
```

**Comment by kholia** [comment]
http://seclists.org/oss-sec/2015/q1/498 (something to keep track of)
