### ISSUE TITLE
run against a PDF hash of a file with a known PW, with masking, format pdf-opencl not working correctly

### ISSUE THREAD

**Issue by illsk1lls** [openwall/john#5624]
I am trying to use masking to speed up PDF recovery. Testing on personal file with a known PW (circa 2008). I am not able to get opencl working correctly as the format type. If I enter the full password as the mask and enable opencl it will hit, but if I use anything short of the exact password it will not. Alternatively I if i do not use the pdf-opencl format when running john masking works fine and the password is found.

![Screenshot 2024-12-20 065427](https://github.com/user-attachments/assets/f8c69c6d-c41b-4944-928a-6bdbc86fc6e6)

Win11 22631 i7-9750h RTX2070(GameReady 561.09) 32GB Ram 
```
Version: 1.9.0-jumbo-1+bleeding-f8e9ca1eac 2024-11-19 01:45:50 +0100
Build: cygwin 64-bit x86_64 AVX2 AC OMP OPENCL
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
CPU fallback binary: john-avx-omp
OMP fallback binary: john-avx2
$JOHN is 
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 2147483648
SINGLE_BUF_MAX: 4294967295
Effective limit: Number of salts vs. SingleMaxBufferSize
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 12.4.0
OpenCL headers version: 1.2
Crypto library: OpenSSL
OpenSSL library version: 0300000f0
OpenSSL 3.0.15 3 Sep 2024
GMP library version: 6.3.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 1000
Using times(2) for timers, resolution 1 ms
HR timer: QueryPerformanceCounter(), resolution 100 ns
Total physical host memory: 32617 MiB
Available physical host memory: 27440 MiB
Terminal locale string: C.UTF-8
Parsed terminal locale: UTF-8
Cygwin version: 3.5.4-1.x86_64, 2024-08-25 16:52 UTC
```

**Comment by magnumripper** [comment]
Thanks for reporting. Much to my surprise, I can reproduce. I'm not sure what has happened or when, but I'm on it.

**Comment by magnumripper** [comment]
OK that was an embarrassing bug, not sure how it slipped through testing. Fixed now.

I don't know when there will be fresh windows binaries available but in the meantime (if you can't build your own) you can safely run the version you've got with the option `--mask-internal-target=0` and get better speed than the CPU format, although not optimal GPU speed.

**Comment by illsk1lls** [comment]
Thanks for the speedy bugfix. ;)
