### ISSUE TITLE
Excessive unrolling and buggy auto-tuning in gost94crypt-opencl, streebog256crypt-opencl, streebog512crypt-opencl

### ISSUE THREAD

**Issue by solardiz** [openwall/john#5626]
As discussed in #5533:
1. `#pragma unroll HASH_LOOPS` may take forever to build and produces excessive code size. This unroll should be dropped or at least reduced to 21. Anyway, instead of unrolling we could use one of the tricks we already use elsewhere. Like maintaining counter(s) that are reset to 0 upon reaching 3, 7, 21, or 42 (and use an offsets map like `md5crypt_long_fmt.c` does). Crazy unrolling is really not the way.
2. `LOOP_CALLS` has misplaced braces (and may better be called `LOOP_COUNT` for consistency with other formats).

**Comment by magnumripper** [comment]
Worst of all, that `LOOP_CALLS` parameter (even once corrected) was wrong as a parameter to autotune, leading to output like `loop: 0x2.263 ms` and causing excessive work sizes tried for no good. The macro was entirely dropped now.

Perhaps autotune should warn if it gets a zero from `ITERATIONS / HASHLOOPS`, so bugs like this don't go unnoticed.
