### ISSUE TITLE
Link error when enable cuda

### ISSUE THREAD

**Issue by rickyzhang82** [openwall/john#622]
I clone bleeding-jumbo. When linking john, I got the following errors:

/bin/ld: cuda_common.o: undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
/bin/ld: note: '__gxx_personality_v0@@CXXABI_1.3' is defined in DSO /lib64/libstdc++.so.6 so try adding it to the linker command line
/lib64/libstdc++.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

I'm using nvcc 6.0.1, Fedora 20, 3.14.3-200.fc20.x86_64

**Comment by josephdviviano** [comment]
I just had the exact same problem, ricky's solution fixed it (somehow).

**Comment by magnumripper** [comment]
Are you also using the legacy makefile? That is deprecated anyway.

**Comment by kholia** [comment]
@magnumripper one more reason to drop the legacy build system altogether (without any deprecation step)?

**Comment by josephdviviano** [comment]
I wasn't aware that I was using a legacy build system... I was following the `install_ubuntu` documentation.

**Comment by magnumripper** [comment]
@josephdviviano if you followed that, you probably wan't using the legacy system. The legacy stuff is doing something like `make -f Makefile.legacy` instead of the `./configure && make` dance.

**Comment by frank-dittrich** [comment]
We might want to enhance doc/INSTALL-UBUNTU.
For inexperienced users, we could mention that `git pull origin` can be used to update the local git repo.
And we should add `make -s distclean` before the `./configure`.

**Comment by magnumripper** [comment]
I'd rather not even mention Git commands at all but supply a tarball link as in `wget https://github.com/magnumripper/JohnTheRipper/tarball/bleeding-jumbo` instead.

**Comment by josephdviviano** [comment]
In that case I was using the up-to-date system and still had to do use rickyzhang82's fix.

**Comment by magnumripper** [comment]
Yes, that problem is separate (but once fixed, it will be in the ./configure script). I can't really fix it until I get the problem myself somewhere.

So are you actually using Ubuntu, or are you too running Fedora? Did you get CUDA from nvidia or as a distro package?

**Comment by josephdviviano** [comment]
I run Ubuntu.

I installed a version of CUDA directly from NVIDIAs website. I had to replace it with a distro package to get John working, if I recall. But maybe that step wasn't nessecary.

**Comment by magnumripper** [comment]
I have used various versions of Ubuntu with distro packages as well as with nvidia's packages but never had to add libstdc++. But the CUDA stuff has changed in other ways over time so I'm not very surprised if some versions need a tweak.

**Comment by josephdviviano** [comment]
If it helps at all I was using CUDA 6.5 dev before.

**Comment by hiboudev** [comment]
Hi,

I get this error on Ubuntu 16.04 64-bit, following the doc/INSTALL-UBUNTU and using "./configure --enable-cuda". 

```
cuda_cryptmd5.o:(.eh_frame+0xdb): undefined reference to `__gxx_personality_v0'
cuda_phpass.o:(.eh_frame+0x6b): undefined reference to `__gxx_personality_v0'
cuda_mscash2.o:(.eh_frame+0x11f): undefined reference to `__gxx_personality_v0'
cuda_rawsha256.o:(.eh_frame+0x8b): undefined reference to `__gxx_personality_v0'
cuda_rawsha224.o:(.eh_frame+0x8b): undefined reference to `__gxx_personality_v0'
cuda_mscash.o:(.eh_frame+0xbf): more undefined references to `__gxx_personality_v0' follow
cuda_wpapsk.o: In function `wpapsk_postprocess(int)':
tmpxft_000075c8_00000000-4_wpapsk.cudafe1.cpp:(.text+0x832): undefined reference to `prf_512(unsigned int*, unsigned char*, unsigned int*)'
tmpxft_000075c8_00000000-4_wpapsk.cudafe1.cpp:(.text+0x8de): undefined reference to `prf_512(unsigned int*, unsigned char*, unsigned int*)'
cuda_wpapsk.o:(.eh_frame+0x3bf): undefined reference to `__gxx_personality_v0'
cuda_pwsafe.o:(.eh_frame+0x6b): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
Makefile:1415: recipe for target '../run/john' failed
make[1]: *** [../run/john] Error 1
Makefile:186: recipe for target 'default' failed
make: *** [default] Error 2
```
Can you please explain how to fix it?

**Comment by claudioandre** [comment]
Have you tried to add -lstdc++ to LDFLAGS ? Which CUDA version are you using?

**Comment by magnumripper** [comment]
This was latest Git version? If not, try that. If it was, try reverting to d1bc6b59 and see if that works.

**Comment by hiboudev** [comment]
Yes, lastest Git Version. Cuda version is in Ubuntu 16.04 repository (7.5.18-0ubuntu1, I follow your Ubuntu guide), I tried to revert to 911c90e and get the same error, and I don't know how to add -lstdc++ to LDFLAGS.

**Comment by magnumripper** [comment]
You need to revert to commit **before** 911c90e which is normally written as `911c90e^` and in this case it ends up as d1bc6b5.

**Comment by hiboudev** [comment]
Thanks for the answers but I can't get rid of this error, here is the [full console output](http://dpaste.com/0NKEV0P).

**Comment by magnumripper** [comment]
I have no idea what could be wrong. I'll try to reproduce your problems using Ubuntu's CUDA packages (I think I'm using the ones from nvidia now).

On a side note, why do you want CUDA at all? It's deprecated and actually doesn't add squat. An OpenCL build has more formats and they perform way better.

**Comment by hiboudev** [comment]
I'm kinda newbie in this, so I'll try OpenCL if it performs faster. I aimed Cuda cause I successfully tested it with TensorFlow.

**Comment by yangl1996** [comment]
@hiboudev if you don't need to decrypt wpapsk you may just remove the line `wpapsk_postprocess(count);` from `src/cuda_wpapsk_fmt_plug.c`. Just to pass the compilation with minimum effort.

I encountered this problem on ubuntu 16.04 ppc64le with CUDA 8.0. Have to use CUDA because nvidia haven't got opencl support for its latest boards on ppc :(
