### ISSUE TITLE
Implement Cisco type 8 (sha256) and 9 (scrypt)

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#711]
Cisco type 9 is scrypt. I know nothing more but here's a sample (from CMIYC):
`$9$cvWdfQlRRDKq/U$VFTPha5VHTCbSgSUAo.nPoh50ZiXOw1zmljEjXkaq1g`
Plaintext is `123456`

Base64 charset is likely same as Cisco type 4.

**Comment by videgro** [comment]
I would like to inform you that I used the discussion in this issue to make a JAVA implementation of the Type 8 and Type 9 hash calculations. Thanks! 
See: https://github.com/videgro/cisco-password-hashes

**Comment by wifiwizardofoz** [comment]
Anyone here (or reading this) want to assist me in figuring this out in Python? I have a small script that is supposed to convert plain text to Cisco Type 9 (scrypt), but the password when entered on the Cisco switch doesn't work. I think it's the way I am handling the salt.
