### ISSUE TITLE
zsh tab-completion needs update

### ISSUE THREAD

**Issue by magnumripper** [openwall/john#765]
It lags behind a little. See for example
`git log --pretty=oneline d6dacd0 ../run/john.bash_completion`

@kost maybe you?

**Comment by solardiz** [comment]
Do we need custom zsh tab completions at all? With no maintainer, maybe it's best to drop this?

**Comment by magnumripper** [comment]
If so, should we drop the existing ridmentary completion or keep it?

**Comment by solardiz** [comment]
I think we don't need to track this any further - it isn't a task from our project, but is rather something people contribute or not. If anyone wants to improve zsh completions, they can. In fact, some maintenance was made in 915cfcc76f31d31f08ff93ade0662440aa3f3b1e and 26ec62e2c8429369e727fe0af4d190e84438cc6d.
