### ISSUE TITLE
Salted formats which don't report tunable costs even if they should... 

### ISSUE THREAD

**Issue by frank-dittrich** [openwall/john#880]
Not sure how to find out which formats still need to report tunable costs.
These must be formats with salt size > 0.
We have 204 CPU formats with salt size > 0 which don't yet report tunable costs:

```
(bleeding-jumbo)run $ ./john --list=format-details |cut -f 1,12,13|grep '\s$'|grep -v "\s0\s$" |wc -l
204
```

To find out which formats need to report tunable costs, we could compare test runs of individual hashes. Of ourse, this doesn't work for formats wich lack self tests for certain supported algorithms / varying cost parameters.
Out of the 204 formats, 9 just have a single self test:

```
 $ ./john --list=format-details |cut -f 1,6,12,13|grep '\s$'|grep -v "\s0\s$" |grep "\s[01]\s[0-9]"|cut -f 1,2
blackberry-es10 1
Clipperz    1
dmd5    1
fde 1
FormSpring  1
keystore    1
lp  1
LUKS    1
osc 1
```

But for the other formats, this might help:

```
$ ./john --list=format-tests |cut -f 4 |LC_ALL=C sort -u > passwords.test
Test scrypt 1: plaintext contains line feed
Test scrypt 1: ciphertext contains line feed or separator character '   '
(bleeding-jumbo)run $ wc -l passwords.test
537 passwords.test
$ ./john --incremental=upper --min-length=7 --max-length=7 --stdout | head -n 1000000 >> passwords.test 
Press 'q' or Ctrl-C to abort, almost any other key for status
$ ./unique passwords.u < passwords.test 
Total lines read 1000537 Unique lines written 1000537
```

Apparently, none of the self test passwords is among the first 1000000 candidates generated by my incremental mode run.
So we can just drop the top 537 lines, to get a suitable sample input file:

```
 $ tail -n +538 passwords.u > test.lst
```

And now let's collect the password hashes:

```
$ for f in `./john --list=format-details |cut -f 1,6,12,13|grep '\s$'|grep -v "\s0\s$" |grep -v "\s[01]\s[0-9]"|cut -f 1`; do ./john --format=$f --list=format-tests |cut -f 2,3| tr '\t' ':' > hashes.$f; done
```

Finally, a test run for each individual hash:

```
$ for f in $(./john --list=format-details |cut -f 1,6,12,13|grep '\s$'|grep -v "\s0\s$" |grep -v "\s[01]\s[0-9]"|cut -f 1); do echo "$f"; for u in $(seq 0 $(./john --format=$f --list=format-details |cut -f 6)); do echo "$f $u "; time ./john hashes.$f --format=$f --users=$u --wordlist=test.lst --session=$f-$u --pot=dummy.pot > stdout-$f-$u.txt 2> stderr-$f-$u.txt; done; done
descrypt
descrypt 0 

real    0m0.275s
user    0m1.043s
sys 0m0.016s
descrypt 1 

real    0m0.201s
user    0m0.967s
sys 0m0.011s
descrypt 2 

real    0m0.201s
user    0m0.970s
sys 0m0.009s
descrypt 3 

real    0m0.212s
user    0m0.970s
sys 0m0.011s
descrypt 4 

real    0m0.203s
user    0m0.984s
sys 0m0.008s
descrypt 5 

real    0m0.062s
user    0m0.058s
sys 0m0.004s
bsdicrypt
bsdicrypt 0 

real    0m2.471s
user    0m18.750s
sys 0m0.013s
bsdicrypt 1 

real    0m2.574s
user    0m19.715s
sys 0m0.007s
bsdicrypt 2 

real    0m2.638s
user    0m20.305s
sys 0m0.006s
bsdicrypt 3 

real    0m2.694s
user    0m20.691s
sys 0m0.015s
bsdicrypt 4 

real    0m2.840s
user    0m20.951s
sys 0m0.030s
bsdicrypt 5 

real    0m2.874s
user    0m21.296s
sys 0m0.026s
bsdicrypt 6 

real    0m2.798s
user    0m21.571s
sys 0m0.013s
bsdicrypt 7 

real    0m2.830s
user    0m21.766s
sys 0m0.014s
bsdicrypt 8 

real    0m2.946s
user    0m21.813s
sys 0m0.017s
bsdicrypt 9 

real    0m2.876s
user    0m22.155s
sys 0m0.015s
bsdicrypt 10 

real    0m2.960s
user    0m22.744s
sys 0m0.010s
bsdicrypt 11 

real    0m2.938s
user    0m22.504s
sys 0m0.013s
bsdicrypt 12 

real    0m0.079s
user    0m0.074s
sys 0m0.006s
...
```

Then, you can compare the run time of individual hashes (e.g., from the last line of the log files).
And if the ratio of fastest vs. slowest run justifies reporting a cost parameter, look into the format and find out what causes the different run time...

Some more scripting is required to automate this. (And may be we need to look into formats that lack some important self tests before doing this.)

(Of course, you'd need a system which doesn't throttle the CPU clock rate due to temperature, so my laptop isn't suitable.)

Not sure whether we should aim to complete this before the next jumbo release...

**Comment by solardiz** [comment]
Skimming the comments from December 2014, this was an attempt by Frank to automatically identify formats missing tunable costs through benchmarking them. magnum pointed out that for some formats performance varies with password length, which we shouldn't treat as a tunable cost.

Despite this issue's title, it doesn't appear to list specific examples of "formats which don't report tunable costs even if they should..."

We probably still do have formats that need tunable costs added, but the comments on this issue look pretty useless for that now. Closing.

**Comment by solardiz** [comment]
A more recent replacement for this issue is #3910.
