### ISSUE TITLE
Keep track of / handle renamed GPU formats in benchmark-unify

### ISSUE THREAD

**Issue by frank-dittrich** [openwall/john#907]
Otherwise, relbench will not be able to show performance improvements/regressions for such renamed formats

**Comment by magnumripper** [comment]
I guess we have plenty. nsldap and nsldaps are gone now in favor of raw/salted sha1.

**Comment by solardiz** [comment]
This issue refers to specific renames from a decade ago. We no longer care to benchmark against versions that old.
